BigString.cc File Reference
#include <limits.h>
#include `BigString.hh`
#include <new.h>
#include <ctype.h>
Defines
#define MAXStrRep_SIZE ((1 << (sizeof(_BIGSTRING_ALLOC) * CHAR_BIT - 1)) - 1)
#define MINStrRep_SIZE 16
#define MALLOC_MIN_OVERHEAD 4
#define RETURN(r) return r
#define RETURNS(r)
#define RETURN_OBJECT(TYPE, NAME) TYPE NAME;
Functions
StrRep * Salloc (StrRep *old, const char *src, _BIGSTRING_SIZE srclen, _BIGSTRING_SIZE newlen)
StrRep * Salloc_istream (StrRep *old, istream &src, _BIGSTRING_SIZE srclen, _BIGSTRING_SIZE newlen)
StrRep * Scopy (StrRep *old, const StrRep *s)
StrRep * Scat (StrRep *old, const char *s, _BIGSTRING_SIZE srclen, const char *t, _BIGSTRING_SIZE tlen)
StrRep * Scat (StrRep *old, const char *s, _BIGSTRING_SIZE srclen, const char *t, _BIGSTRING_SIZE tlen, const char *u, _BIGSTRING_SIZE ulen)
StrRep * Sprepend (StrRep *old, const char *t, _BIGSTRING_SIZE tlen)
_BIGSTRING_SIZE fcompare (const String &x, const String &y)
_BIGSTRING_SIZE compare (const String &x, const char *b)
_BIGSTRING_SIZE compare (const String &x, const String &y)
_BIGSTRING_SIZE compare (const String &x, const SubString &y)
_BIGSTRING_SIZE compare (const SubString &x, const String &y)
_BIGSTRING_SIZE compare (const SubString &x, const SubString &y)
_BIGSTRING_SIZE compare (const SubString &x, const char *b)
_BIGSTRING_SIZE split (const String &src, String results[], _BIGSTRING_SIZE n, const String &sep)
_BIGSTRING_SIZE split (const String &src, String results[], _BIGSTRING_SIZE n, const BigRegex &r)
String join (String src[], _BIGSTRING_SIZE n, const String &separator) RETURNS(x)
StrRep * Sreverse (const StrRep *src, StrRep *dest)
StrRep * Supcase (const StrRep *src, StrRep *dest)
StrRep * Sdowncase (const StrRep *src, StrRep *dest)
StrRep * Scapitalize (const StrRep *src, StrRep *dest)
String replicate (char c, _BIGSTRING_SIZE n)
String replicate (const String &y, _BIGSTRING_SIZE n)
String common_prefix (const String &x, const String &y, _BIGSTRING_SIZE startpos)
String common_suffix (const String &x, const String &y, _BIGSTRING_SIZE startpos)
istream & operator>> (istream &s, String &x)
_BIGSTRING_SIZE readline (istream &s, String &x, char terminator, int discard)
ostream & operator<< (ostream &s, const SubString &x)
Variables
StrRep _nilStrRep = { 0, 1, { 0 } }
String _nilString
Define Documentation
#define MALLOC_MIN_OVERHEAD 4
Definition at line 134 of file BigString.cc.
#define MAXStrRep_SIZE ((1 << (sizeof(_BIGSTRING_ALLOC) * CHAR_BIT - 1)) - 1)
Definition at line 130 of file BigString.cc.
#define MINStrRep_SIZE 16
Definition at line 131 of file BigString.cc.
#define RETURN(r) return r
Definition at line 1143 of file BigString.cc.
Referenced by join().
#define RETURN_OBJECT(TYPE, NAME) TYPE NAME;
Definition at line 1145 of file BigString.cc.
Referenced by join().
#define RETURNS(r)
Definition at line 1144 of file BigString.cc.
Function Documentation
String common_prefix (const String & x, const String & y, _BIGSTRING_SIZE startpos = 0)
Definition at line 1326 of file BigString.cc.
References _BIGSTRING_LENGTH, _BIGSTRING_SIZE, String::chars(), String::length(), String::rep, and Salloc().
Referenced by relurl().
1327 {
1328   String r;
1329   const char* xchars = x.chars();
1330   const char* ychars = y.chars();
1331   const char* xs = &(xchars[startpos]);
1332   const char* ss = xs;
1333   const char* topx = &(xchars[x.length()]);
1334   const char* ys = &(ychars[startpos]);
1335   const char* topy = &(ychars[y.length()]);
1336   _BIGSTRING_LENGTH l;
1337   for (l = 0; xs < topx && ys < topy && *xs++ == *ys++; ++l);
1338   r.rep = Salloc(r.rep, ss, l, l);
1339   return r;
1340 }
String common_suffix (const String & x, const String & y, _BIGSTRING_SIZE startpos = -1)
Definition at line 1342 of file BigString.cc.
References _BIGSTRING_LENGTH, _BIGSTRING_SIZE, String::chars(), String::length(), String::rep, and Salloc().
1343 {
1344   String r;
1345   const char* xchars = x.chars();
1346   const char* ychars = y.chars();
1347   const char* xs = &(xchars[x.length() + startpos]);
1348   const char* botx = xchars;
1349   const char* ys = &(ychars[y.length() + startpos]);
1350   const char* boty = ychars;
1351   _BIGSTRING_LENGTH l;
1352   for (l = 0; xs >= botx && ys >= boty && *xs == *ys ; --xs, --ys, ++l);
1353   r.rep = Salloc(r.rep, ++xs, l, l);
1354   return r;
1355 }
_BIGSTRING_SIZE compare (const SubString & x, const char * b)
Definition at line 481 of file BigString.cc.
References _BIGSTRING_SIZE, SubString::chars(), and SubString::length().
Referenced by operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
482 {
483   if (b == 0)
484     return x.length();
485   else
486   {
487     const char* a = x.chars();
488     _BIGSTRING_SIZE n = x.length();
489     int diff;
490     while (n-- > 0) if ((diff = *a++ - *b++) != 0) return diff;
491     return (*b == 0) ? 0 : -1;
492   }
493 }
_BIGSTRING_SIZE compare (const SubString & x, const SubString & y)
Definition at line 476 of file BigString.cc.
References _BIGSTRING_SIZE, SubString::chars(), and SubString::length().
477 {
478   return ncmp(x.chars(), x.length(), y.chars(), y.length());
479 }
_BIGSTRING_SIZE compare (const SubString & x, const String & y)
Definition at line 471 of file BigString.cc.
References _BIGSTRING_SIZE, String::chars(), SubString::chars(), String::length(), and SubString::length().
472 {
473   return ncmp(x.chars(), x.length(), y.chars(), y.length());
474 }
_BIGSTRING_SIZE compare (const String & x, const SubString & y)
Definition at line 466 of file BigString.cc.
References _BIGSTRING_SIZE, SubString::chars(), String::chars(), SubString::length(), and String::length().
467 {
468   return ncmp(x.chars(), x.length(), y.chars(), y.length());
469 }
_BIGSTRING_SIZE compare (const String & x, const String & y)
Definition at line 461 of file BigString.cc.
References _BIGSTRING_SIZE, and String::chars().
462 {
463   return scmp(x.chars(), y.chars());
464 }
_BIGSTRING_SIZE compare (const String & x, const char * b)
Definition at line 456 of file BigString.cc.
References _BIGSTRING_SIZE, and String::chars().
457 {
458   return scmp(x.chars(), b);
459 }
_BIGSTRING_SIZE fcompare (const String & x, const String & y)
Definition at line 428 of file BigString.cc.
References _BIGSTRING_SIZE, String::chars(), and String::length().
429 {
430   const char* a = x.chars();
431   const char* b = y.chars();
432   _BIGSTRING_SIZE al = x.length();
433   _BIGSTRING_SIZE bl = y.length();
434   _BIGSTRING_SIZE n = (al <= bl)? al : bl;
435   int diff = 0;
436   while (n-- > 0)
437   {
438     char ac = *a++;
439     char bc = *b++;
440     if ((diff = ac - bc) != 0)
441     {
442       if (ac >= 'a' && ac <= 'z')
443         ac = ac - 'a' + 'A';
444       if (bc >= 'a' && bc <= 'z')
445         bc = bc - 'a' + 'A';
446       if ((diff = ac - bc) != 0)
447         return diff;
448     }
449   }
450   return al - bl;
451 }
String join (String src[], _BIGSTRING_SIZE n, const String & separator)
Definition at line 1148 of file BigString.cc.
References _BIGSTRING_ITERATOR, _BIGSTRING_SIZE, String::chars(), String::length(), RETURN, and RETURN_OBJECT.
1149 {
1150   RETURN_OBJECT(String,x)
1151   String sep = separator;
1152   _BIGSTRING_SIZE xlen = 0;
1153   _BIGSTRING_ITERATOR i;
1154   for (i = 0; i < n; ++i)
1155     xlen += src[i].length();
1156   xlen += (n - 1) * sep.length();
1157 
1158   x.rep = Sresize (x.rep, xlen);
1159 
1160   _BIGSTRING_ITERATOR j = 0;
1161   
1162   for (i = 0; i < n - 1; ++i)
1163   {
1164     ncopy(src[i].chars(), &(x.rep->s[j]), src[i].length());
1165     j += src[i].length();
1166     ncopy(sep.chars(), &(x.rep->s[j]), sep.length());
1167     j += sep.length();
1168   }
1169   ncopy0(src[i].chars(), &(x.rep->s[j]), src[i].length());
1170   RETURN(x);
1171 }
ostream& operator<< (ostream & s, const SubString & x)
Definition at line 1415 of file BigString.cc.
References SubString::chars(), and SubString::length().
1416 { 
1417   const char* a = x.chars();
1418   const char* lasta = &(a[x.length()]);
1419   while (a < lasta)
1420     s.put(*a++);
1421   return(s);
1422 }
istream& operator>> (istream & s, String & x)
Definition at line 1361 of file BigString.cc.
References _BIGSTRING_ITERATOR, StrRep::len, String::rep, StrRep::s, and StrRep::sz.
1362 {
1363   if (!s.ipfx(0) || (!(s.flags() & ios::skipws) && !ws(s)))
1364   {
1365     s.clear(ios::failbit|s.rdstate()); // Redundant if using GNU iostreams.
1366     return s;
1367   }
1368   int ch;
1369   _BIGSTRING_ITERATOR i = 0;
1370   x.rep = Sresize(x.rep, 20);
1371   register streambuf *sb = s.rdbuf();
1372   while ((ch = sb->sbumpc()) != EOF)
1373   {
1374     if (isspace(ch))
1375       break;
1376     if (i >= x.rep->sz - 1)
1377       x.rep = Sresize(x.rep, i+1);
1378     x.rep->s[i++] = ch;
1379   }
1380   x.rep->s[i] = 0;
1381   x.rep->len = i;
1382   int new_state = s.rdstate();
1383   if (i == 0) new_state |= ios::failbit;
1384   if (ch == EOF) new_state |= ios::eofbit;
1385   s.clear(new_state);
1386   return s;
1387 }
_BIGSTRING_SIZE readline (istream & s, String & x, char terminator = '\n', int discard = 1)
Definition at line 1389 of file BigString.cc.
References _BIGSTRING_ITERATOR, _BIGSTRING_SIZE, StrRep::len, String::rep, StrRep::s, and StrRep::sz.
1390 {
1391   if (!s.ipfx(0))
1392     return 0;
1393   int ch;
1394   _BIGSTRING_ITERATOR i = 0;
1395   x.rep = Sresize(x.rep, 80);
1396   register streambuf *sb = s.rdbuf();
1397   while ((ch = sb->sbumpc()) != EOF)
1398   {
1399     if (ch != terminator || !discard)
1400     {
1401       if (i >= x.rep->sz - 1)
1402         x.rep = Sresize(x.rep, i+1);
1403       x.rep->s[i++] = ch;
1404     }
1405     if (ch == terminator)
1406       break;
1407   }
1408   x.rep->s[i] = 0;
1409   x.rep->len = i;
1410   if (ch == EOF) s.clear(ios::eofbit|s.rdstate());
1411   return i;
1412 }
String replicate (const String & y, _BIGSTRING_SIZE n)
Definition at line 1311 of file BigString.cc.
References _BIGSTRING_SIZE, String::chars(), String::length(), String::rep, and StrRep::s.
Referenced by search_cmd(), DIL_Visualize_with_FORM_Tabs::Visualize_Element(), DIL_Visualize_with_HTML_Tabs::Visualize_Element(), DIL_Visualize_with_Tabs::Visualize_Element(), DIL_Visualize_with_FORM_Tabs::Visualize_NotShown(), DIL_Visualize_with_HTML_Tabs::Visualize_NotShown(), and DIL_Visualize_with_Tabs::Visualize_NotShown().
1312 {
1313   String w;
1314   _BIGSTRING_SIZE len = y.length();
1315   w.rep = Sresize(w.rep, n * len);
1316   char* p = w.rep->s;
1317   while (n-- > 0)
1318   {
1319     ncopy(y.chars(), p, len);
1320     p += len;
1321   }
1322   *p = 0;
1323   return w;
1324 }
String replicate (char c, _BIGSTRING_SIZE n)
Definition at line 1301 of file BigString.cc.
References _BIGSTRING_SIZE, String::rep, and StrRep::s.
1302 {
1303   String w;
1304   w.rep = Sresize(w.rep, n);
1305   char* p = w.rep->s;
1306   while (n-- > 0) *p++ = c;
1307   *p = 0;
1308   return w;
1309 }
StrRep* Salloc (StrRep * old, const char * src, _BIGSTRING_SIZE srclen, _BIGSTRING_SIZE newlen)
Definition at line 173 of file BigString.cc.
References _BIGSTRING_SIZE, StrRep::len, StrRep::s, and StrRep::sz.
Referenced by common_prefix(), common_suffix(), String::operator=(), Scapitalize(), Sdowncase(), split(), Sreverse(), String::String(), and Supcase().
174 {
175 #ifdef DEBUG_BIGSTRING
176 //bool _debugop;
177 //if (old) _debugop = old->debugop; else _debugop = true;
178 //if (old) old->debugop = false;
179 #endif
180   if (old == &_nilStrRep) old = 0;
181   if (srclen < 0) srclen = slen(src);
182   if (newlen < srclen) newlen = srclen;
183 #ifdef DEBUG_BIGSTRING
184 //if (_debugop) cerr << "[Salloc] srclen = " << srclen << ", newlen = " << newlen << '\n';
185 if (globaldebugop) cerr << "[Salloc] srclen = " << srclen << ", newlen = " << newlen << '\n';
186 #endif
187   StrRep* rep;
188   if (old == 0 || newlen > old->sz)
189     rep = Snew(newlen);
190   else
191     rep = old;
192 
193   rep->len = newlen;
194   ncopy0(src, rep->s, srclen);
195 
196   if (old != rep && old != 0) delete old;
197 
198 #ifdef DEBUG_BIGSTRING
199 //rep->debugop = _debugop;
200 #endif
201   return rep;
202 }
StrRep* Salloc_istream (StrRep * old, istream & src, _BIGSTRING_SIZE srclen, _BIGSTRING_SIZE newlen)
Definition at line 207 of file BigString.cc.
References _BIGSTRING_SIZE, StrRep::len, StrRep::s, and StrRep::sz.
Referenced by String::operator=().
208 {
209         if (!src) return old;
210         if (old == &_nilStrRep) old = 0;
211         if (srclen < 0) {
212                 src.seekg(0,ios::end);
213                 srclen = src.tellg();
214                 src.seekg(0);
215         }
216         if (newlen < srclen) newlen = srclen;
217         StrRep* rep;
218         if (old == 0 || newlen > old->sz) rep = Snew(newlen);
219         else rep = old;
220         rep->len = newlen;
221         ncopy0_istream(src, rep->s, srclen);
222         if (old != rep && old != 0) delete old;
223         return rep;
224 }
StrRep* Scapitalize (const StrRep * src, StrRep * dest)
Definition at line 1218 of file BigString.cc.
References _BIGSTRING_SIZE, StrRep::len, StrRep::s, and Salloc().
Referenced by capitalize(), and String::capitalize().
1219 {
1220   _BIGSTRING_SIZE n = src->len;
1221   if (src != dest) dest = Salloc(dest, src->s, n, n);
1222 
1223   char* p = dest->s;
1224   char* e = &(p[n]);
1225   for (; p < e; ++p)
1226   {
1227     int at_word;
1228     if (at_word = islower(*p))
1229       *p = toupper(*p);
1230     else 
1231       at_word = isupper(*p) || isdigit(*p);
1232 
1233     if (at_word)
1234     {
1235       while (++p < e)
1236       {
1237         if (isupper(*p))
1238           *p = tolower(*p);
1239         /* A '\'' does not break a word, so that "Nathan's" stays
1240            "Nathan's" rather than turning into "Nathan'S". */
1241         else if (!islower(*p) && !isdigit(*p) && (*p != '\''))
1242           break;
1243       }
1244     }
1245   }
1246   return dest;
1247 }
StrRep* Scat (StrRep * old, const char * s, _BIGSTRING_SIZE srclen, const char * t, _BIGSTRING_SIZE tlen, const char * u, _BIGSTRING_SIZE ulen)
Definition at line 344 of file BigString.cc.
References _BIGSTRING_SIZE, StrRep::len, StrRep::s, and StrRep::sz.
Referenced by cat().
346 {
347   if (old == &_nilStrRep) old = 0;
348   if (srclen < 0) srclen = slen(s);
349   if (tlen < 0) tlen = slen(t);
350   if (ulen < 0) ulen = slen(u);
351   _BIGSTRING_SIZE newlen = srclen + tlen + ulen;
352   StrRep* rep;
353   if (old == 0 || newlen > old->sz || 
354       (t >= old->s && t < &(old->s[old->len])) ||
355       (u >= old->s && u < &(old->s[old->len])))
356     rep = Snew(newlen);
357   else
358     rep = old;
359 
360   rep->len = newlen;
361 
362   ncopy(s, rep->s, srclen);
363   ncopy(t, &(rep->s[srclen]), tlen);
364   ncopy0(u, &(rep->s[srclen+tlen]), ulen);
365 
366   if (old != rep && old != 0) delete old;
367 
368   return rep;
369 }
StrRep* Scat (StrRep * old, const char * s, _BIGSTRING_SIZE srclen, const char * t, _BIGSTRING_SIZE tlen)
Definition at line 293 of file BigString.cc.
References _BIGSTRING_SIZE, StrRep::len, StrRep::s, and StrRep::sz.
294 {
295   if (old == &_nilStrRep) old = 0;
296   if (srclen < 0) srclen = slen(s);
297   if (tlen < 0) tlen = slen(t);
298   _BIGSTRING_SIZE newlen = srclen + tlen;
299   StrRep* rep;
300 
301   if (old == 0 || newlen > old->sz || 
302       (t >= old->s && t < &(old->s[old->len]))) // beware of aliasing
303     rep = Snew(newlen);
304   else
305     rep = old;
306 
307   rep->len = newlen;
308 
309   ncopy(s, rep->s, srclen);
310   ncopy0(t, &(rep->s[srclen]), tlen);
311 
312   if (old != rep && old != 0) delete old;
313 
314   return rep;
315 }
StrRep* Scopy (StrRep * old, const StrRep * s)
Definition at line 262 of file BigString.cc.
References _BIGSTRING_SIZE, StrRep::len, StrRep::s, and StrRep::sz.
Referenced by String::operator=().
263 {
264   if (old == &_nilStrRep) old = 0;
265   if (s == &_nilStrRep) s = 0;
266   if (old == s) 
267     return (old == 0)? &_nilStrRep : old;
268   else if (s == 0)
269   {
270     old->s[0] = 0;
271     old->len = 0;
272     return old;
273   }
274   else 
275   {
276     StrRep* rep;
277     _BIGSTRING_SIZE newlen = s->len;
278     if (old == 0 || newlen > old->sz)
279     {
280       if (old != 0) delete old;
281       rep = Snew(newlen);
282     }
283     else
284       rep = old;
285     rep->len = newlen;
286     ncopy0(s->s, rep->s, newlen);
287     return rep;
288   }
289 }
StrRep* Sdowncase (const StrRep * src, StrRep * dest)
Definition at line 1208 of file BigString.cc.
References _BIGSTRING_SIZE, StrRep::len, StrRep::s, and Salloc().
Referenced by downcase(), and String::downcase().
1209 {
1210   _BIGSTRING_SIZE n = src->len;
1211   if (src != dest) dest = Salloc(dest, src->s, n, n);
1212   char* p = dest->s;
1213   char* e = &(p[n]);
1214   for (; p < e; ++p) if (isupper(*p)) *p = tolower(*p);
1215   return dest;
1216 }
_BIGSTRING_SIZE split (const String & src, String results[], _BIGSTRING_SIZE n, const BigRegex & r)
Definition at line 1117 of file BigString.cc.
References _BIGSTRING_ITERATOR, _BIGSTRING_SIZE, String::chars(), String::length(), String::rep, Salloc(), and BigRegex::search().
1118 {
1119   String x = src;
1120   const char* s = x.chars();
1121   _BIGSTRING_SIZE sl = x.length();
1122   _BIGSTRING_ITERATOR i = 0;
1123   _BIGSTRING_SIZE pos = 0;
1124   _BIGSTRING_SIZE p, matchlen;
1125   while (i < n && pos < sl)
1126   {
1127     p = r.search(s, sl, matchlen, pos);
1128     if (p < 0)
1129       p = sl;
1130     results[i].rep = Salloc(results[i].rep, &(s[pos]), p - pos, p - pos);
1131     i++;
1132     pos = p + matchlen;
1133   }
1134   return i;
1135 }
_BIGSTRING_SIZE split (const String & src, String results[], _BIGSTRING_SIZE n, const String & sep)
Definition at line 1098 of file BigString.cc.
References _BIGSTRING_ITERATOR, _BIGSTRING_SIZE, String::chars(), String::length(), String::rep, Salloc(), and String::search().
1099 {
1100   String x = src;
1101   const char* s = x.chars();
1102   _BIGSTRING_SIZE sl = x.length();
1103   _BIGSTRING_ITERATOR i = 0;
1104   _BIGSTRING_SIZE pos = 0;
1105   while (i < n && pos < sl)
1106   {
1107     _BIGSTRING_SIZE p = x.search(pos, sl, sep.chars(), sep.length());
1108     if (p < 0)
1109       p = sl;
1110     results[i].rep = Salloc(results[i].rep, &(s[pos]), p - pos, p - pos);
1111     i++;
1112     pos = p + sep.length();
1113   }
1114   return i;
1115 }
StrRep* Sprepend (StrRep * old, const char * t, _BIGSTRING_SIZE tlen)
Definition at line 373 of file BigString.cc.
References _BIGSTRING_SIZE, StrRep::len, StrRep::s, and StrRep::sz.
Referenced by String::prepend().
374 {
375   char* s;
376   _BIGSTRING_SIZE srclen;
377   if (old == &_nilStrRep || old == 0)
378   {
379     s = 0; old = 0; srclen = 0;
380   }
381   else
382   {
383     s = old->s; srclen = old->len;
384   }
385   if (tlen < 0) tlen = slen(t);
386   _BIGSTRING_SIZE newlen = srclen + tlen;
387   StrRep* rep;
388   if (old == 0 || newlen > old->sz || 
389       (t >= old->s && t < &(old->s[old->len])))
390     rep = Snew(newlen);
391   else
392     rep = old;
393 
394   rep->len = newlen;
395 
396   revcopy(&(s[srclen]), &(rep->s[newlen]), srclen+1);
397   ncopy(t, rep->s, tlen);
398 
399   if (old != rep && old != 0) delete old;
400 
401   return rep;
402 }
StrRep* Sreverse (const StrRep * src, StrRep * dest)
Definition at line 1178 of file BigString.cc.
References _BIGSTRING_SIZE, StrRep::len, StrRep::s, and Salloc().
Referenced by reverse(), and String::reverse().
1179 {
1180   _BIGSTRING_SIZE n = src->len;
1181   if (src != dest)
1182     dest = Salloc(dest, src->s, n, n);
1183   if (n > 0)
1184   {
1185     char* a = dest->s;
1186     char* b = &(a[n - 1]);
1187     while (a < b)
1188     {
1189       char t = *a;
1190       *a++ = *b;
1191       *b-- = t;
1192     }
1193   }
1194   return dest;
1195 }
StrRep* Supcase (const StrRep * src, StrRep * dest)
Definition at line 1198 of file BigString.cc.
References _BIGSTRING_SIZE, StrRep::len, StrRep::s, and Salloc().
Referenced by upcase(), and String::upcase().
1199 {
1200   _BIGSTRING_SIZE n = src->len;
1201   if (src != dest) dest = Salloc(dest, src->s, n, n);
1202   char* p = dest->s;
1203   char* e = &(p[n]);
1204   for (; p < e; ++p) if (islower(*p)) *p = toupper(*p);
1205   return dest;
1206 }
Variable Documentation
String _nilString
Definition at line 57 of file BigString.cc.
StrRep _nilStrRep = { 0, 1, { 0 } }
Definition at line 55 of file BigString.cc.