BigString.hh File Reference
#include `BigRegex.hh`
#include <iostream.h>
#include <stdlib.h>
#include <stdio.h>
Compounds
class String
struct StrRep
class SubString
Defines
#define _BigString_hh 1
#define _String_hh 1
#define _G_NO_NRV
#define BIGSTRING_MAXIMIZE_SPEED
#define BIGSTRING_ISTREAM_INITIALIZATION
#define BIGSTRING_LONGLONG_INITIALIZATION
#define BIGSTRING_DOUBLE_INITIALIZATION
Typedefs
typedef unsigned int _BIGSTRING_ALLOC
typedef unsigned int _BIGSTRING_LENGTH
typedef int _BIGSTRING_SIZE
typedef int _BIGSTRING_ITERATOR
typedef int _BIGSTRING_REVERSE
typedef unsigned long _BIGSTRING_ALLOCMANIP
typedef String StrTmp
Functions
StrRep * Salloc (StrRep *old, const char *src, _BIGSTRING_SIZE srclen, _BIGSTRING_SIZE newlen)
StrRep * Scopy (StrRep *, const StrRep *)
StrRep * Scat (StrRep *, const char *, _BIGSTRING_SIZE, const char *, _BIGSTRING_SIZE)
StrRep * Scat (StrRep *, const char *, _BIGSTRING_SIZE, const char *, _BIGSTRING_SIZE, const char *, _BIGSTRING_SIZE)
StrRep * Sprepend (StrRep *, const char *, _BIGSTRING_SIZE)
StrRep * Sreverse (const StrRep *, StrRep *)
StrRep * Supcase (const StrRep *, StrRep *)
StrRep * Sdowncase (const StrRep *, StrRep *)
StrRep * Scapitalize (const StrRep *, StrRep *)
StrRep * Salloc_istream (StrRep *old, istream &src, _BIGSTRING_SIZE srclen, _BIGSTRING_SIZE newlen)
StrRep * Scat_istream (StrRep *, const char *, _BIGSTRING_SIZE, istream &, _BIGSTRING_SIZE)
_BIGSTRING_SIZE compare (const String &x, const String &y)
_BIGSTRING_SIZE compare (const String &x, const SubString &y)
_BIGSTRING_SIZE compare (const String &x, const char *y)
_BIGSTRING_SIZE compare (const SubString &x, const String &y)
_BIGSTRING_SIZE compare (const SubString &x, const SubString &y)
_BIGSTRING_SIZE compare (const SubString &x, const char *y)
_BIGSTRING_SIZE fcompare (const String &x, const String &y)
void cat (const String &x, const String &y, String &r)
void cat (const String &x, const SubString &y, String &r)
void cat (const String &x, const char *y, String &r)
void cat (const String &x, char y, String &r)
void cat (const SubString &x, const String &y, String &r)
void cat (const SubString &x, const SubString &y, String &r)
void cat (const SubString &x, const char *y, String &r)
void cat (const SubString &x, char y, String &r)
void cat (const char *x, const String &y, String &r)
void cat (const char *x, const SubString &y, String &r)
void cat (const char *x, const char *y, String &r)
void cat (const char *x, char y, String &r)
void cat (const String &a, const String &x, const String &y, String &r)
void cat (const String &a, const String &x, const SubString &y, String &r)
void cat (const String &a, const String &x, const char *y, String &r)
void cat (const String &a, const String &x, char y, String &r)
void cat (const String &a, const SubString &x, const String &y, String &r)
void cat (const String &a, const SubString &x, const SubString &y, String &r)
void cat (const String &a, const SubString &x, const char *y, String &r)
void cat (const String &a, const SubString &x, char y, String &r)
void cat (const String &a, const char *x, const String &y, String &r)
void cat (const String &a, const char *x, const SubString &y, String &r)
void cat (const String &a, const char *x, const char *y, String &r)
void cat (const String &a, const char *x, char y, String &r)
void cat (const char *a, const String &x, const String &y, String &r)
void cat (const char *a, const String &x, const SubString &y, String &r)
void cat (const char *a, const String &x, const char *y, String &r)
void cat (const char *a, const String &x, char y, String &r)
void cat (const char *a, const SubString &x, const String &y, String &r)
void cat (const char *a, const SubString &x, const SubString &y, String &r)
void cat (const char *a, const SubString &x, const char *y, String &r)
void cat (const char *a, const SubString &x, char y, String &r)
void cat (const char *a, const char *x, const String &y, String &r)
void cat (const char *a, const char *x, const SubString &y, String &r)
void cat (const char *a, const char *x, const char *y, String &r)
void cat (const char *a, const char *x, char y, String &r)
String operator+ (const String &x, const String &y)
String operator+ (const String &x, const SubString &y)
String operator+ (const String &x, const char *y)
String operator+ (const String &x, char y)
String operator+ (const SubString &x, const String &y)
String operator+ (const SubString &x, const SubString &y)
String operator+ (const SubString &x, const char *y)
String operator+ (const SubString &x, char y)
String operator+ (const char *x, const String &y)
String operator+ (char x, const String &y)
String operator+ (const char *x, const SubString &y)
String reverse (const String &x)
String upcase (const String &x)
String downcase (const String &x)
String capitalize (const String &x)
ostream & operator<< (ostream &s, const String &x)
int operator== (const String &x, const String &y)
int operator!= (const String &x, const String &y)
int operator> (const String &x, const String &y)
int operator>= (const String &x, const String &y)
int operator< (const String &x, const String &y)
int operator<= (const String &x, const String &y)
int operator== (const String &x, const SubString &y)
int operator!= (const String &x, const SubString &y)
int operator> (const String &x, const SubString &y)
int operator>= (const String &x, const SubString &y)
int operator< (const String &x, const SubString &y)
int operator<= (const String &x, const SubString &y)
int operator== (const String &x, const char *t)
int operator!= (const String &x, const char *t)
int operator> (const String &x, const char *t)
int operator>= (const String &x, const char *t)
int operator< (const String &x, const char *t)
int operator<= (const String &x, const char *t)
int operator== (const SubString &x, const String &y)
int operator!= (const SubString &x, const String &y)
int operator> (const SubString &x, const String &y)
int operator>= (const SubString &x, const String &y)
int operator< (const SubString &x, const String &y)
int operator<= (const SubString &x, const String &y)
int operator== (const SubString &x, const SubString &y)
int operator!= (const SubString &x, const SubString &y)
int operator> (const SubString &x, const SubString &y)
int operator>= (const SubString &x, const SubString &y)
int operator< (const SubString &x, const SubString &y)
int operator<= (const SubString &x, const SubString &y)
int operator== (const SubString &x, const char *t)
int operator!= (const SubString &x, const char *t)
int operator> (const SubString &x, const char *t)
int operator>= (const SubString &x, const char *t)
int operator< (const SubString &x, const char *t)
int operator<= (const SubString &x, const char *t)
Variables
StrRep _nilStrRep
String _nilString
Define Documentation
#define _BigString_hh 1
Definition at line 30 of file BigString.hh.
#define _G_NO_NRV
Definition at line 40 of file BigString.hh.
#define _String_hh 1
Definition at line 31 of file BigString.hh.
#define BIGSTRING_DOUBLE_INITIALIZATION
Definition at line 52 of file BigString.hh.
#define BIGSTRING_ISTREAM_INITIALIZATION
Definition at line 50 of file BigString.hh.
#define BIGSTRING_LONGLONG_INITIALIZATION
Definition at line 51 of file BigString.hh.
#define BIGSTRING_MAXIMIZE_SPEED
Definition at line 48 of file BigString.hh.
Typedef Documentation
typedef unsigned int _BIGSTRING_ALLOC
Definition at line 71 of file BigString.hh.
Referenced by String::allocation().
typedef unsigned long _BIGSTRING_ALLOCMANIP
Definition at line 76 of file BigString.hh.
typedef int _BIGSTRING_ITERATOR
Definition at line 74 of file BigString.hh.
Referenced by String::_gsub(), String::elem(), extract_paper_novelties(), join(), operator>>(), String::operator[](), readline(), and split().
typedef unsigned int _BIGSTRING_LENGTH
Definition at line 72 of file BigString.hh.
Referenced by String::alloc(), common_prefix(), common_suffix(), String::del(), String::freq(), SubString::length(), and String::length().
typedef int _BIGSTRING_REVERSE
Definition at line 75 of file BigString.hh.
typedef int _BIGSTRING_SIZE
Definition at line 73 of file BigString.hh.
Referenced by String::_gsub(), String::after(), String::alloc(), SubString::assign(), String::at(), String::before(), common_prefix(), common_suffix(), compare(), String::contains(), String::del(), fcompare(), String::freq(), String::from(), String::gsub(), String::index(), join(), String::match(), String::matches(), String::operator()(), readline(), replicate(), Salloc(), Salloc_istream(), Scapitalize(), Scat(), Scopy(), Sdowncase(), String::search(), split(), Sprepend(), Sreverse(), String::String(), SubString::SubString(), Supcase(), and String::through().
typedef String StrTmp
Definition at line 476 of file BigString.hh.
Function Documentation
String capitalize (const String & x) [inline]
Definition at line 1028 of file BigString.hh.
References String::rep, and Scapitalize().
Referenced by update_main_ALs().
1029 {
1030   String r; r.rep = Scapitalize(x.rep, r.rep); return r;
1031 }
void cat (const char * a, const char * x, char y, String & r) [inline]
Definition at line 809 of file BigString.hh.
References String::rep, and Scat().
Referenced by operator+().
810 {
811   r.rep = Scat(r.rep, a, -1, x, -1, &y, 1);
812 }
void cat (const char * a, const char * x, const char * y, String & r) [inline]
Definition at line 804 of file BigString.hh.
References String::rep, and Scat().
805 {
806   r.rep = Scat(r.rep, a, -1, x, -1, y, -1);
807 }
void cat (const char * a, const char * x, const SubString & y, String & r) [inline]
Definition at line 799 of file BigString.hh.
References SubString::chars(), SubString::length(), String::rep, and Scat().
800 {
801   r.rep = Scat(r.rep, a, -1, x, -1, y.chars(), y.length());
802 }
void cat (const char * a, const char * x, const String & y, String & r) [inline]
Definition at line 794 of file BigString.hh.
References String::chars(), String::length(), String::rep, and Scat().
795 {
796   r.rep = Scat(r.rep, a, -1, x, -1, y.chars(), y.length());
797 }
void cat (const char * a, const SubString & x, char y, String & r) [inline]
Definition at line 789 of file BigString.hh.
References SubString::chars(), SubString::length(), String::rep, and Scat().
790 {
791   r.rep = Scat(r.rep, a, -1, x.chars(), x.length(), &y, 1);
792 }
void cat (const char * a, const SubString & x, const char * y, String & r) [inline]
Definition at line 784 of file BigString.hh.
References SubString::chars(), SubString::length(), String::rep, and Scat().
785 {
786   r.rep = Scat(r.rep, a, -1, x.chars(), x.length(), y, -1);
787 }
void cat (const char * a, const SubString & x, const SubString & y, String & r) [inline]
Definition at line 779 of file BigString.hh.
References SubString::chars(), SubString::length(), String::rep, and Scat().
780 {
781   r.rep = Scat(r.rep, a, -1, x.chars(), x.length(), y.chars(), y.length());
782 }
void cat (const char * a, const SubString & x, const String & y, String & r) [inline]
Definition at line 774 of file BigString.hh.
References String::chars(), SubString::chars(), String::length(), SubString::length(), String::rep, and Scat().
775 {
776   r.rep = Scat(r.rep, a, -1, x.chars(), x.length(), y.chars(), y.length());
777 }
void cat (const char * a, const String & x, char y, String & r) [inline]
Definition at line 769 of file BigString.hh.
References String::chars(), String::length(), String::rep, and Scat().
770 {
771   r.rep = Scat(r.rep, a, -1, x.chars(), x.length(), &y, 1);
772 }
void cat (const char * a, const String & x, const char * y, String & r) [inline]
Definition at line 764 of file BigString.hh.
References String::chars(), String::length(), String::rep, and Scat().
765 {
766   r.rep = Scat(r.rep, a, -1, x.chars(), x.length(), y, -1);
767 }
void cat (const char * a, const String & x, const SubString & y, String & r) [inline]
Definition at line 759 of file BigString.hh.
References SubString::chars(), String::chars(), SubString::length(), String::length(), String::rep, and Scat().
760 {
761   r.rep = Scat(r.rep, a, -1, x.chars(), x.length(), y.chars(), y.length());
762 }
void cat (const char * a, const String & x, const String & y, String & r) [inline]
Definition at line 754 of file BigString.hh.
References String::chars(), String::length(), String::rep, and Scat().
755 {
756   r.rep = Scat(r.rep, a, -1, x.chars(), x.length(), y.chars(), y.length());
757 }
void cat (const String & a, const char * x, char y, String & r) [inline]
Definition at line 748 of file BigString.hh.
References String::chars(), String::length(), String::rep, and Scat().
749 {
750   r.rep = Scat(r.rep, a.chars(), a.length(), x, -1, &y, 1);
751 }
void cat (const String & a, const char * x, const char * y, String & r) [inline]
Definition at line 743 of file BigString.hh.
References String::chars(), String::length(), String::rep, and Scat().
744 {
745   r.rep = Scat(r.rep, a.chars(), a.length(), x, -1, y, -1);
746 }
void cat (const String & a, const char * x, const SubString & y, String & r) [inline]
Definition at line 738 of file BigString.hh.
References SubString::chars(), String::chars(), SubString::length(), String::length(), String::rep, and Scat().
739 {
740   r.rep = Scat(r.rep, a.chars(), a.length(), x, -1, y.chars(), y.length());
741 }
void cat (const String & a, const char * x, const String & y, String & r) [inline]
Definition at line 733 of file BigString.hh.
References String::chars(), String::length(), String::rep, and Scat().
734 {
735   r.rep = Scat(r.rep, a.chars(), a.length(), x, -1, y.chars(), y.length());
736 }
void cat (const String & a, const SubString & x, char y, String & r) [inline]
Definition at line 728 of file BigString.hh.
References SubString::chars(), String::chars(), SubString::length(), String::length(), String::rep, and Scat().
729 {
730   r.rep = Scat(r.rep, a.chars(), a.length(), x.chars(), x.length(), &y, 1);
731 }
void cat (const String & a, const SubString & x, const char * y, String & r) [inline]
Definition at line 723 of file BigString.hh.
References SubString::chars(), String::chars(), SubString::length(), String::length(), String::rep, and Scat().
724 {
725   r.rep = Scat(r.rep, a.chars(), a.length(), x.chars(), x.length(), y, -1);
726 }
void cat (const String & a, const SubString & x, const SubString & y, String & r) [inline]
Definition at line 718 of file BigString.hh.
References SubString::chars(), String::chars(), SubString::length(), String::length(), String::rep, and Scat().
719 {
720   r.rep = Scat(r.rep, a.chars(), a.length(), x.chars(), x.length(), y.chars(), y.length());
721 }
void cat (const String & a, const SubString & x, const String & y, String & r) [inline]
Definition at line 713 of file BigString.hh.
References SubString::chars(), String::chars(), SubString::length(), String::length(), String::rep, and Scat().
714 {
715   r.rep = Scat(r.rep, a.chars(), a.length(), x.chars(), x.length(), y.chars(), y.length());
716 }
void cat (const String & a, const String & x, char y, String & r) [inline]
Definition at line 708 of file BigString.hh.
References String::chars(), String::length(), String::rep, and Scat().
709 {
710   r.rep = Scat(r.rep, a.chars(), a.length(), x.chars(), x.length(), &y, 1);
711 }
void cat (const String & a, const String & x, const char * y, String & r) [inline]
Definition at line 703 of file BigString.hh.
References String::chars(), String::length(), String::rep, and Scat().
704 {
705   r.rep = Scat(r.rep, a.chars(), a.length(), x.chars(), x.length(), y, -1);
706 }
void cat (const String & a, const String & x, const SubString & y, String & r) [inline]
Definition at line 698 of file BigString.hh.
References SubString::chars(), String::chars(), SubString::length(), String::length(), String::rep, and Scat().
699 {
700   r.rep = Scat(r.rep, a.chars(), a.length(), x.chars(), x.length(), y.chars(), y.length());
701 }
void cat (const String & a, const String & x, const String & y, String & r) [inline]
Definition at line 693 of file BigString.hh.
References String::chars(), String::length(), String::rep, and Scat().
694 {
695   r.rep = Scat(r.rep, a.chars(), a.length(), x.chars(), x.length(), y.chars(), y.length());
696 }
void cat (const char * x, char y, String & r) [inline]
Definition at line 688 of file BigString.hh.
References String::rep, and Scat().
689 {
690   r.rep = Scat(r.rep, x, -1, &y, 1);
691 }
void cat (const char * x, const char * y, String & r) [inline]
Definition at line 683 of file BigString.hh.
References String::rep, and Scat().
684 {
685   r.rep = Scat(r.rep, x, -1, y, -1);
686 }
void cat (const char * x, const SubString & y, String & r) [inline]
Definition at line 678 of file BigString.hh.
References SubString::chars(), SubString::length(), String::rep, and Scat().
679 {
680   r.rep = Scat(r.rep, x, -1, y.chars(), y.length());
681 }
void cat (const char * x, const String & y, String & r) [inline]
Definition at line 673 of file BigString.hh.
References String::chars(), String::length(), String::rep, and Scat().
674 {
675   r.rep = Scat(r.rep, x, -1, y.chars(), y.length());
676 }
void cat (const SubString & x, char y, String & r) [inline]
Definition at line 668 of file BigString.hh.
References SubString::chars(), SubString::length(), String::rep, and Scat().
669 {
670   r.rep = Scat(r.rep, x.chars(), x.length(), &y, 1);
671 }
void cat (const SubString & x, const char * y, String & r) [inline]
Definition at line 663 of file BigString.hh.
References SubString::chars(), SubString::length(), String::rep, and Scat().
664 {
665   r.rep = Scat(r.rep, x.chars(), x.length(), y, -1);
666 }
void cat (const SubString & x, const SubString & y, String & r) [inline]
Definition at line 658 of file BigString.hh.
References SubString::chars(), SubString::length(), String::rep, and Scat().
659 {
660   r.rep = Scat(r.rep, x.chars(), x.length(), y.chars(), y.length());
661 }
void cat (const SubString & x, const String & y, String & r) [inline]
Definition at line 653 of file BigString.hh.
References String::chars(), SubString::chars(), String::length(), SubString::length(), String::rep, and Scat().
654 {
655   r.rep = Scat(r.rep, x.chars(), x.length(), y.chars(), y.length());
656 }
void cat (const String & x, char y, String & r) [inline]
Definition at line 648 of file BigString.hh.
References String::chars(), String::length(), String::rep, and Scat().
649 {
650   r.rep = Scat(r.rep, x.chars(), x.length(), &y, 1);
651 }
void cat (const String & x, const char * y, String & r) [inline]
Definition at line 643 of file BigString.hh.
References String::chars(), String::length(), String::rep, and Scat().
644 {
645   r.rep = Scat(r.rep, x.chars(), x.length(), y, -1);
646 }
void cat (const String & x, const SubString & y, String & r) [inline]
Definition at line 638 of file BigString.hh.
References SubString::chars(), String::chars(), SubString::length(), String::length(), String::rep, and Scat().
639 {
640   r.rep = Scat(r.rep, x.chars(), x.length(), y.chars(), y.length());
641 }
void cat (const String & x, const String & y, String & r) [inline]
Definition at line 633 of file BigString.hh.
References String::chars(), String::length(), String::rep, and Scat().
634 {
635   r.rep = Scat(r.rep, x.chars(), x.length(), y.chars(), y.length());
636 }
_BIGSTRING_SIZE compare (const SubString & x, const char * y)
Definition at line 481 of file BigString.cc.
References _BIGSTRING_SIZE, SubString::chars(), and SubString::length().
Referenced by operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
482 {
483   if (b == 0)
484     return x.length();
485   else
486   {
487     const char* a = x.chars();
488     _BIGSTRING_SIZE n = x.length();
489     int diff;
490     while (n-- > 0) if ((diff = *a++ - *b++) != 0) return diff;
491     return (*b == 0) ? 0 : -1;
492   }
493 }
_BIGSTRING_SIZE compare (const SubString & x, const SubString & y)
_BIGSTRING_SIZE compare (const SubString & x, const String & y)
_BIGSTRING_SIZE compare (const String & x, const char * y)
_BIGSTRING_SIZE compare (const String & x, const SubString & y)
_BIGSTRING_SIZE compare (const String & x, const String & y)
String downcase (const String & x) [inline]
Definition at line 1023 of file BigString.hh.
References String::rep, and Sdowncase().
1024 {
1025   String r; r.rep = Sdowncase(x.rep, r.rep); return r;
1026 }
_BIGSTRING_SIZE fcompare (const String & x, const String & y)
Definition at line 428 of file BigString.cc.
References _BIGSTRING_SIZE, String::chars(), and String::length().
429 {
430   const char* a = x.chars();
431   const char* b = y.chars();
432   _BIGSTRING_SIZE al = x.length();
433   _BIGSTRING_SIZE bl = y.length();
434   _BIGSTRING_SIZE n = (al <= bl)? al : bl;
435   int diff = 0;
436   while (n-- > 0)
437   {
438     char ac = *a++;
439     char bc = *b++;
440     if ((diff = ac - bc) != 0)
441     {
442       if (ac >= 'a' && ac <= 'z')
443         ac = ac - 'a' + 'A';
444       if (bc >= 'a' && bc <= 'z')
445         bc = bc - 'a' + 'A';
446       if ((diff = ac - bc) != 0)
447         return diff;
448     }
449   }
450   return al - bl;
451 }
int operator!= (const SubString & x, const char * t) [inline]
Definition at line 1423 of file BigString.hh.
References compare().
1424 {
1425   return compare(x, t) != 0;
1426 }
int operator!= (const SubString & x, const SubString & y) [inline]
Definition at line 1393 of file BigString.hh.
References compare().
1394 {
1395   return compare(x, y) != 0;
1396 }
int operator!= (const SubString & x, const String & y) [inline]
Definition at line 1363 of file BigString.hh.
References compare().
1364 {
1365   return compare(y, x) != 0;
1366 }
int operator!= (const String & x, const char * t) [inline]
Definition at line 1333 of file BigString.hh.
References compare().
1334 {
1335   return compare(x, t) != 0; 
1336 }
int operator!= (const String & x, const SubString & y) [inline]
Definition at line 1303 of file BigString.hh.
References compare().
1304 {
1305   return compare(x, y) != 0; 
1306 }
int operator!= (const String & x, const String & y) [inline]
Definition at line 1273 of file BigString.hh.
References compare().
1274 {
1275   return compare(x, y) != 0; 
1276 }
String operator+ (const char * x, const SubString & y) [inline]
Definition at line 1008 of file BigString.hh.
References cat().
1009 {
1010   String r; cat(x, y, r); return r;
1011 }
String operator+ (char x, const String & y) [inline]
Definition at line 996 of file BigString.hh.
References String::prepend().
997 {
998 //cout << "<*>" ;
999   String r;
1000   r = y;
1001 //for (char *tp = (char *) r.chars(); *tp!='\0'; tp++) cout << (*tp) << '{' << (int) (*tp) << '}';
1002 //cout << '\n';
1003   r.prepend(x);
1004 //for (char *tp = (char *) r.chars(); *tp!='\0'; tp++) cout << (*tp) << '{' << (int) (*tp) << '}';
1005   return r;
1006 }
String operator+ (const char * x, const String & y) [inline]
Definition at line 991 of file BigString.hh.
References cat().
992 {
993   String r; cat(x, y, r); return r;
994 }
String operator+ (const SubString & x, char y) [inline]
Definition at line 986 of file BigString.hh.
References cat().
987 {
988   String r; cat(x, y, r); return r;
989 }
String operator+ (const SubString & x, const char * y) [inline]
Definition at line 981 of file BigString.hh.
References cat().
982 {
983   String r; cat(x, y, r); return r;
984 }
String operator+ (const SubString & x, const SubString & y) [inline]
Definition at line 976 of file BigString.hh.
References cat().
977 {
978   String r; cat(x, y, r); return r;
979 }
String operator+ (const SubString & x, const String & y) [inline]
Definition at line 971 of file BigString.hh.
References cat().
972 {
973   String r; cat(x, y, r); return r;
974 }
String operator+ (const String & x, char y) [inline]
Definition at line 966 of file BigString.hh.
References cat().
967 {
968   String r; cat(x, y, r); return r;
969 }
String operator+ (const String & x, const char * y) [inline]
Definition at line 961 of file BigString.hh.
References cat().
962 {
963   String r; cat(x, y, r); return r;
964 }
String operator+ (const String & x, const SubString & y) [inline]
Definition at line 956 of file BigString.hh.
References cat().
957 {
958   String r; cat(x, y, r); return r;
959 }
String operator+ (const String & x, const String & y) [inline]
Definition at line 951 of file BigString.hh.
References cat().
952 {
953   String r;  cat(x, y, r);  return r;
954 }
int operator< (const SubString & x, const char * t) [inline]
Definition at line 1438 of file BigString.hh.
References compare().
1439 {
1440   return compare(x, t) < 0; 
1441 }
int operator< (const SubString & x, const SubString & y) [inline]
Definition at line 1408 of file BigString.hh.
References compare().
1409 {
1410   return compare(x, y) < 0;
1411 }
int operator< (const SubString & x, const String & y) [inline]
Definition at line 1378 of file BigString.hh.
References compare().
1379 {
1380   return compare(y, x) > 0;
1381 }
int operator< (const String & x, const char * t) [inline]
Definition at line 1348 of file BigString.hh.
References compare().
1349 {
1350   return compare(x, t) < 0; 
1351 }
int operator< (const String & x, const SubString & y) [inline]
Definition at line 1318 of file BigString.hh.
References compare().
1319 {
1320   return compare(x, y) < 0; 
1321 }
int operator< (const String & x, const String & y) [inline]
Definition at line 1288 of file BigString.hh.
References compare().
1289 {
1290   return compare(x, y) < 0; 
1291 }
ostream& operator<< (ostream & s, const String & x) [inline]
Definition at line 1261 of file BigString.hh.
References String::chars().
1262 {
1263    s << x.chars(); return s;
1264 }
int operator<= (const SubString & x, const char * t) [inline]
Definition at line 1443 of file BigString.hh.
References compare().
1444 {
1445   return compare(x, t) <= 0; 
1446 }
int operator<= (const SubString & x, const SubString & y) [inline]
Definition at line 1413 of file BigString.hh.
References compare().
1414 {
1415   return compare(x, y) <= 0;
1416 }
int operator<= (const SubString & x, const String & y) [inline]
Definition at line 1383 of file BigString.hh.
References compare().
1384 {
1385   return compare(y, x) >= 0;
1386 }
int operator<= (const String & x, const char * t) [inline]
Definition at line 1353 of file BigString.hh.
References compare().
1354 {
1355   return compare(x, t) <= 0; 
1356 }
int operator<= (const String & x, const SubString & y) [inline]
Definition at line 1323 of file BigString.hh.
References compare().
1324 {
1325   return compare(x, y) <= 0; 
1326 }
int operator<= (const String & x, const String & y) [inline]
Definition at line 1293 of file BigString.hh.
References compare().
1294 {
1295   return compare(x, y) <= 0; 
1296 }
int operator== (const SubString & x, const char * t) [inline]
Definition at line 1418 of file BigString.hh.
References compare().
1419 {
1420   return compare(x, t) == 0; 
1421 }
int operator== (const SubString & x, const SubString & y) [inline]
Definition at line 1388 of file BigString.hh.
References compare().
1389 {
1390   return compare(x, y) == 0; 
1391 }
int operator== (const SubString & x, const String & y) [inline]
Definition at line 1358 of file BigString.hh.
References compare().
1359 {
1360   return compare(y, x) == 0; 
1361 }
int operator== (const String & x, const char * t) [inline]
Definition at line 1328 of file BigString.hh.
References compare().
1329 {
1330   return compare(x, t) == 0; 
1331 }
int operator== (const String & x, const SubString & y) [inline]
Definition at line 1298 of file BigString.hh.
References compare().
1299 {
1300   return compare(x, y) == 0; 
1301 }
int operator== (const String & x, const String & y) [inline]
Definition at line 1268 of file BigString.hh.
References compare().
1269 {
1270   return compare(x, y) == 0; 
1271 }
int operator> (const SubString & x, const char * t) [inline]
Definition at line 1428 of file BigString.hh.
References compare().
1429 {
1430   return compare(x, t) > 0; 
1431 }
int operator> (const SubString & x, const SubString & y) [inline]
Definition at line 1398 of file BigString.hh.
References compare().
1399 {
1400   return compare(x, y) > 0;
1401 }
int operator> (const SubString & x, const String & y) [inline]
Definition at line 1368 of file BigString.hh.
References compare().
1369 {
1370   return compare(y, x) < 0;
1371 }
int operator> (const String & x, const char * t) [inline]
Definition at line 1338 of file BigString.hh.
References compare().
1339 {
1340   return compare(x, t) > 0; 
1341 }
int operator> (const String & x, const SubString & y) [inline]
Definition at line 1308 of file BigString.hh.
References compare().
1309 {
1310   return compare(x, y) > 0; 
1311 }
int operator> (const String & x, const String & y) [inline]
Definition at line 1278 of file BigString.hh.
References compare().
1279 {
1280   return compare(x, y) > 0; 
1281 }
int operator>= (const SubString & x, const char * t) [inline]
Definition at line 1433 of file BigString.hh.
References compare().
1434 {
1435   return compare(x, t) >= 0; 
1436 }
int operator>= (const SubString & x, const SubString & y) [inline]
Definition at line 1403 of file BigString.hh.
References compare().
1404 {
1405   return compare(x, y) >= 0;
1406 }
int operator>= (const SubString & x, const String & y) [inline]
Definition at line 1373 of file BigString.hh.
References compare().
1374 {
1375   return compare(y, x) <= 0;
1376 }
int operator>= (const String & x, const char * t) [inline]
Definition at line 1343 of file BigString.hh.
References compare().
1344 {
1345   return compare(x, t) >= 0; 
1346 }
int operator>= (const String & x, const SubString & y) [inline]
Definition at line 1313 of file BigString.hh.
References compare().
1314 {
1315   return compare(x, y) >= 0; 
1316 }
int operator>= (const String & x, const String & y) [inline]
Definition at line 1283 of file BigString.hh.
References compare().
1284 {
1285   return compare(x, y) >= 0; 
1286 }
String reverse (const String & x) [inline]
Definition at line 1013 of file BigString.hh.
References String::rep, and Sreverse().
1014 {
1015   String r; r.rep = Sreverse(x.rep, r.rep); return r;
1016 }
StrRep* Salloc (StrRep * old, const char * src, _BIGSTRING_SIZE srclen, _BIGSTRING_SIZE newlen)
Definition at line 173 of file BigString.cc.
References _BIGSTRING_SIZE, StrRep::len, StrRep::s, and StrRep::sz.
Referenced by common_prefix(), common_suffix(), String::operator=(), Scapitalize(), Sdowncase(), split(), Sreverse(), String::String(), and Supcase().
174 {
175 #ifdef DEBUG_BIGSTRING
176 //bool _debugop;
177 //if (old) _debugop = old->debugop; else _debugop = true;
178 //if (old) old->debugop = false;
179 #endif
180   if (old == &_nilStrRep) old = 0;
181   if (srclen < 0) srclen = slen(src);
182   if (newlen < srclen) newlen = srclen;
183 #ifdef DEBUG_BIGSTRING
184 //if (_debugop) cerr << "[Salloc] srclen = " << srclen << ", newlen = " << newlen << '\n';
185 if (globaldebugop) cerr << "[Salloc] srclen = " << srclen << ", newlen = " << newlen << '\n';
186 #endif
187   StrRep* rep;
188   if (old == 0 || newlen > old->sz)
189     rep = Snew(newlen);
190   else
191     rep = old;
192 
193   rep->len = newlen;
194   ncopy0(src, rep->s, srclen);
195 
196   if (old != rep && old != 0) delete old;
197 
198 #ifdef DEBUG_BIGSTRING
199 //rep->debugop = _debugop;
200 #endif
201   return rep;
202 }
StrRep* Salloc_istream (StrRep * old, istream & src, _BIGSTRING_SIZE srclen, _BIGSTRING_SIZE newlen)
Definition at line 207 of file BigString.cc.
References _BIGSTRING_SIZE, StrRep::len, StrRep::s, and StrRep::sz.
Referenced by String::operator=().
208 {
209         if (!src) return old;
210         if (old == &_nilStrRep) old = 0;
211         if (srclen < 0) {
212                 src.seekg(0,ios::end);
213                 srclen = src.tellg();
214                 src.seekg(0);
215         }
216         if (newlen < srclen) newlen = srclen;
217         StrRep* rep;
218         if (old == 0 || newlen > old->sz) rep = Snew(newlen);
219         else rep = old;
220         rep->len = newlen;
221         ncopy0_istream(src, rep->s, srclen);
222         if (old != rep && old != 0) delete old;
223         return rep;
224 }
StrRep* Scapitalize (const StrRep *, StrRep *)
Definition at line 1218 of file BigString.cc.
References _BIGSTRING_SIZE, StrRep::len, StrRep::s, and Salloc().
Referenced by String::capitalize(), and capitalize().
1219 {
1220   _BIGSTRING_SIZE n = src->len;
1221   if (src != dest) dest = Salloc(dest, src->s, n, n);
1222 
1223   char* p = dest->s;
1224   char* e = &(p[n]);
1225   for (; p < e; ++p)
1226   {
1227     int at_word;
1228     if (at_word = islower(*p))
1229       *p = toupper(*p);
1230     else 
1231       at_word = isupper(*p) || isdigit(*p);
1232 
1233     if (at_word)
1234     {
1235       while (++p < e)
1236       {
1237         if (isupper(*p))
1238           *p = tolower(*p);
1239         /* A '\'' does not break a word, so that "Nathan's" stays
1240            "Nathan's" rather than turning into "Nathan'S". */
1241         else if (!islower(*p) && !isdigit(*p) && (*p != '\''))
1242           break;
1243       }
1244     }
1245   }
1246   return dest;
1247 }
StrRep* Scat (StrRep *, const char *, _BIGSTRING_SIZE, const char *, _BIGSTRING_SIZE, const char *, _BIGSTRING_SIZE)
Definition at line 344 of file BigString.cc.
References _BIGSTRING_SIZE, StrRep::len, StrRep::s, and StrRep::sz.
Referenced by cat().
346 {
347   if (old == &_nilStrRep) old = 0;
348   if (srclen < 0) srclen = slen(s);
349   if (tlen < 0) tlen = slen(t);
350   if (ulen < 0) ulen = slen(u);
351   _BIGSTRING_SIZE newlen = srclen + tlen + ulen;
352   StrRep* rep;
353   if (old == 0 || newlen > old->sz || 
354       (t >= old->s && t < &(old->s[old->len])) ||
355       (u >= old->s && u < &(old->s[old->len])))
356     rep = Snew(newlen);
357   else
358     rep = old;
359 
360   rep->len = newlen;
361 
362   ncopy(s, rep->s, srclen);
363   ncopy(t, &(rep->s[srclen]), tlen);
364   ncopy0(u, &(rep->s[srclen+tlen]), ulen);
365 
366   if (old != rep && old != 0) delete old;
367 
368   return rep;
369 }
StrRep* Scat (StrRep *, const char *, _BIGSTRING_SIZE, const char *, _BIGSTRING_SIZE)
StrRep* Scat_istream (StrRep *, const char *, _BIGSTRING_SIZE, istream &, _BIGSTRING_SIZE)
StrRep* Scopy (StrRep *, const StrRep *)
Definition at line 262 of file BigString.cc.
References _BIGSTRING_SIZE, StrRep::len, StrRep::s, and StrRep::sz.
Referenced by String::operator=().
263 {
264   if (old == &_nilStrRep) old = 0;
265   if (s == &_nilStrRep) s = 0;
266   if (old == s) 
267     return (old == 0)? &_nilStrRep : old;
268   else if (s == 0)
269   {
270     old->s[0] = 0;
271     old->len = 0;
272     return old;
273   }
274   else 
275   {
276     StrRep* rep;
277     _BIGSTRING_SIZE newlen = s->len;
278     if (old == 0 || newlen > old->sz)
279     {
280       if (old != 0) delete old;
281       rep = Snew(newlen);
282     }
283     else
284       rep = old;
285     rep->len = newlen;
286     ncopy0(s->s, rep->s, newlen);
287     return rep;
288   }
289 }
StrRep* Sdowncase (const StrRep *, StrRep *)
Definition at line 1208 of file BigString.cc.
References _BIGSTRING_SIZE, StrRep::len, StrRep::s, and Salloc().
Referenced by String::downcase(), and downcase().
1209 {
1210   _BIGSTRING_SIZE n = src->len;
1211   if (src != dest) dest = Salloc(dest, src->s, n, n);
1212   char* p = dest->s;
1213   char* e = &(p[n]);
1214   for (; p < e; ++p) if (isupper(*p)) *p = tolower(*p);
1215   return dest;
1216 }
StrRep* Sprepend (StrRep *, const char *, _BIGSTRING_SIZE)
Definition at line 373 of file BigString.cc.
References _BIGSTRING_SIZE, StrRep::len, StrRep::s, and StrRep::sz.
Referenced by String::prepend().
374 {
375   char* s;
376   _BIGSTRING_SIZE srclen;
377   if (old == &_nilStrRep || old == 0)
378   {
379     s = 0; old = 0; srclen = 0;
380   }
381   else
382   {
383     s = old->s; srclen = old->len;
384   }
385   if (tlen < 0) tlen = slen(t);
386   _BIGSTRING_SIZE newlen = srclen + tlen;
387   StrRep* rep;
388   if (old == 0 || newlen > old->sz || 
389       (t >= old->s && t < &(old->s[old->len])))
390     rep = Snew(newlen);
391   else
392     rep = old;
393 
394   rep->len = newlen;
395 
396   revcopy(&(s[srclen]), &(rep->s[newlen]), srclen+1);
397   ncopy(t, rep->s, tlen);
398 
399   if (old != rep && old != 0) delete old;
400 
401   return rep;
402 }
StrRep* Sreverse (const StrRep *, StrRep *)
Definition at line 1178 of file BigString.cc.
References _BIGSTRING_SIZE, StrRep::len, StrRep::s, and Salloc().
Referenced by String::reverse(), and reverse().
1179 {
1180   _BIGSTRING_SIZE n = src->len;
1181   if (src != dest)
1182     dest = Salloc(dest, src->s, n, n);
1183   if (n > 0)
1184   {
1185     char* a = dest->s;
1186     char* b = &(a[n - 1]);
1187     while (a < b)
1188     {
1189       char t = *a;
1190       *a++ = *b;
1191       *b-- = t;
1192     }
1193   }
1194   return dest;
1195 }
StrRep* Supcase (const StrRep *, StrRep *)
Definition at line 1198 of file BigString.cc.
References _BIGSTRING_SIZE, StrRep::len, StrRep::s, and Salloc().
Referenced by String::upcase(), and upcase().
1199 {
1200   _BIGSTRING_SIZE n = src->len;
1201   if (src != dest) dest = Salloc(dest, src->s, n, n);
1202   char* p = dest->s;
1203   char* e = &(p[n]);
1204   for (; p < e; ++p) if (islower(*p)) *p = toupper(*p);
1205   return dest;
1206 }
String upcase (const String & x) [inline]
Definition at line 1018 of file BigString.hh.
References String::rep, and Supcase().
1019 {
1020   String r; r.rep = Supcase(x.rep, r.rep); return r;
1021 }
Variable Documentation
String _nilString
Definition at line 489 of file BigString.hh.
StrRep _nilStrRep
Definition at line 488 of file BigString.hh.