DIL_Visualize Class Reference
#include <dil2al.hh>
Public Methods
DIL_Visualize (DIL_Hierarchy_Level_Data *ld=NULL)
virtual void Initialize ()=NULL
virtual void Attach_Level_Data (DIL_Hierarchy_Level_Data &ld)
virtual void Detach_Level_Data ()
virtual DIL_Hierarchy_Level_Data * Level_Data ()
virtual void Visualize_Element (DIL_entry *de, int depth)=NULL
virtual void Visualize_NotShown (int numdependencies, int depth)=NULL
virtual String Output ()=NULL
virtual double get_cumlikelihood ()
virtual void set_cumlikelihood (double cumlike)
Public Attributes
PLLRoot< DIL_Hierarchy_Level_Data > ldroot
Protected Attributes
double cumlikelihood
DIL_Hierarchy_Level_Data * leveldata
Constructor & Destructor Documentation
DIL_Visualize::DIL_Visualize (DIL_Hierarchy_Level_Data * ld = NULL) [inline]
Definition at line 745 of file dil2al.hh.
References cumlikelihood.
745 : cumlikelihood(0.0), leveldata(ld) {}
Member Function Documentation
virtual void DIL_Visualize::Attach_Level_Data (DIL_Hierarchy_Level_Data & ld) [inline, virtual]
Definition at line 750 of file dil2al.hh.
Referenced by Show_DIL_Hierarchy().
750 { leveldata = &ld; }
virtual void DIL_Visualize::Detach_Level_Data () [inline, virtual]
Definition at line 751 of file dil2al.hh.
Referenced by Show_DIL_Hierarchy().
751 { leveldata = NULL; }
virtual double DIL_Visualize::get_cumlikelihood () [inline, virtual]
Definition at line 756 of file dil2al.hh.
References cumlikelihood.
Referenced by Show_DIL_Hierarchy().
756 { return cumlikelihood; }
virtual void DIL_Visualize::Initialize () [virtual]
Reimplemented in DIL_Visualize_with_Tabs (p.), DIL_Visualize_with_HTML_Tabs (p.), and DIL_Visualize_with_FORM_Tabs (p.).
virtual DIL_Hierarchy_Level_Data* DIL_Visualize::Level_Data () [inline, virtual]
Definition at line 752 of file dil2al.hh.
Referenced by DIL_Visualize_with_FORM_Tabs::Visualize_Element(), DIL_Visualize_with_FORM_Tabs::Visualize_NotShown(), and DIL_Visualize_with_FORM_Tabs::Visualize_Plan_Entry().
752 { return leveldata;  }
virtual String DIL_Visualize::Output () [virtual]
Reimplemented in DIL_Visualize_with_Tabs (p.), DIL_Visualize_with_HTML_Tabs (p.), and DIL_Visualize_with_FORM_Tabs (p.).
virtual void DIL_Visualize::set_cumlikelihood (double cumlike) [inline, virtual]
Definition at line 757 of file dil2al.hh.
References cumlikelihood.
Referenced by Show_DIL_Hierarchy().
757 { cumlikelihood=cumlike; }
virtual void DIL_Visualize::Visualize_Element (DIL_entry * de, int depth) [virtual]
Reimplemented in DIL_Visualize_with_Tabs (p.), DIL_Visualize_with_HTML_Tabs (p.), and DIL_Visualize_with_FORM_Tabs (p.).
Referenced by Show_DIL_Hierarchy().
virtual void DIL_Visualize::Visualize_NotShown (int numdependencies, int depth) [virtual]
Reimplemented in DIL_Visualize_with_Tabs (p.), DIL_Visualize_with_HTML_Tabs (p.), and DIL_Visualize_with_FORM_Tabs (p.).
Referenced by Show_DIL_Hierarchy().
Member Data Documentation
double DIL_Visualize::cumlikelihood [protected]
Definition at line 742 of file dil2al.hh.
Referenced by DIL_Visualize(), get_cumlikelihood(), set_cumlikelihood(), DIL_Visualize_with_FORM_Tabs::Visualize_Element(), and DIL_Visualize_with_FORM_Tabs::Visualize_Plan_Entry().
PLLRoot<DIL_Hierarchy_Level_Data> DIL_Visualize::ldroot
Definition at line 748 of file dil2al.hh.
Referenced by Show_DIL_Hierarchy().
DIL_Hierarchy_Level_Data* DIL_Visualize::leveldata [protected]
Definition at line 743 of file dil2al.hh.
The documentation for this class was generated from the following file:
dil2al.hh