PLLType< PLLType > Class Template Reference
#include <templates.defines.hh>
Public Methods
PLLType ()
PLLRoot_ PLLType * Next ()
PLLType * Prev ()
PLLType * head ()
PLLType * tail ()
PLLType * el (int n)
PLLType * seek_head ()
PLLType * seek_tail ()
int length ()
int fulllength ()
bool unlink_before (PLLRoot_##PLLType &succ)
bool unlink_after (PLLRoot_##PLLType &pred)
PLLType * remove ()
~PLLRoot_ PLLRoot_ PLLType * head ()
PLLType * tail ()
PLLType * el (int n)
PLLType * operator[] (int n)
int length ()
void update ()
bool link_before (PLLRoot_##PLLType *succ)
bool link_before (PLLType *succ)
bool link_after (PLLRoot_##PLLType *pred)
bool link_after (PLLType *pred)
bool insert_after (PLLType *pred, PLLType *inshead)
bool insert_after (int n, PLLType *inshead)
bool insert_before (PLLType *succ, PLLType *inshead)
bool insert_before (int n, PLLType *inshead)
Protected Methods
void set_root (PLLType *h)
Protected Attributes
PLLRoot_ PLLType * pllnext
PLLRoot_ PLLType * pllprev
PLLType * pllhead
PLLType * plltail
template<class PLLType> class PLLType< PLLType >
Constructor & Destructor Documentation
template<class PLLType> PLLType< PLLType >::PLLType () [inline]
Definition at line 57 of file templates.defines.hh.
57 : pllroot(NULL), pllnext(NULL), pllprev(NULL) {} 
Member Function Documentation
template<class PLLType> PLLType* PLLType< PLLType >::el (int n) [inline]
Definition at line 83 of file templates.defines.hh.
References PLLType< PLLType >::el().
83 { if (pllhead) return pllhead->el(n); return NULL; } 
template<class PLLType> PLLType* PLLType< PLLType >::el (int n) [inline]
Referenced by PLLRoot< DIL_entry_Pointer >::el(), and PLLType< PLLType >::el().
template<class PLLType> int PLLType< PLLType >::fulllength () [inline]
template<class PLLType> ~PLLRoot_ PLLRoot_ PLLType* PLLType< PLLType >::head () [inline]
Definition at line 81 of file templates.defines.hh.
81 { return pllhead; } 
template<class PLLType> PLLType* PLLType< PLLType >::head () [inline]
Definition at line 61 of file templates.defines.hh.
Referenced by if().
61 { return pllroot->head(); } 
template<class PLLType> bool PLLType< PLLType >::insert_after (int n, PLLType< PLLType > * inshead) [inline]
template<class PLLType> bool PLLType< PLLType >::insert_after (PLLType< PLLType > * pred, PLLType< PLLType > * inshead) [inline]
template<class PLLType> bool PLLType< PLLType >::insert_before (int n, PLLType< PLLType > * inshead) [inline]
template<class PLLType> bool PLLType< PLLType >::insert_before (PLLType< PLLType > * succ, PLLType< PLLType > * inshead) [inline]
template<class PLLType> int PLLType< PLLType >::length () [inline]
Definition at line 85 of file templates.defines.hh.
References PLLType< PLLType >::length().
85 { if (pllhead) return pllhead->length(); return 0; } 
template<class PLLType> int PLLType< PLLType >::length () [inline]
Referenced by PLLHandle< PLLType >::fulllength(), PLLRoot< DIL_entry_Pointer >::length(), PLLType< PLLType >::length(), and PLLHandle< PLLType >::length().
template<class PLLType> bool PLLType< PLLType >::link_after (PLLType< PLLType > * pred) [inline]
template<class PLLType> bool PLLType< PLLType >::link_after (PLLRoot_##PLLType< PLLType > * pred) [inline]
template<class PLLType> bool PLLType< PLLType >::link_before (PLLType< PLLType > * succ) [inline]
template<class PLLType> bool PLLType< PLLType >::link_before (PLLRoot_##PLLType< PLLType > * succ) [inline]
template<class PLLType> PLLRoot_ PLLType* PLLType< PLLType >::Next () [inline]
Definition at line 59 of file templates.defines.hh.
Referenced by PLLRoot< PLLType >::set_root().
59 { return pllnext; } 
template<class PLLType> PLLType* PLLType< PLLType >::operator[] (int n) [inline]
Definition at line 84 of file templates.defines.hh.
84 { return el(n); } 
template<class PLLType> PLLType* PLLType< PLLType >::Prev () [inline]
Definition at line 60 of file templates.defines.hh.
60 { return pllprev; } 
template<class PLLType> PLLType* PLLType< PLLType >::remove () [inline]
template<class PLLType> PLLType* PLLType< PLLType >::seek_head () [inline]
template<class PLLType> PLLType* PLLType< PLLType >::seek_tail () [inline]
template<class PLLType> void PLLType< PLLType >::set_root (PLLType< PLLType > * h) [inline, protected]
template<class PLLType> PLLType* PLLType< PLLType >::tail () [inline]
Definition at line 82 of file templates.defines.hh.
82 { return plltail; } 
template<class PLLType> PLLType* PLLType< PLLType >::tail () [inline]
Definition at line 62 of file templates.defines.hh.
Referenced by if().
62 { return pllroot->tail(); } 
template<class PLLType> bool PLLType< PLLType >::unlink_after (PLLRoot_##PLLType< PLLType > & pred) [inline]
Referenced by PLLRoot< PLLType >::insert_after().
template<class PLLType> bool PLLType< PLLType >::unlink_before (PLLRoot_##PLLType< PLLType > & succ) [inline]
Referenced by PLLRoot< PLLType >::insert_before().
template<class PLLType> void PLLType< PLLType >::update () [inline]
Member Data Documentation
template<class PLLType> PLLType* PLLType< PLLType >::pllhead [protected]
Definition at line 75 of file templates.defines.hh.
Referenced by if().
template<class PLLType> PLLRoot_ PLLType* PLLType< PLLType >::pllnext [protected]
Definition at line 55 of file templates.defines.hh.
Referenced by PLLRoot< PLLType >::link_after().
template<class PLLType> PLLRoot_ PLLType * PLLType< PLLType >::pllprev [protected]
Definition at line 55 of file templates.defines.hh.
Referenced by if(), and PLLRoot< PLLType >::link_before().
template<class PLLType> PLLType* PLLType< PLLType >::plltail [protected]
Definition at line 76 of file templates.defines.hh.
Referenced by if().
The documentation for this class was generated from the following file:
templates.defines.hh