Financial_Monthly_SubCategory Class Reference
#include <dil2al.hh>
Public Methods
Financial_Monthly_SubCategory (String s, double r=0.0)
String SubCategory () const
Financial_Monthly_SubCategory * Find_SubCategory (String s) const
double Result () const
Protected Methods
void add (double e)
Protected Attributes
String subcategory
double result
Constructor & Destructor Documentation
Financial_Monthly_SubCategory::Financial_Monthly_SubCategory (String s, double r = 0.0) [inline]
Definition at line 1106 of file dil2al.hh.
References result.
1106 : subcategory(s), result(r) {}
Member Function Documentation
void Financial_Monthly_SubCategory::add (double e) [inline, protected]
Definition at line 1104 of file dil2al.hh.
References result.
Referenced by Financial_Monthly_Category::add().
1104 { result += e; }
Financial_Monthly_SubCategory * Financial_Monthly_SubCategory::Find_SubCategory (String s) const
Definition at line 155 of file finances.cc.
References PLLHandle< Financial_Monthly_SubCategory >::Next(), and subcategory.
Referenced by Financial_Monthly_Category::add().
155                                                                                               {
156   if (subcategory==s) return const_cast<Financial_Monthly_SubCategory *>(this);
157   if (Next()) return Next()->Find_SubCategory(s);
158   return NULL;
159 }
double Financial_Monthly_SubCategory::Result () const [inline]
Definition at line 1109 of file dil2al.hh.
References result.
1109 { return result; }
String Financial_Monthly_SubCategory::SubCategory () const [inline]
Definition at line 1107 of file dil2al.hh.
1107 { return subcategory; }
Member Data Documentation
double Financial_Monthly_SubCategory::result [protected]
Definition at line 1103 of file dil2al.hh.
Referenced by add(), Financial_Monthly_SubCategory(), and Result().
String Financial_Monthly_SubCategory::subcategory [protected]
Definition at line 1102 of file dil2al.hh.
Referenced by Find_SubCategory().
The documentation for this class was generated from the following files:
dil2al.hh
finances.cc