Topical_DIL_Files_Root Class Reference
#include <dil2al.hh>
Public Methods
Topical_DIL_Files_Root ()
String * operator[] (int n)
String * File (int n=0)
String * Title (int n=0)
filetitle_t * Topic (int n=0)
void Invalidate ()
int Refresh ()
Public Attributes
PLLRoot< Topical_DIL_Files > dil
Constructor & Destructor Documentation
Topical_DIL_Files_Root::Topical_DIL_Files_Root () [inline]
Definition at line 343 of file dil2al.hh.
References dil, and PLLRoot< Topical_DIL_Files >::link_before().
343 { Topical_DIL_Files * tdf = new Topical_DIL_Files(); dil.link_before(tdf); }
Member Function Documentation
String* Topical_DIL_Files_Root::File (int n = 0) [inline]
Definition at line 348 of file dil2al.hh.
References PLLRoot< PLLType >::head().
348 { if (dil.head()) return dil.head()->File(n); return NULL; }
void Topical_DIL_Files_Root::Invalidate () [inline]
Definition at line 351 of file dil2al.hh.
References PLLRoot< PLLType >::head().
351 { if (dil.head()) dil.head()->Invalidate(); }
String* Topical_DIL_Files_Root::operator[] (int n) [inline]
Definition at line 347 of file dil2al.hh.
References PLLRoot< PLLType >::head().
347 { if (dil.head()) return (*dil.head())[n]; return NULL; }
int Topical_DIL_Files_Root::Refresh () [inline]
Definition at line 352 of file dil2al.hh.
References PLLRoot< PLLType >::head().
352 { if (dil.head()) return dil.head()->Refresh(); return 0; }
String* Topical_DIL_Files_Root::Title (int n = 0) [inline]
Definition at line 349 of file dil2al.hh.
References PLLRoot< PLLType >::head().
349 { if (dil.head()) return dil.head()->Title(n); return NULL; }
filetitle_t* Topical_DIL_Files_Root::Topic (int n = 0) [inline]
Definition at line 350 of file dil2al.hh.
References PLLRoot< PLLType >::head().
350 { if (dil.head()) return dil.head()->Topic(n); return NULL; }
Member Data Documentation
PLLRoot<Topical_DIL_Files> Topical_DIL_Files_Root::dil
Definition at line 345 of file dil2al.hh.
Referenced by Topical_DIL_Files_Root().
The documentation for this class was generated from the following file:
dil2al.hh