DIL_Visualize_with_FORM_Tabs Class Reference
#include <dil2al.hh>
Public Methods
DIL_Visualize_with_FORM_Tabs (DIL_Hierarchy_Level_Data *ld=NULL)
virtual void Initialize ()
virtual void Visualize_Element (DIL_entry *de, int depth)
virtual void Visualize_NotShown (int numdependencies, int depth)
virtual String Output ()
virtual String Output_Content ()
virtual void Append (String appendstr)
Protected Methods
virtual bool Visualize_Plan_Entry (DIL_entry *de)
Protected Attributes
String s
String content
Constructor & Destructor Documentation
DIL_Visualize_with_FORM_Tabs::DIL_Visualize_with_FORM_Tabs (DIL_Hierarchy_Level_Data * ld = NULL) [inline]
Definition at line 795 of file dil2al.hh.
795 : DIL_Visualize(ld) {}
Member Function Documentation
virtual void DIL_Visualize_with_FORM_Tabs::Append (String appendstr) [inline, virtual]
Definition at line 801 of file dil2al.hh.
Referenced by Tabbed_FORM_DIL_Hierarchy().
801 { s += appendstr; }
virtual void DIL_Visualize_with_FORM_Tabs::Initialize () [inline, virtual]
Reimplemented from DIL_Visualize (p.).
Definition at line 796 of file dil2al.hh.
796 { s = ""; content = ""; }
virtual String DIL_Visualize_with_FORM_Tabs::Output () [inline, virtual]
Reimplemented from DIL_Visualize (p.).
Definition at line 799 of file dil2al.hh.
Referenced by Tabbed_FORM_DIL_Hierarchy().
799 { return s; }
virtual String DIL_Visualize_with_FORM_Tabs::Output_Content () [inline, virtual]
Definition at line 800 of file dil2al.hh.
Referenced by Tabbed_FORM_DIL_Hierarchy().
800 { return content; }
void DIL_Visualize_with_FORM_Tabs::Visualize_Element (DIL_entry * de, int depth) [virtual]
Reimplemented from DIL_Visualize (p.).
Definition at line 187 of file diladmin.cc.
References DIL_ID::chars(), DIL_entry_content::completion, DIL_entry::content, content, DIL_Visualize::cumlikelihood, DIL_Topical_List::dil, Elipsis_At(), DIL_entry::Entry_Text(), filetitle_t::file, String::gsub(), HTML_put_href(), HTML_remove_tags(), DIL_Visualize::Level_Data(), replicate(), s, DIL_ID::str(), DIL_entry::Topics(), and Visualize_Plan_Entry().
187                                                                               {
188   String ptxtcontent;
189   content += "\nDIL#" + String(de->chars()) + ":\n";
190   String * ctxt = de->Entry_Text();
191   if (ctxt) {
192     ptxtcontent = (*ctxt);
193     content += (*HTML_remove_tags(ptxtcontent));
194     Elipsis_At(ptxtcontent,hierarchyexcerptlength);
195     ptxtcontent.gsub('\n',' ');
196   } else ptxtcontent = "<!-- excerpt requires content file option -->";
197   content += '\n';
198   if (depth>0) s += replicate('\t',depth);
199   else cumlikelihood = 0.0;
200   // differentiation of display depending on completion status
201   bool pending = true;
202   if (de->content) pending = ((de->content->completion>=0.0) && (de->content->completion<1.0));
203   // show checkbox and DIL ID reference
204   s += "<INPUT type=\"checkbox\" name=\"DILIDCHKBX"+String(de->chars())+"\" value=\"extract\">";
205   if (pending) s += HTML_put_href((de->Topics(0)->dil.file+'#')+de->chars(),"<B>DIL#" + String(de->chars()) + "</B>");
206   else s += HTML_put_href((de->Topics(0)->dil.file+'#')+de->chars(),"DIL#" + String(de->chars()));
207   // show level-specific data
208   if (Level_Data()) { // visualization that depends on level-specific data
209     if (!Visualize_Plan_Entry(de)) if (de->content) s += "[<A HREF=\"file:///cgi-bin/dil2al?dil2al=MEI&DILID="+de->str()+"\">edit</A>]";
210   }
211   // show DIL entry text content
212   s += ": " + ptxtcontent + '\n';
213 }
void DIL_Visualize_with_FORM_Tabs::Visualize_NotShown (int numdependencies, int depth) [virtual]
Reimplemented from DIL_Visualize (p.).
Definition at line 215 of file diladmin.cc.
References DIL_Hierarchy_Level_Data::has_benefit_risk(), DIL_Visualize::Level_Data(), replicate(), and s.
215                                                                                     {
216   if (numdependencies>0) {
217     if (depth>0) s += replicate('\t',depth);
218     s += '['+String((long) numdependencies);
219     if (reversehierarchy) s += " superiors...]\n";
220     else s += " dependencies...]\n";
221   }
222   if (Level_Data())
223     if (Level_Data()->has_benefit_risk()) {
224       if (depth>0) s += replicate('\t',depth);
225       s += "&lt;" + String(Level_Data()->benefit,"%3.1f") + '/' + String(Level_Data()->risk,"%3.1f") + "&gt;\n";
226     }
227 }
bool DIL_Visualize_with_FORM_Tabs::Visualize_Plan_Entry (DIL_entry * de) [protected, virtual]
Definition at line 145 of file diladmin.cc.
References DIL_Hierarchy_Level_Data::benefit, DIL_entry::content, DIL_Visualize::cumlikelihood, Plan_entry_content::Decision(), DILSUPS_REL_UNSPECIFIED, DIL_Hierarchy_Level_Data::Entry(), DIL_entry_content::Get_Plan_Entry_Content(), DIL_entry::Is_Plan_Entry(), DIL_Visualize::Level_Data(), DIL_Hierarchy_Level_Data::likelihood, PLAN_ENTRY_TYPE_ACTION, PLAN_ENTRY_TYPE_GOAL, PLLHandle< DIL_Hierarchy_Level_Data >::Prev(), DIL_Hierarchy_Level_Data::risk, s, and DIL_ID::str().
Referenced by Visualize_Element().
145                                                                       {
146   // returns false mostly just to indicate when a regular content editing
147   // link should be added to s
148   if ((!de) || (!Level_Data())) return false;
149   if (hierarchyplanparse) { // additional parsing requested
150     if (de->Is_Plan_Entry()==PLAN_ENTRY_TYPE_ACTION) {
151 #ifdef DEBUG_PLAN_ENTRY
152       s += '[' + String((long) de->Is_Plan_Entry()) + ']';
153 #endif
154       if (Level_Data()->Prev()) {
155         DIL_entry * pe = Level_Data()->Prev()->Entry();
156         if (pe->Is_Plan_Entry()==PLAN_ENTRY_TYPE_GOAL)
157           if (pe->content->Get_Plan_Entry_Content()->Decision()==(*de)) {
158             s += "<B>{!}</B>";
159           }
160       }
161     }
162 #ifdef DEBUG_PLAN_ENTRY
163     else s += '{' + String((long) de->Is_Plan_Entry()) + '}';
164 #endif
165   }
166   if (Level_Data()->likelihood>DILSUPS_REL_UNSPECIFIED) {
167     if (cumlikelihood==0.0) cumlikelihood = Level_Data()->likelihood;
168     else cumlikelihood *= Level_Data()->likelihood;
169     s += " (";
170     if (de->content) {
171       s += "<A HREF=\"file:///cgi-bin/dil2al?dil2al=MEI&DILID="+de->str()+"\">"; // open link to modification interface
172       double desirability = de->content->PLAN_OUTCOME_DESIRABILITY;
173       if (desirability>0.0) {
174         s += "<B>" + String(desirability,"%3.1f") + "</B>,";
175         if (Level_Data()->Prev()) Level_Data()->Prev()->benefit += (Level_Data()->likelihood*desirability);
176       } else {
177         s += String(desirability,"%3.1f") + ',';
178         if (Level_Data()->Prev()) Level_Data()->Prev()->risk += (Level_Data()->likelihood*(-desirability));
179       }
180       s += "</A>"; //close link to modification interface
181     } 
182     s += String(Level_Data()->likelihood,"%4.2f") + '|' + String(cumlikelihood,"%5.3f") + ')';
183   } else return false;
184   return true;
185 }
Member Data Documentation
String DIL_Visualize_with_FORM_Tabs::content [protected]
Definition at line 792 of file dil2al.hh.
Referenced by Visualize_Element().
String DIL_Visualize_with_FORM_Tabs::s [protected]
Definition at line 791 of file dil2al.hh.
Referenced by Visualize_Element(), Visualize_NotShown(), and Visualize_Plan_Entry().
The documentation for this class was generated from the following files:
dil2al.hh
diladmin.cc