DIL_Visualize_with_HTML_Tabs Class Reference
#include <dil2al.hh>
Public Methods
DIL_Visualize_with_HTML_Tabs (DIL_Hierarchy_Level_Data *ld=NULL)
virtual void Initialize ()
virtual void Visualize_Element (DIL_entry *de, int depth)
virtual void Visualize_NotShown (int numdependencies, int depth)
virtual String Output ()
virtual String Output_Content ()
Protected Attributes
String s
String content
Constructor & Destructor Documentation
DIL_Visualize_with_HTML_Tabs::DIL_Visualize_with_HTML_Tabs (DIL_Hierarchy_Level_Data * ld = NULL) [inline]
Definition at line 780 of file dil2al.hh.
780 : DIL_Visualize(ld) {}
Member Function Documentation
virtual void DIL_Visualize_with_HTML_Tabs::Initialize () [inline, virtual]
Reimplemented from DIL_Visualize (p.).
Definition at line 781 of file dil2al.hh.
781 { s = ""; content = ""; }
virtual String DIL_Visualize_with_HTML_Tabs::Output () [inline, virtual]
Reimplemented from DIL_Visualize (p.).
Definition at line 784 of file dil2al.hh.
Referenced by Tabbed_HTML_DIL_Hierarchy().
784 { return s; }
virtual String DIL_Visualize_with_HTML_Tabs::Output_Content () [inline, virtual]
Definition at line 785 of file dil2al.hh.
Referenced by Tabbed_HTML_DIL_Hierarchy().
785 { return content; }
void DIL_Visualize_with_HTML_Tabs::Visualize_Element (DIL_entry * de, int depth) [virtual]
Reimplemented from DIL_Visualize (p.).
Definition at line 121 of file diladmin.cc.
References DIL_ID::chars(), content, DIL_Topical_List::dil, Elipsis_At(), DIL_entry::Entry_Text(), filetitle_t::file, String::gsub(), HTML_put_href(), HTML_remove_tags(), replicate(), s, and DIL_entry::Topics().
121                                                                               {
122   String ptxtcontent;
123   content += "\nDIL#" + String(de->chars()) + ":\n";
124   String * ctxt = de->Entry_Text();
125   if (ctxt) {
126     ptxtcontent = (*ctxt);
127     content += (*HTML_remove_tags(ptxtcontent));
128     Elipsis_At(ptxtcontent,hierarchyexcerptlength);
129     ptxtcontent.gsub('\n',' ');
130   } else ptxtcontent = "<!-- excerpt requires content file option -->";
131   content += '\n';
132   if (depth>0) s += replicate('\t',depth);
133   s += HTML_put_href((de->Topics(0)->dil.file+'#')+de->chars(),"DIL#" + String(de->chars())) + ": " + ptxtcontent + '\n';
134 }
void DIL_Visualize_with_HTML_Tabs::Visualize_NotShown (int numdependencies, int depth) [virtual]
Reimplemented from DIL_Visualize (p.).
Definition at line 136 of file diladmin.cc.
References replicate(), and s.
136                                                                                     {
137   if (numdependencies>0) {
138     if (depth>0) s += replicate('\t',depth);
139     s += '['+String((long) numdependencies);
140     if (reversehierarchy) s += " superiors...]\n";
141     else s += " dependencies...]\n";
142   }
143 }
Member Data Documentation
String DIL_Visualize_with_HTML_Tabs::content [protected]
Definition at line 778 of file dil2al.hh.
Referenced by Visualize_Element().
String DIL_Visualize_with_HTML_Tabs::s [protected]
Definition at line 777 of file dil2al.hh.
Referenced by Visualize_Element(), and Visualize_NotShown().
The documentation for this class was generated from the following files:
dil2al.hh
diladmin.cc