Financial_Note Class Reference
#include <dil2al.hh>
Public Methods
Financial_Note (time_t d, double e, String t, bool h, String n, String c)
Financial_Note ()
Financial_Note (String &s, time_t &t, int &sloc)
int get (String &s, time_t &t, int sloc=0)
String put () const
void link_sorted (PLLRoot< Financial_Note > &r)
time_t Date () const
bool Handled () const
String Type () const
double Expense () const
Protected Attributes
time_t date
double expense
String type
bool handled
String note
String comment
Constructor & Destructor Documentation
Financial_Note::Financial_Note (time_t d, double e, String t, bool h, String n, String c) [inline]
Definition at line 1083 of file dil2al.hh.
References date, expense, and handled.
1083 : date(d), expense(e), type(t), handled(h), note(n), comment(c) {}
Financial_Note::Financial_Note () [inline]
Definition at line 1084 of file dil2al.hh.
References date, expense, false, and handled.
1084 : date(0), expense(0.0), type(""), handled(false), note(""), comment("") {}
Financial_Note::Financial_Note (String & s, time_t & t, int & sloc) [inline]
Definition at line 1085 of file dil2al.hh.
References get().
1085 { sloc = get(s,t,sloc); }
Member Function Documentation
time_t Financial_Note::Date () const [inline]
Definition at line 1089 of file dil2al.hh.
References date.
Referenced by Financial_Monthly_Root::add(), link_sorted(), and put().
1089 { return date; }
double Financial_Note::Expense () const [inline]
Definition at line 1092 of file dil2al.hh.
References expense.
Referenced by Financial_Monthly::add().
1092 { return expense; }
int Financial_Note::get (String & s, time_t & t, int sloc = 0)
Definition at line 13 of file finances.cc.
References String::at(), String::before(), comment, String::contains(), date, String::del(), String::empty(), expense, handled, HTML_get_table_cell(), HTML_get_table_row(), String::index(), String::lastchar(), String::length(), note, String::SEARCH_END, String::sub(), BigRegex::sublen(), BigRegex::subpos(), time_stamp_time_date(), type, and String::upcase.
Referenced by Financial_Note().
13                                                             {
14   // get a financial note item from a string
15   BigRegex trx("[[]\\([^]]+\\)[]]");
16   String tr,trp;
17   sloc = HTML_get_table_row(s,sloc,trp,tr);
18   trp.upcase();
19   handled = !trp.contains("BGCOLOR");
20   StringList tc; int tclen = 0;
21   for (int j = 0; j>=0; ) {
22     j = HTML_get_table_cell(tr,j,trp,tc[tclen]);
23     if (j>=0) tclen++;
24   }
25   int i = 0;
26   if ((tclen>2) && (tc[0].index(BRXint)>=0)) {
27     // get a new date
28     String datestr(tc[0].sub(BRXint,0)+"0000");
29     t = time_stamp_time_date(datestr.before(12));
30     i++;
31   }
32   date = t;
33   note = tc[i];
34   expense = 0.0;
35   int e = -1, l;
36   for (int eend = 0; eend>=0; ) { // get last double in note (expenses must contain a decimal point)
37     eend = note.index(BRXdouble,String::SEARCH_END,eend);
38     if (eend>=0) if (note.sub(BRXdouble,0).contains('.')) { e = BRXdouble.subpos(); l = BRXdouble.sublen(); }
39   }
40   if (e>=0) {
41     expense = atof(String(note.at(e,l)));
42     if (e>0) if (note[e-1]=='$') { e--; l++; }
43     note.del(e,l);
44   }
45   if (note.index(trx)<0) type = "unknown";
46   else {
47     type = note.sub(trx,1);
48     note.del(trx.subpos(),trx.sublen());
49   }
50   while ((!note.empty()) && (note.lastchar()==' ')) note.del((int) note.length()-1,1);
51   i++;
52   if (tclen>i) comment=tc[i];
53   while ((!comment.empty()) && (comment.lastchar()=='\n')) comment.del((int) comment.length()-1,1);
54   return sloc;
55 }
bool Financial_Note::Handled () const [inline]
Definition at line 1090 of file dil2al.hh.
References handled.
1090 { return handled; }
void Financial_Note::link_sorted (PLLRoot< Financial_Note > & r)
Definition at line 57 of file finances.cc.
References Date(), PLLRoot< PLLType >::head(), PLLRoot< PLLType >::insert_before(), PLLRoot< PLLType >::link_before(), and PLL_LOOP_FORWARD.
Referenced by financial_notes(), and read_financial_notes_file().
57                                                             {
58   // link this financial note to r in order sorted by date
59   PLL_LOOP_FORWARD(Financial_Note,r.head(),1) {
60     if (e->Date()>Date()) {
61       r.insert_before(e,this); // sorted by date
62       return;
63     }
64   }
65   r.link_before(this); // append at end
66 }
String Financial_Note::put () const
Definition at line 68 of file finances.cc.
References comment, Date(), expense, HTML_put_table_cell(), HTML_put_table_row(), PLLHandle< Financial_Note >::Next(), note, PLL_LOOP_FORWARD, PLLHandle< Financial_Note >::Prev(), time_stamp(), and type.
68                                  {
69   const String hstr(" BGCOLOR=\"#FF5F5F\"");
70   const String nullstr("");
71   const String * rp;
72   if (handled) rp=&nullstr; else rp=&hstr;
73   String datecell("");
74   if ((!Prev()) || ((Prev()->Date()!=Date()))) {
75     long notesondate = 1;
76     PLL_LOOP_FORWARD(Financial_Note,Next(),Date()==e->Date()) notesondate++;
77     datecell = HTML_put_table_cell(" ROWSPAN="+String(notesondate),time_stamp("%Y%m%d",Date()),true)+'\n';
78   }
79   return HTML_put_table_row(*rp,datecell+HTML_put_table_cell("",note+" $"+String(expense,"%.2f")+" ["+type+']',true)+HTML_put_table_cell("",comment,true),true)+'\n';
80 }
String Financial_Note::Type () const [inline]
Definition at line 1091 of file dil2al.hh.
Referenced by Financial_Monthly::add().
1091 { return type; }
Member Data Documentation
String Financial_Note::comment [protected]
Definition at line 1081 of file dil2al.hh.
Referenced by get(), and put().
time_t Financial_Note::date [protected]
Definition at line 1076 of file dil2al.hh.
Referenced by Date(), Financial_Note(), and get().
double Financial_Note::expense [protected]
Definition at line 1077 of file dil2al.hh.
Referenced by Expense(), Financial_Note(), get(), and put().
bool Financial_Note::handled [protected]
Definition at line 1079 of file dil2al.hh.
Referenced by Financial_Note(), get(), and Handled().
String Financial_Note::note [protected]
Definition at line 1080 of file dil2al.hh.
Referenced by get(), and put().
String Financial_Note::type [protected]
Definition at line 1078 of file dil2al.hh.
Referenced by get(), and put().
The documentation for this class was generated from the following files:
dil2al.hh
finances.cc