SubString Class Reference
#include <BigString.hh>
Public Methods
~SubString ()
SubString & operator= (const String &y)
SubString & operator= (const SubString &y)
SubString & operator= (const char *t)
SubString & operator= (char c)
int contains (char c) const
int contains (const String &y) const
int contains (const SubString &y) const
int contains (const char *t) const
int contains (const BigRegex &r) const
int matches (const BigRegex &r) const
_BIGSTRING_LENGTH length () const
int empty () const
const char * chars () const
int OK () const
Protected Methods
void assign (const StrRep *, const char *, _BIGSTRING_SIZE=-1)
SubString (String &x, _BIGSTRING_SIZE p, _BIGSTRING_SIZE l)
SubString (const SubString &x)
Protected Attributes
String & S
_BIGSTRING_LENGTH pos
_BIGSTRING_LENGTH len
Friends
class String
ostream & operator<< (ostream &s, const SubString &x)
Constructor & Destructor Documentation
SubString::SubString (String & x, _BIGSTRING_SIZE p, _BIGSTRING_SIZE l) [inline, protected]
Definition at line 541 of file BigString.hh.
References _BIGSTRING_SIZE.
542   :S(x), pos(first), len(l) {}
SubString::SubString (const SubString & x) [inline, protected]
Definition at line 539 of file BigString.hh.
540   :S(x.S), pos(x.pos), len(x.len) {}
SubString::~SubString () [inline]
Definition at line 544 of file BigString.hh.
544 {}
Member Function Documentation
void SubString::assign (const StrRep *, const char *, _BIGSTRING_SIZE = -1) [protected]
Definition at line 577 of file BigString.cc.
References _BIGSTRING_SIZE, len, StrRep::len, pos, String::rep, StrRep::s, S, and StrRep::sz.
Referenced by operator=().
578 { // INVOLVED in lfstr.at(...) = ...
579   if (&S == &_nilString) return;
580 
581   if (ylen < 0) ylen = slen(ys);
582   StrRep* targ = S.rep;
583   _BIGSTRING_SIZE sl = targ->len - len + ylen;
584 #ifdef DEBUG_BIGSTRING
585         if (ysrc->debugop) cerr << "Target String length = " << targ->len << ", Substring length = " << len << ", assigned length = " << ylen << ", sl = " << sl << '\n';
586 #endif
587 
588   if (ysrc == targ || sl >= targ->sz)
589   {
590 #ifdef DEBUG_BIGSTRING
591         if (ysrc->debugop) cerr << "Assigning new String chunk.\n";
592 #endif
593     StrRep* oldtarg = targ;
594     targ = Sresize(0, sl);
595     ncopy(oldtarg->s, targ->s, pos);
596     ncopy(ys, &(targ->s[pos]), ylen);
597     scopy(&(oldtarg->s[pos + len]), &(targ->s[pos + ylen]));
598     delete oldtarg;
599   }
600   else if (len == ylen)
601 #ifdef DEBUG_BIGSTRING
602         {
603                 if (ysrc->debugop) cerr << "Replacing with equal length.\n";
604 #endif
605     ncopy(ys, &(targ->s[pos]), len);
606 #ifdef DEBUG_BIGSTRING
607         }
608 #endif
609   else if (ylen < len)
610   {
611 #ifdef DEBUG_BIGSTRING
612         if (ysrc->debugop) cerr << "New substring is shorter.\n";
613 #endif
614     ncopy(ys, &(targ->s[pos]), ylen);
615     scopy(&(targ->s[pos + len]), &(targ->s[pos + ylen]));
616   }
617   else
618   {
619 #ifdef DEBUG_BIGSTRING
620         if (ysrc->debugop) cerr << "New substring is longer, in same chunk.\n";
621 #endif
622     revcopy(&(targ->s[targ->len]), &(targ->s[sl]), targ->len-pos-len +1);
623     ncopy(ys, &(targ->s[pos]), ylen);
624   }
625 #ifdef DEBUG_BIGSTRING
626         if (ysrc->debugop) cerr << "New string length = " << sl << '\n';
627 #endif
628   targ->len = sl;
629   S.rep = targ;
630 }
const char * SubString::chars () const [inline]
Definition at line 500 of file BigString.hh.
References pos, String::rep, StrRep::s, and S.
Referenced by String::after(), String::at(), String::before(), cat(), compare(), contains(), String::contains(), String::del(), String::freq(), String::from(), String::gsub(), String::index(), matches(), String::matches(), operator<<(), operator=(), String::operator=(), String::prepend(), and String::through().
500 { return &(S.rep->s[pos]); }
int SubString::contains (const BigRegex & r) const [inline]
Definition at line 1224 of file BigString.hh.
References chars(), len, and BigRegex::search().
1225 {
1226   int unused;  return r.search(chars(), len, unused, 0) >= 0;
1227 }
int SubString::contains (const char * t) const [inline]
Definition at line 1204 of file BigString.hh.
References len, pos, S, and String::search().
1205 {   
1206   return S.search(pos, pos+len, t) >= 0;
1207 }
int SubString::contains (const SubString & y) const [inline]
Definition at line 1214 of file BigString.hh.
References chars(), len, length(), pos, S, and String::search().
1215 {   
1216   return S.search(pos, pos+len, y.chars(), y.length()) >= 0;
1217 }
int SubString::contains (const String & y) const [inline]
Definition at line 1209 of file BigString.hh.
References String::chars(), len, String::length(), pos, S, and String::search().
1210 {   
1211   return S.search(pos, pos+len, y.chars(), y.length()) >= 0;
1212 }
int SubString::contains (char c) const [inline]
Definition at line 1219 of file BigString.hh.
References len, pos, S, and String::search().
1220 {
1221   return S.search(pos, pos+len, c) >= 0;
1222 }
int SubString::empty () const [inline]
Definition at line 499 of file BigString.hh.
References len.
499 { return len == 0; }
_BIGSTRING_LENGTH SubString::length () const [inline]
Definition at line 498 of file BigString.hh.
References _BIGSTRING_LENGTH, and len.
Referenced by String::after(), String::at(), String::before(), cat(), compare(), contains(), String::contains(), String::del(), String::freq(), String::from(), String::gsub(), String::index(), String::matches(), operator<<(), operator=(), String::operator=(), String::prepend(), and String::through().
498 { return len; }
int SubString::matches (const BigRegex & r) const [inline]
Definition at line 1229 of file BigString.hh.
References chars(), len, and BigRegex::match().
1230 {
1231   return r.match(chars(), len, 0) == len;
1232 }
int SubString::OK () const
Definition at line 1468 of file BigString.cc.
References String::error(), StrRep::len, len, String::OK(), pos, String::rep, and S.
1469 {
1470   int v = S != (const char*)0; // have a String;
1471   v &= S.OK();                 // that is legal
1472   v &= pos + len >= S.rep->len;// pos and len within bounds
1473   if (!v) S.error("SubString invariant failure");
1474   return v;
1475 }
SubString & SubString::operator= (char c) [inline]
Definition at line 606 of file BigString.hh.
References assign().
607 {
608   assign(0, &ch, 1);
609   return *this;
610 }
SubString & SubString::operator= (const char * t) [inline]
Definition at line 600 of file BigString.hh.
References assign().
601 {
602   assign(0, ys);
603   return *this;
604 }
SubString & SubString::operator= (const SubString & y) [inline]
Definition at line 618 of file BigString.hh.
References assign(), chars(), length(), String::rep, and S.
619 {
620   assign(y.S.rep, y.chars(), y.length());
621   return *this;
622 }
SubString & SubString::operator= (const String & y) [inline]
Definition at line 612 of file BigString.hh.
References assign(), String::chars(), String::length(), and String::rep.
613 {
614   assign(y.rep, y.chars(), y.length()); // INVOLVED in lfstr.at(...) = ...
615   return *this;
616 }
Friends And Related Function Documentation
ostream& operator<< (ostream & s, const SubString & x) [friend]
Definition at line 1415 of file BigString.cc.
1416 { 
1417   const char* a = x.chars();
1418   const char* lasta = &(a[x.length()]);
1419   while (a < lasta)
1420     s.put(*a++);
1421   return(s);
1422 }
friend class String [friend]
Definition at line 113 of file BigString.hh.
Member Data Documentation
_BIGSTRING_LENGTH SubString::len [protected]
Definition at line 118 of file BigString.hh.
Referenced by assign(), contains(), empty(), length(), matches(), and OK().
_BIGSTRING_LENGTH SubString::pos [protected]
Definition at line 117 of file BigString.hh.
Referenced by assign(), chars(), contains(), and OK().
String& SubString::S [protected]
Definition at line 116 of file BigString.hh.
Referenced by assign(), chars(), contains(), OK(), and operator=().
The documentation for this class was generated from the following files:
BigString.hh
BigString.cc