Quick_String_Hash Class Reference
#include <dil2al.hh>
Public Methods
Quick_String_Hash ()
~Quick_String_Hash ()
Quick_String_Hash & insert (const char *s)
Quick_String_Hash & operator<< (const char *s)
int read (const char *s) const
int operator[] (const char *s) const
unsigned long nodes () const
unsigned long size () const
Protected Methods
Quick_String_Hash * add_list_element (int i)
Protected Attributes
Quick_String_Hash ** list
int offset
int len
Constructor & Destructor Documentation
Quick_String_Hash::Quick_String_Hash () [inline]
Definition at line 187 of file dil2al.hh.
References len, and offset.
Referenced by add_list_element(), and insert().
187 : list(NULL), offset(0), len(0) {}
Quick_String_Hash::~Quick_String_Hash () [inline]
Definition at line 189 of file dil2al.hh.
References len.
189 { if (list) { for (int i=0; i<len; i++) delete list[i]; delete[] list; } }
Member Function Documentation
Quick_String_Hash * Quick_String_Hash::add_list_element (int i) [protected]
Definition at line 179 of file utilities.cc.
References len, list, offset, and Quick_String_Hash().
Referenced by insert(), and String_Hash_Value::insert_value().
179                                                              {
180 // Note: currently there is no way for this to return NULL, since allocation
181 // errors are not caught.
182         if (i<0) i = 0; // reduce the impact of roll-over errors
183         if (!list) { // allocate list of pointers
184                 len = 1;
185                 list = new Quick_String_Hash*[len];
186 #ifdef CONST_QUICK_STRING_HASH_ENDNODE
187                 list[0] = const_cast<Quick_String_Hash *>(&_qsh_endnode);
188 #else
189                 list[0] = new Quick_String_Hash();
190 #endif
191                 offset = i;
192                 return list[0];
193         }
194         if (i<offset) { // prepend to the list
195                 int oldlen = len;
196                 len += (offset-i);
197                 offset = i;
198                 Quick_String_Hash ** oldlist = list;
199                 list = new Quick_String_Hash*[len];
200                 for (int j = 0; j<len; j++) list[j] = NULL; // initialize list
201 #ifdef CONST_QUICK_STRING_HASH_ENDNODE
202                 list[0] = const_cast<Quick_String_Hash *>(&_qsh_endnode);
203 #else
204                 list[0] = new Quick_String_Hash();
205 #endif
206                 for (int j = oldlen-1, k = len-1; j>=0; j--, k--) list[k] = oldlist[j];
207                 delete[] oldlist;
208                 return list[0];
209         }
210         i -= offset;
211         if (i>=len) { // append to the list
212                 int oldlen = len;
213                 len = i+1;
214                 Quick_String_Hash ** oldlist = list;
215                 list = new Quick_String_Hash*[len];
216                 for (int j = 0; j<len; j++) list[j] = NULL; // initialize list
217 #ifdef CONST_QUICK_STRING_HASH_ENDNODE
218                 list[i] = const_cast<Quick_String_Hash *>(&_qsh_endnode);
219 #else
220                 list[i] = new Quick_String_Hash();
221 #endif
222                 for (int j = 0; j<oldlen; j++) list[j] = oldlist[j];
223                 delete[] oldlist;
224                 return list[i];
225         }
226         if (!list[i]) { // add list element
227 #ifdef CONST_QUICK_STRING_HASH_ENDNODE
228                 list[i] = const_cast<Quick_String_Hash *>(&_qsh_endnode);
229 #else
230                 list[i] = new Quick_String_Hash();
231 #endif
232                 return list[i];
233         }
234 }
Quick_String_Hash & Quick_String_Hash::insert (const char * s)
Definition at line 236 of file utilities.cc.
References add_list_element(), len, list, offset, and Quick_String_Hash().
Referenced by String_Hash_Value::insert_value(), and operator<<().
236                                                             {
237 // *** can adapt this to the faster method according to results obtained with read and read_recursive
238         if (s[0]=='\0') return (*this);
239         int i = ((int) s[0]);   // implied list coordinate
240         int r = i - offset;             // real list coordinate
241         if (r<0) {
242                 if (add_list_element(i)==NULL) return (*this);
243                 r = i - offset; // adjust to new offset
244         } else if (r>=len) {
245                 if (add_list_element(i)==NULL) return (*this); // this also takes care of the case where the list is unallocated
246                 r = i - offset; // adjust to new offset
247         } else if (!list[r]) {
248                 if (add_list_element(i)==NULL) return (*this);
249         }
250 #ifdef CONST_QUICK_STRING_HASH_ENDNODE
251         if ((s[1]!='\0') && (list[r]==&_qsh_endnode)) list[r] = new Quick_String_Hash(); // allocate so that list can be made
252 #endif
253         list[r]->insert(&s[1]);
254         return (*this);
255 }
unsigned long Quick_String_Hash::nodes () const
Definition at line 284 of file utilities.cc.
References len, list, and res.
284                                              {
285 #ifdef CONST_QUICK_STRING_HASH_ENDNODE
286         if (this==&_qsh_endnode) return 0;
287 #endif
288         unsigned long res = 1;
289         for (int i=0; i<len; i++) if (list[i]) res += list[i]->nodes();
290         return res;
291 }
Quick_String_Hash& Quick_String_Hash::operator<< (const char * s) [inline]
Definition at line 192 of file dil2al.hh.
References insert().
192 { return insert(s); }
int Quick_String_Hash::operator[] (const char * s) const [inline]
Definition at line 194 of file dil2al.hh.
References read().
194 { return read(s); }
int Quick_String_Hash::read (const char * s) const
Definition at line 258 of file utilities.cc.
References len, list, and offset.
Referenced by Search_Target::check_encountered(), and operator[]().
258                                                 {
259         // Determines if the next character in s exists in the tree
260         if (s[0]=='\0') return 1;
261         int i = ((int) s[0]);   // implied list coordinate
262         if (i<offset) return 0;
263         i -= offset;                    // real list coordinate
264         if (i>=len) return 0;   // this also takes care of the case where the list is unallocated
265         if (list[i]) return list[i]->read(&s[1]);
266         return 0;
267 }
unsigned long Quick_String_Hash::size () const
Definition at line 293 of file utilities.cc.
References len, list, and res.
293                                             {
294 #ifdef CONST_QUICK_STRING_HASH_ENDNODE
295         if (this==&_qsh_endnode) return 0;
296 #endif
297         unsigned long res = sizeof(*this);
298         for (int i=0; i<len; i++) if (list[i]) res += list[i]->size();
299         return res;
300 }
Member Data Documentation
int Quick_String_Hash::len [protected]
Definition at line 183 of file dil2al.hh.
Referenced by add_list_element(), insert(), String_Hash_Value::insert_value(), nodes(), Quick_String_Hash(), read(), String_Hash_Value::read_value(), size(), and ~Quick_String_Hash().
Quick_String_Hash** Quick_String_Hash::list [protected]
Definition at line 181 of file dil2al.hh.
Referenced by add_list_element(), insert(), String_Hash_Value::insert_value(), nodes(), read(), String_Hash_Value::read_value(), and size().
int Quick_String_Hash::offset [protected]
Definition at line 182 of file dil2al.hh.
Referenced by add_list_element(), insert(), String_Hash_Value::insert_value(), Quick_String_Hash(), read(), and String_Hash_Value::read_value().
The documentation for this class was generated from the following files:
dil2al.hh
utilities.cc