Novelty_Marker_List Class Reference
#include <dil2al.hh>
Public Methods
~Novelty_Marker_List ()
Novelty_Marker_List ()
Novelty_Marker_List (unsigned long n)
Novelty_Marker_List (const Novelty_Marker cs, Novelty_Marker_List *cn=NULL)
Novelty_Marker & operator[] (unsigned long n)
Novelty_Marker_List * get_Next ()
void append (unsigned long n, Novelty_Marker &ins)
void insert (unsigned long n, Novelty_Marker &ins)
unsigned long length ()
long iselement (Novelty_Marker &el, unsigned long n=0)
void Get_Context_Ranks (StringList &cc, LongList &ccr)
Protected Attributes
Novelty_Marker_List * Next
Novelty_Marker s
Constructor & Destructor Documentation
Novelty_Marker_List::~Novelty_Marker_List () [inline]
Definition at line 292 of file dil2al.hh.
292 { if (Next) delete Next; }
Novelty_Marker_List::Novelty_Marker_List () [inline]
Definition at line 293 of file dil2al.hh.
Referenced by append(), insert(), Novelty_Marker_List(), and operator[]().
293 { Next=NULL; }
Novelty_Marker_List::Novelty_Marker_List (unsigned long n) [inline]
Definition at line 294 of file dil2al.hh.
References Novelty_Marker_List().
294 { if (n) Next = new Novelty_Marker_List(n-1); else Next = NULL; }
Novelty_Marker_List::Novelty_Marker_List (const Novelty_Marker cs, Novelty_Marker_List * cn = NULL) [inline]
Definition at line 295 of file dil2al.hh.
295 { s=cs; Next=cn; }
Member Function Documentation
void Novelty_Marker_List::append (unsigned long n, Novelty_Marker & ins)
Definition at line 463 of file utilities.cc.
References Next, and Novelty_Marker_List().
463                                                                       {
464         if (!n) Next = new Novelty_Marker_List(ins,Next);
465         else
466                 if (Next) Next->append(n-1,ins);
467                 else {
468                         Next = new Novelty_Marker_List();
469                         Next->append(n-1,ins);
470                 }
471 }
void Novelty_Marker_List::Get_Context_Ranks (StringList & cc, LongList & ccr)
Definition at line 492 of file utilities.cc.
References get_Next(), StringList::iselement(), Novelty_Marker::NM_NOVELTY_ITEM, and s.
Referenced by extract_paper_plan_to_paper().
492                                                                            {
493 // creates a list of concatenated contexts and a ranking according to their
494 // average Novelty Item importance parameter values (rank 0 is highest)
495         int cclen = 0, i; String s; LongList ccnum;
496         for (Novelty_Marker_List * nml = this; (nml); nml=nml->get_Next()) if ((*nml)[0].nmtype==Novelty_Marker::NM_NOVELTY_ITEM) {
497                 s = (*nml)[0].context.concatenate(", ");
498                 if ((i=cc.iselement(s))<0) { // add new concatenated context
499                         cc[cclen] = s; ccnum[cclen] = 0; i = cclen; cclen++;
500                 }
501                 ccnum[i]++;
502                 float imp = 0.0;
503                 for (int j = 0; j<(*nml)[0].impnum; j++) imp += (*nml)[0].imp[j];
504                 if ((*nml)[0].impnum>1) imp /= (float) (*nml)[0].impnum; // average importance of concatenated contexts of Novelty Item
505                 ccr[i] = (long) (imp*1000.0);
506         }
507         for (i=0; i<cclen; i++) ccr[i] /= ccnum[i]; // average importances of concatenated contexts
508         long biggest, rank = 0, cctodo = cclen;
509         while (cctodo>0) {
510                 // find biggest
511                 biggest = -1;
512                 for (i=0; i<cclen; i++) if (ccr[i]>biggest) biggest = ccr[i];
513                 if (biggest<0) break;
514                 // set all at biggest size to next rank
515                 for (i=0; i<cclen; i++) if (ccr[i]==biggest) {
516                         ccnum[i] = rank; ccr[i] = -1; cctodo--;
517                 }
518                 rank++;
519         }
520         for (i=0; i<cclen; i++) ccr[i] = ccnum[i];
521 }
Novelty_Marker_List* Novelty_Marker_List::get_Next () [inline]
Definition at line 297 of file dil2al.hh.
Referenced by Get_Context_Ranks().
297 { return Next; }
void Novelty_Marker_List::insert (unsigned long n, Novelty_Marker & ins)
Definition at line 473 of file utilities.cc.
References Next, Novelty_Marker_List(), and s.
473                                                                       {
474         if (!n) { Next = new Novelty_Marker_List(s,Next); s = ins; }
475         else
476                 if (Next) Next->insert(n-1,ins);
477                 else 
478                         if (n>1) {
479                                 Next = new Novelty_Marker_List();
480                                 Next->insert(n-1,ins);
481                         } else Next = new Novelty_Marker_List(ins);
482 }
long Novelty_Marker_List::iselement (Novelty_Marker & el, unsigned long n = 0)
Definition at line 484 of file utilities.cc.
References Novelty_Marker::id, Next, s, and Novelty_Marker::source.
Referenced by extract_paper_plan_to_paper(), and extract_recursively().
484                                                                             {
485         if ((el.source == s.source) && (el.id == s.id)) return n;
486         else {
487                 if (Next) return Next->iselement(el,n+1);
488                 else return -1;
489         }
490 }
unsigned long Novelty_Marker_List::length () [inline]
Definition at line 303 of file dil2al.hh.
Referenced by extract_paper_plan_to_paper(), and extract_recursively().
303 { if (Next) return 1+Next->length(); else return 1; }
Novelty_Marker & Novelty_Marker_List::operator[] (unsigned long n)
Definition at line 457 of file utilities.cc.
References Next, Novelty_Marker_List(), and s.
457                                                                 {
458         if (!n) return s;
459         if (!Next) Next = new Novelty_Marker_List();
460         return (*Next)[n-1];
461 }
Member Data Documentation
Novelty_Marker_List* Novelty_Marker_List::Next [protected]
Definition at line 289 of file dil2al.hh.
Referenced by append(), insert(), iselement(), and operator[]().
Novelty_Marker Novelty_Marker_List::s [protected]
Definition at line 290 of file dil2al.hh.
Referenced by Get_Context_Ranks(), insert(), iselement(), and operator[]().
The documentation for this class was generated from the following files:
dil2al.hh
utilities.cc