DIL_entry_parameters Class Reference
#include <dil2al.hh>
Public Methods
DIL_entry_parameters (DIL_entry &e, int loc=-1)
bool topic_append (String tfile, String ttitle, float trelevance)
bool topic_prepend (String tfile, String ttitle, float trelevance)
bool project_append (String pfile, String ptitle, float prelevance, float punbounded, float pbounded, time_t ptargetdate, int ptdprop, float purgency, float ppriority)
bool project_prepend (String pfile, String ptitle, float prelevance, float punbounded, float pbounded, time_t ptargetdate, int ptdprop, float purgency, float ppriority)
int OrigLoc ()
bool Write_to_Binary_Cache (ofstream &cfl)
bool Read_from_Binary_Cache (ifstream &cfl)
bool Binary_Cache_Diagnostic (DIL_entry_parameters *cached, int &testedbytes)
Public Attributes
PLLRoot< DIL_Topical_List > topics
PLLRoot< DIL_AL_List > projects
Protected Attributes
DIL_entry * entry
int origloc
Constructor & Destructor Documentation
DIL_entry_parameters::DIL_entry_parameters (DIL_entry & e, int loc = -1) [inline]
Definition at line 624 of file dil2al.hh.
References origloc.
624 : entry(&e), origloc(loc) {}
Member Function Documentation
bool DIL_entry_parameters::Binary_Cache_Diagnostic (DIL_entry_parameters * cached, int & testedbytes)
Definition at line 892 of file utilities.cc.
References DIL_AL_List::Binary_Cache_Diagnostic(), DIL_Topical_List::Binary_Cache_Diagnostic(), entry, PLLRoot< DIL_AL_List >::head(), PLLRoot< DIL_Topical_List >::head(), PLLRoot< DIL_AL_List >::length(), PLLRoot< DIL_Topical_List >::length(), PLLHandle< DIL_AL_List >::Next(), PLLHandle< DIL_Topical_List >::Next(), origloc, projects, topics, and VOUT.
Referenced by DIL_entry::Binary_Cache_Diagnostic().
892                                                                                                    {
893   // test if the quick load cache process works reliably
894   // this is the original entry_parameters, cached is the one retrieved from the binary cache
895   //   start of this object test
896   int localtestedbytes = 0;
897   if ((*entry)!=(*(cached->entry))) VOUT << "*** DIL_entry_parameters entry mismatch\n"; // testing if DIL_ID==DIL_ID
898   localtestedbytes += sizeof(entry);
899   if (origloc!=cached->origloc) VOUT << "*** DIL_entry_parameters origloc mismatch\n";
900   localtestedbytes += sizeof(origloc);
901   if (topics.length()!=cached->topics.length()) VOUT << "*** DIL_entry_parameters topics length mismatch, " << topics.length() << " vs. " << cached->topics.length() << '\n';;
902   localtestedbytes += sizeof(topics);
903   if (projects.length()!=cached->projects.length()) VOUT << "*** DIL_entry_parameters projects length mismatch, " << projects.length() << " vs. " << cached->projects.length() << '\n';;
904   localtestedbytes += sizeof(projects);
905   //   end of this object test
906   if (localtestedbytes!=sizeof(DIL_entry_parameters)) VOUT << "*** testedbytes!=sizeof(DIL_entry_parameters)\n";
907   for (DIL_Topical_List * e = topics.head(), * c = cached->topics.head(); ((e) && (c)); e=e->Next(), c=c->Next()) if (!e->Binary_Cache_Diagnostic(c,testedbytes)) return false;
908   for (DIL_AL_List * e = projects.head(), * c = cached->projects.head(); ((e) && (c)); e=e->Next(), c=c->Next()) if (!e->Binary_Cache_Diagnostic(c,testedbytes)) return false;
909   testedbytes += localtestedbytes;
910   return true;
911 }
int DIL_entry_parameters::OrigLoc () [inline]
Definition at line 637 of file dil2al.hh.
References origloc.
637 { return origloc; }
bool DIL_entry_parameters::project_append (String pfile, String ptitle, float prelevance, float punbounded, float pbounded, time_t ptargetdate, int ptdprop, float purgency, float ppriority) [inline]
Definition at line 631 of file dil2al.hh.
References PLLRoot< PLLType >::link_before().
Referenced by Detailed_Items_List::Get_Project_Data(), modify_DIL_entry_target_date(), modify_DIL_group_target_dates(), modify_DIL_group_target_dates_cmd(), and update_DIL_entry_parameter_elements().
631                                                                                                                                                                          {
632     return projects.link_before(new DIL_AL_List(*entry,pfile,ptitle,prelevance,punbounded,pbounded,ptargetdate,ptdprop,purgency,ppriority));
633   }
bool DIL_entry_parameters::project_prepend (String pfile, String ptitle, float prelevance, float punbounded, float pbounded, time_t ptargetdate, int ptdprop, float purgency, float ppriority) [inline]
Definition at line 634 of file dil2al.hh.
References PLLRoot< PLLType >::link_after().
634                                                                                                                                                                           {
635     return projects.link_after(new DIL_AL_List(*entry,pfile,ptitle,prelevance,punbounded,pbounded,ptargetdate,ptdprop,purgency,ppriority));
636   }
bool DIL_entry_parameters::Read_from_Binary_Cache (ifstream & cfl)
Definition at line 864 of file utilities.cc.
References entry, PLLRoot< DIL_AL_List >::link_before(), PLLRoot< DIL_Topical_List >::link_before(), origloc, projects, DIL_AL_List::Read_from_Binary_Cache(), DIL_Topical_List::Read_from_Binary_Cache(), READSOMETYPE, topics, and VOUT.
Referenced by DIL_entry::Read_from_Binary_Cache().
864                                                                 {
865   // origloc
866   if ((cfl.read((READSOMETYPE) (&origloc), sizeof(origloc))).gcount()<sizeof(origloc)) return false;
867   // topics
868   int numtopics;
869   if ((cfl.read((READSOMETYPE) (&numtopics), sizeof(numtopics))).gcount()<sizeof(numtopics)) return false;
870 #ifdef TEST_CACHE_READ
871   VOUT << "&&& numtopics = " << numtopics << '\n'; cout.flush();
872 #endif
873   if (numtopics>0) for (int i = 0; i<numtopics; i++) {
874     DIL_Topical_List * dtl = new DIL_Topical_List(*entry);
875     if (!dtl->Read_from_Binary_Cache(cfl)) { delete dtl; return false; }
876     topics.link_before(dtl);
877   }
878   // projects
879   int numprojects;
880   if ((cfl.read((READSOMETYPE) (&numprojects), sizeof(numprojects))).gcount()<sizeof(numprojects)) return false;
881 #ifdef TEST_CACHE_READ
882   VOUT << "&&& numprojects = " << numtopics << '\n'; cout.flush();
883 #endif
884   if (numprojects>0) for (int i = 0; i<numprojects; i++) {
885     DIL_AL_List * dal = new DIL_AL_List(*entry);
886     if (!dal->Read_from_Binary_Cache(cfl)) { delete dal; return false; }
887     projects.link_before(dal);
888   }
889   return true;
890 }
bool DIL_entry_parameters::topic_append (String tfile, String ttitle, float trelevance) [inline]
Definition at line 629 of file dil2al.hh.
References PLLRoot< PLLType >::link_before().
Referenced by Detailed_Items_List::Get_All_DIL_ID_File_Parameters().
629 { return topics.link_before(new DIL_Topical_List(*entry,tfile,ttitle,trelevance)); }
bool DIL_entry_parameters::topic_prepend (String tfile, String ttitle, float trelevance) [inline]
Definition at line 630 of file dil2al.hh.
References PLLRoot< PLLType >::link_after().
630 { return topics.link_after(new DIL_Topical_List(*entry,tfile,ttitle,trelevance)); }
bool DIL_entry_parameters::Write_to_Binary_Cache (ofstream & cfl)
Definition at line 850 of file utilities.cc.
References PLLRoot< DIL_AL_List >::head(), PLLRoot< DIL_Topical_List >::head(), PLLRoot< DIL_AL_List >::length(), PLLRoot< DIL_Topical_List >::length(), origloc, PLL_LOOP_FORWARD, projects, and topics.
Referenced by DIL_entry::Write_to_Binary_Cache().
850                                                                {
851   // origloc
852   cfl.write((const void *) (&origloc), sizeof(origloc));
853   // topics
854   int numtopics = topics.length();
855   cfl.write((const void *) (&numtopics), sizeof(numtopics));
856   if (numtopics>0) PLL_LOOP_FORWARD(DIL_Topical_List,topics.head(),1) if (!e->Write_to_Binary_Cache(cfl)) return false;
857   // projects
858   int numprojects = projects.length();
859   cfl.write((const void *) (&numprojects), sizeof(numprojects));
860   if (numprojects>0) PLL_LOOP_FORWARD(DIL_AL_List,projects.head(),1) if (!e->Write_to_Binary_Cache(cfl)) return false;
861   return true;
862 }
Member Data Documentation
DIL_entry* DIL_entry_parameters::entry [protected]
Definition at line 620 of file dil2al.hh.
Referenced by Binary_Cache_Diagnostic(), and Read_from_Binary_Cache().
int DIL_entry_parameters::origloc [protected]
Definition at line 621 of file dil2al.hh.
Referenced by Binary_Cache_Diagnostic(), DIL_entry_parameters(), OrigLoc(), Read_from_Binary_Cache(), and Write_to_Binary_Cache().
PLLRoot<DIL_AL_List> DIL_entry_parameters::projects
Definition at line 627 of file dil2al.hh.
Referenced by Binary_Cache_Diagnostic(), DIL_entry::Projects(), DIL_entry::Propagated_Target_Date(), Read_from_Binary_Cache(), and Write_to_Binary_Cache().
PLLRoot<DIL_Topical_List> DIL_entry_parameters::topics
Definition at line 626 of file dil2al.hh.
Referenced by Binary_Cache_Diagnostic(), Read_from_Binary_Cache(), DIL_entry::Topics(), and Write_to_Binary_Cache().
The documentation for this class was generated from the following files:
dil2al.hh
utilities.cc