Financial_Monthly_Root Class Reference
#include <dil2al.hh>
Public Methods
Financial_Monthly_Root ()
void add (const Financial_Note &fn)
String put_results () const
Constructor & Destructor Documentation
Financial_Monthly_Root::Financial_Monthly_Root () [inline]
Definition at line 1148 of file dil2al.hh.
1148 {};
Member Function Documentation
void Financial_Monthly_Root::add (const Financial_Note & fn)
Definition at line 227 of file finances.cc.
References Financial_Monthly::add(), Financial_Monthly::Copy_Categories(), Financial_Note::Date(), Financial_Monthly::Find_Month(), PLLRoot< Financial_Monthly >::head(), PLLRoot< Financial_Monthly >::link_before(), and time_stamp().
Referenced by financial_monthly().
227                                                           {
228   // add by month
229   String mstr = time_stamp("%Y%m",fn.Date());
230   Financial_Monthly * fm = NULL;
231   if (head()) fm = head()->Find_Month(mstr);
232   if (!fm) { // add month
233       fm = new Financial_Monthly(mstr);
234       link_before(fm);
235       fm->Copy_Categories(head());
236   }
237   // check for new categories and subcategories
238   // add by category and subcategory within month
239   fm->add(fn);
240 }
String Financial_Monthly_Root::put_results () const
Definition at line 242 of file finances.cc.
References PLLRoot< Financial_Monthly >::head(), PLL_LOOP_FORWARD, PLL_LOOP_FORWARD_NESTED, and res.
Referenced by financial_monthly().
242                                                  {
243   String res;
244   PLL_LOOP_FORWARD_NESTED(Financial_Monthly,head(),1,m) { // month
245     res += "Month: " + m->Month() + '\n';
246     PLL_LOOP_FORWARD_NESTED(Financial_Monthly_Category,m->categories.head(),1,c) { // category
247       res += "<TABLE BORDER=1 WIDTH=\"100%\">\n<TR>";
248       // headings
249       PLL_LOOP_FORWARD(Financial_Monthly_SubCategory,c->subcategories.head(),1) { // subcategory
250         res += "<TH>" + e->SubCategory();
251       }
252       res += "<TH>" + c->Category() + "\n<TR>";
253       // results
254       PLL_LOOP_FORWARD(Financial_Monthly_SubCategory,c->subcategories.head(),1) { // subcategory
255         res += "<TD>" + String(e->Result(),"%.2f");
256       }
257       res += "<TH><B>" + String(c->Result(),"%.2f") + "</B>\n</TABLE>\n";
258     }
259   }
260   return res;
261 }
The documentation for this class was generated from the following files:
dil2al.hh
finances.cc