AL_TC Class Reference
#include <dil2al.hh>
Public Methods
AL_TC ()
AL_TC (long itc, long i_limit)
~AL_TC ()
AL_TC * next_avail_el ()
AL_TC * avail_el (unsigned int n)
void set_val (float v)
DIL_entry * Get_DE ()
operator DIL_entry * ()
long available_before (unsigned int n)
float allocate_with_value (float uval, DIL_entry *d)
DIL_entry * Set_DE (DIL_entry *d)
AL_TC * allocate (DIL_entry *d)
Protected Attributes
DIL_entry * de
float val
Constructor & Destructor Documentation
AL_TC::AL_TC () [inline]
Definition at line 811 of file dil2al.hh.
References val.
811 : de(NULL), val(0.0) {}
AL_TC::AL_TC (long itc, long i_limit)
Definition at line 324 of file alcomp.cc.
References linear_distribution(), and val.
324                                   : de(NULL) {
325 // create TC and set value
326         val = linear_distribution((float) itc, (float) i_limit);
327 }
AL_TC::~AL_TC () [inline]
Definition at line 814 of file dil2al.hh.
814 {} 
Member Function Documentation
AL_TC * AL_TC::allocate (DIL_entry * d)
Definition at line 379 of file alcomp.cc.
References de, PLLHandle< AL_TC >::Next(), and val.
Referenced by AL_Day::allocate().
379                                      {
380 // allocates d to the first available task chunk
381 // returns the allocated task chunk
382         if (de) {
383                 if (Next()) return Next()->allocate(d);
384                 return NULL;
385         }
386         de = d;
387         val = 0.0;
388         return this;
389 }
float AL_TC::allocate_with_value (float uval, DIL_entry * d)
Definition at line 357 of file alcomp.cc.
References de, EOUT, PLLHandle< AL_TC >::Next(), and val.
Referenced by AL_Day::allocate_with_value().
357                                                           {
358 // allocate a DIL entry to a task chunk according to
359 // a random value
360 // returns the value of the allocated task chunk
361 // creates TCs if necessary
362         const char _err_msg[] = "dil2al: Available TC values do not add up to day value in AL_TC::allocate_with_value(), continuing\n";
363         if (de) {
364                 if (Next()) return Next()->allocate_with_value(uval,d);
365                 EOUT << _err_msg;
366                 return 0.0;
367         }
368         if (val<uval) {
369                 if (Next()) return Next()->allocate_with_value(uval-val,d);
370                 EOUT << _err_msg;
371                 return 0.0;
372         }
373         de = d;
374         uval = val;
375         val = 0.0;
376         return uval;
377 }
AL_TC * AL_TC::avail_el (unsigned int n)
Definition at line 335 of file alcomp.cc.
References PLL_LOOP_FORWARD.
Referenced by AL_Day::Get_Avail_TC(), and AL_Day::set_TC_values().
335                                       {
336 // returns the nth available task chunk
337         PLL_LOOP_FORWARD(AL_TC,this,1) if (!e->Get_DE()) {
338                 if (n==0) return e;
339                 n--;
340         }
341         return NULL;
342 }
long AL_TC::available_before (unsigned int n)
Definition at line 344 of file alcomp.cc.
References PLL_LOOP_FORWARD.
Referenced by AL_Day::available_before().
344                                            {
345 // returns the number of task chunks available before the
346 // nth task chunk (i.e. does not include the nth task chunk)
347 // This is used by AL_Day::available_before().
348         long avail = 0;
349         PLL_LOOP_FORWARD(AL_TC,this,1) {
350                 if (n==0) return avail;
351                 if (!e->Get_DE()) avail++;
352                 n--;
353         }
354         return avail;
355 }
DIL_entry* AL_TC::Get_DE () [inline]
Definition at line 819 of file dil2al.hh.
Referenced by generate_AL(), Active_List::generate_focused_AL(), Active_List::generate_wide_AL(), operator DIL_entry *(), and AL_Day::remove_unused_TCs().
819 { return de; }
AL_TC * AL_TC::next_avail_el ()
Definition at line 329 of file alcomp.cc.
References PLL_LOOP_FORWARD.
329                              {
330 // returns the next available task chunk
331         PLL_LOOP_FORWARD(AL_TC,this,1) if (!e->Get_DE()) return e;
332         return NULL;
333 }
AL_TC::operator DIL_entry * () [inline]
Definition at line 820 of file dil2al.hh.
References Get_DE().
820 { return Get_DE(); }
DIL_entry* AL_TC::Set_DE (DIL_entry * d) [inline]
Definition at line 826 of file dil2al.hh.
Referenced by AL_Day::add_TCs().
826 { DIL_entry * dprev = de; de = d; return dprev; }
void AL_TC::set_val (float v) [inline]
Definition at line 818 of file dil2al.hh.
References val.
Referenced by AL_Day::set_TC_values().
818 { val = v; }
Member Data Documentation
DIL_entry* AL_TC::de [protected]
Definition at line 807 of file dil2al.hh.
Referenced by allocate(), and allocate_with_value().
float AL_TC::val [protected]
Definition at line 808 of file dil2al.hh.
Referenced by AL_TC(), allocate(), allocate_with_value(), and set_val().
The documentation for this class was generated from the following files:
dil2al.hh
alcomp.cc