PLLHandle< PLLType > Class Template Reference
#include <templates.classic.hh>
Public Methods
PLLRoot< PLLType > * Root () const
PLLType * Next () const
PLLType * Prev () const
PLLType * head () const
PLLType * tail () const
PLLType * el (int n) const
PLLType * seek_head () const
PLLType * seek_tail () const
int length () const
int fulllength () const
bool unlink_before (PLLRoot< PLLType > &succ)
bool unlink_after (PLLRoot< PLLType > &pred)
void remove ()
PLLRoot< PLLType > * Root () const
PLLType * Next () const
PLLType * Prev () const
PLLType * head () const
PLLType * tail () const
PLLType * el (int n) const
PLLType * seek_head () const
PLLType * seek_tail () const
int length () const
int fulllength () const
bool unlink_before (PLLRoot< PLLType > &succ)
bool unlink_after (PLLRoot< PLLType > &pred)
void remove ()
PLLRoot< PLLType > * Root () const
PLLType * Next () const
PLLType * Prev () const
PLLType * head () const
PLLType * tail () const
PLLType * el (int n) const
PLLType * seek_head () const
PLLType * seek_tail () const
int length () const
int fulllength () const
bool unlink_before (PLLRoot< PLLType > &succ)
bool unlink_after (PLLRoot< PLLType > &pred)
void remove ()
PLLRoot< PLLType > * Root () const
PLLType * Next () const
PLLType * Prev () const
PLLType * head () const
PLLType * tail () const
PLLType * el (int n) const
PLLType * seek_head () const
PLLType * seek_tail () const
int length () const
int fulllength () const
bool unlink_before (PLLRoot< PLLType > &succ)
bool unlink_after (PLLRoot< PLLType > &pred)
void remove ()
Protected Methods
PLLHandle ()
virtual ~PLLHandle ()
PLLHandle ()
virtual ~PLLHandle ()
PLLHandle ()
virtual ~PLLHandle ()
void isolate ()
PLLHandle ()
virtual ~PLLHandle ()
Protected Attributes
PLLRoot< PLLType > * pllroot
PLLHandle< PLLType > * pllnext
PLLHandle< PLLType > * pllprev
PLLRoot< PLLType > * pllroot
PLLHandle< PLLType > * pllnext
PLLHandle< PLLType > * pllprev
PLLRoot< PLLType > * pllroot
PLLType * pllnext
PLLType * pllprev
PLLHandle_Signal pllsignal
PLLRoot< PLLType > * pllroot
PLLHandle< PLLType > * pllnext
PLLHandle< PLLType > * pllprev
template<class PLLType> class PLLHandle< PLLType >
Constructor & Destructor Documentation
template<class PLLType> PLLHandle< PLLType >::PLLHandle () [inline, protected]
Definition at line 56 of file templates.classic.hh.
56 : pllroot(NULL), pllnext(NULL), pllprev(NULL) {} 
template<class PLLType> virtual PLLHandle< PLLType >::~PLLHandle () [inline, protected, virtual]
Definition at line 57 of file templates.classic.hh.
57 { delete pllnext; } // virtual destructor calls actual complete most-derived object's destructor first
template<class PLLType> PLLHandle< PLLType >::PLLHandle () [inline, protected]
Definition at line 56 of file templates.clean.hh.
56 : pllroot(NULL), pllnext(NULL), pllprev(NULL) {} 
template<class PLLType> virtual PLLHandle< PLLType >::~PLLHandle () [inline, protected, virtual]
Definition at line 57 of file templates.clean.hh.
57 { delete pllnext; } // virtual destructor calls actual complete most-derived object's destructor first
template<class PLLType> PLLHandle< PLLType >::PLLHandle () [inline, protected]
Definition at line 64 of file templates.hh.
64 : pllroot(NULL), pllnext(NULL), pllprev(NULL), pllsignal(PLL_NOSIGNAL) {}
template<class PLLType> virtual PLLHandle< PLLType >::~PLLHandle () [inline, protected, virtual]
Definition at line 65 of file templates.hh.
65                        { // virtual destructor calls actual complete most-derived object's destructor first
66     //cerr << "PLLH=" << (int) this << " next=" << (int) pllnext << " s=" << (int) pllsignal << '\n'; cerr.flush();
67     if (pllsignal==PLL_LIST_DESTRUCT) { // If pllroot calls deletion, delete from here onwards.
68       if (pllnext) {
69         pllnext->pllsignal=PLL_LIST_DESTRUCT;
70         delete pllnext;
71       }
72     } else {
73       // If un unexpected source calls deletion (e.g. if this element
74       // was a local object that is destructed) then unlink and
75       // delete.
76       isolate();
77     }
78   }
template<class PLLType> PLLHandle< PLLType >::PLLHandle () [inline, protected]
Definition at line 56 of file templates.unfixed.hh.
56 : pllroot(NULL), pllnext(NULL), pllprev(NULL) {} 
template<class PLLType> virtual PLLHandle< PLLType >::~PLLHandle () [inline, protected, virtual]
Definition at line 57 of file templates.unfixed.hh.
57 { delete pllnext; } // virtual destructor calls actual complete most-derived object's destructor first
Member Function Documentation
template<class PLLType> PLLType* PLLHandle< PLLType >::el (int n) const [inline]
template<class PLLType> PLLType* PLLHandle< PLLType >::el (int n) const [inline]
template<class PLLType> PLLType* PLLHandle< PLLType >::el (int n) const [inline]
template<class PLLType> PLLType * PLLHandle< PLLType >::el (int n) const [inline]
Definition at line 171 of file templates.classic.hh.
References PLLHandle< PLLType >::pllnext, and PLLHandle< PLLType >::pllprev.
Referenced by PLLRoot< DIL_entry_Pointer >::el().
171                                                    { 
172         if (!n) return (PLLType *)const_cast<PLLHandle<PLLType> *>(this); 
173         if (n>0) { 
174                 if (pllnext) return pllnext->el(n-1); 
175                 else return NULL; 
176         } else { 
177                 if (pllprev) return pllprev->el(n+1); 
178                 else return NULL; 
179         } 
180 } 
template<class PLLType> int PLLHandle< PLLType >::fulllength () const [inline]
template<class PLLType> int PLLHandle< PLLType >::fulllength () const [inline]
template<class PLLType> int PLLHandle< PLLType >::fulllength () const [inline]
template<class PLLType> int PLLHandle< PLLType >::fulllength () const [inline]
Definition at line 201 of file templates.classic.hh.
References PLLHandle< PLLType >::head(), and PLLType< PLLType >::length().
201                                                 { 
202         return head()->length(); 
203 } 
template<class PLLType> PLLType* PLLHandle< PLLType >::head () const [inline]
Definition at line 62 of file templates.unfixed.hh.
62 { return pllroot->head(); } 
template<class PLLType> PLLType* PLLHandle< PLLType >::head () const [inline]
Definition at line 84 of file templates.hh.
84 { return pllroot->head(); } 
template<class PLLType> PLLType* PLLHandle< PLLType >::head () const [inline]
Definition at line 62 of file templates.clean.hh.
62 { return pllroot->head(); } 
template<class PLLType> PLLType* PLLHandle< PLLType >::head () const [inline]
Definition at line 62 of file templates.classic.hh.
Referenced by PLLHandle< PLLType >::fulllength().
62 { return pllroot->head(); } 
template<class PLLType> void PLLHandle< PLLType >::isolate () [inline, protected]
Definition at line 190 of file templates.hh.
References PLLRoot< PLLType >::link_before(), PLLRoot< PLLType >::pllhead, PLLHandle< PLLType >::pllnext, PLLHandle< PLLType >::pllprev, PLLHandle< PLLType >::pllroot, PLLRoot< PLLType >::plltail, PLLHandle< PLLType >::unlink_after(), and PLLHandle< PLLType >::unlink_before().
Referenced by PLLHandle< DIL_entry_Pointer >::~PLLHandle().
190                                         { 
191 // unlink Protected Linked List element and update head and tail
192         if (!pllroot) { 
193                 if (pllprev) pllprev->pllnext = pllnext; 
194                 if (pllnext) pllnext->pllprev = pllprev;
195                 pllprev = pllnext = NULL;
196                 return;
197         } 
198         PLLRoot<PLLType> * h = pllroot, r, t; 
199         unlink_before(t); // t becomes root of this and after
200         unlink_after(r); // r becomes root of this
201         h->link_before(&t); // append t to h
202         // avoid deletion as r is destructed
203         r.pllhead = NULL; r.plltail = NULL; pllroot = NULL;
204 } 
template<class PLLType> int PLLHandle< PLLType >::length () const [inline]
template<class PLLType> int PLLHandle< PLLType >::length () const [inline]
template<class PLLType> int PLLHandle< PLLType >::length () const [inline]
template<class PLLType> int PLLHandle< PLLType >::length () const [inline]
Definition at line 195 of file templates.classic.hh.
References PLLType< PLLType >::length(), and PLLHandle< PLLType >::Next().
Referenced by PLLRoot< DIL_entry_Pointer >::length().
195                                             { 
196         if (Next()) return 1 + Next()->length(); 
197         return 1; 
198 } 
template<class PLLType> PLLType* PLLHandle< PLLType >::Next () const [inline]
Definition at line 60 of file templates.unfixed.hh.
60 { return static_cast<PLLType *>(pllnext); } 
template<class PLLType> PLLType* PLLHandle< PLLType >::Next () const [inline]
Definition at line 82 of file templates.hh.
82 { return pllnext; } 
template<class PLLType> PLLType* PLLHandle< PLLType >::Next () const [inline]
Definition at line 60 of file templates.clean.hh.
60 { return static_cast<PLLType *>(pllnext); } 
template<class PLLType> PLLType* PLLHandle< PLLType >::Next () const [inline]
Definition at line 60 of file templates.classic.hh.
Referenced by PLLHandle< PLLType >::length(), and PLLRoot< PLLType >::set_root().
60 { return (PLLType *)const_cast<PLLHandle<PLLType> *>(pllnext); } 
template<class PLLType> PLLType* PLLHandle< PLLType >::Prev () const [inline]
Definition at line 61 of file templates.unfixed.hh.
61 { return static_cast<PLLType *>(pllprev); } 
template<class PLLType> PLLType* PLLHandle< PLLType >::Prev () const [inline]
Definition at line 83 of file templates.hh.
83 { return pllprev; } 
template<class PLLType> PLLType* PLLHandle< PLLType >::Prev () const [inline]
Definition at line 61 of file templates.clean.hh.
61 { return static_cast<PLLType *>(pllprev); } 
template<class PLLType> PLLType* PLLHandle< PLLType >::Prev () const [inline]
Definition at line 61 of file templates.classic.hh.
61 { return (PLLType *)const_cast<PLLHandle<PLLType> *>(pllprev); } 
template<class PLLType> void PLLHandle< PLLType >::remove () [inline]
template<class PLLType> void PLLHandle< PLLType >::remove () [inline]
template<class PLLType> void PLLHandle< PLLType >::remove () [inline]
template<class PLLType> void PLLHandle< PLLType >::remove () [inline]
Definition at line 154 of file templates.classic.hh.
References PLLRoot< PLLType >::link_before(), PLLHandle< PLLType >::pllnext, PLLHandle< PLLType >::pllprev, PLLHandle< PLLType >::pllroot, PLLHandle< PLLType >::unlink_after(), and PLLHandle< PLLType >::unlink_before().
154                                        { 
155 // unlink and delete Protected Linked List element
156 // and update head and tail
157         if (!pllroot) { 
158                 pllprev->pllnext = pllnext; 
159                 pllnext->pllprev = pllprev; 
160                 PLLType * pn = (PLLType *) pllnext; 
161                 delete this;
162                 return;
163         } 
164         PLLRoot<PLLType> * h = pllroot, r, t; 
165         unlink_before(t); 
166         unlink_after(r); 
167         h->link_before(&t); // deletion occurs as r and t are destroyed
168 } 
template<class PLLType> PLLRoot<PLLType>* PLLHandle< PLLType >::Root () const [inline]
Definition at line 59 of file templates.unfixed.hh.
59 { return pllroot; } 
template<class PLLType> PLLRoot<PLLType>* PLLHandle< PLLType >::Root () const [inline]
Definition at line 81 of file templates.hh.
81 { return pllroot; } 
template<class PLLType> PLLRoot<PLLType>* PLLHandle< PLLType >::Root () const [inline]
Definition at line 59 of file templates.clean.hh.
59 { return pllroot; } 
template<class PLLType> PLLRoot<PLLType>* PLLHandle< PLLType >::Root () const [inline]
Definition at line 59 of file templates.classic.hh.
59 { return pllroot; } 
template<class PLLType> PLLType* PLLHandle< PLLType >::seek_head () const [inline]
template<class PLLType> PLLType* PLLHandle< PLLType >::seek_head () const [inline]
template<class PLLType> PLLType* PLLHandle< PLLType >::seek_head () const [inline]
template<class PLLType> PLLType * PLLHandle< PLLType >::seek_head () const [inline]
Definition at line 183 of file templates.classic.hh.
References PLLHandle< PLLType >::pllprev.
Referenced by PLLHandle< PLLType >::unlink_after().
183                                                      { 
184         if (!pllprev) return (PLLType *)const_cast<PLLHandle<PLLType> *>(this); 
185         return pllprev->seek_head(); 
186 } 
template<class PLLType> PLLType* PLLHandle< PLLType >::seek_tail () const [inline]
template<class PLLType> PLLType* PLLHandle< PLLType >::seek_tail () const [inline]
template<class PLLType> PLLType* PLLHandle< PLLType >::seek_tail () const [inline]
template<class PLLType> PLLType * PLLHandle< PLLType >::seek_tail () const [inline]
Definition at line 189 of file templates.classic.hh.
References PLLHandle< PLLType >::pllnext.
Referenced by PLLHandle< PLLType >::unlink_before().
189                                                      { 
190         if (!pllnext) return (PLLType *)const_cast<PLLHandle<PLLType> *>(this); 
191         return pllnext->seek_tail(); 
192 } 
template<class PLLType> PLLType* PLLHandle< PLLType >::tail () const [inline]
Definition at line 63 of file templates.unfixed.hh.
63 { return pllroot->tail(); } 
template<class PLLType> PLLType* PLLHandle< PLLType >::tail () const [inline]
Definition at line 85 of file templates.hh.
85 { return pllroot->tail(); } 
template<class PLLType> PLLType* PLLHandle< PLLType >::tail () const [inline]
Definition at line 63 of file templates.clean.hh.
63 { return pllroot->tail(); } 
template<class PLLType> PLLType* PLLHandle< PLLType >::tail () const [inline]
Definition at line 63 of file templates.classic.hh.
63 { return pllroot->tail(); } 
template<class PLLType> bool PLLHandle< PLLType >::unlink_after (PLLRoot< PLLType > & pred) [inline]
template<class PLLType> bool PLLHandle< PLLType >::unlink_after (PLLRoot< PLLType > & pred) [inline]
template<class PLLType> bool PLLHandle< PLLType >::unlink_after (PLLRoot< PLLType > & pred) [inline]
template<class PLLType> bool PLLHandle< PLLType >::unlink_after (PLLRoot< PLLType > & pred) [inline]
Definition at line 136 of file templates.classic.hh.
References PLLRoot< PLLType >::head(), PLLRoot< PLLType >::pllhead, PLLHandle< PLLType >::pllnext, PLLHandle< PLLType >::pllroot, PLLRoot< PLLType >::plltail, pred, PLLHandle< PLLType >::seek_head(), and PLLRoot< PLLType >::set_root().
Referenced by PLLHandle< PLLType >::isolate(), and PLLHandle< PLLType >::remove().
136                                                                     { 
137 // unlinks after this and gives this and before
138 // the new root pred
139 // pred is currently required to be an empty list
140         if (pred.head()) return false; 
141         if (pllnext) pllnext->pllprev = NULL; 
142         pred.plltail = this; 
143         if (pllroot) { 
144                 pred.pllhead = pllroot->head(); 
145                 pllroot->pllhead = pllnext; 
146                 if (!pllnext) pllroot->plltail = NULL; 
147         } else pred.pllhead = seek_head(); 
148         pllnext = NULL; 
149         pred.set_root(pred.head()); 
150         return true; 
151 } 
template<class PLLType> bool PLLHandle< PLLType >::unlink_before (PLLRoot< PLLType > & succ) [inline]
template<class PLLType> bool PLLHandle< PLLType >::unlink_before (PLLRoot< PLLType > & succ) [inline]
template<class PLLType> bool PLLHandle< PLLType >::unlink_before (PLLRoot< PLLType > & succ) [inline]
template<class PLLType> bool PLLHandle< PLLType >::unlink_before (PLLRoot< PLLType > & succ) [inline]
Definition at line 118 of file templates.classic.hh.
References PLLRoot< PLLType >::head(), PLLRoot< PLLType >::pllhead, PLLHandle< PLLType >::pllprev, PLLHandle< PLLType >::pllroot, PLLRoot< PLLType >::plltail, PLLHandle< PLLType >::seek_tail(), PLLRoot< PLLType >::set_root(), and succ.
Referenced by PLLHandle< PLLType >::isolate(), and PLLHandle< PLLType >::remove().
118                                                                      { 
119 // unlinks before this and gives this and after
120 // the new root succ
121 // succ is currently required to be an empty list
122         if (succ.head()) return false; 
123         if (pllprev) pllprev->pllnext = NULL; 
124         succ.pllhead = this; 
125         if (pllroot) { 
126                 succ.plltail = pllroot->tail(); 
127                 pllroot->plltail = pllprev; 
128                 if (!pllprev) pllroot->pllhead = NULL; 
129         } else succ.plltail = seek_tail(); 
130         pllprev = NULL; 
131         succ.set_root(this); 
132         return true; 
133 } 
Member Data Documentation
template<class PLLType> PLLHandle<PLLType>* PLLHandle< PLLType >::pllnext [protected]
Definition at line 55 of file templates.unfixed.hh.
template<class PLLType> PLLType* PLLHandle< PLLType >::pllnext [protected]
Definition at line 62 of file templates.hh.
template<class PLLType> PLLHandle<PLLType>* PLLHandle< PLLType >::pllnext [protected]
Definition at line 55 of file templates.clean.hh.
template<class PLLType> PLLHandle<PLLType>* PLLHandle< PLLType >::pllnext [protected]
Definition at line 55 of file templates.classic.hh.
Referenced by PLLHandle< PLLType >::el(), PLLHandle< PLLType >::isolate(), PLLHandle< PLLType >::remove(), PLLHandle< PLLType >::seek_tail(), and PLLHandle< PLLType >::unlink_after().
template<class PLLType> PLLHandle<PLLType> * PLLHandle< PLLType >::pllprev [protected]
Definition at line 55 of file templates.unfixed.hh.
template<class PLLType> PLLType * PLLHandle< PLLType >::pllprev [protected]
Definition at line 62 of file templates.hh.
template<class PLLType> PLLHandle<PLLType> * PLLHandle< PLLType >::pllprev [protected]
Definition at line 55 of file templates.clean.hh.
template<class PLLType> PLLHandle<PLLType> * PLLHandle< PLLType >::pllprev [protected]
Definition at line 55 of file templates.classic.hh.
Referenced by PLLHandle< PLLType >::el(), PLLHandle< PLLType >::isolate(), PLLHandle< PLLType >::remove(), PLLHandle< PLLType >::seek_head(), and PLLHandle< PLLType >::unlink_before().
template<class PLLType> PLLRoot<PLLType>* PLLHandle< PLLType >::pllroot [protected]
Definition at line 54 of file templates.unfixed.hh.
template<class PLLType> PLLRoot<PLLType>* PLLHandle< PLLType >::pllroot [protected]
Definition at line 61 of file templates.hh.
template<class PLLType> PLLRoot<PLLType>* PLLHandle< PLLType >::pllroot [protected]
Definition at line 54 of file templates.clean.hh.
template<class PLLType> PLLRoot<PLLType>* PLLHandle< PLLType >::pllroot [protected]
Definition at line 54 of file templates.classic.hh.
Referenced by PLLHandle< PLLType >::isolate(), PLLHandle< PLLType >::remove(), PLLRoot< PLLType >::set_root(), PLLHandle< PLLType >::unlink_after(), and PLLHandle< PLLType >::unlink_before().
template<class PLLType> PLLHandle_Signal PLLHandle< PLLType >::pllsignal [protected]
Definition at line 63 of file templates.hh.
Referenced by PLLHandle< DIL_entry_Pointer >::PLLHandle(), and PLLHandle< DIL_entry_Pointer >::~PLLHandle().
The documentation for this class was generated from the following files:
templates.classic.hh
templates.clean.hh
templates.hh
templates.unfixed.hh