DIL_entry Class Reference
#include <dil2al.hh>
Public Methods
DIL_entry (Text_File_Buffers &t)
DIL_entry (Text_File_Buffers &t, String &idstr)
DIL_entry (Text_File_Buffers &t, const SubString &idstr)
~DIL_entry ()
DIL_entry * elbyid (const DIL_ID &id) const
DIL_entry * operator[] (DIL_ID &id)
DIL_Topical_List * Topics (int n)
DIL_AL_List * Projects (int n)
void Set_Semaphore (int svalue)
int Get_Semaphore ()
void Set_Semaphores (int svalue)
time_t Propagated_Target_Date (bool warn, bool top=true) const
time_t Target_Date (bool top=true) const
time_t Local_Target_Date (int n, time_t unspecified=-2)
time_t Time_Required ()
float Completion_State ()
String * Entry_Text ()
bool Get_Entry_Parameters (String &parstr)
bool Is_Direct_Dependency_Of (const DIL_entry *superior)
bool Is_Dependency_Of (DIL_entry *superior)
bool Has_Superiors (bool taggedonly=false)
int Is_Plan_Entry ()
bool Write_to_Binary_Cache (ofstream &cfl)
bool Write_Topical_to_Binary_Cache (ofstream &cfl, bool gottext)
bool Read_from_Binary_Cache (ifstream &cfl)
bool Read_Topical_from_Binary_Cache (ifstream &cfl, bool gottext)
bool Binary_Cache_Diagnostic (DIL_entry *cached, int &testedbytes)
Public Attributes
DIL_entry_content * content
DIL_entry_parameters * parameters
Protected Attributes
int semaphore
Text_File_Buffers * tfb
Constructor & Destructor Documentation
DIL_entry::DIL_entry (Text_File_Buffers & t)
Definition at line 913 of file utilities.cc.
Referenced by Propagated_Target_Date().
913 : tfb(&t), DIL_ID(), content(NULL), parameters(NULL) {}
DIL_entry::DIL_entry (Text_File_Buffers & t, String & idstr)
Definition at line 915 of file utilities.cc.
915 : tfb(&t), DIL_ID(idstr), content(NULL), parameters(NULL) {}
DIL_entry::DIL_entry (Text_File_Buffers & t, const SubString & idstr)
Definition at line 917 of file utilities.cc.
917 : tfb(&t), DIL_ID(idstr), content(NULL), parameters(NULL) {}
DIL_entry::~DIL_entry () [inline]
Definition at line 660 of file dil2al.hh.
References content, and parameters.
660 { delete content; delete parameters; }
Member Function Documentation
bool DIL_entry::Binary_Cache_Diagnostic (DIL_entry * cached, int & testedbytes)
Definition at line 1108 of file utilities.cc.
References DIL_entry_parameters::Binary_Cache_Diagnostic(), DIL_entry_content::Binary_Cache_Diagnostic(), content, parameters, and VOUT.
Referenced by Detailed_Items_List::Binary_Cache_Diagnostic().
1108                                                                              {
1109   // test if the quick load cache process works reliably
1110   // this is the original entry, cached is the one retrieved from the binary cache
1111   //   start of this object test
1112   int localtestedbytes = 0;
1113   if ((*this)!=(*cached)) VOUT << "*** DIL_ID mismatch\n"; // testing if DIL_ID==DIL_ID
1114   localtestedbytes += sizeof(DIL_ID) + sizeof(PLLHandle<DIL_entry>) + sizeof(semaphore) + sizeof(tfb) + sizeof(content) + sizeof(parameters);
1115   //   end of this object test
1116   if (localtestedbytes!=sizeof(DIL_entry)) VOUT << "*** testedbytes!=sizeof(DIL_entry)\n";
1117   if (content) {
1118     if (cached->content) {
1119       if (!content->Binary_Cache_Diagnostic(cached->content,testedbytes)) return false;
1120     } else VOUT << "*** entry has content, cached does not\n";
1121   } else if (cached->content) VOUT << "*** entry has no content, cached does\n";
1122   if (parameters) {
1123     if (cached->parameters) {
1124       if (!parameters->Binary_Cache_Diagnostic(cached->parameters,testedbytes)) return false;
1125     } else VOUT << "*** entry has parameters, cached does not\n";
1126   } else if (cached->parameters) VOUT << "*** entry has no parameters, cached does\n";
1127   testedbytes += localtestedbytes;
1128   return true;
1129 }
float DIL_entry::Completion_State () [inline]
Definition at line 683 of file dil2al.hh.
References DIL_entry_content::completion.
Referenced by DIL_Required_Task_Chunks().
683 { if (content) return content->completion; return (float) 0.0; }
DIL_entry * DIL_entry::elbyid (const DIL_ID & id) const
Definition at line 919 of file utilities.cc.
References PLLHandle< DIL_entry >::Next(), and PLLHandle< DIL_entry >::Prev().
Referenced by Plan_entry_content::Decision_Ptr(), generate_modify_element_FORM_interface(), generate_modify_element_FORM_interface_DIL_entry_parameters(), Detailed_Items_List::Get_All_Topical_DIL_Parameters(), modify_DIL_entry_target_date(), modify_DIL_group_target_dates(), modify_element_through_FORM_interface(), operator[](), Propagated_Target_Date(), Detailed_Items_List::Read_Topical_from_Binary_Cache(), DIL_AL_List::Superiorbyid(), Tabbed_DIL_Hierarchy(), Tabbed_FORM_DIL_Hierarchy(), Tabbed_HTML_DIL_Hierarchy(), and update_DIL_entry_parameter_elements().
919                                                      {
920 // return pointer to list element with DIL ID id
921 //      if ((*const_cast<DIL_entry *>(this))==id) return const_cast<DIL_entry *>(this);
922         if ((*this)==id) return const_cast<DIL_entry *>(this);
923         for (DIL_entry * de=Next(); de; de=de->Next()) if (*de==id) return de;
924         for (DIL_entry * de=Prev(); de; de=de->Prev()) if (*de==id) return de;
925         return NULL;
926 }
String* DIL_entry::Entry_Text () [inline]
Definition at line 684 of file dil2al.hh.
References DIL_entry_content::text.
Referenced by Active_List::generate_focused_AL(), generate_modify_element_FORM_interface_DIL_entry_content(), generate_modify_element_FORM_interface_DIL_Superiors(), Active_List::generate_wide_AL(), update_main_ALs(), DIL_Visualize_with_FORM_Tabs::Visualize_Element(), DIL_Visualize_with_HTML_Tabs::Visualize_Element(), and DIL_Visualize_with_Tabs::Visualize_Element().
684 { if (content) return content->text; return NULL; }
bool DIL_entry::Get_Entry_Parameters (String & parstr)
Definition at line 992 of file utilities.cc.
References String::after(), DIL_entry_content::completion, content, double2time(), String::index(), DIL_entry_content::required, DIL_entry_content::started, and DIL_entry_content::valuation.
Referenced by Detailed_Items_List::Get_All_Topical_DIL_Parameters().
992                                                     {
993 // parstr contains entry parameters to be parsed and stored
994         int parstart = -1; double pars[4];
995         for (int parnum = 0; parnum<4; parnum++) {
996                 if ((parstart=parstr.index(':',parstart+1))<0) return false;
997                 pars[parnum] = atof(String(parstr.after(parstart)));
998         }
999         if (!content) content = new DIL_entry_content(*this);
1000         content->started  = double2time(pars[0]); // *** can remove this (see dil2al.hh)
1001         content->required = (time_t) (ceil(pars[1]*60.0)*60.0); // convert hours to seconds
1002         content->completion = pars[2];
1003         content->valuation = pars[3];
1004         return true;
1005 }
int DIL_entry::Get_Semaphore () [inline]
Definition at line 672 of file dil2al.hh.
References semaphore.
Referenced by Has_Superiors().
672 { return semaphore; }
bool DIL_entry::Has_Superiors (bool taggedonly = false)
Definition at line 1027 of file utilities.cc.
References Get_Semaphore(), PLL_LOOP_FORWARD, and Projects().
1027                                                      {
1028   // superior references to the DIL entry itself do not count
1029   // if taggedonly==true then only superiors with a set semaphore count
1030   if (taggedonly) {
1031     if (Projects(0)) PLL_LOOP_FORWARD(DIL_AL_List,Projects(0),1) {
1032       DIL_entry * dilsup = e->Superiorbyid();
1033       if ((!(dilsup==this)) && (dilsup->Get_Semaphore()>0)) return true;
1034     }
1035   } else {
1036     if (Projects(0)) PLL_LOOP_FORWARD(DIL_AL_List,Projects(0),1) if (!(e->Superiorbyid()==this)) return true;
1037   }
1038   return false;
1039 }
bool DIL_entry::Is_Dependency_Of (DIL_entry * superior)
Definition at line 1016 of file utilities.cc.
References EOUT.
Referenced by generate_AL().
1016                                                      {
1017 // checks if this DIL entry is a dependency of superior
1018 // superior==NULL is interpreted as "all"
1019 // dependencies do not need to be direct
1020         if (!superior) return true;
1021 // *** Implement DIL hierarchy, use the Set_Semaphores
1022 //     recursive approach as in Target_Date()
1023         EOUT << "WARNING: DIL_entry::Is_Dependency_Of() is not yet implemented!\n";
1024         return true;
1025 }
bool DIL_entry::Is_Direct_Dependency_Of (const DIL_entry * superior)
Definition at line 1007 of file utilities.cc.
References PLL_LOOP_FORWARD, and Projects().
1007                                                                   {
1008 // checks if this DIL entry points to superior through one of its
1009 // DIL_AL_List references
1010 // A self-reference is not reported as a direct dependency.
1011         if (superior==this) return false;
1012         if (Projects(0)) PLL_LOOP_FORWARD(DIL_AL_List,Projects(0),1) if (e->Superiorbyid()==superior) return true;
1013         return false;
1014 }
int DIL_entry::Is_Plan_Entry ()
Definition at line 1041 of file utilities.cc.
References content, EOUT, DIL_entry_content::Is_Plan_Entry(), and PLAN_ENTRY_TYPE_UNASSIGNED.
Referenced by generate_modify_element_FORM_interface_DIL_entry_content(), generate_modify_element_FORM_interface_DIL_entry_parameters(), and DIL_Visualize_with_FORM_Tabs::Visualize_Plan_Entry().
1041                              {
1042   // attempts to determine if the DIL entry content contains PLAN entry data
1043   if (!content) {
1044     EOUT << "dil2al: Warning - no content available for DIL_entry::Is_Plan_Entry() --- obtaining content automatically is not yet implemented, continuing as is\n";
1045     return PLAN_ENTRY_TYPE_UNASSIGNED;
1046   }
1047   return content->Is_Plan_Entry();
1048 }
time_t DIL_entry::Local_Target_Date (int n, time_t unspecified = -2) [inline]
Definition at line 681 of file dil2al.hh.
References Projects(), and DIL_AL_List::targetdate().
Referenced by modify_DIL_group_target_dates(), and modify_DIL_group_target_dates_cmd().
681 { if (Projects(n)) return Projects(n)->targetdate(); return unspecified; }
DIL_entry* DIL_entry::operator[] (DIL_ID & id) [inline]
Definition at line 668 of file dil2al.hh.
References elbyid().
668 { return elbyid(id); }
DIL_AL_List* DIL_entry::Projects (int n) [inline]
Definition at line 670 of file dil2al.hh.
References PLLHandle< DIL_AL_List >::el(), PLLRoot< DIL_AL_List >::head(), and DIL_entry_parameters::projects.
Referenced by generate_modify_element_FORM_interface_DIL_entry_parameters(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), Has_Superiors(), Is_Direct_Dependency_Of(), Local_Target_Date(), modify_DIL_entry_target_date(), modify_DIL_group_target_dates(), modify_element_through_FORM_interface(), Show_DIL_Hierarchy(), and update_DIL_entry_parameter_elements().
670 { if (parameters) if (parameters->projects.head()) return parameters->projects.head()->el(n); return NULL; }
time_t DIL_entry::Propagated_Target_Date (bool warn, bool top = true) const
Definition at line 929 of file utilities.cc.
References DIL_ID::chars(), DIL_entry(), elbyid(), PLLHandle< DIL_entry >::head(), PLLRoot< DIL_AL_List >::head(), MAXTIME_T, parameters, PLL_LOOP_FORWARD, DIL_entry_parameters::projects, semaphore, Set_Semaphores(), DIL_ID::str(), Target_Date(), TD_PROTECT, DIL_ID::valid(), and VOUT.
Referenced by Target_Date().
929                                                                          {
930 #else
931 time_t DIL_entry::Propagated_Target_Date(bool warn) const {
932 #endif
933 // return nearest target date, as given for this DIL entry in
934 // relation to one of its project superiors, or as given for its
935 // project superiors, or MAXTIME_T
936 // *** could implement a local buffer for superior target date
937 //     look-ups, but such a buffer must be refreshed if local
938 //     or relevant superior target dates are changed
939 #ifdef LOOP_PROTECT
940         if ((!top) && (!semaphore)) {
941                 if (warn) {
942                         if (!looplist) looplist = new Detailed_Items_List();
943                         DIL_entry * lhde = looplist->list.head();
944                         if ((!lhde) || (!lhde->elbyid(*this))) { // add to looplist
945 //                      if ((!lhde) || (!lhde->elbyid(*(static_cast<DIL_ID *>(this))))) { // add to looplist
946                                 String ldeid(chars());
947                                 DIL_entry * lde = new DIL_entry(*looplist,ldeid);
948                                 looplist->list.link_before(lde);
949                         }
950                 }
951                 return MAXTIME_T;
952         }
953 #endif
954         DIL_entry * sup;
955         time_t t = MAXTIME_T; // default where no target date is known
956         // priority target dates are target dates specific to this DIL entry
957         if (parameters) PLL_LOOP_FORWARD(DIL_AL_List,parameters->projects.head(),1) {
958                 time_t tdate = e->targetdate();
959                 if (tdate<0) { // missing target dates are obtained from the corresponding project superior
960                         // *** this can be made more efficient once the pointers to
961                         //     superiors are implemented
962                         if (str()!=e->al.title) { // not self-referential
963                                 DIL_ID did(e->al.title);
964                                 if (did.valid()) {
965                                         sup = elbyid(did);
966                                         if (sup) {
967 #ifdef LOOP_PROTECT
968                                                 if (top) head()->Set_Semaphores(TD_PROTECT);
969                                                 semaphore = 0; // set this one parsed
970                                                 tdate = sup->Target_Date(false);
971 #else
972                                                 tdate = sup->Target_Date();
973 #endif
974                                         } else {
975                                                 if (warn) VOUT << "dil2al: Warning - Superior DIL#" << did.chars() << " not found in Target_Date() at DIL#" << chars() << '\n';
976                                                 tdate = MAXTIME_T;
977                                         }
978                                 } else {
979                                         if (warn) VOUT << "dil2al: Warning - Invalid superior reference detected in Target_Date() at DIL#" << chars() << '\n';
980                                         tdate = MAXTIME_T;
981                                 }
982                         } else {
983                                 if (warn) VOUT << "dil2al: Warning - Self-reference without specific target date detected in Target_Date() at DIL#" << chars() << '\n';
984                                 tdate = MAXTIME_T;
985                         }
986                 }
987                 if (tdate<t) t = tdate;
988         }
989         return t;
990 }
bool DIL_entry::Read_from_Binary_Cache (ifstream & cfl)
Definition at line 1070 of file utilities.cc.
References parameters, DIL_ID::Read_DIL_ID_from_Binary_Cache(), DIL_entry_parameters::Read_from_Binary_Cache(), READSOMETYPE, and VOUT.
Referenced by Detailed_Items_List::Read_from_Binary_Cache().
1070                                                      {
1071   // Reads a DIL entry from a binary cache file and sets the DIL ID
1072   // DIL_ID
1073   if (!Read_DIL_ID_from_Binary_Cache(cfl)) return false;
1074   bool hasparameters;
1075   if ((cfl.read((READSOMETYPE) (&hasparameters), sizeof(hasparameters))).gcount()<sizeof(hasparameters)) return false;
1076   if (!hasparameters) return true;
1077   // parameters
1078   delete parameters; // clear any previous allocation and parameter values
1079   parameters = new DIL_entry_parameters(*this);
1080 #ifdef TEST_CACHE_READ
1081   VOUT << "&&& parameters = " << (long) parameters << '\n'; cout.flush();
1082 #endif
1083   return parameters->Read_from_Binary_Cache(cfl);
1084 }
bool DIL_entry::Read_Topical_from_Binary_Cache (ifstream & cfl, bool gottext)
Definition at line 1086 of file utilities.cc.
References content, DIL_entry_content::Read_Topical_from_Binary_Cache(), READSOMETYPE, and VOUT.
Referenced by Detailed_Items_List::Read_Topical_from_Binary_Cache().
1086                                                                            {
1087   // Reads a DIL entry from a binary cache file and sets the DIL ID
1088   // DIL_ID
1089   // done in outer loop: if (!Read_DIL_ID_from_Binary_Cache(cfl)) return false;
1090   bool hascontent;
1091   if ((cfl.read((READSOMETYPE) (&hascontent), sizeof(hascontent))).gcount()<sizeof(hascontent)) return false;
1092 #ifdef TEST_CACHE_READ
1093   VOUT << "&&& hascontent = " << hascontent << '\n'; cout.flush();
1094 #endif
1095   if (!hascontent) return true;
1096   // content
1097 #ifdef TEST_CACHE_READ
1098   VOUT << "&&& content (before clearing) = " << (long) content << '\n'; cout.flush();
1099 #endif
1100   delete content; // clear any previous allocation and content
1101   content = new DIL_entry_content(*this);
1102 #ifdef TEST_CACHE_READ
1103   VOUT << "&&& content (after clearing) = " << (long) content << '\n'; cout.flush();
1104 #endif
1105   return content->Read_Topical_from_Binary_Cache(cfl,gottext);
1106 }
void DIL_entry::Set_Semaphore (int svalue) [inline]
Definition at line 671 of file dil2al.hh.
References semaphore.
671 { semaphore = svalue; }
void DIL_entry::Set_Semaphores (int svalue) [inline]
Definition at line 673 of file dil2al.hh.
References PLLHandle< DIL_entry >::Next(), and semaphore.
Referenced by Propagated_Target_Date(), and Tabbed_FORM_DIL_Hierarchy_full().
673 { semaphore = svalue; if (Next()) Next()->Set_Semaphores(svalue); }
time_t DIL_entry::Target_Date (bool top = true) const [inline]
Definition at line 676 of file dil2al.hh.
References Propagated_Target_Date().
Referenced by AL_Day::Add_Target_Date(), AL_Day::add_TCs(), generate_AL(), Active_List::generate_focused_AL(), modify_DIL_entry_target_date(), modify_DIL_group_target_dates(), and Propagated_Target_Date().
676 { return Propagated_Target_Date(true,top); }
time_t DIL_entry::Time_Required () [inline]
Definition at line 682 of file dil2al.hh.
References DIL_entry_content::required.
Referenced by DIL_Required_Task_Chunks().
682 { if (content) return content->required; return (time_t) 0; }
DIL_Topical_List* DIL_entry::Topics (int n) [inline]
Definition at line 669 of file dil2al.hh.
References PLLHandle< DIL_Topical_List >::el(), PLLRoot< DIL_Topical_List >::head(), and DIL_entry_parameters::topics.
Referenced by generate_AL(), Active_List::generate_focused_AL(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), update_DIL_entry_elements(), DIL_Visualize_with_FORM_Tabs::Visualize_Element(), and DIL_Visualize_with_HTML_Tabs::Visualize_Element().
669 { if (parameters) if (parameters->topics.head()) return parameters->topics.head()->el(n); return NULL; }
bool DIL_entry::Write_to_Binary_Cache (ofstream & cfl)
Definition at line 1050 of file utilities.cc.
References parameters, DIL_ID::Write_DIL_ID_to_Binary_Cache(), and DIL_entry_parameters::Write_to_Binary_Cache().
1050                                                     {
1051   // DIL_ID
1052   if (!Write_DIL_ID_to_Binary_Cache(cfl)) return false;
1053   bool hasparameters = (parameters!=NULL);
1054   cfl.write((const void *) (&hasparameters), sizeof(hasparameters));
1055   if (!hasparameters) return true;
1056   // parameters
1057   return parameters->Write_to_Binary_Cache(cfl);
1058 }
bool DIL_entry::Write_Topical_to_Binary_Cache (ofstream & cfl, bool gottext)
Definition at line 1060 of file utilities.cc.
References content, DIL_ID::Write_DIL_ID_to_Binary_Cache(), and DIL_entry_content::Write_Topical_to_Binary_Cache().
1060                                                                           {
1061   // DIL_ID
1062   if (!Write_DIL_ID_to_Binary_Cache(cfl)) return false;
1063   bool hascontent = (content!=NULL);
1064   cfl.write((const void *) (&hascontent), sizeof(hascontent));
1065   if (!hascontent) return true;
1066   // content
1067   return content->Write_Topical_to_Binary_Cache(cfl,gottext);
1068 }
Member Data Documentation
DIL_entry_content* DIL_entry::content
Definition at line 662 of file dil2al.hh.
Referenced by Binary_Cache_Diagnostic(), generate_modify_element_FORM_interface_DIL_entry_content(), Detailed_Items_List::Get_All_Topical_DIL_Parameters(), Get_Entry_Parameters(), Is_Plan_Entry(), Plan_entry_content::Parse_Entry_Content(), Read_Topical_from_Binary_Cache(), DIL_Visualize_with_FORM_Tabs::Visualize_Element(), DIL_Visualize_with_FORM_Tabs::Visualize_Plan_Entry(), Write_Topical_to_Binary_Cache(), and ~DIL_entry().
DIL_entry_parameters* DIL_entry::parameters
Definition at line 663 of file dil2al.hh.
Referenced by Binary_Cache_Diagnostic(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), modify_DIL_entry_target_date(), modify_DIL_group_target_dates(), modify_DIL_group_target_dates_cmd(), Propagated_Target_Date(), Read_from_Binary_Cache(), update_DIL_entry_parameter_elements(), Write_to_Binary_Cache(), Detailed_Items_List::Write_to_File(), and ~DIL_entry().
int DIL_entry::semaphore [protected]
Definition at line 652 of file dil2al.hh.
Referenced by Get_Semaphore(), Propagated_Target_Date(), Set_Semaphore(), and Set_Semaphores().
Text_File_Buffers* DIL_entry::tfb [protected]
Definition at line 653 of file dil2al.hh.
The documentation for this class was generated from the following files:
dil2al.hh
utilities.cc