Financial_Monthly_Category Class Reference
#include <dil2al.hh>
Public Methods
Financial_Monthly_Category (String c, double r=0.0)
String Category () const
Financial_Monthly_Category * Find_Category (String c) const
double Result () const
void Copy_SubCategories (Financial_Monthly_Category *c)
void add (String s, double e, Financial_Monthly &month)
Public Attributes
PLLRoot< Financial_Monthly_SubCategory > subcategories
Protected Attributes
String category
double result
Constructor & Destructor Documentation
Financial_Monthly_Category::Financial_Monthly_Category (String c, double r = 0.0) [inline]
Definition at line 1121 of file dil2al.hh.
References result.
1121 : category(c), result(r) {}
Member Function Documentation
void Financial_Monthly_Category::add (String s, double e, Financial_Monthly & month)
Definition at line 175 of file finances.cc.
References Financial_Monthly_SubCategory::add(), category, Financial_Monthly_SubCategory::Find_SubCategory(), PLLHandle< Financial_Monthly >::head(), PLLRoot< Financial_Monthly_SubCategory >::head(), String::index(), PLLRoot< Financial_Monthly_SubCategory >::link_before(), PLL_LOOP_FORWARD, result, String::sub(), subcategories, and PLLRoot< Financial_Monthly_SubCategory >::tail().
Referenced by Financial_Monthly::add().
175                                                                                   {
176   // add to result and by subcategory
177   result += e;
178   if (s.index(BRXidentifier)<0) s = "general";
179   else s = s.sub(BRXidentifier,0);
180   Financial_Monthly_SubCategory * fs = NULL;
181   if (subcategories.head()) fs = subcategories.head()->Find_SubCategory(s);
182   if (!fs) { // add subcategory in this category in all months
183     PLL_LOOP_FORWARD(Financial_Monthly,month.head(),1) {
184       Financial_Monthly_Category * fc = e->categories.head()->Find_Category(category);
185       fs = new Financial_Monthly_SubCategory(s);
186       fc->subcategories.link_before(fs);
187     }
188     fs = subcategories.tail(); // retrieve subcategory in this month and category
189   }
190   // add to subcategory result
191   fs->add(e);
192 }
String Financial_Monthly_Category::Category () const [inline]
Definition at line 1123 of file dil2al.hh.
1123 { return category; }
void Financial_Monthly_Category::Copy_SubCategories (Financial_Monthly_Category * c)
Definition at line 167 of file finances.cc.
References PLLRoot< Financial_Monthly_SubCategory >::head(), PLLRoot< Financial_Monthly_SubCategory >::link_before(), PLL_LOOP_FORWARD, and subcategories.
Referenced by Financial_Monthly::Copy_Categories().
167                                                                                   {
168   if (c==this) return; // no other category to copy from
169   PLL_LOOP_FORWARD(Financial_Monthly_SubCategory,c->subcategories.head(),1) {
170     Financial_Monthly_SubCategory * fs = new Financial_Monthly_SubCategory(e->SubCategory());
171     subcategories.link_before(fs);
172   }
173 }
Financial_Monthly_Category * Financial_Monthly_Category::Find_Category (String c) const
Definition at line 161 of file finances.cc.
References category, and PLLHandle< Financial_Monthly_Category >::Next().
Referenced by Financial_Monthly::add().
161                                                                                      {
162   if (category==c) return const_cast<Financial_Monthly_Category *>(this);
163   if (Next()) return Next()->Find_Category(c);
164   return NULL;
165 }
double Financial_Monthly_Category::Result () const [inline]
Definition at line 1125 of file dil2al.hh.
References result.
1125 { return result; }
Member Data Documentation
String Financial_Monthly_Category::category [protected]
Definition at line 1118 of file dil2al.hh.
Referenced by add(), and Find_Category().
double Financial_Monthly_Category::result [protected]
Definition at line 1119 of file dil2al.hh.
Referenced by add(), Financial_Monthly_Category(), and Result().
PLLRoot<Financial_Monthly_SubCategory> Financial_Monthly_Category::subcategories
Definition at line 1122 of file dil2al.hh.
Referenced by add(), and Copy_SubCategories().
The documentation for this class was generated from the following files:
dil2al.hh
finances.cc