Target_Access Class Reference
#include <dil2al.hh>
Public Types
enum Target_Access_types { TA_LOCAL,
TA_LOCAL_DIRECTORY,
TA_HTTP,
TA_FTP,
TA_UNKNOWN
 }
Public Methods
Target_Access (const char *t)
Target_Access (const Target_Access &t)
Target_Access (const Target_Access &parent, const char *t)
int isequal (const Target_Access &ta) const
int operator== (const Target_Access &ta) const
int operator!= (const Target_Access &ta) const
bool make_local_copy ()
bool uncompress ()
bool cleartext_conversion ()
bool read_raw_into_String (String &text, bool warnopen=true)
bool read_uncompressed_into_String (String &text, bool warnopen=true)
bool read_cleartext_into_String (String &text, bool warnopen=true)
void remove_local_copy ()
void remove_uncompressed ()
void remove_cleartext ()
String Target () const
Target_Access_types Type () const
void Retain_Transformed ()
void Discard_Transformed ()
Protected Methods
void set_target (const char *t, const Target_Access *parent=NULL)
void remove_name_reference (String &tpath)
void remove_back_references (String &tpath)
void transformed_name (String &transformed, String &prevname)
void transformed_name (String &transformed, String &prevname, const BigRegex &transrx)
bool make_local_copy_of_directory ()
bool make_local_copy_of_HTTP ()
bool make_local_copy_of_FTP ()
bool syscommand (String program, String args, int success=0) const
Protected Attributes
String target
String user
String server
String path
Target_Access_types type
String localcopy
String uncompressed
String cleartext
bool retaintransformed
Member Enumeration Documentation
enum Target_Access::Target_Access_types
Enumeration values:
TA_LOCAL
TA_LOCAL_DIRECTORY
TA_HTTP
TA_FTP
TA_UNKNOWN
Definition at line 974 of file dil2al.hh.
Referenced by Type().
974 { TA_LOCAL, TA_LOCAL_DIRECTORY, TA_HTTP, TA_FTP, TA_UNKNOWN };
Constructor & Destructor Documentation
Target_Access::Target_Access (const char * t) [inline]
Definition at line 992 of file dil2al.hh.
References false, retaintransformed, and set_target().
992 : localcopy(""), uncompressed(""), cleartext(""), retaintransformed(false) { set_target(t); }
Target_Access::Target_Access (const Target_Access & t) [inline]
Definition at line 993 of file dil2al.hh.
References retaintransformed, and type.
993 : target(t.target), user(t.user), server(t.server), path(t.path), type(t.type), localcopy(t.localcopy), uncompressed(t.uncompressed), cleartext(t.cleartext), retaintransformed(t.retaintransformed) {}
Target_Access::Target_Access (const Target_Access & parent, const char * t) [inline]
Definition at line 994 of file dil2al.hh.
References false, retaintransformed, and set_target().
994 : localcopy(""), uncompressed(""), cleartext(""), retaintransformed(false) { set_target(t,&parent); } // relative to parent target
Member Function Documentation
bool Target_Access::cleartext_conversion ()
Definition at line 232 of file search.cc.
References cleartext, String::contains(), String::empty(), syscommand(), transformed_name(), uncompress(), and uncompressed.
Referenced by read_cleartext_into_String().
232                                          {
233         // makes sure a clear text version is available
234         if (!cleartext.empty()) return true;
235         if (!uncompress()) return false;
236         const BigRegex psrx("[.][Pp][Ss]$"); const BigRegex pdfrx("[.][Pp][Dd][Ff]$");
237         if (uncompressed.contains(psrx)) {
238                 transformed_name(cleartext,uncompressed,psrx);
239                 remove(cleartext); // remove possible stale file
240                 if (!syscommand("pstotext",uncompressed+" > "+cleartext)) return false;
241         } else if (uncompressed.contains(pdfrx)) {
242                 transformed_name(cleartext,uncompressed,pdfrx);
243                 remove(cleartext); // remove possible stale file
244                 if (!syscommand("pdftotext","-raw "+uncompressed+' '+cleartext)) return false;
245         } else cleartext = uncompressed;
246 //cerr << "Cleartext: " << cleartext << '\n';
247         return true;
248 }
void Target_Access::Discard_Transformed () [inline]
Definition at line 1010 of file dil2al.hh.
References retaintransformed.
1010 { retaintransformed = false; }
int Target_Access::isequal (const Target_Access & ta) const [inline]
Definition at line 995 of file dil2al.hh.
References target.
Referenced by operator!=(), and operator==().
995 { return (target==ta.target); }
bool Target_Access::make_local_copy ()
Definition at line 181 of file search.cc.
References String::empty(), EOUT, localcopy, make_local_copy_of_directory(), make_local_copy_of_FTP(), make_local_copy_of_HTTP(), path, TA_HTTP, TA_LOCAL, TA_LOCAL_DIRECTORY, TA_UNKNOWN, target, transformed_name(), and type.
Referenced by read_raw_into_String(), and uncompress().
181                                     {
182         // makes sure a local copy is available
183         if (!localcopy.empty()) return true;
184         if (type==TA_UNKNOWN) {
185                 if (verbose) EOUT << "dil2al: Unable to access unknown target type in Target_Access::make_local_copy()\n";
186                 return false;
187         }
188         if (type==TA_LOCAL) localcopy = path;
189         else if (type==TA_LOCAL_DIRECTORY) {
190                 transformed_name(localcopy,path);
191                 remove(localcopy); // remove possible stale file
192                 return make_local_copy_of_directory();
193         } else {
194                 transformed_name(localcopy,target);
195                 remove(localcopy); // remove possible stale file
196                 if (type==TA_HTTP) return make_local_copy_of_HTTP();
197                 else return make_local_copy_of_FTP();
198         }
199         return true;
200 }
bool Target_Access::make_local_copy_of_directory () [protected]
Definition at line 145 of file search.cc.
References Get_Target_Directory(), HTML_put_href(), localcopy, path, and write_file_from_String().
Referenced by make_local_copy().
145                                                  {
146         // create HTML list of links for directory entries
147         // Note: localcopy must point to a valid temporary file name
148         // get directory
149         StringList dirtargets;
150         unsigned long num = Get_Target_Directory(dirtargets,0,path);
151         // create HTML links
152         String dirfile("<HTML>\n<HEAD>\n<TITLE>Local Directory: "+path+"</TITLE>\n</HEAD>\n<BODY>\n<H1>Local Directory: "+path+"</H1>\n\n");
153         for (unsigned long i = 0; i<num; i++) dirfile += HTML_put_href(dirtargets[i],dirtargets[i].after('/',-1)) + "\n<P>\n";
154         dirfile += "(Temporary local HTML copy of directory created by dil2al "+curtime+")\n\n</BODY>\n</HTML>\n";
155         // write local file
156         write_file_from_String(localcopy,dirfile,"",true); // message used to be: "Local copy of "+path+" directory"
157         return true;
158 }
bool Target_Access::make_local_copy_of_FTP () [protected]
Definition at line 172 of file search.cc.
References localcopy, syscommand(), and target.
Referenced by make_local_copy().
172                                           {
173         // Note: The wget utility has a smaller footprint than the lynx browser, but
174         // has some difficulties with unresponsive connections, as it tends to wait
175         // just as long for a connection as it does between network packages (specified
176         // with the -T option, with a default of 15 minutes).
177         return syscommand("lynx","-connect_timeout=30 -source "+target+" > "+localcopy);
178         //return syscommand("wget","-q -t 2 --retr-symlinks -O "+localcopy+' '+target);
179 }
bool Target_Access::make_local_copy_of_HTTP () [protected]
Definition at line 160 of file search.cc.
References localcopy, syscommand(), and target.
Referenced by make_local_copy().
160                                            {
161         // Note: The wget utility has a smaller footprint than the lynx browser, but
162         // has some difficulties with unresponsive connections, as it tends to wait
163         // just as long for a connection as it does between network packages (specified
164         // with the -T option, with a default of 15 minutes).
165         // *** An alternative solution for this is to do searching or at least remote
166         //     retrieval in the background with multiple threads, as indicated in the
167         //     DIL entry <A HREF="../../doc/html/lists/dil2al.html#20000930123422.1">DIL#20000930123422.1</A>.
168         return syscommand("lynx","-connect_timeout=30 -source "+target+" > "+localcopy);
169         //return syscommand("wget","-q -t 2 -O "+localcopy+' '+target);
170 }
int Target_Access::operator!= (const Target_Access & ta) const [inline]
Definition at line 997 of file dil2al.hh.
References isequal().
997 { return (!isequal(ta)); }
int Target_Access::operator== (const Target_Access & ta) const [inline]
Definition at line 996 of file dil2al.hh.
References isequal().
996 { return isequal(ta); }
bool Target_Access::read_cleartext_into_String (String & text, bool warnopen = true)
Definition at line 267 of file search.cc.
References cleartext, cleartext_conversion(), read_file_into_String(), remove_cleartext(), remove_local_copy(), remove_uncompressed(), and retaintransformed.
Referenced by Search_Target::search().
267                                                                                   {
268         if (!cleartext_conversion()) return false;
269         if (!read_file_into_String(cleartext,text,warnopen)) return false;
270         if (!retaintransformed) {
271                 remove_cleartext();
272                 remove_uncompressed();
273                 remove_local_copy();
274         }
275         return true;
276 }
bool Target_Access::read_raw_into_String (String & text, bool warnopen = true)
Definition at line 250 of file search.cc.
References localcopy, make_local_copy(), read_file_into_String(), remove_local_copy(), and retaintransformed.
250                                                                             {
251         if (!make_local_copy()) return false;
252         if (!read_file_into_String(localcopy,text,warnopen)) return false;
253         if (!retaintransformed) remove_local_copy();
254         return true;
255 }
bool Target_Access::read_uncompressed_into_String (String & text, bool warnopen = true)
Definition at line 257 of file search.cc.
References read_file_into_String(), remove_local_copy(), remove_uncompressed(), retaintransformed, uncompress(), and uncompressed.
257                                                                                      {
258         if (!uncompress()) return false;
259         if (!read_file_into_String(uncompressed,text,warnopen)) return false;
260         if (!retaintransformed) {
261                 remove_uncompressed();
262                 remove_local_copy();
263         }
264         return true;
265 }
void Target_Access::remove_back_references (String & tpath) [protected]
Definition at line 105 of file search.cc.
References String::del(), String::firstchar(), String::gsub(), String::index(), and String::length().
Referenced by set_target().
105                                                          {
106         // Removes ./ and ../ references from a path
107         tpath.gsub("/./","/");
108         if ((tpath.firstchar()=='.') && (tpath[1]=='/')) tpath.del(0,2);
109         int i, j;
110         while ((i=tpath.index("/../"))>=0) {
111                 if ((j=tpath.index('/',(i-tpath.length())-1))<0) j=-1;
112                 j++;
113                 tpath.del(j,(i-j)+4);
114         }
115 }
void Target_Access::remove_cleartext () [inline]
Definition at line 1006 of file dil2al.hh.
References String::empty().
Referenced by read_cleartext_into_String().
1006 { if (!cleartext.empty()) { if (cleartext!=path) remove(cleartext); cleartext = ""; } }
void Target_Access::remove_local_copy () [inline]
Definition at line 1004 of file dil2al.hh.
References String::empty(), TA_LOCAL, and type.
Referenced by read_cleartext_into_String(), read_raw_into_String(), and read_uncompressed_into_String().
1004 { if (!localcopy.empty()) { if (type!=TA_LOCAL) remove(localcopy); localcopy = ""; } }
void Target_Access::remove_name_reference (String & tpath) [protected]
Definition at line 100 of file search.cc.
References generic_remove_name_reference(), TA_HTTP, and type.
Referenced by set_target().
100                                                         {
101         // Removes a potential #name reference from an http target or path
102         if (type == TA_HTTP) generic_remove_name_reference(tpath);
103 }
void Target_Access::remove_uncompressed () [inline]
Definition at line 1005 of file dil2al.hh.
References String::empty().
Referenced by read_cleartext_into_String(), and read_uncompressed_into_String().
1005 { if (!uncompressed.empty()) { if (uncompressed!=path) remove(uncompressed); uncompressed = ""; } }
void Target_Access::Retain_Transformed () [inline]
Definition at line 1009 of file dil2al.hh.
References retaintransformed.
1009 { retaintransformed = true; } // mode selector: whether to keep transformed versions or not
void Target_Access::set_target (const char * t, const Target_Access * parent = NULL) [protected]
Definition at line 21 of file search.cc.
References String::after(), String::at(), String::before(), String::empty(), EOUT, file_is_directory(), String::firstchar(), String::from(), String::index(), String::length(), path, String::prepend(), remove_back_references(), remove_name_reference(), String::SEARCH_END, server, TA_FTP, TA_HTTP, TA_LOCAL, TA_LOCAL_DIRECTORY, TA_UNKNOWN, target, type, String::upcase, and user.
Referenced by Target_Access().
21                                                                                   {
22         // Identify type of target and verify proper specification
23                                 // *** generate new target, target is local if relative and current is local, followlinks-1
24                                 // - put absolute file references in as such + server&user if current is remote
25                                 // - append relative file references to current target
26         // Note: This function is currently not intended to be used to reinitialize Target_Access objects,
27         // as it does not reset server and user parameters if the new target is local
28         target = t;
29         String preslash(target.before('/'));
30         preslash.upcase();
31         if ((preslash == "HTTP:") || (preslash == "FTP:")) { // Server and path references for URLs
32                 if (preslash == "HTTP:") type = TA_HTTP;
33                 else type = TA_FTP;
34                 remove_name_reference(target);
35                 int serverstart = target.index("://",String::SEARCH_END,0);
36                 if (serverstart<0) {
37                         if (verbose) EOUT << "dil2al: Warning - malformed URL, " << target << ", in Target_Access::Target_Access()\n";
38                         type = TA_UNKNOWN;
39                         return;
40                 }
41                 int serverend = target.index('/',serverstart);
42                 if (serverend<0) serverend = target.length();
43                 if (serverstart==serverend) {
44                         if (verbose) EOUT << "dil2al: Warning - malformed URL server, " << target << ", in Target_Access::Target_Access()\n";
45                         type = TA_UNKNOWN;
46                         return;
47                 }
48                 server = target.at(serverstart,serverend-serverstart);
49                 path = target.from(serverend);
50                 if (type == TA_HTTP) return;
51                 // FTP specific initialization
52                 user = server.before('@');
53                 if (!user.empty()) server = server.after('@');
54                 return;
55         }
56         // Local file specific initialization
57         path = target;
58         if (parent) { // reference relative to parent
59                 if ((parent->type==TA_HTTP) || (parent->type==TA_FTP)) { // relative to remote
60                         type = parent->type;
61                         server = parent->server;
62                         user = parent->user;
63                         // *** problem: if parent target was an ftp or http directory without a '/' at
64                         //     the end, then there is no way to know if the last part of the target path
65                         //     is part of the path to prepend or not
66                         //     You actually *have* this information, because if you are setting up a
67                         //     target relative to a parent, then you have that parent's contents, from
68                         //     which you got the link... so you can see if it's a directory index
69                         // *** problem: at some point between reading the citeseer site and the nec.com
70                         //     site, dil2al appears to develop a memory leak and grows rapidly then crashes
71                         // *** problem: there has to be another way around the long wget wait for
72                         //     connections, perhaps a site's availability can be tested some other way
73                         //     before attempting a wget
74                         remove_name_reference(path);
75                         if (path.firstchar()!='/') path.prepend(const_cast<String &>(parent->path).through('/',-1));
76                         remove_back_references(path);
77                         if (type==TA_HTTP) target = "http://"+server+path;
78                         else target = "ftp://"+user+'@'+server+path;
79                         return;
80                 } else if (path.firstchar()!='/') { // relative to local
81                         if (parent->type==TA_LOCAL_DIRECTORY) {
82                                 if (parent->path.lastchar()!='/') path.prepend('/');
83                                 path.prepend(parent->path);
84                         } else path.prepend(const_cast<String &>(parent->path).through('/',-1));
85                 }
86         }
87         // local reference
88         remove_back_references(path);
89         target = path; // complete local target reference
90         if (file_is_directory(path)) type = TA_LOCAL_DIRECTORY;
91         else type = TA_LOCAL;
92 }
bool Target_Access::syscommand (String program, String args, int success = 0) const [protected]
Definition at line 202 of file search.cc.
References EOUT.
Referenced by cleartext_conversion(), make_local_copy_of_FTP(), make_local_copy_of_HTTP(), and uncompress().
202                                                                                  {
203         int sysret = system(program+' '+args);
204         if (sysret==success) return true;
205         switch (sysret) {
206                 case -1:
207                         EOUT << "dil2al: Error in system(<" << program << ">) call in Target_Access::syscommand()\n";
208                         return false;
209                 case 127:
210                         EOUT << "dil2al: Execve() call for /bin/sh failed in Target_Access::syscommand()\n";
211                         return false;
212                 default:
213                         EOUT << "dil2al: Return value of " << program << " was " << sysret << " in Target_Access::syscommand()\n";
214                         return false;
215         }
216 }
String Target_Access::Target () const [inline]
Definition at line 1007 of file dil2al.hh.
Referenced by Search_Target::check_encountered(), Search_Result::HTML_put_text(), Search_Target::search(), and Search_Target::Target().
1007 { return target; }
void Target_Access::transformed_name (String & transformed, String & prevname, const BigRegex & transrx) [protected]
Definition at line 140 of file search.cc.
References String::before(), BigRegex::subpos(), and transformed_name().
140                                                                                                       {
141         transformed = prevname.before(transrx.subpos());
142         transformed_name(transformed,prevname);
143 }
void Target_Access::transformed_name (String & transformed, String & prevname) [protected]
Definition at line 132 of file search.cc.
References String::empty(), String::gsub(), path, String::prepend(), and target.
Referenced by cleartext_conversion(), make_local_copy(), transformed_name(), and uncompress().
132                                                                             {
133         if (transformed.empty()) transformed = prevname;
134         if ((prevname==path) || (prevname==target)) {
135                 transformed.gsub('/','%');
136                 transformed.prepend(tareadfile);
137         }
138 }
Target_Access_types Target_Access::Type () const [inline]
Definition at line 1008 of file dil2al.hh.
References Target_Access_types, and type.
Referenced by Search_Target::check_encountered(), and Search_Result::Search_Result().
1008 { return type; }
bool Target_Access::uncompress ()
Definition at line 218 of file search.cc.
References String::contains(), String::empty(), localcopy, make_local_copy(), syscommand(), transformed_name(), and uncompressed.
Referenced by cleartext_conversion(), and read_uncompressed_into_String().
218                                {
219         // makes sure an uncompressed version is available
220         if (!uncompressed.empty()) return true;
221         if (!make_local_copy()) return false;
222         const BigRegex gzrx("[.][Gg]?[Zz]$");
223         if (localcopy.contains(gzrx)) {
224                 transformed_name(uncompressed,localcopy,gzrx);
225 //cerr << "Uncompressed: " << uncompressed << '\n';
226                 remove(uncompressed); // remove possible stale file
227                 if (!syscommand("gzip","-d -c "+localcopy+" > "+uncompressed)) return false;
228         } else uncompressed = localcopy;
229         return true;
230 }
Member Data Documentation
String Target_Access::cleartext [protected]
Definition at line 979 of file dil2al.hh.
Referenced by cleartext_conversion(), and read_cleartext_into_String().
String Target_Access::localcopy [protected]
Definition at line 979 of file dil2al.hh.
Referenced by make_local_copy(), make_local_copy_of_directory(), make_local_copy_of_FTP(), make_local_copy_of_HTTP(), read_raw_into_String(), and uncompress().
String Target_Access::path [protected]
Definition at line 977 of file dil2al.hh.
Referenced by make_local_copy(), make_local_copy_of_directory(), set_target(), and transformed_name().
bool Target_Access::retaintransformed [protected]
Definition at line 980 of file dil2al.hh.
Referenced by Discard_Transformed(), read_cleartext_into_String(), read_raw_into_String(), read_uncompressed_into_String(), Retain_Transformed(), and Target_Access().
String Target_Access::server [protected]
Definition at line 977 of file dil2al.hh.
Referenced by set_target().
String Target_Access::target [protected]
Definition at line 976 of file dil2al.hh.
Referenced by isequal(), make_local_copy(), make_local_copy_of_FTP(), make_local_copy_of_HTTP(), set_target(), and transformed_name().
Target_Access_types Target_Access::type [protected]
Definition at line 978 of file dil2al.hh.
Referenced by make_local_copy(), remove_local_copy(), remove_name_reference(), set_target(), Target_Access(), and Type().
String Target_Access::uncompressed [protected]
Definition at line 979 of file dil2al.hh.
Referenced by cleartext_conversion(), read_uncompressed_into_String(), and uncompress().
String Target_Access::user [protected]
Definition at line 977 of file dil2al.hh.
Referenced by set_target().
The documentation for this class was generated from the following files:
dil2al.hh
search.cc