Time Class Reference
#include <dil2al.hh>
Public Methods
Time ()
Time (time_t tinit)
Time (const char *tlocal, bool withseconds=false)
Time (int h, int m, int s)
void local2caltime (const char *tlocal, bool withseconds=false)
String caltime2local (const char *dateformat)
String caltime2GM (const char *dateformat)
String caltime2interval (const char *dateformat)
time_t date (Time *tdate)
Protected Attributes
time_t t
Constructor & Destructor Documentation
Time::Time () [inline]
Definition at line 84 of file dil2al.hh.
References t.
84 : t(0) {}
Time::Time (time_t tinit) [inline]
Definition at line 85 of file dil2al.hh.
References t.
85 { if (tinit<0) tinit=time(NULL); t=tinit; }
Time::Time (const char * tlocal, bool withseconds = false) [inline]
Definition at line 86 of file dil2al.hh.
References local2caltime().
86 { local2caltime(tlocal,withseconds); }
Time::Time (int h, int m, int s) [inline]
Definition at line 87 of file dil2al.hh.
References t.
87 { t = (((((time_t) h)*60)+((time_t) m))*60)+((time_t) s); }
Member Function Documentation
String Time::caltime2GM (const char * dateformat) [inline]
Definition at line 90 of file dil2al.hh.
Referenced by caltime2interval().
90 {} // time_stamp_GM
String Time::caltime2interval (const char * dateformat) [inline]
Definition at line 91 of file dil2al.hh.
References caltime2GM().
91 { return caltime2GM(dateformat); }
String Time::caltime2local (const char * dateformat)
Definition at line 25 of file utilities.cc.
References t, and time_stamp().
25                                                   {
26         return time_stamp(dateformat,t);
27 }
time_t Time::date (Time * tdate) [inline]
Definition at line 92 of file dil2al.hh.
92 {} // time_stamp_time_date
void Time::local2caltime (const char * tlocal, bool withseconds = false) [inline]
Definition at line 88 of file dil2al.hh.
Referenced by Time().
88 {} // time_stamp_time integrated with time_stamp_time_of_day
Member Data Documentation
time_t Time::t [protected]
Definition at line 82 of file dil2al.hh.
Referenced by caltime2local(), and Time().
The documentation for this class was generated from the following files:
dil2al.hh
utilities.cc