String Class Reference
#include <BigString.hh>
Public Types
enum BigString_Search_t { SEARCH_START,
SEARCH_END
 }
Public Methods
String ()
String (const String &x)
String (const SubString &x)
String (const char *t)
String (const char *t, _BIGSTRING_SIZE len)
String (char c)
String (istream &ist)
String (long l)
String (double d, const char *format)
~String ()
String & operator= (const String &y)
String & operator= (const char *y)
String & operator= (char c)
String & operator= (const SubString &y)
String & operator= (istream &y)
String & readnoseek (istream &y)
String & readtotag (istream &y, const char *t, char terminator='\n')
String & operator+= (const String &y)
String & operator+= (const SubString &y)
String & operator+= (const char *y)
String & operator+= (char c)
String & operator+= (istream &y)
void prepend (const String &y)
void prepend (const SubString &y)
void prepend (const char *t)
void prepend (char c)
_BIGSTRING_SIZE index (char c, _BIGSTRING_SIZE startpos=0) const
_BIGSTRING_SIZE index (const String &y, _BIGSTRING_SIZE startpos=0) const
_BIGSTRING_SIZE index (const SubString &y, _BIGSTRING_SIZE startpos=0) const
_BIGSTRING_SIZE index (const char *t, _BIGSTRING_SIZE startpos=0) const
_BIGSTRING_SIZE index (const BigRegex &r, _BIGSTRING_SIZE startpos=0) const
_BIGSTRING_SIZE index (const BigRegex &r, BigString_Search_t _st, _BIGSTRING_SIZE startpos=0) const
int contains (char c) const
int contains (const String &y) const
int contains (const SubString &y) const
int contains (const char *t) const
int contains (const BigRegex &r) const
int contains (char c, _BIGSTRING_SIZE pos) const
int contains (const String &y, _BIGSTRING_SIZE pos) const
int contains (const SubString &y, _BIGSTRING_SIZE pos) const
int contains (const char *t, _BIGSTRING_SIZE pos) const
int contains (const BigRegex &r, _BIGSTRING_SIZE pos) const
int matches (char c, _BIGSTRING_SIZE pos=0) const
int matches (const String &y, _BIGSTRING_SIZE pos=0) const
int matches (const SubString &y, _BIGSTRING_SIZE pos=0) const
int matches (const char *t, _BIGSTRING_SIZE pos=0) const
int matches (const BigRegex &r, _BIGSTRING_SIZE pos=0) const
_BIGSTRING_SIZE freq (char c) const
_BIGSTRING_SIZE freq (const String &y) const
_BIGSTRING_SIZE freq (const SubString &y) const
_BIGSTRING_SIZE freq (const char *t) const
SubString at (_BIGSTRING_SIZE pos, _BIGSTRING_SIZE len)
SubString operator() (_BIGSTRING_SIZE pos, _BIGSTRING_SIZE len)
SubString at (const String &x, _BIGSTRING_SIZE startpos=0)
SubString at (const SubString &x, _BIGSTRING_SIZE startpos=0)
SubString at (const char *t, _BIGSTRING_SIZE startpos=0)
SubString at (char c, _BIGSTRING_SIZE startpos=0)
SubString at (const BigRegex &r, _BIGSTRING_SIZE startpos=0)
SubString before (_BIGSTRING_SIZE pos)
SubString before (const String &x, _BIGSTRING_SIZE startpos=0)
SubString before (const SubString &x, _BIGSTRING_SIZE startpos=0)
SubString before (const char *t, _BIGSTRING_SIZE startpos=0)
SubString before (char c, _BIGSTRING_SIZE startpos=0)
SubString before (const BigRegex &r, _BIGSTRING_SIZE startpos=0)
SubString through (_BIGSTRING_SIZE pos)
SubString through (const String &x, _BIGSTRING_SIZE startpos=0)
SubString through (const SubString &x, _BIGSTRING_SIZE startpos=0)
SubString through (const char *t, _BIGSTRING_SIZE startpos=0)
SubString through (char c, _BIGSTRING_SIZE startpos=0)
SubString through (const BigRegex &r, _BIGSTRING_SIZE startpos=0)
SubString from (_BIGSTRING_SIZE pos)
SubString from (const String &x, _BIGSTRING_SIZE startpos=0)
SubString from (const SubString &x, _BIGSTRING_SIZE startpos=0)
SubString from (const char *t, _BIGSTRING_SIZE startpos=0)
SubString from (char c, _BIGSTRING_SIZE startpos=0)
SubString from (const BigRegex &r, _BIGSTRING_SIZE startpos=0)
SubString after (_BIGSTRING_SIZE pos)
SubString after (const String &x, _BIGSTRING_SIZE startpos=0)
SubString after (const SubString &x, _BIGSTRING_SIZE startpos=0)
SubString after (const char *t, _BIGSTRING_SIZE startpos=0)
SubString after (char c, _BIGSTRING_SIZE startpos=0)
SubString after (const BigRegex &r, _BIGSTRING_SIZE startpos=0)
String sub (const BigRegex &r, int nth)
void del (_BIGSTRING_SIZE pos, _BIGSTRING_SIZE len)
void del (const String &y, _BIGSTRING_SIZE startpos=0)
void del (const SubString &y, _BIGSTRING_SIZE startpos=0)
void del (const char *t, _BIGSTRING_SIZE startpos=0)
void del (char c, _BIGSTRING_SIZE startpos=0)
void del (const BigRegex &r, _BIGSTRING_SIZE startpos=0)
_BIGSTRING_SIZE gsub (const String &pat, const String &repl)
_BIGSTRING_SIZE gsub (const SubString &pat, const String &repl)
_BIGSTRING_SIZE gsub (const char *pat, const String &repl)
_BIGSTRING_SIZE gsub (const char *pat, const char *repl)
_BIGSTRING_SIZE gsub (const BigRegex &pat, const String &repl, char substrs='\0')
void reverse ()
void upcase ()
void downcase ()
void capitalize ()
char & operator[] (_BIGSTRING_ITERATOR i)
const char & operator[] (_BIGSTRING_ITERATOR i) const
char elem (_BIGSTRING_ITERATOR i) const
char firstchar () const
char lastchar () const
operator const char * () const
const char * chars () const
_BIGSTRING_LENGTH length () const
int empty () const
void alloc (_BIGSTRING_SIZE newsize)
_BIGSTRING_ALLOC allocation () const
void error (const char *msg) const
int OK () const
Protected Methods
_BIGSTRING_SIZE search (_BIGSTRING_SIZE, _BIGSTRING_SIZE, const char *, _BIGSTRING_SIZE=-1) const
_BIGSTRING_SIZE search (_BIGSTRING_SIZE, _BIGSTRING_SIZE, char) const
_BIGSTRING_SIZE match (_BIGSTRING_SIZE, _BIGSTRING_SIZE, int, const char *, _BIGSTRING_SIZE=-1) const
_BIGSTRING_SIZE _gsub (const char *, _BIGSTRING_SIZE, const char *,_BIGSTRING_SIZE)
_BIGSTRING_SIZE _gsub (const BigRegex &, const char *, _BIGSTRING_SIZE, char substrs='\0')
SubString _substr (int, int)
Protected Attributes
StrRep * rep
Friends
class SubString
void cat (const String &, const String &, String &)
void cat (const String &, const SubString &, String &)
void cat (const String &, const char *, String &)
void cat (const String &, char, String &)
void cat (const SubString &, const String &, String &)
void cat (const SubString &, const SubString &, String &)
void cat (const SubString &, const char *, String &)
void cat (const SubString &, char, String &)
void cat (const char *, const String &, String &)
void cat (const char *, const SubString &, String &)
void cat (const char *, const char *, String &)
void cat (const char *, char, String &)
void cat (const String &, const String &, const String &, String &)
void cat (const String &, const String &, const SubString &, String &)
void cat (const String &, const String &, const char *, String &)
void cat (const String &, const String &, char, String &)
void cat (const String &, const SubString &, const String &, String &)
void cat (const String &, const SubString &, const SubString &, String &)
void cat (const String &, const SubString &, const char *, String &)
void cat (const String &, const SubString &, char, String &)
void cat (const String &, const char *, const String &, String &)
void cat (const String &, const char *, const SubString &, String &)
void cat (const String &, const char *, const char *, String &)
void cat (const String &, const char *, char, String &)
void cat (const char *, const String &, const String &, String &)
void cat (const char *, const String &, const SubString &, String &)
void cat (const char *, const String &, const char *, String &)
void cat (const char *, const String &, char, String &)
void cat (const char *, const SubString &, const String &, String &)
void cat (const char *, const SubString &, const SubString &, String &)
void cat (const char *, const SubString &, const char *, String &)
void cat (const char *, const SubString &, char, String &)
void cat (const char *, const char *, const String &, String &)
void cat (const char *, const char *, const SubString &, String &)
void cat (const char *, const char *, const char *, String &)
void cat (const char *, const char *, char, String &)
_BIGSTRING_SIZE split (const String &x, String res[], _BIGSTRING_SIZE maxn, const String &sep)
_BIGSTRING_SIZE split (const String &x, String res[], _BIGSTRING_SIZE maxn, const BigRegex &sep)
String common_prefix (const String &x, const String &y, _BIGSTRING_SIZE startpos=0)
String common_suffix (const String &x, const String &y, _BIGSTRING_SIZE startpos=-1)
String replicate (char c, _BIGSTRING_SIZE n)
String replicate (const String &y, _BIGSTRING_SIZE n)
String join (String src[], _BIGSTRING_SIZE n, const String &sep)
String reverse (const String &x)
String upcase (const String &x)
String downcase (const String &x)
String capitalize (const String &x)
ostream & operator<< (ostream &s, const String &x)
ostream & operator<< (ostream &s, const SubString &x)
istream & operator>> (istream &s, String &x)
_BIGSTRING_SIZE readline (istream &s, String &x, char terminator='\n', int discard_terminator=1)
Member Enumeration Documentation
enum String::BigString_Search_t
Enumeration values:
SEARCH_START
SEARCH_END
Definition at line 288 of file BigString.hh.
288 { SEARCH_START, SEARCH_END };
Constructor & Destructor Documentation
String::String () [inline]
Definition at line 507 of file BigString.hh.
Referenced by sub().
508   : rep(&_nilStrRep) {}
String::String (const String & x) [inline]
Definition at line 509 of file BigString.hh.
510   : rep(Scopy(0, x.rep)) {}
String::String (const SubString & x) [inline]
Definition at line 522 of file BigString.hh.
523   : rep(Salloc(0, y.chars(), y.length(), y.length())) {}
String::String (const char * t) [inline]
Definition at line 511 of file BigString.hh.
512   : rep(Salloc(0, t, -1, -1)) {
513 #ifdef CONSTCHAR_INITIALIZE_TEST
514         cout << "dil2al: Debug CONSTCHAR_INITIALIZE_TEST: ";
515         for (char * tp = (char *) t; *tp!='\0'; tp++) cout << (*tp) << '[' << (int) (*tp) << ']';
516         cout << '\n';
517         cout << '{' << (*this) << "}\n";
518 #endif
519 }
String::String (const char * t, _BIGSTRING_SIZE len) [inline]
Definition at line 520 of file BigString.hh.
References _BIGSTRING_SIZE.
521   : rep(Salloc(0, t, tlen, tlen)) {}
String::String (char c) [inline]
Definition at line 524 of file BigString.hh.
525   : rep(Salloc(0, &c, 1, 1)) {}
String::String (istream & ist) [inline]
Definition at line 527 of file BigString.hh.
528   : rep(Salloc_istream(0,ist,-1,-1)) {}
String::String (long l) [inline]
Definition at line 531 of file BigString.hh.
References rep, and Salloc().
531 { char s[12]; sprintf(s,"%ld",l); rep = Salloc(0,s,-1,-1); }
String::String (double d, const char * format) [inline]
Definition at line 534 of file BigString.hh.
References rep, and Salloc().
534 { char s[30]; sprintf(s,format,d); rep = Salloc(0,s,-1,-1); }
String::~String () [inline]
Definition at line 537 of file BigString.hh.
References rep.
537 { if (rep != &_nilStrRep) delete rep; }
Member Function Documentation
_BIGSTRING_SIZE String::_gsub (const BigRegex &, const char *, _BIGSTRING_SIZE, char substrs = '\0') [protected]
Definition at line 709 of file BigString.cc.
References _BIGSTRING_ITERATOR, _BIGSTRING_SIZE, BIGREGEX_MAX_SUBEXPRESSIONS, chars(), StrRep::len, length(), BigRegex::match_info(), StrRep::s, BigRegex::search(), and StrRep::sz.
709                                                                                                          { 
710 // when substrs is not '\0', substring identifiers
711 // 'substrs'1,'substrs'2, etc. can be used in the replace string
712   char * rloc;
713   _BIGSTRING_SIZE nsubstrs = 0, *substrrl, subrl = 0;
714   int * substrid;
715   char ** substridx;
716   _BIGSTRING_SIZE nmatches = 0;
717   _BIGSTRING_SIZE sl = length();
718   if (sl <= 0)
719     return nmatches;
720 
721   if (rl < 0) rl = slen(r);
722   if (substrs!='\0') {
723                 // (* could increase array lengths, since the number
724                 // of times a subexpression can occur in the replacement
725                 // string is not dependent on the maximum number of
726                 // subexpressions)
727                 substridx = new (char *)[BIGREGEX_MAX_SUBEXPRESSIONS];
728                 substrrl = new _BIGSTRING_SIZE[BIGREGEX_MAX_SUBEXPRESSIONS];
729                 substrid = new int[BIGREGEX_MAX_SUBEXPRESSIONS]; // we don't use substrid[0]
730                 // copy replacement string
731                 rloc = new char[rl+1];
732                 ncopy(r,rloc,rl+1);
733                 // create substrings and store indices
734                 substridx[0] = rloc;
735                 for (int i=0; i<rl; i++) if ((rloc[i]==substrs) && (nsubstrs<(BIGREGEX_MAX_SUBEXPRESSIONS-1))) {
736                         long a = strtol(&rloc[i+1],&(substridx[nsubstrs+1]),10);
737                         if ((a>=0) && (a<BIGREGEX_MAX_SUBEXPRESSIONS)) {
738                                 rloc[i] = '\0';
739                                 substrrl[nsubstrs] = (_BIGSTRING_SIZE) (&(rloc[i]) - substridx[nsubstrs]);
740                                 subrl += substrrl[nsubstrs];
741                                 nsubstrs++;
742                                 substrid[nsubstrs] = a;
743                         } else rloc[i] = r[i];
744                 } else rloc[i] = r[i];
745                 substrrl[nsubstrs] = (_BIGSTRING_SIZE) (&(rloc[rl]) - substridx[nsubstrs]);
746                 subrl += substrrl[nsubstrs];
747   }
748   const char* s = chars();
749 
750   StrRep* nrep = 0;
751   _BIGSTRING_SIZE nsz = 0;
752 
753   char* x = 0;
754 
755   _BIGSTRING_ITERATOR si = 0;
756   _BIGSTRING_ITERATOR xi = 0;
757   _BIGSTRING_SIZE remaining = sl;
758   _BIGSTRING_SIZE  pos, pl = 0;   // how long is a regular expression?
759   int start, length;
760 
761   while (remaining > 0)
762   {
763     pos = pat.search(s, sl, pl, si); // unlike string search, the pos returned here is absolute
764     if (pos < 0 || pl <= 0)
765       break;    // done if not found
766     else
767     {   // found match
768       ++nmatches;
769          if (substrs!='\0') { // rl depends on matched substring sizes
770                 rl = subrl;
771                 for (int i=1; i<=nsubstrs; i++) if (pat.match_info(start,length,substrid[i])) rl += length;
772          }
773       _BIGSTRING_SIZE mustfit = xi + remaining + rl - pl;
774       if (mustfit >= nsz)
775       { // resize destination if necessary
776         if (nrep != 0) nrep->len = xi;
777         nrep = Sresize(nrep, mustfit);
778         x = nrep->s;
779         nsz = nrep->sz;
780       }
781       pos -= si;        // length to copy before match
782       ncopy(&(s[si]), &(x[xi]), pos);   // copy unmatched part
783       si += pos + pl;   // advance source index
784       remaining -= pos + pl;    // subtract amount searched and matched
785          xi += pos;     // advance destination index
786          if (substrs=='\0') {
787                 ncopy(r, &(x[xi]), rl); // paste replacement string
788                 xi += rl;       // advance destination index
789         } else {
790                 ncopy(substridx[0], &(x[xi]), substrrl[0]); xi += substrrl[0];
791                 for (int i=1; i<=nsubstrs; i++) {
792                         if (pat.match_info(start,length,substrid[i])) {
793                                 ncopy(&(s[start]),&(x[xi]),length);
794                                 xi += length;
795                         }
796                         ncopy(substridx[i],&(x[xi]), substrrl[i]); xi += substrrl[i];
797                 }
798          }
799     }
800   }
801 
802   if (substrs!='\0') {
803         delete[] substridx;
804         delete[] substrrl;
805         delete[] substrid;
806         delete[] rloc;
807   }
808 
809   if (nrep == 0)
810   {
811     if (nmatches == 0)
812       return nmatches;
813     else
814       nrep = Sresize(nrep, xi+remaining); // allocate to fit remaining
815   }
816 
817   ncopy0(&(s[si]), &(x[xi]), remaining);        // copy remainder of source
818   nrep->len = xi + remaining;
819 
820 #ifndef BIGSTRING_MAXIMIZE_SPEED
821   if (nrep->len <= rep->sz)
822   {
823     rep->len = nrep->len;
824     ncopy0(nrep->s, rep->s, rep->len);
825     delete(nrep);
826   }
827   else
828   {
829 #endif
830     delete(rep);
831     rep = nrep;
832 #ifndef BIGSTRING_MAXIMIZE_SPEED
833   }
834 #endif
835   return nmatches;
836 }
_BIGSTRING_SIZE String::_gsub (const char *, _BIGSTRING_SIZE, const char *, _BIGSTRING_SIZE) [protected]
Definition at line 639 of file BigString.cc.
References _BIGSTRING_ITERATOR, _BIGSTRING_SIZE, chars(), StrRep::len, length(), StrRep::s, search(), and StrRep::sz.
Referenced by gsub().
640 {
641   _BIGSTRING_SIZE nmatches = 0;
642   if (pl < 0) pl = slen(pat);
643   if (rl < 0) rl = slen(r);
644   _BIGSTRING_SIZE sl = length();
645   if (sl <= 0 || pl <= 0 || sl < pl)
646     return nmatches;
647   
648   const char* s = chars();
649 
650   // prepare to make new rep
651   StrRep* nrep = 0;
652   _BIGSTRING_SIZE nsz = 0;
653   char* x = 0;
654 
655   _BIGSTRING_ITERATOR si = 0;
656   _BIGSTRING_ITERATOR xi = 0;
657   _BIGSTRING_SIZE remaining = sl;
658 
659   while (remaining >= pl)
660   {
661     _BIGSTRING_SIZE pos = search(si, sl, pat, pl);
662     if (pos < 0)
663       break;
664     else
665     {
666       ++nmatches;
667       _BIGSTRING_SIZE mustfit = xi + remaining + rl - pl;
668       if (mustfit >= nsz)
669       {
670         if (nrep != 0) nrep->len = xi;
671         nrep = Sresize(nrep, mustfit);
672         nsz = nrep->sz;
673         x = nrep->s;
674       }
675       pos -= si;
676       ncopy(&(s[si]), &(x[xi]), pos);
677       ncopy(r, &(x[xi + pos]), rl);
678       si += pos + pl;
679       remaining -= pos + pl;
680       xi += pos + rl;
681     }
682   }
683 
684   if (nrep == 0)
685   {
686     if (nmatches == 0)
687       return nmatches;
688     else
689       nrep = Sresize(nrep, xi+remaining);
690   }
691 
692   ncopy0(&(s[si]), &(x[xi]), remaining);
693   nrep->len = xi + remaining;
694 
695   if (nrep->len <= rep->sz)   // fit back in if possible
696   {
697     rep->len = nrep->len;
698     ncopy0(nrep->s, rep->s, rep->len);
699     delete(nrep);
700   }
701   else
702   {
703     delete(rep);
704     rep = nrep;
705   }
706   return nmatches;
707 }
SubString String::_substr (int, int) [protected]
Referenced by after(), at(), before(), from(), operator()(), sub(), and through().
SubString String::after (const BigRegex & r, _BIGSTRING_SIZE startpos = 0)
Definition at line 1038 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), chars(), length(), and BigRegex::search().
1039 {
1040   _BIGSTRING_SIZE mlen;
1041   _BIGSTRING_SIZE first = r.search(chars(), length(), mlen, startpos);
1042   if (first >= 0) first += mlen;
1043   return _substr(first, length() - first);
1044 }
SubString String::after (char c, _BIGSTRING_SIZE startpos = 0)
Definition at line 1031 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), length(), and search().
1032 {
1033   _BIGSTRING_SIZE first = search(startpos, length(), c);
1034   if (first >= 0) first += 1;
1035   return _substr(first, length() - first);
1036 }
SubString String::after (const char * t, _BIGSTRING_SIZE startpos = 0)
Definition at line 1046 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), length(), and search().
1047 {
1048   _BIGSTRING_SIZE tlen = slen(t);
1049   _BIGSTRING_SIZE first = search(startpos, length(), t, tlen);
1050   if (first >= 0) first += tlen;
1051   return _substr(first, length() - first);
1052 }
SubString String::after (const SubString & x, _BIGSTRING_SIZE startpos = 0)
Definition at line 1024 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), SubString::chars(), SubString::length(), length(), and search().
1025 {
1026   _BIGSTRING_SIZE first = search(startpos, length(), y.chars(), y.length());
1027   if (first >= 0) first += y.length();
1028   return _substr(first, length() - first);
1029 }
SubString String::after (const String & x, _BIGSTRING_SIZE startpos = 0)
Definition at line 1017 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), chars(), length(), and search().
1018 {
1019   _BIGSTRING_SIZE first = search(startpos, length(), y.chars(), y.length());
1020   if (first >= 0) first += y.length();
1021   return _substr(first, length() - first);
1022 }
SubString String::after (_BIGSTRING_SIZE pos)
Definition at line 906 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), and length().
Referenced by absurl(), Financial_Monthly::add(), add_TL_chunk_or_entry(), cmdline_extract_paper_novelties(), cmdline_extract_paper_plan_to_paper(), DIL_Hierarchy_cmd(), extract_hierarchy_depth_decrease_to_paper(), extract_paper_novelties(), extract_paper_plan_to_paper(), extract_recursively(), generate_AL_entry(), generate_Figures_Directory_entry(), generate_TL_chunk_header(), generate_TL_entry_header(), DIL_entry::Get_Entry_Parameters(), get_figure_data(), Novelty_Marker::Get_Novelty_from_Paper_Plan(), get_Paper_Plans_Section_IDs(), include_article_head_template(), include_article_section_head_template(), include_article_section_tail_template(), include_article_tail_template(), include_protected_text(), DIL_ID::init(), initialize(), main(), make_note(), max_chunk_entry(), Modify_Element(), process_HTML(), process_note_CC(), process_note_generic(), process_note_HTML(), process_note_TeX(), relurl(), RX_Search_Safe(), search_cmd(), select_TL_AL_refs(), select_TL_DIL_refs(), Target_Access::set_target(), LongList::split(), StringList::split(), stop_TL_chunk(), Tabbed_DIL_Hierarchy(), Tabbed_FORM_DIL_Hierarchy(), Tabbed_HTML_DIL_Hierarchy(), and update_DIL_entry_elements().
907 {
908   return _substr(pos + 1, length() - (pos + 1));
909 }
void String::alloc (_BIGSTRING_SIZE newsize)
Definition at line 253 of file BigString.cc.
References _BIGSTRING_LENGTH, _BIGSTRING_SIZE, StrRep::len, and rep.
Referenced by HTML_remove_comments(), and remove_AL_TC().
254 {
255   _BIGSTRING_LENGTH old_len = rep->len;
256   rep = Sresize(rep, newsize);
257   rep->len = old_len;
258 }
_BIGSTRING_ALLOC String::allocation () const [inline]
Definition at line 496 of file BigString.hh.
References _BIGSTRING_ALLOC, rep, and StrRep::sz.
496 { return rep->sz; }
SubString String::at (const BigRegex & r, _BIGSTRING_SIZE startpos = 0)
Definition at line 928 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), chars(), length(), and BigRegex::search().
929 {
930   _BIGSTRING_SIZE mlen;
931   _BIGSTRING_SIZE first = r.search(chars(), length(), mlen, startpos);
932   return _substr(first, mlen); // INVOLVED in lfstr.at(...) = ...
933 }
SubString String::at (char c, _BIGSTRING_SIZE startpos = 0)
Definition at line 942 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), length(), and search().
943 {
944   _BIGSTRING_SIZE first = search(startpos, length(), c);
945   return _substr(first, 1);
946 }
SubString String::at (const char * t, _BIGSTRING_SIZE startpos = 0)
Definition at line 935 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), length(), and search().
936 {
937   _BIGSTRING_SIZE tlen = slen(t);
938   _BIGSTRING_SIZE first = search(startpos, length(), t, tlen);
939   return _substr(first, tlen);
940 }
SubString String::at (const SubString & x, _BIGSTRING_SIZE startpos = 0)
Definition at line 922 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), SubString::chars(), SubString::length(), length(), and search().
923 {
924   _BIGSTRING_SIZE first = search(startpos, length(), y.chars(), y.length());
925   return _substr(first, y.length());
926 }
SubString String::at (const String & x, _BIGSTRING_SIZE startpos = 0)
Definition at line 916 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), chars(), length(), and search().
917 {
918   _BIGSTRING_SIZE first = search(startpos, length(), y.chars(), y.length());
919   return _substr(first,  y.length());
920 }
SubString String::at (_BIGSTRING_SIZE pos, _BIGSTRING_SIZE len)
Definition at line 886 of file BigString.cc.
References _BIGSTRING_SIZE, and _substr().
Referenced by add_protected_text(), add_TL_chunk_or_entry(), add_TL_section(), Assess_Paper_Correction_Time(), clean_paper_outline(), D2A_get_tag(), Detect_Form_Input(), dil2al_commands(), extract_hierarchy_depth_decrease_to_paper(), extract_hierarchy_depth_increase_to_paper(), extract_paper_novelties(), extract_paper_plan_to_paper(), extract_recursively(), extract_required_item_to_paper(), generate_AL_entry(), generate_modify_element_FORM_interface_DIL_entry_content(), Financial_Note::get(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), get_figure_data(), get_most_recent_TC_AL(), get_most_recent_TC_DE(), Novelty_Marker::Get_Novelty_from_Paper_Plan(), get_Paper_Plans_Section_IDs(), Detailed_Items_List::Get_Project_Data(), HTML_get_href(), HTML_get_marker(), HTML_get_name(), HTML_get_tagged_environment(), HTML_remove_comments(), include_article_head_template(), include_article_section_head_template(), include_article_section_tail_template(), include_article_tail_template(), include_protected_text(), DIL_ID::init(), DIL_entry_content::Is_Plan_Entry(), item_content_between_range_tags(), item_content_within_DIL_entry(), item_content_within_paragraph(), item_content_within_TL_chunk(), locate_most_recent_TL_chunk(), modify_DIL_group_target_dates_cmd(), Modify_Element(), post_process_note(), process_HTML(), process_note_CC(), process_note_generic(), process_note_HTML(), process_note_TeX(), remove_AL_TC(), search_cmd(), Search_Result::Search_Result(), select_TL_DIL_refs(), send_dil_to_DIL(), Target_Access::set_target(), TeX_format_corrections(), TeX_get_command(), TeX_get_scope(), TeX_safe_text(), time_stamp_time(), time_stamp_time_of_day(), and Detailed_Items_List::Write_to_File().
887 {
888   return _substr(first, len);
889 }
SubString String::before (const BigRegex & r, _BIGSTRING_SIZE startpos = 0)
Definition at line 960 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), chars(), length(), and BigRegex::search().
961 {
962   _BIGSTRING_SIZE mlen;
963   _BIGSTRING_SIZE first = r.search(chars(), length(), mlen, startpos);
964   return _substr(0, first);
965 }
SubString String::before (char c, _BIGSTRING_SIZE startpos = 0)
Definition at line 967 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), length(), and search().
968 {
969   _BIGSTRING_SIZE last = search(startpos, length(), c);
970   return _substr(0, last);
971 }
SubString String::before (const char * t, _BIGSTRING_SIZE startpos = 0)
Definition at line 973 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), length(), and search().
974 {
975   _BIGSTRING_SIZE tlen = slen(t);
976   _BIGSTRING_SIZE last = search(startpos, length(), t, tlen);
977   return _substr(0, last);
978 }
SubString String::before (const SubString & x, _BIGSTRING_SIZE startpos = 0)
Definition at line 954 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), SubString::chars(), SubString::length(), length(), and search().
955 {
956   _BIGSTRING_SIZE last = search(startpos, length(), y.chars(), y.length());
957   return _substr(0, last);
958 }
SubString String::before (const String & x, _BIGSTRING_SIZE startpos = 0)
Definition at line 948 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), chars(), length(), and search().
949 {
950   _BIGSTRING_SIZE last = search(startpos, length(), y.chars(), y.length());
951   return _substr(0, last);
952 }
SubString String::before (_BIGSTRING_SIZE pos)
Definition at line 896 of file BigString.cc.
References _BIGSTRING_SIZE, and _substr().
Referenced by absurl(), add_protected_text(), add_TL_chunk_or_entry(), add_TL_section(), cmdline_extract_paper_novelties(), cmdline_extract_paper_plan_to_paper(), DIL_Hierarchy_cmd(), Elipsis_At(), extract_hierarchy_depth_decrease_to_paper(), extract_paper_plan_to_paper(), extract_recursively(), generate_AL_entry(), generate_Figures_Directory_entry(), Financial_Note::get(), get_figure_data(), Novelty_Marker::Get_Novelty_from_Paper_Plan(), get_Paper_Plans_Section_IDs(), Get_Target_Regex(), HTML_marker_arguments(), include_article_head_template(), include_article_section_head_template(), include_article_section_tail_template(), include_article_tail_template(), include_protected_text(), DIL_ID::init(), make_note(), max_chunk_entry(), modify_DIL_group_target_dates_cmd(), Modify_Element(), process_HTML(), process_note_CC(), process_note_generic(), process_note_HTML(), process_note_TeX(), read_financial_notes_file(), relurl(), search_cmd(), Search_Result::Search_Result(), select_TL_AL_refs(), select_TL_DIL_refs(), Target_Access::set_target(), LongList::split(), StringList::split(), stop_TL_chunk(), Tabbed_DIL_Hierarchy(), Tabbed_FORM_DIL_Hierarchy(), Tabbed_HTML_DIL_Hierarchy(), TeX_format_corrections(), time_stamp_time_date(), Target_Access::transformed_name(), update_DIL_entry_elements(), update_main_ALs(), and Detailed_Items_List::Write_to_File().
897 {
898   return _substr(0, pos);
899 }
void String::capitalize () [inline]
Definition at line 1056 of file BigString.hh.
References rep, and Scapitalize().
1057 {
1058   rep = Scapitalize(rep, rep);
1059 }
const char * String::chars () const [inline]
Definition at line 495 of file BigString.hh.
References rep, and StrRep::s.
Referenced by _gsub(), after(), at(), before(), cat(), DIL_ID::chars(), common_prefix(), common_suffix(), compare(), SubString::contains(), contains(), del(), Detect_Form_Input(), dil2al_commands(), exit_report(), fcompare(), freq(), from(), gsub(), index(), join(), matches(), operator const char *(), operator<<(), SubString::operator=(), prepend(), replicate(), search(), LongList::split(), split(), through(), time_stamp_time_of_day(), DIL_AL_List::Write_to_Binary_Cache(), DIL_Topical_List::Write_to_Binary_Cache(), Detailed_Items_List::Write_to_File(), and DIL_entry_content::Write_Topical_to_Binary_Cache().
495 { return &(rep->s[0]); }
int String::contains (const BigRegex & r, _BIGSTRING_SIZE pos) const [inline]
Definition at line 1171 of file BigString.hh.
References _BIGSTRING_SIZE, chars(), length(), and BigRegex::match().
1172 {
1173   return r.match(chars(), length(), p) >= 0;
1174 }
int String::contains (const char * t, _BIGSTRING_SIZE pos) const [inline]
Definition at line 1151 of file BigString.hh.
References _BIGSTRING_SIZE, length(), and match().
1152 {
1153   return match(p, length(), 0, t) >= 0;
1154 }
int String::contains (const SubString & y, _BIGSTRING_SIZE pos) const [inline]
Definition at line 1161 of file BigString.hh.
References _BIGSTRING_SIZE, SubString::chars(), SubString::length(), length(), and match().
1162 {
1163   return match(p, length(), 0, y.chars(), y.length()) >= 0;
1164 }
int String::contains (const String & y, _BIGSTRING_SIZE pos) const [inline]
Definition at line 1156 of file BigString.hh.
References _BIGSTRING_SIZE, chars(), length(), and match().
1157 {
1158   return match(p, length(), 0, y.chars(), y.length()) >= 0;
1159 }
int String::contains (char c, _BIGSTRING_SIZE pos) const [inline]
Definition at line 1146 of file BigString.hh.
References _BIGSTRING_SIZE, length(), and match().
1147 {
1148   return match(p, length(), 0, &c, 1) >= 0;
1149 }
int String::contains (const BigRegex & r) const [inline]
Definition at line 1166 of file BigString.hh.
References chars(), length(), and BigRegex::search().
1167 {
1168   int unused;  return r.search(chars(), length(), unused, 0) >= 0;
1169 }
int String::contains (const char * t) const [inline]
Definition at line 1131 of file BigString.hh.
References length(), and search().
1132 {   
1133   return search(0, length(), t) >= 0;
1134 }
int String::contains (const SubString & y) const [inline]
Definition at line 1141 of file BigString.hh.
References SubString::chars(), SubString::length(), length(), and search().
1142 {   
1143   return search(0, length(), y.chars(), y.length()) >= 0;
1144 }
int String::contains (const String & y) const [inline]
Definition at line 1136 of file BigString.hh.
References chars(), length(), and search().
1137 {   
1138   return search(0, length(), y.chars(), y.length()) >= 0;
1139 }
int String::contains (char c) const [inline]
Definition at line 1126 of file BigString.hh.
References length(), and search().
Referenced by absurl(), add_TL_chunk_or_entry(), Assess_Paper_Correction_Time(), Target_Access::cleartext_conversion(), StringList::contains(), extract_DIL_IDs_from_form(), extract_paper_plan_to_paper(), extract_recursively(), extraction_put_figure(), StringList::first_contained_in(), Financial_Note::get(), get_AL_entry(), Novelty_Marker::Get_Novelty_from_Paper_Plan(), Get_Target_Regex(), item_content_within_DIL_entry(), item_content_within_TL_chunk(), Search_Target::links(), main(), Plan_entry_content::Parse_Entry_Content(), process_HTML(), readtotag(), Search_Result::Search_Result(), select_TL_AL_refs(), select_TL_DIL_refs(), and Target_Access::uncompress().
1127 {
1128   return search(0, length(), c) >= 0;
1129 }
void String::del (const BigRegex & r, _BIGSTRING_SIZE startpos = 0)
Definition at line 852 of file BigString.cc.
References _BIGSTRING_SIZE, chars(), del(), length(), and BigRegex::search().
853 {
854   _BIGSTRING_SIZE mlen;
855   _BIGSTRING_SIZE first = r.search(chars(), length(), mlen, startpos);
856   del(first, mlen);
857 }
void String::del (char c, _BIGSTRING_SIZE startpos = 0)
Definition at line 876 of file BigString.cc.
References _BIGSTRING_SIZE, del(), length(), and search().
877 {
878   del(search(startpos, length(), c), 1);
879 }
void String::del (const char * t, _BIGSTRING_SIZE startpos = 0)
Definition at line 859 of file BigString.cc.
References _BIGSTRING_SIZE, del(), length(), and search().
860 {
861   _BIGSTRING_SIZE tlen = slen(t);
862   _BIGSTRING_SIZE p = search(startpos, length(), t, tlen);
863   del(p, tlen);
864 }
void String::del (const SubString & y, _BIGSTRING_SIZE startpos = 0)
Definition at line 871 of file BigString.cc.
References _BIGSTRING_SIZE, SubString::chars(), del(), SubString::length(), length(), and search().
872 {
873   del(search(startpos, length(), y.chars(), y.length()), y.length());
874 }
void String::del (const String & y, _BIGSTRING_SIZE startpos = 0)
Definition at line 866 of file BigString.cc.
References _BIGSTRING_SIZE, chars(), del(), length(), and search().
867 {
868   del(search(startpos, length(), y.chars(), y.length()), y.length());
869 }
void String::del (_BIGSTRING_SIZE pos, _BIGSTRING_SIZE len)
Definition at line 843 of file BigString.cc.
References _BIGSTRING_LENGTH, _BIGSTRING_SIZE, StrRep::len, length(), and StrRep::s.
Referenced by add_TL_chunk_or_entry(), Assess_Paper_Correction_Time(), auto_interactive(), del(), Detect_Form_Input(), dil2al_commands(), DIL_Hierarchy_cmd(), extract_hierarchy_depth_decrease_to_paper(), extract_paper_plan_to_paper(), extraction_put_figure(), financial_notes(), generate_Figures_Directory_entry(), generic_remove_name_reference(), Financial_Note::get(), get_figure_data(), get_most_recent_TC_AL(), get_most_recent_TC_DE(), Novelty_Marker::Get_Novelty_from_Paper_Plan(), get_Paper_Plans_Section_IDs(), Detailed_Items_List::Get_Project_Data(), Get_Target_Directory(), Get_Target_Regex(), include_protected_text(), locate_most_recent_TL_chunk(), make_note(), Modify_Element(), read_financial_notes_file(), remove_AL_TC(), Target_Access::remove_back_references(), search_cmd(), select_TL_AL_refs(), select_TL_DIL_refs(), send_dil_to_DIL(), and Text_limit_line_length().
844 {
845   if (pos < 0 || len <= 0 || (unsigned)(pos + len) > length()) return;
846   _BIGSTRING_LENGTH nlen = length() - len;
847   _BIGSTRING_SIZE first = pos + len;
848   ncopy0(&(rep->s[first]), &(rep->s[pos]), length() - first);
849   rep->len = nlen;
850 }
void String::downcase () [inline]
Definition at line 1050 of file BigString.hh.
References rep, and Sdowncase().
1051 {
1052   rep = Sdowncase(rep, rep);
1053 }
char String::elem (_BIGSTRING_ITERATOR i) const [inline]
Definition at line 1075 of file BigString.hh.
References _BIGSTRING_ITERATOR, error(), length(), rep, and StrRep::s.
Referenced by firstchar(), get_figure_data(), lastchar(), TeX_format_corrections(), TeX_get_argument(), TeX_get_scope(), and TeX_safe_text().
1076 { 
1077   if (((unsigned)i) >= length()) error("invalid index");
1078   return rep->s[i];
1079 }
int String::empty () const [inline]
Definition at line 494 of file BigString.hh.
References StrRep::len, and rep.
Referenced by Target_Access::cleartext_conversion(), Detect_Form_Input(), DIL_Hierarchy_cmd(), extraction_put_figure(), financial_notes(), Financial_Note::get(), get_double(), get_figure_data(), Search_Target::links(), Target_Access::make_local_copy(), modify_element_through_FORM_interface_DIL_Superiors(), relurl(), Target_Access::remove_cleartext(), Target_Access::remove_local_copy(), Target_Access::remove_uncompressed(), search_cmd(), search_FORM_cmd(), Target_Access::set_target(), Tabbed_DIL_Hierarchy(), Tabbed_FORM_DIL_Hierarchy(), Tabbed_HTML_DIL_Hierarchy(), Target_Access::transformed_name(), Target_Access::uncompress(), and write_file_from_String().
494 { return rep->len == 0; }
void String::error (const char * msg) const
Definition at line 39 of file BigString.cc.
Referenced by elem(), SubString::OK(), OK(), and operator[]().
40 {
41 cerr << "Error in String: " << msg << '\n';
42 //  (*lib_error_handler)("String", msg);
43 }
char String::firstchar () const [inline]
Definition at line 1081 of file BigString.hh.
References elem().
Referenced by Target_Access::remove_back_references(), and Target_Access::set_target().
1082 { 
1083   return elem(0);
1084 }
_BIGSTRING_SIZE String::freq (const char * t) const
Definition at line 1442 of file BigString.cc.
References _BIGSTRING_LENGTH, _BIGSTRING_SIZE, length(), and match().
1443 {
1444   _BIGSTRING_SIZE found = 0;
1445   for (_BIGSTRING_LENGTH i = 0; i < length(); i++) 
1446     if (match(i,length(),0,t) >= 0) found++;
1447   return(found);
1448 }
_BIGSTRING_SIZE String::freq (const SubString & y) const
Definition at line 1426 of file BigString.cc.
References _BIGSTRING_LENGTH, _BIGSTRING_SIZE, SubString::chars(), SubString::length(), length(), and match().
1427 {
1428   _BIGSTRING_SIZE found = 0;
1429   for (_BIGSTRING_LENGTH i = 0; i < length(); i++) 
1430     if (match(i,length(),0,y.chars(), y.length())>= 0) found++;
1431   return(found);
1432 }
_BIGSTRING_SIZE String::freq (const String & y) const
Definition at line 1434 of file BigString.cc.
References _BIGSTRING_LENGTH, _BIGSTRING_SIZE, chars(), length(), and match().
1435 {
1436   _BIGSTRING_SIZE found = 0;
1437   for (_BIGSTRING_LENGTH i = 0; i < length(); i++) 
1438     if (match(i,length(),0,y.chars(),y.length()) >= 0) found++;
1439   return(found);
1440 }
_BIGSTRING_SIZE String::freq (char c) const
Definition at line 1450 of file BigString.cc.
References _BIGSTRING_LENGTH, _BIGSTRING_SIZE, length(), and match().
Referenced by absurl().
1451 {
1452   _BIGSTRING_SIZE found = 0;
1453   for (_BIGSTRING_LENGTH i = 0; i < length(); i++) 
1454     if (match(i,length(),0,&c,1) >= 0) found++;
1455   return(found);
1456 }
SubString String::from (const BigRegex & r, _BIGSTRING_SIZE startpos = 0)
Definition at line 1066 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), chars(), length(), and BigRegex::search().
1067 {
1068   _BIGSTRING_SIZE mlen;
1069   _BIGSTRING_SIZE first = r.search(chars(), length(), mlen, startpos);
1070   return _substr(first, length() - first);
1071 }
SubString String::from (char c, _BIGSTRING_SIZE startpos = 0)
Definition at line 1073 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), length(), and search().
1074 {
1075   _BIGSTRING_SIZE first = search(startpos, length(), c);
1076   return _substr(first, length() - first);
1077 }
SubString String::from (const char * t, _BIGSTRING_SIZE startpos = 0)
Definition at line 1079 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), length(), and search().
1080 {
1081   _BIGSTRING_SIZE tlen = slen(t);
1082   _BIGSTRING_SIZE first = search(startpos, length(), t, tlen);
1083   return _substr(first, length() - first);
1084 }
SubString String::from (const SubString & x, _BIGSTRING_SIZE startpos = 0)
Definition at line 1060 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), SubString::chars(), SubString::length(), length(), and search().
1061 {
1062   _BIGSTRING_SIZE first = search(startpos, length(), y.chars(), y.length());
1063   return _substr(first, length() - first);
1064 }
SubString String::from (const String & x, _BIGSTRING_SIZE startpos = 0)
Definition at line 1054 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), chars(), length(), and search().
1055 {
1056   _BIGSTRING_SIZE first = search(startpos, length(), y.chars(), y.length());
1057   return _substr(first, length() - first);
1058 }
SubString String::from (_BIGSTRING_SIZE pos)
Definition at line 911 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), and length().
Referenced by add_protected_text(), add_TL_chunk_or_entry(), Assess_Paper_Correction_Time(), clean_paper_outline(), DIL_Hierarchy_cmd(), extract_paper_plan_to_paper(), extract_recursively(), HTML_marker_arguments(), include_article_section_tail_template(), DIL_ID::init(), Modify_Element(), process_note_TeX(), read_financial_notes_file(), relurl(), Search_Result::Search_Result(), Target_Access::set_target(), TeX_format_corrections(), TeX_safe_text(), Text_limit_line_length(), update_DIL_entry_elements(), and update_main_ALs().
912 {
913   return _substr(pos, length() - pos);
914 }
_BIGSTRING_SIZE String::gsub (const BigRegex & pat, const String & repl, char substrs = '\0') [inline]
Definition at line 1244 of file BigString.hh.
References _BIGSTRING_SIZE, _gsub(), chars(), and length().
1245 {
1246   return _gsub(pat, r.chars(), r.length(), substrs);
1247 }
_BIGSTRING_SIZE String::gsub (const char * pat, const char * repl) [inline]
Definition at line 1254 of file BigString.hh.
References _BIGSTRING_SIZE, and _gsub().
1255 {
1256   return _gsub(pat, -1, r, -1);
1257 }
_BIGSTRING_SIZE String::gsub (const char * pat, const String & repl) [inline]
Definition at line 1249 of file BigString.hh.
References _BIGSTRING_SIZE, _gsub(), chars(), and length().
1250 {
1251   return _gsub(pat, -1, r.chars(), r.length());
1252 }
_BIGSTRING_SIZE String::gsub (const SubString & pat, const String & repl) [inline]
Definition at line 1239 of file BigString.hh.
References _BIGSTRING_SIZE, _gsub(), chars(), SubString::chars(), length(), and SubString::length().
1240 {
1241   return _gsub(pat.chars(), pat.length(), r.chars(), r.length());
1242 }
_BIGSTRING_SIZE String::gsub (const String & pat, const String & repl) [inline]
Definition at line 1234 of file BigString.hh.
References _BIGSTRING_SIZE, _gsub(), chars(), and length().
Referenced by absurl(), add_TL_chunk_or_entry(), Assess_Paper_Correction_Time(), clean_paper_outline(), convert_item_content_to_TeX(), extract_hierarchy_depth_decrease_to_paper(), extract_paper_novelties(), extract_paper_plan_to_paper(), extraction_put_figure(), generate_AL(), generate_AL_entry(), generate_EPS_cells(), Active_List::generate_focused_AL(), generate_modify_element_FORM_interface_DIL_entry_parameters(), Active_List::generate_wide_AL(), get_figure_data(), get_most_recent_TC_DE(), Novelty_Marker::Get_Novelty_from_Paper_Plan(), get_Paper_Plans_Section_IDs(), HTML_remove_tags(), HTML_safe(), include_article_head_template(), include_article_tail_template(), item_content_within_TL_chunk(), make_note(), modify_DIL_group_target_dates_cmd(), modify_element_through_FORM_interface(), process_HTML(), process_note(), process_note_CC(), process_note_generic(), process_note_TeX(), Target_Access::remove_back_references(), remove_whitespace(), RX_Search_Safe(), search_cmd(), search_FORM_cmd(), select_TL_AL_refs(), select_TL_DIL_refs(), send_dil_to_DIL(), stop_TL_chunk(), TeX_format_corrections(), TeX_safe_text(), Target_Access::transformed_name(), unconvert_item_content_from_TeX(), update_DIL_entry_elements(), DIL_Visualize_with_FORM_Tabs::Visualize_Element(), and DIL_Visualize_with_HTML_Tabs::Visualize_Element().
1235 {
1236   return _gsub(pat.chars(), pat.length(), r.chars(), r.length());
1237 }
_BIGSTRING_SIZE String::index (const BigRegex & r, BigString_Search_t _st, _BIGSTRING_SIZE startpos = 0) const [inline]
Definition at line 1118 of file BigString.hh.
References _BIGSTRING_SIZE, chars(), length(), BigRegex::search(), and SEARCH_START.
1119 {
1120   int matchlen;
1121   int matchstart = r.search(chars(), length(), matchlen, startpos);
1122   if ((matchstart<0) || (_st==SEARCH_START)) return matchstart;
1123   else return (matchstart+matchlen);
1124 }
_BIGSTRING_SIZE String::index (const BigRegex & r, _BIGSTRING_SIZE startpos = 0) const [inline]
Definition at line 1113 of file BigString.hh.
References _BIGSTRING_SIZE, chars(), length(), and BigRegex::search().
1114 {
1115   int unused;  return r.search(chars(), length(), unused, startpos);
1116 }
_BIGSTRING_SIZE String::index (const char * t, _BIGSTRING_SIZE startpos = 0) const [inline]
Definition at line 1098 of file BigString.hh.
References _BIGSTRING_SIZE, length(), and search().
1099 {   
1100   return search(startpos, length(), t);
1101 }
_BIGSTRING_SIZE String::index (const SubString & y, _BIGSTRING_SIZE startpos = 0) const [inline]
Definition at line 1108 of file BigString.hh.
References _BIGSTRING_SIZE, SubString::chars(), SubString::length(), length(), and search().
1109 {   
1110   return search(startpos, length(), y.chars(), y.length());
1111 }
_BIGSTRING_SIZE String::index (const String & y, _BIGSTRING_SIZE startpos = 0) const [inline]
Definition at line 1103 of file BigString.hh.
References _BIGSTRING_SIZE, chars(), length(), and search().
1104 {   
1105   return search(startpos, length(), y.chars(), y.length());
1106 }
_BIGSTRING_SIZE String::index (char c, _BIGSTRING_SIZE startpos = 0) const [inline]
Definition at line 1093 of file BigString.hh.
References _BIGSTRING_SIZE, length(), and search().
Referenced by Financial_Monthly::add(), Financial_Monthly_Category::add(), add_protected_text(), add_TL_chunk_or_entry(), add_TL_section(), Assess_Paper_Correction_Time(), BigRegex_freq(), clean_paper_outline(), D2A_get_tag(), extract_hierarchy_depth_decrease_to_paper(), extract_hierarchy_depth_increase_to_paper(), extract_paper_novelties(), extract_paper_plan_to_paper(), extract_recursively(), extract_required_item_to_paper(), find_delimiter(), generate_AL_entry(), generic_remove_name_reference(), Financial_Note::get(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), DIL_entry::Get_Entry_Parameters(), get_figure_data(), Novelty_Marker::Get_Novelty_from_Paper_Plan(), get_Paper_Plans_Section_IDs(), Detailed_Items_List::Get_Project_Data(), HTML_get_href(), HTML_get_marker(), HTML_get_name(), HTML_get_tagged_environment(), HTML_remove_comments(), include_article_head_template(), include_article_section_head_template(), include_article_section_tail_template(), include_article_tail_template(), include_protected_text(), DIL_entry_content::Is_Plan_Entry(), item_content_between_range_tags(), item_content_within_DIL_entry(), item_content_within_paragraph(), item_content_within_TL_chunk(), Search_Target::links(), locate_most_recent_TL_chunk(), max_chunk_entry(), modify_DIL_group_target_dates_cmd(), Plan_entry_content::Parse_Entry_Content(), process_HTML(), process_note_CC(), process_note_generic(), process_note_HTML(), process_note_TeX(), process_note_TL(), read_financial_notes_file(), Target_Access::remove_back_references(), Search_Target::search(), search_cmd(), Search_Result::Search_Result(), select_TL_DIL_refs(), send_dil_to_DIL(), Target_Access::set_target(), LongList::split(), StringList::split(), TeX_format_corrections(), TeX_get_argument(), TeX_get_scope(), TeX_safe_text(), Text_find_line_end(), Text_limit_line_length(), and update_DIL_entry_elements().
1094 {
1095   return search(startpos, length(), c);
1096 }
char String::lastchar () const [inline]
Definition at line 1086 of file BigString.hh.
References elem(), and length().
Referenced by extraction_put_figure(), Financial_Note::get(), Get_Target_Directory(), and relurl().
1087 { 
1088   return elem(length() - 1);
1089 }
_BIGSTRING_LENGTH String::length () const [inline]
Definition at line 493 of file BigString.hh.
References _BIGSTRING_LENGTH, StrRep::len, and rep.
Referenced by _gsub(), add_protected_text(), add_TL_chunk_or_entry(), after(), at(), before(), DIL_entry_content::Binary_Cache_Diagnostic(), cat(), clean_paper_outline(), common_prefix(), common_suffix(), compare(), SubString::contains(), contains(), del(), Detect_Form_Input(), dil2al_commands(), DIL_Hierarchy_cmd(), elem(), Elipsis_At(), extract_paper_plan_to_paper(), extract_recursively(), extraction_put_figure(), fcompare(), financial_notes(), freq(), from(), generate_AL_entry(), generate_modify_element_FORM_interface_DIL_entry_content(), generic_remove_name_reference(), Financial_Note::get(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), get_figure_data(), Novelty_Marker::Get_Novelty_from_Paper_Plan(), Detailed_Items_List::Get_Project_Data(), Get_Target_Directory(), Get_Target_Regex(), gsub(), HTML_get_marker(), HTML_get_tagged_environment(), HTML_marker_arguments(), HTML_put_form_input(), HTML_put_form_text(), HTML_remove_comments(), include_article_head_template(), index(), DIL_ID::init(), item_content_between_range_tags(), item_content_within_DIL_entry(), item_content_within_paragraph(), item_content_within_TL_chunk(), join(), lastchar(), matches(), modify_DIL_group_target_dates_cmd(), Modify_Element(), SubString::operator=(), operator[](), post_process_note(), prepend(), process_HTML(), process_note_CC(), process_note_TL(), read_financial_notes_file(), relurl(), remove_AL_TC(), Target_Access::remove_back_references(), replicate(), RX_Search_Safe(), search_cmd(), Search_Result::Search_Result(), select_TL_DIL_refs(), Target_Access::set_target(), LongList::split(), StringList::split(), split(), DIL_ID::str(), TeX_format_corrections(), Text_find_line_end(), Text_limit_line_length(), through(), time_stamp_time(), time_stamp_time_date(), time_stamp_time_of_day(), URI_unescape(), DIL_AL_List::Write_to_Binary_Cache(), DIL_Topical_List::Write_to_Binary_Cache(), Detailed_Items_List::Write_to_File(), and DIL_entry_content::Write_Topical_to_Binary_Cache().
493 {  return rep->len; }
_BIGSTRING_SIZE String::match (_BIGSTRING_SIZE, _BIGSTRING_SIZE, int, const char *, _BIGSTRING_SIZE = -1) const [protected]
Definition at line 555 of file BigString.cc.
References _BIGSTRING_SIZE, and StrRep::s.
Referenced by contains(), freq(), and matches().
556 {
557   if (tl < 0) tl = slen(t);
558 
559   if (start < 0)
560   {
561     start = sl + start - tl + 1;
562     if (start < 0 || (exact && start != 0))
563       return -1;
564   }
565   else if (exact && sl - start != tl)
566     return -1;
567 
568   if (sl == 0 || tl == 0 || sl - start < tl || start >= sl)
569     return -1;
570 
571   _BIGSTRING_SIZE n = tl;
572   const char* s = &(rep->s[start]);
573   while (--n >= 0) if (*s++ != *t++) return -1;
574   return tl;
575 }
int String::matches (const BigRegex & r, _BIGSTRING_SIZE pos = 0) const [inline]
Definition at line 1197 of file BigString.hh.
References _BIGSTRING_SIZE, chars(), length(), and BigRegex::match().
1198 {
1199   _BIGSTRING_SIZE l = (p < 0)? -p : length() - p;
1200   return r.match(chars(), length(), p) == l;
1201 }
int String::matches (const char * t, _BIGSTRING_SIZE pos = 0) const [inline]
Definition at line 1187 of file BigString.hh.
References _BIGSTRING_SIZE, length(), and match().
1188 {
1189   return match(p, length(), 1, t) >= 0;
1190 }
int String::matches (const SubString & y, _BIGSTRING_SIZE pos = 0) const [inline]
Definition at line 1177 of file BigString.hh.
References _BIGSTRING_SIZE, SubString::chars(), SubString::length(), length(), and match().
1178 {
1179   return match(p, length(), 1, y.chars(), y.length()) >= 0;
1180 }
int String::matches (const String & y, _BIGSTRING_SIZE pos = 0) const [inline]
Definition at line 1182 of file BigString.hh.
References _BIGSTRING_SIZE, chars(), length(), and match().
1183 {
1184   return match(p, length(), 1, y.chars(), y.length()) >= 0;
1185 }
int String::matches (char c, _BIGSTRING_SIZE pos = 0) const [inline]
Definition at line 1192 of file BigString.hh.
References _BIGSTRING_SIZE, length(), and match().
Referenced by get_double(), Get_Target_Regex(), make_note(), max_chunk_entry(), modify_element_through_FORM_interface_DIL_Superiors(), process_note(), select_TL_AL_refs(), select_TL_DIL_refs(), Set_Parameter(), stop_TL_chunk(), TeX_format_corrections(), TeX_get_command(), and TeX_safe_text().
1193 {
1194   return match(p, length(), 1, &c, 1) >= 0;
1195 }
int String::OK () const
Definition at line 1459 of file BigString.cc.
References error(), StrRep::len, StrRep::s, and StrRep::sz.
Referenced by SubString::OK().
1460 {
1461   if (rep == 0             // don't have a rep
1462     || rep->len > rep->sz     // string oustide bounds
1463     || rep->s[rep->len] != 0)   // not null-terminated
1464       error("invariant failure");
1465   return 1;
1466 }
String::operator const char * () const
Definition at line 45 of file BigString.cc.
References chars().
46 { 
47   return (const char*)chars();
48 }
SubString String::operator() (_BIGSTRING_SIZE pos, _BIGSTRING_SIZE len)
Definition at line 891 of file BigString.cc.
References _BIGSTRING_SIZE, and _substr().
892 {
893   return _substr(first, len);
894 }
String& String::operator+= (istream & y)
String & String::operator+= (char c) [inline]
Definition at line 834 of file BigString.hh.
References cat.
835 {
836   cat(*this, y, *this);
837   return *this;
838 }
String & String::operator+= (const char * y) [inline]
Definition at line 828 of file BigString.hh.
References cat.
829 {
830   cat(*this, y, *this);
831   return *this;
832 }
String & String::operator+= (const SubString & y) [inline]
Definition at line 822 of file BigString.hh.
References cat.
823 {
824   cat(*this, y, *this);
825   return *this;
826 }
String & String::operator+= (const String & y) [inline]
Definition at line 816 of file BigString.hh.
References cat.
817 {
818   cat(*this, y, *this);
819   return *this;
820 }
String & String::operator= (istream & y) [inline]
Definition at line 573 of file BigString.hh.
References rep, and Salloc_istream().
573                                             {
574         rep = Salloc_istream(rep, y, -1, -1);
575         return *this;
576 }
String & String::operator= (const SubString & y) [inline]
Definition at line 560 of file BigString.hh.
References SubString::chars(), SubString::length(), rep, and Salloc().
561 {
562   rep = Salloc(rep, y.chars(), y.length(), y.length());
563   return *this;
564 }
String & String::operator= (char c) [inline]
Definition at line 566 of file BigString.hh.
References rep, and Salloc().
567 {
568   rep = Salloc(rep, &c, 1, 1);
569   return *this;
570 }
String & String::operator= (const char * y) [inline]
Definition at line 554 of file BigString.hh.
References rep, and Salloc().
555 {
556   rep = Salloc(rep, t, -1, -1);
557   return *this;
558 }
String & String::operator= (const String & y) [inline]
Definition at line 548 of file BigString.hh.
References rep, and Scopy().
549 { 
550   rep = Scopy(rep, y.rep);
551   return *this;
552 }
const char & String::operator[] (_BIGSTRING_ITERATOR i) const [inline]
Definition at line 1069 of file BigString.hh.
References _BIGSTRING_ITERATOR, error(), length(), rep, and StrRep::s.
1070 { 
1071   if (((unsigned)i) >= length()) error("invalid index");
1072   return rep->s[i];
1073 }
char & String::operator[] (_BIGSTRING_ITERATOR i) [inline]
Definition at line 1063 of file BigString.hh.
References _BIGSTRING_ITERATOR, error(), length(), rep, and StrRep::s.
1064 { 
1065   if (((unsigned)i) >= length()) error("invalid index");
1066   return rep->s[i];
1067 }
void String::prepend (char c) [inline]
Definition at line 859 of file BigString.hh.
References rep, and Sprepend().
860 {
861   rep = Sprepend(rep, &y, 1); 
862 }
void String::prepend (const char * t) [inline]
Definition at line 854 of file BigString.hh.
References rep, and Sprepend().
855 {
856   rep = Sprepend(rep, y, -1); 
857 }
void String::prepend (const SubString & y) [inline]
Definition at line 864 of file BigString.hh.
References SubString::chars(), SubString::length(), rep, and Sprepend().
865 {
866   rep = Sprepend(rep, y.chars(), y.length());
867 }
void String::prepend (const String & y) [inline]
Definition at line 849 of file BigString.hh.
References chars(), length(), rep, and Sprepend().
Referenced by add_TL_chunk_or_entry(), cmdline_extract_paper_novelties(), cmdline_extract_paper_plan_to_paper(), extract_required_item_to_paper(), extraction_put_figure(), Active_List::generate_focused_AL(), get_figure_data(), get_most_recent_TC_AL(), HTML_put_structure(), initialize(), Int2HexStr(), make_note(), operator+(), relurl(), Search_Result::Search_Result(), select_TL_AL_refs(), select_TL_DIL_refs(), Set_Parameter(), Target_Access::set_target(), DIL_ID::str(), and Target_Access::transformed_name().
850 {
851   rep = Sprepend(rep, y.chars(), y.length());
852 }
String & String::readnoseek (istream & y) [inline]
Definition at line 578 of file BigString.hh.
578                                              {
579         char buf[4097]; int bufread;
580         do {
581                 y.read(buf,4096);
582                 bufread = y.gcount();
583                 if (bufread>0) {
584                         buf[bufread] = '\0';
585                         (*this) += buf;
586                 }
587         } while (bufread==4096);
588         return *this;
589 }
String & String::readtotag (istream & y, const char * t, char terminator = '\n') [inline]
Definition at line 591 of file BigString.hh.
References contains(), and readline.
591                                                                                     {
592   String buf;
593   while (readline(y,buf,terminator,0)>0) {
594     if (buf.contains(t)) break;
595     else (*this) += buf;
596   }
597 }
void String::reverse () [inline]
Definition at line 1038 of file BigString.hh.
References rep, and Sreverse().
1039 {
1040   rep = Sreverse(rep, rep);
1041 }
_BIGSTRING_SIZE String::search (_BIGSTRING_SIZE, _BIGSTRING_SIZE, char) const [protected]
Definition at line 499 of file BigString.cc.
References _BIGSTRING_SIZE, and chars().
500 {
501   const char* s = chars();
502   if (sl > 0)
503   {
504     if (start >= 0)
505     {
506       const char* a = &(s[start]);
507       const char* lasta = &(s[sl]);
508       while (a < lasta) if (*a++ == c) return --a - s;
509     }
510     else
511     {
512       const char* a = &(s[sl + start + 1]);
513       while (--a >= s) if (*a == c) return a - s;
514     }
515   }
516   return -1;
517 }
_BIGSTRING_SIZE String::search (_BIGSTRING_SIZE, _BIGSTRING_SIZE, const char *, _BIGSTRING_SIZE = -1) const [protected]
Definition at line 519 of file BigString.cc.
References _BIGSTRING_SIZE, and chars().
Referenced by _gsub(), after(), at(), before(), SubString::contains(), contains(), del(), from(), index(), split(), and through().
520 {
521   const char* s = chars();
522   if (tl < 0) tl = slen(t);
523   if (sl > 0 && tl > 0)
524   {
525     if (start >= 0)
526     {
527       const char* lasts = &(s[sl - tl]);
528       const char* lastt = &(t[tl]);
529       const char* p = &(s[start]);
530 
531       while (p <= lasts)
532       {
533         const char* x = p++;
534         const char* y = t;
535         while (*x++ == *y++) if (y >= lastt) return --p - s;
536       }
537     }
538     else
539     {
540       const char* firsts = &(s[tl - 1]);
541       const char* lastt =  &(t[tl - 1]);
542       const char* p = &(s[sl + start + 1]); 
543 
544       while (--p >= firsts)
545       {
546         const char* x = p;
547         const char* y = lastt;
548         while (*x-- == *y--) if (y < t) return ++x - s;
549       }
550     }
551   }
552   return -1;
553 }
String String::sub (const BigRegex & r, int nth)
Definition at line 1086 of file BigString.cc.
References _substr(), BigRegex::match_info(), and String().
Referenced by Financial_Monthly::add(), Financial_Monthly_Category::add(), extract_paper_plan_to_paper(), Financial_Note::get(), get_figure_data(), Get_Target_Regex(), Search_Result::Search_Result(), TeX_format_corrections(), and TeX_safe_text().
1086                                               {
1087         int s,l;
1088         if (!r.match_info(s,l,nth)) return String("");
1089         return String(_substr(s,l));
1090 }
SubString String::through (const BigRegex & r, _BIGSTRING_SIZE startpos = 0)
Definition at line 994 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), chars(), length(), and BigRegex::search().
995 {
996   _BIGSTRING_SIZE mlen;
997   _BIGSTRING_SIZE first = r.search(chars(), length(), mlen, startpos);
998   if (first >= 0) first += mlen;
999   return _substr(0, first);
1000 }
SubString String::through (char c, _BIGSTRING_SIZE startpos = 0)
Definition at line 1002 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), length(), and search().
1003 {
1004   _BIGSTRING_SIZE last = search(startpos, length(), c);
1005   if (last >= 0) last += 1;
1006   return _substr(0, last);
1007 }
SubString String::through (const char * t, _BIGSTRING_SIZE startpos = 0)
Definition at line 1009 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), length(), and search().
1010 {
1011   _BIGSTRING_SIZE tlen = slen(t);
1012   _BIGSTRING_SIZE last = search(startpos, length(), t, tlen);
1013   if (last >= 0) last += tlen;
1014   return _substr(0, last);
1015 }
SubString String::through (const SubString & x, _BIGSTRING_SIZE startpos = 0)
Definition at line 987 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), SubString::chars(), SubString::length(), length(), and search().
988 {
989   _BIGSTRING_SIZE last = search(startpos, length(), y.chars(), y.length());
990   if (last >= 0) last += y.length();
991   return _substr(0, last);
992 }
SubString String::through (const String & x, _BIGSTRING_SIZE startpos = 0)
Definition at line 980 of file BigString.cc.
References _BIGSTRING_SIZE, _substr(), chars(), length(), and search().
981 {
982   _BIGSTRING_SIZE last = search(startpos, length(), y.chars(), y.length());
983   if (last >= 0) last += y.length();
984   return _substr(0, last);
985 }
SubString String::through (_BIGSTRING_SIZE pos)
Definition at line 901 of file BigString.cc.
References _BIGSTRING_SIZE, and _substr().
Referenced by extract_recursively(), extraction_put_figure(), include_article_section_head_template(), and relurl().
902 {
903   return _substr(0, pos+1);
904 }
void String::upcase () [inline]
Definition at line 1044 of file BigString.hh.
References rep, and Supcase().
1045 {
1046   rep = Supcase(rep, rep);
1047 }
Friends And Related Function Documentation
String capitalize (const String & x) [friend]
Definition at line 1028 of file BigString.hh.
1029 {
1030   String r; r.rep = Scapitalize(x.rep, r.rep); return r;
1031 }
void cat (const char *, const char *, char, String &) [friend]
Definition at line 809 of file BigString.hh.
810 {
811   r.rep = Scat(r.rep, a, -1, x, -1, &y, 1);
812 }
void cat (const char *, const char *, const char *, String &) [friend]
Definition at line 804 of file BigString.hh.
805 {
806   r.rep = Scat(r.rep, a, -1, x, -1, y, -1);
807 }
void cat (const char *, const char *, const SubString &, String &) [friend]
Definition at line 799 of file BigString.hh.
800 {
801   r.rep = Scat(r.rep, a, -1, x, -1, y.chars(), y.length());
802 }
void cat (const char *, const char *, const String &, String &) [friend]
Definition at line 794 of file BigString.hh.
795 {
796   r.rep = Scat(r.rep, a, -1, x, -1, y.chars(), y.length());
797 }
void cat (const char *, const SubString &, char, String &) [friend]
Definition at line 789 of file BigString.hh.
790 {
791   r.rep = Scat(r.rep, a, -1, x.chars(), x.length(), &y, 1);
792 }
void cat (const char *, const SubString &, const char *, String &) [friend]
Definition at line 784 of file BigString.hh.
785 {
786   r.rep = Scat(r.rep, a, -1, x.chars(), x.length(), y, -1);
787 }
void cat (const char *, const SubString &, const SubString &, String &) [friend]
Definition at line 779 of file BigString.hh.
780 {
781   r.rep = Scat(r.rep, a, -1, x.chars(), x.length(), y.chars(), y.length());
782 }
void cat (const char *, const SubString &, const String &, String &) [friend]
Definition at line 774 of file BigString.hh.
775 {
776   r.rep = Scat(r.rep, a, -1, x.chars(), x.length(), y.chars(), y.length());
777 }
void cat (const char *, const String &, char, String &) [friend]
Definition at line 769 of file BigString.hh.
770 {
771   r.rep = Scat(r.rep, a, -1, x.chars(), x.length(), &y, 1);
772 }
void cat (const char *, const String &, const char *, String &) [friend]
Definition at line 764 of file BigString.hh.
765 {
766   r.rep = Scat(r.rep, a, -1, x.chars(), x.length(), y, -1);
767 }
void cat (const char *, const String &, const SubString &, String &) [friend]
Definition at line 759 of file BigString.hh.
760 {
761   r.rep = Scat(r.rep, a, -1, x.chars(), x.length(), y.chars(), y.length());
762 }
void cat (const char *, const String &, const String &, String &) [friend]
Definition at line 754 of file BigString.hh.
755 {
756   r.rep = Scat(r.rep, a, -1, x.chars(), x.length(), y.chars(), y.length());
757 }
void cat (const String &, const char *, char, String &) [friend]
Definition at line 748 of file BigString.hh.
749 {
750   r.rep = Scat(r.rep, a.chars(), a.length(), x, -1, &y, 1);
751 }
void cat (const String &, const char *, const char *, String &) [friend]
Definition at line 743 of file BigString.hh.
744 {
745   r.rep = Scat(r.rep, a.chars(), a.length(), x, -1, y, -1);
746 }
void cat (const String &, const char *, const SubString &, String &) [friend]
Definition at line 738 of file BigString.hh.
739 {
740   r.rep = Scat(r.rep, a.chars(), a.length(), x, -1, y.chars(), y.length());
741 }
void cat (const String &, const char *, const String &, String &) [friend]
Definition at line 733 of file BigString.hh.
734 {
735   r.rep = Scat(r.rep, a.chars(), a.length(), x, -1, y.chars(), y.length());
736 }
void cat (const String &, const SubString &, char, String &) [friend]
Definition at line 728 of file BigString.hh.
729 {
730   r.rep = Scat(r.rep, a.chars(), a.length(), x.chars(), x.length(), &y, 1);
731 }
void cat (const String &, const SubString &, const char *, String &) [friend]
Definition at line 723 of file BigString.hh.
724 {
725   r.rep = Scat(r.rep, a.chars(), a.length(), x.chars(), x.length(), y, -1);
726 }
void cat (const String &, const SubString &, const SubString &, String &) [friend]
Definition at line 718 of file BigString.hh.
719 {
720   r.rep = Scat(r.rep, a.chars(), a.length(), x.chars(), x.length(), y.chars(), y.length());
721 }
void cat (const String &, const SubString &, const String &, String &) [friend]
Definition at line 713 of file BigString.hh.
714 {
715   r.rep = Scat(r.rep, a.chars(), a.length(), x.chars(), x.length(), y.chars(), y.length());
716 }
void cat (const String &, const String &, char, String &) [friend]
Definition at line 708 of file BigString.hh.
709 {
710   r.rep = Scat(r.rep, a.chars(), a.length(), x.chars(), x.length(), &y, 1);
711 }
void cat (const String &, const String &, const char *, String &) [friend]
Definition at line 703 of file BigString.hh.
704 {
705   r.rep = Scat(r.rep, a.chars(), a.length(), x.chars(), x.length(), y, -1);
706 }
void cat (const String &, const String &, const SubString &, String &) [friend]
Definition at line 698 of file BigString.hh.
699 {
700   r.rep = Scat(r.rep, a.chars(), a.length(), x.chars(), x.length(), y.chars(), y.length());
701 }
void cat (const String &, const String &, const String &, String &) [friend]
Definition at line 693 of file BigString.hh.
694 {
695   r.rep = Scat(r.rep, a.chars(), a.length(), x.chars(), x.length(), y.chars(), y.length());
696 }
void cat (const char *, char, String &) [friend]
Definition at line 688 of file BigString.hh.
689 {
690   r.rep = Scat(r.rep, x, -1, &y, 1);
691 }
void cat (const char *, const char *, String &) [friend]
Definition at line 683 of file BigString.hh.
684 {
685   r.rep = Scat(r.rep, x, -1, y, -1);
686 }
void cat (const char *, const SubString &, String &) [friend]
Definition at line 678 of file BigString.hh.
679 {
680   r.rep = Scat(r.rep, x, -1, y.chars(), y.length());
681 }
void cat (const char *, const String &, String &) [friend]
Definition at line 673 of file BigString.hh.
674 {
675   r.rep = Scat(r.rep, x, -1, y.chars(), y.length());
676 }
void cat (const SubString &, char, String &) [friend]
Definition at line 668 of file BigString.hh.
669 {
670   r.rep = Scat(r.rep, x.chars(), x.length(), &y, 1);
671 }
void cat (const SubString &, const char *, String &) [friend]
Definition at line 663 of file BigString.hh.
664 {
665   r.rep = Scat(r.rep, x.chars(), x.length(), y, -1);
666 }
void cat (const SubString &, const SubString &, String &) [friend]
Definition at line 658 of file BigString.hh.
659 {
660   r.rep = Scat(r.rep, x.chars(), x.length(), y.chars(), y.length());
661 }
void cat (const SubString &, const String &, String &) [friend]
Definition at line 653 of file BigString.hh.
654 {
655   r.rep = Scat(r.rep, x.chars(), x.length(), y.chars(), y.length());
656 }
void cat (const String &, char, String &) [friend]
Definition at line 648 of file BigString.hh.
649 {
650   r.rep = Scat(r.rep, x.chars(), x.length(), &y, 1);
651 }
void cat (const String &, const char *, String &) [friend]
Definition at line 643 of file BigString.hh.
644 {
645   r.rep = Scat(r.rep, x.chars(), x.length(), y, -1);
646 }
void cat (const String &, const SubString &, String &) [friend]
Definition at line 638 of file BigString.hh.
639 {
640   r.rep = Scat(r.rep, x.chars(), x.length(), y.chars(), y.length());
641 }
void cat (const String &, const String &, String &) [friend]
Definition at line 633 of file BigString.hh.
Referenced by operator+=().
634 {
635   r.rep = Scat(r.rep, x.chars(), x.length(), y.chars(), y.length());
636 }
String common_prefix (const String & x, const String & y, _BIGSTRING_SIZE startpos = 0) [friend]
Definition at line 1326 of file BigString.cc.
1327 {
1328   String r;
1329   const char* xchars = x.chars();
1330   const char* ychars = y.chars();
1331   const char* xs = &(xchars[startpos]);
1332   const char* ss = xs;
1333   const char* topx = &(xchars[x.length()]);
1334   const char* ys = &(ychars[startpos]);
1335   const char* topy = &(ychars[y.length()]);
1336   _BIGSTRING_LENGTH l;
1337   for (l = 0; xs < topx && ys < topy && *xs++ == *ys++; ++l);
1338   r.rep = Salloc(r.rep, ss, l, l);
1339   return r;
1340 }
String common_suffix (const String & x, const String & y, _BIGSTRING_SIZE startpos = -1) [friend]
Definition at line 1342 of file BigString.cc.
1343 {
1344   String r;
1345   const char* xchars = x.chars();
1346   const char* ychars = y.chars();
1347   const char* xs = &(xchars[x.length() + startpos]);
1348   const char* botx = xchars;
1349   const char* ys = &(ychars[y.length() + startpos]);
1350   const char* boty = ychars;
1351   _BIGSTRING_LENGTH l;
1352   for (l = 0; xs >= botx && ys >= boty && *xs == *ys ; --xs, --ys, ++l);
1353   r.rep = Salloc(r.rep, ++xs, l, l);
1354   return r;
1355 }
String downcase (const String & x) [friend]
Definition at line 1023 of file BigString.hh.
1024 {
1025   String r; r.rep = Sdowncase(x.rep, r.rep); return r;
1026 }
String join (String src[], _BIGSTRING_SIZE n, const String & sep) [friend]
Definition at line 1148 of file BigString.cc.
1149 {
1150   RETURN_OBJECT(String,x)
1151   String sep = separator;
1152   _BIGSTRING_SIZE xlen = 0;
1153   _BIGSTRING_ITERATOR i;
1154   for (i = 0; i < n; ++i)
1155     xlen += src[i].length();
1156   xlen += (n - 1) * sep.length();
1157 
1158   x.rep = Sresize (x.rep, xlen);
1159 
1160   _BIGSTRING_ITERATOR j = 0;
1161   
1162   for (i = 0; i < n - 1; ++i)
1163   {
1164     ncopy(src[i].chars(), &(x.rep->s[j]), src[i].length());
1165     j += src[i].length();
1166     ncopy(sep.chars(), &(x.rep->s[j]), sep.length());
1167     j += sep.length();
1168   }
1169   ncopy0(src[i].chars(), &(x.rep->s[j]), src[i].length());
1170   RETURN(x);
1171 }
ostream& operator<< (ostream & s, const SubString & x) [friend]
Definition at line 1415 of file BigString.cc.
1416 { 
1417   const char* a = x.chars();
1418   const char* lasta = &(a[x.length()]);
1419   while (a < lasta)
1420     s.put(*a++);
1421   return(s);
1422 }
ostream& operator<< (ostream & s, const String & x) [friend]
Definition at line 1261 of file BigString.hh.
1262 {
1263    s << x.chars(); return s;
1264 }
istream& operator>> (istream & s, String & x) [friend]
Definition at line 1361 of file BigString.cc.
1362 {
1363   if (!s.ipfx(0) || (!(s.flags() & ios::skipws) && !ws(s)))
1364   {
1365     s.clear(ios::failbit|s.rdstate()); // Redundant if using GNU iostreams.
1366     return s;
1367   }
1368   int ch;
1369   _BIGSTRING_ITERATOR i = 0;
1370   x.rep = Sresize(x.rep, 20);
1371   register streambuf *sb = s.rdbuf();
1372   while ((ch = sb->sbumpc()) != EOF)
1373   {
1374     if (isspace(ch))
1375       break;
1376     if (i >= x.rep->sz - 1)
1377       x.rep = Sresize(x.rep, i+1);
1378     x.rep->s[i++] = ch;
1379   }
1380   x.rep->s[i] = 0;
1381   x.rep->len = i;
1382   int new_state = s.rdstate();
1383   if (i == 0) new_state |= ios::failbit;
1384   if (ch == EOF) new_state |= ios::eofbit;
1385   s.clear(new_state);
1386   return s;
1387 }
_BIGSTRING_SIZE readline (istream & s, String & x, char terminator = '\n', int discard_terminator = 1) [friend]
Definition at line 1389 of file BigString.cc.
Referenced by readtotag().
1390 {
1391   if (!s.ipfx(0))
1392     return 0;
1393   int ch;
1394   _BIGSTRING_ITERATOR i = 0;
1395   x.rep = Sresize(x.rep, 80);
1396   register streambuf *sb = s.rdbuf();
1397   while ((ch = sb->sbumpc()) != EOF)
1398   {
1399     if (ch != terminator || !discard)
1400     {
1401       if (i >= x.rep->sz - 1)
1402         x.rep = Sresize(x.rep, i+1);
1403       x.rep->s[i++] = ch;
1404     }
1405     if (ch == terminator)
1406       break;
1407   }
1408   x.rep->s[i] = 0;
1409   x.rep->len = i;
1410   if (ch == EOF) s.clear(ios::eofbit|s.rdstate());
1411   return i;
1412 }
String replicate (const String & y, _BIGSTRING_SIZE n) [friend]
Definition at line 1311 of file BigString.cc.
1312 {
1313   String w;
1314   _BIGSTRING_SIZE len = y.length();
1315   w.rep = Sresize(w.rep, n * len);
1316   char* p = w.rep->s;
1317   while (n-- > 0)
1318   {
1319     ncopy(y.chars(), p, len);
1320     p += len;
1321   }
1322   *p = 0;
1323   return w;
1324 }
String replicate (char c, _BIGSTRING_SIZE n) [friend]
Definition at line 1301 of file BigString.cc.
1302 {
1303   String w;
1304   w.rep = Sresize(w.rep, n);
1305   char* p = w.rep->s;
1306   while (n-- > 0) *p++ = c;
1307   *p = 0;
1308   return w;
1309 }
String reverse (const String & x) [friend]
Definition at line 1013 of file BigString.hh.
1014 {
1015   String r; r.rep = Sreverse(x.rep, r.rep); return r;
1016 }
_BIGSTRING_SIZE split (const String & x, String res[], _BIGSTRING_SIZE maxn, const BigRegex & sep) [friend]
Definition at line 1117 of file BigString.cc.
1118 {
1119   String x = src;
1120   const char* s = x.chars();
1121   _BIGSTRING_SIZE sl = x.length();
1122   _BIGSTRING_ITERATOR i = 0;
1123   _BIGSTRING_SIZE pos = 0;
1124   _BIGSTRING_SIZE p, matchlen;
1125   while (i < n && pos < sl)
1126   {
1127     p = r.search(s, sl, matchlen, pos);
1128     if (p < 0)
1129       p = sl;
1130     results[i].rep = Salloc(results[i].rep, &(s[pos]), p - pos, p - pos);
1131     i++;
1132     pos = p + matchlen;
1133   }
1134   return i;
1135 }
_BIGSTRING_SIZE split (const String & x, String res[], _BIGSTRING_SIZE maxn, const String & sep) [friend]
Definition at line 1098 of file BigString.cc.
1099 {
1100   String x = src;
1101   const char* s = x.chars();
1102   _BIGSTRING_SIZE sl = x.length();
1103   _BIGSTRING_ITERATOR i = 0;
1104   _BIGSTRING_SIZE pos = 0;
1105   while (i < n && pos < sl)
1106   {
1107     _BIGSTRING_SIZE p = x.search(pos, sl, sep.chars(), sep.length());
1108     if (p < 0)
1109       p = sl;
1110     results[i].rep = Salloc(results[i].rep, &(s[pos]), p - pos, p - pos);
1111     i++;
1112     pos = p + sep.length();
1113   }
1114   return i;
1115 }
friend class SubString [friend]
Definition at line 165 of file BigString.hh.
String upcase (const String & x) [friend]
Definition at line 1018 of file BigString.hh.
Referenced by extract_paper_plan_to_paper(), Financial_Note::get(), get_Paper_Plans_Section_IDs(), include_protected_text(), and Target_Access::set_target().
1019 {
1020   String r; r.rep = Supcase(x.rep, r.rep); return r;
1021 }
Member Data Documentation
StrRep* String::rep [protected]
Definition at line 168 of file BigString.hh.
Referenced by alloc(), allocation(), SubString::assign(), capitalize(), capitalize(), cat(), SubString::chars(), chars(), common_prefix(), common_suffix(), downcase(), downcase(), elem(), empty(), length(), SubString::OK(), SubString::operator=(), operator=(), operator>>(), operator[](), prepend(), readline(), replicate(), reverse(), reverse(), split(), String(), upcase(), upcase(), and ~String().
The documentation for this class was generated from the following files:
BigString.hh
BigString.cc