Plan_entry_content Class Reference
#include <dil2al.hh>
Public Methods
Plan_entry_content (DIL_entry &e, int pet, int parsefrom=-1)
int get_decision ()
DIL_ID & Decision ()
DIL_entry * Decision_Ptr ()
void Parse_Entry_Content (int parsefrom=0)
Protected Attributes
DIL_entry * entry
int planentrytype
int decision
DIL_ID decisionID
DIL_entry * decisionptr
Constructor & Destructor Documentation
Plan_entry_content::Plan_entry_content (DIL_entry & e, int pet, int parsefrom = -1) [inline]
Definition at line 471 of file dil2al.hh.
References decision, Parse_Entry_Content(), and planentrytype.
471 : entry(&e), planentrytype(pet), decision(-1), decisionID(), decisionptr(NULL) { if (parsefrom>=0) Parse_Entry_Content(parsefrom); }
Member Function Documentation
DIL_ID& Plan_entry_content::Decision () [inline]
Definition at line 473 of file dil2al.hh.
Referenced by DIL_Visualize_with_FORM_Tabs::Visualize_Plan_Entry().
473 { return decisionID; }
DIL_entry * Plan_entry_content::Decision_Ptr () [inline]
Definition at line 1166 of file dil2al.hh.
References decisionID, decisionptr, DIL_entry::elbyid(), and entry.
1166                                                     {
1167   if (!decisionptr) decisionptr=entry->elbyid(decisionID);
1168   return decisionptr;
1169 }
int Plan_entry_content::get_decision () [inline]
Definition at line 472 of file dil2al.hh.
References decision.
472 { return decision; }
void Plan_entry_content::Parse_Entry_Content (int parsefrom = 0)
Definition at line 551 of file utilities.cc.
References String::contains(), DIL_entry::content, decision, decisionID, entry, HTML_get_href(), HTML_get_list(), HTML_get_list_item(), HTML_remove_comments(), String::index(), PLAN_ENTRY_DECISION_TAG, PLAN_ENTRY_TYPE_GOAL, planentrytype, DIL_entry_content::text, and DIL_ID::valid().
Referenced by Plan_entry_content().
551                                                               {
552   // find plan specific information in DIL entry text content
553   if (planentrytype==PLAN_ENTRY_TYPE_GOAL) {
554     String & ctxt = *(entry->content->text);
555     int i;
556     // note: This assumes that action alternatives are elements of the first
557     // ordered list in the text.
558     if ((i=ctxt.index("<OL>",parsefrom))>=0) {
559       String listparams, listcontent;
560       if ((i=HTML_get_list(ctxt,i,listparams,listcontent))>=0) {
561         HTML_remove_comments(listcontent);
562         String itemcontent; int j = 0; decision = -1;
563         while ((j=HTML_get_list_item(listcontent,j,listparams,itemcontent))>=0) {
564           decision++;
565           // *** The decision tag has not yet been tested
566           if (itemcontent.contains(PLAN_ENTRY_DECISION_TAG)) {
567             String hreftext;
568             if (HTML_get_href(itemcontent,0,listparams,hreftext)>=0) {
569               decisionID = hreftext;
570               break;
571             }
572           }
573         }
574         if (decision==0) if (HTML_get_href(itemcontent,0,listparams,listcontent)>=0) decisionID = listcontent;
575         if ((decision>0) && (!decisionID.valid())) decision = -1; // alternatives exist, but no decision specified
576       }
577     }
578   }
579 }
Member Data Documentation
int Plan_entry_content::decision [protected]
Definition at line 467 of file dil2al.hh.
Referenced by get_decision(), Parse_Entry_Content(), and Plan_entry_content().
DIL_ID Plan_entry_content::decisionID [protected]
Definition at line 468 of file dil2al.hh.
Referenced by Decision_Ptr(), and Parse_Entry_Content().
DIL_entry* Plan_entry_content::decisionptr [protected]
Definition at line 469 of file dil2al.hh.
Referenced by Decision_Ptr().
DIL_entry* Plan_entry_content::entry [protected]
Definition at line 465 of file dil2al.hh.
Referenced by Decision_Ptr(), and Parse_Entry_Content().
int Plan_entry_content::planentrytype [protected]
Definition at line 466 of file dil2al.hh.
Referenced by Parse_Entry_Content(), and Plan_entry_content().
The documentation for this class was generated from the following files:
dil2al.hh
utilities.cc