DIL_ID Class Reference
#include <dil2al.hh>
Public Methods
DIL_ID ()
DIL_ID (idnumber idmaj0, idnumber idmaj1, unsigned int idmin)
DIL_ID (DIL_ID &id)
DIL_ID (String &idstr)
DIL_ID (const SubString &idstr)
DIL_ID & operator= (const DIL_ID &id)
bool operator== (const DIL_ID &id2) const
bool operator!= (const DIL_ID &id2) const
bool operator< (const DIL_ID &id2) const
bool operator<= (const DIL_ID &id2) const
bool operator> (const DIL_ID &id2) const
bool operator>= (const DIL_ID &id2) const
DIL_ID & operator= (String &idstr)
DIL_ID & operator= (String *idstr)
String str () const
const char * chars () const
operator const char * () const
bool valid ()
bool Write_DIL_ID_to_Binary_Cache (ofstream &cfl)
bool Read_DIL_ID_from_Binary_Cache (ifstream &cfl)
Public Attributes
idnumber idmajor [2]
unsigned int idminor
Protected Methods
void init (String &idstr)
Constructor & Destructor Documentation
DIL_ID::DIL_ID () [inline]
Definition at line 410 of file dil2al.hh.
References idmajor, and idminor.
410 : idminor(0) { idmajor[0]=0; idmajor[1]=0; }
DIL_ID::DIL_ID (idnumber idmaj0, idnumber idmaj1, unsigned int idmin) [inline]
Definition at line 411 of file dil2al.hh.
References idmajor, idminor, and idnumber.
411 : idminor(idmin) { idmajor[0]=idmaj0; idmajor[1]=idmaj1; }
DIL_ID::DIL_ID (DIL_ID & id) [inline]
Definition at line 412 of file dil2al.hh.
References idmajor, and idminor.
412 : idminor(id.idminor) { idmajor[0]=id.idmajor[0]; idmajor[1]=id.idmajor[1]; }
DIL_ID::DIL_ID (String & idstr) [inline]
Definition at line 413 of file dil2al.hh.
References init().
413 { init(idstr); }
DIL_ID::DIL_ID (const SubString & idstr) [inline]
Definition at line 414 of file dil2al.hh.
References init().
414 { String s(idstr); init(s); }
Member Function Documentation
const char* DIL_ID::chars () const [inline]
Definition at line 444 of file dil2al.hh.
References String::chars(), and str().
Referenced by Active_List::Active_List(), DIL_Required_Task_Chunks(), generate_AL(), generate_EPS_cells(), Active_List::generate_focused_AL(), generate_modify_element_FORM_interface_DIL_entry_content(), generate_modify_element_FORM_interface_DIL_entry_parameters(), Active_List::generate_wide_AL(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), Detailed_Items_List::Get_All_Topical_DIL_Parameters(), modify_DIL_entry_target_date(), modify_DIL_group_target_dates(), modify_DIL_group_target_dates_cmd(), modify_element_through_FORM_interface(), operator const char *(), DIL_entry::Propagated_Target_Date(), Detailed_Items_List::Read_Topical_from_Binary_Cache(), Show_DIL_Hierarchy(), update_DIL_entry_parameter_elements(), update_DIL_to_AL(), update_main_ALs(), DIL_Visualize_with_FORM_Tabs::Visualize_Element(), DIL_Visualize_with_HTML_Tabs::Visualize_Element(), and DIL_Visualize_with_Tabs::Visualize_Element().
444                                    { 
445     /*cout << "CHECKING: ";
446       for (char * tp = (char *) str().chars(); *tp!='\0'; tp++) cout << (*tp) << '[' << (int) (*tp) << ']';
447       cout << '\n';*/
448     /*String idstr(str());
449       cout << "idstr in chars() function: ";
450       int i = 0;
451       for (char * tp = (char *) idstr.chars(); (*tp!='\0') && (i<80); tp++, i++) cout << (*tp) << '{' << (int) (*tp) << '}';
452       cout << '\n';*/
453     static String idstr; // need static here to avoid trouble with life-time of object that chars() return points to
454     idstr = str();
455     return idstr.chars(); }
void DIL_ID::init (String & idstr) [inline, protected]
Definition at line 401 of file dil2al.hh.
References String::after(), String::at(), String::before(), String::from(), idmajor, idminor, and String::length().
Referenced by DIL_ID(), and operator=().
401                             {
402     String idmajorstr(idstr.before('.'));
403     idmajor[0] = (idnumber) atol((const char *) String(idmajorstr.at(0,idmajorstr.length()-6)));
404     idmajor[1] = (idnumber) atol((const char *) String(idmajorstr.from(((int) idmajorstr.length())-6)));
405     idminor = (unsigned int) atoi((const char *) String(idstr.after('.')));
406   }
DIL_ID::operator const char * () const [inline]
Definition at line 456 of file dil2al.hh.
References chars().
456 { return chars(); }
bool DIL_ID::operator!= (const DIL_ID & id2) const [inline]
Definition at line 425 of file dil2al.hh.
425 { return (!(*this==id2)); }
bool DIL_ID::operator< (const DIL_ID & id2) const [inline]
Definition at line 426 of file dil2al.hh.
References idmajor, and idminor.
426 { return ((idmajor[0]<id2.idmajor[0]) || ((idmajor[0]==id2.idmajor[0]) && (idmajor[1]<id2.idmajor[1])) || ((idmajor[0]==id2.idmajor[0]) && (idmajor[1]==id2.idmajor[1]) && (idminor<id2.idminor))); }
bool DIL_ID::operator<= (const DIL_ID & id2) const [inline]
Definition at line 427 of file dil2al.hh.
427 { return ((*this<id2) || (*this==id2)); }
DIL_ID& DIL_ID::operator= (String * idstr) [inline]
Definition at line 432 of file dil2al.hh.
References init().
432 { init(*idstr); }
DIL_ID& DIL_ID::operator= (String & idstr) [inline]
Definition at line 431 of file dil2al.hh.
References init().
431 { init(idstr); }
DIL_ID& DIL_ID::operator= (const DIL_ID & id) [inline]
Definition at line 423 of file dil2al.hh.
References idmajor, and idminor.
423 { idmajor[0]=id.idmajor[0]; idmajor[1]=id.idmajor[1]; idminor=id.idminor; return *this; }
bool DIL_ID::operator== (const DIL_ID & id2) const [inline]
Definition at line 424 of file dil2al.hh.
References idmajor, and idminor.
424 { return ((idmajor[0]==id2.idmajor[0]) && (idmajor[1]==id2.idmajor[1]) && (idminor==id2.idminor)); }
bool DIL_ID::operator> (const DIL_ID & id2) const [inline]
Definition at line 428 of file dil2al.hh.
428 { return (id2<*this); }
bool DIL_ID::operator>= (const DIL_ID & id2) const [inline]
Definition at line 429 of file dil2al.hh.
429 { return (id2<=*this); }
bool DIL_ID::Read_DIL_ID_from_Binary_Cache (ifstream & cfl)
Definition at line 542 of file utilities.cc.
References READSOMETYPE.
Referenced by DIL_entry::Read_from_Binary_Cache(), and Detailed_Items_List::Read_Topical_from_Binary_Cache().
542                                                          {
543   // DIL_ID
544   if ((cfl.read((READSOMETYPE) this, sizeof(DIL_ID))).gcount()<sizeof(DIL_ID)) return false;
545   // alternative code:
546   //  if ((cfl.read((READSOMETYPE) idmajor, sizeof(idnumber)*2)).gcount()<(sizeof(idnumber)*2)) return false;
547   //  if ((cfl.read((READSOMETYPE) (&idminor), sizeof(idminor))).gcount()<sizeof(idminor)) return false;
548   return true;
549 }
String DIL_ID::str () const
Definition at line 523 of file utilities.cc.
References idmajor, idminor, String::length(), and String::prepend().
Referenced by chars(), Active_List::generate_focused_AL(), DIL_AL_List::IsSelfReference(), modify_element_through_FORM_interface(), DIL_entry::Propagated_Target_Date(), Detailed_Items_List::Read_from_Binary_Cache(), DIL_Visualize_with_FORM_Tabs::Visualize_Element(), and DIL_Visualize_with_FORM_Tabs::Visualize_Plan_Entry().
523                          {
524         static String idstr; // stored in function, not objects, static to avoid problems with lifetime of object that return value points to
525         idstr = String((long) idmajor[1]);
526         while (idstr.length()<6) idstr.prepend('0');
527         idstr.prepend(String((long) idmajor[0]));
528         idstr += '.' + String((long) idminor);
529 /*cout << "chars() RESULT at end of str() function: ";
530 int i = 0;
531 for (char * tp = (char *) idstr.chars(); (*tp!='\0') && (i<80); tp++, i++) cout << (*tp) << '{' << (int) (*tp) << '}';
532 cout << '\n';*/
533         return idstr;
534 }
bool DIL_ID::valid () [inline]
Definition at line 458 of file dil2al.hh.
References idmajor, and idminor.
Referenced by generate_modify_element_FORM_interface(), generate_modify_element_FORM_interface_DIL_entry_parameters(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), DIL_AL_List::IsSelfReference(), modify_element_through_FORM_interface(), Plan_entry_content::Parse_Entry_Content(), DIL_entry::Propagated_Target_Date(), DIL_AL_List::Superiorbyid(), Tabbed_DIL_Hierarchy(), Tabbed_FORM_DIL_Hierarchy(), and Tabbed_HTML_DIL_Hierarchy().
458 { return ((idmajor[0]!=0) && (idmajor[1]!=0) && (idminor!=0)); }
bool DIL_ID::Write_DIL_ID_to_Binary_Cache (ofstream & cfl)
Definition at line 536 of file utilities.cc.
Referenced by DIL_entry::Write_to_Binary_Cache(), and DIL_entry::Write_Topical_to_Binary_Cache().
536                                                         {
537   // DIL_ID
538   cfl.write((const void *) this, sizeof(DIL_ID));
539   return true;
540 }
Member Data Documentation
idnumber DIL_ID::idmajor[2]
Definition at line 420 of file dil2al.hh.
Referenced by DIL_ID(), init(), operator<(), operator=(), operator==(), str(), and valid().
unsigned int DIL_ID::idminor
Definition at line 421 of file dil2al.hh.
Referenced by DIL_ID(), init(), operator<(), operator=(), operator==(), str(), and valid().
The documentation for this class was generated from the following files:
dil2al.hh
utilities.cc