PLLRoot< PLLType > Class Template Reference
#include <templates.classic.hh>
Public Methods
~PLLRoot ()
PLLRoot ()
PLLType * head () const
PLLType * tail () const
PLLType * el (int n) const
PLLType * operator[] (int n) const
int length () const
void update ()
bool link_before (PLLRoot *succ)
bool link_before (PLLType *succ)
bool link_after (PLLRoot *pred)
bool link_after (PLLType *pred)
bool insert_after (PLLType *pred, PLLType *inshead)
bool insert_after (int n, PLLType *inshead)
bool insert_before (PLLType *succ, PLLType *inshead)
bool insert_before (int n, PLLType *inshead)
void clear ()
~PLLRoot ()
PLLRoot ()
PLLType * head () const
PLLType * tail () const
PLLType * el (int n) const
PLLType * operator[] (int n) const
int length () const
void update ()
bool link_before (PLLRoot *succ)
bool link_before (PLLType *succ)
bool link_after (PLLRoot *pred)
bool link_after (PLLType *pred)
bool insert_after (PLLType *pred, PLLType *inshead)
bool insert_after (int n, PLLType *inshead)
bool insert_before (PLLType *succ, PLLType *inshead)
bool insert_before (int n, PLLType *inshead)
void clear ()
~PLLRoot ()
PLLRoot ()
PLLType * head () const
PLLType * tail () const
PLLType * el (int n) const
PLLType * operator[] (int n) const
int length () const
void update ()
bool link_before (PLLRoot *succ)
bool link_before (PLLType *succ)
bool link_after (PLLRoot *pred)
bool link_after (PLLType *pred)
bool insert_after (PLLType *pred, PLLType *inshead)
bool insert_after (int n, PLLType *inshead)
bool insert_before (PLLType *succ, PLLType *inshead)
bool insert_before (int n, PLLType *inshead)
void clear ()
~PLLRoot ()
PLLRoot ()
PLLType * head () const
PLLType * tail () const
PLLType * el (int n) const
PLLType * operator[] (int n) const
int length () const
void update ()
bool link_before (PLLRoot *succ)
bool link_before (PLLType *succ)
bool link_after (PLLRoot *pred)
bool link_after (PLLType *pred)
bool insert_after (PLLType *pred, PLLType *inshead)
bool insert_after (int n, PLLType *inshead)
bool insert_before (PLLType *succ, PLLType *inshead)
bool insert_before (int n, PLLType *inshead)
void clear ()
Protected Methods
void set_root (PLLHandle< PLLType > *h)
void set_root (PLLHandle< PLLType > *h)
void set_root (PLLType *h)
void set_root (PLLHandle< PLLType > *h)
Protected Attributes
PLLHandle< PLLType > * pllhead
PLLHandle< PLLType > * plltail
PLLHandle< PLLType > * pllhead
PLLHandle< PLLType > * plltail
PLLType * pllhead
PLLType * plltail
PLLHandle< PLLType > * pllhead
PLLHandle< PLLType > * plltail
template<class PLLType> class PLLRoot< PLLType >
Constructor & Destructor Documentation
template<class PLLType> PLLRoot< PLLType >::~PLLRoot () [inline]
Definition at line 84 of file templates.classic.hh.
84 { delete pllhead; } // *** perhaps also make this virtual, but delete is not usually called on a PLLRoot<PLLType> object
template<class PLLType> PLLRoot< PLLType >::PLLRoot () [inline]
Definition at line 85 of file templates.classic.hh.
85 : pllhead(NULL), plltail(NULL) {} 
template<class PLLType> PLLRoot< PLLType >::~PLLRoot () [inline]
Definition at line 84 of file templates.clean.hh.
84 { delete pllhead; } // *** perhaps also make this virtual, but delete is not usually called on a PLLRoot<PLLType> object
template<class PLLType> PLLRoot< PLLType >::PLLRoot () [inline]
Definition at line 85 of file templates.clean.hh.
85 : pllhead(NULL), plltail(NULL) {} 
template<class PLLType> PLLRoot< PLLType >::~PLLRoot () [inline]
Definition at line 109 of file templates.hh.
109                            {
110 //cerr << "PLLR=" << (int) this << " head=" << (int) pllhead << '\n'; cerr.flush();
111                 clear(); } // *** perhaps also make this virtual, but delete is not usually called on a PLLRoot<PLLType> object
template<class PLLType> PLLRoot< PLLType >::PLLRoot () [inline]
Definition at line 112 of file templates.hh.
112 : pllhead(NULL), plltail(NULL) {}
template<class PLLType> PLLRoot< PLLType >::~PLLRoot () [inline]
Definition at line 84 of file templates.unfixed.hh.
84 { delete pllhead; } // *** perhaps also make this virtual, but delete is not usually called on a PLLRoot<PLLType> object
template<class PLLType> PLLRoot< PLLType >::PLLRoot () [inline]
Definition at line 85 of file templates.unfixed.hh.
85 : pllhead(NULL), plltail(NULL) {} 
Member Function Documentation
template<class PLLType> void PLLRoot< PLLType >::clear () [inline]
Definition at line 104 of file templates.unfixed.hh.
104 { delete pllhead; pllhead = NULL; plltail = NULL; }
template<class PLLType> void PLLRoot< PLLType >::clear () [inline]
Definition at line 131 of file templates.hh.
131 { if (pllhead) pllhead->pllsignal = PLLHandle<PLLType>::PLL_LIST_DESTRUCT; delete pllhead; pllhead = NULL; plltail = NULL; }
template<class PLLType> void PLLRoot< PLLType >::clear () [inline]
Definition at line 104 of file templates.clean.hh.
104 { delete pllhead; pllhead = NULL; plltail = NULL; }
template<class PLLType> void PLLRoot< PLLType >::clear () [inline]
Definition at line 104 of file templates.classic.hh.
Referenced by Detailed_Items_List::Get_All_Topical_DIL_Parameters(), search(), search_output(), and PLLRoot< DIL_entry_Pointer >::~PLLRoot().
104 { delete pllhead; pllhead = NULL; plltail = NULL; }
template<class PLLType> PLLType* PLLRoot< PLLType >::el (int n) const [inline]
Definition at line 88 of file templates.unfixed.hh.
88 { if (pllhead) return pllhead->el(n); return NULL; } 
template<class PLLType> PLLType* PLLRoot< PLLType >::el (int n) const [inline]
Definition at line 115 of file templates.hh.
115 { if (pllhead) return pllhead->el(n); return NULL; } 
template<class PLLType> PLLType* PLLRoot< PLLType >::el (int n) const [inline]
Definition at line 88 of file templates.clean.hh.
88 { if (pllhead) return pllhead->el(n); return NULL; } 
template<class PLLType> PLLType* PLLRoot< PLLType >::el (int n) const [inline]
Definition at line 88 of file templates.classic.hh.
Referenced by PLLRoot< PLLType >::insert_after(), PLLRoot< PLLType >::insert_before(), and PLLRoot< DIL_entry_Pointer >::operator[]().
88 { if (pllhead) return pllhead->el(n); return NULL; } 
template<class PLLType> PLLType* PLLRoot< PLLType >::head () const [inline]
Definition at line 86 of file templates.unfixed.hh.
86 { return static_cast<PLLType *>(pllhead); } 
template<class PLLType> PLLType* PLLRoot< PLLType >::head () const [inline]
Definition at line 113 of file templates.hh.
113 { return pllhead; } 
template<class PLLType> PLLType* PLLRoot< PLLType >::head () const [inline]
Definition at line 86 of file templates.clean.hh.
86 { return static_cast<PLLType *>(pllhead); } 
template<class PLLType> PLLType* PLLRoot< PLLType >::head () const [inline]
Definition at line 86 of file templates.classic.hh.
Referenced by Active_List::AL_Head(), Active_List::available_before(), Topical_DIL_Files_Root::File(), financial_monthly(), PLLHandle< DIL_entry_Pointer >::head(), Topical_DIL_Files_Root::Invalidate(), PLLRoot< PLLType >::link_after(), PLLRoot< PLLType >::link_before(), Financial_Note::link_sorted(), Topical_DIL_Files_Root::operator[](), Topical_DIL_Files_Root::Refresh(), search(), search_output(), AL_Day::TC_Head(), AL_Day::TD_Head(), Topical_DIL_Files_Root::Title(), Topical_DIL_Files_Root::Topic(), PLLHandle< PLLType >::unlink_after(), PLLHandle< PLLType >::unlink_before(), update_DIL_entry_parameter_elements(), write_financial_notes_file(), and Detailed_Items_List::Write_Topical_to_Binary_Cache().
86 { return (PLLType *)const_cast<PLLHandle<PLLType> *>(pllhead); } 
template<class PLLType> bool PLLRoot< PLLType >::insert_after (int n, PLLType * inshead) [inline]
template<class PLLType> bool PLLRoot< PLLType >::insert_after (PLLType * pred, PLLType * inshead) [inline]
template<class PLLType> bool PLLRoot< PLLType >::insert_after (int n, PLLType * inshead) [inline]
template<class PLLType> bool PLLRoot< PLLType >::insert_after (PLLType * pred, PLLType * inshead) [inline]
template<class PLLType> bool PLLRoot< PLLType >::insert_after (int n, PLLType * inshead) [inline]
template<class PLLType> bool PLLRoot< PLLType >::insert_after (PLLType * pred, PLLType * inshead) [inline]
template<class PLLType> bool PLLRoot< PLLType >::insert_after (int n, PLLType * inshead) [inline]
Definition at line 304 of file templates.classic.hh.
References PLLRoot< PLLType >::el(), PLLRoot< PLLType >::insert_after(), and pred.
304                                                                    {
305 // inserts inshead after the nth element in this list
306 // if nth element does not exist, inserts at tail of list
307         PLLType * pred = el(n);
308         return insert_after(pred,inshead);
309 } 
template<class PLLType> bool PLLRoot< PLLType >::insert_after (PLLType * pred, PLLType * inshead) [inline]
Definition at line 291 of file templates.classic.hh.
References PLLRoot< PLLType >::link_after(), PLLRoot< PLLType >::link_before(), pred, res, and PLLType< PLLType >::unlink_after().
Referenced by PLLRoot< PLLType >::insert_after().
291                                                                             {
292 // inserts inshead after element pred in this list
293 // if pred==NULL or pred->Root()!=this, inserts at tail of list
294         if (!pred) return link_before(inshead); // link inshead to tail of this
295         if (pred->Root()!=this) return link_before(inshead); // link inshead to tail of this
296         PLLRoot<PLLType> h;
297         pred->unlink_after(h); // get head of list up to pred into h
298         bool res = h.link_before(inshead); // link inshead to tail of h
299         link_after(&h); // link h to head of this
300         return res;
301 } 
template<class PLLType> bool PLLRoot< PLLType >::insert_before (int n, PLLType * inshead) [inline]
template<class PLLType> bool PLLRoot< PLLType >::insert_before (PLLType * succ, PLLType * inshead) [inline]
template<class PLLType> bool PLLRoot< PLLType >::insert_before (int n, PLLType * inshead) [inline]
template<class PLLType> bool PLLRoot< PLLType >::insert_before (PLLType * succ, PLLType * inshead) [inline]
template<class PLLType> bool PLLRoot< PLLType >::insert_before (int n, PLLType * inshead) [inline]
template<class PLLType> bool PLLRoot< PLLType >::insert_before (PLLType * succ, PLLType * inshead) [inline]
template<class PLLType> bool PLLRoot< PLLType >::insert_before (int n, PLLType * inshead) [inline]
Definition at line 325 of file templates.classic.hh.
References PLLRoot< PLLType >::el(), PLLRoot< PLLType >::insert_before(), and succ.
325                                                                     {
326 // inserts inshead before the nth element in this list
327 // if nth element does not exist, inserts at head of list
328         PLLType * succ = el(n);
329         return insert_before(succ,inshead);
330 } 
template<class PLLType> bool PLLRoot< PLLType >::insert_before (PLLType * succ, PLLType * inshead) [inline]
Definition at line 312 of file templates.classic.hh.
References PLLRoot< PLLType >::link_after(), PLLRoot< PLLType >::link_before(), res, succ, and PLLType< PLLType >::unlink_before().
Referenced by PLLRoot< PLLType >::insert_before(), and Financial_Note::link_sorted().
312                                                                              {
313 // inserts inshead before element succ in this list
314 // if succ==NULL or succ->Root()!=this, inserts at head of list
315         if (!succ) return link_after(inshead); // link inshead to head of this
316         if (succ->Root()!=this) return link_after(inshead); // link inshead to head of this
317         PLLRoot<PLLType> t;
318         succ->unlink_before(t); // get tail of list from succ into t
319         bool res = t.link_after(inshead); // link inshead to head of t
320         link_before(&t); // link t to tail of this
321         return res;
322 } 
template<class PLLType> int PLLRoot< PLLType >::length () const [inline]
Definition at line 90 of file templates.unfixed.hh.
90 { if (pllhead) return pllhead->length(); return 0; } 
template<class PLLType> int PLLRoot< PLLType >::length () const [inline]
Definition at line 117 of file templates.hh.
117 { if (pllhead) return pllhead->length(); return 0; } 
template<class PLLType> int PLLRoot< PLLType >::length () const [inline]
Definition at line 90 of file templates.clean.hh.
90 { if (pllhead) return pllhead->length(); return 0; } 
template<class PLLType> int PLLRoot< PLLType >::length () const [inline]
Definition at line 90 of file templates.classic.hh.
Referenced by search_output(), and Detailed_Items_List::Write_Topical_to_Binary_Cache().
90 { if (pllhead) return pllhead->length(); return 0; } 
template<class PLLType> bool PLLRoot< PLLType >::link_after (PLLType * pred) [inline]
template<class PLLType> bool PLLRoot< PLLType >::link_after (PLLRoot< PLLType > * pred) [inline]
template<class PLLType> bool PLLRoot< PLLType >::link_after (PLLType * pred) [inline]
template<class PLLType> bool PLLRoot< PLLType >::link_after (PLLRoot< PLLType > * pred) [inline]
template<class PLLType> bool PLLRoot< PLLType >::link_after (PLLType * pred) [inline]
template<class PLLType> bool PLLRoot< PLLType >::link_after (PLLRoot< PLLType > * pred) [inline]
template<class PLLType> bool PLLRoot< PLLType >::link_after (PLLType * pred) [inline]
Definition at line 275 of file templates.classic.hh.
References PLLRoot< PLLType >::link_after(), PLLRoot< PLLType >::pllhead, PLLType< PLLType >::pllnext, PLLRoot< PLLType >::plltail, pred, and PLLRoot< PLLType >::set_root().
275                                                        { 
276 // when succ->Root()==NULL, this allows previously
277 // unprotected lists or newly created PLLType elements
278 // to be linked
279         if (!pred) return false; 
280         if (pred->Root()) return link_after(pred->Root()); 
281         if (pllhead) { 
282                 pllhead->pllprev = pred; 
283                 pred->pllnext = pllhead; 
284         } else plltail = pred; 
285         pllhead = pred;  // *** this may need to be pred->seek_head(), unless lists without root cannot exist
286         set_root(pred); 
287         return true; 
288 }
template<class PLLType> bool PLLRoot< PLLType >::link_after (PLLRoot< PLLType > * pred) [inline]
Definition at line 259 of file templates.classic.hh.
References PLLRoot< PLLType >::head(), PLLRoot< PLLType >::pllhead, PLLType< PLLType >::pllnext, PLLRoot< PLLType >::plltail, pred, PLLRoot< PLLType >::set_root(), PLLRoot< PLLType >::tail(), and PLLRoot< PLLType >::update().
Referenced by PLLRoot< PLLType >::insert_after(), PLLRoot< PLLType >::insert_before(), PLLRoot< PLLType >::link_after(), DIL_entry_parameters::project_prepend(), and DIL_entry_parameters::topic_prepend().
259                                                                 { 
260         if (!pred) return false; 
261         if (!pred->tail()) return false; 
262         // *** could call update() here first to insure that pllhead and plltail
263         //     are correct
264         if (pllhead) { 
265                 pllhead->pllprev = pred->tail(); 
266                 pred->tail()->pllnext = pllhead; 
267         } else plltail = pred->head(); 
268         pllhead = pred->head(); 
269         set_root(pred->head()); 
270         pred->update(); 
271         return true; 
272 }
template<class PLLType> bool PLLRoot< PLLType >::link_before (PLLType * succ) [inline]
template<class PLLType> bool PLLRoot< PLLType >::link_before (PLLRoot< PLLType > * succ) [inline]
template<class PLLType> bool PLLRoot< PLLType >::link_before (PLLType * succ) [inline]
template<class PLLType> bool PLLRoot< PLLType >::link_before (PLLRoot< PLLType > * succ) [inline]
template<class PLLType> bool PLLRoot< PLLType >::link_before (PLLType * succ) [inline]
template<class PLLType> bool PLLRoot< PLLType >::link_before (PLLRoot< PLLType > * succ) [inline]
template<class PLLType> bool PLLRoot< PLLType >::link_before (PLLType * succ) [inline]
Definition at line 243 of file templates.classic.hh.
References PLLRoot< PLLType >::link_before(), PLLRoot< PLLType >::pllhead, PLLType< PLLType >::pllprev, PLLRoot< PLLType >::plltail, PLLRoot< PLLType >::set_root(), and succ.
243                                                         { 
244 // when succ->Root()==NULL, this allows previously
245 // unprotected lists or newly created PLLType elements
246 // to be linked
247         if (!succ) return false; 
248         if (succ->Root()) return link_before(succ->Root()); 
249         if (plltail) { 
250                 plltail->pllnext = succ;
251                 succ->pllprev = plltail; 
252         } else pllhead = succ; 
253         plltail = succ; // *** this may need to be succ->seek_tail(), unless lists without root cannot exist
254         set_root(succ); 
255         return true; 
256 } 
template<class PLLType> bool PLLRoot< PLLType >::link_before (PLLRoot< PLLType > * succ) [inline]
Definition at line 227 of file templates.classic.hh.
References PLLRoot< PLLType >::head(), PLLRoot< PLLType >::pllhead, PLLType< PLLType >::pllprev, PLLRoot< PLLType >::plltail, PLLRoot< PLLType >::set_root(), succ, PLLRoot< PLLType >::tail(), and PLLRoot< PLLType >::update().
Referenced by Detailed_Items_List::Get_All_Topical_DIL_Parameters(), PLLRoot< PLLType >::insert_after(), PLLRoot< PLLType >::insert_before(), PLLHandle< PLLType >::isolate(), PLLRoot< PLLType >::link_before(), Financial_Note::link_sorted(), modify_element_through_FORM_interface(), DIL_entry_parameters::project_append(), PLLHandle< PLLType >::remove(), search(), and DIL_entry_parameters::topic_append().
227                                                                  { 
228         if (!succ) return false; 
229         if (!succ->head()) return false; 
230         // *** could call update() here first to insure that pllhead and plltail
231         //     are correct
232         if (plltail) { 
233                 plltail->pllnext = succ->head(); 
234                 succ->head()->pllprev = plltail; 
235         } else pllhead = succ->head(); 
236         plltail = succ->tail(); 
237         set_root(succ->head()); 
238         succ->update(); 
239         return true; 
240 } 
template<class PLLType> PLLType* PLLRoot< PLLType >::operator[] (int n) const [inline]
Definition at line 89 of file templates.unfixed.hh.
89 { return el(n); } 
template<class PLLType> PLLType* PLLRoot< PLLType >::operator[] (int n) const [inline]
Definition at line 116 of file templates.hh.
116 { return el(n); } 
template<class PLLType> PLLType* PLLRoot< PLLType >::operator[] (int n) const [inline]
Definition at line 89 of file templates.clean.hh.
89 { return el(n); } 
template<class PLLType> PLLType* PLLRoot< PLLType >::operator[] (int n) const [inline]
Definition at line 89 of file templates.classic.hh.
89 { return el(n); } 
template<class PLLType> void PLLRoot< PLLType >::set_root (PLLHandle< PLLType > * h) [inline, protected]
template<class PLLType> void PLLRoot< PLLType >::set_root (PLLType * h) [inline, protected]
Definition at line 257 of file templates.hh.
References PLLType< PLLType >::Next().
257                                                   { 
258         for (; (h); h = h->Next()) h->pllroot = this; 
259 } 
template<class PLLType> void PLLRoot< PLLType >::set_root (PLLHandle< PLLType > * h) [inline, protected]
template<class PLLType> void PLLRoot< PLLType >::set_root (PLLHandle< PLLType > * h) [inline, protected]
Definition at line 206 of file templates.classic.hh.
References PLLHandle< PLLType >::Next(), and PLLHandle< PLLType >::pllroot.
Referenced by PLLRoot< PLLType >::link_after(), PLLRoot< PLLType >::link_before(), PLLHandle< PLLType >::unlink_after(), and PLLHandle< PLLType >::unlink_before().
206                                                              { 
207         for (; (h); h = h->Next()) h->pllroot = this; 
208 } 
template<class PLLType> PLLType* PLLRoot< PLLType >::tail () const [inline]
Definition at line 87 of file templates.unfixed.hh.
87 { return static_cast<PLLType *>(plltail); } 
template<class PLLType> PLLType* PLLRoot< PLLType >::tail () const [inline]
Definition at line 114 of file templates.hh.
114 { return plltail; } 
template<class PLLType> PLLType* PLLRoot< PLLType >::tail () const [inline]
Definition at line 87 of file templates.clean.hh.
87 { return static_cast<PLLType *>(plltail); } 
template<class PLLType> PLLType* PLLRoot< PLLType >::tail () const [inline]
Definition at line 87 of file templates.classic.hh.
Referenced by Active_List::AL_Tail(), PLLRoot< PLLType >::link_after(), PLLRoot< PLLType >::link_before(), PLLHandle< DIL_entry_Pointer >::tail(), AL_Day::TC_Tail(), and AL_Day::TD_Tail().
87 { return (PLLType *)const_cast<PLLHandle<PLLType> *>(plltail); } 
template<class PLLType> void PLLRoot< PLLType >::update () [inline]
template<class PLLType> void PLLRoot< PLLType >::update () [inline]
template<class PLLType> void PLLRoot< PLLType >::update () [inline]
template<class PLLType> void PLLRoot< PLLType >::update () [inline]
Definition at line 211 of file templates.classic.hh.
References PLLRoot< PLLType >::pllhead, and PLLRoot< PLLType >::plltail.
Referenced by PLLRoot< PLLType >::link_after(), and PLLRoot< PLLType >::link_before().
211                                      { 
212 // clears head and tail if elements were linked to another root
213 // or fixes head and tail if either one pointed to an element with
214 // a different root
215         if (pllhead) if (pllhead->Root()!=this) pllhead = NULL; 
216         if (plltail) { 
217                 if (plltail->Root()!=this) { 
218                         if (!pllhead) plltail = NULL; 
219                         else plltail = pllhead->seek_tail(); 
220                 } else { 
221                         if (!pllhead) pllhead = plltail->seek_head(); 
222                 } 
223         } 
224 } 
Member Data Documentation
template<class PLLType> PLLHandle<PLLType>* PLLRoot< PLLType >::pllhead [protected]
Definition at line 80 of file templates.unfixed.hh.
template<class PLLType> PLLType* PLLRoot< PLLType >::pllhead [protected]
Definition at line 101 of file templates.hh.
template<class PLLType> PLLHandle<PLLType>* PLLRoot< PLLType >::pllhead [protected]
Definition at line 80 of file templates.clean.hh.
template<class PLLType> PLLHandle<PLLType>* PLLRoot< PLLType >::pllhead [protected]
Definition at line 80 of file templates.classic.hh.
Referenced by PLLHandle< PLLType >::isolate(), PLLRoot< PLLType >::link_after(), PLLRoot< PLLType >::link_before(), PLLHandle< PLLType >::unlink_after(), PLLHandle< PLLType >::unlink_before(), and PLLRoot< PLLType >::update().
template<class PLLType> PLLHandle<PLLType>* PLLRoot< PLLType >::plltail [protected]
Definition at line 81 of file templates.unfixed.hh.
template<class PLLType> PLLType* PLLRoot< PLLType >::plltail [protected]
Definition at line 102 of file templates.hh.
template<class PLLType> PLLHandle<PLLType>* PLLRoot< PLLType >::plltail [protected]
Definition at line 81 of file templates.clean.hh.
template<class PLLType> PLLHandle<PLLType>* PLLRoot< PLLType >::plltail [protected]
Definition at line 81 of file templates.classic.hh.
Referenced by PLLHandle< PLLType >::isolate(), PLLRoot< PLLType >::link_after(), PLLRoot< PLLType >::link_before(), PLLHandle< PLLType >::unlink_after(), PLLHandle< PLLType >::unlink_before(), and PLLRoot< PLLType >::update().
The documentation for this class was generated from the following files:
templates.classic.hh
templates.clean.hh
templates.hh
templates.unfixed.hh