DIL_Visualize_with_Tabs Class Reference
#include <dil2al.hh>
Public Methods
DIL_Visualize_with_Tabs (DIL_Hierarchy_Level_Data *ld=NULL)
virtual void Initialize ()
virtual void Visualize_Element (DIL_entry *de, int depth)
virtual void Visualize_NotShown (int numdependencies, int depth)
virtual String Output ()
virtual String Output_Content ()
Protected Attributes
String s
String content
Constructor & Destructor Documentation
DIL_Visualize_with_Tabs::DIL_Visualize_with_Tabs (DIL_Hierarchy_Level_Data * ld = NULL) [inline]
Definition at line 766 of file dil2al.hh.
766 : DIL_Visualize(ld) {}
Member Function Documentation
virtual void DIL_Visualize_with_Tabs::Initialize () [inline, virtual]
Reimplemented from DIL_Visualize (p.).
Definition at line 767 of file dil2al.hh.
767 { s = ""; content = ""; }
virtual String DIL_Visualize_with_Tabs::Output () [inline, virtual]
Reimplemented from DIL_Visualize (p.).
Definition at line 770 of file dil2al.hh.
Referenced by Tabbed_DIL_Hierarchy().
770 { return s; }
virtual String DIL_Visualize_with_Tabs::Output_Content () [inline, virtual]
Definition at line 771 of file dil2al.hh.
Referenced by Tabbed_DIL_Hierarchy().
771 { return content; }
void DIL_Visualize_with_Tabs::Visualize_Element (DIL_entry * de, int depth) [virtual]
Reimplemented from DIL_Visualize (p.).
Definition at line 102 of file diladmin.cc.
References DIL_ID::chars(), content, DIL_entry::Entry_Text(), HTML_remove_tags(), replicate(), and s.
102                                                                          {
103         if (depth>0) s += replicate('\t',depth);
104         s += "DIL#" + String(de->chars()) + '\n';
105         content += "\nDIL#" + String(de->chars()) + ":\n";
106         String * ctxt = de->Entry_Text();
107         if (ctxt) {
108                 String ptxtcontent(*ctxt);
109                 content += (*HTML_remove_tags(ptxtcontent));
110         }
111         content += '\n';
112 }
void DIL_Visualize_with_Tabs::Visualize_NotShown (int numdependencies, int depth) [virtual]
Reimplemented from DIL_Visualize (p.).
Definition at line 114 of file diladmin.cc.
References replicate(), and s.
114                                                                                {
115   if (numdependencies>0) {
116     if (depth>0) s += replicate('\t',depth);
117     s += '['+String((long) numdependencies)+" dependencies...]\n";
118   }
119 }
Member Data Documentation
String DIL_Visualize_with_Tabs::content [protected]
Definition at line 764 of file dil2al.hh.
Referenced by Visualize_Element().
String DIL_Visualize_with_Tabs::s [protected]
Definition at line 763 of file dil2al.hh.
Referenced by Visualize_Element(), and Visualize_NotShown().
The documentation for this class was generated from the following files:
dil2al.hh
diladmin.cc