Search_Result Class Reference
#include <dil2al.hh>
Public Types
enum Search_Result_types { SR_REGULAR,
SR_DIRECTORY_ENTRY,
SR_URL
 }
Public Methods
Search_Result (const char *s, const Target_Access &t, String &text, const BigRegex &skrx)
Search_Result_types Type ()
int isequal (const Search_Result &sr) const
int operator== (const Search_Result &sr) const
int operator!= (const Search_Result &sr) const
String HTML_put_text () const
operator const char * () const
Protected Attributes
String searchkey
Target_Access target
String pretext
String keytext
String posttext
long location
Search_Result_types type
Member Enumeration Documentation
enum Search_Result::Search_Result_types
Enumeration values:
SR_REGULAR
SR_DIRECTORY_ENTRY
SR_URL
Definition at line 1052 of file dil2al.hh.
Referenced by Type().
1052 { SR_REGULAR, SR_DIRECTORY_ENTRY, SR_URL };
Constructor & Destructor Documentation
Search_Result::Search_Result (const char * s, const Target_Access & t, String & text, const BigRegex & skrx)
Definition at line 343 of file search.cc.
References String::at(), String::before(), String::contains(), String::from(), String::index(), keytext, String::length(), posttext, String::prepend(), pretext, String::SEARCH_END, SR_DIRECTORY_ENTRY, SR_REGULAR, String::sub(), Target_Access::TA_LOCAL_DIRECTORY, type, and Target_Access::Type().
343                                                                                                          : searchkey(s), target(t), location(skrx.subpos()) {
344         // Obtains the matched keytext and some pretext and posttext
345         const int PTEXTSIZE = 160;
346         keytext = text.sub(skrx,0);
347         if (t.Type()!=Target_Access::TA_LOCAL_DIRECTORY) { // get pretext and posttext
348                 // *** DETECT HERE IF SR_URL!
349                 type = SR_REGULAR;
350                 if (skrx.subpos()>PTEXTSIZE) pretext = text.at(skrx.subpos()-PTEXTSIZE,PTEXTSIZE); else pretext = text.before(skrx.subpos());
351                 int skrxend = skrx.subpos()+skrx.sublen();
352                 if ((skrxend+PTEXTSIZE)<text.length()) posttext = text.at(skrxend,PTEXTSIZE); else posttext = text.from(skrxend);
353         } else { // get complete directory entry reference
354                 type = SR_DIRECTORY_ENTRY;
355                 int entrystart = text.index("<A HREF=",(int) (skrx.subpos()-text.length()));
356                 if (entrystart>=0) {
357                         int entryend = text.index("</A>",skrx.subpos());
358                         if (entryend>=0) {
359                                 int urlend = text.index("\">",String::SEARCH_END,entrystart);
360                                 if (urlend>=0) {
361                                         pretext = text.at(entrystart,urlend-entrystart); // get URL
362                                         // split reference text into pre, key and post parts
363                                         posttext = text.at(urlend,entryend-urlend);
364                                         if (posttext.contains(skrx)) {
365                                                 pretext += posttext.before(skrx.subpos());
366                                                 keytext = posttext.sub(skrx,0);
367                                                 posttext = posttext.from(skrx.subpos()+skrx.sublen());
368                                         } else { // should never occur in a SR_DIRECTORY_ENTRY, just for extra safety
369                                                 pretext += '[';
370                                                 posttext.prepend("] ");
371                                         }
372                                         posttext += "</A>";
373                                 }
374                         }
375                 }
376         }
377 }
Member Function Documentation
String Search_Result::HTML_put_text () const
Definition at line 391 of file search.cc.
References HTML_safe(), keytext, location, posttext, pretext, res, SR_DIRECTORY_ENTRY, SR_REGULAR, SR_URL, Target_Access::Target(), and target.
Referenced by operator const char *().
391                                           {
392         // Produce HTML output for search result
393         static String res;
394         String pre, post, key;
395         // *** IMPROVE:
396         // - identify any links in the pretext+keytext+posttext and turn them into correct relative links
397         // - beware of searchkey found in the middle of an HREF URL
398         switch (type) {
399                 case SR_REGULAR: // *** this one will be modified with the improvements mentioned above
400                         pre = pretext; key = keytext; post = posttext;
401                         res = "<A HREF=\""+target.Target()+"\">"+target.Target()+"</A> ["+String(location)+"]: "+(*HTML_safe(pre))+"<FONT COLOR=\"#FF0000\"><B>"+(*HTML_safe(key))+"</B></FONT>"+(*HTML_safe(post))+"\n<P>\n\n";
402                         break;
403                 case SR_DIRECTORY_ENTRY:
404                         res = "<A HREF=\""+target.Target()+"\">"+target.Target()+"</A>: "+pretext+"<FONT COLOR=\"#FF0000\"><B>"+keytext+"</B></FONT>"+posttext+"\n<P>\n\n";
405                         break;
406                 case SR_URL: // *** implement this correctly!
407                         res = "<A HREF=\""+target.Target()+"\">"+target.Target()+"</A> ["+String(location)+"]: "+pretext+"<FONT COLOR=\"#FF0000\"><B>"+keytext+"</B></FONT>"+posttext+"\n<P>\n\n";
408                         break;
409         }
410         return res;
411 }
int Search_Result::isequal (const Search_Result & sr) const
Definition at line 379 of file search.cc.
References keytext, posttext, pretext, searchkey, target, and type.
Referenced by operator!=(), and operator==().
379                                                          {
380         // Equality comparison operator
381         // Note: This could also have been defined as a function that takes two arguments
382         if (searchkey!=sr.searchkey) return 0;
383         if (target!=sr.target) return 0;
384         if (pretext!=sr.pretext) return 0;
385         if (keytext!=sr.keytext) return 0;
386         if (posttext!=sr.posttext) return 0;
387         if (type!=sr.type) return 0;
388         return 1;
389 }
Search_Result::operator const char * () const [inline]
Definition at line 1069 of file dil2al.hh.
References HTML_put_text().
1069 { return (const char *) HTML_put_text(); }
int Search_Result::operator!= (const Search_Result & sr) const [inline]
Definition at line 1067 of file dil2al.hh.
References isequal().
1067 { return (!isequal(sr)); }
int Search_Result::operator== (const Search_Result & sr) const [inline]
Definition at line 1066 of file dil2al.hh.
References isequal().
1066 { return isequal(sr); }
Search_Result_types Search_Result::Type () [inline]
Definition at line 1064 of file dil2al.hh.
References Search_Result_types, and type.
Referenced by Search_Target::search().
1064 { return type; }
Member Data Documentation
String Search_Result::keytext [protected]
Definition at line 1057 of file dil2al.hh.
Referenced by HTML_put_text(), isequal(), and Search_Result().
long Search_Result::location [protected]
Definition at line 1058 of file dil2al.hh.
Referenced by HTML_put_text().
String Search_Result::posttext [protected]
Definition at line 1057 of file dil2al.hh.
Referenced by HTML_put_text(), isequal(), and Search_Result().
String Search_Result::pretext [protected]
Definition at line 1057 of file dil2al.hh.
Referenced by HTML_put_text(), isequal(), and Search_Result().
String Search_Result::searchkey [protected]
Definition at line 1055 of file dil2al.hh.
Referenced by isequal().
Target_Access Search_Result::target [protected]
Definition at line 1056 of file dil2al.hh.
Referenced by HTML_put_text(), and isequal().
Search_Result_types Search_Result::type [protected]
Definition at line 1059 of file dil2al.hh.
Referenced by isequal(), Search_Result(), and Type().
The documentation for this class was generated from the following files:
dil2al.hh
search.cc