LongList Class Reference
#include <dil2al.hh>
Public Methods
~LongList ()
LongList ()
LongList (unsigned long n)
LongList (const long cs, LongList *cn=NULL)
LongList (String cs, const char sep)
long & operator[] (unsigned long n)
LongList * get_Next ()
void append (unsigned long n, long &ins)
void insert (unsigned long n, long &ins)
unsigned long length ()
long iselement (long el, unsigned long n=0)
long contains (long substr, unsigned long n=0)
unsigned long split (unsigned long n, String cs, const char sep='\n')
String concatenate (String sepstr=``)
Protected Attributes
LongList * Next
long s
Constructor & Destructor Documentation
LongList::~LongList () [inline]
Definition at line 135 of file dil2al.hh.
135 { if (Next) delete Next; }
LongList::LongList () [inline]
Definition at line 136 of file dil2al.hh.
References LONGLIST_INITIAL_VALUE, and s.
Referenced by append(), insert(), LongList(), and operator[]().
136 { Next=NULL; s = LONGLIST_INITIAL_VALUE; }
LongList::LongList (unsigned long n) [inline]
Definition at line 137 of file dil2al.hh.
References LongList(), LONGLIST_INITIAL_VALUE, and s.
137 { s = LONGLIST_INITIAL_VALUE; if (n) Next = new LongList(n-1); else Next = NULL; }
LongList::LongList (const long cs, LongList * cn = NULL) [inline]
Definition at line 138 of file dil2al.hh.
References s.
138 { s=cs; Next=cn; }
LongList::LongList (String cs, const char sep)
Definition at line 115 of file utilities.cc.
References Next, and split().
115                                             {
116 // initialize list from a string with a specified separator
117 // (Note: In the current implementation this leaves an unused
118 // list element at the end of the list.)
119         Next=NULL;
120         split(0,cs,sep);
121 }
Member Function Documentation
void LongList::append (unsigned long n, long & ins)
Definition at line 129 of file utilities.cc.
References LongList(), and Next.
129                                                  {
130         if (!n) Next = new LongList(ins,Next);
131         else
132                 if (Next) Next->append(n-1,ins);
133                 else {
134                         Next = new LongList();
135                         Next->append(n-1,ins);
136                 }
137 }
String LongList::concatenate (String sepstr = ``)
Definition at line 174 of file utilities.cc.
References Next, and s.
174                                                {
175         if (Next) return String(s)+sepstr+Next->concatenate(sepstr);
176         else return String(s);
177 }
long LongList::contains (long substr, unsigned long n = 0)
Definition at line 158 of file utilities.cc.
References iselement().
158                                                         {
159         return iselement(substr,n);
160 }
LongList* LongList::get_Next () [inline]
Definition at line 141 of file dil2al.hh.
141 { return Next; }
void LongList::insert (unsigned long n, long & ins)
Definition at line 139 of file utilities.cc.
References LongList(), Next, and s.
Referenced by split().
139                                                  {
140         if (!n) { Next = new LongList(s,Next); s = ins; }
141         else
142                 if (Next) Next->insert(n-1,ins);
143                 else 
144                         if (n>1) {
145                                 Next = new LongList();
146                                 Next->insert(n-1,ins);
147                         } else Next = new LongList(ins);
148 }
long LongList::iselement (long el, unsigned long n = 0)
Definition at line 150 of file utilities.cc.
References Next, and s.
Referenced by contains().
150                                                      {
151         if (el == s) return n;
152         else {
153                 if (Next) return Next->iselement(el,n+1);
154                 else return -1;
155         }
156 }
unsigned long LongList::length () [inline]
Definition at line 147 of file dil2al.hh.
Referenced by split().
147 { if (Next) return 1+Next->length(); else return 1; }
long & LongList::operator[] (unsigned long n)
Definition at line 123 of file utilities.cc.
References LongList(), Next, and s.
123                                            {
124         if (!n) return s;
125         if (!Next) Next = new LongList();
126         return (*Next)[n-1];
127 }
unsigned long LongList::split (unsigned long n, String cs, const char sep = '\n')
Definition at line 162 of file utilities.cc.
References String::after(), String::before(), String::chars(), String::index(), insert(), length(), and String::length().
Referenced by LongList().
162                                                                                {
163 // insert list elements from a string with a specified separator
164         if (cs.length()<=0) return length();
165         String el;
166         if (cs.index(sep)>=0) el = cs.before(sep); else el = cs;
167         // *** this is not a speed optimized implementation
168         long elval = atol(el.chars());
169         insert(n,elval);
170         split(n+1,cs.after(sep),sep);
171         return length();
172 }
Member Data Documentation
LongList* LongList::Next [protected]
Definition at line 132 of file dil2al.hh.
Referenced by append(), concatenate(), insert(), iselement(), LongList(), and operator[]().
long LongList::s [protected]
Definition at line 133 of file dil2al.hh.
Referenced by concatenate(), insert(), iselement(), LongList(), and operator[]().
The documentation for this class was generated from the following files:
dil2al.hh
utilities.cc