BigRegex Class Reference
#include <BigRegex.hh>
Public Methods
BigRegex (const char *t, int fast=0, int bufsize=40, const char *transtable=0)
~BigRegex ()
int match (const char *s, int len, int pos=0) const
int search (const char *s, int len, int &matchlen, int startpos=0) const
int match_info (int &start, int &length, int nth=0) const
int subpos (int nth=0) const
int sublen (int nth=0) const
int OK () const
Protected Attributes
regex_t * re
regmatch_t * rm
bool * re_assigned
Constructor & Destructor Documentation
BigRegex::BigRegex (const char * t, int fast = 0, int bufsize = 40, const char * transtable = 0)
Definition at line 61 of file BigRegex.cc.
References BIGREGEX_MAX_SUBEXPRESSIONS, re, re_assigned, res, and rm.
61                                                                                {
62         re_assigned = new bool;
63         if (t==0) *re_assigned = false; // zero-length RE
64         else {
65                 re = new regex_t;
66 //*** NOTE: bufsize doesn't really work yet, since it
67 //*** is not remembered anywhere and up to
68 //*** BIGREGEX_MAX_SUBEXPRESSIONS are filled in searches below
69                  if (bufsize>BIGREGEX_MAX_SUBEXPRESSIONS) bufsize = BIGREGEX_MAX_SUBEXPRESSIONS;
70                 rm = new regmatch_t[bufsize];
71                 int res;
72 #ifdef __DIL2AL__
73                 // revert to Basic RE backslashing style as inherited from Regex
74                 // this reverses backslashed and non-backslashed meanings for: (){}|
75                 char * ttmp;
76                 int tlen = 0; while (t[tlen]) tlen++;
77                 ttmp = new char[(2*tlen)+1]; // allocate a character buffer twice as large in case everything has to be escaped with `\'
78                 int ttmplen = 0; int ii;
79                 for (int i=0; i<=tlen; i++) {
80                         ii = i+1;
81                         if ((t[i]=='\\') && ((t[ii]=='\\') || (t[ii]=='(') || (t[ii]==')') || (t[ii]=='{') || (t[ii]=='}') || (t[ii]=='|'))) {
82                                 if (t[ii]=='\\') { // retain escaped backslash
83                                         ttmp[ttmplen] = '\\';
84                                         ttmplen++;
85                                 }
86                                 i++; // skip backslash
87                         } else if ((t[i]=='(') || (t[i]==')') || (t[i]=='{') || (t[i]=='}') || (t[i]=='|')) {
88                                 ttmp[ttmplen] = '\\'; // add backslash
89                                 ttmplen++;
90                         }
91                         ttmp[ttmplen] = t[i]; // copy character (possibly after skipping or adding a backslash)
92                         ttmplen++;
93                 }
94                 ttmplen--; // don't count '\0'
95                 res = regcomp(re,ttmp,REG_EXTENDED);
96                 delete[] ttmp;
97 #else
98                 res = regcomp(re,t,REG_EXTENDED);
99 #endif
100                 if (!res) *re_assigned = true;
101                 else {
102                         *re_assigned = false;
103 #ifdef _BIGREGEX_HAVE_ERROR_HANDLER
104                         char errbuf[256];
105                         if (regerror(res,re,errbuf,256)>0) (*lib_error_handler)("BigRegex",errbuf);
106 #endif                  
107                 }
108         }
109 }
BigRegex::~BigRegex ()
Definition at line 54 of file BigRegex.cc.
References re, re_assigned, and rm.
54                     {
55         if (re_assigned) if (*re_assigned) regfree(re);
56         delete re;
57         delete[] rm;
58         delete re_assigned;
59 }
Member Function Documentation
int BigRegex::match (const char * s, int len, int pos = 0) const
Definition at line 295 of file BigRegex.cc.
References BIGREGEX_MAX_SUBEXPRESSIONS, re, res, and rm.
Referenced by String::contains(), SubString::matches(), and String::matches().
295                                                       {
296         // negative p is considered an offset from len backwards,
297         // but note that the match is still scanned forward
298         if (p < 0) {
299                 len += p + 1; // point len at len - abs(p) + 1
300                 if (len <= 0) return -1;
301                 p = 0;
302         } else if (p > len) return -1;
303         // match re to (char*) s, from position p to position len
304         // store subexpression information
305         // return the number of characters matched
306         int res;
307 #ifndef _BIGREGEX_SAFE_MATCHES
308         if (s[len]=='\0') res = regexec(re,&s[p],(size_t) BIGREGEX_MAX_SUBEXPRESSIONS,(regmatch_t *) rm,0);
309         else {
310 #endif
311                 char * stmp; // copy up to len characters
312                 stmp = new char[len+1];
313                 int i;
314 #ifdef _BIGREGEX_SAFE_MATCHES
315                 for (i=0; ((i<len) && (s[i]!='\0')); i++) stmp[i]=s[i];
316 #else
317                 for (i=0; i<len; i++) stmp[i]=s[i];
318 #endif
319                 stmp[i]='\0';
320                 res = regexec(re,&stmp[p],(size_t) BIGREGEX_MAX_SUBEXPRESSIONS,(regmatch_t *) rm,0);
321                 delete[] stmp;
322 #ifndef _BIGREGEX_SAFE_MATCHES
323         }
324 #endif
325         if (res==0) {
326                 if (p>0) { // adjust rm to the offset p
327                         for(i=0; ((i<BIGREGEX_MAX_SUBEXPRESSIONS) && (rm[i].rm_so>-1)); i++) {
328                                 rm[i].rm_so += p;
329                                 rm[i].rm_eo += p;
330                         }
331                 }
332 #if defined(_BIGREGEX_SAFE_MATCHES) && defined(_BIGREGEX_HAS_RM_SPEP)
333                 // change rm pointers back to original string
334                 for(i=0; ((i<BIGREGEX_MAX_SUBEXPRESSIONS) && (rm[i].rm_so>-1)); i++) {
335                         rm[i].rm_sp = s + rm[i].rm_so;
336                         rm[i].rm_ep = s + rm[i].rm_eo;
337                 }
338 #endif
339                 return rm[0].rm_eo - rm[0].rm_so; // number of characters matched
340         } else {
341                 if (res==REG_NOMATCH) return 0;
342                 else return -2; // internal error
343         }
344 }
int BigRegex::match_info (int & start, int & length, int nth = 0) const
Definition at line 111 of file BigRegex.cc.
References BIGREGEX_MAX_SUBEXPRESSIONS, and rm.
Referenced by String::_gsub(), D2A_get_tag(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), HTML_get_href(), HTML_get_marker(), HTML_get_name(), select_TL_DIL_refs(), and String::sub().
111                                                                {
112         if ((unsigned)(nth) >= BIGREGEX_MAX_SUBEXPRESSIONS) return 0;
113         start = rm[nth].rm_so;
114         length = rm[nth].rm_eo - start;
115         return start >= 0 && length >= 0;
116 }
int BigRegex::OK () const
Definition at line 346 of file BigRegex.cc.
References re_assigned.
346                        {
347 #ifdef _BIGREGEX_HAVE_ERROR_HANDLER
348         if (re_assigned) if (!(*re_assigned)) (*lib_error_handler)("BigRegex", "invariant failure");
349 #endif
350         if (re_assigned) return *re_assigned;
351         else return 0;
352 }
int BigRegex::search (const char * s, int len, int & matchlen, int startpos = 0) const
Definition at line 190 of file BigRegex.cc.
References BIGREGEX_MAX_SUBEXPRESSIONS, DEBUG_OUT, re, re_registers, res, rm, TALLOC, and TFREE.
Referenced by String::_gsub(), String::after(), String::at(), String::before(), SubString::contains(), String::contains(), String::del(), String::from(), String::index(), select_TL_DIL_refs(), split(), and String::through().
190                                                                               {
191 // Returns -1 if no match, otherwise index of match
192 // Negative startpos means scan from end (very slow with regular POSIX.2 regex)
193         int res = -1;
194         char * stmp;
195         bool copied = true;
196         int p = startpos;
197         if (startpos<0) {
198 DEBUG_OUT('~')
199                 len += p + 1;   // start searching at len-abs(startpos)
200                 if (len <= 0) return -1;
201                 p = 0;
202         }
203 #ifndef _BIGREGEX_SAFE_MATCHES
204         if (s[len]=='\0') { // assumes no '\0' prior to s[len]
205                 copied = false;
206                 stmp = s;
207         } else
208 #endif
209         stmp = new char[len+1];
210         int i;
211 #ifdef _BIGREGEX_SAFE_MATCHES
212         for (i=0; ((i<len) && (s[i]!='\0')); i++) stmp[i]=s[i];
213 #else
214         for (i=0; i<len; i++) stmp[i]=s[i];
215 #endif
216         stmp[i]='\0';
217         if (startpos>=0) { // search forward
218                 res = regexec(re,&stmp[p],(size_t) BIGREGEX_MAX_SUBEXPRESSIONS,(regmatch_t *) rm,0);
219         } else { // search backward
220 #ifdef _BIGREGEX_PARANOID_POSIX
221                 int tmpp = p, tmpres = 0;
222                 regmatch_t * tmprm = new regmatch_t[BIGREGEX_MAX_SUBEXPRESSIONS];
223                 res = REG_NOMATCH;
224                 while ((tmpp<len) && (tmpres==0)) {
225                         tmpres = regexec(re,&stmp[tmpp],(size_t) BIGREGEX_MAX_SUBEXPRESSIONS,(regmatch_t *) tmprm,0);
226                         if (tmpres!=REG_NOMATCH) { // furthest match found so far
227                                 res = tmpres;
228                                 p = tmpp;
229                                 for (i=0; i<BIGREGEX_MAX_SUBEXPRESSIONS; i++) {
230                                         rm[i].rm_so = tmprm[i].rm_so;
231                                         rm[i].rm_eo = tmprm[i].rm_eo;
232 #if defined(_BIGREGEX_SAFE_MATCHES) && defined(_BIGREGEX_HAS_RM_SPEP)
233                                         rm[i].rm_sp = tmprm[i].rm_sp;
234                                         rm[i].rm_ep = tmprm[i].rm_ep;
235 #endif
236                                 }
237                                 tmpp=tmprm[0].rm_so+1;  // try next just after current match index
238                         }
239                 }
240                 delete[] tmprm;
241 #else
242 DEBUG_OUT('-')
243                 regex_t private_preg;
244                 struct re_registers regs;
245                 private_preg = *re;
246                 private_preg.not_bol = !!(0 & REG_NOTBOL);
247                 private_preg.not_eol = !!(0 & REG_NOTEOL);
248                 private_preg.regs_allocated = REGS_FIXED;
249                 regs.num_regs = BIGREGEX_MAX_SUBEXPRESSIONS;
250                 regs.start = TALLOC (BIGREGEX_MAX_SUBEXPRESSIONS, regoff_t);
251                 regs.end = TALLOC (BIGREGEX_MAX_SUBEXPRESSIONS, regoff_t);
252                 if (regs.start == NULL || regs.end == NULL) return (int) REG_NOMATCH;
253                 res = re_search (&private_preg, stmp, len, len-1, -(len-1), &regs);
254              if (res >= 0) {
255 DEBUG_OUT('!')
256                         for (unsigned r = 0; r < BIGREGEX_MAX_SUBEXPRESSIONS; r++) {
257                                 rm[r].rm_so = regs.start[r];
258                                 rm[r].rm_eo = regs.end[r];
259                         }
260                         res = 0;
261                 } else res = REG_NOMATCH;
262                 TFREE (regs.start);
263                 TFREE (regs.end);
264 #endif
265         }
266 #ifndef _BIGREGEX_SAFE_MATCHES
267         if (copied)
268 #endif
269         delete[] stmp;
270         if (res==0) {
271                 if (p>0) { // adjust rm to the offset p
272                         for(i=0; ((i<BIGREGEX_MAX_SUBEXPRESSIONS) && (rm[i].rm_so>-1)); i++) {
273                                 rm[i].rm_so += p;
274                                 rm[i].rm_eo += p;
275                         }
276                 }
277 #if defined(_BIGREGEX_SAFE_MATCHES) && defined(_BIGREGEX_HAS_RM_SPEP)
278                 // change rm pointers back to original string
279                 for(i=0; ((i<BIGREGEX_MAX_SUBEXPRESSIONS) && (rm[i].rm_so>-1)); i++) {
280                         rm[i].rm_sp = s + rm[i].rm_so;
281                         rm[i].rm_ep = s + rm[i].rm_eo;
282                 }
283 #endif
284                 matchlen = rm[0].rm_eo - rm[0].rm_so;
285                 return rm[0].rm_so; // start of match
286         } else {
287                 matchlen = 0;
288                 if (res==REG_NOMATCH) return -1;
289                 else return -2; // internal error
290         }
291 }
int BigRegex::sublen (int nth = 0) const
Definition at line 123 of file BigRegex.cc.
References BIGREGEX_MAX_SUBEXPRESSIONS, and rm.
Referenced by extract_DIL_IDs_from_form(), extract_paper_novelties(), Financial_Note::get(), get_figure_data(), modify_DIL_group_target_dates_cmd(), remove_AL_TC(), select_TL_DIL_refs(), send_dil_to_DIL(), TeX_format_corrections(), TeX_get_command(), and TeX_safe_text().
123                                   {
124         if ((unsigned)(nth) >= BIGREGEX_MAX_SUBEXPRESSIONS) return -1;
125         return rm[nth].rm_eo - rm[nth].rm_so;
126 }
int BigRegex::subpos (int nth = 0) const
Definition at line 118 of file BigRegex.cc.
References BIGREGEX_MAX_SUBEXPRESSIONS, and rm.
Referenced by extract_DIL_IDs_from_form(), extract_paper_novelties(), Financial_Note::get(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), get_figure_data(), Get_Target_Regex(), modify_DIL_group_target_dates_cmd(), remove_AL_TC(), select_TL_DIL_refs(), send_dil_to_DIL(), TeX_format_corrections(), TeX_get_command(), and Target_Access::transformed_name().
118                                   {
119         if ((unsigned)(nth) >= BIGREGEX_MAX_SUBEXPRESSIONS) return -1;
120         return rm[nth].rm_so;
121 }
Member Data Documentation
regex_t* BigRegex::re [protected]
Definition at line 86 of file BigRegex.hh.
Referenced by BigRegex(), match(), search(), and ~BigRegex().
bool* BigRegex::re_assigned [protected]
Definition at line 88 of file BigRegex.hh.
Referenced by BigRegex(), OK(), and ~BigRegex().
regmatch_t* BigRegex::rm [protected]
Definition at line 87 of file BigRegex.hh.
Referenced by BigRegex(), match(), match_info(), search(), sublen(), subpos(), and ~BigRegex().
The documentation for this class was generated from the following files:
BigRegex.hh
BigRegex.cc