StringList Class Reference
#include <dil2al.hh>
Public Methods
~StringList ()
StringList ()
StringList (unsigned long n)
StringList (const String cs, StringList *cn=NULL)
StringList (String cs, const char sep)
String & operator[] (unsigned long n)
StringList * get_Next ()
StringList * List_Index (long n)
void append (unsigned long n, String &ins)
void insert (unsigned long n, String &ins)
unsigned long length ()
long iselement (String el, unsigned long n=0)
long contains (String substr, unsigned long n=0)
long first_contained_in (String &sourcestr, unsigned long n=0)
unsigned long split (unsigned long n, String cs, const char sep='\n')
String concatenate (String sepstr=``)
Protected Attributes
StringList * Next
String s
Constructor & Destructor Documentation
StringList::~StringList () [inline]
Definition at line 100 of file dil2al.hh.
100 { if (Next) delete Next; }
StringList::StringList () [inline]
Definition at line 101 of file dil2al.hh.
Referenced by append(), insert(), operator[](), and StringList().
101 { Next=NULL; }
StringList::StringList (unsigned long n) [inline]
Definition at line 102 of file dil2al.hh.
References StringList().
102 { if (n) Next = new StringList(n-1); else Next = NULL; }
StringList::StringList (const String cs, StringList * cn = NULL) [inline]
Definition at line 103 of file dil2al.hh.
103 { s=cs; Next=cn; }
StringList::StringList (String cs, const char sep)
Definition at line 29 of file utilities.cc.
References Next, and split().
29                                                 {
30 // initialize list from a string with a specified separator
31 // (Note: In the current implementation this leaves an unused
32 // list element at the end of the list.
33 // Beware! If you fix this to leave no unused list element at
34 // the end of the list you must check all source code where
35 // this initialization function is used to insure that the
36 // code is modified so as not to depend on this "feature"!)
37         Next=NULL;
38         split(0,cs,sep);
39 }
Member Function Documentation
void StringList::append (unsigned long n, String & ins)
Definition at line 54 of file utilities.cc.
References Next, and StringList().
54                                                      {
55         if (!n) Next = new StringList(ins,Next);
56         else
57                 if (Next) Next->append(n-1,ins);
58                 else {
59                         Next = new StringList();
60                         Next->append(n-1,ins);
61                 }
62 }
String StringList::concatenate (String sepstr = ``)
Definition at line 110 of file utilities.cc.
References Next, and s.
Referenced by extract_DIL_IDs_from_form(), extract_hierarchy_depth_increase_to_paper(), extract_recursively(), and extract_required_item_to_paper().
110                                                  {
111         if (Next) return s+sepstr+Next->concatenate(sepstr);
112         else return s;
113 }
long StringList::contains (String substr, unsigned long n = 0)
Definition at line 83 of file utilities.cc.
References String::contains(), Next, and s.
Referenced by Detect_Form_Input(), modify_element_through_FORM_interface(), modify_element_through_FORM_interface_DIL_Superiors(), search_cmd(), and select_TL_DIL_refs().
83                                                             {
84         if (s.contains(substr)) return n;
85         else {
86                 if (Next) return Next->contains(substr,n+1);
87                 else return -1;
88         }
89 }
long StringList::first_contained_in (String & sourcestr, unsigned long n = 0)
Definition at line 91 of file utilities.cc.
References String::contains(), Next, and s.
Referenced by Tabbed_FORM_DIL_Hierarchy_full().
91                                                                            {
92   if (sourcestr.contains(s)) return n;
93   else {
94     if (Next) return Next->first_contained_in(sourcestr,n+1);
95     else return -1;
96   }
97 }
StringList* StringList::get_Next () [inline]
Definition at line 106 of file dil2al.hh.
Referenced by get_new_DIL_ID(), and modify_element_through_FORM_interface().
106 { return Next; }
void StringList::insert (unsigned long n, String & ins)
Definition at line 64 of file utilities.cc.
References Next, s, and StringList().
Referenced by add_new_to_DIL(), and split().
64                                                      {
65         if (!n) { Next = new StringList(s,Next); s = ins; }
66         else
67                 if (Next) Next->insert(n-1,ins);
68                 else 
69                         if (n>1) {
70                                 Next = new StringList();
71                                 Next->insert(n-1,ins);
72                         } else Next = new StringList(ins);
73 }
long StringList::iselement (String el, unsigned long n = 0)
Definition at line 75 of file utilities.cc.
References Next, and s.
Referenced by extract_hierarchy_depth_increase_to_paper(), extract_paper_plan_to_paper(), Novelty_Marker_List::Get_Context_Ranks(), and get_file_in_list().
75                                                          {
76         if (el == s) return n;
77         else {
78                 if (Next) return Next->iselement(el,n+1);
79                 else return -1;
80         }
81 }
unsigned long StringList::length () [inline]
Definition at line 113 of file dil2al.hh.
Referenced by Detect_Form_Input(), extract_paper_plan_to_paper(), generate_modify_element_FORM_interface_DIL_entry_parameters(), Novelty_Marker::Get_Novelty_from_Paper_Plan(), Get_Target_Directory(), Get_Target_Regex(), modify_DIL_group_target_dates_cmd(), modify_element_through_FORM_interface(), search(), split(), superior_reference_info(), Tabbed_FORM_DIL_Hierarchy(), and Tabbed_FORM_DIL_Hierarchy_full().
113 { if (Next) return 1+Next->length(); else return 1; }
StringList * StringList::List_Index (long n)
Definition at line 47 of file utilities.cc.
References Next.
Referenced by modify_element_through_FORM_interface().
47                                           {
48   if (n<0) return NULL;
49   if (!n) return this;
50   if (!Next) return NULL;
51   return Next->List_Index(n-1);
52 }
String & StringList::operator[] (unsigned long n)
Definition at line 41 of file utilities.cc.
References Next, s, and StringList().
41                                                {
42         if (!n) return s;
43         if (!Next) Next = new StringList();
44         return (*Next)[n-1];
45 }
unsigned long StringList::split (unsigned long n, String cs, const char sep = '\n')
Definition at line 99 of file utilities.cc.
References String::after(), String::before(), String::index(), insert(), length(), and String::length().
Referenced by StringList().
99                                                                                  {
100 // insert list elements from a string with a specified separator
101         if (cs.length()<=0) return length();
102         String el;
103         if (cs.index(sep)>=0) el = cs.before(sep); else el = cs;
104         // *** this is not a speed optimized implementation
105         insert(n,el);
106         split(n+1,cs.after(sep),sep);
107         return length();
108 }
Member Data Documentation
StringList* StringList::Next [protected]
Definition at line 97 of file dil2al.hh.
Referenced by append(), concatenate(), contains(), first_contained_in(), insert(), iselement(), List_Index(), operator[](), and StringList().
String StringList::s [protected]
Definition at line 98 of file dil2al.hh.
Referenced by concatenate(), contains(), first_contained_in(), insert(), iselement(), and operator[]().
The documentation for this class was generated from the following files:
dil2al.hh
utilities.cc