Financial_Monthly Class Reference
#include <dil2al.hh>
Public Methods
Financial_Monthly (String m)
String Month () const
Financial_Monthly * Find_Month (String m) const
void Copy_Categories (Financial_Monthly *h)
void add (const Financial_Note &fn)
Public Attributes
PLLRoot< Financial_Monthly_Category > categories
Protected Attributes
String month
Constructor & Destructor Documentation
Financial_Monthly::Financial_Monthly (String m) [inline]
Definition at line 1136 of file dil2al.hh.
1136 : month(m) {}
Member Function Documentation
void Financial_Monthly::add (const Financial_Note & fn)
Definition at line 209 of file finances.cc.
References Financial_Monthly_Category::add(), String::after(), categories, Financial_Note::Expense(), Financial_Monthly_Category::Find_Category(), PLLHandle< Financial_Monthly >::head(), PLLRoot< Financial_Monthly_Category >::head(), String::index(), PLL_LOOP_FORWARD, String::sub(), PLLRoot< Financial_Monthly_Category >::tail(), and Financial_Note::Type().
Referenced by Financial_Monthly_Root::add().
209                                                      {
210   // add by category
211   String cstr = fn.Type();
212   if (cstr.index(BRXidentifier)<0) cstr = "variable";
213   else cstr = cstr.sub(BRXidentifier,0);
214   Financial_Monthly_Category * fc = NULL;
215   if (categories.head()) fc = categories.head()->Find_Category(cstr);
216   if (!fc) { // add category in all months
217     PLL_LOOP_FORWARD(Financial_Monthly,head(),1) {
218       fc = new Financial_Monthly_Category(cstr);
219       e->categories.link_before(fc);
220     }
221     fc = categories.tail(); // retrieve category in this month
222   }
223   // add to category result and by subcategory
224   fc->add(fn.Type().after(','),fn.Expense(),*this);
225 }
void Financial_Monthly::Copy_Categories (Financial_Monthly * h)
Definition at line 200 of file finances.cc.
References categories, Financial_Monthly_Category::Copy_SubCategories(), PLLRoot< Financial_Monthly_Category >::head(), PLLRoot< Financial_Monthly_Category >::link_before(), and PLL_LOOP_FORWARD.
Referenced by Financial_Monthly_Root::add().
200                                                              {
201   if (h==this) return; // no other month to copy from
202   PLL_LOOP_FORWARD(Financial_Monthly_Category,h->categories.head(),1) {
203     Financial_Monthly_Category * fc = new Financial_Monthly_Category(e->Category());
204     categories.link_before(fc);
205     fc->Copy_SubCategories(e);
206   }
207 }
Financial_Monthly * Financial_Monthly::Find_Month (String m) const
Definition at line 194 of file finances.cc.
References month, and PLLHandle< Financial_Monthly >::Next().
Referenced by Financial_Monthly_Root::add().
194                                                                 {
195   if (month==m) return const_cast<Financial_Monthly *>(this);
196   if (Next()) return Next()->Find_Month(m);
197   return NULL;
198 }
String Financial_Monthly::Month () const [inline]
Definition at line 1138 of file dil2al.hh.
1138 { return month; }
Member Data Documentation
PLLRoot<Financial_Monthly_Category> Financial_Monthly::categories
Definition at line 1137 of file dil2al.hh.
Referenced by add(), and Copy_Categories().
String Financial_Monthly::month [protected]
Definition at line 1134 of file dil2al.hh.
Referenced by Find_Month().
The documentation for this class was generated from the following files:
dil2al.hh
finances.cc