AL_Day Class Reference
#include <dil2al.hh>
Public Types
enum TC_add_method { TAIL_REPLACE,
RANDOM,
BEFORE_HEAD
 }
Public Methods
AL_Day (time_t dd, int typ, time_t tcsec, time_t dsmin, time_t dmaxt=SECONDSPERDAY)
~AL_Day ()
int DayType ()
time_t DayDate ()
time_t DayStart ()
time_t DayStartMin ()
time_t DayMaxt ()
bool Expanded ()
long Avail ()
long Total ()
AL_TC * TC_Head ()
AL_TC * TC_Tail ()
AL_TD * TD_Head ()
AL_TD * TD_Tail ()
long set_avail (time_t av)
long available_before (time_t td)
int days_to (time_t td)
void create_TCs (bool setvalues=false)
void add_TCs (long tcs, TC_add_method m, time_t addborder=MAXTIME_T)
long expand (long expandn, time_t td)
float set_TC_values (long &i_start, long i_limit)
float allocate_with_value (float uval, DIL_entry *de)
AL_TC * Get_Avail_TC (unsigned long n)
AL_TC * allocate (DIL_entry *de)
AL_Day * Add_Target_Date (DIL_entry *de)
long remove_unused_TCs ()
float linear_day_distribution (time_t td)
float squared_day_distribution (time_t td)
Public Attributes
PLLRoot< AL_TC > tc
PLLRoot< AL_TD > td
float val
Protected Attributes
int daytype
long avail
long tot
time_t daydate
time_t daystart
time_t daystartmin
time_t daymaxt
time_t tcseconds
bool expanded
long cache_i_start
long cache_i_limit
Member Enumeration Documentation
enum AL_Day::TC_add_method
Enumeration values:
TAIL_REPLACE
RANDOM
BEFORE_HEAD
Definition at line 887 of file dil2al.hh.
Referenced by expand().
887 { TAIL_REPLACE, RANDOM, BEFORE_HEAD };
Constructor & Destructor Documentation
AL_Day::AL_Day (time_t dd, int typ, time_t tcsec, time_t dsmin, time_t dmaxt = SECONDSPERDAY)
Definition at line 391 of file alcomp.cc.
References daystart, daystartmin, false, and SECONDSPERDAY.
391                                                                                           :
392                 daystartmin(dsmin), daymaxt(dmaxt), daytype(typ), avail(0), tot(0), daydate(dd),
393                 tcseconds(tcsec), expanded(false), cache_i_start(0), cache_i_limit(0), val(0.0) {
394         if (alworkdaystart>=daystartmin) daystart = alworkdaystart;
395         else daystart = daystartmin;
396 }
AL_Day::~AL_Day () [inline]
Definition at line 864 of file dil2al.hh.
864 {} 
Member Function Documentation
AL_Day * AL_Day::Add_Target_Date (DIL_entry * de)
Definition at line 649 of file alcomp.cc.
References daydate, PLLRoot< AL_TD >::link_before(), PLLHandle< AL_Day >::Next(), PLLHandle< AL_Day >::Prev(), SECONDSPERDAY, DIL_entry::Target_Date(), and td.
Referenced by Active_List::Add_Target_Date().
649                                                {
650 // Adds a target date reference to the day that contains it
651         if (!de) return NULL;
652         time_t tdiff = de->Target_Date() - daydate;
653         if (tdiff<0) {
654                 if (Prev()) return Prev()->Add_Target_Date(de);
655                 return NULL;
656         }
657         if (tdiff>=SECONDSPERDAY) {
658                 if (Next()) return Next()->Add_Target_Date(de);
659                 return NULL;
660         }
661         AL_TD * atd = new AL_TD(*de);
662         td.link_before(atd);
663         return this;
664 }
void AL_Day::add_TCs (long tcs, TC_add_method m, time_t addborder = MAXTIME_T)
Definition at line 442 of file alcomp.cc.
References avail, BEFORE_HEAD, expanded, PLLRoot< AL_TC >::head(), PLLRoot< AL_TC >::length(), PLLRoot< AL_TC >::link_after(), PLLRoot< AL_TC >::link_before(), MAXTIME_T, RANDOM, AL_TC::Set_DE(), TAIL_REPLACE, DIL_entry::Target_Date(), tc, and tot.
Referenced by expand().
442                                                                             {
443 // safely add task chunks to a day
444 // links new task chunks if tchead!=NULL, using TAIL_REPLACE,
445 // RANDOM or BEFORE_HEAD methods, TAIL_REPLACE and RANDOM
446 // methods use the addborder parameter
447 // (see <A HREF="al-day-expand.fig">al-day-expand.fig</A>)
448 // uses tchead.length() to insure that tot will
449 // equal tchead.length() if tchead!=NULL
450         expanded = true;
451         avail += tcs;
452         tot += tcs;
453         if (tc.head()) {
454                 long linked = tc.length(), tci;
455                 tcs = tot - linked; // recalculated to insure at least tot TCs
456                 if (tcs<0) tcs = 0;
457                 switch (m) {
458                         case TAIL_REPLACE:
459                                 // Place empty TCs at tail and move de pointers at chosen
460                                 // random location to those TCs if de->Target_Date()>addborder
461                                 for (; tcs>0; tcs--) {
462                                         AL_TC * altc = new AL_TC();
463                                         tc.link_before(altc); linked++;
464                                         tci = (unsigned long) rint(((float) linked)*(((float) rand()) / ((float) RAND_MAX)));
465                                         if (tc[tci]) {
466                                                 DIL_entry * de = tc[tci]->Get_DE();
467                                                 if (de) if (de->Target_Date()>addborder) altc->Set_DE(tc[tci]->Set_DE(NULL));
468                                         }
469                                 }
470                                 break;
471                         case RANDOM:
472                                 // Place empty TCs at head and move de pointers at chosen
473                                 // random location to those TCs
474                                 if (linked>addborder) linked = (long) addborder; // number of TCs prior to tdiff
475                                 for (; tcs>0; tcs--) {
476                                         AL_TC * altc = new AL_TC();
477                                         tc.link_after(altc); linked++;
478                                         tci = (unsigned long) rint(((float) linked)*(((float) rand()) / ((float) RAND_MAX)));
479                                         if (tc[tci]) {
480                                                 DIL_entry * de = tc[tci]->Get_DE();
481                                                 if (de) altc->Set_DE(tc[tci]->Set_DE(NULL));
482                                         }
483                                 }
484                                 break;
485                         case BEFORE_HEAD:
486                                 // link tcs empty TCs before head
487                                 for (; tcs>0; tcs--) tc.link_after(new AL_TC());
488                                 break;
489                 }
490         }
491 }
AL_TC * AL_Day::allocate (DIL_entry * de)
Definition at line 628 of file alcomp.cc.
References AL_TC::allocate(), Avail(), avail, create_TCs(), DayDate(), PLLRoot< AL_TC >::head(), PLLHandle< AL_Day >::Next(), tc, time_stamp(), Total(), and VOUT.
Referenced by Active_List::allocate().
628                                        {
629 // allocates de to the first available task
630 // chunk in this day or following days
631 // returns the allocated task chunk
632 // creates task chunks if necessary where tchead==NULL
633         if (avail<=0) {
634                 if (Next()) return Next()->allocate(de);
635                 return NULL;
636         }
637 #ifdef DETAILED_AL_DIAGNOSTIC_OUTPUT
638         VOUT << "A>" << time_stamp("%Y%m%d",DayDate()) << ": (" << Total() << ',' << Avail() << ')';
639 #endif
640         create_TCs();
641         AL_TC * atc = tc.head()->allocate(de);
642         if (atc) avail--;
643 #ifdef DETAILED_AL_DIAGNOSTIC_OUTPUT
644         VOUT << "->(" << Total() << ',' << Avail() << ")\n";
645 #endif
646         return atc;
647 }
float AL_Day::allocate_with_value (float uval, DIL_entry * de)
Definition at line 593 of file alcomp.cc.
References AL_TC::allocate_with_value(), avail, Avail(), create_TCs(), DayDate(), PLLRoot< AL_TC >::head(), PLLHandle< AL_Day >::Next(), tc, time_stamp(), Total(), val, and VOUT.
Referenced by Active_List::allocate_with_value().
593                                                             {
594 // allocate a DIL entry to a task chunk according to
595 // a random value
596 // returns the value of the allocated task chunk
597 // creates TCs if necessary
598         if (val<uval) {
599                 if (Next()) return Next()->allocate_with_value(uval-val,de);
600                 return 0.0; // (error) no more days, value was beyond sum
601         }
602 #ifdef DETAILED_AL_DIAGNOSTIC_OUTPUT
603         VOUT << "V>" << time_stamp("%Y%m%d",DayDate()) << ": (" << Total() << ',' << Avail() << ')';
604 #endif
605         create_TCs(true); // create TCs if necessary
606         float v = tc.head()->allocate_with_value(uval,de);
607         if (v>0.0) {
608                 val -= v;
609                 avail--;
610         }
611 #ifdef DETAILED_AL_DIAGNOSTIC_OUTPUT
612         VOUT << "->(" << Total() << ',' << Avail() << ")\n";
613 #endif
614         return v;
615 }
long AL_Day::Avail () [inline]
Definition at line 877 of file dil2al.hh.
References avail.
Referenced by allocate(), allocate_with_value(), and expand().
877 { return avail; }
long AL_Day::available_before (time_t td)
Definition at line 418 of file alcomp.cc.
References avail, AL_TC::available_before(), daydate, DayDate(), daystart, EOUT, PLLHandle< AL_Day >::Next(), TC_Head(), tcseconds, and td.
418                                        {
419 // returns the number of task chunks available for allocation
420 // prior to a target date td
421 // avail, daystart, tcseconds and Next()->DayDate() must contain valid values
422 // *** might be sped up by putting a for-loop into the
423 //     corresponding Active_List function
424         if (Next()) if (td>=Next()->DayDate()) return avail + Next()->available_before(td); // target date is within a following day
425         time_t tdiff = td - (daydate+daystart);
426         if (tdiff<=0) return 0; // target date is earlier than or at work start offset
427 #ifdef DIAGNOSTIC_OUTPUT
428         EOUT << "@tdiff=" << tdiff << ", tcseconds=" << tcseconds << ", tdiff/tcseconds=" << tdiff/tcseconds << '@';
429 #endif
430         long TCs_before = tdiff / tcseconds; // can't exceed target date
431         if (TC_Head()) return TC_Head()->available_before(TCs_before); // count available TCs before target date
432         return TCs_before;
433 }
void AL_Day::create_TCs (bool setvalues = false)
Definition at line 580 of file alcomp.cc.
References cache_i_limit, cache_i_start, PLLRoot< AL_TC >::head(), PLLRoot< AL_TC >::link_before(), tc, and tot.
Referenced by allocate(), allocate_with_value(), and Get_Avail_TC().
580                                               {
581 // creates TCs and sets values according to a random
582 // distribution if setvalues==true, in which case it
583 // requires valid cache_i_start and cache_i_limit values
584         if (tc.head()) return;
585         AL_TC * atc;
586         for (long i = 0; i<tot; i++) {
587                 if (setvalues) atc = new AL_TC(i+cache_i_start,cache_i_limit);
588                 else atc = new AL_TC();
589                 tc.link_before(atc);
590         }
591 }
time_t AL_Day::DayDate () [inline]
Definition at line 872 of file dil2al.hh.
References daydate.
Referenced by Active_List::Add_Day(), AL_Day_Marker(), allocate(), allocate_with_value(), available_before(), days_to(), expand(), and generate_AL().
872 { return daydate; }
time_t AL_Day::DayMaxt () [inline]
Definition at line 875 of file dil2al.hh.
References daymaxt.
Referenced by AL_Day_Marker(), and generate_AL().
875 { return daymaxt; }
int AL_Day::days_to (time_t td)
Definition at line 435 of file alcomp.cc.
References DayDate(), PLLHandle< AL_Day >::Next(), and td.
Referenced by linear_day_distribution(), and squared_day_distribution().
435                              {
436 // returns the number of days to the target date, including
437 // the current day and the day containing the target date
438         if (Next()) if (td>Next()->DayDate()) return 1 + Next()->days_to(td);
439         return 1;
440 }
time_t AL_Day::DayStart () [inline]
Definition at line 873 of file dil2al.hh.
References daystart.
Referenced by AL_Day_Marker(), generate_AL(), and Active_List::Initialize_AL_Length().
873 { return daystart; }
time_t AL_Day::DayStartMin () [inline]
Definition at line 874 of file dil2al.hh.
References daystartmin.
Referenced by AL_Day_Marker(), and Active_List::Initialize_AL_Length().
874 { return daystartmin; }
int AL_Day::DayType () [inline]
Definition at line 871 of file dil2al.hh.
References daytype.
Referenced by AL_Day_Marker().
871 { return daytype; }
long AL_Day::expand (long expandn, time_t td)
Definition at line 494 of file alcomp.cc.
References add_TCs(), Avail(), BEFORE_HEAD, DayDate(), daydate, daymaxt, daystart, daystartmin, EOUT, RANDOM, TAIL_REPLACE, TC_add_method, tcseconds, td, time_stamp(), tot, Total(), and VOUT.
Referenced by Active_List::expand().
494                                            {
495 // expand work time by adding task chunks prior to
496 // the target date td
497 // returns the number of task chunks added (-1==error)
498 // (see <A HREF="al-day-expand.fig">al-day-expand.fig</A>)
499         if (expandn<=0) return 0;
500         const time_t tdiff(td - daydate); // target date limit (offset in current day)
501         // case: TD1 in al-day-expand.fig
502         if (tdiff<(daystartmin+tcseconds)) return 0;
503 #ifdef DETAILED_AL_DIAGNOSTIC_OUTPUT
504         VOUT << "E>" << time_stamp("%Y%m%d",DayDate()) << ": (" << Total() << ',' << Avail() << "), expand request = " << expandn << '\n';
505 #endif
506         long addabove = 0;
507         time_t dayend = daystart+(tot*tcseconds); // if tot==0 dayend is current time
508         // cases: TD4, TD5 and TD6 in al-day-expand.fig
509         if (tdiff>=(dayend+tcseconds)) { // TD beyond current end of day tasks
510                 time_t dayendmax = tdiff;
511                 if (tdiff>daymaxt) dayendmax = daymaxt; // day upper limit
512                 addabove = (dayendmax-dayend)/tcseconds; // count TCs that can be added prior to target date and daymaxt
513                 if (addabove>0) {
514                         if (addabove>expandn) addabove = expandn; // add expandn or fewer TCs above current dayend
515 #ifdef DETAILED_AL_DIAGNOSTIC_OUTPUT
516                         VOUT << "Ea>" << time_stamp("%Y%m%d",DayDate()) << ": (" << Total() << ',' << Avail() << ')';
517 #endif
518                         add_TCs(addabove,TAIL_REPLACE,daydate+dayendmax); // add empty TCs by replacing allocated TCs with target dates greater than dayendmax and moving those to the tail and update tot and avail
519                         expandn -= addabove;
520 #ifdef DETAILED_AL_DIAGNOSTIC_OUTPUT
521                         VOUT << "->(" << Total() << ',' << Avail() << ")\n";
522 #endif
523                         if (expandn<0) EOUT << "dil2al: Warning - Expansion exceeded requirement in AL_Day::expand()\n";
524                         if (expandn<=0) return addabove;
525                 }
526         }
527         // case: TD3 in al-day-expand.fig
528         time_t tlowerexpand = daystart;
529         TC_add_method m = RANDOM;
530         long totbeforetdiff = (tdiff-daystart)/tcseconds;
531         // case: TD2 in al-day-expand.fig
532         if (totbeforetdiff<=0) {
533                 tlowerexpand = tdiff;
534                 m = BEFORE_HEAD;
535         }
536         if (totbeforetdiff>tot) totbeforetdiff = tot;
537         time_t newdaystart = tlowerexpand - (expandn*tcseconds); // attempt to add expandn TCs prior to daystart
538         if (newdaystart<daystartmin) newdaystart = daystartmin; // daystart limit
539         long addbelow = (tlowerexpand-newdaystart)/tcseconds; // count TCs to be added prior to daystart
540         if (addbelow>0) { // add expandn or fewer TCs below min(daystart,TDtime)
541                 daystart = newdaystart;
542 #ifdef DETAILED_AL_DIAGNOSTIC_OUTPUT
543                 VOUT << "Eab>" << time_stamp("%Y%m%d",DayDate()) << ": (" << Total() << ',' << Avail() << ')';
544 #endif
545                 add_TCs(addbelow,m,totbeforetdiff); // add empty TCs before target date and update tot and avail
546 #ifdef DETAILED_AL_DIAGNOSTIC_OUTPUT
547                 VOUT << "->(" << Total() << ',' << Avail() << ")\n";
548 #endif
549                 return addabove+addbelow;
550         }
551 #ifdef DETAILED_AL_DIAGNOSTIC_OUTPUT
552         VOUT << "Ex>" << time_stamp("%Y%m%d",DayDate()) << ": (" << Total() << ',' << Avail() << ")\n";
553 #endif
554         return addabove;
555 }
bool AL_Day::Expanded () [inline]
Definition at line 876 of file dil2al.hh.
References expanded.
Referenced by AL_Day_Marker().
876 { return expanded; }
AL_TC * AL_Day::Get_Avail_TC (unsigned long n)
Definition at line 617 of file alcomp.cc.
References avail, AL_TC::avail_el(), create_TCs(), PLLRoot< AL_TC >::head(), PLLHandle< AL_Day >::Next(), and tc.
Referenced by Active_List::Get_Avail_TC().
617                                             {
618 // returns the nth available task chunk in the AL
619 // creates task chunks if necessary where tchead==NULL
620         if (avail<=n) {
621                 if (Next()) return Next()->Get_Avail_TC(n-avail);
622                 return NULL;
623         }
624         create_TCs();
625         return tc.head()->avail_el(n);
626 }
float AL_Day::linear_day_distribution (time_t td)
Definition at line 702 of file alcomp.cc.
References days_to(), PLL_LOOP_FORWARD, and td.
Referenced by Active_List::expand().
702                                                {
703 // linearly distribute values up to target date
704         float sumval = 0;
705         int tddays = days_to(td);
706         float fdays = (float) tddays;
707         long i = 0;
708         PLL_LOOP_FORWARD(AL_Day,this,(e->DayDate()<td)) {
709                 e->val = 1.0 - (aldaydistslope*((float) i/fdays));
710                 sumval += e->val;
711                 i++;
712         }
713         return sumval;
714 }
long AL_Day::remove_unused_TCs ()
Definition at line 666 of file alcomp.cc.
References avail, AL_TC::Get_DE(), PLLRoot< AL_TC >::head(), PLLHandle< AL_TC >::Next(), PLLHandle< AL_Day >::Next(), PLLHandle< AL_TC >::remove(), tc, and tot.
Referenced by Active_List::remove_unused_TCs().
666                                {
667 // clean up by removing unused TCs
668 // returns remaining number of TCs in AL
669         if (!tc.head()) { // no TCs created in this day
670                 tot = 0;
671                 avail = 0;
672                 if (Next()) return Next()->remove_unused_TCs();
673                 return 0;
674         }
675         AL_TC * rtc, * atc = tc.head();
676         tot = 0; // insure correct count
677         while (atc) { // remove unused TCs in this day
678                 rtc = atc;
679                 atc = atc->Next();
680                 if (!rtc->Get_DE()) rtc->remove();
681                 else tot++; // faster than calling tchead->length()
682         }
683         avail = 0;
684         if (Next()) return tot + Next()->remove_unused_TCs();
685         return tot;
686 }
long AL_Day::set_avail (time_t av)
Definition at line 398 of file alcomp.cc.
References avail, daymaxt, daystartmin, EOUT, tcseconds, and tot.
Referenced by Active_List::Initialize_AL_Length().
398                                 {
399 // attempt to make av seconds available through task chunks
400 // returns the number of task chunks made available
401 // the number of task chunks is limited by (daymaxt-daystartmin)
402 // if av<0 no task chunks will be made available
403         time_t dtmax = daymaxt - daystartmin;
404 #ifdef DIAGNOSTIC_OUTPUT
405         EOUT << "dil2al: (DIAGNOSTICS) av = " << av << ", daymaxt = " << daymaxt << ", daystartmin = " << daystartmin << ", dtmax = " << dtmax << '\n';
406 #endif
407         if (av>0) {
408                 if (av>dtmax) av = dtmax;
409                 avail = av/tcseconds; // floor, can't exceed limit
410         } else avail = 0;
411         tot = avail; // initialized with all TCs available
412 #ifdef DIAGNOSTIC_OUTPUT
413         EOUT << "dil2al: (DIAGNOSTICS) av = " << av << ", avail = " << avail << ", tot = " << tot << '\n';
414 #endif
415         return avail;
416 }
float AL_Day::set_TC_values (long & i_start, long i_limit)
Definition at line 557 of file alcomp.cc.
References avail, AL_TC::avail_el(), cache_i_limit, cache_i_start, daydate, EOUT, PLLRoot< AL_TC >::head(), linear_distribution(), AL_TC::set_val(), tc, time_stamp(), and val.
557                                                         {
558 // set TC values within this day
559 // returns sum of TC values
560         float v;
561         cache_i_start = i_start;
562         cache_i_limit = i_limit;
563         val = 0.0;
564         for (long i=0; i<avail; i++) {
565                 if ((i+i_start)>=i_limit) v = 0.0;
566                 else v = linear_distribution((float) (i+i_start), (float) i_limit);
567                 if (tc.head()) {
568                         AL_TC * atc = tc.head()->avail_el(i);
569                         if (atc) atc->set_val(v);
570                         else EOUT << "dil2al: Available TC #" << i << " on day " << time_stamp("%Y%m%d",daydate) << " not found in AL_Day::set_TC_values(), continuing\n";
571                 }
572                 // assignment of values to remaining TCs occurs when
573                 // those TCs are created as a search enters them
574                 val += v; // store summed values of TCs for that day
575         }
576         i_start += avail;
577         return val;
578 }
float AL_Day::squared_day_distribution (time_t td)
Definition at line 688 of file alcomp.cc.
References days_to(), PLL_LOOP_FORWARD, and td.
Referenced by Active_List::expand().
688                                                 {
689 // distribute values up to target date according to a squared function
690         float sumval = 0;
691         int tddays = days_to(td);
692         float fdays = (float) tddays, fi = 0.0;
693         long i = 0;
694         PLL_LOOP_FORWARD(AL_Day,this,(e->DayDate()<td)) {
695                 e->val = 1.0 - (aldaydistslope*(fi*fi));
696                 sumval += e->val;
697                 i++; fi = ((float) i)/fdays;
698         }
699         return sumval;
700 }
AL_TC* AL_Day::TC_Head () [inline]
Definition at line 879 of file dil2al.hh.
References PLLRoot< PLLType >::head().
Referenced by available_before().
879 { return tc.head(); }
AL_TC* AL_Day::TC_Tail () [inline]
Definition at line 880 of file dil2al.hh.
References PLLRoot< PLLType >::tail().
880 { return tc.tail(); }
AL_TD* AL_Day::TD_Head () [inline]
Definition at line 881 of file dil2al.hh.
References PLLRoot< PLLType >::head().
Referenced by AL_Day_Marker().
881 { return td.head(); }
AL_TD* AL_Day::TD_Tail () [inline]
Definition at line 882 of file dil2al.hh.
References PLLRoot< PLLType >::tail().
882 { return td.tail(); }
long AL_Day::Total () [inline]
Definition at line 878 of file dil2al.hh.
References tot.
Referenced by AL_Day_Marker(), allocate(), allocate_with_value(), and expand().
878 { return tot; }
Member Data Documentation
long AL_Day::avail [protected]
Definition at line 850 of file dil2al.hh.
Referenced by add_TCs(), allocate(), allocate_with_value(), Avail(), available_before(), Get_Avail_TC(), remove_unused_TCs(), set_avail(), and set_TC_values().
long AL_Day::cache_i_limit [protected]
Definition at line 859 of file dil2al.hh.
Referenced by create_TCs(), and set_TC_values().
long AL_Day::cache_i_start [protected]
Definition at line 858 of file dil2al.hh.
Referenced by create_TCs(), and set_TC_values().
time_t AL_Day::daydate [protected]
Definition at line 852 of file dil2al.hh.
Referenced by Add_Target_Date(), available_before(), DayDate(), expand(), and set_TC_values().
time_t AL_Day::daymaxt [protected]
Definition at line 855 of file dil2al.hh.
Referenced by DayMaxt(), expand(), and set_avail().
time_t AL_Day::daystart [protected]
Definition at line 853 of file dil2al.hh.
Referenced by AL_Day(), available_before(), DayStart(), and expand().
time_t AL_Day::daystartmin [protected]
Definition at line 854 of file dil2al.hh.
Referenced by AL_Day(), DayStartMin(), expand(), and set_avail().
int AL_Day::daytype [protected]
Definition at line 849 of file dil2al.hh.
Referenced by DayType().
bool AL_Day::expanded [protected]
Definition at line 857 of file dil2al.hh.
Referenced by add_TCs(), and Expanded().
PLLRoot<AL_TC> AL_Day::tc
Definition at line 866 of file dil2al.hh.
Referenced by add_TCs(), allocate(), allocate_with_value(), create_TCs(), Get_Avail_TC(), remove_unused_TCs(), and set_TC_values().
time_t AL_Day::tcseconds [protected]
Definition at line 856 of file dil2al.hh.
Referenced by available_before(), expand(), and set_avail().
PLLRoot<AL_TD> AL_Day::td
Definition at line 867 of file dil2al.hh.
Referenced by Add_Target_Date(), available_before(), days_to(), expand(), linear_day_distribution(), and squared_day_distribution().
long AL_Day::tot [protected]
Definition at line 851 of file dil2al.hh.
Referenced by add_TCs(), create_TCs(), expand(), remove_unused_TCs(), set_avail(), and Total().
float AL_Day::val
Definition at line 869 of file dil2al.hh.
Referenced by allocate_with_value(), Active_List::expand(), and set_TC_values().
The documentation for this class was generated from the following files:
dil2al.hh
alcomp.cc