Search_Target Class Reference
#include <dil2al.hh>
Public Methods
Search_Target (PLLRoot< Search_Result > *r, const char *s, const char *t, int f, bool l, Quick_String_Hash *e=NULL)
Search_Target (const Search_Target &parent, const char *t)
String Target () const
long search ()
long links (const String &t)
void set_searched (int sval=1)
void reset_searched ()
Protected Methods
void check_encountered ()
Protected Attributes
PLLRoot< Search_Result > * results
String searchkey
Target_Access target
int followlinks
bool localtargets
Quick_String_Hash * encountered
int searched
Constructor & Destructor Documentation
Search_Target::Search_Target (PLLRoot< Search_Result > * r, const char * s, const char * t, int f, bool l, Quick_String_Hash * e = NULL) [inline]
Definition at line 1037 of file dil2al.hh.
References check_encountered(), followlinks, localtargets, and searched.
Referenced by links().
1037 : results(r), searchkey(s), target(t), followlinks(f), localtargets(l), encountered(e), searched(0) { check_encountered(); }
Search_Target::Search_Target (const Search_Target & parent, const char * t) [inline]
Definition at line 1038 of file dil2al.hh.
References check_encountered(), followlinks, localtargets, and searched.
1038 : results(parent.results), searchkey(parent.searchkey), target(parent.target,t), followlinks(parent.followlinks-1), localtargets(parent.localtargets), encountered(parent.encountered), searched(0) { check_encountered(); } // relative to a parent target
Member Function Documentation
void Search_Target::check_encountered () [protected]
Definition at line 278 of file search.cc.
References encountered, Quick_String_Hash::read(), searched, Target_Access::TA_FTP, Target_Access::TA_HTTP, Target_Access::Target(), target, and Target_Access::Type().
Referenced by Search_Target().
278                                       {
279         if (encountered) {
280                 if (encountered->read((const char *) target.Target())) searched = 1;
281                 else (*encountered) << (const char *) target.Target();
282         }
283         if ((!remotesearch) && ((target.Type()==Target_Access::TA_HTTP) || (target.Type()==Target_Access::TA_FTP))) searched = -1;
284 }
long Search_Target::links (const String & t)
Definition at line 316 of file search.cc.
References String::contains(), String::empty(), generic_remove_name_reference(), String::index(), PLLRoot< Search_Target >::link_before(), PLLHandle< Search_Target >::Root(), String::SEARCH_END, and Search_Target().
Referenced by search().
316                                           {
317         // Finds links in the text t and adds them to the list of targets
318         const BigRegex linksrx("[<][Aa][^>]+[Hh][Rr][Ee][Ff]");
319         const BigRegex lkendrx("[<][/][Aa][ \t]?[^>]*[>]");
320         const BigRegex urlstartrx("=[ \t]*\"?");
321         const BigRegex mailtorx("^[ \t]*[Mm][Aa][Ii][Ll][Tt][Oo][ \t]*:");
322         int i = 0;
323         while ((i=t.index(linksrx,String::SEARCH_END,i))>=0) {
324                 int urlstart = t.index(urlstartrx,String::SEARCH_END,i); // find URL start
325                 if (urlstart>=0) {
326                         int urlend;
327                         if (t[urlstart-1]=='"') urlend = t.index('"',urlstart); // find matching '"'
328                         else urlend = t.index(BRXwhite,urlstart); // find white-space terminated URL
329                         if (urlend>=0) {
330                                 String url(const_cast<String &>(t).at(urlstart,urlend-urlstart)); // get URL
331                                 generic_remove_name_reference(url);
332                                 if (!(url.empty() || url.contains(mailtorx))) {
333                                         // *** currently assumes breadth-first search
334                                         Search_Target * st = new Search_Target(*this,url);
335                                         Root()->link_before(st); // append st to list
336                                 }
337                         }
338                 }
339                 i = t.index(lkendrx,String::SEARCH_END,i); // find end of hyperlink
340         }       
341 }
void Search_Target::reset_searched () [inline]
Definition at line 1045 of file dil2al.hh.
References searched.
1045 { searched = 0; }
long Search_Target::search ()
Definition at line 287 of file search.cc.
References EOUT, followlinks, String::index(), PLLRoot< Search_Result >::link_before(), links(), Target_Access::read_cleartext_into_String(), res, results, String::SEARCH_END, searched, searchkey, Search_Result::SR_DIRECTORY_ENTRY, Search_Result::SR_URL, PLLRoot< Search_Result >::tail(), Target_Access::Target(), target, and Search_Result::Type().
287                            {
288         // Searches the target file for occurrences of searchkey and stores the results
289 #ifdef SEARCH_TARGET_DEBUG
290         EOUT << "dil2al: Search_Target::search(), followlinks=" << followlinks << ", target.Target() = " << target.Target() << '\n';
291 #endif
292         if (searched!=0) {
293                 if (verbose) {
294                         if (searched==1) EOUT << target.Target() << " already searched elsewhere\n";
295                         else EOUT << target.Target() << " restricted, do not search\n";
296                 }
297                 return 0;
298         }
299         String t;
300         if (!target.read_cleartext_into_String(t)) return -1;
301         int i = 0, res = 0; BigRegex skrx(searchkey);
302         while ((i=t.index(skrx,String::SEARCH_END,i))>=0) {
303                 Search_Result * r = new Search_Result(searchkey,target,t,skrx);
304                 if (((r->Type()==Search_Result::SR_DIRECTORY_ENTRY) || (r->Type()==Search_Result::SR_URL)) && (results->tail())) if (*(results->tail())==*r) {
305                         delete r; // try to avoid duplicates
306                         continue;
307                 }
308                 results->link_before(r);
309                 res++;
310         }
311         if (followlinks>0) links(t); // if followlinks>0 then links are sought and added to the search
312         searched = 1;
313         return res;
314 }
void Search_Target::set_searched (int sval = 1) [inline]
Definition at line 1044 of file dil2al.hh.
References searched.
1044 { searched = sval; }
String Search_Target::Target () const [inline]
Definition at line 1041 of file dil2al.hh.
References Target_Access::Target().
1041 { return target.Target(); }
Member Data Documentation
Quick_String_Hash* Search_Target::encountered [protected]
Definition at line 1027 of file dil2al.hh.
Referenced by check_encountered().
int Search_Target::followlinks [protected]
Definition at line 1025 of file dil2al.hh.
Referenced by search(), and Search_Target().
bool Search_Target::localtargets [protected]
Definition at line 1026 of file dil2al.hh.
Referenced by Search_Target().
PLLRoot<Search_Result>* Search_Target::results [protected]
Definition at line 1022 of file dil2al.hh.
Referenced by search().
int Search_Target::searched [protected]
Definition at line 1033 of file dil2al.hh.
Referenced by check_encountered(), reset_searched(), search(), Search_Target(), and set_searched().
String Search_Target::searchkey [protected]
Definition at line 1023 of file dil2al.hh.
Referenced by search().
Target_Access Search_Target::target [protected]
Definition at line 1024 of file dil2al.hh.
Referenced by check_encountered(), and search().
The documentation for this class was generated from the following files:
dil2al.hh
search.cc