Topical_DIL_Files Class Reference
#include <dil2al.hh>
Public Methods
Topical_DIL_Files ()
~Topical_DIL_Files ()
String * operator[] (int n)
String * File (int n=0)
String * Title (int n=0)
filetitle_t * Topic (int n=0)
void Invalidate ()
int Refresh ()
Protected Methods
void Set_File (String file, int n=0)
void Set_Title (String title, int n=0)
Protected Attributes
filetitle_t ft
bool updated
Constructor & Destructor Documentation
Topical_DIL_Files::Topical_DIL_Files () [inline]
Definition at line 321 of file dil2al.hh.
References false, and updated.
Referenced by Set_File(), and Set_Title().
321 : updated(false) {}
Topical_DIL_Files::~Topical_DIL_Files () [inline]
Definition at line 323 of file dil2al.hh.
323 {} 
Member Function Documentation
String * Topical_DIL_Files::File (int n = 0) [inline]
Definition at line 379 of file dil2al.hh.
References File(), filetitle_t::file, ft, and Topical_DIL_Files_Updated_Access.
Referenced by File(), and operator[]().
379                                                  {
380         Topical_DIL_Files_Updated_Access(&(ft.file),File(),File)
381 }
void Topical_DIL_Files::Invalidate () [inline]
Definition at line 359 of file dil2al.hh.
References PLLHandle< Topical_DIL_Files >::Next(), PLLHandle< Topical_DIL_Files >::Prev(), and updated.
359                                           {
360         updated=false;
361         if (Prev()) Prev()->Invalidate();
362         if (Next()) Next()->Invalidate();
363 }
String * Topical_DIL_Files::operator[] (int n) [inline]
Definition at line 355 of file dil2al.hh.
References File(), and Protected_Linked_List_Indexed_Access.
355                                                    {
356         Protected_Linked_List_Indexed_Access(Topical_DIL_Files,File(),File());
357 }
int Topical_DIL_Files::Refresh ()
Definition at line 47 of file diladmin.cc.
References absurl(), EOUT, filetitle_t::file, find_line(), ft, PLLHandle< Topical_DIL_Files >::Next(), pattern_in_line(), PLLHandle< Topical_DIL_Files >::Prev(), Set_File(), Set_Title(), and filetitle_t::title.
47                                {
48 // Clear and reload Topical DIL files list
49         if (Prev()) return Prev()->Refresh(); // seek head of list
50         delete Next(); // clear list
51         ft.file=""; ft.title="";
52         const int LLEN = 10240, SLEN = 1024;
53         char lbuf[LLEN], sbuf[SLEN];
54         ifstream lf(listfile);
55         regex_t re;
56         regmatch_t rm[3];
57         int mres;
58         numDILs = 0;
59         if (lf) {
60                 // find DIL header
61                 if (!find_line(&lf,"<H1><A NAME=\"DIL\">",lbuf,LLEN)) return 0;
62                 // find <UL>
63                 if (!find_line(&lf,"<UL>",lbuf,LLEN)) return 0;
64                 // get DILs
65                 if (regcomp(&re,"<LI><A +HREF=\"([^\"]*)\">([^<]*)<", REG_EXTENDED) != 0) {
66                         EOUT << "dil2al: Unable to compile regular expression in get_topical_DILs()\n";
67                         return 0;
68                 }
69                 do {
70                         if (lf.eof()) {
71                                 regfree(&re);
72                                 return numDILs;
73                         }
74                         lf.getline(lbuf,LLEN);
75                         mres = regexec(&re,lbuf, (size_t) 3, rm, 0);
76                         if ((mres != 0) && (mres != REG_NOMATCH)) {
77                                 EOUT << "dil2al: Internal error while matching in get_topical_DILs()\n";
78                                 regfree(&re);
79                                 return 0;
80                         }
81                         if (!mres) {
82                                 if (rm[2].rm_so==-1) EOUT << "dil2al: Wrong number of substring matches in get_topical_DILs()\n";
83                                 else {
84                                         strncpy(sbuf,&lbuf[rm[1].rm_so],rm[1].rm_eo-rm[1].rm_so);
85                                         sbuf[rm[1].rm_eo-rm[1].rm_so]='\0';
86                                         Set_File(absurl(listfile,sbuf),numDILs);
87                                         strncpy(sbuf,&lbuf[rm[2].rm_so],rm[2].rm_eo-rm[2].rm_so);
88                                         sbuf[rm[2].rm_eo-rm[2].rm_so]='\0';
89                                         Set_Title(sbuf,numDILs);
90                                         numDILs++;
91                                 }
92                         }
93                 } while (!pattern_in_line("</UL>",lbuf));
94                 regfree(&re);
95                 return numDILs;
96         } else {
97                 EOUT << "dil2al: Error - " << listfile << " not found\n";
98                 return 0;
99         }
100 }
void Topical_DIL_Files::Set_File (String file, int n = 0) [protected]
Definition at line 13 of file diladmin.cc.
References filetitle_t::file, ft, PLLRoot< Topical_DIL_Files >::link_after(), PLLRoot< Topical_DIL_Files >::link_before(), PLLHandle< Topical_DIL_Files >::Next(), PLLHandle< Topical_DIL_Files >::Prev(), PLLHandle< Topical_DIL_Files >::Root(), Topical_DIL_Files(), and updated.
Referenced by Refresh().
13                                                        {
14         if (!n) { ft.file = file; updated=true; return; }
15         if (n>0) {
16                 if (Next()) Next()->Set_File(file,n-1);
17                 else {
18                         Topical_DIL_Files * tdf = new Topical_DIL_Files();
19                         if (Root()->link_before(tdf)) Next()->Set_File(file,n-1);
20                 }
21         } else {
22                 if (Prev()) Prev()->Set_File(file,n+1);
23                 else {
24                         Topical_DIL_Files * tdf = new Topical_DIL_Files();
25                         if (Root()->link_after(tdf)) Prev()->Set_File(file,n+1);
26                 }
27         }
28 }
void Topical_DIL_Files::Set_Title (String title, int n = 0) [protected]
Definition at line 30 of file diladmin.cc.
References ft, PLLRoot< Topical_DIL_Files >::link_after(), PLLRoot< Topical_DIL_Files >::link_before(), PLLHandle< Topical_DIL_Files >::Next(), PLLHandle< Topical_DIL_Files >::Prev(), PLLHandle< Topical_DIL_Files >::Root(), filetitle_t::title, Topical_DIL_Files(), and updated.
Referenced by Refresh().
30                                                          {
31         if (!n) { ft.title = title; updated=true; return; }
32         if (n>0) {
33                 if (Next()) Next()->Set_Title(title,n-1);
34                 else {
35                         Topical_DIL_Files * tdf = new Topical_DIL_Files();
36                         if (Root()->link_before(tdf)) Next()->Set_Title(title,n-1);
37                 }
38         } else {
39                 if (Prev()) Prev()->Set_Title(title,n+1);
40                 else {
41                         Topical_DIL_Files * tdf = new Topical_DIL_Files();
42                         if (Root()->link_after(tdf)) Prev()->Set_Title(title,n+1);
43                 }
44         }
45 }
String * Topical_DIL_Files::Title (int n = 0) [inline]
Definition at line 383 of file dil2al.hh.
References ft, Title(), filetitle_t::title, and Topical_DIL_Files_Updated_Access.
Referenced by Title().
383                                                   {
384         Topical_DIL_Files_Updated_Access(&(ft.title),Title(),Title)
385 }
filetitle_t * Topical_DIL_Files::Topic (int n = 0) [inline]
Definition at line 387 of file dil2al.hh.
References ft, Topic(), and Topical_DIL_Files_Updated_Access.
Referenced by Topic().
387                                                        {
388         Topical_DIL_Files_Updated_Access(&ft,Topic(),Topic)
389 }
Member Data Documentation
filetitle_t Topical_DIL_Files::ft [protected]
Definition at line 315 of file dil2al.hh.
Referenced by File(), Refresh(), Set_File(), Set_Title(), Title(), and Topic().
bool Topical_DIL_Files::updated [protected]
Definition at line 316 of file dil2al.hh.
Referenced by Invalidate(), Set_File(), Set_Title(), and Topical_DIL_Files().
The documentation for this class was generated from the following files:
dil2al.hh
diladmin.cc