dil2al.hh File Reference
#include `BigRegex.hh`
#include `BigString.hh`
#include `templates.hh`
#include <stdlib.h>
#include <stdio.h>
#include <iostream.h>
#include <stream.h>
#include <fstream.h>
#include <string.h>
#include <unistd.h>
#include <time.h>
#include <errno.h>
#include <math.h>
#include <values.h>
#include <float.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <dirent.h>
Compounds
class Active_List
class AL_Day
class AL_TC
class AL_TD
class Detailed_Items_List
class DIL_AL_List
class DIL_entry
class DIL_entry_content
class DIL_entry_parameters
class DIL_entry_Pointer
class DIL_Hierarchy_Level_Data
class DIL_ID
class DIL_Topical_List
class DIL_Visualize
class DIL_Visualize_with_FORM_Tabs
class DIL_Visualize_with_HTML_Tabs
class DIL_Visualize_with_Tabs
class Directory_Access
struct filetitle_t
class Financial_Monthly
class Financial_Monthly_Category
class Financial_Monthly_Root
class Financial_Monthly_SubCategory
class Financial_Note
class LongList
class Novelty_Marker
class Novelty_Marker_List
class Plan_entry_content
class Quick_String_Hash
class Search_Result
class Search_Target
class StringList
class Target_Access
class Text_File_Buffers
class Time
class Topical_DIL_Files
class Topical_DIL_Files_Root
Defines
#define LOOP_PROTECT
#define CAUTIOUS_OBJECT_INTERFACES
#define HITIME_T ((time_t)(1 << BITS(time_t) - 1))
#define MAXTIME_T ((time_t)(~HITIME_T))
#define SECONDSPERDAY (60*60*24)
#define DIL2AL_CONDITIONAL_ERROR_RETURN(_condition, _message) if (_condition) { EOUT << _message; return false; }
#define LONGLIST_INITIAL_VALUE -1
#define RECURSIVE_QUICK_STRING_HASH
#define Topical_DIL_Files_Updated_Access(Here, There, ThereSteps)
#define PLAN_ENTRY_TYPE_UNASSIGNED -1
#define PLAN_ENTRY_TYPE_NONE 0
#define PLAN_ENTRY_TYPE_ACTION 1
#define PLAN_ENTRY_TYPE_GOAL 2
#define PLAN_ENTRY_TYPE_OBJECTIVE 3
#define PLAN_ENTRY_TYPE_OUTCOME 4
#define PLAN_ENTRY_TYPE_VARIABLE 5
#define PLAN_OUTCOME_DESIRABILITY valuation
#define COMPLETION_STATE_OBSOLETE -1.0
#define COMPLETION_STATE_REPLACED -2.0
#define COMPLETION_STATE_DONE_DIFFERENTLY -3.0
#define COMPLETION_STATE_NO_LONGER_POSSIBLE -4.0
#define DILTOPICS_REL_UNSPECIFIED 0.0
#define DIL_Superiors DIL_AL_List
#define DILSUPS_REL_UNSPECIFIED 0.0
#define DILSUPS_UNB_UNSPECIFIED 0.0
#define DILSUPS_BND_UNSPECIFIED 0.0
#define DILSUPS_TD_UNSPECIFIED -1
#define DILSUPS_URG_UNSPECIFIED 0.0
#define DILSUPS_PRI_UNSPECIFIED 0.0
#define DILSUPS_TDPROP_FIXED 1
#define PLAN_OUTCOME_LIKELIHOOD relevance
#define TD_PROTECT 1
#define RELDIRHTML `doc/html/`
#define DILMAIN `lists.html`
#define RELLISTSDIR `lists/`
#define DILBYIDFILE `lists/detailed-items-by-ID.html`
#define OWNER `Randal A. Koene`
#define DEFAULTCHUNKSIZE 20
#define DEFAULTCHUNKSLACK 5
#define DEFAULTSECTIONSIZE 150
#define DEFAULTALTCS (3*3*12)
#define DEFAULTALFOCUSED (3*3*12)
#define DEFAULTALWIDE (12*3*12)
#define DEFAULTALGENREGULAR 8
#define DEFAULTALGENALL 13
#define DEFAULTALEPSHOURS (24.0 - 6.0 - 2.5 - 1.0 - 3.5)
#define DEFAULTALWORKDAYSTART ((time_t) 9 * (time_t) 60 * (time_t) 60)
#define DEFAULTALSYNCSLACK ((time_t) 60 * (time_t) 60)
#define DEFAULTALDAYDISTSLOPE 0.9
#define DEFAULTALCUMTIMEREQEXCERPTLENGTH 25
#define DEFAULTHIERARCHYMAXDEPTH 15
#define DEFAULTHIERARCHYEXCERPTLENGTH 50
#define DEFAULTEDITOR `nedit`
#define DEFAULTBROWSER `w3m`
#define NOTETMPFILE `tmp/dil2al-note.html`
#define TLENTRYTMPFILE `tmp/dil2al-TLentry.html`
#define CONFIGFILE `.dil2alrc`
#define TASKLOGFILE `lists/task-log.html`
#define PAPERPLANSFILE `lists/paper-plans.html`
#define FIGURESDIRECTORY `lists/figures-directory.html`
#define BIBINDEXFILE `planning/bibliography.html`
#define ARTICLEHEADTEMPLATE `lists/template.Article-Head.tex`
#define ARTICLETAILTEMPLATE `lists/template.Article-Tail.tex`
#define TEMPLATEARTICLESUBSECTION `lists/template.Article-SubSection.tex`
#define TEMPLATEARTICLESUBSUBSECTION `lists/template.Article-SubSubSection.tex`
#define DILREFFILE `tmp/dilref`
#define TAREADFILE `tmp/dil2al-TA-read.`
#define FINNOTESFILE `financial-notes.html`
#define DEFAULTUNIECMD `nc -noask -do 'revert_to_saved()' @notedst@ -do 'set_cursor_pos(@res@)' @notedst@`
#define DEFAULTFLAGCMD `xnotification \`TTC\` &`
#define DEFAULTATCOMMAND `at now`
#define DEFAULTATCONTROLLER `rxvt -display 'localhost:0.0' -e dil2al -S &`
#define DEFAULT_HTMLFORM_INTERFACE `/cgi-bin/dil2al`
#define DEFAULT_HTMLFORM_METHOD `GET`
#define MAX_RECURSIVE_PP2PD_EXTRACTION_DEPTH 7
#define DILBYID_CACHE_NUMENTRIES_SUSPICIOUS 10
#define TCS_CURRENT 0
#define TCS_NEW 1
#define TCS_ASK 2
#define TSS_CURRENT 0
#define TSS_NEW 1
#define TSS_ASK 2
#define UNIE_NO 0
#define UNIE_YES 1
#define UNIE_ASK 2
#define ACW_TIME 0
#define ACW_TL 1
#define ACW_ASK 2
#define AAU_NO 0
#define AAU_YES 1
#define AAU_ASK 2
#define ANSI_BOLD_ON `\33[1m`
#define ANSI_BOLD_OFF `\33[22m`
#define ANSI_UNDERLINE_ON `\33[4m`
#define ANSI_UNDERLINE_OFF `\33[24m`
#define DILBYID_FLOAT_FORMAT `%.4g`
#define ALDAYDISTFUNCLINEAR 0
#define ALDAYDISTFUNCSQUARED 1
#define DEFAULTALDAYEMPHASIS ` BGCOLOR=\`#3F005F\``
#define DEFAULTALFOCUSEDHEADER `<HTML>\n<HEAD>\n<TITLE>Active List - Focused: @SUP@</TITLE>\n</HEAD>\n<BODY BGCOLOR=\`#000000\` TEXT=\`#F0E0A0\` LINK=\`#AFAFFF\` VLINK=\`#7F7FFF\`>\n<H1><FONT COLOR=\`#00FF00\`>Active List - Focused: @SUP@</FONT></H1>\n\n<B>Involvement of DIL topics, I_{proj,top} in [0,1]:</B>\n<UL>\n(currently not in use)\n</UL>\n\n<B>AL Target Date:</B> @TD@ <B>General Daily Work Time:</B> @GENERAL-WORK-TIME@\n<P>\n\@PASSED@<TABLE WIDTH=\`100%\` CELLPADDING=3 BGCOLOR=\`#4F4F3F\`>\n\n`
#define DEFAULTALFOCUSEDTAIL `</TABLE>\n<P>\n\n<LI><A HREF=\`@ALFILE@.wide.html\`>Active List - Wide: @SUP@</A>\n\@CUMULATIVE@<LI><A HREF=\`../lists.html#AL\`>Active Lists</A>\n<LI><A HREF=\`../lists.html#DIL\`>Topical Detailed Items Lists</A>\n<P><HR>~/doc/<A HREF=\`../maincont.html\`>html</A>/<A HREF=\`../lists.html\`>lists</A>/@ALFILE@.html - \(generated: @ALDATE@)\n\n</BODY>\n</HTML>\n`
#define DEFAULTALFOCUSEDEMPHASIS ` BGCOLOR=\`#3F5F00\``
#define DEFAULTALWIDEHEADER `<HTML>\n<HEAD>\n<TITLE>Active List - Wide: @SUP@</TITLE>\n</HEAD>\n<BODY BGCOLOR=\`#000000\` TEXT=\`#F0E0A0\` LINK=\`#AFAFFF\` VLINK=\`#7F7FFF\`>\n<H1><FONT COLOR=\`#00FF00\`>Active List - Wide: @SUP@</FONT></H1>\n\n<OL><B>DIL Reference</B>\n`
#define DEFAULTALWIDETAIL `</OL>\n\n<P>\n<LI><A HREF=\`@ALFILE@.html\`>Active List - Focused: @SUP@</A>\n\@CUMULATIVE@<LI><A HREF=\`../lists.html#AL\`>Active Lists</A>\n<LI><A HREF=\`../lists.html#DIL\`>Topical Detailed Items Lists</A>\n<P>\n<HR>\n\~/doc/<A HREF=\`../maincont.html\`>html</A>/<A HREF=\`../lists.html\`>lists</A>/@ALFILE@.wide.html - \(generated: @ALDATE@)\n\n</BODY>\n</HTML>\n`
#define DEFAULTALCUMULATIVEREQHEADER `<HTML>\n<HEAD>\n<TITLE>Active List - Cumulative Time Required: @SUP@</TITLE>\n</HEAD>\n<BODY BGCOLOR=\`#000000\` TEXT=\`#F0E0A0\` LINK=\`#AFAFFF\` VLINK=\`#7F7FFF\`>\n<H1><FONT COLOR=\`#00FF00\`>Active List - Cumulative Time Required: @SUP@</FONT></H1>\n\n\Assumed hours available per day for the EPS method: <FONT COLOR=\`#FFFF00\`>@EPSHRS@</FONT>\n<P>\n<FORM METHOD=\`@FORMMETHOD@\` ACTION=\`@FORMACTION@\`><INPUT type=\`hidden\` name=\`dil2al\` value=\`MEtgroup\`>\n<TABLE CELLPADDING=3 BGCOLOR=\`#4F4F3F\`>\n\n<TR><TH>GRP</TH><TH>ID</TH><TH>DIL (primary)</TH><TH>Target Date</TH><TH>Treq</TH><TH>Tcum</TH><TH>Greq</TH><TH>EPS TD (chkbx=no update)</TH><TH>Excerpt</TH>\n\n`
#define DEFAULTALCUMULATIVEREQTAIL `</TABLE>\n<INPUT type=\`radio\` name=\`TDupdate\` value=\`group\` checked> Minimize fragmentation <INPUT type=\`radio\` name=\`TDupdate\` value=\`direct\`> Direct<BR>\n<INPUT type=\`submit\` value=\`Update\`> <INPUT type=\`reset\`></FORM>\n\n<P>\n<LI><A HREF=\`@ALFILE@.html\`>Active List - Focused: @SUP@</A>\n<LI><A HREF=\`@ALFILE@.wide.html\`>Active List - Wide: @SUP@</A>\n<LI><A HREF=\`../lists.html#AL\`>Active Lists</A>\n<LI><A HREF=\`../lists.html#DIL\`>Topical Detailed Items Lists</A>\n<P>\n<HR>\n\~/doc/<A HREF=\`../maincont.html\`>html</A>/<A HREF=\`../lists.html\`>lists</A>/@ALFILE@.ctr.html - \(generated: @ALDATE@)\n\n</BODY>\n</HTML>\n`
#define DIN (*din)
#define EOUT (*eout)
#define VOUT (*vout)
Typedefs
typedef unsigned long idnumber
Functions
int get_file_in_list (String &fname, StringList &srcf, StringList &srcfname, int &srcfnum)
void Set_Parameter (char *lbuf)
String generate_tag (String &tagid)
bool Diagnostic (String diagnosticstr)
int DIL_entry_target_date_qsort_compare (const void *vde1, const void *vde2)
int BigRegex_freq (String &str, const BigRegex &rx)
int BigRegex_freq (String &str, String rxstr)
int BigRegex_freq (String &str, const char *rxstr)
String RX_Search_Safe (String s)
time_t Time (time_t *tloc)
String time_stamp (const char *dateformat, time_t t=-1)
String time_stamp_GM (const char *dateformat, time_t t=-1)
String date_string ()
time_t time_stamp_time (String timestr)
time_t time_stamp_time_of_day (String timestr)
time_t time_stamp_time_date (String timestr)
time_t time_stamp_diff (String oldtime, String newtime)
time_t double2time (double t)
bool confirmation (String message, char nondefault)
void auto_interactive (String &autostr, String message, char *lbuf, int llen)
String relurl (String srcurl, String dsturl)
String absurl (String srcurl, String relurl)
bool file_is_regular (String filepath)
bool file_is_regular_or_symlink (String filepath)
bool file_is_directory (String filepath)
bool prepare_temporary_file (String tmpfile, String initstr)
bool backup_and_rename (String filename, String message, bool isnew=false)
bool read_file_into_String (ifstream &sfl, String &filestr, bool warnnoopen=true)
bool read_file_into_String (String filename, String &filestr, bool warnnoopen=true)
bool read_file_into_String (bool &isnew, String filename, String &filestr)
bool write_file_from_String (String filename, const String &filestr, String message, bool isnew=false)
void read_data_from_stream (istream &ifs, String &dstr, const char *terminate)
bool Lock_File (String lockfile, String msgstr)
bool Unlock_File (String lockfile)
int find_delimiter (String &str, int startpos, int lenlimit, char delimiter='\n')
bool pattern_in_line (const char *pattern, char *lbuf)
bool substring_from_line (const char *pattern, int nsub, String *dilid, const char *lbuf)
bool find_line (ifstream *lf, const char *pattern, char *lbuf, int llen)
int copy_until_line (ifstream *lf, ofstream *of, const char *pattern, char *lbuf, int llen)
int find_in_line (ifstream *lf, const char *pattern, int nsub, String *dilid, const char *before, char *lbuf, int llen)
bool initialize_new_DIL_TL (String initializecmd, bool includeinput)
int D2A_get_tag (String &d2astr, int strloc, String d2atag, String &tagtext)
int HTML_get_marker (String &htmlstr, int strloc, String &marker, bool locate=true)
String HTML_marker_arguments (String &marker)
int HTML_get_tagged_environment (const BigRegex &begintag, const BigRegex &endmatch, const BigRegex &endtag, String &htmlstr, int strloc, String &envparams, String &envcontent, int *envstart=NULL)
int HTML_get_table_cell (String &htmlstr, int strloc, String &cellparams, String &cellcontent, int *cellstart=NULL)
int HTML_get_table_row (String &htmlstr, int strloc, String &rowparams, String &rowcontent, int *rowstart=NULL)
int HTML_get_list (String &htmlstr, int strloc, String &listparams, String &listcontent, int *liststart=NULL)
int HTML_get_list_item (String &htmlstr, int strloc, String &itemparams, String &itemcontent, int *itemstart=NULL)
int HTML_get_href (String &htmlstr, int strloc, String &hrefurl, String &hreftext, int *hrefstart=NULL)
int HTML_get_name (String &htmlstr, int strloc, String &nametag, String &nametext)
String * HTML_safe (String &textstr)
String * HTML_remove_comments (String &htmlstr)
String * HTML_remove_tags (String &htmlstr)
String HTML_put_structure (String tag, String params, String content, bool relaxedhtml=false)
String HTML_put_table_row (String rowparams, String rowcontent, bool relaxedhtml=false)
String HTML_put_table_cell (String cellparams, String cellcontent, bool relaxedhtml=false)
String HTML_put_list (char listtype, String htmlstr)
String HTML_put_list_item (String htmlstr, bool relaxedhtml=false)
String HTML_put_href (String hrefurl, String hreftext)
String HTML_put_name (String nametag, String nametext)
String HTML_put_form (String formmethod, String formaction, String formcontent)
String HTML_put_form_input (String inputtype, String inputargs)
String HTML_put_form_submit (String submittext)
String HTML_put_form_reset ()
String HTML_put_form_radio (String radioname, String radiovalue, String radiotext, bool checked=false)
String HTML_put_form_checkbox (String checkboxname, String checkboxvalue, String checkboxtext, bool checked=false)
String HTML_put_form_text (String textname, String textvalue, long maxlen=-1)
String HTML_put_form_text (String textname, long maxlen=-1)
int Elipsis_At (String &s, int maxsize)
String URI_unescape (String escapedURI)
String Int2HexStr (unsigned int i)
String * remove_whitespace (String &str)
double get_double (String valstr, double defval=0.0, bool *gotdouble=NULL)
int get_topic_keywords ()
String generate_AL_full_entry (String dilid, int chunkfreq)
String generate_AL_entry (String dilid, bool ishighestpriority=false)
String AL_Day_Marker (String &dstfile, AL_Day *ald)
String AL_Passed_Target_Dates (String &dstfile, AL_TD *atd)
bool update_main_ALs (DIL_entry *superior)
float linear_distribution (float i, float i_limit)
long * DIL_Required_Task_Chunks (DIL_entry **dep, int deplen)
void Get_Worked_Estimate ()
float linear_day_distribution (AL_Day *ald, time_t td)
bool generate_AL (DIL_entry **dep, DIL_entry *superior=NULL)
int get_AL_entry (String &alstr, int alpos, String &rowcontent, int &rowstart, int &rowend)
bool remove_AL_TC (String alref, String dilid)
bool update_DIL_to_AL ()
bool refresh_quick_load_cache ()
bool get_active_DIL_IDs (StringList &idfileids, unsigned long *resnumidfileids=NULL)
bool add_new_to_DIL (String dilfile, StringList *supinfoptr)
bool create_new_DIL (String dilfile)
bool send_dil_to_DIL (String dilfile)
String get_new_DIL_ID ()
bool generate_modify_element_FORM_interface (StringList *qlist=NULL)
bool modify_element_through_FORM_interface (StringList *qlist=NULL)
bool update_DIL_entry_elements (String dilid, double valuation, bool updateval, double completion, bool updatecomp, double required, bool updatereq, time_t tdiff=-1)
bool update_DIL_entry_parameter_elements (Detailed_Items_List &dilist, DIL_ID dilid, PLLRoot< DIL_Superiors > &addsups, StringList *removesups, int removesupsnum)
bool modify_DIL_entry_target_date (DIL_ID dilid, time_t tdate, Detailed_Items_List &dilist)
bool modify_DIL_entry_target_date (DIL_ID dilid, time_t tdate)
bool modify_DIL_group_target_dates (Detailed_Items_List &dilgroup, bool minfragmentation=true)
bool modify_DIL_group_target_dates_cmd (bool minfragmentation, StringList *qlist=NULL)
bool extract_DIL_IDs_from_form (StringList *qlist=NULL)
void Show_DIL_Hierarchy (DIL_entry *topde, DIL_Visualize &dv, const int maxdepth, int depth=0, double likelihood=DILSUPS_REL_UNSPECIFIED)
String Tabbed_DIL_Hierarchy (String dilidstr, int maxdepth=50)
String Tabbed_HTML_DIL_Hierarchy (String dilidstr, int maxdepth=50)
String Tabbed_FORM_DIL_Hierarchy (String dilidstr, int maxdepth=50)
bool DIL_Hierarchy_cmd (String dilidstr, int maxdepth=50)
String get_TL_head ()
int max_chunk_entry (String &tlchunk)
String generate_TL_chunk_header (String nametag, String newalref, String altitle, String alhead, String newdilref, String diltitle, String dilhead, int generateparts=0)
String generate_TL_entry_header (String nametag, String newalref, String altitle, String alhead, String newdilref, String diltitle, String dilhead)
String get_most_recent_TC_AL (String &tl)
String get_most_recent_TC_DE (String &tl)
void stop_TL_chunk (String &tl)
String select_TL_DIL_refs (String &tl, bool newchunk, String newalref)
String select_TL_AL_refs (String &tl, bool newchunk, String newdilref)
String add_TL_chunk_or_entry (String &tl, String &notestr, bool newchunk, String chunkid, int &tlinsertloc)
bool add_TL_section (String &tl)
int locate_most_recent_TL_chunk (String &tl, int seekfrom, String *chunkid)
String decide_add_TL_chunk (String &tl, int &tlinsertloc, bool comparetimes, bool createifgreater=true)
void process_HTML (String &notestr)
int pre_process_note (String notefile, String notedst, String typestr, String &notestr, String &notedststr, bool &isnew)
int post_process_note (String notedst, String &notestr, String &notedststr, int insertindex, bool isnew)
int process_note_TL (String notefile, String notedst)
int process_note_HTML (String notefile, String notedst)
int process_note_TeX (String notefile, String notedst)
int process_note_CC (String notefile, String notedst)
int process_note_generic (String notefile, String notedst)
bool process_note (String notefile, String notedst)
bool make_note ()
String chunk_controller (String controllercmd)
time_t time_chunk_remaining (String chunkid)
bool schedule_controller (String controllercmd)
bool filter_TL_by_AL ()
bool generate_TL_keyword_index ()
bool search_TL (String searchstr)
bool extract_paper_novelties (String fname, String paperplanurl, ostream &ostr)
bool cmdline_extract_paper_novelties (String filepaper)
String generate_Figures_Directory_entry (String figid)
void get_figure_data (String &figfile, String &figlabel, String &figcaption, String &figintext, String &psconversions, StringList &srcf, StringList &srcfname, int &srcfnum)
bool get_Paper_Plans_Section_IDs (StringList &ppsectionids, StringList &ppsectiontitles, StringList &ppsectiontemplates)
int TeX_get_scope (String &textstr, int start, String &scopecontent)
int TeX_get_argument (String &textstr, int start, String &argstr, char argtype, int *argstart=NULL)
int TeX_get_command (String &textstr, int start, String &cmdstr)
String TeX_safe_text (String &title)
void TeX_format_corrections (String &ostrtext, bool estimate=false)
int Text_find_line_end (String &textstr, int start, char lend='\n')
void Text_limit_line_length (String &textstr, int optlinemax, int abslinemax, char lend='\n')
void convert_item_content_to_TeX (String &itemcontent)
void unconvert_item_content_from_TeX (String &itemcontent)
bool extract_paper_plan_to_paper (String ppname, String pout, String pprevious)
bool cmdline_extract_paper_plan_to_paper (String ppfile)
bool Quantitative_Assessment (char qatype, String ppfile)
String search (StringList &targets, String searchkey, bool stringoutput=true)
unsigned long Get_Target_Directory (StringList &targets, unsigned long i, String dirpath)
unsigned long Get_Target_Regex (StringList &targets, unsigned long i, String dirpath)
bool search_cmd (String grepinfo)
bool search_FORM_cmd (StringList *qlist=NULL)
bool read_financial_notes_file (PLLRoot< Financial_Note > &fnotes, String &finnotestop, String &finnotesend)
bool write_financial_notes_file (PLLRoot< Financial_Note > &fnotes, String &finnotestop, String &finnotesend)
bool financial_notes ()
bool financial_monthly ()
Variables
String homedir
String basedir
String listfile
String idfile
String lockidfile
String crcidfile
String cacheidfile
String tasklog
String taskloghead
String paperplansfile
String figuresdirectory
String dilref
String bibindexfilename
String bibindexfile
String articleheadtemplate
String articletailtemplate
String templatearticlesubsection
String templatearticlesubsubsection
ifstream dinfile
istream * din
ofstream eoutfile
ostream * eout
ostream * vout
int numDILs
Topical_DIL_Files_Root dil
bool verbose
bool suggestnameref
bool askprocesstype
bool offercreate
bool askALDILref
bool showflag
bool isdaemon
bool useansi
bool askextractconcat
bool usequickloadcache
time_t emulatedtime
String curdate
String curtime
String owner
int timechunksize
int timechunkslack
int timechunkoverstrategy
int timechunkunderstrategy
int sectionsize
int sectionstrategy
long generatealtcs
time_t generatealmaxt
int alfocused
int alwide
int algenregular
int algenall
float alepshours
bool alautoexpand
bool alshowcumulativereq
int alcumtimereqexcerptlength
bool rapidscheduleupdating
bool targetdatepreferences
bool weekdayworkendpreferences
time_t wdworkendprefs [7]
time_t alworkdaystart
int alcurdayworkedstrategy
time_t alworked
int alautoupdate
time_t alsyncslack
int aldaydistfunc
float aldaydistslope
bool reversehierarchy
bool hierarchyplanparse
int hierarchymaxdepth
int hierarchyexcerptlength
String updatenoteineditorcmd
int updatenoteineditor
String atcommand
String atcontroller
String htmlforminterface
String htmlformmethod
String editor
String browser
String flagcmd
String notetmpfile
String tlentrytmpfile
String configfile
String tareadfile
String finnotesfile
bool calledbyforminput
int followlinks
bool searchprogressmeter
bool immediatesearchoutput
bool remotesearch
StringList quicknotedst
StringList quicknotedsttitle
StringList quicknotedescr
int quicknotedstnum
StringList indexkeys
int indexkeysnum
String newTLID
bool chunkcreated
Detailed_Items_List * looplist
Define Documentation
#define AAU_ASK 2
Definition at line 1242 of file dil2al.hh.
Referenced by dil2al_commands(), select_TL_DIL_refs(), Set_Parameter(), and stop_TL_chunk().
#define AAU_NO 0
Definition at line 1240 of file dil2al.hh.
Referenced by dil2al_commands(), select_TL_DIL_refs(), Set_Parameter(), and stop_TL_chunk().
#define AAU_YES 1
Definition at line 1241 of file dil2al.hh.
Referenced by dil2al_commands(), and Set_Parameter().
#define ACW_ASK 2
Definition at line 1238 of file dil2al.hh.
Referenced by Get_Worked_Estimate(), and Set_Parameter().
#define ACW_TIME 0
Definition at line 1236 of file dil2al.hh.
Referenced by Get_Worked_Estimate(), and Set_Parameter().
#define ACW_TL 1
Definition at line 1237 of file dil2al.hh.
Referenced by Get_Worked_Estimate(), and Set_Parameter().
#define ALDAYDISTFUNCLINEAR 0
Definition at line 1251 of file dil2al.hh.
Referenced by Set_Parameter().
#define ALDAYDISTFUNCSQUARED 1
Definition at line 1252 of file dil2al.hh.
Referenced by Active_List::expand(), and Set_Parameter().
#define ANSI_BOLD_OFF `\33[22m`
Definition at line 1245 of file dil2al.hh.
Referenced by chunk_controller(), decide_add_TL_chunk(), make_note(), modify_DIL_group_target_dates_cmd(), select_TL_AL_refs(), and select_TL_DIL_refs().
#define ANSI_BOLD_ON `\33[1m`
Definition at line 1244 of file dil2al.hh.
Referenced by chunk_controller(), decide_add_TL_chunk(), make_note(), modify_DIL_group_target_dates_cmd(), select_TL_AL_refs(), and select_TL_DIL_refs().
#define ANSI_UNDERLINE_OFF `\33[24m`
Definition at line 1247 of file dil2al.hh.
Referenced by make_note(), modify_DIL_group_target_dates_cmd(), select_TL_AL_refs(), and select_TL_DIL_refs().
#define ANSI_UNDERLINE_ON `\33[4m`
Definition at line 1246 of file dil2al.hh.
Referenced by make_note(), modify_DIL_group_target_dates_cmd(), select_TL_AL_refs(), and select_TL_DIL_refs().
#define ARTICLEHEADTEMPLATE `lists/template.Article-Head.tex`
Definition at line 1208 of file dil2al.hh.
#define ARTICLETAILTEMPLATE `lists/template.Article-Tail.tex`
Definition at line 1209 of file dil2al.hh.
#define BIBINDEXFILE `planning/bibliography.html`
Definition at line 1207 of file dil2al.hh.
#define CAUTIOUS_OBJECT_INTERFACES
Definition at line 51 of file dil2al.hh.
#define COMPLETION_STATE_DONE_DIFFERENTLY -3.0
Definition at line 490 of file dil2al.hh.
#define COMPLETION_STATE_NO_LONGER_POSSIBLE -4.0
Definition at line 491 of file dil2al.hh.
#define COMPLETION_STATE_OBSOLETE -1.0
Definition at line 488 of file dil2al.hh.
#define COMPLETION_STATE_REPLACED -2.0
Definition at line 489 of file dil2al.hh.
#define CONFIGFILE `.dil2alrc`
Definition at line 1203 of file dil2al.hh.
#define DEFAULT_HTMLFORM_INTERFACE `/cgi-bin/dil2al`
Definition at line 1219 of file dil2al.hh.
#define DEFAULT_HTMLFORM_METHOD `GET`
Definition at line 1220 of file dil2al.hh.
#define DEFAULTALCUMTIMEREQEXCERPTLENGTH 25
Definition at line 1196 of file dil2al.hh.
#define DEFAULTALCUMULATIVEREQHEADER `<HTML>\n<HEAD>\n<TITLE>Active List - Cumulative Time Required: @SUP@</TITLE>\n</HEAD>\n<BODY BGCOLOR=\`#000000\` TEXT=\`#F0E0A0\` LINK=\`#AFAFFF\` VLINK=\`#7F7FFF\`>\n<H1><FONT COLOR=\`#00FF00\`>Active List - Cumulative Time Required: @SUP@</FONT></H1>\n\n\Assumed hours available per day for the EPS method: <FONT COLOR=\`#FFFF00\`>@EPSHRS@</FONT>\n<P>\n<FORM METHOD=\`@FORMMETHOD@\` ACTION=\`@FORMACTION@\`><INPUT type=\`hidden\` name=\`dil2al\` value=\`MEtgroup\`>\n<TABLE CELLPADDING=3 BGCOLOR=\`#4F4F3F\`>\n\n<TR><TH>GRP</TH><TH>ID</TH><TH>DIL (primary)</TH><TH>Target Date</TH><TH>Treq</TH><TH>Tcum</TH><TH>Greq</TH><TH>EPS TD (chkbx=no update)</TH><TH>Excerpt</TH>\n\n`
Definition at line 1291 of file dil2al.hh.
Referenced by generate_AL().
#define DEFAULTALCUMULATIVEREQTAIL `</TABLE>\n<INPUT type=\`radio\` name=\`TDupdate\` value=\`group\` checked> Minimize fragmentation <INPUT type=\`radio\` name=\`TDupdate\` value=\`direct\`> Direct<BR>\n<INPUT type=\`submit\` value=\`Update\`> <INPUT type=\`reset\`></FORM>\n\n<P>\n<LI><A HREF=\`@ALFILE@.html\`>Active List - Focused: @SUP@</A>\n<LI><A HREF=\`@ALFILE@.wide.html\`>Active List - Wide: @SUP@</A>\n<LI><A HREF=\`../lists.html#AL\`>Active Lists</A>\n<LI><A HREF=\`../lists.html#DIL\`>Topical Detailed Items Lists</A>\n<P>\n<HR>\n\~/doc/<A HREF=\`../maincont.html\`>html</A>/<A HREF=\`../lists.html\`>lists</A>/@ALFILE@.ctr.html - \(generated: @ALDATE@)\n\n</BODY>\n</HTML>\n`
Definition at line 1299 of file dil2al.hh.
Referenced by generate_AL().
#define DEFAULTALDAYDISTSLOPE 0.9
Definition at line 1195 of file dil2al.hh.
#define DEFAULTALDAYEMPHASIS ` BGCOLOR=\`#3F005F\``
Definition at line 1254 of file dil2al.hh.
Referenced by AL_Day_Marker(), and remove_AL_TC().
#define DEFAULTALEPSHOURS (24.0 - 6.0 - 2.5 - 1.0 - 3.5)
Definition at line 1192 of file dil2al.hh.
#define DEFAULTALFOCUSED (3*3*12)
Definition at line 1188 of file dil2al.hh.
#define DEFAULTALFOCUSEDEMPHASIS ` BGCOLOR=\`#3F5F00\``
Definition at line 1273 of file dil2al.hh.
Referenced by Active_List::generate_focused_AL(), and remove_AL_TC().
#define DEFAULTALFOCUSEDHEADER `<HTML>\n<HEAD>\n<TITLE>Active List - Focused: @SUP@</TITLE>\n</HEAD>\n<BODY BGCOLOR=\`#000000\` TEXT=\`#F0E0A0\` LINK=\`#AFAFFF\` VLINK=\`#7F7FFF\`>\n<H1><FONT COLOR=\`#00FF00\`>Active List - Focused: @SUP@</FONT></H1>\n\n<B>Involvement of DIL topics, I_{proj,top} in [0,1]:</B>\n<UL>\n(currently not in use)\n</UL>\n\n<B>AL Target Date:</B> @TD@ <B>General Daily Work Time:</B> @GENERAL-WORK-TIME@\n<P>\n\@PASSED@<TABLE WIDTH=\`100%\` CELLPADDING=3 BGCOLOR=\`#4F4F3F\`>\n\n`
Definition at line 1256 of file dil2al.hh.
Referenced by Active_List::generate_focused_AL().
#define DEFAULTALFOCUSEDTAIL `</TABLE>\n<P>\n\n<LI><A HREF=\`@ALFILE@.wide.html\`>Active List - Wide: @SUP@</A>\n\@CUMULATIVE@<LI><A HREF=\`../lists.html#AL\`>Active Lists</A>\n<LI><A HREF=\`../lists.html#DIL\`>Topical Detailed Items Lists</A>\n<P><HR>~/doc/<A HREF=\`../maincont.html\`>html</A>/<A HREF=\`../lists.html\`>lists</A>/@ALFILE@.html - \(generated: @ALDATE@)\n\n</BODY>\n</HTML>\n`
Definition at line 1265 of file dil2al.hh.
Referenced by Active_List::generate_focused_AL().
#define DEFAULTALGENALL 13
Definition at line 1191 of file dil2al.hh.
#define DEFAULTALGENREGULAR 8
Definition at line 1190 of file dil2al.hh.
#define DEFAULTALSYNCSLACK ((time_t) 60 * (time_t) 60)
Definition at line 1194 of file dil2al.hh.
#define DEFAULTALTCS (3*3*12)
Definition at line 1187 of file dil2al.hh.
#define DEFAULTALWIDE (12*3*12)
Definition at line 1189 of file dil2al.hh.
#define DEFAULTALWIDEHEADER `<HTML>\n<HEAD>\n<TITLE>Active List - Wide: @SUP@</TITLE>\n</HEAD>\n<BODY BGCOLOR=\`#000000\` TEXT=\`#F0E0A0\` LINK=\`#AFAFFF\` VLINK=\`#7F7FFF\`>\n<H1><FONT COLOR=\`#00FF00\`>Active List - Wide: @SUP@</FONT></H1>\n\n<OL><B>DIL Reference</B>\n`
Definition at line 1275 of file dil2al.hh.
Referenced by Active_List::generate_wide_AL().
#define DEFAULTALWIDETAIL `</OL>\n\n<P>\n<LI><A HREF=\`@ALFILE@.html\`>Active List - Focused: @SUP@</A>\n\@CUMULATIVE@<LI><A HREF=\`../lists.html#AL\`>Active Lists</A>\n<LI><A HREF=\`../lists.html#DIL\`>Topical Detailed Items Lists</A>\n<P>\n<HR>\n\~/doc/<A HREF=\`../maincont.html\`>html</A>/<A HREF=\`../lists.html\`>lists</A>/@ALFILE@.wide.html - \(generated: @ALDATE@)\n\n</BODY>\n</HTML>\n`
Definition at line 1280 of file dil2al.hh.
Referenced by Active_List::generate_wide_AL().
#define DEFAULTALWORKDAYSTART ((time_t) 9 * (time_t) 60 * (time_t) 60)
Definition at line 1193 of file dil2al.hh.
#define DEFAULTATCOMMAND `at now`
Definition at line 1217 of file dil2al.hh.
#define DEFAULTATCONTROLLER `rxvt -display 'localhost:0.0' -e dil2al -S &`
Definition at line 1218 of file dil2al.hh.
#define DEFAULTBROWSER `w3m`
Definition at line 1200 of file dil2al.hh.
#define DEFAULTCHUNKSIZE 20
Definition at line 1184 of file dil2al.hh.
#define DEFAULTCHUNKSLACK 5
Definition at line 1185 of file dil2al.hh.
#define DEFAULTEDITOR `nedit`
Definition at line 1199 of file dil2al.hh.
#define DEFAULTFLAGCMD `xnotification \`TTC\` &`
Definition at line 1216 of file dil2al.hh.
#define DEFAULTHIERARCHYEXCERPTLENGTH 50
Definition at line 1198 of file dil2al.hh.
#define DEFAULTHIERARCHYMAXDEPTH 15
Definition at line 1197 of file dil2al.hh.
#define DEFAULTSECTIONSIZE 150
Definition at line 1186 of file dil2al.hh.
#define DEFAULTUNIECMD `nc -noask -do 'revert_to_saved()' @notedst@ -do 'set_cursor_pos(@res@)' @notedst@`
Definition at line 1215 of file dil2al.hh.
#define DIL2AL_CONDITIONAL_ERROR_RETURN(_condition, _message) if (_condition) { EOUT << _message; return false; }
Definition at line 71 of file dil2al.hh.
Referenced by modify_element_through_FORM_interface(), and search_FORM_cmd().
#define DIL_Superiors DIL_AL_List
Definition at line 547 of file dil2al.hh.
Referenced by generate_modify_element_FORM_interface_DIL_entry_parameters(), generate_modify_element_FORM_interface_DIL_Superiors(), modify_DIL_group_target_dates(), modify_element_through_FORM_interface(), modify_element_through_FORM_interface_DIL_Superiors(), and update_DIL_entry_parameter_elements().
#define DILBYID_CACHE_NUMENTRIES_SUSPICIOUS 10
Definition at line 1222 of file dil2al.hh.
Referenced by Detailed_Items_List::Read_from_Binary_Cache().
#define DILBYID_FLOAT_FORMAT `%.4g`
Definition at line 1249 of file dil2al.hh.
Referenced by Detailed_Items_List::Write_to_File().
#define DILBYIDFILE `lists/detailed-items-by-ID.html`
Definition at line 1181 of file dil2al.hh.
#define DILMAIN `lists.html`
Definition at line 1179 of file dil2al.hh.
#define DILREFFILE `tmp/dilref`
Definition at line 1212 of file dil2al.hh.
#define DILSUPS_BND_UNSPECIFIED 0.0
Definition at line 553 of file dil2al.hh.
Referenced by DIL_AL_List::DIL_AL_List(), modify_DIL_entry_target_date(), modify_DIL_group_target_dates(), modify_DIL_group_target_dates_cmd(), and Detailed_Items_List::Write_to_File().
#define DILSUPS_PRI_UNSPECIFIED 0.0
Definition at line 556 of file dil2al.hh.
Referenced by DIL_AL_List::DIL_AL_List(), modify_DIL_entry_target_date(), modify_DIL_group_target_dates(), modify_DIL_group_target_dates_cmd(), and Detailed_Items_List::Write_to_File().
#define DILSUPS_REL_UNSPECIFIED 0.0
Definition at line 551 of file dil2al.hh.
Referenced by DIL_AL_List::DIL_AL_List(), DIL_Hierarchy_Level_Data::DIL_Hierarchy_Level_Data(), modify_DIL_entry_target_date(), modify_DIL_group_target_dates(), modify_DIL_group_target_dates_cmd(), Show_DIL_Hierarchy(), DIL_Visualize_with_FORM_Tabs::Visualize_Plan_Entry(), and Detailed_Items_List::Write_to_File().
#define DILSUPS_TD_UNSPECIFIED -1
Definition at line 554 of file dil2al.hh.
Referenced by DIL_AL_List::DIL_AL_List(), generate_modify_element_FORM_interface_DIL_Superiors(), and Detailed_Items_List::Write_to_File().
#define DILSUPS_TDPROP_FIXED 1
Definition at line 557 of file dil2al.hh.
Referenced by generate_modify_element_FORM_interface_DIL_Superiors(), Detailed_Items_List::Get_Project_Data(), modify_element_through_FORM_interface_DIL_Superiors(), DIL_AL_List::set_targetdate(), and Detailed_Items_List::Write_to_File().
#define DILSUPS_UNB_UNSPECIFIED 0.0
Definition at line 552 of file dil2al.hh.
Referenced by DIL_AL_List::DIL_AL_List(), modify_DIL_entry_target_date(), modify_DIL_group_target_dates(), modify_DIL_group_target_dates_cmd(), and Detailed_Items_List::Write_to_File().
#define DILSUPS_URG_UNSPECIFIED 0.0
Definition at line 555 of file dil2al.hh.
Referenced by DIL_AL_List::DIL_AL_List(), modify_DIL_entry_target_date(), modify_DIL_group_target_dates(), modify_DIL_group_target_dates_cmd(), and Detailed_Items_List::Write_to_File().
#define DILTOPICS_REL_UNSPECIFIED 0.0
Definition at line 521 of file dil2al.hh.
Referenced by Detailed_Items_List::Write_to_File().
#define DIN (*din)
Definition at line 1405 of file dil2al.hh.
Referenced by Detect_Form_Input(), dil2al_commands(), initialize_new_DIL_TL(), modify_DIL_group_target_dates_cmd(), and send_dil_to_DIL().
#define EOUT (*eout)
Definition at line 1406 of file dil2al.hh.
Referenced by Active_List::Add_Day(), add_new_to_DIL(), add_TL_chunk_or_entry(), add_TL_section(), AL_TC::allocate_with_value(), AL_Day::available_before(), backup_and_rename(), Detailed_Items_List::Binary_Cache_Diagnostic(), chunk_controller(), clean_paper_outline(), cmdline_extract_paper_novelties(), cmdline_extract_paper_plan_to_paper(), convert_item_content_to_TeX(), copy_until_line(), create_new_DIL(), D2A_get_tag(), decide_add_TL_chunk(), dil2al_commands(), DIL_Required_Task_Chunks(), AL_Day::expand(), extract_hierarchy_depth_decrease_to_paper(), extract_hierarchy_depth_increase_to_paper(), extract_novelty_item_to_paper(), extract_paper_novelties(), extract_paper_plan_to_paper(), extract_recursively(), extract_required_item_to_paper(), file_is_directory(), file_is_regular(), file_is_regular_or_symlink(), find_in_line(), find_line(), formalizer_commands(), generate_AL(), generate_AL_entry(), Active_List::generate_focused_AL(), Active_List::generate_wide_AL(), get_active_DIL_IDs(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), Detailed_Items_List::Get_All_Topical_DIL_Parameters(), get_figure_data(), get_file_in_list(), get_new_DIL_ID(), Novelty_Marker::Get_Novelty_from_Paper_Plan(), get_Paper_Plans_Section_IDs(), Get_Target_Directory(), Get_Target_Regex(), get_TL_head(), get_topic_keywords(), Get_Worked_Estimate(), HTML_get_href(), HTML_get_name(), include_article_head_template(), include_article_section_head_template(), include_article_section_tail_template(), include_article_tail_template(), include_protected_text(), Active_List::Initialize_AL_Length(), initialize_new_DIL_TL(), DIL_entry::Is_Dependency_Of(), DIL_entry::Is_Plan_Entry(), DIL_entry_content::Is_Plan_Entry(), locate_most_recent_TL_chunk(), Lock_File(), Target_Access::make_local_copy(), make_note(), modify_DIL_entry_target_date(), modify_DIL_group_target_dates(), Modify_Element(), pattern_in_line(), prepare_temporary_file(), process_HTML(), process_note(), process_note_HTML(), process_note_TeX(), process_note_TL(), Quantitative_Assessment(), read_file_into_String(), read_financial_notes_file(), Detailed_Items_List::Read_from_Binary_Cache(), Detailed_Items_List::Read_Topical_from_Binary_Cache(), Topical_DIL_Files::Refresh(), refresh_quick_load_cache(), remove_AL_TC(), schedule_controller(), Search_Target::search(), search_cmd(), select_TL_AL_refs(), select_TL_DIL_refs(), send_dil_to_DIL(), AL_Day::set_avail(), Target_Access::set_target(), AL_Day::set_TC_values(), Show_DIL_Hierarchy(), Detailed_Items_List::Sort_by_Target_Date(), stop_TL_chunk(), substring_from_line(), Target_Access::syscommand(), Tabbed_DIL_Hierarchy(), Tabbed_FORM_DIL_Hierarchy(), Tabbed_HTML_DIL_Hierarchy(), Text_limit_line_length(), Unlock_File(), update_DIL_entry_elements(), update_DIL_entry_parameter_elements(), update_main_ALs(), write_file_from_String(), Detailed_Items_List::Write_to_Binary_Cache(), Detailed_Items_List::Write_to_File(), and Detailed_Items_List::Write_Topical_to_Binary_Cache().
#define FIGURESDIRECTORY `lists/figures-directory.html`
Definition at line 1206 of file dil2al.hh.
#define FINNOTESFILE `financial-notes.html`
Definition at line 1214 of file dil2al.hh.
#define HITIME_T ((time_t)(1 << BITS(time_t) - 1))
Definition at line 66 of file dil2al.hh.
#define LONGLIST_INITIAL_VALUE -1
Definition at line 130 of file dil2al.hh.
Referenced by LongList::LongList().
#define LOOP_PROTECT
Definition at line 50 of file dil2al.hh.
#define MAX_RECURSIVE_PP2PD_EXTRACTION_DEPTH 7
Definition at line 1221 of file dil2al.hh.
Referenced by extract_recursively().
#define MAXTIME_T ((time_t)(~HITIME_T))
Definition at line 68 of file dil2al.hh.
Referenced by AL_Day::add_TCs(), DIL_entry_target_date_qsort_compare(), and DIL_entry::Propagated_Target_Date().
#define NOTETMPFILE `tmp/dil2al-note.html`
Definition at line 1201 of file dil2al.hh.
#define OWNER `Randal A. Koene`
Definition at line 1182 of file dil2al.hh.
#define PAPERPLANSFILE `lists/paper-plans.html`
Definition at line 1205 of file dil2al.hh.
#define PLAN_ENTRY_TYPE_ACTION 1
Definition at line 482 of file dil2al.hh.
Referenced by DIL_Visualize_with_FORM_Tabs::Visualize_Plan_Entry().
#define PLAN_ENTRY_TYPE_GOAL 2
Definition at line 483 of file dil2al.hh.
Referenced by Plan_entry_content::Parse_Entry_Content(), and DIL_Visualize_with_FORM_Tabs::Visualize_Plan_Entry().
#define PLAN_ENTRY_TYPE_NONE 0
Definition at line 481 of file dil2al.hh.
Referenced by DIL_entry_content::Is_Plan_Entry().
#define PLAN_ENTRY_TYPE_OBJECTIVE 3
Definition at line 484 of file dil2al.hh.
#define PLAN_ENTRY_TYPE_OUTCOME 4
Definition at line 485 of file dil2al.hh.
Referenced by generate_modify_element_FORM_interface_DIL_entry_content(), and generate_modify_element_FORM_interface_DIL_entry_parameters().
#define PLAN_ENTRY_TYPE_UNASSIGNED -1
Definition at line 480 of file dil2al.hh.
Referenced by DIL_entry_content::DIL_entry_content(), DIL_entry::Is_Plan_Entry(), and DIL_entry_content::Is_Plan_Entry().
#define PLAN_ENTRY_TYPE_VARIABLE 5
Definition at line 486 of file dil2al.hh.
#define PLAN_OUTCOME_DESIRABILITY valuation
Definition at line 487 of file dil2al.hh.
#define PLAN_OUTCOME_LIKELIHOOD relevance
Definition at line 558 of file dil2al.hh.
#define RECURSIVE_QUICK_STRING_HASH
Definition at line 162 of file dil2al.hh.
#define RELDIRHTML `doc/html/`
Definition at line 1178 of file dil2al.hh.
#define RELLISTSDIR `lists/`
Definition at line 1180 of file dil2al.hh.
Referenced by add_new_to_DIL(), add_TL_chunk_or_entry(), add_TL_section(), create_new_DIL(), generate_AL(), generate_AL_entry(), Active_List::generate_focused_AL(), generate_modify_element_FORM_interface_DIL_entry_content(), Active_List::generate_wide_AL(), get_most_recent_TC_AL(), select_TL_AL_refs(), select_TL_DIL_refs(), send_dil_to_DIL(), and update_main_ALs().
#define SECONDSPERDAY (60*60*24)
Definition at line 69 of file dil2al.hh.
Referenced by Active_List::Add_Day(), AL_Day::Add_Target_Date(), AL_Day::AL_Day(), generate_EPS_cells(), Active_List::Initialize_AL_Length(), and remove_AL_TC().
#define TAREADFILE `tmp/dil2al-TA-read.`
Definition at line 1213 of file dil2al.hh.
#define TASKLOGFILE `lists/task-log.html`
Definition at line 1204 of file dil2al.hh.
#define TCS_ASK 2
Definition at line 1226 of file dil2al.hh.
Referenced by decide_add_TL_chunk(), and Set_Parameter().
#define TCS_CURRENT 0
Definition at line 1224 of file dil2al.hh.
Referenced by decide_add_TL_chunk(), and Set_Parameter().
#define TCS_NEW 1
Definition at line 1225 of file dil2al.hh.
Referenced by decide_add_TL_chunk(), and Set_Parameter().
#define TD_PROTECT 1
Definition at line 650 of file dil2al.hh.
Referenced by DIL_entry::Propagated_Target_Date().
#define TEMPLATEARTICLESUBSECTION `lists/template.Article-SubSection.tex`
Definition at line 1210 of file dil2al.hh.
#define TEMPLATEARTICLESUBSUBSECTION `lists/template.Article-SubSubSection.tex`
Definition at line 1211 of file dil2al.hh.
#define TLENTRYTMPFILE `tmp/dil2al-TLentry.html`
Definition at line 1202 of file dil2al.hh.
#define Topical_DIL_Files_Updated_Access(Here, There, ThereSteps)
Value:
if (updated) { \
                Protected_Linked_List_Indexed_Access(Topical_DIL_Files,Here,There); \
        } \
        if (!Prev()) { \
                if (Refresh()) return ThereSteps(n); \
                else return NULL; \
        } else { \
                Invalidate(); \
                return Prev()->ThereSteps(n+1); \
        }
Definition at line 366 of file dil2al.hh.
Referenced by Topical_DIL_Files::File(), Topical_DIL_Files::Title(), and Topical_DIL_Files::Topic().
#define TSS_ASK 2
Definition at line 1230 of file dil2al.hh.
Referenced by decide_add_TL_chunk(), and Set_Parameter().
#define TSS_CURRENT 0
Definition at line 1228 of file dil2al.hh.
Referenced by Set_Parameter().
#define TSS_NEW 1
Definition at line 1229 of file dil2al.hh.
Referenced by decide_add_TL_chunk(), and Set_Parameter().
#define UNIE_ASK 2
Definition at line 1234 of file dil2al.hh.
Referenced by process_note(), and Set_Parameter().
#define UNIE_NO 0
Definition at line 1232 of file dil2al.hh.
Referenced by Set_Parameter().
#define UNIE_YES 1
Definition at line 1233 of file dil2al.hh.
Referenced by Set_Parameter().
#define VOUT (*vout)
Definition at line 1407 of file dil2al.hh.
Referenced by add_new_to_DIL(), AL_Day::allocate(), AL_Day::allocate_with_value(), Assess_Paper_Correction_Time(), backup_and_rename(), Detailed_Items_List::Binary_Cache_Diagnostic(), DIL_entry::Binary_Cache_Diagnostic(), DIL_entry_parameters::Binary_Cache_Diagnostic(), DIL_AL_List::Binary_Cache_Diagnostic(), DIL_Topical_List::Binary_Cache_Diagnostic(), DIL_entry_content::Binary_Cache_Diagnostic(), chunk_controller(), clean_paper_outline(), create_new_DIL(), dil2al_commands(), DIL_Hierarchy_cmd(), exit_report(), Active_List::expand(), AL_Day::expand(), extract_DIL_IDs_from_form(), extract_hierarchy_depth_decrease_to_paper(), extract_hierarchy_depth_increase_to_paper(), extract_paper_plan_to_paper(), extract_recursively(), extract_required_item_to_paper(), extraction_put_figure(), financial_monthly(), financial_notes(), Form_Input_Error(), Form_Reply(), Form_Reply_Close(), Form_Reply_Open(), generate_AL(), Active_List::generate_focused_AL(), generate_modify_element_FORM_interface(), generate_modify_element_FORM_interface_DIL_entry_content(), generate_modify_element_FORM_interface_DIL_entry_parameters(), generate_modify_element_FORM_interface_DIL_Superiors(), Active_List::generate_wide_AL(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), Detailed_Items_List::Get_All_Topical_DIL_Parameters(), get_figure_data(), get_TL_head(), include_article_head_template(), Active_List::Initialize_AL_Length(), make_note(), modify_DIL_entry_target_date(), modify_DIL_group_target_dates(), modify_DIL_group_target_dates_cmd(), modify_element_through_FORM_interface(), modify_element_through_FORM_interface_DIL_Superiors(), pre_process_note(), process_note_CC(), process_note_generic(), DIL_entry::Propagated_Target_Date(), read_financial_notes_file(), Detailed_Items_List::Read_from_Binary_Cache(), DIL_entry::Read_from_Binary_Cache(), DIL_entry_parameters::Read_from_Binary_Cache(), DIL_AL_List::Read_from_Binary_Cache(), Detailed_Items_List::Read_Topical_from_Binary_Cache(), DIL_entry::Read_Topical_from_Binary_Cache(), remove_AL_TC(), search_cmd(), search_output(), select_TL_DIL_refs(), send_dil_to_DIL(), stop_TL_chunk(), superior_reference_info(), Tabbed_FORM_DIL_Hierarchy(), Tabbed_FORM_DIL_Hierarchy_full(), TeX_format_corrections(), Text_limit_line_length(), time_chunk_remaining(), update_DIL_entry_elements(), update_DIL_entry_parameter_elements(), update_main_ALs(), write_file_from_String(), Detailed_Items_List::Write_to_Binary_Cache(), and Detailed_Items_List::Write_Topical_to_Binary_Cache().
Typedef Documentation
typedef unsigned long idnumber
Definition at line 73 of file dil2al.hh.
Referenced by DIL_ID::DIL_ID().
Function Documentation
String absurl (String srcurl, String relurl)
Definition at line 1943 of file utilities.cc.
References String::after(), String::before(), String::contains(), String::freq(), and String::gsub().
Referenced by extract_paper_plan_to_paper(), extract_recursively(), generate_modify_element_FORM_interface_DIL_entry_content(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), get_Paper_Plans_Section_IDs(), modify_element_through_FORM_interface(), and Topical_DIL_Files::Refresh().
1943                                             {
1944 // srcurl is an absolute filename or a directory path
1945 // ending with "/"
1946 // relurl is a URL relative to srcurl or an absolute URL
1947 // Note: This function may be confused by directory names
1948 //       of the form BigRegex(".+[.][.]")
1949         if (relurl=="") return srcurl;
1950         if (relurl.contains("://")) relurl = relurl.after("://");
1951         if (relurl[0]=='/') return relurl;
1952         if (relurl[0]=='#') return srcurl+relurl;
1953         int upcnt = relurl.freq("../");
1954         relurl.gsub("../","");
1955         srcurl = srcurl.before('/',-1); // prune source filename
1956         for (int i = 0; i < upcnt; i++) srcurl = srcurl.before('/',-1);
1957         return srcurl+'/'+relurl;
1958 }
bool add_new_to_DIL (String dilfile, StringList * supinfoptr)
Definition at line 281 of file diladmin.cc.
References backup_and_rename(), EOUT, find_in_line(), find_line(), get_active_DIL_IDs(), StringList::insert(), pattern_in_line(), RELLISTSDIR, res, substring_from_line(), superior_reference_info(), and VOUT.
Referenced by dil2al_commands(), and send_dil_to_DIL().
281                                                              {
282 // Adds all new DIL entry ID references to the DIL-by-ID file,
283 // with superior DIL entry information if provided in supinfoptr
284         const int LLEN = 10240;
285         char lbuf[LLEN];
286         String dilid[2], dilfilename, dilfiletitle;
287         StringList dilfileids, idfileids, beforeid;
288         unsigned long numdilfileids = 0, numidfileids = 0, newdils = 0;
289         int res;
290         // get name of DIL file
291         if (!substring_from_line("([^/]+)$",2,dilid,(const char *) dilfile)) {
292                 EOUT << "dil2al: Unable to parse name from DIL file path in add_new_to_DIL()\n";
293                 return false;
294         } else dilfilename = dilid[1];
295         dilfile=basedir+RELLISTSDIR+dilfilename;
296         if (verbose) VOUT << "Adding new DIL ID from " << dilfile << '\n';
297         ifstream df(dilfile);
298         if (df) {
299                 // get title of DIL file
300                 if (!find_line(&df,"[<]TITLE[>] *DIL: *",lbuf,LLEN)) {
301                         EOUT << "dil2al: Unable to find title of DIL file in add_new_to_DIL()\n";
302                         return false;
303                 }
304                 if (!substring_from_line("[<]TITLE[>] *DIL: *([^<]+)",2,dilid,lbuf)) {
305                         EOUT << "dil2al: Unable to parse title from title line of DIL file in add_new_to_DIL()\n";
306                         return false;
307                 } else dilfiletitle = dilid[1];
308                 // collect all DIL IDs in dilfile
309                 if (!find_line(&df,"[<]!-- *dil2al: *DIL *begin *--[>]",lbuf,LLEN)) {
310                         EOUT << "dil2al: Tag <!-- dil2al: DIL begin --> not found in " << dilfile << '\n';
311                         return false;
312                 }
313                 if (verbose) VOUT << "Reading DIL IDs\n";
314                 do {
315                         if ((res=find_in_line(&df,"[<]TR +BGCOLOR=\"#00005F",0,NULL,"[<]!-- *dil2al: *DIL *end *--[>]",lbuf,LLEN))==1) {
316                                 res = find_in_line(&df,"[<]TD[^>]*[>][<]A +NAME=\"([.0-9]+)\"",2,dilid,"[<]TR +BGCOLOR=\"#00005F|[<]!-- *dil2al: *DIL *end *--[>]",lbuf,LLEN);
317                                 if (res<-1) return false;
318                                 if (numdilfileids) {
319                                         unsigned long i;
320                                         for (i=0; ((i<numdilfileids) && (dilid[1]>dilfileids[i])); i++);
321                                         dilfileids.insert(i,dilid[1]);
322                                 } else dilfileids[0]=dilid[1];
323                                 numdilfileids++;
324                         } else {
325                                 if (res>=-1) res=-1;
326                                 else return false;
327                         }
328                 } while ((res>0) || ((res==0) && (!pattern_in_line("[<]!-- *dil2al: *DIL *end *--[>]",lbuf))));
329                 df.close();
330         } else {
331                 EOUT << "dil2al: Unable to open DIL file " << dilfile << '\n';
332                 return false;
333         }
334         // compare with all DIL IDs in detailed-items-by-ID.html
335         if (verbose) VOUT << "Comparing with DIL IDs in " << idfile << '\n';
336         if (!get_active_DIL_IDs(idfileids,&numidfileids)) {
337                 EOUT << "dil2al: Unable to obtain DIL IDs from " << idfile << '\n';
338                 return false;
339         }
340 //      for (int i=0; i<numidfileids; i++) cout << idfileids[i] << '\n';
341         if (verbose) VOUT << "Removing existing IDs from batch to add\n";
342 //*** THIS IS WHERE IT *SHOULD* STILL ADD ADDITIONAL DIL REFERENCES TO THE
343 //*** DIL-BY-ID LIST IF AN ITEM OCCURS IN MORE THAN ONE DIL!!!
344 //*** SEE DIL 20000124180439.1, WHICH OCCURS IN BOTH components.html and experiments.html
345 //*** (NOTE ALSO THAT SENDTODIL DID NOT WORK PROPERLY FOR THE SECOND OCCURRANCE!)
346         newdils=numdilfileids;
347         for (unsigned long i=0; i<numdilfileids; i++)
348                 for (unsigned long j=0; j<numidfileids; j++)
349                         if ((dilfileids[i])==(idfileids[j])) {
350                                 dilfileids[i]=""; // avoid adding multiples
351                                 newdils--;
352                                 break;
353                         } else if ((idfileids[j]>dilfileids[i]) && (beforeid[i]=="")) beforeid[i]=idfileids[j];
354         if (newdils>0) {
355                 VOUT << "Number of new DILs: " << newdils << '\n';
356 //              for (int i=0; i<numdilfileids; i++) cout << dilfileids[i] << ',' << beforeid[i] << '\n';
357                 // copy idfile and add new DILs in sorted locations (beforeid[i]=="" implies place at end)
358                 df.open(idfile);
359                 if (!df) {
360                         EOUT << "dil2al: Unable to open DIL ID file " << idfile << "in add_new_to_DIL()\n";
361                         return false;
362                 }
363                 ofstream ndf(idfile+".new");
364                 if (ndf) {
365                         //df.seekg(0);
366                         unsigned long i;
367                         if (verbose) VOUT << "Inserting new IDs\n";
368                         // find first new DIL to insert
369                         for (i=0; (i<numdilfileids) && (dilfileids[i]==""); i++);
370                         while (!df.eof()) {
371                                 df.getline(lbuf,LLEN);
372                                 if (newdils) {
373                                         // test if found an insertion location
374                                         if ((beforeid[i]!="") && (pattern_in_line("[<]TD[^>]*[>][<]A +NAME=\""+beforeid[i],lbuf))) {
375                                                 // insert
376                                                 ndf << "<TD><A NAME=\"" << dilfileids[i] << "\">"
377                                                         << dilfileids[i] << "</A>\n<TD><A HREF=\""
378                                                         << dilfilename << '#' << dilfileids[i] << "\">"
379                                                         << dilfiletitle << superior_reference_info(supinfoptr) << "<TR>\n";
380                                                 // find next DIL to insert
381                                                 for (i++; (i<numdilfileids) && (dilfileids[i]==""); i++);
382                                                 newdils--;
383                                         }
384                                         // test if found end of DILs (insert rest here)
385                                         if (pattern_in_line("[<]!-- *dil2al: *DIL ID *end *--[>]",lbuf)) {
386                                                 do {
387                                                         ndf << "<TR>\n<TD><A NAME=\"" << dilfileids[i] << "\">"
388                                                                 << dilfileids[i] << "</A>\n<TD><A HREF=\""
389                                                                 << dilfilename << '#' << dilfileids[i] << "\">"
390                                                                 << dilfiletitle << superior_reference_info(supinfoptr);
391                                                         for (i++; (i<numdilfileids) && (dilfileids[i]==""); i++);
392                                                         newdils--;
393                                                 } while (newdils);
394                                         }
395                                 }
396                                 if (!df.eof()) ndf << lbuf << endl;
397                         }
398                         df.close();
399                         ndf.close();
400                         if (!backup_and_rename(idfile,"DIL ID")) return false;
401                 } else {
402                         EOUT << "dil2al: Unable to create file " << idfile << ".new in add_new_to_DIL()\n";
403                         return false;
404                 }
405         } else if (verbose) VOUT << "No new IDs to add\n";
406         return true;
407 }
String add_TL_chunk_or_entry (String & tl, String & notestr, bool newchunk, String chunkid, int & tlinsertloc)
Definition at line 485 of file tladmin.cc.
References String::after(), String::at(), String::before(), String::contains(), String::del(), EOUT, String::from(), generate_TL_chunk_header(), generate_TL_entry_header(), get_TL_head(), String::gsub(), String::index(), String::length(), max_chunk_entry(), String::prepend(), read_file_into_String(), RELLISTSDIR, RX_Search_Safe(), select_TL_AL_refs(), select_TL_DIL_refs(), stop_TL_chunk(), and write_file_from_String().
Referenced by decide_add_TL_chunk(), and process_note_TL().
485
486 // Add a new chunk or a new entry to the Task Log
487 // tlinsertloc is used when adding an entry, while it
488 // is set here when adding a chunk
489 String nametag;
490 int chunkendindex; // used to find NAME tag and for entry insertion
491 if (!newchunk)
492 // determine entry NAME tag
493 nametag = chunkid;
494 chunkendindex = tl.index(BigRegex("[<]!--[ ]*chunk End[ ]*--[>]"),tlinsertloc);
495 if (chunkendindex>=0)
496 String tlchunk = tl.at(tlinsertloc,chunkendindex-tlinsertloc);
497 nametag = nametag + "." + dec(max_chunk_entry(tlchunk)+1);
498 else
499 EOUT << "dil2al: Unable to find Task Log chunk end in add_TL_chunk_or_entry()";
500 return String("");
501
502 else
503 nametag = curtime; // new NAME tag for new chunk
504 // if a current chunk is active, mark its completion time
505 stop_TL_chunk(tl); // can close previous task chunk and update AL and completion ratios
506
507 #ifdef DEBUGTIER1
508 cout << "chunkid nametag: " << nametag << '';
509 #endif
510 // obtain DIL reference ID or identifying comment and AL reference ID
511 String newdilref,newalref,alhead,dilhead,altitle,diltitle;
512 #ifdef DEBUGTIER1
513 cout << '+';
514 #endif
515 while ((newdilref=="*") || (newdilref==""))
516 #ifdef DEBUGTIER1
517 cout << 'x';
518 #endif
519 if ((newdilref=select_TL_DIL_refs(tl,newchunk,newalref))=="") return String("");
520 #ifdef DEBUGTIER1
521 cout << 'x';
522 #endif
523 if ((newalref=="") || (newdilref=="*")) if ((newalref=select_TL_AL_refs(tl,newchunk,newdilref))=="") return String("");
524 #ifdef DEBUGTIER1
525 cout << 'x';
526 #endif
527
528 #ifdef DEBUGTIER1
529 cout << "newdilref: " << newdilref << ": " << newalref << '';
530 #endif
531 String lfstr, lfrx;
532 #ifdef DEBUG_BIGSTRING
533 //lfstr.debug_on();
534 globaldebugop=true;
535 #endif
536 if (newalref[0]!='*')
537 // find previous AL reference with the same ID
538 if (!read_file_into_String(listfile,lfstr)) return String("");
539 // AL head and title in lists file
540 #ifdef DEBUG_BIGSTRING
541 globaldebugop=false;
542 //lfstr.debug_off();
543 cout << "[Freshly read] lfstr.length()=" << lfstr.length() << '';
544 #endif
545 #ifdef DEBUGTIER1
546 cout << ".";
547 #endif
548 lfrx = "[<]LI[>][ ]*[<]A[ ][^>]*[Hh][Rr][Ee][Ff][ ]*=[ ]*"+RX_Search_Safe(RELLISTSDIR+newalref)+"[^]*";
549 altitle = lfstr.at(BigRegex(lfrx));
550 #ifdef DEBUG_BIGSTRING
551 cout << "[After reading into alhead] lfstr.length()=" << lfstr.length() << '';
552 #endif
553 alhead = altitle.at(BigRegex("([^)]*AL head"));
554 altitle.del(BigRegex("[ ]*([^)]*AL head.*"));
555 altitle.gsub(BigRegex("[<][^>]*[>]"),"");
556 if (alhead!="")
557 #ifdef DEBUGTIER1
558 cout << ".";
559 #endif
560 alhead.del(BigRegex("([^,]*,[ ]*[<]A [^>]*[Hh][Rr][Ee][Ff][ ]*=[ ]*"));
561 if (alhead[0]!='/')
562 if (alhead.contains(RELLISTSDIR,0)) alhead.del(RELLISTSDIR);
563 else alhead.prepend("../");
564
565 alhead = alhead.before("");
566 alhead.del(get_TL_head());
567
568 #ifdef DEBUGTIER1
569 cout << "altitle: " << altitle << ": " << alhead << '';
570 #endif
571
572 String dfstr, dlrx;
573 if (newdilref[0]!='*')
574 // find previous DIL reference with the same ID or identifying comment
575 if (newdilref[0]=='!') // non-DIL identifying comment
576 int dilheadindex;
577 if ((dilheadindex = tl.index(BigRegex("Context[ ]*--[>][ ]*"+RX_Search_Safe(newdilref.after("!"))+"[^(]*([^/]*/next"),-1))>=0)
578 dilhead = tl.at(BigRegex("Begin[ ]*-->[^]*[<]A[ ]+[^>]*[Nn][Aa][Mm][Ee][ ]*=[ ]*[^]+"),dilheadindex-tl.length());
579 if (dilhead!="")
580 dilhead = dilhead.after("",-1);
581 dilhead.prepend('#');
582 #ifdef DEBUGTIER1
583 cout << "diltitle: " << diltitle << ": " << dilhead << '';
584 #endif
585 else EOUT << "dil2al: Context error, no matching Begin in add_TL_chunk_or_entry(), continuing";
586 else
587 // search for Context in previous TL sections
588 String prevtlfile = tl.at(BigRegex("[<]/H1[>]+[<]TABLE.*[>][ ]*previous[ ]+TL[ ]+section"));
589 if (prevtlfile!="")
590 prevtlfile = prevtlfile.after(BigRegex("[<]A[ ]+[Hh][Rr][Ee][Ff]="));
591 prevtlfile = basedir+RELLISTSDIR+prevtlfile.before("");
592 while (prevtlfile!="")
593 String prevtl;
594 if (!read_file_into_String(prevtlfile,prevtl))
595 EOUT << "dil2al: Continuing without non-DIL identifying comment previous dilhead";
596 break;
597
598 if ((dilheadindex = prevtl.index(BigRegex("Context[ ]*--[>][ ]*"+RX_Search_Safe(newdilref.after("!"))+"[^(]*([^/]*/next"),-1))>=0)
599 dilhead = prevtl.at(BigRegex("Begin[ ]*-->[^]*[<]A[ ]+[^>]*[Nn][Aa][Mm][Ee][ ]*=[ ]*[^]+"),dilheadindex-tl.length());
600 if (dilhead!="")
601 dilhead = dilhead.after("",-1);
602 dilhead.prepend('#');
603 #ifdef DEBUGTIER1
604 cout << "diltitle: " << diltitle << ": " << dilhead << '';
605 #endif
606 break;
607 else EOUT << "dil2al: Context error, no matching Begin in add_TL_chunk_or_entry(), continuing";
608
609 prevtlfile = prevtl.at(BigRegex("[<]/H1[>]+[<]TABLE.*[>][ ]*previous[ ]+TL[ ]+section"));
610 if (prevtlfile!="")
611 prevtlfile = prevtlfile.after(BigRegex("[<]A[ ]+[Hh][Rr][Ee][Ff]="));
612 prevtlfile = basedir+RELLISTSDIR+prevtlfile.before("");
613
614
615
616
617 else // DIL reference ID
618 if (!read_file_into_String(basedir+RELLISTSDIR+newdilref.before("#"),dfstr)) return String("");
619 // DIL title in newdilref file
620 diltitle = dfstr.at(BigRegex("[<]TITLE[>][^<]*[<]/TITLE[>]"));
621 diltitle.del("<TITLE>");
622 diltitle.del("</TITLE>");
623 // DIL head in newdilref file
624 dlrx = "[<]TD[^>]*[>][<]A [^>]*[Nn][Aa][Mm][Ee][ ]*=[ ]*"+RX_Search_Safe(newdilref.after("#"))+"[^]*([^)]*head";
625 dilhead = dfstr.at(BigRegex(dlrx));
626 if (dilhead!="")
627 dilhead.del(BigRegex("[<]TD[^>]*[>][<]A [^>]*[Nn][Aa][Mm][Ee][ ]*=[ ]*"+RX_Search_Safe(newdilref.after("#"))+"[^]*([^,]*,[ ]*[<]A [^>]*[Hh][Rr][Ee][Ff][ ]*=[ ]*"));
628 dilhead = dilhead.before("");
629 dilhead.del(get_TL_head());
630
631 #ifdef DEBUGTIER1
632 cout << "diltitle: " << diltitle << ": " << dilhead << '';
633 #endif
634
635
636 // prepend newalref, newdilref, alhead, dilhead, altitle and diltitle information to note
637 String notepre;
638 if (newchunk)
639 notepre = generate_TL_chunk_header(nametag, newalref, altitle, alhead, newdilref, diltitle, dilhead);
640 // find new chunk insertion location (becomes tlinsertloc for entry also)
641 if ((tlinsertloc=tl.index(BigRegex("[<]!--[ ]+section End[ ]+-->")))<0)
642 EOUT << "dil2al: Unable to find section End in " << taskloghead << "in add_TL_chunk_or_entry()";
643 return String("");
644
645 else
646 notepre = generate_TL_entry_header(nametag, newalref, altitle, alhead, newdilref, diltitle, dilhead);
647 // reposition at End of chunk for insertion of TL entry
648 tlinsertloc=chunkendindex;
649
650 // insert note and store if operations on tl are complete
651 String tltail = tl.from(tlinsertloc);
652 if (newchunk) tl = tl.before(tlinsertloc) + notepre + tltail;
653 else tl = tl.before(tlinsertloc) + notepre + notestr + "<P>" + tltail;
654 get_TL_head();
655 String tlheadfile=taskloghead.after(basedir+RELLISTSDIR);
656 String alheadfile=alhead.before("#"); if ((alhead!="") (alheadfile=="")) alheadfile = tlheadfile;
657 String dilheadfile=dilhead.before("#"); if ((dilhead!="") (dilheadfile=="")) dilheadfile = tlheadfile;
658 #ifdef DEBUGTIER1
659 cout << "tlheadfile = " << tlheadfile << "= " << alheadfile << "= " << dilheadfile << '';
660 #endif
661 if ((tlheadfile!=alheadfile) (tlheadfile!=dilheadfile))
662 // store updated Task Log
663 if (!write_file_from_String(taskloghead,tl,"Task Log")) return String("");
664
665 String tlp;
666 if (alhead!="")
667 // modify ``next'' in previous AL head
668 String newalnext, altlfile = basedir+RELLISTSDIR+alheadfile;
669 #ifdef DEBUGTIER2
670 cout << "D1,"; cout.flush();
671 #endif
672 //*** This is not very optimized, requiring some copying
673 //*** of long Strings. This is due to a ``bug'' in the
674 //*** String class, which caused modifications via a
675 //*** pointer tlp->at.() or reference tlp.at() to add
676 //*** several characters of junk at the end of the
677 //*** string. Note that we cannot simply overwrite tl
678 //*** here as it may be needed below.
679 if (tlheadfile==alheadfile)
680 #ifdef DEBUGTIER2
681 cout << "D2,"; cout.flush();
682 #endif
683 tlp = tl;
684 #ifdef DEBUGTIER2
685 cout << "D3,"; cout.flush();
686 #endif
687 newalnext = '#'+nametag;
688 #ifdef DEBUGTIER2
689 cout << "D4,"; cout.flush();
690 #endif
691 else
692 if (!read_file_into_String(altlfile,tlp)) return String("");
693 newalnext = tlheadfile+'#'+nametag;
694
695 BigRegex alindexrx("
(chunk
|entry
)[ ]+Begin[ ]+--[>][^]*[<]A[ ][^>]*[Nn][Aa][Mm][Ee][ ]*=[ ]*"+alhead.after("#")+'"');
696 #ifdef DEBUGTIER1
697 cout << "D5,"; cout.flush();
698 #endif
699 //*** could make this a forward search by continuing to
700 //*** search until -1 is returned
701 //*** NOT NECESSARY WITH NON-PARANOID OR FASTER BACKWARD SEARCH METHOD
702 int alnextindex=tlp.index(alindexrx,-1);
703 #ifdef DEBUGTIER1
704 cout << "alnextindex = " << alnextindex << '';
705 cout << "E,"; cout.flush();
706 #endif
707 if (alnextindex<0)
708 EOUT << "dil2al: Unable to find previous AL head in " << alheadfile << " in add_TL_chunk_or_entry()";
709 return String("");
710
711 #ifdef DEBUGTIER2
712 cout << "E0,"; cout.flush();
713 #endif
714 String alnext;
715 #ifdef DEBUGTIER2
716 cout << "E0.5,"; cout.flush();
717 #endif
718 BigRegex alnextrx("AL[ ]+--[>][^]*"+newalref+"[^(]*([^)]*/next");
719 #ifdef DEBUGTIER2
720 cout << "E0.75,"; cout.flush();
721 #endif
722 alnext=tlp.at(alnextrx,alnextindex);
723 #ifdef DEBUGTIER2
724 cout << "alnext = " << alnext << "1,"; cout.flush();
725 #endif
726 alnext = alnext.before("next",-1) + "<A HREF="+newalnext+">next</A>";
727 //alnext.at("next",-1)="<A HREF="+newalnext+">next</A>";
728 #ifdef DEBUGTIER2
729 cout << "alnext = " << alnext << "2,"; cout.flush();
730 #endif
731 String ttmp = tlp.before(BigRegex("AL[ ]+--[>][^]*"+RX_Search_Safe(newalref)+"[^(]*([^)]*/next"),alnextindex);
732 #ifdef DEBUGTIER2
733 cout << "E3,"; cout.flush();
734 #endif
735 ttmp += alnext;
736 #ifdef DEBUGTIER2
737 cout << "E4,"; cout.flush();
738 #endif
739 ttmp += tlp.after(BigRegex("AL[ ]+--[>][^]*"+RX_Search_Safe(newalref)+"[^(]*([^)]*/next"),alnextindex);
740 #ifdef DEBUGTIER2
741 cout << "E5,"; cout.flush();
742 #endif
743 tlp = ttmp;
744 //*** THIS WORKED... SO IT IS OBVIOUSLY DANGEROUS TO USE THE SUBSTRING REPLACEMENT
745 //*** METHOD FOR INSERTION, BUT THE ABOVE IS OF COURSE VERY NON-OPTIMAL!
746 // tlp.at(BigRegex("AL[ ]+--[>][^]*"+newalref+"[^(]*([^)]*/next"),alnextindex)=alnext;
747 #ifdef DEBUGTIER1
748 cout << "F,"; cout.flush();
749 #endif
750 if (alheadfile!=dilheadfile)
751 if (!write_file_from_String(altlfile,tlp,"AL head Task Log")) return String("");
752
753
754 #ifdef DEBUGTIER1
755 cout << "G,"; cout.flush();
756 #endif
757 if (dilhead!="")
758 #ifdef DEBUGTIER1
759 cout << "H,"; cout.flush();
760 #endif
761 // modify ``next'' in previous DIL head
762 String newdilnext, diltlfile = basedir+RELLISTSDIR+dilheadfile;
763 if (dilheadfile==tlheadfile) newdilnext = '#'+nametag;
764 else newdilnext = tlheadfile+'#'+nametag;
765 if (alheadfile!=dilheadfile)
766 if (tlheadfile==dilheadfile) tlp = tl;
767 else if (!read_file_into_String(diltlfile,tlp)) return String("");
768
769 #ifdef DEBUGTIER2
770 cout << "H1,"; cout.flush();
771 #endif
772 String dilnext;
773 //*** could make this a forward search by continuing to
774 //*** search until -1 is returned
775 //*** NOT NECESSARY WITH NON-PARANOID OR FASTER BACKWARD SEARCH METHOD
776 int dilnextindex=tlp.index(BigRegex("
(chunk
|entry
)[ ]+Begin[ ]+--[>][^]*[<]A[ ][^>]*[Nn][Aa][Mm][Ee][ ]*=[ ]*"+RX_Search_Safe(dilhead.after("#")+'"')),-1);
777 if (dilnextindex<0)
778 EOUT << "dil2al: Unable to find previous DIL head in " << dilheadfile << " in add_TL_chunk_or_entry()";
779 return String("");
780
781 #ifdef DEBUGTIER2
782 cout << "H2,"; cout.flush();
783 #endif
784 if (newdilref[0]=='!')
785 #ifdef DEBUGTIER2
786 cout << "H3,"; cout.flush();
787 #endif
788 dilnext=tlp.at(BigRegex("Context[ ]+--[>][ ]*"+RX_Search_Safe(newdilref.after("!"))+"[^(]*([^)]*/next"),dilnextindex);
789 dilnext.at("next",-1)="<A HREF="+newdilnext+">next</A>";
790 tlp.at(BigRegex("Context[ ]+--[>][ ]*"+RX_Search_Safe(newdilref.after("!"))+"[^(]*([^)]*/next"),dilnextindex)=dilnext;
791 else
792 #ifdef DEBUGTIER2
793 cout << "H4,"; cout.flush();
794 #endif
795 dilnext=tlp.at(BigRegex("Context[ ]+--[>][^]*"+RX_Search_Safe(newdilref)+"[^(]*([^)]*/next"),dilnextindex);
796 dilnext.at("next",-1)="<A HREF="+newdilnext+">next</A>";
797 tlp.at(BigRegex("Context[ ]+--[>][^]*"+RX_Search_Safe(newdilref)+"[^(]*([^)]*/next"),dilnextindex)=dilnext;
798
799 if (!write_file_from_String(diltlfile,tlp,"Context head Task Log")) return String("");
800 #ifdef DEBUGTIER2
801 cout << "H5,"; cout.flush();
802 #endif
803
804 if (newalref[0]!='*')
805 #ifdef DEBUGTIER1
806 cout << "I,";
807 #endif
808 // update AL head in listfile
809 if (alhead!="")
810 #ifdef DEBUGTIER1
811 cout << ",J"; cout.flush();
812 #endif
813 String newalnext = lfstr.at(BigRegex(lfrx));
814 #ifdef DEBUG_BIGSTRING
815 cout << "[After reading into newalnext] lfstr.length()=" << lfstr.length() << '';
816 #endif
817 #ifdef DEBUGTIER2
818 cout << ",J1"; cout.flush();
819 #endif
820 newalnext.at(BigRegex("[Hh][Rr][Ee][Ff][ ]*=[ ]*[^]+"),-1) = "HREF="+(RELLISTSDIR+tlheadfile)+'#'+nametag+"";
821 #ifdef DEBUGTIER2
822 cout << ",J2"; cout.flush();
823 #endif
824 #ifdef DEBUG_BIGSTRING
825 cout << "lfstr.length()=" << lfstr.length() << '';
826 newalnext.debug_on();
827 #endif
828 lfstr.at(BigRegex(lfrx)) = newalnext;
829 #ifdef DEBUG_BIGSTRING
830 newalnext.debug_off();
831 cout << "lfstr.length()=" << lfstr.length() << '';
832 #endif
833 else
834 #ifdef DEBUGTIER2
835 cout << ",JJ"; cout.flush();
836 #endif
837 String newalnext = lfstr.at(BigRegex("[<]LI[>][ ]*[<]A[ ][^>]*[Hh][Rr][Ee][Ff][ ]*=[ ]*"+RX_Search_Safe(RELLISTSDIR+newalref)+"[^]*"));
838 #ifdef DEBUGTIER2
839 cout << ",JJ1"; cout.flush();
840 #endif
841 newalnext.at("<BR>",-1) = " (<A HREF="+(RELLISTSDIR+tlheadfile)+'#'+nametag+">AL tail</A>,<A HREF="+(RELLISTSDIR+tlheadfile)+('#'+nametag)+">AL head</A>)<BR>";
842 #ifdef DEBUGTIER2
843 cout << ",JJ2"; cout.flush();
844 #endif
845 lfstr.at(BigRegex("[<]LI[>][ ]*[<]A[ ][^>]*[Hh][Rr][Ee][Ff][ ]*=[ ]*"+RX_Search_Safe(RELLISTSDIR+newalref)+"[^]*")) = newalnext;
846
847 if (!write_file_from_String(listfile,lfstr,"Main Lists")) return String("");
848
849 #ifdef DEBUGTIER1
850 cout << ",K";
851 #endif
852 if ((newdilref[0]!='*') (newdilref[0]!='!'))
853 #ifdef DEBUGTIER1
854 cout << ",L";
855 #endif
856 // update DIL head in DIL file
857 if (dilhead!="")
858 String newdilnext = dfstr.at(BigRegex(dlrx));
859 #ifdef DEBUGTIER2
860 cout << ",L1";
861 #endif
862 newdilnext.at(BigRegex("[Hh][Rr][Ee][Ff][ ]*=[ ]*[^]+"),-1) = "HREF="+tlheadfile+'#'+nametag+"";
863 #ifdef DEBUGTIER2
864 cout << ",L2";
865 #endif
866 dfstr.at(BigRegex(dlrx)) = newdilnext;
867 else
868 #ifdef DEBUGTIER1
869 cout << ",M";
870 #endif
871 String newdilnext = dfstr.at(BigRegex("[<]TD[^>]*[>][<]A [^>]*[Nn][Aa][Mm][Ee][ ]*=[ ]*"+RX_Search_Safe(newdilref.after("#"))+"[^]*"));
872 #ifdef DEBUGTIER2
873 cout << ",M1";
874 #endif
875 newdilnext += " (<A HREF="+tlheadfile+'#'+nametag+">tail</A>,<A HREF="+tlheadfile+'#'+nametag+">head</A>)<BR>";
876 #ifdef DEBUGTIER2
877 cout << ",M2";
878 #endif
879 dfstr.at(BigRegex("[<]TD[^>]*[>][<]A [^>]*[Nn][Aa][Mm][Ee][ ]*=[ ]*"+RX_Search_Safe(newdilref.after("#"))+"[^]*")) = newdilnext;
880
881 if (!write_file_from_String(basedir+RELLISTSDIR+newdilref.before("#"),dfstr,"DIL")) return String("");
882
883 #ifdef DEBUGTIER1
884 cout << ",N";
885 #endif
886 if (newchunk) chunkcreated = true; // update process variable
887 return nametag;
888
bool add_TL_section (String & tl)
Definition at line 890 of file tladmin.cc.
References String::at(), String::before(), EOUT, get_TL_head(), String::index(), read_file_into_String(), RELLISTSDIR, stop_TL_chunk(), and write_file_from_String().
Referenced by decide_add_TL_chunk().
890                                  {
891 // Add a new section to the Task Log
892 // Note: modifies current Task Log head file, tl, taskloghead,
893 //       Main List File (listfile), Task Log symbolic link (tasklog);
894 //       update in-memory copies and any variables that reference specific
895 //       items or locations in the modified variables and files if necessary
896         // close any currently active TL chunk
897         stop_TL_chunk(tl);
898         // initialize new TL section
899         get_TL_head();
900         String curtlid = taskloghead.after("task-log.");
901         curtlid = curtlid.before(".html");
902         if (curtlid==curdate) {
903                 EOUT << "dil2al: Cannot create Task Log section with same ID as current Task Log head\n";
904                 return false;
905         }
906         String newreltlhead = "task-log."+curdate+".html";
907         String newtlsection = "<HTML>\n<HEAD><TITLE>Task Log ("+curdate+")</TITLE>\n</HEAD>\n<BODY BGCOLOR=\"#000000\" TEXT=\"#FFDF00\" LINK=\"#AFAFFF\" VLINK=\"#7F7FFF\">\n<H1><FONT COLOR=\"#00FF00\">Task Log ("
908                                         + curdate + ")</FONT></H1>\n\n<TABLE WIDTH=\"100%\" CELLPADDING=3 BGCOLOR=\"#007F00\"><TR><TD WIDTH=\"30%\" ALIGN=CENTER><A HREF=\"task-log."
909                                         + curtlid + ".html\"><FONT COLOR=\"#FFFFFF\">previous TL section ("+curtlid+")</FONT></A><TD WIDTH=\"40%\" BGCOLOR=\"#005F00\">&nbsp;<TD WIDTH=\"30%\" ALIGN=CENTER><FONT COLOR=\"#FFFFFF\">(no next TL section)</FONT></TABLE>\n\n"
910                                         + "<P>\n<LI><A HREF=\"../lists.html#AL\">Project Active Lists</A>\n"
911                                         + "<LI><A HREF=\"../lists.html#DIL\">Topical Detailed Items Lists</A>\n"
912                                         + "<LI><A HREF=\"detailed-items-by-ID.html\">Detailed Items by ID</A>\n"
913                                         + "<LI><A HREF=\"../work-log.html\">Work Log</A>\n<P>\n<HR>\n<P>\n"
914                                         + "<!-- section Begin --><TABLE WIDTH=\"100%\" CELLPADDING=3 BGCOLOR=\"#3F3F3F\">\n\n"
915                                         + "<!-- section End --></TABLE>\n\n<P>\n<HR>\n"
916                                         + "~/doc/<A HREF=\"../maincont.html\">html</A>/<A HREF=\"../lists.html\">lists</A>/"+newreltlhead+"\n\n</BODY>\n";
917         String newtaskloghead = basedir+RELLISTSDIR+newreltlhead;
918         if (!write_file_from_String(newtaskloghead,newtlsection,"New Task Log section",true)) return false;
919         // update next TL section reference in tl and store current Task Log
920         tl.at(BigRegex("[<]FONT[        ]+COLOR[        ]*=[    ]*\"#FFFFFF\"[>][       ]*([    ]*no next TL section[   ]*)[    ]*[<]/FONT[>][<]/TABLE[>]")) = "<A HREF=\""+newreltlhead+"\"><FONT COLOR=\"#FFFFFF\">next TL section ("+curdate+")</FONT></A></TABLE>";
921         if (!write_file_from_String(taskloghead,tl,"Task Log")) return false;
922         // update list of Task Log sections in listfile
923         String lfstr;
924         if (!read_file_into_String(listfile,lfstr)) return false;
925         int lftlindex = lfstr.index("<A NAME=\"TL\">");
926         if (lftlindex>=0) if ((lftlindex=lfstr.index("</OL>",lftlindex))>=0) lfstr.at(lftlindex,1) = "<LI><A HREF=\""+(RELLISTSDIR+newreltlhead)+"\">Task Log: section initiation date mark "+curdate+"</A>\n<";
927         if (lftlindex<0) EOUT << "dil2al: Unable to update Task Log sections list in " << listfile << " in add_TL_section(), continuing as is\n";
928         if (!write_file_from_String(listfile,lfstr,"Main List")) return false;
929         // update Task Log symbolic link in tasklog
930         if (unlink(tasklog)<0) {
931                 EOUT << "dil2al: Unable to remove Task Log symbolic link " << tasklog << " to task-log." << curtlid << ".html in add_TL_section()\n";
932                 return false;
933         }
934         if (symlink(newreltlhead,tasklog)<0) {
935                 EOUT << "dil2al: Unable to create Task Log symbolic link " << tasklog << " to " << newreltlhead << " in add_TL_section()\n";
936                 return false;
937         }
938         // set variables to new Task Log section
939         tl = newtlsection;
940         taskloghead = newtaskloghead;
941         return true;
942 }
String AL_Day_Marker (String & dstfile, AL_Day * ald)
Definition at line 74 of file alcomp.cc.
References AL_Day::DayDate(), AL_Day::DayMaxt(), AL_Day::DayStart(), AL_Day::DayStartMin(), AL_Day::DayType(), DEFAULTALDAYEMPHASIS, AL_Day::Expanded(), HTML_put_href(), HTML_put_table_cell(), HTML_put_table_row(), PLL_LOOP_FORWARD, relurl(), AL_Day::TD_Head(), time_stamp(), time_stamp_GM(), and AL_Day::Total().
Referenced by Active_List::generate_focused_AL(), and Active_List::generate_wide_AL().
74                                                      {
75 // Generates a table row with data about ald for inclusion in AL files
76         if (!ald) return String("");
77         String daytxt = "<!-- @select_TL_DIL_refs: SKIP ROW@ --><B>Day " + time_stamp("%Y%m%d",ald->DayDate())
78                         + "</B> (suggested start " + time_stamp_GM("%H:%M",ald->DayStart()) + ", limits "
79                         + time_stamp_GM("%H:%M",ald->DayStartMin()) + '-' + time_stamp_GM("%H:%M",ald->DayMaxt());
80         if (ald->DayType()==1) daytxt += ", worked " + time_stamp_GM("%H:%M",alworked);
81         daytxt += "), "; daytxt += dec(ald->Total()); daytxt += " task chunks";
82         if (ald->Expanded()) daytxt += " (expanded)";
83         if (ald->TD_Head()) {
84                 String relidfile(relurl(dstfile,idfile));
85                 daytxt += ", target dates: ";
86                 PLL_LOOP_FORWARD(AL_TD,ald->TD_Head(),1) {
87                         daytxt += HTML_put_href((relidfile+'#')+e->DE()->chars(),"DIL#" + String(e->DE()->chars()));
88                         daytxt += " (" + time_stamp("%H:%M",e->DE()->Target_Date()) + ')';
89                         if (e->Next()) daytxt += ", ";
90                 }
91         }
92         return HTML_put_table_row(DEFAULTALDAYEMPHASIS,HTML_put_table_cell("",daytxt)) + '\n';
93 }
String AL_Passed_Target_Dates (String & dstfile, AL_TD * atd)
Definition at line 95 of file alcomp.cc.
References Elipsis_At(), HTML_put_form(), HTML_put_form_checkbox(), HTML_put_form_input(), HTML_put_form_radio(), HTML_put_form_reset(), HTML_put_form_submit(), HTML_put_form_text(), HTML_put_href(), HTML_remove_tags(), PLL_LOOP_FORWARD, relurl(), and time_stamp().
Referenced by Active_List::generate_focused_AL().
95                                                              {
96 // Generates a list of passed target date DIL entries
97   if (atd) {
98     String diltext;
99     String passedstr(HTML_put_form_input("hidden","name=\"dil2al\" value=\"MEtgroup\"")+"\n<B>Passed Target Dates:</B>\n<UL>\n"), relidfile(relurl(dstfile,idfile));
100     PLL_LOOP_FORWARD(AL_TD,atd,1) {
101       if (e->DE()->Entry_Text()) diltext = (*e->DE()->Entry_Text());
102       else diltext="";
103       HTML_remove_tags(diltext);
104       Elipsis_At(diltext,30);
105       String deidstr(e->DE()->chars());
106       passedstr += "<LI>" + HTML_put_href((relidfile+'#')+deidstr,"DIL#"+ deidstr)
107         + "[<A HREF=\"file:///cgi-bin/dil2al?dil2al=MEI&DILID="+deidstr+"\">edit</A>] ("
108         + time_stamp("%Y%m%d%H%M",e->DE()->Target_Date()) + ") "
109         + HTML_put_form_checkbox(String("TDCHKBX")+deidstr,"noupdate","",true)
110         + HTML_put_form_text(String("TD")+deidstr,12) + ' ' + diltext + '\n';
111     }
112     passedstr += "</UL>\n"+HTML_put_form_radio("TDupdate","group","Minimize fragmentation",true)
113       + ' '+HTML_put_form_radio("TDupdate","direct","Direct")+"<BR>\n"
114       + HTML_put_form_submit("Update")+' '+HTML_put_form_reset()+"\n<P>\n";
115     return HTML_put_form(htmlformmethod,htmlforminterface,passedstr);
116   } else return String("");
117 }
void auto_interactive (String & autostr, String message, char * lbuf, int llen)
Definition at line 1916 of file utilities.cc.
References String::del().
Referenced by chunk_controller().
1916                                                                                {
1917 // enables interactive responses or takes responses from autostr if available
1918         if (autostr=="") {
1919                 cout << message;
1920                 cin.getline(lbuf,llen);
1921         } else {
1922                 strcpy(lbuf,(const char *) autostr);
1923                 autostr.del(0,1);
1924         }
1925 }
bool backup_and_rename (String filename, String message, bool isnew = false)
Definition at line 2016 of file utilities.cc.
References EOUT, and VOUT.
Referenced by add_new_to_DIL(), cmdline_extract_paper_novelties(), create_new_DIL(), extract_paper_plan_to_paper(), send_dil_to_DIL(), and write_file_from_String().
2016                                                                             {
2017 // Backup previous version of file with date stamp and make
2018 // new version current.
2019         String backupname = filename+'.'+curdate+".bak";
2020         if (!isnew) if (rename(filename,backupname)<0) {
2021                 if (errno!=ENOENT) {
2022                         EOUT << "dil2al: Unable to rename " << filename << " to " << backupname << " in backup_and_rename()\n(New version remains in " << filename << ".new)\n";
2023                         return false;
2024                 } else EOUT << "dil2al: Warning - no old version of " << filename << " to backup in backup_and_rename()\n";
2025         }
2026         if (rename(filename+".new",filename)<0) {
2027                 EOUT << "dil2al: Unable to rename " << filename << ".new to " << filename << " in backup_and_rename()\n(New version remains in " << filename << ".new)\nRestoring previous " << filename << '\n';
2028                 if (!isnew) if (rename(backupname,filename)<0) EOUT << "dil2al: Unable to restore " << backupname << " to " << filename << '\n';
2029                 return false;
2030         }
2031         if (verbose) { // *** perhaps this should be suppressed if errno==ENOENT was caught above
2032                 if (isnew) VOUT << message << " initialized as " << filename << '\n';
2033                 else VOUT << "Old " << message << " file moved to " << backupname << '\n';
2034         }
2035         return true;
2036 }
int BigRegex_freq (String & str, const char * rxstr)
Definition at line 1809 of file utilities.cc.
Referenced by Assess_Paper_Correction_Time(), BigRegex_freq(), and decide_add_TL_chunk().
1809                                                     {
1810         BigRegex rx(rxstr);
1811         return BigRegex_freq(str,rx);
1812 }
int BigRegex_freq (String & str, String rxstr)
Definition at line 1804 of file utilities.cc.
1804                                               {
1805         BigRegex rx(rxstr);
1806         return BigRegex_freq(str,rx);
1807 }
int BigRegex_freq (String & str, const BigRegex & rx)
Definition at line 1798 of file utilities.cc.
1798                                                      {
1799         int i = 0, cnt = 0;
1800         while ((i=str.index(rx,String::SEARCH_END,i))>=0) cnt++;
1801         return cnt;
1802 }
String chunk_controller (String controllercmd)
Definition at line 6 of file controller.cc.
References ANSI_BOLD_OFF, ANSI_BOLD_ON, auto_interactive(), decide_add_TL_chunk(), EOUT, get_TL_head(), make_note(), read_file_into_String(), stop_TL_chunk(), time_stamp(), VOUT, and write_file_from_String().
Referenced by dil2al_commands(), and schedule_controller().
6                                               {
7 // Called timechunk minutes after starting a task chunk
8 // (e.g. via at-jobs or a timer daemon, which could be
9 // constructed as an AfterStep Wharf applet).
10 // It can also be called before timechunk minutes have
11 // passed if the chunk is stopped early.
12 // As previous chunks are closed with stop_TL_chunk() where
13 // necessary with options C,S or T, AL updating options
14 // determine if and how the current AL and closed chunk's DIL
15 // entry should be updated, and the corresponding update is done.
16         const int LLEN = 10240;
17         char lbuf[LLEN];
18         // check if audio-visual flag is to be made noticable
19         if (showflag) {
20                 cout << "\a";
21                 if (flagcmd!="") {
22                         if (system(flagcmd)<0) EOUT << "dil2al: Unable to show visual flag in chunk_controller(), continuing\n";
23                 }
24         }
25         // show next AL item(s) (may involve recomputing)
26 //*** recomputation of AL not yet included
27 #ifdef DEBUG
28         cout << "dil2al: DEBUG - Recomputation of ALs in chunk_controller() not yet implemented\n";
29 #endif
30         // offer opportunity to make a Task Log entry
31         bool madenote = false;
32         chunkcreated = false; // reset process variable
33         if (useansi) cout << ANSI_BOLD_ON; // bold on
34         auto_interactive(controllercmd,"Make Note/Task Log entry? (y/N) ",lbuf,LLEN);
35         if (useansi) cout << ANSI_BOLD_OFF; // bold off
36         if ((lbuf[0]=='y') || (lbuf[0]=='Y')) {
37                 // make Task Log entry
38                 if (!make_note()) EOUT << "dil2al: Unable to make note in chunk_contorller(), continuing as is\n";
39                 madenote = true;
40         }
41         // offer controller options
42         lbuf[0]='\0'; String chunkid;
43         while (lbuf[0]=='\0') {
44                 String message = "\nOptions:\n[C]ontinue Task Chunk if Time Remaining else Start New Task Chunk\n";
45                 if (!chunkcreated) message += "[S]tart New Task Chunk (new task context)\n";
46                 message += "S[t]op Task Chunk (pause list tasks)\nE[x]it Retaining Current State (ignore list suggestions)\n";
47                 if (useansi) cout << ANSI_BOLD_ON; // bold on
48                 auto_interactive(controllercmd,message,lbuf,LLEN);
49                 if (useansi) cout << ANSI_BOLD_OFF; // bold off
50                 // refresh curtime to avoid misrepresentations due to long delay before option selection
51                 // but don't change time if madenote to properly detect chunkid==curtime
52                 // if a new chunk was made during make_note()
53                 if (!madenote) curtime = time_stamp("%Y%m%d%H%M");
54                 String tl; int tlinsertloc;
55                 switch (lbuf[0]) {
56                         case 'c': case 'C':
57                                 if (verbose) VOUT << "Continuing according to task list chunk controller suggestions\n";
58                                 tlinsertloc = -1;
59                                 if (!read_file_into_String(get_TL_head(),tl)) return String("");
60                                 if (tl=="") return tl;
61                                 if ((chunkid=decide_add_TL_chunk(tl,tlinsertloc,true,false))=="") return String("");
62                                 break;
63                         case 's': case 'S':
64                                 if (!chunkcreated) {
65                                         if (verbose) VOUT << "Starting task chunk with new context\n";
66                                         tlinsertloc = -1;
67                                         if (!read_file_into_String(get_TL_head(),tl)) return String("");
68                                         if (tl=="") return tl;
69                                         if ((chunkid=decide_add_TL_chunk(tl,tlinsertloc,false,false))=="") return String("");
70                                 } else {
71                                         EOUT << "dil2al: Unknown option `" << lbuf[0] << "'\n";
72                                         lbuf[0]='\0';
73                                 }
74                                 break;
75                         case 't': case 'T':
76 //*** instead of this approach, which exits once list tasks are paused
77 //*** it is possible to stay in this while loop and offer exit as well
78 //*** as start with comparetimes=false in the decide_add_TL_chunk() call
79                                 if (verbose) VOUT << "Stopping task chunk and pausing list tasks\n";
80                                 if (!read_file_into_String(get_TL_head(),tl)) return String("");
81                                 if (tl=="") return tl;
82                                 stop_TL_chunk(tl);
83                                 if (!write_file_from_String(taskloghead,tl,"Task Log")) return String("");
84                                 chunkid = "-1";
85                                 break;
86                         case 'x': case 'X':
87                                 if (verbose) VOUT << "Exiting and retaining current task state\n";
88                                 chunkid = "-2";
89                                 break;
90                         default:
91                                 EOUT << "dil2al: Unknown option `" << lbuf[0] << "'\n";
92                                 lbuf[0] = '\0';
93                 }
94         }
95         return chunkid;
96 }
bool cmdline_extract_paper_novelties (String filepaper)
Definition at line 65 of file tlfilter.cc.
References String::after(), backup_and_rename(), String::before(), EOUT, extract_paper_novelties(), String::prepend(), and res.
Referenced by dil2al_commands().
65                                                        {
66 // Commandline interface to the extraction of NOVELTY tagged items
67         bool res;
68         String fname, paperplanurl;
69         fname = filepaper.before("+");
70         if (fname == "") {
71                 fname = filepaper;
72                 paperplanurl = homedir+"doc/tex/somepaper/somepaper.html"; // dummy URL
73                 res = extract_paper_novelties(fname,paperplanurl,cout);
74         } else {
75                 paperplanurl = filepaper.after("+");
76                 if (paperplanurl == "") {
77                         paperplanurl = homedir+"doc/tex/somepaper/somepaper.html"; // dummy URL
78                         res = extract_paper_novelties(fname,paperplanurl,cout);
79                 } else {
80                         if (paperplanurl[0]!='/') paperplanurl.prepend(homedir);
81                         ofstream ostr(paperplanurl+".new");
82                         if (!ostr) {
83                                 EOUT << "dil2al: Unable to create " << paperplanurl << ".new in cmdline_extract_paper_novelties()\n";
84                                 return false;
85                         }
86                         ifstream istr(paperplanurl);
87                         bool isnew = (!istr);
88                         if (!isnew) ostr << istr.rdbuf(); // copy existing content (without regard to a possible </BODY> tag)
89                         istr.close();
90                         res = extract_paper_novelties(fname,paperplanurl,ostr);
91                         ostr.close();
92                         if (!backup_and_rename(paperplanurl,"Paper Plan",isnew)) return false;
93                 }
94         }
95         return true;
96 }
bool cmdline_extract_paper_plan_to_paper (String ppfile)
Definition at line 1253 of file ppfilter.cc.
References String::after(), String::before(), EOUT, extract_paper_plan_to_paper(), and String::prepend().
Referenced by dil2al_commands().
1253                                                         {
1254 // Commandline interface to extract_paper_plan_to_paper()
1255         String ppname, poutline, pprevious;
1256         ppname = ppfile.before("+");
1257         if (ppname == "") {
1258                 ppname = ppfile;
1259                 EOUT << "dil2al: Paper extraction without specific paper outline not yet supported\n";
1260                 return false;
1261         } else {
1262                 poutline = ppfile.after("+");
1263                 if (poutline == "") {
1264                         EOUT << "dil2al: Paper extraction without specific paper outline not yet supported\n";
1265                         return false;
1266                 } else {
1267                         pprevious = poutline.after("+");
1268                         if (pprevious != "") {
1269                                 poutline = poutline.before("+");
1270                                 if (pprevious[0]!='/') pprevious.prepend(homedir);
1271                         }
1272                         if (ppfile[0]!='/') ppfile.prepend(homedir);
1273                         if (poutline[0]!='/') poutline.prepend(homedir);
1274                         return extract_paper_plan_to_paper(ppname,poutline,pprevious);
1275                 }
1276         }
1277 }
bool confirmation (String message, char nondefault)
Definition at line 1907 of file utilities.cc.
Referenced by extract_hierarchy_depth_decrease_to_paper(), extract_hierarchy_depth_increase_to_paper(), extract_recursively(), extract_required_item_to_paper(), financial_notes(), select_TL_DIL_refs(), and stop_TL_chunk().
1907                                                    {
1908 // requests confirmation, returns false if the response is nondefault
1909         const int LLEN = 16;
1910         char lbuf[LLEN];
1911         cout << message;
1912         cin.getline(lbuf,LLEN);
1913         return (lbuf[0]!=nondefault);
1914 }
void convert_item_content_to_TeX (String & itemcontent)
Definition at line 673 of file ppfilter.cc.
References String::gsub().
Referenced by extract_recursively().
673                                                        {
674         // conversions to TeX (also ensures that lines do not exceed the TeX buffer size)
675         //      - remove Novelty Marker tags
676         itemcontent.gsub(BigRegex("[<]A[        ]+[Nn][Aa][Mm][Ee][     ]*=[    ]*\"NOVELTY-[^>]*[>][[][^]]*N[^]]*[]]"),"");
677         //      - identify content hyperlink references
678         itemcontent.gsub(BigRegex("[<]A[        ]+[^>]*[Hh][Rr][Ee][Ff][        ]*=[    ]*\"\\([^\"]+\\)\"[^>]*[>]"),"@HRef::_1@",'_');
679         //      - cite, but do not recurse into bibliography references
680         itemcontent.gsub(BigRegex("\\([[][^]]*\\)?@HRef::[^@]*"+RX_Search_Safe(bibindexfilename)+"#\\([^@]+:[^@]+\\)@\\([^]]*[]]\\)?"),"\\cite{_2}",'_');
681         //      - sometimes citations do not contain an HRef, warn if this appears to be the case and apply citation tentatively
682         int citeerrnum = itemcontent.gsub(BigRegex("[[]\\([A-Z]+:[A-Z]+[,A-Z:]*\\)[]]"),"\\cite{_1}",'_');
683         if (citeerrnum>0) EOUT << "dil2al: " << citeerrnum << " apparent citations without HRef encountered in convert_item_content_to_TeX(), continuing\n";
684         //      - convert paragraph and line-break codes
685         itemcontent.gsub("\n<P>\n","\n\n");
686         itemcontent.gsub("<P>","\n");
687         itemcontent.gsub(BigRegex("\\([^\n]\\)[\n]?[<][Bb][Rr][>]"),"_1\\\\",'_');
688 //*** the following two lines can be removed when Thesis Log has been converted to the Task Log format
689         itemcontent.gsub(BigRegex("[<]!--[      ]*entry Begin[  ]*--[>][^]]+[]][        ]*[<]/FONT[>]"),"");
690         itemcontent.gsub(BigRegex("[<]!--[      ]*chunk End[    ]*--[>][        ]*[<][Ii][>][^<]+[<]/[Ii][>]"),"");
691 //*** possibly remove the following conversions
692         //      - convert text attribute codes
693         itemcontent.gsub(BigRegex("[<]\\([Bb]\\|[Ss][Tt][Rr][Oo][Nn][Gg]\\)[>]"),"{\\bf ");
694         itemcontent.gsub(BigRegex("[<]\\([Ii]\\|[Ee][Mm]\\)[>]"),"{\\em ");
695         itemcontent.gsub(BigRegex("[<]/\\([Bb]\\|[Ss][Tt][Rr][Oo][Nn][Gg]\\|[Ii]\\|[Ee][Mm]\\)[>]"),"}");
696 //*** possibly remove conversions above
697         //      - remove remaining HTML tags
698         itemcontent.gsub(BigRegex("[<][^>]*[>]"),"");
699         //      - convert HTML character codes
700         itemcontent.gsub("&lt;","<");
701         itemcontent.gsub("&gt;",">");
702         itemcontent.gsub("&amp;","\\&");
703         //      - escape LaTeX special characters
704         itemcontent.gsub(BigRegex("\\([^\\]\\)\\([#&_%]\\)"),"_1\\_2",'_');
705 //*** convert GESNlib variable names to GESN convention standard labels as found in nse.label-equivalence.tex
706 //*** could do that to the source once instead
707         // insure lines are at most around 1000 characters long
708         Text_limit_line_length(itemcontent,1000,1500);
709 }
int copy_until_line (ifstream * lf, ofstream * of, const char * pattern, char * lbuf, int llen)
Definition at line 2248 of file utilities.cc.
References EOUT.
Referenced by create_new_DIL(), make_note(), and send_dil_to_DIL().
2248                                                                                                {
2249 // returns 1 if line was encountered, 0 if not, and <0 for errors
2250 // the line containing pattern is not copied, but is returned in lbuf
2251         regex_t re;
2252         int mres;
2253         if (!lf) {
2254                 EOUT << "dil2al: input file not open in copy_until_line()\n";
2255                 return -1;
2256         }
2257         if (!of) {
2258                 EOUT << "dil2al: output file not open in copy_until_line()\n";
2259                 return -1;
2260         }
2261         if (regcomp(&re,pattern, REG_EXTENDED|REG_NOSUB) != 0) {
2262                 EOUT << "dil2al: Unable to compile regular expression in copy_until_line()\n";
2263                 return -2;
2264         }
2265         mres = 1;
2266         cout << "dil2al WARNING: copy_until_line(<from>,<to>," << pattern << ",<lbuf>,<llen>) may be broken as EOF is not detected when line length exceeds llen=" << llen << ", this code should use BigRegex functions instead!\n";
2267         while (mres!=0) {
2268                 if (lf->eof()) {
2269                         regfree(&re);
2270                         return 0;
2271                 }
2272                 lf->getline(lbuf,llen);
2273                 mres = regexec(&re,lbuf, (size_t) 0, NULL, 0);
2274                 if ((mres != 0) && (mres != REG_NOMATCH)) {
2275                         EOUT << "dil2al: Internal error while matching in copy_until_line()\n";
2276                         regfree(&re);
2277                         return -3;
2278                 }
2279                 if (mres!=0) (*of) << lbuf << endl;
2280         }
2281         regfree(&re);
2282         return 1;
2283 }
bool create_new_DIL (String dilfile)
Definition at line 409 of file diladmin.cc.
References backup_and_rename(), copy_until_line(), EOUT, RELLISTSDIR, substring_from_line(), and VOUT.
Referenced by dil2al_commands(), and send_dil_to_DIL().
409                                     {
410         const int LLEN = 10240;
411         char lbuf[LLEN];
412         String dilid[2], dilfilename, diltitle;
413         // get name of DIL file regardless of whether it was a relative or absolute path
414         if (!substring_from_line("([^/]+)$",2,dilid,(const char *) dilfile)) {
415                 EOUT << "dil2al: Unable to parse name from DIL file path in create_new_DIL()\n";
416                 return false;
417         } else dilfilename = dilid[1];
418         dilfile=basedir+RELLISTSDIR+dilfilename;
419         if (verbose) VOUT << "Creating new DIL file " << dilfile << '\n';
420         ifstream df(dilfile);
421         if (df) {
422                 df.close();
423                 cout << "DIL file " << dilfilename << " already exists, overwrite? (y/N) ";
424                 cin.getline(lbuf,LLEN);
425                 if ((lbuf[0]!='y') && (lbuf[0]!='Y')) return false;
426         }
427         ofstream ndf(dilfile);
428         if (ndf) {
429                 if (verbose) VOUT << "Initializing new DIL file\n";
430                 cout << "DIL title for " << dilfilename << ": ";
431                 cin.getline(lbuf,LLEN); diltitle = lbuf;
432                 ndf << "<HTML>\n<HEAD>\n<TITLE>DIL: " << diltitle << "</TITLE>\n";
433                 ndf << "</HEAD>\n<BODY BGCOLOR=\"#000000\" TEXT=\"#F0E0A0\" LINK=\"#AFAFFF\" VLINK=\"#7F7FFF\">\n";
434                 ndf << "<H1><FONT COLOR=\"#00FF00\">DIL: " << diltitle << "</FONT></H1>\n\n";
435                 cout << "DIL keywords and relevance, e.g. neuron (1.0), synapse (1.0): ";
436                 cin.getline(lbuf,LLEN);
437                 ndf << "<B>Topic Keywords, k_{top} (and relevance in [0,1]):</B> " << lbuf << "\n<P>\n\n";
438                 ndf << "<TABLE WIDTH=\"100%\" CELLPADDING=3 BORDER=2>\n<!-- dil2al: DIL begin -->\n\n<!-- dil2al: DIL end -->\n</TABLE>\n\n\n";
439                 ndf << "<LI><A HREF=\"detailed-items-by-ID.html\">Detailed Items by ID</A>\n<LI><A HREF=\"../lists.html#DIL\">Topical Detailed Items Lists</A>\n<P>\n";
440                 ndf << "<HR>~/doc/<A HREF=\"../maincont.html\">html</A>/<A HREF=\"../lists.html\">lists</A>/"
441                         << dilfilename << " <FONT COLOR=\"#AFAFAF\"><I>&nbsp;&nbsp;&nbsp;(created " << curdate << ", Randal A. Koene)</I></FONT>\n\n</BODY>\n";
442                 ndf.close();
443         } else {
444                 EOUT << "dil2al: Unable to create file " << dilfile << " in create_new_DIL()\n";
445                 return false;
446         }
447         // Add DIL title and reference to list.html
448         df.open(listfile);
449         if (!df) {
450                 EOUT << "dil2al: Unable to open " << listfile << " in create_new_DIL()\n";
451                 return false;
452         }
453         ndf.open(listfile+".new");
454         if (!ndf) {
455                 EOUT << "dil2al: Unable to create " << listfile << ".new in create_new_DIL()\n";
456                 return false;
457         }
458         if (verbose) VOUT << "Adding new DIL to " << listfile << '\n';
459         if (copy_until_line(&df,&ndf,"<H1><A NAME=\"DIL\">",lbuf,LLEN)<=0) {
460                 EOUT << "dil2al: No DIL header ``<H1><A NAME=\"DIL\">'' found in create_new_DIL()\n";
461                 return false;
462         }
463         ndf << lbuf << endl;
464         if (copy_until_line(&df,&ndf,"</UL>",lbuf,LLEN)<=0) {
465                 EOUT << "dil2al: No DIL list end ``</UL>'' found in create_new_DIL()\n";
466                 return false;
467         }
468         ndf << "<LI><A HREF=\"" << RELLISTSDIR << dilfilename << "\">" << diltitle << "</A>\n";
469         ndf << lbuf << endl;
470         ndf << df.rdbuf();
471         df.close();
472         ndf.close();
473         if (!backup_and_rename(listfile,"lists index")) return false;
474         return true;
475 }
int D2A_get_tag (String & d2astr, int strloc, String d2atag, String & tagtext)
Definition at line 2396 of file utilities.cc.
References String::at(), EOUT, String::index(), BigRegex::match_info(), and String::SEARCH_END.
Referenced by Assess_Paper_Correction_Time().
2396                                                                               {
2397 // searches for a dil2al standardized tag with the specific regex
2398 // id d2atag and returns the corresponding specific information
2399 // in tagtext, as well as the position in d2astr immediately
2400 // following the tag
2401         BigRegex tm('@'+d2atag+":\\([^@]*\\)@");
2402         if ((strloc=d2astr.index(tm,String::SEARCH_END,strloc))>=0) {
2403                 int s,l;
2404                 if (!tm.match_info(s,l,1)) return -1;
2405                 if (l==0) EOUT << "dil2al: Warning - Non-specific tag at " << s << " in D2A_get_tag(), continuing\n";
2406                 tagtext = d2astr.at(s,l);
2407         }
2408         return strloc;
2409 }
String date_string ()
Definition at line 1852 of file utilities.cc.
References time_stamp().
Referenced by dil2al_commands(), and main().
1852                      {
1853         return time_stamp("%Y%m%d");
1854 }
String decide_add_TL_chunk (String & tl, int & tlinsertloc, bool comparetimes, bool createifgreater = true)
Definition at line 971 of file tladmin.cc.
References add_TL_chunk_or_entry(), add_TL_section(), ANSI_BOLD_OFF, ANSI_BOLD_ON, BigRegex_freq(), EOUT, locate_most_recent_TL_chunk(), TCS_ASK, TCS_CURRENT, TCS_NEW, time_stamp_diff(), TSS_ASK, and TSS_NEW.
Referenced by chunk_controller(), and process_note_TL().
971                                                                                                            {
972 // Add a Task Log chunk based on strategies and time since creation
973 // of most recent chunk
974 // time-based decisions can be either
975 // create-if-greater-than-chunksize-plus-slack or
976 // create-unless-smaller-than-chunksize
977 // initialize tlinsertloc with -1 to search from end of Task Log
978 // tlinsertloc is updated for use when adding entry to Task Log
979 // returns chunkid
980         // find most recent TL chunk (immediately preceding @INSERT-TL-NOTE@ if present)
981         const int LLEN = 10240;
982         char lbuf[LLEN];
983         String chunkid; bool newchunk = !createifgreater;
984         if ((tlinsertloc = locate_most_recent_TL_chunk(tl,tlinsertloc,&chunkid))<0) return String("");
985         if (chunkid=="") newchunk=true;
986         else {
987                 // compare chunk time stamp with curtime
988 #ifdef DEBUG
989                 cout << "decision chunkid = " << chunkid << "\ncurtime = " << curtime << '\n';
990 #endif
991                 if (createifgreater) {
992                         // test if curtime > chunk_creation_time+timechunksize+timechunkslack
993                         if ((comparetimes) && ((time_stamp_diff(chunkid,curtime)/60)>(timechunksize+timechunkslack))) {
994                                 if (timechunkoverstrategy==TCS_NEW) newchunk=true;
995                                 else if (timechunkoverstrategy==TCS_ASK) {
996                                         if (useansi) cout << ANSI_BOLD_ON; // bold on
997                                         cout << "\nDifference between time stamp of current Task Log chunk and current time is\ngreater than " << (timechunksize+timechunkslack) << " minutes. Create new Task Log chunk? (y/N) ";
998                                         if (useansi) cout << ANSI_BOLD_OFF; // bold off
999                                         cin.getline(lbuf,LLEN);
1000                                         if ((lbuf[0]=='y') || (lbuf[0]=='Y')) newchunk=true;
1001                                 }
1002                         }
1003                 } else {
1004                         // test if curtime == chunk_creation_time, e.g. created during make_note() opportunity in chunk_controller()
1005                         if (chunkid==curtime) newchunk=false;
1006                         else {
1007                                 // test if curtime < chunk_creation_time+timechunksize
1008                                 if ((comparetimes) && ((time_stamp_diff(chunkid,curtime)/60)<timechunksize)) {
1009                                         if (timechunkunderstrategy==TCS_CURRENT) newchunk=false;
1010                                         else if (timechunkunderstrategy==TCS_ASK) {
1011                                                 if (useansi) cout << ANSI_BOLD_ON; // bold on
1012                                                 cout << "\nDifference between time stamp of current Task Log chunk and current time is\nless than " << timechunksize << " minutes. Create new Task Log chunk anyway? (y/N) ";
1013                                                 if (useansi) cout << ANSI_BOLD_OFF; // bold off
1014                                                 cin.getline(lbuf,LLEN);
1015                                                 if ((lbuf[0]!='y') && (lbuf[0]!='Y')) newchunk=false;
1016                                         }
1017                                 }
1018                         }
1019                 }
1020         }
1021         if (newchunk) {
1022                 bool newsection = false;
1023                 // if TL contains more than sectionsize chunks consider starting a new section
1024                 int numchunks = BigRegex_freq(tl,"[<]!--[       ]+chunk Begin[  ]+--[>]");
1025                 if (numchunks>=sectionsize) {
1026                         if (sectionstrategy==TSS_NEW) newsection = true;
1027                         else if (sectionstrategy==TSS_ASK) {
1028                                 if (useansi) cout << ANSI_BOLD_ON; // bold on
1029                                 cout << "\nThere are " << numchunks << " chunks in this Task Log section. Create new section? (y/N) ";
1030                                 if (useansi) cout << ANSI_BOLD_OFF; // bold off
1031                                 cin.getline(lbuf,LLEN);
1032                                 if ((lbuf[0]=='y') || (lbuf[0]=='Y')) newsection=true;
1033                         }
1034                 }
1035                 if (newsection) {
1036                         // add a new section to the Task Log
1037                         if (!add_TL_section(tl)) {
1038                                 EOUT << "dil2al: Unable to add new Task Log section in decide_add_TL_chunk()\n";
1039                                 return String("");
1040                         }
1041                 }
1042                 // add a new chunk to the Task Log
1043                 if ((chunkid = add_TL_chunk_or_entry(tl,chunkid,true,chunkid,tlinsertloc))=="") {
1044                         EOUT << "dil2al: Unable to add new Task Log chunk in decide_add_TL_chunk()\n";
1045                         return String("");
1046                 }
1047         }
1048         return chunkid;
1049 }
bool Diagnostic (String diagnosticstr)
Definition at line 348 of file dil2al.cc.
References Detailed_Items_List::Binary_Cache_Diagnostic().
Referenced by dil2al_commands().
348                                       {
349   // run a self-diagnostic test
350   if (diagnosticstr=="cache") {
351     Detailed_Items_List dilist;
352     return dilist.Binary_Cache_Diagnostic();
353   }
354   return false;
355 }
int DIL_entry_target_date_qsort_compare (const void * vde1, const void * vde2)
Definition at line 1774 of file utilities.cc.
References MAXTIME_T.
Referenced by Detailed_Items_List::Sort_by_Target_Date().
1774                                                                               {
1775 // used with qsort() (<stdlib.h>)
1776 // Treats unspecified self-referential target dates as MAXTIME
1777 // for the ordering of the corresponding DIL entry  - and avoids
1778 // the accompanying warning messages.
1779 // (This is useful when groups of DIL entries with desired
1780 // target dates are sorted, in which some DIL entries are marked
1781 // with -2 codes).
1782 // Note: ISO C++ is strict about providing the correct function
1783 // declaration in cases such as the call to qsort(). This function
1784 // was therefore rewritten from the original declaration,
1785 // DIL_entry_target_date_qsort_compare(DIL_entry ** de1, DIL_entry ** de2)
1786 // - please keep in mind that the elements are of type DIL_entry **,
1787 // i.e. arrays/pointers of pointers to objects.
1788         DIL_entry ** de1 = (DIL_entry **) vde1;
1789         DIL_entry ** de2 = (DIL_entry **) vde2;
1790         time_t t1 = MAXTIME_T, t2 = MAXTIME_T;
1791         if (*de1) t1 = (*de1)->Propagated_Target_Date(false);
1792         if (*de2) t2 = (*de2)->Propagated_Target_Date(false);
1793         if (t1==t2) return 0;
1794         if (t1<t2) return -1;
1795         return 1;
1796 }
bool DIL_Hierarchy_cmd (String dilidstr, int maxdepth = 50)
Definition at line 1545 of file diladmin.cc.
References String::after(), String::before(), String::del(), String::empty(), String::from(), String::length(), Tabbed_DIL_Hierarchy(), Tabbed_FORM_DIL_Hierarchy(), Tabbed_HTML_DIL_Hierarchy(), VOUT, and write_file_from_String().
Referenced by dil2al_commands(), and extract_DIL_IDs_from_form().
1545                                                            {
1546 // visualize a DIL hierarchy
1547 #ifdef DEBUG_HIERARCHY_EXPRESSIONS
1548   VOUT << "&&& DIL_Hierarchy_cmd: dilidstr = " << dilidstr << '\n';
1549 #endif
1550   String hierarchyfile("");
1551   // 1. Get optional @f@ hierarchyfile reference
1552   if ((dilidstr.length()>=2) && (dilidstr[0]=='@')) {
1553     dilidstr.del(0,1);
1554     hierarchyfile = dilidstr.before('@');
1555     dilidstr = dilidstr.after('@');
1556   }
1557 #ifdef DEBUG_HIERARCHY_EXPRESSIONS
1558   VOUT << "&&& DIL_Hierarchy_cmd: hierarchyfile = " << hierarchyfile << " dilidstr = " << dilidstr << '\n';
1559 #endif
1560   // 2. Get optional type identifier
1561   if ((dilidstr.length()>=4) && (String(dilidstr.before(4))=="FORM")) {
1562     dilidstr = dilidstr.from(4);
1563 #ifdef DEBUG_HIERARCHY_EXPRESSIONS
1564     VOUT << "&&& DIL_Hierarchy_cmd: type is FORM, dilidstr = " << dilidstr << '\n';
1565 #endif
1566     if ((calledbyforminput) && (hierarchyfile.empty())) VOUT << "</PRE><!-- "; // clean up HTML output (dil2al processing output can still be inspected by looking at the HTML source)
1567     dilidstr = Tabbed_FORM_DIL_Hierarchy(dilidstr,maxdepth);
1568     // *** If I want to give hierarchy.html a proper head and tail then I
1569     //     can detect "if ((!hierarchyfile.empty()) && (!dilidstr.empty()))"
1570     //     here and prepend the head and append the tail to dilidstr if true.
1571   } else if ((dilidstr.length()>4) && (String(dilidstr.before(4))=="HTML")) {
1572     dilidstr = dilidstr.from(4);
1573     dilidstr = Tabbed_HTML_DIL_Hierarchy(dilidstr,maxdepth);
1574   } else dilidstr = Tabbed_DIL_Hierarchy(dilidstr,maxdepth);
1575   if (dilidstr.empty()) return false;
1576   if (!hierarchyfile.empty()) {
1577     VOUT << "Writing DIL Hierarchy to file " << hierarchyfile << " (<A HREF=\"file://" << hierarchyfile << "\">" << hierarchyfile << "</A>\n";
1578     return write_file_from_String(hierarchyfile,dilidstr,"DIL Hierarchy");
1579   }
1580   VOUT << dilidstr;
1581   return true;
1582 }
long* DIL_Required_Task_Chunks (DIL_entry ** dep, int deplen)
Definition at line 273 of file alcomp.cc.
References DIL_ID::chars(), DIL_entry::Completion_State(), EOUT, and DIL_entry::Time_Required().
Referenced by generate_AL().
273                                                               {
274 // returns an array with the number of task chunks
275 // required to complete the DIL entries in the array
276 // dep with length deplen
277   long * req = new long[deplen];
278   float completion;
279   long c_size = ((long) timechunksize)*60;
280   for (int i=0; i<deplen; i++) {
281     req[i] = dep[i]->Time_Required();
282     completion = dep[i]->Completion_State();
283     if (completion<0.0) completion = 1.0; // negative completion values have special meaning but do imply that the task is no longer scheduled to be completed
284     if (completion>1.0) {
285       EOUT << "dil2al: Completion ratio exceeds 1.0 for DIL#";
286       if (calledbyforminput) EOUT << "<A HREF=\"" << idfile << '#' << dep[i]->chars() << "\">";
287       EOUT << dep[i]->chars();
288       if (calledbyforminput) EOUT << "</A>";
289       EOUT << " in DIL_Required_Task_Chunks(), continuing\n";
290       req[i] = 0;
291       continue;
292     }
293     completion = ceil(((double) req[i])*(1.0-completion)); // determine remaining time required
294     req[i] = (long) completion;
295     if (req[i] % c_size) req[i] = (req[i]/c_size) + 1;
296     else req[i] /= c_size;
297   }
298   return req;
299 }
time_t double2time (double t)
Definition at line 1893 of file utilities.cc.
Referenced by DIL_entry::Get_Entry_Parameters().
1893                              {
1894         struct tm td;
1895         td.tm_sec = 0; // seconds not explicit
1896         td.tm_min = (int) fmod(t,100.0); t /= 100.0;
1897         td.tm_hour = (int) fmod(t,100.0); t /= 100.0;
1898         td.tm_mday = (int) fmod(t,100.0); t /= 100.0;
1899         td.tm_mon = ((int) fmod(t,100.0))-1; t /= 100.0;
1900         td.tm_year = ((int) t)-1900;
1901         td.tm_wday = 0;
1902         td.tm_yday = 0;
1903         td.tm_isdst = 0;
1904         return mktime(&td);
1905 }
int Elipsis_At (String & s, int maxsize)
Definition at line 2634 of file utilities.cc.
References String::before(), and String::length().
Referenced by AL_Passed_Target_Dates(), generate_AL(), Active_List::generate_focused_AL(), generate_modify_element_FORM_interface_DIL_Superiors(), Active_List::generate_wide_AL(), update_main_ALs(), DIL_Visualize_with_HTML_Tabs::Visualize_Element(), and DIL_Visualize_with_FORM_Tabs::Visualize_Element().
2634                                         {
2635 // returns the length of the resulting string
2636         if (s.length()>maxsize) {
2637                 s = s.before(maxsize);
2638                 s = s.before(BigRegex("[        \n.,;:]"),-1);
2639                 s += "...";
2640         }
2641         return s.length();
2642 }
bool extract_DIL_IDs_from_form (StringList * qlist = NULL)
Definition at line 1342 of file diladmin.cc.
References StringList::concatenate(), String::contains(), DIL_Hierarchy_cmd(), BigRegex::sublen(), BigRegex::subpos(), URI_unescape(), VOUT, and write_file_from_String().
Referenced by Detect_Form_Input().
1342                                                           {
1343   // Form interface that extracts DIL IDs that correspond to checked
1344   // checkboxes in any form.
1345   // Known variable names in form: dil2al, DILIDCHKBX<DIL_ID>, processcmd,
1346   // maxdepth, hierarchyfile.
1347   if (!qlist) return false;
1348   const BigRegex dilidchkbx("^DILIDCHKBX\\([0-9]+[.][0-9]+\\)=");
1349   StringList dilids; int dilidsnum = 0;
1350   // Find checked checkboxes that contain DIL IDs
1351   int qnum = qlist->length()-1; // *** empty element at end of StringList
1352   for (int i = 0; i<qnum; i++) {
1353     // *** Beware: The same caveat about the assumed length of DIL IDs applies
1354     //     as in the modify_DIL_group_target_dates_cmd() function above.
1355 #ifdef DEBUGTIER2
1356     cout << '$' << (*qlist)[i] << '\n';
1357 #endif
1358     if ((*qlist)[i].contains(dilidchkbx)) {
1359       String chkbxid = (*qlist)[i].at(dilidchkbx.subpos(1),dilidchkbx.sublen(1));
1360       String chkbxval = (*qlist)[i].after('=');
1361       if (chkbxval=="extract") {
1362         dilids[dilidsnum] = chkbxid;
1363         dilidsnum++;
1364       }
1365     }
1366   }
1367   // Check if extract or make new hierarchy
1368   int processcmdidx = qlist->contains("processcmd");
1369   if (processcmdidx>0) if (String((*qlist)[processcmdidx].after('='))=="newhierarchy") {
1370     int depthidx = qlist->contains("maxdepth"), maxdepth = 50;
1371     if (depthidx>0) maxdepth = atol((const char *) String((*qlist)[depthidx].after('=')));
1372     int hierarchyfileidx = qlist->contains("hierarchyfile"); String hierarchyfile("");
1373     if (hierarchyfileidx>0) hierarchyfile = '@'+String((*qlist)[hierarchyfileidx].after('='))+'@';
1374     int expressionsidx = qlist->contains("expressions"); String expressions("");
1375     if (expressionsidx>0) expressions = '#'+URI_unescape(String((*qlist)[expressionsidx].after('=')));
1376     int contentfileidx = qlist->contains("contentfile"); String contentfile("");
1377     if (contentfileidx>0) contentfile = 'c'+String((*qlist)[contentfileidx].after('='));
1378     return DIL_Hierarchy_cmd(hierarchyfile+"FORM"+dilids.concatenate('+')+contentfile+expressions,maxdepth);
1379   }
1380   // Write the DIL IDs to the dilref file
1381   if (dilidsnum==0) return false;
1382   VOUT << dilids.concatenate("\n");
1383   String dilidsstr;
1384   for (int i = 0; i<dilidsnum; i++) dilidsstr += "Current URL      file://"+idfile+'#'+dilids[i]+'\n';
1385   return write_file_from_String(dilref,dilidsstr,"Checked DIL IDs");
1386 }
bool extract_paper_novelties (String fname, String paperplanurl, ostream & ostr)
Definition at line 19 of file tlfilter.cc.
References _BIGSTRING_ITERATOR, String::after(), String::at(), EOUT, String::gsub(), String::index(), read_file_into_String(), relurl(), RX_Search_Safe(), BigRegex::sublen(), and BigRegex::subpos().
Referenced by cmdline_extract_paper_novelties().
19                                                                                 {
20 // searches a document for <A NAME="NOVELTY-some-id">[<B>N</B>]</A>/<!-- @NOVELTY-some-id@ -->
21 // tags and returns the items between the tags
22         String fcont;
23         if (!read_file_into_String(fname,fcont)) {
24                 EOUT << "dil2al: Unable to read file " << fname << " in extract_paper_novelties()\n";
25                 return false;
26         }
27         _BIGSTRING_ITERATOR i=-1;
28         while ((i=fcont.index(BigRegex("[<]A[   ]+[Nn][Aa][Mm][Ee][     ]*=[    ]*\"NOVELTY-[^\"]*\"[>]"),i+1))>=0) {
29                 _BIGSTRING_ITERATOR ii = fcont.index("\">",i); // find end of ID
30                 if (ii>=0) {
31                         String nid;
32                         nid = fcont.at(i,ii-i);
33                         nid = nid.after("\"",-1);
34                         ii = fcont.index("</A>",ii); // find start of content
35                         if (ii>=0) {
36                                 BigRegex en("[<]!--[    ]+@"+RX_Search_Safe(nid)+"@[    ]+\\([^>]*\\)--[>]");
37                                 _BIGSTRING_ITERATOR iii = fcont.index(en,ii); // get end marker
38                                 if (iii>=0) {
39                                         String cstr, istr, lstr, sstr;
40                                         if (en.sublen(1)>0) { // extract possible qualifying and quantifying information
41                                                 String qqinfo = fcont.at(en.subpos(1),en.sublen(1));
42                                                 const BigRegex qqi("@CONTEXT:[  ]*\\([^@]*\\)@[         ]*@IMP:[        ]*\\([^@]*\\)@[         ]*@LEN:[        ]*\\([^@]*\\)@[         ]*@SECTION:[    ]*\\([^@]*\\)@");
43                                                 if (qqinfo.index(qqi)>=0) {
44                                                         cstr = qqinfo.at(qqi.subpos(1),qqi.sublen(1));
45                                                         istr = qqinfo.at(qqi.subpos(2),qqi.sublen(2));
46                                                         lstr = qqinfo.at(qqi.subpos(3),qqi.sublen(3));
47                                                         sstr = qqinfo.at(qqi.subpos(4),qqi.sublen(4));
48                                                 }
49                                         }
50                                         String ncont;
51                                         ncont = fcont.at(ii+4,iii-(ii+4)); // get content
52                                         ncont.gsub(BigRegex("[<][^>]*[>]"),""); // clean up content
53                                         String fshortname = fname.after("/",-1);
54                                         if (fshortname == "") fshortname = fname;
55                                         ostr << "<LI>" << ncont << " [<A HREF=\"" << relurl(paperplanurl,fname) << '#' << nid << "\">" << fshortname << '#' << nid << "</A>]<BR>\n"; // return content
56 //*** selection criteria suggestions can be automatically generated (see DIL#20000310091924.1)
57                                         ostr << "(<B>Context</B>: " << cstr << ", <B>Importance</B>: " << istr << ", <B>Length</B>: " << lstr << ", <B>Section</B>: " << sstr << ")\n"; // add selection criteria
58                                 }
59                         }
60                 }
61         } // else may already have HREF reference to paper in which it is included
62         return true;
63 }
bool extract_paper_plan_to_paper (String ppname, String pout, String pprevious)
Definition at line 1069 of file ppfilter.cc.
References absurl(), String::after(), String::at(), backup_and_rename(), String::before(), String::del(), EOUT, extract_hierarchy_depth_decrease_to_paper(), extract_hierarchy_depth_increase_to_paper(), extract_novelty_item_to_paper(), extract_required_item_to_paper(), String::from(), get_Paper_Plans_Section_IDs(), String::gsub(), String::index(), StringList::iselement(), Novelty_Marker_List::iselement(), String::length(), Novelty_Marker::NM_NOVELTY_ITEM, Novelty_Marker::NM_REQUIRED_ITEM, Novelty_Marker::NM_TCH_DEPTH_DEC, Novelty_Marker::NM_TCH_DEPTH_INC, read_file_into_String(), relurl(), String::SEARCH_END, String::upcase, and VOUT.
Referenced by cmdline_extract_paper_plan_to_paper().
1069                                                                                {
1070 // uses information in a paper plan to generate paper outline and content
1071 // (see DIL#20000315155709.1)
1072 // preparation:
1073 // - a sorted paper plan including required items
1074 // - an optional previous (version of the) paper, containing
1075 //   stylistically rewritten items or arbitrary ``protected'' text
1076 //   for inclusion in the paper draft
1077         const BigRegex fighererx("[\\][A-Za-z]*figurehere[{]");
1078         String pptext, pprevtext, ostrtext, _figcaps, _figps, * figcaps = NULL, * figps = NULL;
1079         if (!read_file_into_String(ppname,pptext)) return false;
1080         if (pprevious!="") if (!read_file_into_String(pprevious,pprevtext)) return false; // safe in case new paper draft would overwrite pprevious
1081         ofstream ostr(pout+".new");
1082         if (!ostr) {
1083                 EOUT << "dil2al: Unable to create " << pout << ".new in extract_paper_plan_to_paper()\n";
1084                 return false;
1085         }
1086         include_article_head_template(pout,ostrtext,pprevtext);
1087         // determine if FIGURE CAPTIONS and FIGURE PSCONVERSIONS sections are present
1088         if (ostrtext.contains("@Begin FIGURE CAPTIONS@")) figcaps = &_figcaps;
1089         if (ostrtext.contains("@Begin FIGURE PSCONVERSIONS@")) figps = &_figps;
1090         // read all Novelty items from paper plan into list
1091         Novelty_Marker_List nml; int nmend = 0, nmnum = 0, hdepth = 0;
1092         if ((nmend = pptext.index(BigRegex("[<]A[       ]*[Nn][Aa][Mm][Ee][     ]*=[    ]*\"tch\""),nmend))<0) {
1093                 EOUT << "dil2al: No Topical Context Hierarchy found in Paper Plan in extract_paper_plan_to_paper()\n";
1094                 return false;
1095         }
1096 #ifdef DEBUG_PPEXTRACT
1097         cout << "Paper Plan text length = " << pptext.length() << " Novelty Markers at positions: ";
1098 #endif
1099         while ((nmend = nml[nmnum].Get_Novelty_from_Paper_Plan(pptext,nmend,hdepth))>=0) {
1100 #ifdef DEBUG_PPEXTRACT
1101                 if (nmnum>0) cout << ',';
1102                 cout << nmend;
1103 #endif
1104                 hdepth = nml[nmnum].hierdepth; // track Topical Context Hierarchy depth
1105                 if (hdepth<0) break;
1106                 if (nml[nmnum].source!="") nml[nmnum].source = absurl(ppname,nml[nmnum].source);
1107 #ifdef DEBUG_PPEXTRACT
1108                 if (nml[nmnum].source!="") cout << '(' << nml[nmnum].source << ')';
1109                 else cout << '(' << nml[nmnum].context[0] << ')';
1110 #endif
1111                 nmnum++;
1112         }
1113 #ifdef DEBUG_PPEXTRACT
1114         cout << '\n';
1115 #endif
1116         StringList contextconcats; LongList ccranks;
1117         nml.Get_Context_Ranks(contextconcats,ccranks);
1118         if (verbose) VOUT << nmnum << " Novelty Items, Topic Openings and Closings\n";
1119         // read Section IDs
1120         StringList ppsectionids, ppsectiontitles, ppsectiontemplates;
1121         if (!get_Paper_Plans_Section_IDs(ppsectionids,ppsectiontitles,ppsectiontemplates)) return false;
1122         // test for unknown section IDs in Novelty Items
1123         for (int i = 0; i<nmnum; i++) if (nml[i].nmtype==Novelty_Marker::NM_NOVELTY_ITEM)
1124                 for (int s = 0; s<nml[i].section.length(); s++) if (ppsectionids.iselement(nml[i].section[s])<0)
1125                         EOUT << "dil2al: Unknown section type `" << nml[i].section[s] << "' for " << nml[i].id << " in extract_paper_plan_to_paper(), continuing as is\n";
1126 //*** generate tentative Abstract, as specified in
1127 //*** DIL#20000315155709.1
1128 //*** use information about paper type to modify main template or section templates
1129 //*** according to background template
1130         // per section
1131         int secidx, srcfnum = 0; StringList srcf, srcfname; String requireditems,sectiontemplate;
1132         for (secidx=0; secidx<ppsectionids.length(); secidx++) if (ppsectionids[secidx]!="ABS") {
1133 #ifdef DEBUG_PPEXTRACT
1134                 cout << 'I'; cout.flush();
1135 #endif
1136                 // get section title
1137                 String sectitle = ppsectiontitles[secidx];
1138                 sectitle.upcase();
1139                 if (verbose) VOUT << "Generating paper outline section " << sectitle << '\n';
1140                 include_article_section_head_template(ppsectiontemplates[secidx],sectiontemplate,ostrtext,pprevtext);
1141                 // parse items in section
1142                 String refurl = relurl(pout,ppname);
1143                 for (int i=0; i<nmnum; i++)
1144 #ifdef DEBUG_PPEXTRACT
1145                 { cout << 'J'; cout.flush();
1146 #endif
1147                  if ((nml[i].nmtype==Novelty_Marker::NM_TCH_DEPTH_INC)
1148                   || (nml[i].nmtype==Novelty_Marker::NM_TCH_DEPTH_DEC)
1149                   || (nml[i].section.iselement(ppsectionids[secidx])>=0)) {
1150                         if (nml[i].nmtype==Novelty_Marker::NM_REQUIRED_ITEM) extract_required_item_to_paper(ostrtext,refurl,nml[i],sectitle,requireditems,pprevtext);
1151                         else if (nml[i].nmtype==Novelty_Marker::NM_TCH_DEPTH_INC) extract_hierarchy_depth_increase_to_paper(ostrtext,nml[i],contextconcats,ccranks,sectitle,srcf,srcfname,srcfnum,pprevtext);
1152                         else if (nml[i].nmtype==Novelty_Marker::NM_TCH_DEPTH_DEC) extract_hierarchy_depth_decrease_to_paper(ostrtext,nml[i],sectitle,srcf,srcfname,srcfnum,pprevtext);
1153                         else if (nml[i].nmtype==Novelty_Marker::NM_NOVELTY_ITEM) extract_novelty_item_to_paper(ostrtext,figcaps,figps,nml[i],sectitle,srcf,srcfname,srcfnum,pout,pprevtext);
1154                         else EOUT << "dil2al: Unknown Novelty_Marker::nmtype in extract_paper_plan_to_paper(), continuing as is\n";
1155                 }
1156                 // close section
1157 #ifdef DEBUG_PPEXTRACT
1158                 } cout << 'L'; cout.flush();
1159 #endif
1160                 include_article_section_tail_template(sectiontemplate,ostrtext,pprevtext);
1161         }
1162 #ifdef DEBUG_PPEXTRACT
1163         cout << 'K'; cout.flush();
1164 #endif
1165         include_article_tail_template(pout,ostrtext,pprevtext);
1166         // add FIGURE CAPTIONS and FIGURE PSCONVERSIONS sections if present
1167         if (figcaps!=NULL) ostrtext.gsub(BigRegex("@Begin FIGURE CAPTIONS@[^\n]*\n"),"@Begin FIGURE CAPTIONS@\n"+_figcaps);
1168         if (figps!=NULL) ostrtext.gsub(BigRegex("@Begin FIGURE PSCONVERSIONS@[^\n]*\n"),"@Begin FIGURE PSCONVERSIONS@\n"+_figps);
1169         // add \figureloose commands
1170         int ofigidx;
1171         if ((ofigidx = ostrtext.index(fighererx))>=0) {
1172                 // find loose figures location in outline and copy to there
1173                 int iloosefigidx, ifigend; String ostrtail;
1174                 if (((iloosefigidx = ostrtext.index(BigRegex("\n%[      ]*@Begin FIGURES AT END@"),-1))>=0)
1175                  && ((ifigend = ostrtext.index(BigRegex("\n%[   ]*@End FIGURES AT END@[^\n]*\n"),String::SEARCH_END,-1))>=0)) {
1176                         ostrtail = ostrtext.from(ifigend);
1177                         ostrtext = ostrtext.before(iloosefigidx);
1178                 } else {
1179                         if ((iloosefigidx = ostrtext.index("\\end{document}",-1))>=0) {
1180                                 ostrtail = ostrtext.from(iloosefigidx);
1181                                 ostrtext = ostrtext.before(iloosefigidx);
1182                         } else {
1183                                 EOUT << "dil2al: No \\end{document} found in outline in extract_paper_plan_to_paper(), continuing as is\n";
1184                                 ostrtail = "";
1185                         }
1186                 }
1187                 // copy \figurehere data to \figureloose commands
1188                 ostrtext += "\n% @Begin FIGURES AT END@\n\n";
1189                 while (ofigidx>=0) {
1190                         String figdata;
1191                         if ((ifigend=TeX_get_command(ostrtext,ofigidx,figdata))>=0) {
1192                                 figdata.gsub(BigRegex("^\\([\\][A-Za-z]*\\)figurehere[{]"),"_1figureloose{",'_');
1193                                 ostrtext += figdata + "\n\n";
1194                         } else {
1195                                 EOUT << "dil2al: Incomplete figure command found for " << ostrtext.sub(fighererx,0) << " in extract_paper_plan_to_paper(), continuing as is\n";
1196                                 ifigend = ofigidx+1;
1197                         }
1198                         ofigidx = ostrtext.index(fighererx,ifigend);
1199                 }
1200                 ostrtext += "% @End FIGURES AT END@\n"+ostrtail;
1201         }
1202         // include protected text
1203         include_protected_text(ostrtext,pprevtext);
1204         // TeX format corrections, safeguards for TeX compilation
1205         TeX_format_corrections(ostrtext,true);
1206 //*** add new Context items to contexts file here (DIL#20010412121145.1)
1207 cerr << "Add automatic call to add Context items to contexts file here (DIL#20010412121145.1)...\n";
1208         ostr << ostrtext; // write paper draft file
1209         ostr.close();
1210 #ifndef DEBUG_DO_NOT_CREATE_NEW_OUTLINE
1211         if (!backup_and_rename(pout,"Paper Draft")) return false;
1212         // find required items list in paper plan, create if not found
1213         if (requireditems.length()>0) {
1214                 int riidx;
1215                 if ((riidx = pptext.index(BigRegex("[<]!--[     ]*@Begin REQUIRED ITEMS@[       ]*--[>]\n"),String::SEARCH_END))<0) {
1216                         // create list of required items
1217                         if ((riidx = pptext.index(BigRegex("\\([<][Pp][>][      ]*\n[<][Hh][Rr][>].*\\)?[<]/[Bb][Oo][Dd][Yy][>]")))<0)
1218                                 EOUT << "dil2al: Unable to create list of required items in extract_paper_plan_to_paper(), continuing as is\n";
1219                         else {
1220                                 String pptextrest = pptext.at(riidx,pptext.length()-riidx);
1221                                 pptext = pptext.before(riidx)
1222                                                 + "<H2><A HNAME=\"required-items\">Required Items</A></H2>\n\n<UL>\n<!-- @Begin REQUIRED ITEMS@ -->\n<!-- @End REQUIRED ITEMS@ -->\n</UL>\n\n"
1223                                                 + pptextrest;
1224                                 riidx += 92; // move index to start of <!-- @End REQUIRED ITEMS@ --> tag
1225                         }
1226                 }
1227                 if (riidx>=0) {
1228                         // update required items list
1229                         int riend;
1230                         if ((riend = pptext.index(BigRegex("[<]!--[     ]*@End REQUIRED ITEMS@[         ]*--[>]"),riidx))<0) {
1231                                 EOUT << "dil2al: Missing @End REQUIRED ITEMS@ tag in extract_paper_plan_to_paper(), placing tag\n";
1232                                 String pptextrest = pptext.at(riidx,pptext.length()-riidx);
1233                                 pptext = pptext.before(riidx) + "<!-- @End REQUIRED ITEMS@ -->\n" + pptextrest;
1234                                 riend = riidx;
1235                         }
1236                         String pptextrest = pptext.at(riend,pptext.length()-riend);
1237                         pptext = pptext.before(riidx) + requireditems + pptextrest;
1238                         // store, backup and rename updated paper plan
1239                         ostr.open(ppname+".new");
1240                         if (!ostr) {
1241                                 EOUT << "dil2al: Unable to create " << ppname << ".new to update required items list in extract_paper_plan_to_paper(), continuing as is\n";
1242                                 return false;
1243                         }
1244                         ostr << pptext;
1245                         if (!backup_and_rename(ppname,"Paper Plan"))
1246                                 EOUT << "dil2al: Unable to update required items list extract_paper_plan_to_paper(), continuing as is\n";
1247                 }
1248         } else if (verbose) VOUT << "No Required items to list\n";
1249         return true;
1250 #endif
1251 }
bool file_is_directory (String filepath)
Definition at line 1988 of file utilities.cc.
References EOUT.
Referenced by Get_Target_Directory(), search_cmd(), and Target_Access::set_target().
1988                                         {
1989         struct stat fs;
1990         if (stat(filepath,&fs)!=0) {
1991                 if (verbose) EOUT << "dil2al: Error reading file attributes of " << filepath << "in file_is_directory()\n";
1992                 return false;
1993         }
1994         return S_ISDIR(fs.st_mode);
1995 }
bool file_is_regular (String filepath)
Definition at line 1970 of file utilities.cc.
References EOUT.
1970                                       {
1971         struct stat fs;
1972         if (stat(filepath,&fs)!=0) {
1973                 if (verbose) EOUT << "dil2al: Error reading file attributes of " << filepath << " in file_is_regular()\n";
1974                 return false;
1975         }
1976         return S_ISREG(fs.st_mode);
1977 }
bool file_is_regular_or_symlink (String filepath)
Definition at line 1979 of file utilities.cc.
References EOUT.
Referenced by Get_Target_Directory().
1979                                                  {
1980         struct stat fs;
1981         if (stat(filepath,&fs)!=0) {
1982                 if (verbose) EOUT << "dil2al: Error reading file attributes of " << filepath << "in file_is_regular_or_symlink()\n";
1983                 return false;
1984         }
1985         return (S_ISREG(fs.st_mode) || (S_ISLNK(fs.st_mode)));
1986 }
bool filter_TL_by_AL ()
Definition at line 6 of file tlfilter.cc.
6                        {
7 }
bool financial_monthly ()
Definition at line 263 of file finances.cc.
References Financial_Monthly_Root::add(), PLLRoot< PLLType >::head(), PLL_LOOP_FORWARD, Financial_Monthly_Root::put_results(), read_financial_notes_file(), and VOUT.
Referenced by formalizer_commands().
263                          {
264   // Compute results from <A HREF="../../doc/html/financial-notes.html">financial-notes.html</A>.
265   PLLRoot<Financial_Note> fnotes; String finnotestop, finnotesend;
266   if (!read_financial_notes_file(fnotes,finnotestop,finnotesend)) return false;
267   // compute sums of categorized expenses that have not previously been handled
268   Financial_Monthly_Root fmonthly;
269   if (verbose) VOUT << "If you wish to rely on monthly results from the Financial Notes, please\nverify that all non-variable expenses listed in bank statements are\naccounted for in the Financial Notes.\n\n";
270   PLL_LOOP_FORWARD(Financial_Note,fnotes.head(),1) {
271     if (!e->Handled()) fmonthly.add(*e);
272   }
273   VOUT << fmonthly.put_results();
274 }
bool financial_notes ()
Definition at line 117 of file finances.cc.
References confirmation(), String::del(), String::empty(), String::length(), Financial_Note::link_sorted(), read_financial_notes_file(), time_stamp_time_date(), VOUT, and write_financial_notes_file().
Referenced by formalizer_commands().
117                        {
118   // Edit notes in <A HREF="../../doc/html/financial-notes.html">financial-notes.html</A>.
119   PLLRoot<Financial_Note> fnotes; String finnotestop, finnotesend;
120   if (!read_financial_notes_file(fnotes,finnotestop,finnotesend)) return false;
121   // add new notes (currently just by hand)
122   Financial_Note * f;
123   time_t d; double e; bool h; String dstr(curdate), t, n, c;
124   const int LLEN = 10240;
125   char lbuf[LLEN];
126   d = time_stamp_time_date(dstr+"0000");
127   while (1) {
128     VOUT << "date [" << dstr << "] (done=exit): ";
129     cin.getline(lbuf,LLEN); n = lbuf;
130     if (!n.empty()) {
131       if (n=="done") break;
132       dstr = n;
133       n += "0000"; n.del(12,n.length()-12);
134       d = time_stamp_time_date(n);
135     }
136     VOUT << "expense: ";
137     cin.getline(lbuf,LLEN);
138     e = atof(lbuf);
139     VOUT << "type [variable]: ";
140     cin.getline(lbuf,LLEN); t = lbuf;
141     if (t.empty()) t = "variable";
142     if (t==String("variable")) h = true;
143     else h = !confirmation("handled [n]: ",'y');
144     VOUT << "note: ";
145     cin.getline(lbuf,LLEN); n = lbuf;
146     VOUT << "comment: ";
147     cin.getline(lbuf,LLEN); c = lbuf;
148     f = new Financial_Note(d,e,t,h,n,c);
149     f->link_sorted(fnotes);
150   }
151   // write financial notes file
152   return write_financial_notes_file(fnotes,finnotestop,finnotesend);
153 }
int find_delimiter (String & str, int startpos, int lenlimit, char delimiter = '\n') [inline]
Definition at line 2158 of file utilities.cc.
References String::index().
Referenced by Detailed_Items_List::Get_Project_Data().
2158                                                                                            {
2159         int delimpos = str.index(delimiter,startpos);
2160         if (delimpos>=lenlimit) return -1;
2161         return delimpos;
2162 }
int find_in_line (ifstream * lf, const char * pattern, int nsub, String * dilid, const char * before, char * lbuf, int llen)
Definition at line 2285 of file utilities.cc.
References EOUT.
Referenced by add_new_to_DIL(), get_active_DIL_IDs(), and select_TL_AL_refs().
2285                                                                                                                             {
2286 // takes an open ifstream and searches for the regex pattern with nsub subexpressions
2287 // before a line with the ``before'' pattern (NULL = EOF)
2288 // returns substrings in dilid and the return value
2289 // 1 (found ``pattern''), 0 (found ``before''), -1 (EOF),
2290 // -2 (wrong #substrings), -3 (regex error) -4 (file not open)
2291         const int SLEN = 1024;
2292         char sbuf[SLEN];
2293         regex_t re,be;
2294         regmatch_t * rm;
2295         int mres;
2296         bool done;
2297         if (*lf) {
2298                 if (nsub) rm = new regmatch_t[nsub];
2299                 else rm = NULL;
2300                 if (regcomp(&re,pattern, REG_EXTENDED) != 0) {
2301                         EOUT << "dil2al: Unable to compile ``pattern'' regular expression in find_in_line()\n";
2302                         return -3;
2303                 }
2304                 if (before) {
2305                         if (regcomp(&be,before, REG_EXTENDED|REG_NOSUB) != 0) {
2306                                 regfree(&re);
2307                                 EOUT << "dil2al: Unable to compile ``before'' regular expression in find_in_line()\n";
2308                                 return -3;
2309                         }
2310                 }
2311                 done = false;
2312                 while (!done) {
2313                         if (lf->eof()) { mres = 2; done=true; }
2314                         else {
2315                                 lf->getline(lbuf,llen);
2316                                 if (before) mres = regexec(&be,lbuf, (size_t) 0, NULL, 0);
2317                                 if ((before) && (mres != 0) && (mres != REG_NOMATCH)) {
2318                                         EOUT << "dil2al: Internal error while matching ``before'' in find_in_line()\n";
2319                                         mres = 4; done = true;
2320                                 } else {
2321                                         if ((before) && (mres==0)) { mres = 1; done = true; }
2322                                         else {
2323                                                 mres = regexec(&re,lbuf, (size_t) nsub, rm, 0);
2324                                                 if ((mres != 0) && (mres != REG_NOMATCH)) {
2325                                                         EOUT << "dil2al: Internal error while matching ``pattern'' in find_in_line()\n";
2326                                                         mres = 4; done = true;
2327                                                 } else {
2328                                                         if (!mres) {
2329                                                                 done = true;
2330                                                                 if (nsub) {
2331                                                                         if (rm[nsub-1].rm_so==-1) {
2332                                                                                 EOUT << "dil2al: Wrong number of substring matches in find_in_line()\n";
2333                                                                                 mres = 3;
2334                                                                         } else {
2335                                                                                 for (int i=0; i<nsub; i++) {
2336                                                                                         strncpy(sbuf,&lbuf[rm[i].rm_so],rm[i].rm_eo-rm[i].rm_so);
2337                                                                                         sbuf[rm[i].rm_eo-rm[i].rm_so]='\0';
2338                                                                                         dilid[i] = sbuf;
2339                                                                                 }
2340                                                                         }
2341                                                                 }
2342                                                         }
2343                                                 }
2344                                         }
2345                                 }
2346                         }
2347                 }
2348                 regfree(&re);
2349                 regfree(&be);
2350                 if (nsub) delete[] rm;
2351                 return (-mres) + 1;
2352         } else {
2353                 EOUT << "dil2al: file not open in find_in_line()\n";
2354                 return -4;
2355         }
2356 }
bool find_line (ifstream * lf, const char * pattern, char * lbuf, int llen)
Definition at line 2217 of file utilities.cc.
References EOUT.
Referenced by add_new_to_DIL(), get_active_DIL_IDs(), get_topic_keywords(), make_note(), Topical_DIL_Files::Refresh(), select_TL_AL_refs(), and select_TL_DIL_refs().
2217                                                                            {
2218 // takes an open ifstream and searches for the regex pattern
2219         regex_t re;
2220         int mres;
2221         if (*lf) {
2222                 if (regcomp(&re,pattern, REG_EXTENDED|REG_NOSUB) != 0) {
2223                         EOUT << "dil2al: Unable to compile regular expression in find_line()\n";
2224                         return false;
2225                 }
2226                 mres = 1;
2227                 while (mres!=0) {
2228                         if (lf->eof()) {
2229                                 regfree(&re);
2230                                 return false;
2231                         }
2232                         lf->getline(lbuf,llen);
2233                         mres = regexec(&re,lbuf, (size_t) 0, NULL, 0);
2234                         if ((mres != 0) && (mres != REG_NOMATCH)) {
2235                                 EOUT << "dil2al: Internal error while matching in find_line()\n";
2236                                 regfree(&re);
2237                                 return false;
2238                         }
2239                 }
2240                 regfree(&re);
2241                 return true;
2242         } else {
2243                 EOUT << "dil2al: file not open in find_line()\n";
2244                 return false;
2245         }
2246 }
bool generate_AL (DIL_entry ** dep, DIL_entry * superior = NULL)
Definition at line 985 of file alcomp.cc.
References Active_List::Add_Passed_Target_Date(), Active_List::Add_Target_Date(), Active_List::AL_Head(), AL_PREPARATION_DELAY, Active_List::AL_Tail(), Active_List::allocate(), Active_List::allocate_with_value(), Active_List::available_before(), DIL_ID::chars(), AL_Day::DayDate(), AL_Day::DayMaxt(), AL_Day::DayStart(), Active_List::deavail, DEFAULTALCUMULATIVEREQHEADER, DEFAULTALCUMULATIVEREQTAIL, DIL_Topical_List::dil, DIL_Required_Task_Chunks(), Elipsis_At(), EOUT, Active_List::expand(), filetitle_t::file, Active_List::filestr(), PLLHandle< DIL_entry >::fulllength(), generate_EPS_cells(), Active_List::generate_focused_AL(), Active_List::generate_wide_AL(), Active_List::Get_Avail_TC(), AL_TC::Get_DE(), Active_List::get_supstr(), Get_Worked_Estimate(), String::gsub(), HTML_put_form_checkbox(), HTML_put_form_text(), HTML_put_href(), HTML_put_table_cell(), HTML_put_table_row(), HTML_remove_tags(), DIL_entry::Is_Dependency_Of(), Active_List::length(), PLLHandle< AL_TC >::Next(), PLL_LOOP_FORWARD, RELLISTSDIR, relurl(), Active_List::remove_unused_TCs(), Active_List::set_TC_values(), DIL_entry::Target_Date(), Time(), time_stamp(), filetitle_t::title, DIL_entry::Topics(), update_main_ALs(), VOUT, and write_file_from_String().
Referenced by select_TL_DIL_refs(), stop_TL_chunk(), and update_DIL_to_AL().
985                                                                 {
986 // create AL from sorted array of DIL entries
987 // if superior == NULL then the AL spans all DIL categories
988 // if generatealtcs == 0, a complete AL will be computed, for
989 // the completion of all DIL entries that are dependencies of
990 // superior
991 // if generatealmaxt > 0, the AL will be computed up to the
992 // limit date specified
993 // if generatealtcs > 0, the AL will be computed for that
994 // number of Task Chunks
995         // check parameters
996         if (!dep) {
997                 EOUT << "dil2al: Missing sorted DIL pointer in generate_AL()\n";
998                 return false;
999         }
1000         if (!dep[0]) {
1001                 EOUT << "dil2al: Empty DIL in generate_AL()\n";
1002                 return false;
1003         }
1004         if (generatealtcs<0) {
1005                 EOUT << "dil2al: Invalid AL interval size (" << generatealtcs << ") requested in generate_AL()\n";
1006                 return false;
1007         }
1008         // prepare DIL entry data
1009         int deplen = dep[0]->fulllength(); // *** if you supply a custom list of sorted entries, supply the length of the list as well
1010         long * req = DIL_Required_Task_Chunks(dep,deplen);
1011         // allocate desired AL interval
1012         // Note: If there is ever a need for intervals beginning
1013         // at other times than the current time, that can be
1014         // accomplished easily by setting curtime to the desired
1015         // start of the interval.
1016         time_t algenhpd = ((time_t) algenregular)*3600; // seconds per day (before any expansion)
1017         if (!superior) algenhpd = ((time_t) algenall)*3600;
1018         else { // detect specific hpd for superior
1019                 // *** (search up or down?)
1020                 EOUT << "dil2al: Search for superior-specific hours-per-day parmameter not yet implemented in generate_AL()\n";
1021         }
1022         Get_Worked_Estimate(); // estimated time already worked on current day
1023 #ifdef DIAGNOSTIC_OUTPUT
1024         EOUT << "alworked = " << alworked << '\n';
1025 #endif
1026         #define LOCAL_CLEAN_EXIT { delete[] req; return false; }
1027         Active_List al(req,deplen,algenhpd,superior);
1028 #ifdef DIAGNOSTIC_OUTPUT
1029         EOUT << "allength = " << al.length() << '\n';
1030 #endif
1031         if (al.length()<1) LOCAL_CLEAN_EXIT
1032         // distribute task chunks per DIL entry with target date within AL interval
1033         VOUT << "Distributing task chunks per DIL entry over " << al.length() << " AL task chunks\n";
1034         float sumval=1.0, uval; double cumreq = 0.0, groupreq = 0.0; int groupnum = 0;
1035         String cumreqstr, rowreqstr, entryexcerptcell, dstfile, relidfile; time_t grouptd = -1;
1036         if (alshowcumulativereq) { // cumulative required time file header
1037                 cumreqstr = DEFAULTALCUMULATIVEREQHEADER;
1038                 cumreqstr.gsub("@SUP@",al.get_supstr());
1039                 cumreqstr.gsub("@EPSHRS@",String((double) alepshours,"%5.2f"));
1040                 cumreqstr.gsub("@FORMMETHOD@",htmlformmethod);
1041                 cumreqstr.gsub("@FORMACTION@",htmlforminterface);
1042                 dstfile = basedir+RELLISTSDIR+al.filestr()+".ctr.html";
1043                 relidfile = relurl(dstfile,idfile);
1044         }
1045         time_t t_current = Time(NULL) + AL_PREPARATION_DELAY; // expected time upon completion of AL generation
1046         time_t t_start = al.AL_Head()->DayDate()+al.AL_Head()->DayStart(); // AL start
1047         time_t t_limit = al.AL_Tail()->DayDate()+al.AL_Tail()->DayMaxt(); // AL limit
1048         srand(t_current);
1049         if (superior) { // *** DIL entry specific AL
1050                 EOUT << "dil2al: Actual dependency check for DIL entry specific AL not yet implemented in generate_AL()\n";
1051         }
1052         int i, cnt = 0;
1053         VOUT << "DEs : "; VOUT.flush(); DIL_entry * prevde; // use prevde, since dep[i-1] can point to DIL entry that does not satisfy the conditionals below
1054         #define GENERATE_AL_DEPLOOP_CONTINUE prevde = dep[i]; continue
1055         for (i=0; ((i<deplen) && (dep[i]->Target_Date()<t_limit)); i++) if ((req[i]>0) && (dep[i]->Is_Dependency_Of(superior))) { // non-completed DIL entries
1056 #ifdef DIAGNOSTIC_OUTPUT
1057                 EOUT << dep[i]->chars() << " (" << req[i] << ") :\n";
1058 #endif
1059                 if (alshowcumulativereq) { // compute cumulative required time
1060                         DIL_Topical_List * dtl = dep[i]->Topics(0);
1061                         time_t curtd = dep[i]->Target_Date();
1062                         if (grouptd>=0) { // if first row of form
1063                                 if (curtd==grouptd) rowreqstr += HTML_put_table_cell("","@GROUPTREQ@")+HTML_put_table_cell("",HTML_put_form_checkbox(String("TDCHKBX")+prevde->chars(),"noupdate@GROUPCHECKED@","")
1064                                         +HTML_put_form_text(String("TD")+prevde->chars(),"@GROUPEPSTD@",12)); // if in same group, add @place holders@ to row
1065                                 else { // if not in same group complete group data up to previous entry (prevde)
1066                                         generate_EPS_cells(grouptd,cumreqstr,rowreqstr,groupreq,cumreq,t_current,*prevde);
1067                                         groupnum++;
1068                                 }
1069                                 // *** optionally remove the following cell once T_{pref} is used
1070                                 //     to determine preferable shifts
1071                                 rowreqstr += entryexcerptcell;
1072                                 cumreqstr += HTML_put_table_row("",rowreqstr)+'\n';
1073                         }
1074                         grouptd = curtd;
1075                         groupreq += (double) req[i];
1076                         cumreq += (double) req[i];
1077                         rowreqstr = HTML_put_table_cell("",dec(groupnum))+
1078                                           HTML_put_table_cell("",HTML_put_href((relidfile+'#')+dep[i]->chars(),"DIL#" + String(dep[i]->chars())))+
1079                                           HTML_put_table_cell("",HTML_put_href((relurl(dstfile,dtl->dil.file)+'#')+dep[i]->chars(),dtl->dil.title)+" [<A HREF=\"file:///cgi-bin/dil2al?dil2al=MEI&DILID="+dep[i]->str()+"\">edit</A>]")+
1080                                           HTML_put_table_cell("",time_stamp("%Y%m%d%H%M",curtd))+
1081                                           HTML_put_table_cell("",String((((double) req[i])*((double) timechunksize))/60.0,"%6.2f"))+
1082                                           HTML_put_table_cell("",String((cumreq*((double) timechunksize))/60.0,"%6.2f"));
1083                         if (dep[i]->Entry_Text()) entryexcerptcell = (*dep[i]->Entry_Text());
1084                         else entryexcerptcell = "(Missing Text Content)";
1085                         HTML_remove_tags(entryexcerptcell);
1086                         Elipsis_At(entryexcerptcell,alcumtimereqexcerptlength);
1087                         entryexcerptcell = HTML_put_table_cell("",entryexcerptcell);
1088                 }
1089                 if (dep[i]->Target_Date()<t_start) { // skip DIL entries with target date prior to current time
1090                         al.Add_Passed_Target_Date(dep[i]); // add to list of passed target date DIL entries
1091                         VOUT << "dil2al: Warning - Target Date of DIL entry ";
1092                         if (calledbyforminput) VOUT << "<A HREF=\"" << idfile << '#' << dep[i]->chars() << "\">";
1093                         VOUT << dep[i]->chars();
1094                         if (calledbyforminput) VOUT << "</A>";
1095                         VOUT << " precedes current time\n";
1096                         GENERATE_AL_DEPLOOP_CONTINUE;
1097                 }
1098                 al.Add_Target_Date(dep[i]); // add target date reference
1099                 // *** simplify the below by making member functions
1100                 //     that do things like take req[i], automatically
1101                 //     check if expansion is allowed, do the work, and
1102                 //     return the remainder for req[i]
1103                 long expandn = req[i] - al.available_before(dep[i]->Target_Date()); // also sets al.deavail
1104                 if ((expandn>0) && (alautoexpand)) {
1105                         VOUT << "Expanded for DIL entry #" << dep[i]->chars() << " (" << expandn << ")\n";
1106                         if ((expandn -= al.expand(expandn,dep[i]->Target_Date()))!=0) {
1107                                 VOUT << "DIL entry #";
1108                                 if (calledbyforminput) VOUT << "<A HREF=\"" << idfile << '#' << dep[i]->chars() << "\">";
1109                                 VOUT << dep[i]->chars();
1110                                 if (calledbyforminput) VOUT << "</A>";
1111                                 VOUT << " tasks cannot be completed before " << time_stamp("%Y%m%d%H%M",dep[i]->Target_Date()) << "(required: " << req[i] << ", available: " << al.deavail <<  ")\n";
1112                         }
1113                 }
1114                 // *** currently only linear distribution function available
1115                 if ((sumval=al.set_TC_values())>0.0) {
1116                         // randomly allocate TCs for this DIL entry
1117                         while ((req[i]>0) && (al.deavail>0)) {
1118                                 uval = sumval*(((float) rand()) / ((float) RAND_MAX));
1119                                 uval = al.allocate_with_value(uval,dep[i]);
1120                                 if (uval>0.0) {
1121                                         sumval -= uval;
1122                                         req[i]--;
1123 #ifdef DIAGNOSTIC_OUTPUT
1124                                         PLL_LOOP_FORWARD(AL_Day,al.AL_Head(),1) {
1125                                                 EOUT << '|';
1126                                                 if (e->TC_Head()) { 
1127                                                         for (AL_TC * etc = e->TC_Head(); (etc); etc = etc->Next())
1128                                                                 if (etc->Get_DE()) EOUT << 'x'; else EOUT << '_';
1129                                                 }
1130                                         }
1131                                         EOUT << '\n';
1132 #endif
1133                                 }
1134                         }
1135                 } else {
1136                         if (sumval==0.0) VOUT << "No task chunks available for DIL entry #" << dep[i]->chars() << " before target date " << time_stamp("%Y%m%d%H%M",dep[i]->Target_Date()) << "(required: " << req[i] << ", available: " << al.deavail <<  ")\n";
1137                         else EOUT << "dil2al: Negative sum of values for DIL entry #" << dep[i]->chars() << " in generate_AL(), continuing\n";
1138                 }
1139                 prevde = dep[i];
1140                 cnt++;
1141 #ifdef DEBUG
1142                 if ((i%10)==0) { VOUT << '>'; VOUT.flush(); }
1143 #endif
1144         }
1145         VOUT << "Scheduled DIL entries with target date in requested range: " << cnt << '\n';
1146         if (alshowcumulativereq) { // cumulative required time file tail
1147                 String cumreqtail(DEFAULTALCUMULATIVEREQTAIL);
1148                 cumreqtail.gsub("@SUP@",al.get_supstr());
1149                 cumreqtail.gsub("@ALFILE@",al.filestr());
1150                 cumreqtail.gsub("@ALDATE@",time_stamp("%c"));
1151                 generate_EPS_cells(grouptd,cumreqstr,rowreqstr,groupreq,cumreq,t_current,*prevde); // final call to complete grouop data for all entries
1152                 rowreqstr += entryexcerptcell;
1153                 cumreqstr += HTML_put_table_row("",rowreqstr)+'\n' + cumreqtail;
1154                 write_file_from_String(dstfile,cumreqstr,"AL Cumulative Time Required");
1155         }
1156 #ifdef DIAGNOSTIC_OUTPUT
1157         EOUT << "*\n";
1158 #endif
1159         // randomly pick tasks that could not be allocated entirely before their target dates
1160         AL_TC * atc = al.Get_Avail_TC(0);
1161         int j, k = 1; cnt = 0;
1162         while (k>=0) {
1163                 // random DIL entry
1164                 j = (int) (((float) i)*((float) rand()) / ((float) RAND_MAX));
1165                 if (j>=i) j=i-1;
1166                 if (j<0) break; // i==0
1167                 // find nearest DIL entry requiring task chunks
1168                 // Note: current order of search gives partially
1169                 // allocated DIL entries priority over DIL entries
1170                 // with target dates prior to current time
1171                 for (k = j; ((k<i) && (req[k]<=0)); k++);
1172                 if (k>=i) for (k = (j-1); ((k>=0) && (req[k]<=0)); k--);
1173                 // allocate earliest available task chunk in AL
1174                 if (k>=0) {
1175                         if (al.allocate(dep[k])) {
1176                                 req[k]--;
1177 #ifdef DIAGNOSTIC_OUTPUT
1178                                 PLL_LOOP_FORWARD(AL_Day,al.AL_Head(),1) {
1179                                         EOUT << '|';
1180                                         if (e->TC_Head()) { 
1181                                                 for (AL_TC * etc = e->TC_Head(); (etc); etc = etc->Next())
1182                                                         if (etc->Get_DE()) EOUT << 'x'; else EOUT << '_';
1183                                         }
1184                                 }
1185                                 EOUT << '\n';
1186 #endif
1187                         } else break;
1188                 }
1189 #ifdef DEBUG
1190                 if ((cnt%10)==0) { VOUT << '+'; VOUT.flush(); }
1191 #endif
1192                 cnt++;
1193         }
1194         VOUT << "Scheduled tasks that could not be completed before target dates: " << cnt << '\n';
1195 #ifdef DIAGNOSTIC_OUTPUT
1196         EOUT << "*\n";
1197 #endif
1198         // randomly pick tasks that have target dates exceeding the AL interval
1199         int remlen = deplen - i;
1200         k = 0; cnt = 0;
1201         while (k<deplen) {
1202                 // random DIL entry
1203                 j = (int) (((float) remlen)*((float) rand()) / ((float) RAND_MAX));
1204                 if (j>=remlen) j=remlen-1;
1205                 if (j<0) break;
1206                 j += i;
1207                 // find nearest DIL entry requiring task chunks
1208                 for (k = j; ((k>=i) && (req[k]<=0)); k--);
1209                 if (k<i) for (k = (j+1); ((k<deplen) && (req[k]<=0)); k++);
1210                 // allocate earliest available task chunk in AL
1211                 if (k<deplen) {
1212                         if (al.allocate(dep[k])) {
1213                                 req[k]--;
1214 #ifdef DIAGNOSTIC_OUTPUT
1215                                 PLL_LOOP_FORWARD(AL_Day,al.AL_Head(),1) {
1216                                         EOUT << '|';
1217                                         if (e->TC_Head()) { 
1218                                                 for (AL_TC * etc = e->TC_Head(); (etc); etc = etc->Next())
1219                                                         if (etc->Get_DE()) EOUT << 'x'; else EOUT << '_';
1220                                         }
1221                                 }
1222                                 EOUT << '\n';
1223 #endif
1224                         } else break;
1225                 }
1226 #ifdef DEBUG
1227                 if ((cnt%10)==0) { VOUT << '"'; VOUT.flush(); }
1228 #endif
1229         }
1230         VOUT << "Scheduled tasks for DIL entries with target dates beyond requested range: " << cnt << '\n';
1231         // clean up by removing unused TCs
1232 #ifdef DIAGNOSTIC_OUTPUT
1233         PLL_LOOP_FORWARD(AL_Day,al.AL_Head(),1) for (AL_TC * etc = e->TC_Head(); (etc); etc=etc->Next()) if (!etc->Get_DE()) cerr << '?'; cerr << '\n';
1234 #endif
1235         al.remove_unused_TCs();
1236         // create visible AL
1237         if (!al.generate_focused_AL(superior,algenhpd)) LOCAL_CLEAN_EXIT
1238         if (!al.generate_wide_AL(superior)) LOCAL_CLEAN_EXIT
1239         // update DIL, AL, TL main page
1240         if (!update_main_ALs(superior)) LOCAL_CLEAN_EXIT
1241         // clean up
1242         delete[] req;
1243         return true;
1244 }
String generate_AL_entry (String dilid, bool ishighestpriority = false)
Definition at line 28 of file alcomp.cc.
References String::after(), String::at(), String::before(), EOUT, String::gsub(), String::index(), String::length(), read_file_into_String(), and RELLISTSDIR.
Referenced by dil2al_commands().
28                                                                        {
29   // Note: This is currently called only when dil2al is run with the
30   // command line argument -a. This function generates an entry for manual
31   // modification of an AL.
32         String idstr;
33         if (!read_file_into_String(idfile,idstr)) return String("");
34         int idindex;
35         idindex = idstr.index(BigRegex("[<]TD[^>]*[>][  ]*[<]A[         ]+[^>]*[Nn][Aa][Mm][Ee][        ]*=[    ]*\""+dilid));
36         if (idindex<0) {
37                 EOUT << "dil2al: Unable to find " << dilid << " in " << idfile << " in generate_AL_entry()\n";
38                 return String("");
39         }
40         String topdil;
41         topdil = idstr.at(BigRegex("[<]TD[^>]*[>][      ]*[<]A[         ]+[^>]*[Hh][Rr][Ee][Ff][        ]*=[    ]*\"[^\"]+"+dilid),idindex+1);
42         if (topdil=="") {
43                 EOUT << "dil2al: Unable to find full reference to " << dilid << " in generate_AL_entry()\n";
44                 return String("");
45         }
46         topdil = topdil.after(BigRegex("[<]TD[^>]*[>][  ]*[<]A[         ]+[^>]*[Hh][Rr][Ee][Ff][        ]*=[    ]*\""));
47         String topdilfile = topdil;
48         topdil = basedir+RELLISTSDIR+topdilfile.before("#");
49         if (!read_file_into_String(topdil,idstr)) return String("");
50         idindex = idstr.index(BigRegex("[<]TD[^>]*[>][  ]*[<]A[         ]+[^>]*[Nn][Aa][Mm][Ee][        ]*=[    ]*\""+dilid));
51         if (idindex<0) {
52                 EOUT << "dil2al: Unable to find " << dilid << " in " << topdil << " in generate_AL_entry()\n";
53                 return String("");
54         }
55         idindex = idstr.index(BigRegex("[<]TR[^>]*[>]"),idindex+1);
56         if (idindex<0) return String("");
57         idindex = idstr.index(BigRegex("[<]TD[^>]*[>]"),idindex+1);
58         if (idindex<0) return String("");
59         topdil = idstr.at(BigRegex("[<]TD[^>]*[>]...[^\n]*"),idindex);
60         if (topdil=="") return String("");
61         topdil = topdil.after(BigRegex("[<]TD[^>]*[>]"));
62         topdil.gsub(BigRegex("[<][^>]+[>]"),"");
63         if (topdil.length()>100) {
64                 topdil = topdil.before(100);
65                 topdil = topdil.before(BigRegex("[      \n.,;:]"),-1);
66                 topdil += "...";
67         }
68         idstr = "<TR";
69         if (ishighestpriority) idstr += " BGCOLOR=\"#3F5F00\"";
70         idstr += "><TD>[<A HREF=\""+topdilfile+"\"><B>"+dilid+"</B></A>][<A HREF=\"file:///cgi-bin/dil2al?dil2al=MEI&DILID="+dilid+"\">edit</A>]\n"+topdil;
71         return idstr;
72 }
String generate_AL_full_entry (String dilid, int chunkfreq)
Definition at line 23 of file alcomp.cc.
References res.
Referenced by dil2al_commands().
23                                                            {
24         String res("<LI><A HREF=\"detailed-items-by-ID.html#"+dilid+"\">"+dilid+"</A> ("+dec(chunkfreq)+")\n");
25         return res;
26 }
String generate_Figures_Directory_entry (String figid)
Definition at line 8 of file ppfilter.cc.
References String::after(), String::before(), String::del(), relurl(), and res.
Referenced by dil2al_commands().
8                                                       {
9         String figlabel, figtype,res;
10         figlabel = figid.before('.',-1);
11         figtype = figid.after('.',-1);
12         figid = figlabel; figlabel.del(BigRegex("^.*/"));
13         figid = relurl(figuresdirectory,figid);
14         res = "<LI><!-- @Begin FIGURE DATA: [fig:"+figlabel+"] "+figid+".eps@ -->\n";
15         res += "[<!-- @Figure label@ -->fig:"+figlabel+"]<BR>\n";
16         if (figtype!="eps") res += "(*)";
17         res += "Figure: <A HREF=\""+figid+".eps\"><!-- @Figure file@ -->"+figid+".eps</A><BR>\n";
18         if (figtype!="fig") res += "(*)";
19         res += "Source: <A HREF=\""+figid+".fig\"><!-- @Figure source@ -->"+figid+".fig</A><BR>\n";
20         if (figtype!="ps") res += "(*)";
21         res += "PostScript: <A HREF=\""+figid+".ps\"><!-- @Figure PostScript@ -->"+figid+".ps</A><BR>\n";
22         res += "Caption: <!-- @Figure caption@ --><BR>\nPSfrag conversions: <PRE><!-- @Begin Figure psconversions@ -->\n<!-- @End Figure psconversions@ --></PRE>\n";
23         res += "Created with:\n<!-- @End FIGURE DATA@ -->\n\n";
24         return res;
25 }
bool generate_modify_element_FORM_interface (StringList * qlist = NULL)
Definition at line 705 of file diladmin.cc.
References DIL_entry::elbyid(), generate_modify_element_FORM_interface_DIL_entry_content(), generate_modify_element_FORM_interface_DIL_entry_parameters(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), Detailed_Items_List::Get_All_Topical_DIL_Parameters(), PLLRoot< DIL_entry >::head(), Detailed_Items_List::list, DIL_ID::valid(), and VOUT.
Referenced by Detect_Form_Input().
705                                                                        {
706 // generates an HTML FORM interface that enables modification of elements
707 // of a DIL entry. The DIL entry is given by a DILID variable in qlist.
708   int dilididx = qlist->contains("DILID");
709   if (dilididx<0) return false;
710   DIL_ID dilid((*qlist)[dilididx].after('='));
711   if (!dilid.valid()) return false;
712   if (calledbyforminput) VOUT << "</PRE><!-- "; // clean up HTML output (dil2al processing output can still be inspected by looking at the HTML source)
713   Detailed_Items_List dilist;
714   if (dilist.Get_All_DIL_ID_File_Parameters()<0) return false;
715   if (!dilist.list.head()) return false;
716   if (dilist.Get_All_Topical_DIL_Parameters(true)<0) return false;
717   DIL_entry * de = dilist.list.head()->elbyid(dilid);
718   if (!de) return false;
719   VOUT << "<!-- comment out process output -->\n";
720   generate_modify_element_FORM_interface_DIL_entry_content(de);
721   VOUT << "<P>&nbsp;<P>\n<HR>\n<P>\n";
722   generate_modify_element_FORM_interface_DIL_entry_parameters(de); //,dilist);
723   VOUT << "<P>&nbsp;<P>\n";
724   return true;
725 }
String generate_tag (String & tagid)
Definition at line 357 of file dil2al.cc.
References res.
Referenced by Assess_Paper_Correction_Time(), dil2al_commands(), and send_dil_to_DIL().
357                                     {
358         const int NUMTAGS = 8, TAGIDSSIZE= 6, TAGSTRSIZE = 300;
359         const char tagids[NUMTAGS][TAGIDSSIZE] = {"CR","GUIDE","LSTY","CHL","CHM","OUTL","EMBH","DESUP"};
360         const char tagstr[NUMTAGS][TAGSTRSIZE] = {"<A NAME=\"TAGname\"><!-- @CRef@ -->TAGanchor</A>",
361                                                                                 "<A NAME=\"TAGname\"><!-- @guideline@ -->TAGanchor</A>",
362                                                                                 "% @LaTeX STYLE REQUIRED: <A HREF=\"relstylepath\">style.sty</A>@",
363                                                                                 "% @Begin CHECKLIST: LISTcaption@\n\\checklist{LISTcaption}{\n% --><TABLE BORDER=\"1\"><CAPTION><B>LISTcaption</B></CAPTION><!--\n}\n% @End CHECKLIST: LISTcaption@ --></TABLE><!--",
364                                                                                 "% @Begin CHECKMARK: MARKtype MARKanchor@\n\\checkmark{0}{MARKtext} (MARKanchor)\\\\\n% --><TR><TD><INPUT TYPE=checkbox NAME=\"MARKtype\" VALUE=\"MARKanchor\"> MARKtext (<A HREF=\"relmarkpath\">MARKanchor</A>)</TD></TR><!--\n% @End CHECKMARK: MARKtype MARKanchor@",
365                                                                                 "% @Begin OUTLINE: Context@\n\\outlinenote{OutlineData}\n% @End OUTLINE: Context@",
366                                                                                 "% @EMBEDDED HTML: HTMLtext@",
367                                                                                 "@DIL Entry Superior: <A HREF=\"#SUPid\">SUPid</A> (SIrel,SIuimp,SIimp,SItd,SIurg,SIpri)@"};
368         if (tagid=="") {
369                 String res;
370                 for (int i = 0; i<NUMTAGS; i++) res += String(tagids[i])+" => "+String(tagstr[i])+'\n';
371                 return res;
372         }
373         for (int i=0; i<NUMTAGS; i++) if (tagid==tagids[i]) return String(tagstr[i]);
374         return String("");
375 }
String generate_TL_chunk_header (String nametag, String newalref, String altitle, String alhead, String newdilref, String diltitle, String dilhead, int generateparts = 0)
Definition at line 52 of file tladmin.cc.
References String::after().
Referenced by add_TL_chunk_or_entry(), and initialize_new_DIL_TL().
52                                                                                                                                                                           {
53 // generatparts = 0 both parts, -1 begin part, 1 end part
54 #ifdef DEBUG
55         cout << "Generating TL chunk header with tag = " << nametag << ", AL = " << newalref << ", DIL entry = " << newdilref << '\n';
56 #endif
57         String chunkheader;
58         if (generateparts<=0) {
59                 chunkheader = "<!-- chunk Begin --><TR><TD><FONT COLOR=\"#FFFFFF\"><A NAME=\""+nametag+"\"><B>"+nametag+"</B></A>\n<!-- chunk AL --><A HREF=\""+newalref+"\">"+altitle+"</A> (";
60                 if (alhead!="") chunkheader += "<A HREF=\""+alhead+"\">previous</A>/next)\n<!-- chunk Context -->";
61                 else chunkheader += "previous/next)\n<!-- chunk Context -->";
62                 if (newdilref[0]=='!') chunkheader += newdilref.after("!")+" (";
63                 else chunkheader += "<A HREF=\""+newdilref+"\">"+diltitle+" "+newdilref.after("#")+"</A> (";
64                 if (dilhead!="") chunkheader +=  "<A HREF=\""+dilhead+"\">previous</A>/next)</FONT>\n<P>\n\n";
65                 else chunkheader += "previous/next)</FONT>\n<P>\n\n";
66         }
67         if (generateparts>=0) {
68                 chunkheader += "<!-- chunk End --></TD></TR>\n\n";
69         }
70         return chunkheader;             
71 }
String generate_TL_entry_header (String nametag, String newalref, String altitle, String alhead, String newdilref, String diltitle, String dilhead)
Definition at line 73 of file tladmin.cc.
References String::after().
Referenced by add_TL_chunk_or_entry(), and initialize_new_DIL_TL().
73                                                                                                                                                    {
74         String entryheader;
75         entryheader = "<!-- entry Begin --><FONT COLOR=\"#FFFFFF\">[<A NAME=\""+nametag+"\"><B>"+nametag.after(".")+"</B></A>";
76         if ((newalref[0]!='*') || (newdilref[0]!='*')) {
77                 entryheader += " -\n<!-- entry AL -->";
78                 if (newalref[0]!='*') {
79                         entryheader += "<A HREF=\""+newalref+"\">"+altitle+"</A> (";
80                         if (alhead!="") entryheader += "<A HREF=\""+alhead+"\">previous</A>/next)\n<!-- entry Context -->";
81                         else entryheader += "previous/next)\n<!-- entry Context -->";
82                 } else entryheader += "\n<!-- entry Context -->";
83                 if (newdilref[0]!='*') {
84                         if (newdilref[0]=='!') entryheader += newdilref.after("!")+" (";
85                         else entryheader += "<A HREF=\""+newdilref+"\">"+diltitle+" "+newdilref.after("#")+"</A> (";
86                         if (dilhead!="") entryheader +=  "<A HREF=\""+dilhead+"\">previous</A>/next)]</FONT>\n<BR>\n";
87                         else entryheader += "previous/next)]</FONT>\n<BR>\n";
88                 } else entryheader += "]</FONT>\n<BR>\n";
89         } else entryheader += "]</FONT>\n"; //*** add "<BR>\n" here?
90         return entryheader;
91 }
bool generate_TL_keyword_index ()
Definition at line 9 of file tlfilter.cc.
9                                  {
10 // keywords can be created with a special tag that you insert anywhere
11 // in a task log entry, or anywhere in HTML or TeX documents or source code or
12 // plain text, plus in the dil2al configuration file
13 }
bool get_active_DIL_IDs (StringList & idfileids, unsigned long * resnumidfileids = NULL)
Definition at line 231 of file diladmin.cc.
References EOUT, find_in_line(), find_line(), pattern_in_line(), and res.
Referenced by add_new_to_DIL(), and get_new_DIL_ID().
231                                                                                         {
232 // obtains all DIL IDs from the DIL-by-ID file
233 // optionally adds the number of IDs found to resnumidfileids
234         const int LLEN = 10240;
235         char lbuf[LLEN];
236         String dilid[2];
237         unsigned long numidfileids = 0;
238         int res;
239         ifstream df(idfile);
240         if (df) {
241                 if (!find_line(&df,"[<]!-- *dil2al: *DIL ID *begin *--[>]",lbuf,LLEN)) {
242                         EOUT << "dil2al: Tag <!-- dil2al: DIL ID begin --> not found in " << idfile << "in get_active_DIL_IDs()\n";
243                         return false;
244                 }
245                 do {
246                         if ((res=find_in_line(&df,"[<]TR[>]",0,NULL,"[<]!-- *dil2al: *DIL ID *end *--[>]",lbuf,LLEN))==1) {
247                                 res = find_in_line(&df,"[<]TD[^>]*[>][<]A +NAME=\"([.0-9]+)\"",2,dilid,"[<]TR[>]|[<]!-- *dil2al: *DIL ID *end *--[>]",lbuf,LLEN);
248                                 if (res<-1) return false;
249                                 idfileids[numidfileids++] = dilid[1];
250                         } else {
251                                 if (res>=-1) res=-1;
252                                 else return false;
253                         }
254                 } while ((res>0) || ((res==0) && (!pattern_in_line("[<]!-- *dil2al: *DIL ID *end *--[>]",lbuf))));
255                 df.close();
256         } else {
257                 EOUT << "dil2al: Unable to open DIL ID file " << idfile << "in get_active_DIL_IDs()\n";
258                 return false;
259         }
260         if (resnumidfileids) (*resnumidfileids) += numidfileids;
261         return true;
262 }
int get_AL_entry (String & alstr, int alpos, String & rowcontent, int & rowstart, int & rowend)
Definition at line 1246 of file alcomp.cc.
References String::contains(), HTML_get_table_cell(), and HTML_get_table_row().
Referenced by remove_AL_TC().
1246                                                                                                {
1247 // gets an entry from an AL table and returns whether that row
1248 // is a Day (0) or a TC (1), returns -1 if row cannot be obtained
1249         String params, cellcontent;
1250         if ((rowend=HTML_get_table_row(alstr,alpos,params,rowcontent,&rowstart))<0) return -1;
1251         if (HTML_get_table_cell(rowcontent,0,params,cellcontent)<0) return -1;
1252         if (cellcontent.contains(BigRegex("[<]!--[      ]+@select_TL_DIL_refs:[         ]+SKIP ROW@[    ]+--[>][^(]*Day"))) return 0;
1253         return 1;
1254 }
double get_double (String valstr, double defval = 0.0, bool * gotdouble = NULL)
Definition at line 2685 of file utilities.cc.
References String::empty(), and String::matches().
Referenced by modify_element_through_FORM_interface(), and modify_element_through_FORM_interface_DIL_Superiors().
2685                                                                                {
2686   // attempts to extract a double variable value from a string
2687   // if no double variable value is found then the value defval is assigned
2688   bool gotdoubledummy;
2689   if (!gotdouble) gotdouble = &gotdoubledummy;
2690   if (valstr.empty()) { (*gotdouble) = false; return defval; }
2691   if (((*gotdouble)=valstr.matches(BRXdouble))==true) return atof((const char *) valstr);
2692   else return defval;
2693 }
void get_figure_data (String & figfile, String & figlabel, String & figcaption, String & figintext, String & psconversions, StringList & srcf, StringList & srcfname, int & srcfnum)
Definition at line 27 of file ppfilter.cc.
27                                                                                                                                                                                     {
28 // obtains missing figure data from the Figures Directory
29 // this function can be called with data in either figfile or figlabel
30         const BigRegex figintextrx("%[  ]*@Begin INTEXT@[ \t\n]*\\(.*\\)%[      ]*@End INTEXT@");
31         int srcidx;
32         if ((srcidx = get_file_in_list(figuresdirectory,srcf,srcfname,srcfnum))<0)
33                 EOUT << "dil2al: Some figure data may be missing in get_figure_data(), continuing as is\n";
34         else {
35                 // find figure data
36                 String findid;
37                 if (!figfile.empty()) findid = relurl(figuresdirectory,figfile);
38                 else if (!figlabel.empty()) findid = figlabel;
39                 else EOUT << "dil2al: No figure file or label, some figure data may be missing in get_figure_data(), continuing as is\n";
40                 if (!findid.empty()) {
41                         int figididx;
42                         if ((figididx = srcf[srcidx].index(BigRegex("[<]!--[    ]@Begin FIGURE DATA:[^@]*"+RX_Search_Safe(findid)+"[^@]*@[      ]*--[>]")))<0) {
43                                 EOUT << "dil2al: Figure " << findid << " not found in get_figure_data(), continuing as is\n";
44                                 if (!figfile.empty()) figfile = findid;
45                                 if (figlabel.empty()) {
46                                         figlabel = figfile.after('/',-1);
47                                         if (figlabel.empty()) figlabel = figfile;
48                                         if (figlabel.index('.',-1)>=0) figlabel = figlabel.before('.',-1);
49                                         figlabel.prepend("fig:");
50                                 }
51                         } else {
52                                 int figidend;
53                                 if ((figidend = srcf[srcidx].index(BigRegex("[<]!--[    ]*@End FIGURE DATA@[    ]*--[>]"),figididx))<0)
54                                         EOUT << "dil2al: Figure " << findid << " End marker missing in get_figure_data(), continuing as is\n";
55                                 else {
56                                         String figdata = srcf[srcidx].at(figididx,figidend-figididx);
57                                         // get figure label
58                                         figlabel = figdata.at(BigRegex("[<]!--[         ]*@Figure label@[       ]*--[>][        ]*[^]<  \n]+"));
59                                         figlabel = figlabel.after(BigRegex("[<]!--[     ]*@Figure label@[       ]*--[>][        ]*"));
60                                         // get figure file
61                                         figfile = figdata.at(BigRegex("[<]!--[  ]*@Figure file@[        ]*--[>][        ]*[^<   \n]+"));
62                                         figfile = figfile.after(BigRegex("[<]!--[       ]*@Figure file@[        ]*--[>][        ]*"));
63                                         int fci = figdata.index(BigRegex("[<]!--[       ]*@Figure caption@[     ]*--[>][        ]*"),String::SEARCH_END);
64                                         // get figure caption
65                                         figcaption = ""; figintext = "";
66                                         if (fci<0) EOUT << "dil2al: Figure " << findid << " ``@Figure caption@'' marker missing in get_figure_data(), continuing as is\n";
67                                         else {
68                                                 int fce = figdata.index(BigRegex("[<][Bb][Rr][>][ \t\n]*PSfrag"),fci);
69                                                 if (fce<0) EOUT << "dil2al: Figure " << findid << " ``<BR>\\nPSfrag'' caption end code missing in get_figure_data(), continuing as is\n";
70                                                 else {
71                                                         figcaption = figdata.at(fci,fce-fci);
72                                                         if (figcaption.index(figintextrx)>=0) { // identify ``INTEXT'' figure descriptions
73                                                                 figintext = "% @Begin INTEXT@\n" + figcaption.sub(figintextrx,1) + "% @End INTEXT@\n"; // place new markers to ensure line ends
74                                                                 fci = figintextrx.subpos(0); fce = figintextrx.subpos(0)+figintextrx.sublen(0);
75                                                                 if (fci>0) if (figcaption.elem(fci-1)=='\n') fci--;
76                                                                 if (fce<figcaption.length()) if (figcaption.elem(fce)=='\n') fce++;
77                                                                 figcaption.del(fci,fce-fci);
78                                                         }
79                                                         // remove troublesome characters from figure caption (cannot use the convert_item_content_to_TeX() function,
80                                                         // since content is already assumed to be in TeX format with codes such as $math-stuff$
81                                                         if (figcaption.gsub(BigRegex("\\([^\\]\\)[%<>]"),"_1X",'_')>0) if (verbose) VOUT << "TeX Correction: Changed special characters in figure caption to `X'\n";
82                                                         if (figcaption.gsub(BigRegex("^[%<>]"),"X")>0) if (verbose) VOUT << "TeX Correction: Changed special characters in figure caption to `X'\n";
83                                                 }
84                                         }
85                                         // get PS conversions
86                                         int pscidx;
87                                         if ((pscidx = figdata.index(BigRegex("[<]!--[   ]*@Begin Figure psconversions@[         ]*--[>][        ]*"),String::SEARCH_END))>=0) {
88                                                 int pscend;
89                                                 if ((pscend = figdata.index(BigRegex("[<]!--[   ]*@End Figure psconversions@[   ]*--[>]"),pscidx))>=0)
90                                                         psconversions = figdata.at(pscidx,pscend-pscidx);
91                                                         if (psconversions=="\n") psconversions = "";
92                                         }
93                                 }
94                         }
95                 }
96         }
97         if (figfile.empty()) figfile = homedir+"doc/tex/common-eps/placeholder.eps";
98         if (figlabel.empty()) figlabel = "fig:unknown";
99         if (figcaption.empty()) figcaption = "\\relax";
100         if (psconversions.empty()) psconversions = "\\relax";
101 }
int get_file_in_list (String & fname, StringList & srcf, StringList & srcfname, int & srcfnum)
Definition at line 6 of file ppfilter.pre-blank.cc.
References EOUT, StringList::iselement(), and read_file_into_String().
Referenced by extract_hierarchy_depth_decrease_to_paper(), extract_hierarchy_depth_increase_to_paper(), extract_recursively(), Text_File_Buffers::FileIndex(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), Detailed_Items_List::Get_All_Topical_DIL_Parameters(), get_figure_data(), and update_DIL_entry_elements().
6                                                                                              {
7 // load a file if it is not already in a list of file-strings
8         int srcidx;
9         if ((srcidx = srcfname.iselement(fname))<0) {
10                 if (!read_file_into_String(fname,srcf[srcfnum])) {
11                         EOUT << "dil2al: Unable to load source document " << fname << " in get_file_in_list()\n";
12                         return -1;
13                 }
14                 srcfname[srcfnum] = fname;
15                 srcidx = srcfnum;
16                 srcfnum++;
17         }
18         return srcidx;
19 }
String get_most_recent_TC_AL (String & tl)
Definition at line 96 of file tladmin.cc.
References String::at(), String::del(), String::prepend(), and RELLISTSDIR.
Referenced by select_TL_AL_refs(), select_TL_DIL_refs(), and stop_TL_chunk().
96                                           {
97 // returns the AL reference of the most recent task chunk
98         String curAL;
99         curAL = tl.at(BigRegex("[<]!-- chunk AL [^(]*"),-1);
100         curAL.del(BigRegex("[<]!-- chunk AL -->[^\"]*\""));
101         curAL.del(BigRegex("\".*"));
102         curAL.prepend(basedir+RELLISTSDIR);
103         return curAL;
104 }
String get_most_recent_TC_DE (String & tl)
Definition at line 106 of file tladmin.cc.
References String::at(), String::del(), and String::gsub().
Referenced by select_TL_DIL_refs(), and stop_TL_chunk().
106                                           {
107 // returns the DIL entry reference of the most recent task chunk
108         String curDE;
109         curDE = tl.at(BigRegex("[<]!-- chunk Context --[>][^\n][^(]*("),-1);
110         curDE.del(BigRegex("[<]!-- chunk Context --[>]"));
111         curDE.del(BigRegex("[<]A [^>]*[Hh][Rr][Ee][Ff][         ]*=[^\"]*\""));
112         curDE.gsub("\">",":");
113         curDE.del(BigRegex("\\([<][^>]*[>]\\)?[         ]*("));
114         return curDE;
115 }
String get_new_DIL_ID ()
Definition at line 553 of file diladmin.cc.
References EOUT, get_active_DIL_IDs(), StringList::get_Next(), and time_stamp().
Referenced by dil2al_commands(), and initialize_new_DIL_TL().
553                         {
554 // generates a new DIL ID based on the current time
555 // and the next single decimal available with that
556 // time stamp (in the unlikely event that there are
557 // already 9 items with that time stamp, it will
558 // try an ID based on another time stamp)
559         // obtain all existing DIL IDs
560         StringList idfileids;
561         unsigned long numidfileids = 0;
562         if (!get_active_DIL_IDs(idfileids,&numidfileids)) {
563                 EOUT << "dil2al: Unable to obtain DIL IDs from " << idfile << '\n';
564                 return "";
565         }
566         // generate a new time stamped DIL ID
567         String newdilid;
568         for (int loopescape=60; (loopescape); loopescape--) { 
569                 String idtimestamp = time_stamp("%Y%m%d%H%M%S");
570                 // try ID decimal indices
571                 for (char decimalindex = '1'; decimalindex <= '9'; decimalindex++) {
572                         newdilid = idtimestamp + '.' + decimalindex;
573                         for (StringList * idfileentry = &idfileids; (idfileentry); idfileentry=idfileentry->get_Next()) {
574                                 if (newdilid==(*idfileentry)[0]) {
575                                         newdilid="";
576                                         break;
577                                 }
578                         }
579                         if (newdilid!="") break;
580                 }
581                 if (newdilid!="") break;
582                 if (loopescape>1) {
583 // #ifdef SYSV
584 //                      poll((struct poll *) 0, (size_t) 0, 1000); /* 1000 msec */
585 // #else
586                         sleep(1); /* usleep(1000000L); 1000000 microsec */
587 // #endif
588                 }
589         }
590         return newdilid;
591 }
bool get_Paper_Plans_Section_IDs (StringList & ppsectionids, StringList & ppsectiontitles, StringList & ppsectiontemplates)
Definition at line 103 of file ppfilter.cc.
103                                                                                                                            {
104 /* obtain registered IDs of paper Sections as
105    listed in the
106    <A HREF="../../doc/html/lists/paper-plans.html#PST">
107    Paper Plans
108    </A> file */
109         String ppfstr;
110         if (!read_file_into_String(paperplansfile,ppfstr)) return false;
111         int pstidx;
112         if ((pstidx = ppfstr.index(BigRegex("[<]A[      ]+[Nn][Aa][Mm][Ee][     ]*=[    ]*\"PST\"")))<0) {
113                 EOUT << "dil2al: Unable to find Paper Section Titles in Paper Plans document in get_Paper_Plans_Section_IDs()\n";
114                 return false;
115         }
116         if ((pstidx = ppfstr.index("<UL>",pstidx))<0) {
117                 EOUT << "dil2al: Section IDs list not found in Paper Plans document in get_Paper_Plans_Section_IDs()\n";
118                 return false;
119         }
120         int pstend = ppfstr.index("</UL>",pstidx);
121         int pstnum = 0;
122         String pstid, psttitle, psttemplate;
123         while ((pstidx = ppfstr.index("<LI>",pstidx+1))>=0) {
124                 if ((unsigned int) pstidx < (unsigned int) pstend) {
125                         if ((pstid = ppfstr.at(BigRegex("[[]\\([<][^>]*[>]\\)?[^]]+"),pstidx))!="") {
126                                 pstid.del("["); pstid.gsub(BigRegex("[<][^>]*[>]"),""); pstid.gsub(BigRegex("[  ]+"),"");
127                                 if ((psttitle = ppfstr.at(BigRegex("[]][^\n]+"),pstidx))!="") {
128                                         psttitle = psttitle.after(BigRegex("[]][        ]*"));
129                                         psttemplate = psttitle.after(BigRegex("[<]A[    ]+[^>]*[Hh][Rr][Ee][Ff][        ]*=[    ]*\""));
130                                         psttemplate = psttemplate.before("\"");
131                                         if (psttemplate!="") psttemplate = absurl(paperplansfile,psttemplate);
132                                         psttitle.gsub(BigRegex("[<][^>]*[>]"),"");
133                                         psttitle.del(BigRegex("[        ]*$"));
134                                         psttitle.upcase();
135                                         ppsectionids[pstnum] = pstid;
136                                         ppsectiontitles[pstnum] = psttitle;
137                                         ppsectiontemplates[pstnum] = psttemplate;
138                                         pstnum++;
139                                 }
140                         }
141                 } else break;
142         }
143         return true;
144 }
unsigned long Get_Target_Directory (StringList & targets, unsigned long i, String dirpath)
Definition at line 470 of file search.cc.
References String::del(), EOUT, file_is_directory(), file_is_regular_or_symlink(), String::lastchar(), String::length(), StringList::length(), and Directory_Access::read().
Referenced by Get_Target_Regex(), and Target_Access::make_local_copy_of_directory().
470                                                                                           {
471         // add filenames from a directory to the list of targets
472         // returns the number of targets added
473         unsigned long num;
474         // get directory content
475         String t;
476         if (dirpath.lastchar()=='/') dirpath.del((int) (dirpath.length()-1),1);
477         Directory_Access da(dirpath);
478         num = da.read(t);
479         if (num<0) {
480                 EOUT << "dil2al: Unable to read directory " << dirpath << '\n';
481                 return 0;
482         }
483         t.del(0,1); // remove first separator character
484         StringList df(t,'/'); String f;
485         // add verified files to targets list and adjust num as needed
486         for (unsigned long j = 0; j<(df.length()-1); j++) {
487                 f = dirpath+'/'+df[j];
488                 if (file_is_regular_or_symlink(f)) {
489                         targets[i] = f;
490                         i++;
491                 } else if (followlinks>0) { // can enable recursive searching of directories
492                         if ((file_is_directory(f)) && (df[j]!=".") && (df[j]!="..")) {
493                                 targets[i] = f;
494                                 i++;
495                         } else num --;
496                 } else num--;
497         }
498         return num;
499 }
unsigned long Get_Target_Regex (StringList & targets, unsigned long i, String dirpath)
Definition at line 501 of file search.cc.
References String::before(), String::contains(), String::del(), EOUT, Get_Target_Directory(), String::length(), StringList::length(), String::matches(), String::sub(), and BigRegex::subpos().
Referenced by search_cmd().
501                                                                                       {
502         // add filenames from a directory to the list of targets that match a regex
503         // returns the number of targets added
504         // the regex is provided as "@regex-pattern@" following the directory, '@' need not be escaped
505         StringList d;
506         BigRegex trx("@[^/]+@$");
507         // get regex
508         if (!dirpath.contains(trx)) {
509                 EOUT << "dil2al: No regex pattern in " << dirpath << " in Get_Target_Regex()\n";
510                 return 0;
511         }
512         String fileregex = dirpath.sub(trx,0); fileregex.del(0,1); fileregex.del((int) (fileregex.length()-1),1);
513         // get directory content
514         unsigned long num = Get_Target_Directory(d,0,dirpath.before(trx.subpos()));
515         // add files that match the regex to targets list and ajust num as needed
516         String filename; BigRegex frx(fileregex);
517         for (unsigned long j = 0; j<d.length(); j++) {
518                 filename = d[j].from(trx.subpos());
519                 if (filename.matches(frx)) {
520                         targets[i] = d[j];
521                         i++;
522                 } else num--;
523         }
524         return num;
525 }
String get_TL_head ()
Definition at line 6 of file tladmin.cc.
References EOUT, res, and VOUT.
Referenced by add_TL_chunk_or_entry(), add_TL_section(), chunk_controller(), make_note(), and process_note().
6                      {
7 // resolves the TL symbolic link to the TL head file
8         if (taskloghead!="") return taskloghead;
9         const int LLEN = 10240;
10         char lbuf[LLEN];
11         int res;
12         if ((res=readlink(tasklog,lbuf,LLEN))<0) {
13                 EOUT << "dil2al: Unable to read Task Log symbolic link\n" << tasklog << " in get_TL_head()\n";
14                 return String("");
15         } else {
16                 lbuf[res]='\0';
17                 if (lbuf[0]=='/') taskloghead=lbuf;
18                 else {
19                         taskloghead = tasklog;
20                         taskloghead.gsub(BigRegex("[^/]*$"),"");
21                         taskloghead += lbuf;
22                 }
23                 if (verbose) VOUT << "Task Log symbolic link resolved to " << taskloghead << '\n';
24                 return taskloghead;
25         }
26 }
int get_topic_keywords ()
Definition at line 6 of file alcomp.cc.
References EOUT, and find_line().
6                          {
7         const int LLEN = 10240;
8         char lbuf[LLEN];
9         ifstream dilfile;
10         for (int i=0; i<numDILs; i++) {
11                 dilfile.open(*(dil[i]));
12                 if (dilfile) {
13                         if (!find_line(&dilfile,"Topic Keywords",lbuf,LLEN)) {
14                                 EOUT << "dil2al: Missing topic keywords in " << *(dil[i]) << " in get_topic_keywords()\n";
15                                 return 0;
16                         }
17                         dilfile.close();
18                 }
19         }
20         return 1;
21 }
void Get_Worked_Estimate ()
Definition at line 301 of file alcomp.cc.
References ACW_ASK, ACW_TIME, ACW_TL, EOUT, and time_stamp_time_of_day().
Referenced by generate_AL().
301                            {
302 // update alworked (in seconds)
303         if (alworked<0) { // (alworked>=0) if given on command line
304                 time_t tod;
305                 switch (alcurdayworkedstrategy) {
306                         case ACW_TIME: // estimate according to current time
307                                 tod = time_stamp_time_of_day(curtime);
308                                 tod -= alworkdaystart;
309                                 if (tod<0) alworked = 0; else alworked = tod;
310                                 break;
311                         case ACW_TL: // *** obtain an estimate from task log entries
312                                 EOUT << "dil2al: ACW_TL option not yet implemented in Get_Worked_Estimate(), setting to 0\n";
313                                 alworked = 0;
314                                 break;
315                         case ACW_ASK: // *** ask for estimate
316                                 EOUT << "dil2al: ACW_ASK option not yet implemented in Get_Worked_Estimate(), setting to 0\n";
317                                 alworked = 0;
318                                 break;
319                         default: alworked = 0;
320                 }
321         }
322 }
int HTML_get_href (String & htmlstr, int strloc, String & hrefurl, String & hreftext, int * hrefstart = NULL)
Definition at line 2483 of file utilities.cc.
References String::at(), EOUT, String::index(), BigRegex::match_info(), and String::SEARCH_END.
Referenced by generate_modify_element_FORM_interface_DIL_entry_content(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), Plan_entry_content::Parse_Entry_Content(), remove_AL_TC(), select_TL_DIL_refs(), and update_main_ALs().
2483                                                                                                              {
2484 // *** warning, this function can't deal properly yet with HREFs that contain
2485 //     HTML font formatting commands (e.g. <B>) in the reference text!
2486         const BigRegex h("[<][Aa][      ]+[^>]*[Hh][Rr][Ee][Ff][        ]*=[    ]*\"\\([^\"]*\\)\"[^>]*[>]\\([^<]*\\)[<]/[Aa][  ]?[^>]*[>]");
2487         if ((strloc=htmlstr.index(h,String::SEARCH_END,strloc))>=0) {
2488                 int s,l;
2489                 if (hrefstart) {
2490                   if (!h.match_info(s,l,0)) return -1;
2491                   else *hrefstart = s;
2492                 }
2493                 if (!h.match_info(s,l,1)) return -1;
2494                 if (l==0) {
2495                         EOUT << "dil2al: Missing HREF URL at " << s << " in HTML_get_href()\n";
2496                         return -1;
2497                 }
2498                 hrefurl = htmlstr.at(s,l);
2499                 if (!h.match_info(s,l,2)) return -1;
2500                 if (l==0) EOUT << "dil2al: Warning - Invisible HREF anchor at " << s << " in HTML_get_href(), continuing\n";
2501                 hreftext = htmlstr.at(s,l);
2502         }
2503         return strloc;
2504 }
int HTML_get_list (String & htmlstr, int strloc, String & listparams, String & listcontent, int * liststart = NULL)
Definition at line 2469 of file utilities.cc.
References HTML_get_tagged_environment().
Referenced by Plan_entry_content::Parse_Entry_Content(), and update_main_ALs().
2469                                                                                                                    {
2470         const BigRegex lm("[<][UuOo][Ll]");
2471         const BigRegex l("\\([<]/[UuOo][Ll]\\|[<]/[Tt][Aa][Bb][Ll][Ee]\\|[<]/[Bb][Oo][Dd][Yy]\\|[<]/[Hh][Tt][Mm][Ll]\\)");
2472         const BigRegex le("[<]/[UuOo][Ll][^>][>]"); 
2473         return HTML_get_tagged_environment(lm,l,le,htmlstr,strloc,listparams,listcontent,liststart);
2474 }
int HTML_get_list_item (String & htmlstr, int strloc, String & itemparams, String & itemcontent, int * itemstart = NULL)
Definition at line 2476 of file utilities.cc.
References HTML_get_tagged_environment().
Referenced by Plan_entry_content::Parse_Entry_Content(), and update_main_ALs().
2476                                                                                                                         {
2477         const BigRegex im("[<][Ll][Ii]");
2478         const BigRegex i("\\([<]/?[Ll][Ii]\\|[<]/[UuOo][Ll]\\|[<]/[Tt][Aa][Bb][Ll][Ee]\\|[<]/[Bb][Oo][Dd][Yy]\\|[<]/[Hh][Tt][Mm][Ll]\\)");
2479         const BigRegex ie("[<]/[Ll][Ii][^>][>]");
2480         return HTML_get_tagged_environment(im,i,ie,htmlstr,strloc,itemparams,itemcontent,itemstart);
2481 }
int HTML_get_marker (String & htmlstr, int strloc, String & marker, bool locate = true)
Definition at line 2411 of file utilities.cc.
References String::at(), String::index(), String::length(), and BigRegex::match_info().
Referenced by HTML_get_tagged_environment().
2411                                                                                       {
2412         const BigRegex m("[<][^>]+[>]");
2413         // find start of marker
2414         if (locate) {
2415                 if ((strloc=htmlstr.index(m,strloc))<0) return -1;
2416                 // get marker
2417                 int s,l;
2418                 m.match_info(s,l,0);
2419                 marker = htmlstr.at(s,l);
2420                 return strloc+l;
2421         }
2422         // get marker
2423         marker = htmlstr.at(m,strloc); // assumes marker starts at strloc
2424         return strloc+marker.length();
2425 }
int HTML_get_name (String & htmlstr, int strloc, String & nametag, String & nametext)
Definition at line 2506 of file utilities.cc.
References String::at(), EOUT, String::index(), BigRegex::match_info(), and String::SEARCH_END.
Referenced by Detailed_Items_List::Get_All_Topical_DIL_Parameters(), and update_main_ALs().
2506                                                                                      {
2507         const BigRegex n("[<][Aa][      ]+[^>]*[Nn][Aa][Mm][Ee][        ]*=[    ]*\"\\([^\"]*\\)\"[^>]*[>]\\([^<]*\\)[<]/[Aa][  ]?[^>]*[>]");
2508         if ((strloc=htmlstr.index(n,String::SEARCH_END,strloc))>=0) {
2509                 int s,l;
2510                 if (!n.match_info(s,l,1)) return -1;
2511                 if (l==0) {
2512                         EOUT << "dil2al: Missing NAME tag at " << s << " in HTML_get_name()\n";
2513                         return -1;
2514                 }
2515                 nametag = htmlstr.at(s,l);
2516                 if (!n.match_info(s,l,2)) return -1;
2517                 if (l==0) EOUT << "dil2al: Warning - Invisible NAME anchor at " << s << " in HTML_get_name(), continuing\n";
2518                 nametext = htmlstr.at(s,l);
2519         }
2520         return strloc;
2521 }
int HTML_get_table_cell (String & htmlstr, int strloc, String & cellparams, String & cellcontent, int * cellstart = NULL)
Definition at line 2455 of file utilities.cc.
References HTML_get_tagged_environment().
Referenced by Financial_Note::get(), get_AL_entry(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), Detailed_Items_List::Get_All_Topical_DIL_Parameters(), select_TL_DIL_refs(), and update_DIL_entry_elements().
2455                                                                                                                          {
2456         const BigRegex cm("[<][Tt][Dd]");
2457         const BigRegex c("\\([<]/?[Tt][DdRr]\\|[<]/[Tt][Aa][Bb][Ll][Ee]\\|[<]/[Bb][Oo][Dd][Yy]\\|[<]/[Hh][Tt][Mm][Ll]\\)");
2458         const BigRegex ce("[<]/[Tt][Dd][^>]*[>]");
2459         return HTML_get_tagged_environment(cm,c,ce,htmlstr,strloc,cellparams,cellcontent,cellstart);
2460 }
int HTML_get_table_row (String & htmlstr, int strloc, String & rowparams, String & rowcontent, int * rowstart = NULL)
Definition at line 2462 of file utilities.cc.
References HTML_get_tagged_environment().
Referenced by Financial_Note::get(), get_AL_entry(), Detailed_Items_List::Get_All_Topical_DIL_Parameters(), and Detailed_Items_List::Write_to_File().
2462                                                                                                                      {
2463         const BigRegex rm("[<][Tt][Rr]");
2464         const BigRegex r("\\([<]/?[Tt][Rr]\\|[<]/[Tt][Aa][Bb][Ll][Ee]\\|[<]/[Bb][Oo][Dd][Yy]\\|[<]/[Hh][Tt][Mm][Ll]\\)");
2465         const BigRegex re("[<]/[Tt][Rr][^>][>]");
2466         return HTML_get_tagged_environment(rm,r,re,htmlstr,strloc,rowparams,rowcontent,rowstart);
2467 }
int HTML_get_tagged_environment (const BigRegex & begintag, const BigRegex & endmatch, const BigRegex & endtag, String & htmlstr, int strloc, String & envparams, String & envcontent, int * envstart = NULL)
Definition at line 2433 of file utilities.cc.
References String::at(), HTML_get_marker(), String::index(), String::length(), and String::SEARCH_END.
Referenced by HTML_get_list(), HTML_get_list_item(), HTML_get_table_cell(), and HTML_get_table_row().
2433                                                                                                                                                                                                              {
2434 // searches for an environment beginning with a tag matching begintag,
2435 // determines the environment end according to possible matches in endmatch,
2436 // returns tag parameters in envparams, environment contents in envcontent,
2437 // optionally returns the start of the environment in envstart, and
2438 // returns the position directly after the environment and a potential
2439 // endtag
2440         // find start of environment
2441         if ((strloc=htmlstr.index(begintag,strloc))<0) return -1;
2442         if (envstart) (*envstart) = strloc;
2443         // get environment tag parameters
2444         if ((strloc=HTML_get_marker(htmlstr,strloc,envparams,false))<0) return -1;
2445         // get environment content
2446         int envend = htmlstr.index(endmatch,strloc);
2447         if (envend<0) envend = htmlstr.length();
2448         envcontent = htmlstr.at(strloc,envend-strloc);
2449         // skip possible end tag
2450         int envendtagend = htmlstr.index(endtag,String::SEARCH_END,envend);
2451         if (envendtagend>=0) envend = envendtagend;
2452         return envend;
2453 }
String HTML_marker_arguments (String & marker)
Definition at line 2427 of file utilities.cc.
References String::before(), String::from(), String::length(), and res.
Referenced by Detailed_Items_List::Write_to_File().
2427                                               {
2428         const BigRegex a("[     ]");
2429         String res = marker.from(a); if (res.length()>=1) res = res.before((int) res.length()-1);
2430         return res;
2431 }
String HTML_put_form (String formmethod, String formaction, String formcontent)
Definition at line 2593 of file utilities.cc.
Referenced by AL_Passed_Target_Dates().
2593                                                                                {
2594         return "<FORM METHOD="+formmethod+" ACTION=\""+formaction+"\">"+formcontent+"</FORM>";
2595 }
String HTML_put_form_checkbox (String checkboxname, String checkboxvalue, String checkboxtext, bool checked = false)
Definition at line 2617 of file utilities.cc.
References HTML_put_form_input().
Referenced by AL_Passed_Target_Dates(), generate_AL(), and generate_EPS_cells().
2617                                                                                                                     {
2618         String checkedstr;
2619         if (checked) checkedstr = "\" checked"; else checkedstr = "\"";
2620         return HTML_put_form_input("checkbox","name=\""+checkboxname+"\" value=\""+checkboxvalue+checkedstr)+' '+checkboxtext;
2621 }
String HTML_put_form_input (String inputtype, String inputargs)
Definition at line 2597 of file utilities.cc.
References String::length().
Referenced by AL_Passed_Target_Dates(), HTML_put_form_checkbox(), HTML_put_form_radio(), HTML_put_form_reset(), HTML_put_form_submit(), and HTML_put_form_text().
2597                                                                {
2598         String inputstr("<INPUT type=\""+inputtype+'"');
2599         if (inputargs.length()>0) return inputstr+' '+inputargs+'>';
2600         else return inputstr+'>';
2601 }
String HTML_put_form_radio (String radioname, String radiovalue, String radiotext, bool checked = false)
Definition at line 2611 of file utilities.cc.
References HTML_put_form_input().
Referenced by AL_Passed_Target_Dates(), and generate_modify_element_FORM_interface_DIL_Superiors().
2611                                                                                                         {
2612         String checkedstr;
2613         if (checked) checkedstr = "\" checked"; else checkedstr = "\"";
2614         return HTML_put_form_input("radio","name=\""+radioname+"\" value=\""+radiovalue+checkedstr)+' '+radiotext;
2615 }
String HTML_put_form_reset ()
Definition at line 2607 of file utilities.cc.
References HTML_put_form_input().
Referenced by AL_Passed_Target_Dates().
2607                              {
2608         return HTML_put_form_input("reset","");
2609 }
String HTML_put_form_submit (String submittext)
Definition at line 2603 of file utilities.cc.
References HTML_put_form_input().
Referenced by AL_Passed_Target_Dates().
2603                                                {
2604         return HTML_put_form_input("submit","value=\""+submittext+'"');
2605 }
String HTML_put_form_text (String textname, long maxlen = -1)
Definition at line 2630 of file utilities.cc.
Referenced by AL_Passed_Target_Dates(), generate_AL(), and generate_EPS_cells().
2630                                                              {
2631         return HTML_put_form_text(textname,"",maxlen);
2632 }
String HTML_put_form_text (String textname, String textvalue, long maxlen = -1)
Definition at line 2623 of file utilities.cc.
2623                                                                                {
2624         textname += '"';
2625         if (textvalue.length()>0) textname += " value=\"" + textvalue + '"';
2626         if (maxlen>0) textname += " maxlength=" + String(maxlen);
2627         return HTML_put_form_input("text","name=\""+textname);
2628 }
String HTML_put_href (String hrefurl, String hreftext)
Definition at line 2585 of file utilities.cc.
Referenced by AL_Day_Marker(), AL_Passed_Target_Dates(), generate_AL(), Active_List::generate_focused_AL(), generate_modify_element_FORM_interface_DIL_entry_content(), generate_modify_element_FORM_interface_DIL_entry_parameters(), Active_List::generate_wide_AL(), Target_Access::make_local_copy_of_directory(), update_main_ALs(), DIL_Visualize_with_HTML_Tabs::Visualize_Element(), DIL_Visualize_with_FORM_Tabs::Visualize_Element(), and Detailed_Items_List::Write_to_File().
2585                                                       {
2586         return "<A HREF=\""+hrefurl+"\">"+hreftext+"</A>";
2587 }
String HTML_put_list (char listtype, String htmlstr)
Definition at line 2577 of file utilities.cc.
References HTML_put_structure().
Referenced by update_main_ALs().
2577                                                    {
2578         return HTML_put_structure(listtype+String("L"),"",htmlstr);
2579 }
String HTML_put_list_item (String htmlstr, bool relaxedhtml = false)
Definition at line 2581 of file utilities.cc.
References HTML_put_structure().
Referenced by Active_List::generate_wide_AL(), and update_main_ALs().
2581                                                                     {
2582         return HTML_put_structure("LI","",htmlstr,relaxedhtml);
2583 }
String HTML_put_name (String nametag, String nametext)
Definition at line 2589 of file utilities.cc.
Referenced by Detailed_Items_List::Write_to_File().
2589                                                       {
2590         return "<A NAME=\""+nametag+"\">"+nametext+"</A>";
2591 }
String HTML_put_structure (String tag, String params, String content, bool relaxedhtml = false)
Definition at line 2561 of file utilities.cc.
References String::prepend().
Referenced by HTML_put_list(), HTML_put_list_item(), HTML_put_table_cell(), and HTML_put_table_row().
2561                                                                                                {
2562         params.prepend('<'+tag);
2563         params += '>'+content;
2564         if (relaxedhtml) return params;
2565         params += "</"+tag+">\n";
2566         return params;
2567 }
String HTML_put_table_cell (String cellparams, String cellcontent, bool relaxedhtml = false)
Definition at line 2573 of file utilities.cc.
References HTML_put_structure().
Referenced by AL_Day_Marker(), generate_AL(), generate_EPS_cells(), Active_List::generate_focused_AL(), Financial_Note::put(), update_DIL_entry_elements(), and Detailed_Items_List::Write_to_File().
2573                                                                                             {
2574         return HTML_put_structure("TD",cellparams,cellcontent,relaxedhtml);
2575 }
String HTML_put_table_row (String rowparams, String rowcontent, bool relaxedhtml = false)
Definition at line 2569 of file utilities.cc.
References HTML_put_structure().
Referenced by AL_Day_Marker(), generate_AL(), Active_List::generate_focused_AL(), Financial_Note::put(), remove_AL_TC(), and Detailed_Items_List::Write_to_File().
2569                                                                                          {
2570         return HTML_put_structure("TR",rowparams,rowcontent,relaxedhtml);
2571 }
String* HTML_remove_comments (String & htmlstr)
Definition at line 2530 of file utilities.cc.
References String::alloc(), String::at(), String::index(), String::length(), res, and String::SEARCH_END.
Referenced by Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), and Plan_entry_content::Parse_Entry_Content().
2530                                                 {
2531   int cidx, cend = 0; String res;
2532   res.alloc(htmlstr.length());
2533   while ((cidx=htmlstr.index("<!--",cend))>=0) {
2534     if (cidx>cend) res += htmlstr.at(cend,cidx-cend);
2535     if ((cend=htmlstr.index(BigRegex("--[       ]*[>]"),String::SEARCH_END,cidx))<0) cend=htmlstr.length();
2536   }
2537   cidx=htmlstr.length();
2538   if (cidx>cend) res += htmlstr.at(cend,cidx-cend);
2539   htmlstr = res;
2540   return &htmlstr;
2541 }
String* HTML_remove_tags (String & htmlstr)
Definition at line 2555 of file utilities.cc.
References String::gsub().
Referenced by AL_Passed_Target_Dates(), generate_AL(), Active_List::generate_focused_AL(), generate_modify_element_FORM_interface_DIL_Superiors(), Active_List::generate_wide_AL(), Detailed_Items_List::Get_All_Topical_DIL_Parameters(), select_TL_DIL_refs(), update_DIL_entry_elements(), DIL_Visualize_with_Tabs::Visualize_Element(), DIL_Visualize_with_HTML_Tabs::Visualize_Element(), and DIL_Visualize_with_FORM_Tabs::Visualize_Element().
2555                                             {
2556         const BigRegex m("[<][^>]+[>]");
2557         htmlstr.gsub(m,"");
2558         return &htmlstr;
2559 }
String* HTML_safe (String & textstr)
Definition at line 2523 of file utilities.cc.
References String::gsub().
Referenced by Search_Result::HTML_put_text().
2523                                      {
2524         textstr.gsub("&","&amp;");
2525         textstr.gsub("<","&lt;");
2526         textstr.gsub(">","&gt;");
2527         return &textstr;
2528 }
bool initialize_new_DIL_TL (String initializecmd, bool includeinput)
Definition at line 2358 of file utilities.cc.
References DIN, EOUT, generate_TL_chunk_header(), generate_TL_entry_header(), get_new_DIL_ID(), and read_data_from_stream().
Referenced by dil2al_commands().
2358                                                                     {
2359 // sends a DIL template with a new DIL ID, or a Task Log chunk or entry template to stdout
2360         if (initializecmd=="tc") { // initialize Task Log chunk
2361                 cout << generate_TL_chunk_header("{"+curtime+"}","{relative-active-list-url}","{Active List Title}","{#tag-previous-AL-head}","relative-DIL-url","DIL Title/Non-DIL Identifying Comment","#tag-previous-DIL-head",-1) << "<!-- edit items in ``{}'' brackets";
2362                 if (!includeinput) cout << " and add entries here";
2363                 cout << " then close chunk -->\n";
2364         } else if (initializecmd=="te") { // initialize Task Log entry
2365                 cout << generate_TL_entry_header("{"+curtime+"}.{1}","{relative-active-list-url}","{Active List Title}","{#tag-previous-AL-head}","relative-DIL-url","DIL Title/Non-DIL Identifying Comment","#tag-previous-DIL-head") << "<!-- edit items in ``{}'' brackets";
2366                 if (!includeinput) cout << " and add content here";
2367                 cout << " -->\n";
2368         } else { // initialize DIL entry
2369                 String newdilid = get_new_DIL_ID();
2370                 if (newdilid=="") {
2371                         EOUT << "dil2al: Unable to generate new DIL ID in initialize_new_DIL_TL()\n";
2372                         return false;
2373                 }
2374                 cout << "<TR BGCOLOR=\"#00005F\">\n<TD WIDTH=\"15%\"><A NAME=\""
2375                         << newdilid << "\" HREF=\"detailed-items-by-ID.html#"
2376                         << newdilid << "\">" << newdilid
2377                         << "</A>\n<TD><B>time started:</B> - <B>time required:</B> ?.?hrs <B>completion ratio:</B> 0.0 <B>valuation:</B> ?.?\n<TR>\n<TD COLSPAN=2>";
2378         }
2379         if (includeinput) {
2380                 const int LLEN = 10240;
2381                 char lbuf[LLEN];
2382                 String dentrybuf;
2383                 read_data_from_stream(DIN,dentrybuf,"@End of DIL entry@");
2384                 cout << dentrybuf;
2385         }
2386         if (initializecmd=="tc") { // Task Log chunk
2387                 cout << generate_TL_chunk_header("","","","","","","",1);
2388         } else if (initializecmd=="te") { // Task Log entry
2389                 cout << "<P>\n\n";
2390         } else { // DIL entry
2391                 cout << "\n\n";
2392         }
2393         return true;
2394 }
String Int2HexStr (unsigned int i)
Definition at line 2666 of file utilities.cc.
References String::prepend().
2666                                   {
2667   // convert integer to hexadecimal string
2668   String s;
2669   if (i==0) s = "0";
2670   else {
2671     while (i>0) {
2672       int j = i % 16; i = i / 16;
2673       if (j<10) s.prepend(('0'+(char) j));
2674       else s.prepend(('A'+(char) (j-10)));
2675     }
2676   }
2677   return s;
2678 }
float linear_day_distribution (AL_Day * ald, time_t td)
float linear_distribution (float i, float i_limit)
Definition at line 268 of file alcomp.cc.
Referenced by AL_TC::AL_TC(), and AL_Day::set_TC_values().
268                                                   {
269 // linearly distribute TC values (see TL#200006291007.2)
270         return 1.0 - (0.9*i/i_limit);
271 }
int locate_most_recent_TL_chunk (String & tl, int seekfrom, String * chunkid)
Definition at line 944 of file tladmin.cc.
References String::at(), String::del(), EOUT, and String::index().
Referenced by decide_add_TL_chunk(), and stop_TL_chunk().
944                                                                              {
945 // seeks from seekfrom through the task log to find the
946 // most recent chunk, set seekfrom==-1 to search backwards
947 // from the end of the task log
948 // returns the starting location of the most recent chunk or the
949 // beginning of the section (-1 == not found)
950 // if chunkid!=NULL sets (*chunkid) to the chunk ID or to "" if
951 // the beginning of the section is returned
952 // requires a valid task log section in tl
953         int tlinsertloc;
954         if ((tlinsertloc = tl.index(BigRegex("[<]!--[   ]+chunk Begin[  ]+--[>]"),seekfrom))<0) {
955                 if (chunkid) (*chunkid) = ""; // no chunks in TL
956                 if ((tlinsertloc = tl.index(BigRegex("[<]!--[   ]+section Begin[        ]+--[>]")))<0) {
957                         // TL section not properly formatted
958                         EOUT << "dil2al: Section Begin not found in " << taskloghead << " in locate_most_recent_TL_chunk()\n";
959                         return -1;
960                 } 
961                 return tlinsertloc;
962         }
963         if (chunkid) {
964                 // get chunk time stamp at tlinsertloc
965                 (*chunkid) = tl.at(BigRegex("[<]TR[>][<]TD[>][<][^>]*=[^>]*[>][<]A[     ]+[Nn][Aa][Mm][Ee][     ]*=[    ]*\"[0-9]+"),tlinsertloc);
966                 chunkid->del(BigRegex("[<]TR[>][<]TD[>][<][^>]*=[^>]*[>][<]A[   ]+[Nn][Aa][Mm][Ee][     ]*=[    ]*\""));
967         }
968         return tlinsertloc;
969 }
bool Lock_File (String lockfile, String msgstr)
Definition at line 1399 of file utilities.cc.
References EOUT, and prepare_temporary_file().
Referenced by Detailed_Items_List::Read_from_Binary_Cache(), Detailed_Items_List::Read_Topical_from_Binary_Cache(), Detailed_Items_List::Write_to_Binary_Cache(), and Detailed_Items_List::Write_Topical_to_Binary_Cache().
1399                                                {
1400   // check for lock file
1401   struct stat statbuf;
1402   if (stat(lockfile,&statbuf)!=-1) EOUT << "dil2al: Warning - lock file " << lockfile <<  " in use by other process, waiting for release of lock in Lock_File()\n";
1403   while (stat(lockfile,&statbuf)!=-1) sleep(5);
1404   // lock and write to binary cache file
1405   return prepare_temporary_file(lockfile,msgstr);
1406 }
bool make_note ()
Definition at line 384 of file note.cc.
References String::after(), ANSI_BOLD_OFF, ANSI_BOLD_ON, ANSI_UNDERLINE_OFF, ANSI_UNDERLINE_ON, String::before(), copy_until_line(), String::del(), EOUT, find_line(), get_TL_head(), String::gsub(), String::matches(), prepare_temporary_file(), String::prepend(), process_note(), relurl(), res, time_stamp(), and VOUT.
Referenced by chunk_controller(), and dil2al_commands().
384                  {
385         const int LLEN = 65525; // was 10240
386         char lbuf[LLEN];
387         int q,res;
388         // open an editor for a plain text entry
389         String noteinit;
390         if (suggestnameref) {
391                 noteinit = "<A NAME=\"TL-ref-" + curtime + "\" HREF=\"@TLURL@#@TLNEXTENTRY@\">_</A>";
392                 if (verbose) VOUT << "Note: If destination is Task Log and suggested reference is not altered,\nthen " << noteinit << " will be cleaned up automatically.\n";
393         }
394         if (!prepare_temporary_file(notetmpfile,noteinit)) return false;
395         if (system(editor+" "+notetmpfile)<0) return false;
396         // refresh curtime to avoid misrepresentations due to constantly open note editing window
397         curtime = time_stamp("%Y%m%d%H%M");
398         // request destination of note
399         if (useansi) cout << ANSI_UNDERLINE_ON; // underline on
400         cout << "Destination of note (default = Task Log)\n";
401         if (useansi) cout << ANSI_UNDERLINE_OFF; // underline off
402         // get quick-chooser options from configuration file
403         for (int i=0; i<quicknotedstnum; i++) cout << i << ' ' << quicknotedsttitle[i] << quicknotedescr[i] << '\n';
404         if (useansi) cout << ANSI_BOLD_ON; // bold on
405         cout << "or enter file path: ";
406         if (useansi) cout << ANSI_BOLD_OFF; // bold off
407         cin.getline(lbuf,LLEN);
408         String notedst = lbuf;
409         if (notedst == "") {
410                 notedst = tasklog;
411                 cout << "notedst = " << notedst << '\n';
412                 if (suggestnameref) {
413                         // clean up unnecessary (self-)reference NAME tag
414                         ifstream ntf(notetmpfile);
415                         if (!ntf) EOUT << "dil2al: Unable to open " << notetmpfile << " for removal of spurious NAME tag in make_note(), continuing as is\n";
416                         else {
417                                 ofstream ntfnew(notetmpfile+".tlref_cleaned");
418                                 if (!ntfnew) {
419                                         EOUT << "dil2al: Unable to create " << notetmpfile << ".tlref_cleaned in make_note(), continuing as is\n";
420                                         ntf.close();
421                                 } else {
422                                         if ((res=copy_until_line(&ntf,&ntfnew,noteinit,lbuf,LLEN))==1) {
423                                                 String noteline(lbuf); noteline.del(noteinit);
424                                                 ntfnew << noteline << '\n';
425                                                 ntfnew << ntf.rdbuf();
426                                                 ntf.close(); ntfnew.close();
427                                                 if (rename(notetmpfile+".tlref_cleaned",notetmpfile)<0) EOUT << "dil2al: Unable to rename " << notetmpfile << ".tlref_cleaned to " << notetmpfile << "\nin make_note(), continuing as is\n";
428                                         } else {
429                                                 ntf.close(); ntfnew.close();
430                                                 if (res<0) EOUT << "dil2al: Unable to remove unnecessary NAME tag in make_note(), continuing as is\n";
431                                                 if (unlink(notetmpfile+".tlref_cleaned")<0) EOUT << "dil2al: Unable to remove " << notetmpfile << ".tlref_cleaned in make_note(), continuing as is\n";
432                                         }
433                                 }
434                         }
435                 }
436         } else {
437                 // default destination document title is file name
438                 String notedsttitle = notedst; notedsttitle.gsub(BigRegex(".*/"),"");
439                 // obtain quick-chooser destinations
440                 if (notedst.matches(BRXint)) {
441                         q = atoi((const char *) notedst);
442                         if ((q>=0) && (q<quicknotedstnum)) {
443                                 notedst = quicknotedst[q];
444                                 notedsttitle = quicknotedsttitle[q];
445                         } else {
446                                 EOUT << "dil2al: Selection " << q << " is not a predefined note destination\n";
447                                 return false;
448                         }
449                 }
450                 // if not task log, request task log reference line, suggest reference to note
451                 if (notedst[0]!='/') notedst.prepend(homedir);
452                 if (verbose) VOUT << "Note destination to process: " << notedst << '\n';
453                 String tlentryinit = "<A HREF=\""+relurl(get_TL_head(),notedst);
454                 ifstream ntf(notetmpfile);
455                 if (!ntf) { EOUT << "dil2al: Unable to open " << notetmpfile << " in make_note()\n"; return false; }
456                 // this NAME could be the suggested one, or one modified/set manually
457                 if (find_line(&ntf,"[<][Aa][    ]+[^>]*[Nn][As][Mm][Ee]=[       ]*\"[^>]+[>]",lbuf,LLEN)) {
458                         String tlref(lbuf); tlref = tlref.after(BigRegex("[<][Aa][      ]+[^>]*[Nn][As][Mm][Ee]=[       ]*\""));
459                         tlentryinit = tlentryinit + '#' +tlref.before("\"");
460                 }
461                 ntf.close();
462                 tlentryinit +="\">("+notedsttitle+")</A>";
463                 if (!prepare_temporary_file(tlentrytmpfile,tlentryinit)) return false;
464                 if (verbose) VOUT << "Task Log entry referring to note (if any)...\n";
465                 if (system(editor+" "+tlentrytmpfile)<0) return false;
466                 newTLID = ""; // clear to test if properly generated
467                 if (!process_note(tlentrytmpfile,tasklog)) return false;
468                 if (newTLID=="") {
469                         if (verbose) VOUT << "No new Task Log entry ID, perhaps entry was empty (removing @TLURL@ and\n@TLNEXTENTRY@ references)\n";
470                         // remove HREF="@TLURL@#@TLNEXTENTRY@" references from notedst
471                         ntf.open(notetmpfile);
472                         if (!ntf) EOUT << "dil2al: Unable to remove spurious @TLURL@ and @TLNEXTENTRY@ references in\nmake_note(), continuing as is\n";
473                         else {
474                                 ofstream ntfnew(notetmpfile+".tlurl_cleaned");
475                                 if (!ntfnew) EOUT << "dil2al: Unable to creaete " << notetmpfile << ".tlurl_cleaned in make_note(),\ncontinuing as is\n";
476                                 else {
477                                         while (ntf) {
478                                                 if ((res=copy_until_line(&ntf,&ntfnew,"@TLURL@|@TLNEXTENTRY@",lbuf,LLEN))==1) {
479                                                         tlentryinit = lbuf;
480                                                         tlentryinit.gsub(BigRegex("[<][Aa][     ]+[Hh][Rr][Ee][Ff][     ]*=[    ]*\"[^\"]*\\(@TLURL@\\|@TLNEXTENTRY@\\)[^\"]*\"[        ]*[>][^<]*[<]/[Aa][>]"),"");
481                                                         tlentryinit.gsub(BigRegex("[    ]+[Hh][Rr][Ee][Ff][     ]*=[    ]*\"[^\"]*\\(@TLURL@\\|@TLNEXTENTRY@\\)[^\"]*\"[        ]*"),"");
482                                                         ntfnew << tlentryinit << '\n';
483                                                 } else break;
484                                         }
485                                         ntfnew.close();
486                                         if (res<0) EOUT << "dil2al: Unable to remove spurious @TLURL@ and @TLNEXTENTRY@ references in\nmake_note(), continuing as is\n";
487                                         else if (rename(notetmpfile+".tlurl_cleaned",notetmpfile)<0) EOUT << "dil2al: Unable to rename " << notetmpfile << ".tlurl_cleaned to " << notetmpfile << "\nin make_note(), continuing as is\n";
488                                 }
489                                 ntf.close();
490                         }
491                 } else {
492                         // parse notedst to fill in @TLURL@ and @TLNEXTENTRY@
493                         ntf.open(notetmpfile);
494                         if (!ntf) EOUT << "dil2al: Unable to fill in @TLURL@ and @TLNEXTENTRY@ references in\nmake_note(), continuing as is\n";
495                         else {
496                                 ofstream ntfnew(notetmpfile+".tlurl");
497                                 if (!ntfnew) EOUT << "dil2al: Unable to create " << notetmpfile << ".tlurl in make_note(),\ncontinuing as is\n";
498                                 else {
499                                         String tlurl(relurl(notedst,get_TL_head()));
500                                         while (ntf) {
501                                                 if ((res=copy_until_line(&ntf,&ntfnew,"@TLURL@|@TLNEXTENTRY@",lbuf,LLEN))==1) {
502                                                         tlentryinit = lbuf;
503                                                         tlentryinit.gsub("@TLURL@",tlurl);
504                                                         tlentryinit.gsub("@TLNEXTENTRY@",newTLID);
505                                                         ntfnew << tlentryinit << '\n';
506                                                 } else break;
507                                         }
508                                         ntfnew.close();
509                                         if (res<0) EOUT << "dil2al: Unable to fill in @TLURL@ and @TLNEXTENTRY@ references in\nmake_note(), continuing as is\n";
510                                         else if (rename(notetmpfile+".tlurl",notetmpfile)<0) EOUT << "dil2al: Unable to rename " << notetmpfile << ".tlurl to " << notetmpfile << "\nin make_note(), continuing as is\n";
511                                 }
512                                 ntf.close();
513                         }
514                 }
515         }
516         return process_note(notetmpfile,notedst);
517 }
int max_chunk_entry (String & tlchunk)
Definition at line 28 of file tladmin.cc.
References String::after(), String::before(), String::index(), and String::matches().
Referenced by add_TL_chunk_or_entry().
28                                       {
29 // searches for the largest entry number in a Task Log chunk
30 // returns 0 if there are no entries
31 // note that this works even if the entries are not in order or entry numbers are missing
32 #ifdef DEBUG
33         cout << "TLCHUNK:\n" << tlchunk << '\n';
34 #endif
35         int maxentry = 0, entryindex = -1;
36         while ((entryindex = tlchunk.index(BigRegex("[<]!--[    ]*entry Begin[  ]*--[>]"),entryindex+1))>=0) {
37                 String entryid = tlchunk.before(BigRegex("[     ]*[<]/B[>]"),entryindex);
38                 entryid = entryid.after("<B>",-1);
39                 int entryidnum;
40                 if (entryid.matches(BRXint)) entryidnum = atoi((const char *) entryid);
41 #ifdef DEBUG
42                 cout << "entryid = " << entryid << "\nentryidnum = " << entryidnum << '\n';
43 #endif
44                 if (entryidnum>maxentry) maxentry = entryidnum;
45         }
46 #ifdef DEBUG
47         cout << "maxentry = " << maxentry << '\n';
48 #endif
49         return maxentry;
50 }
bool modify_DIL_entry_target_date (DIL_ID dilid, time_t tdate)
Definition at line 1050 of file diladmin.cc.
References EOUT, PLLRoot< DIL_entry >::head(), Detailed_Items_List::list, PLL_LOOP_FORWARD, res, and Detailed_Items_List::Write_to_File().
Referenced by modify_DIL_group_target_dates(), and Modify_Element().
1050                                                               {
1051 // modify the target date of dilid in all self- or superior-
1052 // references (dilid can be initialized from a String) and
1053 // write to DIL ID file
1054 // Target dates are modified locally, without regard to target
1055 // dates of superiors. If no target date was previously given,
1056 // a set of parameters is created. The target date -1 indicates
1057 // that target dates should be set to "?", i.e. unspecified.
1058 // Modifications are made only if tdate differs from Target_Date().
1059 // (Note: Use `modify_DIL_group_target_date()' to update the
1060 // target date with minimal disturbances of relationships
1061 // between dependencies and superiors within a group of DIL
1062 // entries.)
1063         // modify dilid target dates
1064         Detailed_Items_List dilist;
1065         if (!modify_DIL_entry_target_date(dilid,tdate,dilist)) return false;
1066         // place new data and copy rest
1067 #ifdef VERBOSEDEBUG
1068         PLL_LOOP_FORWARD(DIL_entry,dilist.list.head(),1) {
1069                 EOUT << e->chars();
1070                 if (e->Projects(0)) EOUT << '\t' << e->Projects(0)->targetdate();
1071                 EOUT << '\n';
1072         }
1073 #endif
1074 #ifdef DEBUG
1075         bool res = dilist.Write_to_File();
1076         if (res) EOUT << "Modified DIL entry target date and stored to DIL ID file\n";
1077         return res;
1078 #else
1079         return dilist.Write_to_File();
1080 #endif
1081 }
bool modify_DIL_entry_target_date (DIL_ID dilid, time_t tdate, Detailed_Items_List & dilist)
Definition at line 976 of file diladmin.cc.
976                                                                                             {
977 // modify the target date of dilid in all self- or superior-
978 // references (dilid can be initialized from a String)
979 // Target dates are modified locally, without regard to target
980 // dates of superiors. If no target date was previously given,
981 // a set of parameters is created. The target date -1 indicates
982 // that target dates should be set to "?", i.e. unspecified.
983 // If dilist is empty, Get_All_DIL_ID_File_Parameters() is called.
984 // Modifications are made only if tdate differs from Target_Date().
985 // (Note: Use `modify_DIL_group_target_date()' to update the
986 // target date with minimal disturbances of relationships
987 // between dependencies and superiors within a group of DIL
988 // entries.)
989 // *** perhaps there should be a way to `force' modification if
990 //     it is used to ensure that the target date is local
991         // get DIL parameter sets
992         int entrynum;
993 #ifdef DEBUGTIER1
994         VOUT << "dil2al: [DEBUGTIER1] Modifying for DIL#" << dilid.chars() << " to tdate=" << tdate << " (" << time_stamp("%Y%m%d%H%M",tdate) << ")\n";
995 #endif
996         if (!dilist.list.head()) entrynum=dilist.Get_All_DIL_ID_File_Parameters();
997         else entrynum=dilist.list.length();
998         if (entrynum<=0) {
999                 EOUT << "No DIL entries found in " << idfile << " in modify_DIL_entry_target_date(), continuing as is\n";
1000                 return false;
1001         }
1002 #ifdef DEBUGTIER2
1003         VOUT << "dil2al: [DEBUGTIER2] Modification progress: 1";
1004 #endif
1005         // get first entry in list
1006         DIL_entry * de = dilist.list.head();
1007         // if (!de) return false; // should never happen when entrynum>0
1008         DIL_entry * did = de->elbyid(dilid);
1009         if (!did) {
1010                 EOUT << "DIL entry " << dilid << " not found in " << idfile << " in modify_DIL_entry_target_date(), continuing as is\n";
1011                 return false;
1012         }
1013 #ifdef DEBUGTIER2
1014         VOUT << ", 2";
1015 #endif
1016         if (did->Target_Date()!=tdate) { // modify only if different
1017                 if (!did->parameters) {
1018                         EOUT << "DIL entry " << dilid << " parameters not found in " << idfile << " in modify_DIL_entry_target_date(), continuing as is\n";
1019                         return false;
1020                 }
1021 #ifdef DEBUGTIER2
1022         VOUT << ", 3\n";
1023 #endif
1024                 // modify dilid target dates
1025                 if (did->Projects(0)) PLL_LOOP_FORWARD(DIL_AL_List,did->Projects(0),1) {
1026 #ifdef DEBUGTIER2
1027                         VOUT << "e->targetdate = tdate\n";
1028 #endif
1029                         if (!e->set_targetdate(tdate)) VOUT << "Unable to modify FIXED target date of ref.#" << dilid << "->#" << e->al.title << '\n';
1030                 } else if (tdate>=0) { // create self-reference for specified target date
1031                         // *** Modify this if the data format changes
1032 #ifdef DEBUGTIER2
1033                         VOUT << "did->parameters->project_append\n";
1034 #endif
1035                         did->parameters->project_append(idfile+String('#')+did->chars(),did->chars(),DILSUPS_REL_UNSPECIFIED,DILSUPS_UNB_UNSPECIFIED,DILSUPS_BND_UNSPECIFIED,tdate,0,DILSUPS_URG_UNSPECIFIED,DILSUPS_PRI_UNSPECIFIED);
1036                 }
1037 #ifdef DEBUGTIER1
1038                 VOUT << "dil2al: [DEBUGTIER1] Modification performed\n";
1039 #endif
1040         }
1041 #ifdef DEBUGTIER2
1042         else VOUT << ", target date already correct\n";
1043 #endif
1044 #ifdef DEBUG
1045         EOUT << "Modified DIL entry target date\n";
1046 #endif
1047         return true;
1048 }
bool modify_DIL_group_target_dates (Detailed_Items_List & dilgroup, bool minfragmentation = true)
Definition at line 1083 of file diladmin.cc.
References DIL_AL_List::al, DIL_ID::chars(), DIL_Superiors, DILSUPS_BND_UNSPECIFIED, DILSUPS_PRI_UNSPECIFIED, DILSUPS_REL_UNSPECIFIED, DILSUPS_UNB_UNSPECIFIED, DILSUPS_URG_UNSPECIFIED, PLLRoot< DIL_entry >::el(), DIL_entry::elbyid(), EOUT, Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), PLLRoot< DIL_entry >::head(), PLLRoot< DIL_entry >::length(), Detailed_Items_List::list, DIL_entry::Local_Target_Date(), modify_DIL_entry_target_date(), DIL_entry::parameters, PLL_LOOP_FORWARD, PLL_LOOP_FORWARD_NESTED, DIL_entry_parameters::project_append(), DIL_entry::Projects(), res, DIL_AL_List::set_targetdate(), Detailed_Items_List::Sort_by_Target_Date(), DIL_entry::Target_Date(), time_stamp(), filetitle_t::title, VOUT, and Detailed_Items_List::Write_to_File().
Referenced by modify_DIL_group_target_dates_cmd().
1083                                                                                                  {
1084 // Adjust the target dates of DIL entries listed in dilgroup,
1085 // utilizing propagation rules to minimize the number of
1086 // locally specified target dates where superiors can be
1087 // modified and are members of the group. Desired target dates
1088 // are specified in dilgroup.list[i]->Projects(0)->_targetdate,
1089 // so that they can be obtained through dilgroup.list[i]->Target_Date().
1090 // A target date is not changed if it is the same as the
1091 // entry's current Target_Date() or if -2 was specified.
1092 // A target date specification of -1 implies that it will be
1093 // set to `DILSUPS_TD_UNSPECIFIED'.
1094 #ifdef DEBUG_REPORT_DEVIATIONS
1095         int tdmodifdeviations = 0;
1096 #endif
1097         Detailed_Items_List dilist; DIL_entry * de, * did; time_t tdate;
1098 #ifdef DEBUGTIER2
1099         time_t * oldtargetdate;
1100         if (!dilist.list.head()) dilist.Get_All_DIL_ID_File_Parameters();
1101         oldtargetdate = new time_t[dilist.list.length()];
1102         for (int i=0; i<dilist.list.length(); i++) oldtargetdate[i] = dilist.list.el(i)->Local_Target_Date(0);
1103 #endif
1104         if (minfragmentation) { // apply minimization rules
1105 #ifdef DEBUGTIER2
1106         VOUT << "dil2al: [DEBUGTIER2] Applying rules to minimize fragmentation\n";
1107 #endif
1108                 int entrynum=dilist.Get_All_DIL_ID_File_Parameters();
1109                 if (entrynum<=0) {
1110                         EOUT << "No DIL entries found in " << idfile << " in modify_DIL_group_target_dates(), continuing as is\n";
1111                         return false;
1112                 }
1113                 DIL_entry * de = dilist.list.head();
1114                 // sort dilgroup in reverse order of desired target dates
1115                 // - thus superiors with the latest target date are updated first (minimizes insulations)
1116                 DIL_entry ** e = dilgroup.Sort_by_Target_Date(); // traverse in reverse order, highest to lowest
1117                 #define MODIFY_DIL_GROUP_TARGET_DATES_RETURN_WITH_CLEANUP(res) delete[] e; return res
1118                 for (int i = dilgroup.list.length()-1; i>=0; i--) if ((tdate=e[i]->Local_Target_Date(0))>=-1) { // iterate through dilgroup members
1119                         did = de->elbyid(*(e[i]));
1120                         if (!did) {
1121                                 EOUT << "DIL entry " << e[i]->chars() << " not found in " << idfile << " in modify_DIL_group_target_dates(), continuing as is\n";
1122                                 MODIFY_DIL_GROUP_TARGET_DATES_RETURN_WITH_CLEANUP(false);
1123                         }
1124                         if (did->Projects(0)) PLL_LOOP_FORWARD_NESTED(DIL_Superiors,did->Projects(0),1,pe) { // iterate through corresponding dilist member superiors
1125                                 // Note: Do this even if did->Target_Date()==tdate to insure that
1126                                 //       did->Target_Date()==tdate will also be true after the
1127                                 //       target dates of superiors may have been modified.
1128                                 // *** can set local target date if pe refers to self
1129                                 //     once superior references are pointer parameters
1130                                 // set `local' target date specifications to desired target date
1131                                 if (pe->targetdate()>=0) { 
1132                                         if (!pe->set_targetdate(tdate)) VOUT << "Unable to modify FIXED target date of ref.#" << e[i]->chars() << "->#" << pe->al.title << '\n';
1133                                 } else if (tdate>=0) {
1134                                         if (pe->IsSelfReference()) {
1135                                                 EOUT << "dil2al: Warning - Correcting self-reference without local target date in modify_DIL_group_target_dates\n()";
1136                                                 if (!pe->set_targetdate(tdate)) VOUT << "Unable to modify FIXED target date of ref.#" << e[i]->chars() << "->#" << pe->al.title << '\n';
1137                                         } else {
1138                                                 DIL_ID peid(pe->al.title);
1139                                                 DIL_entry * peg = dilgroup.list.head()->elbyid(peid); // can't use Superiorbyid() here, since getting in dilgroup
1140                                                 time_t petdate = -1;
1141                                                 if (peg) petdate = peg->Local_Target_Date(0); // to insure that code -1 is detected
1142                                                 DIL_entry * sup = pe->Superiorbyid();
1143                                                 if (!sup) {
1144                                                         EOUT << "dil2al: DIL entry superior with ID #" << pe->al.title << " not found in modify_DIL_group_target_dates(), continuing as is\n";
1145                                                         continue;
1146                                                 }
1147                                                 // if superior pe of e is in dilgroup with same desired TD
1148                                                 // then pe will take care of update (beware of loops)
1149                                                 if (petdate==tdate) continue;
1150                                                 // if pe->Target_Date() is earlier than desired
1151                                                 // then set desired locally (don't alter superior, since
1152                                                 // that could affect other dependencies of that superior)
1153                                                 if (sup->Target_Date()<tdate) { // insulate from superior's target date
1154                                                         if (!pe->set_targetdate(tdate)) VOUT << "Unable to modify FIXED target date of ref.#" << e[i]->chars() << "->#" << pe->al.title << '\n';
1155                                                 } else {
1156                                                         // if pe in dilgroup and pe desired < e desired
1157                                                         // and relevance not 1.0 or unspecified then set locally
1158                                                         // else warn incompatibility for fully relevant dependency
1159                                                         if ((peg) && (petdate<tdate)) {
1160                                                                 if ((pe->relevance<1.0) && (pe->relevance!=DILSUPS_REL_UNSPECIFIED)) {
1161                                                                         // set locally, because superior will be set to earlier
1162                                                                         if (!pe->set_targetdate(tdate)) VOUT << "Unable to modify FIXED target date of ref.#" << e[i]->chars() << "->#" << pe->al.title << '\n';
1163                                                                         continue;
1164                                                                 } else EOUT << "dil2al: Warning - earlier target date requested for superior with ID #" << pe->al.title << " than for dependency with ID # " << e[i]->chars() << " in modify_DIL_group_target_dates(), continuing\n";
1165                                                         }
1166                                                         // if pe is last superior and Target_Date() is still
1167                                                         // > desired then set locally
1168                                                         if (!pe->Next()) if (did->Target_Date()>tdate) {
1169                                                                 if (!pe->set_targetdate(tdate)) VOUT << "Unable to modify FIXED target date of ref.#" << e[i]->chars() << "->#" << pe->al.title << '\n';
1170                                                         }
1171                                                 }
1172                                         }
1173                                 }
1174                         } else if (tdate>=0) { // unless setting to unspecified, make a self-reference
1175                                 // *** Modify this if the data format changes
1176                                 if (!did->parameters) did->parameters = new DIL_entry_parameters(*did);
1177                                 did->parameters->project_append(idfile+'#'+did->chars(),did->chars(),DILSUPS_REL_UNSPECIFIED,DILSUPS_UNB_UNSPECIFIED,DILSUPS_BND_UNSPECIFIED,tdate,0,DILSUPS_URG_UNSPECIFIED,DILSUPS_PRI_UNSPECIFIED);
1178                         }
1179                 }
1180                 // Double-check to insure that target dates are detected as requested
1181                 for (int i = dilgroup.list.length()-1; i>=0; i--) if ((tdate=e[i]->Local_Target_Date(0))>=0) { // iterate through dilgroup members
1182                         did = de->elbyid(*(e[i]));
1183                         if (did->Target_Date()!=tdate) {
1184 #ifdef DEBUG_REPORT_DEVIATIONS
1185                                 tdmodifdeviations++; // useful when testing functional or rule-based approach above
1186 #endif
1187                                 if (did->Projects(0)) {
1188                                         if (did->Target_Date()>tdate) {
1189                                                 if (!did->Projects(0)->set_targetdate(tdate)) VOUT << "Unable to modify FIXED target date of ref.#" << e[i]->chars() << "->#" << did->Projects(0)->al.title << '\n';
1190                                                 else VOUT << "Forcing target date adjustment at DIL entry #" << did->chars() << " superior reference " << did->Projects(0)->al.title << '\n';
1191                                         } else PLL_LOOP_FORWARD_NESTED(DIL_Superiors,did->Projects(0),1,pe) { // iterate through corresponding dilist member superiors
1192                                                 if (pe->targetdate() < tdate) {
1193                                                         if (!pe->set_targetdate(tdate)) VOUT << "Unable to modify FIXED target date of ref.#" << e[i]->chars() << "->#" << pe->al.title << '\n';
1194                                                         else VOUT << "Forcing target date adjustment at DIL entry #" << did->chars() << " superior reference " << pe->al.title << '\n';
1195                                                 }
1196                                         }
1197                                 }
1198                         }
1199                 }
1200                 // Final test of detected target dates achieved
1201                 for (int i = dilgroup.list.length()-1; i>=0; i--) if ((tdate=e[i]->Local_Target_Date(0))>=0) // iterate through dilgroup members
1202                         if (de->elbyid(*(e[i]))->Target_Date()!=tdate) EOUT << "dil2al: Unable to set target date for DIL#" << did->chars() << " in modify_DIL_group_target_dates(), continuing as is\n";
1203                 delete[] e;
1204         } else PLL_LOOP_FORWARD(DIL_entry,dilgroup.list.head(),1) { // modify target dates directly
1205                 tdate = e->Local_Target_Date(0); // not using Target_Date() to insure -1 and -2 codes are detected
1206                 if (tdate>=-1) if (!modify_DIL_entry_target_date(*e,tdate,dilist)) return false;
1207         }
1208 #ifdef DEBUGTIER2
1209         int i = 0;
1210         PLL_LOOP_FORWARD(DIL_entry,dilist.list.head(),1) {
1211                 if (e->Local_Target_Date(0)!=oldtargetdate[i]) cout << "dil2al: [DEBUGTIER2] Changed DIL entry #" << e->chars() << ", old=" << oldtargetdate[i] << " (" << time_stamp("%Y%m%d%H%M",oldtargetdate[i]) << "), new=" << e->Local_Target_Date(0) << " (" << time_stamp("%Y%m%d%H%M",e->Local_Target_Date(0)) << ") TD=" << time_stamp("%Y%m%d%H%M",e->Target_Date()) << '\n';
1212                 i++;
1213         }
1214         delete[] oldtargetdate;
1215 #endif
1216 #ifdef DEBUG_REPORT_DEVIATIONS
1217         EOUT << "dil2al: [DEBUG_REPORT_DEVIATIONS] Target Date Modification Deviations = " << tdmodifdeviations << '\n';
1218 #endif
1219 #ifdef DEBUG
1220         bool res = dilist.Write_to_File();
1221         if (res) EOUT << "Modified DIL group target dates and stored to DIL ID file\n";
1222         return res;
1223 #else
1224         return dilist.Write_to_File();
1225 #endif
1226 /*
1227 An alternative approach
1228 -----------------------
1229 Note that the concept below needs to be worked out for the case of muiltiple
1230 superiors at each level, i.e. when tracking through the superiors structure,
1231 all path possibilities must be marked/remembered, instead of just using pe as
1232 a roadblock. Due to this, and the depth-search itself, it is unclear if this
1233 functional approach is more or less efficient than the rule-based one. It also
1234 remains to be seen if this approach follows all the same rules as the rule-based
1235 approach.
1236 
1237 From furthest TD to nearest TD in list of DIL entries:
1238 
1239 isgroupsuperior()
1240         if (!pe) return false;
1241         e = dilgroup.list.head()->elbyid(*pe);
1242         if (!e) return false;
1243         if (e->Target_Date()!=tdate) return false;
1244         return true;
1245 
1246 while Target_Date()!=tdate
1247         pe = NULL
1248         while (!isgroupsuperior(pe)) pe = Target_Date_Specified(pe);
1249         if (pe->Projects(0)) pe->Projects(0)->_targetdate = tdate;
1250         else pe->parameters->add_project(...,tdate,...);
1251 */
1252 }
bool modify_DIL_group_target_dates_cmd (bool minfragmentation, StringList * qlist = NULL)
Definition at line 1254 of file diladmin.cc.
References ANSI_BOLD_OFF, ANSI_BOLD_ON, ANSI_UNDERLINE_OFF, ANSI_UNDERLINE_ON, String::at(), String::before(), DIL_ID::chars(), DILSUPS_BND_UNSPECIFIED, DILSUPS_PRI_UNSPECIFIED, DILSUPS_REL_UNSPECIFIED, DILSUPS_UNB_UNSPECIFIED, DILSUPS_URG_UNSPECIFIED, DIN, PLLRoot< DIL_entry >::el(), String::gsub(), String::index(), String::length(), StringList::length(), PLLRoot< DIL_entry >::link_before(), Detailed_Items_List::list, DIL_entry::Local_Target_Date(), modify_DIL_group_target_dates(), DIL_entry::parameters, DIL_entry_parameters::project_append(), read_data_from_stream(), RX_Search_Safe(), BigRegex::sublen(), BigRegex::subpos(), time_stamp(), time_stamp_time(), and VOUT.
Referenced by Detect_Form_Input(), and Modify_Element().
1254                                                                                          {
1255 // Command line interface to modify_DIL_group_target_dates().
1256 // Reads pairs of DIL entry IDs and desired target dates (with
1257 // optional -2 code to indicate no target date modification, and
1258 // -1 to unspecify local target date parameters).
1259 // Data is read from the DIN stream.
1260 // If qlist is not NULL then HTML form data is obtained from qlist.
1261         const BigRegex td("^TD\\([0-9]+[.][0-9]+\\)=");
1262         const BigRegex tdchkbx("^TDCHKBX\\([0-9]+[.][0-9]+\\)=");
1263         const BigRegex pairsep("[ \t,:;]+");
1264         const BigRegex nonnumerals("[^-0-9]");
1265         String modifdata;
1266         if (qlist) { // HTML form interface
1267                 StringList exclude; int excludenum = 0;
1268                 int qnum = qlist->length()-1; // *** empty element at end of StringList
1269                 for (int i = 0; i<qnum; i++) {
1270                 // *** Beware: This code assumes that DIL entry IDs do not
1271                 //     occur as subsets of other DIL entry IDs, i.e. it
1272                 //     assumes that a move to IDs with more digits would imply
1273                 //     prepending older IDs with 0s. This could of course be
1274                 //     handled by a preprocessing loop.
1275 #ifdef DEBUGTIER2
1276                         cout << '$' << (*qlist)[i] << '\n';
1277 #endif
1278                         if ((*qlist)[i].contains("TDupdate=")) {
1279                                 if ((*qlist)[i].after('=')=="direct") minfragmentation = false;
1280                                 else minfragmentation = true;
1281                         } else if ((*qlist)[i].contains(td)) {
1282                                 modifdata += (*qlist)[i].at(td.subpos(1),td.sublen(1)) + ' ';
1283                                 String tdstr = (*qlist)[i].after('='); if (tdstr.length()==0) tdstr = "-2";
1284                                 modifdata += tdstr + '\n';
1285                         } else if ((*qlist)[i].contains(tdchkbx)) {
1286                                 String chkbxid = (*qlist)[i].at(tdchkbx.subpos(1),tdchkbx.sublen(1));
1287                                 String tdstr = (*qlist)[i].after('=');
1288                                 if (tdstr=="noupdate") { // set corresponding desired target date to code -2
1289                                         exclude[excludenum] = chkbxid;
1290                                         excludenum++;
1291                                 }
1292                         }
1293                 }
1294                 for (int i = 0; i<excludenum; i++) modifdata.gsub(BigRegex(RX_Search_Safe(exclude[i])+" [-0-9]*"),exclude[i]+" -2");
1295         } else {
1296                 if (useansi) VOUT << ANSI_BOLD_ON;
1297                 VOUT << "Enter group of DIL entries to consider for target date modification.\n";
1298                 if (useansi) VOUT << ANSI_BOLD_OFF;
1299                 VOUT << "Rows of DIL entry ID and desired target date pairs.\n\
1300 Special desired target date codes:\n\
1301 -1 = set to `unspecified', -2 = no desired target date (but modifiable).\n\
1302 Separate pairs with any number of spaces, tabs, commas, colons or semicolons.\n\
1303 End of File (Ctrl+D) or a line stating `EOF' completes data entry.\n\n";
1304                 if (useansi) VOUT << ANSI_UNDERLINE_ON;
1305                 VOUT << "DIL entry ID#\tdesired target date\n";
1306                 if (useansi) VOUT << ANSI_UNDERLINE_OFF;
1307                 read_data_from_stream(DIN,modifdata,"EOF");
1308         }
1309         StringList modiflist(modifdata,'\n');
1310         int groupsize = modiflist.length()-1; // *** last entry empty when initializing from string with separator
1311         Detailed_Items_List dilgroup; DIL_entry * de; String did; time_t tdate;
1312 #ifdef DEBUGTIER2
1313         cout << "Content-Type: text/plain\n\ndil2al: [DEBUGTIER2]\n";
1314         for (int j=0; j<groupsize; j++) {
1315                 String & s = modiflist[j];
1316                 cout << s << '\n';
1317         }
1318         cout << "+++\n";
1319 #endif
1320         for (int i=0; i<groupsize; i++) {
1321                 did = modiflist[i].after(pairsep); if (did.index(nonnumerals)>=0) did = did.before(nonnumerals);
1322                 tdate = time_stamp_time(did);
1323                 did = modiflist[i].before(pairsep);
1324                 de = new DIL_entry(dilgroup,did);
1325                 de->parameters = new DIL_entry_parameters(*de);
1326                 de->parameters->project_append('#'+did,did,DILSUPS_REL_UNSPECIFIED,DILSUPS_UNB_UNSPECIFIED,DILSUPS_BND_UNSPECIFIED,tdate,0,DILSUPS_URG_UNSPECIFIED,DILSUPS_PRI_UNSPECIFIED);
1327                 dilgroup.list.link_before(de);
1328         }
1329 #ifdef DEBUGTIER1
1330         if (minfragmentation) cout << "dil2al: [DEBUGTIER1] Minimum fragmentation\n"; else cout << "dil2al: [DEBUGTIER1] Direct\n";
1331 #endif
1332 #ifdef DEBUGTIER2
1333         for (int i=0; i<groupsize; i++) {
1334                 cout << "dil2al: [DEBUGTIER2] " << dilgroup.list.el(i)->chars() << '\t';
1335                 if (dilgroup.list.el(i)->Local_Target_Date(0)<0) cout << dilgroup.list.el(i)->Local_Target_Date(0) << '\n';
1336                 else cout << time_stamp("%Y%m%d%H%M",dilgroup.list.el(i)->Local_Target_Date(0)) << '\n';
1337         }
1338 #endif
1339         return modify_DIL_group_target_dates(dilgroup,minfragmentation);
1340 }
bool modify_element_through_FORM_interface (StringList * qlist = NULL)
Definition at line 776 of file diladmin.cc.
References absurl(), DIL_ID::chars(), StringList::contains(), DIL2AL_CONDITIONAL_ERROR_RETURN, DIL_Superiors, DIL_entry::elbyid(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), get_double(), StringList::get_Next(), String::gsub(), PLLRoot< DIL_entry >::head(), StringList::length(), PLLRoot< PLLType >::link_before(), Detailed_Items_List::list, StringList::List_Index(), modify_element_through_FORM_interface_DIL_Superiors(), DIL_entry::Projects(), read_file_into_String(), DIL_ID::str(), update_DIL_entry_elements(), update_DIL_entry_parameter_elements(), DIL_ID::valid(), and VOUT.
Referenced by Detect_Form_Input().
776                                                                       {
777 // receives information about element modifications in a DIL entry through
778 // an HTML FORM interface. The DIL entry is given by a DILID variable in qlist.
779   if (!qlist) return false;
780   // for (int i = 0; i<qlist->length(); i++) VOUT << (*qlist)[i] << '\n';
781   int dilididx = qlist->contains("DILID");
782   if (dilididx<0) return false;
783   DIL_ID dilid((*qlist)[dilididx].after('='));
784   if (!dilid.valid()) return false;
785   // content modifications
786   double valuation = 0.0, completion = 0.0, required = 0.0;
787   bool updateval = false, updatecomp = false, updatereq = false;
788   String valstr;
789   if ((dilididx=qlist->contains("valuation="))>=0) valuation=get_double((*qlist)[dilididx].after('='),valuation,&updateval); // modify valuation
790   if ((dilididx=qlist->contains("completion="))>=0) completion=get_double((*qlist)[dilididx].after('='),completion,&updatecomp); // modify completion ratio
791   if ((dilididx=qlist->contains("required="))>=0) required=get_double((*qlist)[dilididx].after('='),required,&updatereq); // modify time required
792   if (updateval || updatecomp || updatereq) {
793     if (!update_DIL_entry_elements(dilid.chars(),valuation,updateval,completion,updatecomp,required,updatereq)) {
794       VOUT << "Unable to modify content elements of DIL entry\n";
795       return false;
796     }
797     return true;
798   }
799   // parameters modifications
800   Detailed_Items_List dilist; int entrynum;
801   DIL2AL_CONDITIONAL_ERROR_RETURN((entrynum=dilist.Get_All_DIL_ID_File_Parameters())<=0,"No DIL entries found in "+idfile+" in modify_element_through_FORM_interface()\n");
802   DIL_entry * de;
803   DIL2AL_CONDITIONAL_ERROR_RETURN(!(de = dilist.list.head()->elbyid(dilid)),"The DIL entry "+dilid.str()+" does not appear to exist in modify_element_through_FORM_interface()\n");
804   PLLRoot<DIL_Superiors> addsups;
805   // detect add
806   if ((dilididx=qlist->contains("dilrefsups="))>=0) { // add superiors specified in dilref
807     String dilrefsupstr;
808     if (!read_file_into_String(dilref,dilrefsupstr,false)) VOUT << "No superior DIL entries in " << dilref << " for possible addition.\n";
809     else {
810       dilrefsupstr.gsub(BigRegex("Current[^f]*file..."),"");
811       StringList dilrefsups(dilrefsupstr,'\n'); String supid;
812       for (int i=0; i<dilrefsups.length(); i++) {
813         supid = dilrefsups[i].after('#');
814         DIL_ID did(supid);
815         if (did.valid()) {
816           DIL_entry * sup = dilist.list.head()->elbyid(did);
817           if (sup) {
818             DIL_Superiors * dilsup = new DIL_Superiors(*de);
819             dilsup->al.title = supid;
820             dilsup->al.file = absurl(idfile,'#'+supid);
821             modify_element_through_FORM_interface_DIL_Superiors(dilididx,qlist,supid,dilsup);
822             addsups.link_before(dilsup);
823             continue;
824           }
825         }
826         VOUT << supid << "does not appear to be a valid reference!\n";
827       }
828     }
829   }
830   // detect remove
831   StringList removesups; int removesupsnum = 0;
832   for (StringList * qlistptr = qlist->List_Index(qlist->contains("suprm=")); (qlistptr); ) {
833     removesups[removesupsnum] = (*qlistptr)[0].after('=');
834     if (removesups[removesupsnum].contains('=')) removesups[removesupsnum] = removesups[removesupsnum].before('=');
835     removesupsnum++;
836     if (!(qlistptr=qlistptr->get_Next())) break;
837     qlistptr = qlistptr->List_Index(qlistptr->contains("suprm="));
838   }
839   // detect modify
840   for (DIL_Superiors * dilsup = de->Projects(0); dilsup; dilsup = dilsup->Next())
841     modify_element_through_FORM_interface_DIL_Superiors(dilididx,qlist,dilsup->al.title,dilsup);
842   if (!update_DIL_entry_parameter_elements(dilist,dilid,addsups,&removesups,removesupsnum)) {
843     VOUT << "Unable to modify parameter elements of DIL entry\n";
844     return false;
845   }
846   return true;
847 }
bool pattern_in_line (const char * pattern, char * lbuf)
Definition at line 2164 of file utilities.cc.
References EOUT.
Referenced by add_new_to_DIL(), get_active_DIL_IDs(), Topical_DIL_Files::Refresh(), and Set_Parameter().
2164                                                         {
2165         regex_t re;
2166         int mres;
2167         if (regcomp(&re,pattern, REG_EXTENDED|REG_NOSUB) != 0) {
2168                 EOUT << "dil2al: Unable to compile regular expression in pattern_in_line()\n";
2169                 return false;
2170         }
2171         mres = regexec(&re,lbuf, (size_t) 0, NULL, 0);
2172         regfree(&re);
2173         if ((mres != 0) && (mres != REG_NOMATCH)) {
2174                 EOUT << "dil2al: Internal error while matching in pattern_in_line()\n";
2175                 return false;
2176         }
2177         return (mres==0);
2178 }
int post_process_note (String notedst, String & notestr, String & notedststr, int insertindex, bool isnew)
Definition at line 66 of file note.cc.
References String::at(), String::length(), and write_file_from_String().
Referenced by process_note_CC(), process_note_generic(), process_note_HTML(), and process_note_TeX().
66                                                                                                           {
67         // insert note into notedst
68         if (insertindex>=0) {
69                 String c = notedststr.at(insertindex,1);
70                 notedststr.at(insertindex,1) = notestr+c;
71         } else {
72                 insertindex = notedststr.length();
73                 notedststr += notestr;
74         }
75         // store and backup
76         if (!write_file_from_String(notedst,notedststr,"Note destination",isnew)) return -1;
77         return insertindex;
78 }
int pre_process_note (String notefile, String notedst, String typestr, String & notestr, String & notedststr, bool & isnew)
Definition at line 53 of file note.cc.
References process_HTML(), read_file_into_String(), and VOUT.
Referenced by process_note_CC(), process_note_generic(), process_note_HTML(), process_note_TeX(), and process_note_TL().
53                                                                                                                            {
54         if (!read_file_into_String(notefile,notestr)) return -1;
55         if (notestr=="") { // if note is empty, don't do anything, but return true
56                 if (verbose) VOUT << "Note is empty, no change\n";
57                 return 0;
58         }
59         if (verbose) VOUT << "Processing destination file as " << typestr << '\n';
60         process_HTML(notestr);
61         // read note destination into memory
62         if (!read_file_into_String(isnew,notedst,notedststr)) return -1;
63         return 1;
64 }
bool prepare_temporary_file (String tmpfile, String initstr)
Definition at line 1997 of file utilities.cc.
References EOUT.
Referenced by Lock_File(), and make_note().
1997                                                             {
1998 // Can be used to create temporary files (e.g. the dilref or,
1999 // note or DIL entry stubs), and automatically back up the
2000 // previous file if it exists. The stub is filled with the
2001 // content of initstr and closed.
2002         if (rename(tmpfile,tmpfile+".bak")<0) if (errno!=ENOENT) {
2003                 EOUT << "dil2al: Unable to rename " << tmpfile << " to " << tmpfile+".bak in prepare_temporary_file()\n";
2004                 return false;
2005         }
2006         ofstream ntf(tmpfile);
2007         if (!ntf) {
2008                 EOUT << "dil2al: Unable to create temporary file " << tmpfile << " in prepare_temporary_file()\n";
2009                 return false;
2010         }
2011         if (initstr!="") ntf << initstr;
2012         ntf.close();
2013         return true;
2014 }
void process_HTML (String & notestr)
Definition at line 6 of file note.cc.
References String::after(), String::at(), String::before(), String::contains(), EOUT, String::gsub(), String::index(), and String::length().
Referenced by pre_process_note(), and process_note_TL().
6                                     {
7 // Process note shorthand codes to HTML and fill in @tags@
8         // line breaks
9         notestr.gsub("\n","<BR>\n");
10         // paragraphs
11         notestr.gsub(BigRegex("<BR>\n\\(<BR>\n\\)+"),"\n<P>\n");
12         // lists with `-' or `*' item indicators
13         notestr.gsub(BigRegex("^[       ]*-[    ]+"),"<LI>");
14         int lstart, lend;
15         while ((lstart=notestr.index(BigRegex("^[       ]*[*][  ]+")))>=0) {
16                 notestr.at(BigRegex("^[         ]*[*][  ]+"),lstart)="<UL>\n<LI>";
17                 while ((lend=notestr.index("\n",lstart))>=0) {
18                         lstart = lend+1;
19                         if (notestr.contains(BigRegex("\n\\([   ]+[^    ]+\\|[  ]*[*][  ]+\\)"),lend)) {
20                                 notestr.at(BigRegex("\n[        ]*[*][  ]+"),lend) = "\n<LI>";
21                         } else break;
22                 }
23                 if (lend<0) { lend = notestr.length(); notestr += "\n"; }
24                 notestr.at("\n",lend) = "\n</UL>\n";
25         }
26         // note that HTML references are already correct
27         // tag definitions
28         // NOVELTY tags
29         int novcount = 0;
30         lstart = -1;
31         while ((lstart=notestr.index("@NOV@",lstart+1))>=0) {
32                 if ((lend=notestr.index("@/NOV@",lstart))>=0) {
33                         String tmp1,tmp2;
34                         novcount++;
35                         tmp1 = notestr.at(lstart+5,lend-(lstart+4));
36                         tmp2 = notestr.after(lend+6);
37                         notestr = notestr.before(lstart) + "<A NAME=\"NOVELTY-"+((curtime+'-')+dec(novcount))+"\">[<B>N</B>]</A> "
38                                         + tmp1 + "<!-- @NOVELTY-"+((curtime+'-')+dec(novcount))+"@ -->" + tmp2;
39                 } else EOUT << "dil2al: @NOV@ without matching @/NOV@ in process_HTML(), continuing as is\n";
40         }
41 //*** add code here to replace @tags@ and tags defined in the configuration file
42         // clean up
43         notestr.gsub("<BR><BR>","<BR>");
44         notestr.gsub("<BR><P>","<P>");
45         notestr.gsub("<P><BR>","<P>");
46         notestr.gsub("<BR>\n<P>","\n<P>");
47         notestr.gsub("<P>\n<P>","<P>");
48         notestr.gsub("<BR>\n<UL>","\n<UL>");
49         notestr.gsub("<BR>\n<LI>","\n<LI>");
50         notestr.gsub("<BR>\n</UL>","\n</UL>");
51 }
bool process_note (String notefile, String notedst)
Definition at line 330 of file note.cc.
References EOUT, get_TL_head(), String::gsub(), String::matches(), process_note_CC(), process_note_generic(), process_note_HTML(), process_note_TeX(), process_note_TL(), res, and UNIE_ASK.
Referenced by make_note().
330                                                    {
331         const int LLEN = 10240;
332         char lbuf[LLEN];
333         // determine destination file type
334         int filetype = 0; // generic type
335         if (notedst==tasklog) {
336                 filetype = 1; // Task Log type
337                 if ((notedst = get_TL_head())=="") return false;
338         } else if (notedst.matches(BigRegex(".*[.][Hh][Tt][Mm][Ll]?\\([---_.].*\\)?"))) filetype = 2; // HTML type
339         else if (notedst.matches(BigRegex(".*[.][Tt][Ee][Xx]\\([---_.].*\\)?"))) filetype = 3; // TeX type
340         else if (notedst.matches(BigRegex(".*[.]\\([Cc][Cc]|[Hh][Hh]\\)\\([---_.].*\\)?"))) filetype = 4; // C++ type
341         else if (askprocesstype) {
342                 filetype = -1;
343                 while ((filetype<0) || (filetype>4)) {
344                         cout << "Destination file type (0=generic,1=Task Log,2=HTML,3=TeX,4=C++): ";
345                         cin.getline(lbuf,LLEN);
346                         String ftstr = lbuf;
347                         if (ftstr.matches(BRXint)) filetype = atoi((const char *) ftstr);
348                 }
349         }
350         // process and insert note in destination file
351         int res;
352         switch (filetype) {
353                 case 0: res=process_note_generic(notefile,notedst); break;
354                 case 1: res=process_note_TL(notefile,notedst); break;
355                 case 2: res=process_note_HTML(notefile,notedst); break;
356                 case 3: res=process_note_TeX(notefile,notedst); break;
357                 case 4: res=process_note_CC(notefile,notedst); break;
358                 default: {
359                                 EOUT << "dil2al: Unknown destination file type in process_note()\n";
360                                 return false;
361                         }
362         }
363         if (res<0) {
364                 EOUT << "dil2al: Unable to process destination file in process_note()\n";
365                 return false;
366         }
367         // update and open notedst in an editor
368         bool updateineditor = updatenoteineditor;
369         if (updateineditor==UNIE_ASK) {
370                 cout << "\nUpdate and open " << notedst << " in editor? (Y/n) ";
371                 cin.getline(lbuf,LLEN);
372                 updateineditor = (!((lbuf[0]=='n') || (lbuf[0]=='N')));
373         }
374         if (updateineditor) {
375                 String uniecmd = updatenoteineditorcmd;
376                 uniecmd.gsub("@res@",dec(res));
377                 if (filetype==1) notedst=tasklog; // revert to symbolic link in case new Task Log section was added
378                 uniecmd.gsub("@notedst@",notedst);
379                 if (system(uniecmd)<0) EOUT << "dil2al: Unable to update and open " << notedst << " in editor in process_note(), continuing\n";
380         }
381         return true;
382 }
int process_note_CC (String notefile, String notedst)
Definition at line 220 of file note.cc.
References String::after(), String::at(), String::before(), String::gsub(), String::index(), String::length(), post_process_note(), pre_process_note(), res, and VOUT.
Referenced by process_note().
220                                                      {
221         String notestr, notedststr; bool isnew; int res;
222         if ((res = pre_process_note(notefile,notedst,"C++",notestr,notedststr,isnew))<=0) return res;
223         // find a possible // <!-- @INSERT-AT:<tag>@ -->
224         int insertindex = -1;
225         String inserttag = notestr.at(BigRegex("[<]!--[         ]*@INSERT-AT:[^@]+@[    ]*--[>]"));
226         if (inserttag!="") {
227                 inserttag = inserttag.after("INSERT-AT:");
228                 inserttag = inserttag.before("@",-1);
229                 insertindex = notedststr.index(BigRegex("//[\n]*[<]!--[         ]*@"+inserttag+"@[      ]*--[>]"));
230         }
231         // find a possible // <!-- @INSERT-TL-NOTE@ -->
232         if (insertindex<0) insertindex = notedststr.index(BigRegex("//[\n]*[<]!--[      ]*@INSERT-TL-NOTE@[     ]*--[>]"));
233         if ((insertindex<0) && (verbose))  VOUT << "No specific insertion location in " << notedst << ", appending note to end\n";
234         // convert to C++
235         notestr.gsub(BigRegex("[<][Bb][Rr][     ]*[^>][>]\n?"),"\n"); // <BR>
236         notestr.gsub(BigRegex("\n?[<][Pp][      ]*[^>]*[>]\n?"),"\n\n"); // <P>
237         notestr.gsub(BigRegex("[<][Uu][Ll][     ]*[^>]*[>]"),""); // <UL>
238         notestr.gsub(BigRegex("[<]/[Uu][Ll][    ]*[^>]*[>]"),""); // </UL>
239         notestr.gsub(BigRegex("[<][Oo][Ll][     ]*[^>]*[>]"),""); // <OL>
240         notestr.gsub(BigRegex("[<]/[Oo][Ll][    ]*[^>]*[>]"),""); // </OL>
241         notestr.gsub(BigRegex("[<][Ll][Ii][     ]*[^>]*[>]"),"- "); // <LI>
242         // <A HREF="http://the-reference-url/">the-reference-text</A>
243         // <A NAME="the-reference-name-tag">the-reference-anchor</A>
244         int i = 0, j = 0, k;
245         while (i>=0) {
246                 i = notestr.index(BigRegex("[<][Aa][    ]+[^>]*\\([Hh][Rr][Ee][Ff]\\|[Nn][Aa][Mm][Ee]\\)[       ]*=[    ]*[^>]*[>].*[<]/[Aa][   ]*[^>]*[>]"),j);
247                 if (i>=0) {
248                         j = notestr.index(BigRegex("//[^\n]*"),i-notestr.length()); // check if already // commented
249                         if (j<0) {
250                                 j = notestr.index("/*",i-notestr.length());
251                                 if (j>=0) {
252                                         k = notestr.index("*/",i-notestr.length());
253                                         if (k>j) j = -1;
254                                 }
255                         }
256                         if (j<0) {
257                                 j = notestr.index(BigRegex("[<]/[Aa][   ]*[^>]*[>]"),i);
258                                 j = notestr.index(">",j);
259                                 String tmpstr = "/* "+notestr.at(i,(j-i)+1)+" */"+notestr.after(j);
260                                 notestr = notestr.before(i)+tmpstr;
261                                 //notestr.at(j,1) = "> */";
262                                 //notestr.at(i,1) = "/* <";
263                         }
264                 }
265         }
266         // other <...> tags
267         i = 0; j = 0;
268         while (i>=0) {
269                 i = notestr.index(BigRegex("[<][^>]*[>]"),j);
270                 if (i>=0) {
271                         j = notestr.index(BigRegex("//[^\n]*"),i-notestr.length()); // check if already // commented
272                         if (j<0) {
273                                 j = notestr.index("/*",i-notestr.length());
274                                 if (j>=0) {
275                                         k = notestr.index("*/",i-notestr.length());
276                                         if (k>j) j = -1;
277                                 }
278                         }
279                         if (j<0) { // convert tag to comment
280                                 j = notestr.index(">",i);
281                                 String tmpstr = "/* "+notestr.at(i,(j-i)+1)+" */"+notestr.after(j);
282                                 notestr = notestr.before(i)+tmpstr;
283                                 //notestr.at(j,1) = "> */";
284                                 //notestr.at(i,1) = "/* <";
285                         }
286                 }
287         }
288         notestr.gsub("&lt;","<"); // &lt;
289         notestr.gsub("&gt;",">"); // &gt;
290         notestr.gsub("&amp;","&"); // &amp;
291         notestr.gsub("&nbsp;"," "); // &nbsp;
292         // clean up
293         notestr.gsub(BigRegex("[        ]+\n"),"\n");
294         // insert note into notedst
295         return post_process_note(notedst,notestr,notedststr,insertindex,isnew);
296 }
int process_note_generic (String notefile, String notedst)
Definition at line 298 of file note.cc.
References String::after(), String::at(), String::before(), String::gsub(), String::index(), post_process_note(), pre_process_note(), res, and VOUT.
Referenced by process_note().
298                                                           {
299         String notestr, notedststr; bool isnew; int res;
300         if ((res = pre_process_note(notefile,notedst,"generic text",notestr,notedststr,isnew))<=0) return res;
301         // find a possible <!-- @INSERT-AT:<tag>@ -->
302         int insertindex = -1;
303         String inserttag = notestr.at(BigRegex("[<]!--[         ]*@INSERT-AT:[^@]+@[    ]*--[>]"));
304         if (inserttag!="") {
305                 inserttag = inserttag.after("INSERT-AT:");
306                 inserttag = inserttag.before("@",-1);
307                 insertindex = notedststr.index(BigRegex("[<]!--[        ]*@"+inserttag+"@[      ]*--[>]"));
308         }
309         // find a possible <!-- @INSERT-TL-NOTE@ -->
310         if (insertindex<0) insertindex = notedststr.index(BigRegex("[<]!--[     ]*@INSERT-TL-NOTE@[     ]*--[>]"));
311         if ((insertindex<0) && (verbose))  VOUT << "No specific insertion location in " << notedst << ", appending note to end\n";
312         // convert to generic text
313         notestr.gsub(BigRegex("[<][Bb][Rr][     ]*[^>][>]\n?"),"\n"); // <BR>
314         notestr.gsub(BigRegex("\n?[<][Pp][      ]*[^>]*[>]\n?"),"\n\n"); // <P>
315         notestr.gsub(BigRegex("[<][Uu][Ll][     ]*[^>]*[>]"),""); // <UL>
316         notestr.gsub(BigRegex("[<]/[Uu][Ll][    ]*[^>]*[>]"),""); // </UL>
317         notestr.gsub(BigRegex("[<][Oo][Ll][     ]*[^>]*[>]"),""); // <OL>
318         notestr.gsub(BigRegex("[<]/[Oo][Ll][    ]*[^>]*[>]"),""); // </OL>
319         notestr.gsub(BigRegex("[<][Ll][Ii][     ]*[^>]*[>]"),"- "); // <LI>
320         notestr.gsub("&lt;","<"); // &lt;
321         notestr.gsub("&gt;",">"); // &gt;
322         notestr.gsub("&amp;","&"); // &amp;
323         notestr.gsub("&nbsp;"," "); // &nbsp;
324         // clean up
325         notestr.gsub(BigRegex("[        ]+\n"),"\n");
326         // insert note into notedst
327         return post_process_note(notedst,notestr,notedststr,insertindex,isnew);
328 }
int process_note_HTML (String notefile, String notedst)
Definition at line 108 of file note.cc.
References String::after(), String::at(), String::before(), EOUT, String::index(), post_process_note(), pre_process_note(), and res.
Referenced by process_note().
108                                                        {
109         String notestr, notedststr; bool isnew; int res;
110         if ((res = pre_process_note(notefile,notedst,"HTML",notestr,notedststr,isnew))<=0) return res;
111         // find a possible <!-- @INSERT-AT:<tag>@ -->
112         int insertindex = -1;
113         String inserttag = notestr.at(BigRegex("[<]!--[         ]*@INSERT-AT:[^@]+@[    ]*--[>]"));
114         if (inserttag!="") {
115                 inserttag = inserttag.after("INSERT-AT:");
116                 inserttag = inserttag.before("@",-1);
117                 insertindex = notedststr.index(BigRegex("[<]!--[        ]*@"+inserttag+"@[      ]*--[>]"));
118         }
119         // find a possible <!-- @INSERT-TL-NOTE@ -->
120         if (insertindex<0) insertindex = notedststr.index(BigRegex("[<]!--[     ]*@INSERT-TL-NOTE@[     ]*--[>]"));
121         // find </BODY>
122         if (insertindex<0) insertindex = notedststr.index("</BODY>");
123         if (insertindex<0) EOUT << "dil2al: Note destination " << notedst << " missing </BODY> tag, continuing\n";
124         // insert note into notedst
125         return post_process_note(notedst,notestr,notedststr,insertindex,isnew);
126 }
int process_note_TeX (String notefile, String notedst)
Definition at line 128 of file note.cc.
References String::after(), String::at(), String::before(), EOUT, String::from(), String::gsub(), String::index(), post_process_note(), pre_process_note(), and res.
Referenced by process_note().
128                                                       {
129         String notestr, notedststr; bool isnew; int res;
130         if ((res = pre_process_note(notefile,notedst,"TeX",notestr,notedststr,isnew))<=0) return res;
131         // find a possible % <!-- @INSERT-AT:<tag>@ -->
132         int insertindex = -1;
133         String inserttag = notestr.at(BigRegex("[<]!--[         ]*@INSERT-AT:[^@]+@[    ]*--[>]"));
134         if (inserttag!="") {
135                 inserttag = inserttag.after("INSERT-AT:");
136                 inserttag = inserttag.before("@",-1);
137                 insertindex = notedststr.index(BigRegex("%[\n]*[<]!--[  ]*@"+inserttag+"@[      ]*--[>]"));
138         }
139         // find a possible % <!-- @INSERT-TL-NOTE@ -->
140         if (insertindex<0) insertindex = notedststr.index(BigRegex("%[\n]*[<]!--[       ]*@INSERT-TL-NOTE@[     ]*--[>]"));
141         // find \end{document}
142         if (insertindex<0) insertindex = notedststr.index("\\end{document}");
143         // find \endinput
144         if (insertindex<0) insertindex = notedststr.index("\\endinput");
145         if (insertindex<0) EOUT << "dil2al: Note destination " << notedst << " missing \\end{document} and \\endinput tags, continuing\n";
146         // convert to TeX
147         notestr.gsub(BigRegex("[<][Bb][Rr]\\([  ]+[^>][>]\\|[>]\\)"),"\\\\"); // <BR>
148         notestr.gsub(BigRegex("[<][Pp]\\([      ]+[^>]*[>]\\|[>]\\)"),"\n\n"); // <P>
149         notestr.gsub(BigRegex("[<][Uu][Ll]\\([  ]+[^>]*[>]\\|[>]\\)"),"\\begin{itemize}"); // <UL>
150         notestr.gsub(BigRegex("[<]/[Uu][Ll]\\([         ]+[^>]*[>]\\|[>]\\)"),"\\end{itemize}"); // </UL>
151         notestr.gsub(BigRegex("[<][Oo][Ll]\\([  ]+[^>]*[>]\\|[>]\\)"),"\\begin{enumerate}"); // <OL>
152         notestr.gsub(BigRegex("[<]/[Oo][Ll]\\([         ]+[^>]*[>]\\|[>]\\)"),"\\end{enumerate}"); // </OL>
153         notestr.gsub(BigRegex("[<][Ll][Ii]\\([  ]+[^>]*[>]\\|[>]\\)"),"\\item "); // <LI>
154         notestr.gsub(BigRegex("[<][Hh]1\\([     ]+[^>]*[>]\\|[>]\\)"),"\\section{"); // <H1>
155         notestr.gsub(BigRegex("[<][Hh]2\\([     ]+[^>]*[>]\\|[>]\\)"),"\\subsection{"); // <H2>
156         notestr.gsub(BigRegex("[<][Hh]3\\([     ]+[^>]*[>]\\|[>]\\)"),"\\subsubsection{"); // <H3>
157         notestr.gsub(BigRegex("[<][Hh]4\\([     ]+[^>]*[>]\\|[>]\\)"),"\\paragraph{"); // <H3>
158         notestr.gsub(BigRegex("[<]/[Hh][1-4]\\([        ]+[^>]*[>]\\|[>]\\)"),"}"); // </H1>,</H2>,</H3>,</H4>
159         notestr.gsub(BigRegex("[<][Hh][Rr]\\([  ]+[^>]*[>]\\|[>]\\)"),"\\hline "); // <HR>
160         notestr.gsub(BigRegex("[<]!--"),"% <!--"); // <!-- -->
161         notestr.gsub(BigRegex("[<][Tt][Aa][Bb][Ll][Ee][         ]*[^>]*[>]"),"\\begin{tabular}{???}"); // <TABLE>
162         notestr.gsub(BigRegex("[<]/[Tt][Aa][Bb][Ll][Ee][        ]*[^>]*[>]"),"\\end{tabular}"); // </TABLE>
163         notestr.gsub(BigRegex("[<][Tt][Rr][     ]*[^>]*[>]"),"\\\\\n"); // <TR>
164         notestr.gsub(BigRegex("[<]/[Tt][Rr][    ]*[^>]*[>]"),""); // <TR>
165         notestr.gsub(BigRegex("[<][Tt][Dd][     ]*[^>]*[>]")," & "); // <TD>
166         notestr.gsub(BigRegex("[<]/[Tt][Dd][    ]*[^>]*[>]"),""); // <TD>
167         notestr.gsub(BigRegex("[<][Tt][Hh][     ]*[^>]*[>]")," & {\\bf "); // <TH>
168         notestr.gsub(BigRegex("[<]/[Tt][Hh][    ]*[^>]*[>]"),"}"); // <TH>
169         notestr.gsub(BigRegex("[<][Bb]\\([      ]+[^>]*[>]\\|[>]\\)"),"{\\bf "); // <B>
170         notestr.gsub(BigRegex("[<][Ii]\\([      ]+[^>]*[>]\\|[>]\\)"),"{\\em "); // <I>
171         notestr.gsub(BigRegex("[<][Uu]\\([      ]+[^>]*[>]\\|[>]\\)"),"\\underline{"); // <U>
172         notestr.gsub(BigRegex("[<]/[BbIiUu]\\([         ]+[^>]*[>]\\|[>]\\)"),"}"); // </B>,</I>,</U>
173         notestr.gsub(BigRegex("[<][Ee][Mm]\\([  ]+[^>]*[>]\\|[>]\\)"),"{\\em "); // <EM>
174         notestr.gsub(BigRegex("[<]/[Ee][Mm]\\([         ]+[^>]*[>]\\|[>]\\)"),"}"); // </EM>
175         notestr.gsub(BigRegex("[<][Ss][Tt][Rr][Oo][Nn][Gg][     ]*[^>]*[>]"),"{\\bf "); // <STRONG>
176         notestr.gsub(BigRegex("[<]/[Ss][Tt][Rr][Oo][Nn][Gg][    ]*[^>]*[>]"),"}"); // </STRONG>
177         // <A HREF="http://the-reference-url/">the-reference-text</A>
178         // <A NAME="the-reference-name-tag">the-reference-anchor</A>
179         int i = 0, j = 0, k;
180         while (i>=0) {
181                 i = notestr.index(BigRegex("[<][Aa][    ]+[^>]*\\([Hh][Rr][Ee][Ff]\\|[Nn][Aa][Mm][Ee]\\)[       ]*=[    ]*[^>]*[>].*[<]/[Aa][   ]*[^>]*[>]"),j);
182                 if (i>=0) {
183                         k = notestr.index(">",i) + 1;
184                         j = notestr.index(BigRegex("[<]/[Aa][   ]*[^>]*[>]"),i);
185                         if (k<j) {
186                                 String tmpstr = "</A><!--\n"+notestr.at(k,j-k)+'\n'+notestr.after(BigRegex("[<]/[Aa][   ]*[^>]*[>]"),j);
187                                 notestr = notestr.before(BigRegex("[<]/[Aa][    ]*[^>]*[>]"),j);
188                                 notestr += tmpstr;
189                                 //notestr.at(BigRegex("[<]/[Aa][        ]*[^>]*[>]"),j)="</A><!--\n"+notestr.at(k,j-k)+'\n';
190                         }
191                         String tmpstr = "% -->"+notestr.from(i);
192                         notestr = notestr.before(i);
193                         notestr += tmpstr;
194                         //notestr.at(i,1)="% --><";
195                 }
196         }
197         // other <...> tags
198         i = 0; j = 0;
199         while (i>=0) {
200                 i = notestr.index(BigRegex("[<][^>]*[>]"),j);
201                 if (i>=0) {
202                         j = notestr.index(">",i);
203                         String tmpstr = "% "+notestr.at(i,(j-i)+1)+"\n"+notestr.after(j);
204                         notestr = notestr.before(i)+tmpstr;
205                         //notestr.at(j,1) = ">\n";
206                         //notestr.at(i,1) = "% <";
207                 }
208         }
209         notestr.gsub("&lt;","<"); // &lt;
210         notestr.gsub("&gt;",">"); // &gt;
211         notestr.gsub("&amp;","\\&"); // &amp;
212         notestr.gsub("&nbsp;","\\relax"); // &nbsp;
213         // clean up
214         notestr.gsub("\n\n","\n");
215         notestr.gsub(BigRegex("[        ]+\n"),"\n");
216         // insert note into notedst
217         return post_process_note(notedst,notestr,notedststr,insertindex,isnew);
218 }
int process_note_TL (String notefile, String notedst)
Definition at line 80 of file note.cc.
References add_TL_chunk_or_entry(), decide_add_TL_chunk(), EOUT, String::index(), String::length(), pre_process_note(), process_HTML(), and res.
Referenced by process_note().
80                                                      {
81 // A task log entry will be added to the current TL chunk, or to the TL chunk
82 // immediately preceding a @INSERT-TL-NOTE@ tag, or optionally to a new TL chunk,
83 // possibly in a new TL section.
84         String notestr, tl; bool isnew; int res;
85         if ((res = pre_process_note(notefile,notedst,"Task Log",notestr,tl,isnew))<=0) return res;
86         const int LLEN = 10240;
87         char lbuf[LLEN];
88         // search for <!-- @INSERT-TL-NOTE@ --> in TL
89         int tlinsertloc; bool comparetimes = true;
90         if ((tlinsertloc = tl.index("<!-- @INSERT-TL-NOTE@ -->"))>=0) {
91                 tlinsertloc -= tl.length();
92                 comparetimes = false;
93         }
94         // determine whether to add a new Task Log chunk
95         String chunkid;
96         if ((chunkid=decide_add_TL_chunk(tl,tlinsertloc,comparetimes))=="") return -1;
97         // HTML process entry (and fill in @tag@ codes)
98         process_HTML(notestr);
99         // add entry to Task Log chunk
100         newTLID = add_TL_chunk_or_entry(tl,notestr,false,chunkid,tlinsertloc);
101         if (newTLID=="") {
102                 EOUT << "dil2al: Unable to add new Task Log entry in process_note_TL()\n";
103                 return -1;
104         }
105         return tlinsertloc;
106 }
bool Quantitative_Assessment (char qatype, String ppfile)
Definition at line 1322 of file ppfilter.cc.
References Assess_Paper_Correction_Time(), and EOUT.
Referenced by dil2al_commands().
1322                                                          {
1323 // Carry out quantitative assessments that can aid in tasks,
1324 // e.g. obtaining statistics about a paper that help in the
1325 // scheduling of DIL entries with appropriate time requirements.
1326         switch (qatype) {
1327                 case 'c': // assess time required for paper corrections
1328                         return Assess_Paper_Correction_Time(ppfile);
1329                 default:
1330                         EOUT << "dil2al: Unknown assessment request `" << qatype << " in Quantitative_Assessment()\n";
1331                         return false;
1332         }
1333         return true;
1334 }
void read_data_from_stream (istream & ifs, String & dstr, const char * terminate)
Definition at line 2143 of file utilities.cc.
Referenced by initialize_new_DIL_TL(), modify_DIL_group_target_dates_cmd(), and send_dil_to_DIL().
2143                                                                                  {
2144 // Reads data from a stream such as the data input stream
2145 // DIN line by line. Returns when end of file or a line
2146 // stating the terminate string is found.
2147 // *** This can be replaced by String::readtotag if LLEN=4096 is sufficient.
2148         const int LLEN = 10240;
2149         char lbuf[LLEN];
2150         while (ifs) {
2151                 ifs.getline(lbuf,LLEN);
2152                 if (ifs.eof()) break;
2153                 if (strcmp(lbuf,terminate)==0) break;
2154                 dstr = (dstr + lbuf) + '\n';
2155         }
2156 }
bool read_file_into_String (bool & isnew, String filename, String & filestr)
Definition at line 2074 of file utilities.cc.
References EOUT.
Referenced by add_TL_chunk_or_entry(), add_TL_section(), Assess_Paper_Correction_Time(), chunk_controller(), extract_paper_novelties(), extract_paper_plan_to_paper(), generate_AL_entry(), generate_modify_element_FORM_interface_DIL_entry_parameters(), get_file_in_list(), get_Paper_Plans_Section_IDs(), include_article_head_template(), include_article_section_head_template(), include_article_tail_template(), modify_element_through_FORM_interface(), pre_process_note(), Target_Access::read_cleartext_into_String(), read_file_into_String(), read_financial_notes_file(), Target_Access::read_raw_into_String(), Target_Access::read_uncompressed_into_String(), remove_AL_TC(), select_TL_DIL_refs(), and update_main_ALs().
2074                                                                             {
2075 // read the file called filename into filestr if it exists,
2076 // optionally offer to create the file if it does not exist,
2077 // or warn about the inability to open the file
2078 // returns true if file content was read into filestr
2079 // note that no file is created at this point, but the setting
2080 // of the isnew flag can be used later (e.g. by the function
2081 // write_string_to_file()) to anticipate new file creation
2082         if (read_file_into_String(filename,filestr,false)) {
2083                 isnew = false;
2084                 return true;
2085         } else {
2086                 if (offercreate) {
2087                         const int LLEN = 10;
2088                         char lbuf[LLEN];
2089                         cout << "File " << filename << "\ndoes not exist, create (y/N)? ";
2090                         cin.getline(lbuf,LLEN);
2091                         if ((lbuf[0]!='y') && (lbuf[0]!='Y')) return false;
2092                         isnew = true;
2093                         return true;
2094                 } else {
2095                         EOUT << "dil2al: Unable to open " << filename << " in read_file_into_String()\n";
2096                         return false;
2097                 }
2098         }
2099 }
bool read_file_into_String (String filename, String & filestr, bool warnnoopen = true)
Definition at line 2062 of file utilities.cc.
2062                                                                                       {
2063 // read the file called filename into the string filestr,
2064 // optionally warning about the inability to open the file
2065 // returns true if file content was read into filestr
2066         ifstream sfl(filename);
2067         if (read_file_into_String(sfl,filestr,false)) return true;
2068         else {
2069                 if (warnnoopen) EOUT << "dil2al: Unable to open " << filename << " in read_file_into_String()\n";
2070                 return false;
2071         }
2072 }
bool read_file_into_String (ifstream & sfl, String & filestr, bool warnnoopen = true)
Definition at line 2038 of file utilities.cc.
2038                                                                                      {
2039 // read from an open file stream into the string filestr,
2040 // optionally warning about the inability to open the file
2041 // returns true if file content was read into filestr
2042         if (sfl) {
2043                 filestr = sfl;
2044 /*              sfl.seekg(0,ios::end); // seek to EOF
2045                 long int sflsize = sfl.tellg();
2046                 sfl.seekg(0);
2047                 char * s;
2048                 s = new char[sflsize+1];
2049                 sfl.read(s,sflsize);
2050                 s[sfl.gcount()]='\0';
2051                 filestr = s;
2052                 delete[] s;
2053                 if (sfl.gcount()!=sflsize) EOUT << "dil2al: Characters read (" << sfl.gcount() << ") does not equal expected file size (" << sflsize << ") in read_file_into_String(), continuing as is\n";
2054 */              sfl.close();
2055                 return true;
2056         } else {
2057                 if (warnnoopen) EOUT << "dil2al: Unable to open file in read_file_into_String()\n";
2058                 return false;
2059         }
2060 }
bool read_financial_notes_file (PLLRoot< Financial_Note > & fnotes, String & finnotestop, String & finnotesend)
Definition at line 82 of file finances.cc.
References String::before(), String::del(), EOUT, String::from(), String::index(), String::length(), Financial_Note::link_sorted(), read_file_into_String(), String::SEARCH_END, Time(), and VOUT.
Referenced by financial_monthly(), and financial_notes().
82                                                                                                              {
83   String finnotesstr;
84   // read financial notes file
85   if (!read_file_into_String(finnotesfile,finnotesstr)) return false;
86   // extract financial notes table
87   if (verbose) VOUT << "Parsing Financial Notes file\n";
88   int i, j;
89   if ((i=finnotesstr.index("<!-- dil2al: start items -->",String::SEARCH_END,0))<0) {
90     EOUT << "formalizer: Missing start of financial notes items table\n";
91     return false;
92   }
93   if ((j=finnotesstr.index("<!-- dil2al: end items -->",0))<0) {
94     EOUT << "formalizer: Missing end of financial notes items table\n";
95     return false;
96   }
97   finnotestop = finnotesstr.before(i)+'\n';
98   finnotesend = finnotesstr.from(j);
99   finnotesstr.del(j,finnotesstr.length()-j);
100   finnotesstr.del(0,i); // finnotesstr contains table
101   // extract financial notes items while keeping track of dates and sorting by date
102   time_t notedate = Time(NULL);
103   for (i=0; i>=0; ) {
104     Financial_Note * fn = new Financial_Note(finnotesstr,notedate,i);
105     if (i<0) delete fn;
106     else fn->link_sorted(fnotes);
107   }
108   return true;
109 }
bool refresh_quick_load_cache ()
Definition at line 1359 of file alcomp.cc.
References EOUT, Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), and Detailed_Items_List::Get_All_Topical_DIL_Parameters().
Referenced by dil2al_commands().
1359                                 {
1360   if (!usequickloadcache) {
1361     EOUT << "dil2al: The usequickloadcache flag is not set in refresh_quick_load_cache()\n";
1362     return false;
1363   }
1364   Detailed_Items_List dilist;
1365   if (dilist.Get_All_DIL_ID_File_Parameters()<0) return false;
1366   if (dilist.Get_All_Topical_DIL_Parameters(true)<0) return false;
1367   return true;
1368 }
String relurl (String srcurl, String dsturl)
Definition at line 1927 of file utilities.cc.
References String::after(), String::before(), common_prefix(), String::empty(), String::from(), String::lastchar(), String::length(), String::prepend(), and String::through().
Referenced by AL_Day_Marker(), AL_Passed_Target_Dates(), extract_paper_novelties(), extract_paper_plan_to_paper(), extract_recursively(), extraction_put_figure(), generate_AL(), generate_Figures_Directory_entry(), Active_List::generate_focused_AL(), Active_List::generate_wide_AL(), get_figure_data(), make_note(), update_main_ALs(), and Detailed_Items_List::Write_to_File().
1927                                             {
1928         String tmp = common_prefix(srcurl.through('/',-1),dsturl.through('/',-1));
1929         if ((!tmp.empty()) && (tmp.lastchar()!='/')) tmp = tmp.through('/',-1);
1930         if (tmp!="") {
1931                 srcurl = srcurl.after(tmp);
1932                 dsturl = dsturl.after(tmp);
1933                 tmp = dsturl.from('#'); // for dsturl references in srcurl file
1934                 if (tmp.length()>0) {
1935                         String tmp2 = srcurl.before('#'); if (tmp2.length()==0) tmp2 = srcurl;
1936                         if (tmp2==dsturl.before('#')) return tmp;
1937                 }
1938                 while (srcurl.before('/')!="") { srcurl=srcurl.after('/'); dsturl.prepend("../"); }
1939         }
1940         return dsturl;
1941 }
bool remove_AL_TC (String alref, String dilid)
Definition at line 1256 of file alcomp.cc.
References String::alloc(), String::at(), DEFAULTALDAYEMPHASIS, DEFAULTALFOCUSEDEMPHASIS, String::del(), EOUT, get_AL_entry(), HTML_get_href(), HTML_put_table_row(), String::length(), read_file_into_String(), SECONDSPERDAY, BigRegex::sublen(), BigRegex::subpos(), time_stamp_GM(), time_stamp_time_of_day(), VOUT, and write_file_from_String().
Referenced by stop_TL_chunk().
1256                                               {
1257 // removes the top task chunk if it has DIL entry ID dilid
1258 // from the AL indicated by alref and updates the suggested
1259 // start time of that AL day according to the assumed time
1260 // taken to do the task chunk (desynchronization is noticed
1261 // and taken care of in select_TL_DIL_refs())
1262 // day rows at the top of the AL that are not followed by task
1263 // rows are removed
1264 // returns false if dilid did not match the DIL entry ID of
1265 // the top task chunk, or if the visible focused AL became
1266 // empty
1267         String alstr, newalstr;
1268         if (!read_file_into_String(alref,alstr)) return false;
1269         newalstr.alloc(alstr.length());
1270         // get day row and remove empty days at top of AL
1271         // and find top TC to compare with dilid
1272         StringList alentries; int numentries = 0, alpos = 0, tcsfound = 0, tcentries[2], rowstart, rowend;
1273         while (tcsfound<2) {
1274                 switch (get_AL_entry(alstr,alpos,alentries[numentries],rowstart,rowend)) {
1275                         case -1:
1276                                 // *** could detect from numentries and tcsfound
1277                                 //     to give a different VOUT message if the
1278                                 //     visible AL portion contained no more TCs
1279                                 EOUT << "Missing data in AL " << alref << " after position " << alpos << " in remove_AL_TC()";
1280                                 return false;
1281                                 break;
1282                         case 0: break;
1283                         case 1:
1284                                 if (numentries==0) {
1285                                         EOUT << "TC without preceding Day ID in " << alref << " after position " << alpos << " in remove_AL_TC()";
1286                                         return false;
1287                                 }
1288                                 if (tcsfound==0) {
1289                                         String alhrefurl, alhreftext;
1290                                         if (HTML_get_href(alentries[numentries],0,alhrefurl,alhreftext)<0) {
1291                                                 EOUT << "Missing DIL ID reference in " << alref << " after position " << alpos << " in remove_AL_TC()";
1292                                                 return false;
1293                                         }
1294                                         if (alhreftext!=dilid) { // different task
1295                                                 VOUT << "Top of AL " << alref << " does not match DIL entry " << dilid << '\n';
1296                                                 return false;
1297                                         }
1298                                 }
1299                                 tcentries[tcsfound] = numentries;
1300                                 tcsfound++;
1301                                 break;
1302                 }
1303                 if (alpos==0) newalstr = alstr.at(0,rowstart); // copy head of AL
1304                 numentries++; alpos = rowend;
1305         }
1306         if (tcentries[1]==(tcentries[0]+1)) { // next TC on same day, modify daystart
1307                 BigRegex rds("(suggested start[         ]+\\([0-9][0-9]:[0-9][0-9]\\)");
1308                 int didx = tcentries[0]-1, dstimepos;
1309                 if ((dstimepos=alentries[didx].index(rds))<0) {
1310                         EOUT << "Missing suggested start in AL " << alref << " at row " << didx << " in remove_AL_TC()\n";
1311                         return false;
1312                 }
1313                 String daystartstr = alentries[didx].at(rds.subpos(1),rds.sublen(1));
1314                 daystartstr.del(':');
1315                 time_t tds = time_stamp_time_of_day(daystartstr) + ((time_t) (timechunksize*60));
1316                 if (tds>=SECONDSPERDAY) {
1317                         VOUT << "Updated suggested start time exceeds length of day, limiting to 23:59\n";
1318                         tds = SECONDSPERDAY-1;
1319                 }
1320                 daystartstr = time_stamp_GM("%H:%M",tds);
1321                 for (int i = 0; i<5; i++) alentries[didx][rds.subpos(1)+i] = daystartstr[i];
1322         }
1323         // determine day before second TC and write it
1324         int didx = tcentries[1]-1;
1325         if (didx==tcentries[0]) didx--;
1326         newalstr += HTML_put_table_row(DEFAULTALDAYEMPHASIS,alentries[didx]) + '\n';
1327         // write second TC with top TC colors
1328         newalstr += HTML_put_table_row(DEFAULTALFOCUSEDEMPHASIS,alentries[tcentries[1]]) + '\n';
1329         // copy remainder of AL
1330         newalstr += alstr.at(alpos,alstr.length()-alpos);
1331         return write_file_from_String(alref,newalstr,"AL");
1332 }
String* remove_whitespace (String & str)
Definition at line 2680 of file utilities.cc.
References String::gsub().
Referenced by generate_modify_element_FORM_interface_DIL_Superiors(), and select_TL_DIL_refs().
2680                                          {
2681   str.gsub(BRXwhite," ");
2682   return &str;
2683 }
String RX_Search_Safe (String s)
Definition at line 1814 of file utilities.cc.
References String::after(), String::gsub(), and String::length().
Referenced by add_TL_chunk_or_entry(), Assess_Paper_Correction_Time(), convert_item_content_to_TeX(), extract_hierarchy_depth_decrease_to_paper(), extract_hierarchy_depth_increase_to_paper(), extract_paper_novelties(), extract_recursively(), extract_required_item_to_paper(), get_figure_data(), include_article_section_head_template(), include_article_section_tail_template(), include_protected_text(), item_content_between_range_tags(), modify_DIL_group_target_dates_cmd(), send_dil_to_DIL(), TeX_format_corrections(), and update_DIL_entry_elements().
1814                                 {
1815 // converts a regular string to that
1816 // string's match in a BigRegex search
1817         s.gsub("[","[[]");
1818         s.gsub("]","[]]");
1819         s.gsub(BigRegex("[\\.*+?$]"),"[_0]",'_');
1820         if ((s.length()>0) && (s[0]=='^')) s = "[^]" + s.after(0);
1821         return s;
1822 }
bool schedule_controller (String controllercmd)
Definition at line 105 of file controller.cc.
References chunk_controller(), EOUT, and time_chunk_remaining().
Referenced by dil2al_commands().
105                                                {
106 // schedules periodical calls to chunk_controller(),
107 // either via an at-job or by retaining dil2al as a daemon
108         String chunkid;
109         if (isdaemon) { // daemon schedules chunk_controller()
110                 String ccmd;
111                 while (1) {
112                         ccmd = controllercmd; // fresh copy of automatic commands to controller
113                         if ((chunkid=chunk_controller(ccmd))=="") return false;
114                         if ((chunkid=="-1") || (chunkid=="-2")) return true;
115                         time_t tdiff = time_chunk_remaining(chunkid);
116                         if (tdiff>0) sleep(tdiff);
117                 }
118         } else { // at-job schedules chunk_controller()
119                 if ((chunkid=chunk_controller(controllercmd))=="") return false;
120                 if ((chunkid=="-1") || (chunkid=="-2")) return true;
121 #ifdef DEBUG
122 cout << "current chunkid = " << chunkid << '\n';
123 #endif
124                 time_t tdiff = time_chunk_remaining(chunkid);
125 #ifdef DEBUG
126 cout << "seconds remaining = " << tdiff << '\n';
127 #endif
128                 if (tdiff>0) {
129                         tdiff /= 60;
130                         String atcmd = atcommand;
131                         if (tdiff) { atcmd += " + "; atcmd += dec(tdiff); atcmd += " minutes"; }
132                         else atcmd += " + 1 minute";
133                         FILE * p = popen((const char *) atcmd, "w");
134                         if (!p) {
135                                 EOUT << "dil2al: Unable to schedule controller call with " << atcontroller << " in schedule_controller()\n";
136                                 return false;
137                         }
138                         fprintf(p,(const char *) atcontroller);
139                         if (pclose(p)==-1) {
140                                 EOUT << "dil2al: Scheduling controller call with " << atcontroller << " did not complete operations in schedule_controller()\n";
141                                 return false;
142                         }
143                 }
144         }
145 #ifdef DEBUG
146 const int LLEN = 10;
147 char lbuf[LLEN];
148 cout << "Scheduled controller processing completed...\n";
149 cin.getline(lbuf,LLEN);
150 #endif
151         return true;
152 }
String search (StringList & targets, String searchkey, bool stringoutput = true)
Definition at line 425 of file search.cc.
References PLLRoot< PLLType >::clear(), PLLRoot< PLLType >::head(), StringList::length(), PLLRoot< PLLType >::link_before(), PLL_LOOP_FORWARD, res, search_output(), and write_file_from_String().
Referenced by search_cmd().
425                                                                                 {
426         // Search the target for searchkey
427         // Result output is returned as a string or on VOUT.
428         // Returns results as string or a string with the number of results.
429         // Note: Directories are conceptually handled in the same manner
430         // as HTML pages, but they are read differently and can contain
431         // only links to follow for recursive searching.
432         // Note: It is quite easy to make alternative search functions using
433         // the Search_Target and Search_Result classes.
434         // initialize global lists
435         static String res; // stored in function, not objects, static to avoid problems with lifetime of object that return value points to
436         PLLRoot<Search_Result> results;
437         PLLRoot<Search_Target> globaltargets;
438         Quick_String_Hash encountered;
439         // search target objects for searchkey
440         // *** Whether the list of Search_Target objects ever becomes
441         //     greater than one depends on whether a followlinks search
442         //     is conducted in breadth-first or depth-first fashion.
443         Search_Target * t; String progressfile(tareadfile+"progress"), progress; long resnum = 0;
444         for (int i = 0; i<targets.length(); i++) if (!targets[i].empty()) {
445 //cerr << searchkey << " in " << targets[i] << '\n'; cerr.flush();
446                 t = new Search_Target(&results,searchkey,targets[i],followlinks,false,&encountered);
447                 globaltargets.link_before(t);
448                 // *** Not quite sure where to put the next lines, in this
449                 //     loop or outside it, and how that affects the search
450                 //     order if additional targets are added by finding
451                 //     links to follow in a breadth-first followlinks search.
452                 long i_search = 0;
453                 PLL_LOOP_FORWARD(Search_Target,globaltargets.head(),1) {
454                         if (searchprogressmeter) { // write a progress meter to a file
455                                 progress = String((long) i)+','+String(i_search)+':'+e->Target();
456                                 write_file_from_String(progressfile,progress,"",true);
457                                 i_search++;
458                         }
459                         e->search();
460                         if (immediatesearchoutput) resnum += search_output(&results,res,stringoutput);
461                         // *** caused problems here: e->remove(); // frees up space and avoids repeated searches
462                 }
463                 globaltargets.clear(); // frees up space and avoids repeated searches
464         }
465         if (!immediatesearchoutput) resnum = search_output(&results,res,stringoutput);
466         if (!stringoutput) res = String(resnum);
467         return res;
468 }
bool search_cmd (String grepinfo)
Definition at line 527 of file search.cc.
References String::after(), String::at(), String::before(), StringList::contains(), String::del(), String::empty(), EOUT, file_is_directory(), Get_Target_Regex(), String::gsub(), String::index(), String::length(), replicate(), res, search(), and VOUT.
Referenced by dil2al_commands(), and search_FORM_cmd().
527                                  {
528         // Command line interface to search()
529         // Note: For optimal use, wrap the output of this call in a complete framework
530         // for an HTML file. It is also possible to direct the error output to another
531         // file and to link to that one from the HTML file with the search results.
532         const BigRegex trx("@[^/]+@$");
533         const BigRegex rrx("\\(^[Hh][Tt][Tt][Pp]:\\|^[Ff][Tt][Pp]:\\)");
534         if (grepinfo.empty()) {
535                 EOUT << "dil2al: Missing search information in search_cmd()\n";
536                 return false;
537         }
538         char separator = grepinfo[0];
539         grepinfo.gsub(replicate(separator,2),(char) 255); // temporarily replace escaped characters
540         int keyend = grepinfo.index(separator,1);
541         if (keyend<0) {
542                 EOUT << "dil2al: Missing search key end in search_cmd()\n";
543                 return false;
544         }
545         if (keyend==1) {
546                 EOUT << "dil2al: Zero length search key in search_cmd()\n";
547                 return false;
548         }
549         if ((keyend+1)>=grepinfo.length()) {
550                 EOUT << "dil2al: Missing search target in search_cmd()\n";
551                 return false;
552         }
553         // put all search targets into a StringList
554         String searchkey(grepinfo.at(1,keyend-1)); searchkey.gsub((char) 255,separator); // restore escaped characters
555         StringList targets;
556         grepinfo.del(0,keyend+1);
557         for (unsigned long i = 0; (!grepinfo.empty()); i++) {
558                 // get next target from command line arguments
559                 targets[i] = grepinfo.before(separator);
560                 if (targets[i].empty()) targets[i] = grepinfo;
561                 targets[i].gsub((char) 255,separator); // restore escaped characters
562                 // interpret target
563                 // *** add: tar(gz) and zip archives, archive declarator, file containing target lines, default set
564                 if (targets[i].contains(trx)) i = Get_Target_Regex(targets,i,targets[i]) - 1;
565                 // *** does not yet properly handle remote files matching regex pattern or remote files pointing to archives
566                 // Now handled within search: else if (file_is_directory(targets[i])) i = Get_Target_Directory(targets,i,targets[i]) - 1;
567                 else if ((!targets[i].contains(rrx)) && (file_is_directory(targets[i])) && (followlinks<=0)) { // follow links one deep into the directory
568                         followlinks = 1;
569                         if (verbose) VOUT << "(Setting followlinks=1 to search directory.)\n";
570                 }
571                 grepinfo = grepinfo.after(separator);
572         }
573         VOUT << '\n';
574         String res = search(targets,searchkey,false);
575         VOUT << "(Number of search results: <B>" << res << "</B>)\n<P>\n";
576         return true;
577 }
bool search_FORM_cmd (StringList * qlist = NULL)
Definition at line 579 of file search.cc.
References DIL2AL_CONDITIONAL_ERROR_RETURN, String::empty(), String::gsub(), search_cmd(), and URI_unescape().
Referenced by Detect_Form_Input().
579                                                 {
580   // Perform a dil2al regex search with input from an HTML FORM.
581   const char escapedseparator[3] = {254,254,0};
582   const char separator = 254;
583   if (!qlist) return false;
584   String grepinfo(separator);
585   int paridx; String parstr;
586   DIL2AL_CONDITIONAL_ERROR_RETURN((paridx=qlist->contains("regex="))<0,"No regex parameter found in form data in search_FORM_cmd()\n");
587   parstr=URI_unescape((*qlist)[paridx].after('='));
588   DIL2AL_CONDITIONAL_ERROR_RETURN(parstr.empty(),"Empty regex parameter in search_FORM_cmd()\n");
589   parstr.gsub(separator,escapedseparator);
590   grepinfo += parstr + separator;
591   DIL2AL_CONDITIONAL_ERROR_RETURN((paridx=qlist->contains("targets="))<0,"No targets parameter found in form data in search_FORM_cmd()\n");
592   parstr=URI_unescape((*qlist)[paridx].after('='));
593   DIL2AL_CONDITIONAL_ERROR_RETURN(parstr.empty(),"Empty targets parameter in search_FORM_cmd()\n");
594   parstr.gsub(separator,escapedseparator);
595   parstr.gsub('\r',"");
596   parstr.gsub('\n',separator);
597   grepinfo += parstr;
598   return search_cmd(grepinfo);
599 }
bool search_TL (String searchstr)
Definition at line 15 of file tlfilter.cc.
15                                  {
16 // searchstr is a regexp
17 }
String select_TL_AL_refs (String & tl, bool newchunk, String newdilref)
Definition at line 359 of file tladmin.cc.
References String::after(), ANSI_BOLD_OFF, ANSI_BOLD_ON, ANSI_UNDERLINE_OFF, ANSI_UNDERLINE_ON, String::before(), String::contains(), String::del(), EOUT, find_in_line(), find_line(), get_most_recent_TC_AL(), String::gsub(), String::matches(), String::prepend(), and RELLISTSDIR.
Referenced by add_TL_chunk_or_entry().
359                                                                        {
360 // select AL reference for new TL chunk or entry
361 // tl should provide a pointer to a String containing
362 // the most recent section of the Task Log
363 // newchunk indicates if a new chunk or a new entry is being prepared
364 // if newdilref=="*" then possibly choose a new AL
365 // return value "*<AL-ref>"=same as chunk, ""=error
366 // default is current AL
367         const int LLEN = 10240;
368         char lbuf[LLEN];
369         StringList aloptions;
370         int numaloptions = 0;
371         // AL should default either to current, or to that associated with DIL
372         // alternatives can be read from list.html
373         // obtain current AL from TL
374         String curAL = get_most_recent_TC_AL(tl);
375 //*** could insure that if newdilref!="*" the default
376 //*** Active List returned is curAL if the DIL is in it,
377 //*** otherwise the primary one the DIL in newdilref is in
378         if ((askALDILref) && (newdilref=="*")) {
379                 // some options from listfile
380                 ifstream alf(listfile);
381                 if (!alf) EOUT << "dil2al: Unable to read " << listfile << " in select_TL_AL_refs(), continuing\n";
382                 else {
383                         if (find_line(&alf,"[<]A[       ][^>]*[Nn][Aa][Mm][Ee][         ]*=[    ]*\"AL\"",lbuf,LLEN)) {
384                                 String alid[2];
385                                 while (find_in_line(&alf,"[<]LI[>][<]A[         ][^>]*[Hh][Rr][Ee][Ff][         ]*=[    ]*\"(.+)[<][/]A[>]",2,alid,"[<][/]UL[>]",lbuf,LLEN)==1) {
386                                         alid[1].gsub("\">",":");
387                                         alid[1].del(RELLISTSDIR);
388                                         if (!curAL.contains(alid[1].before(":"))) {
389                                                 aloptions[numaloptions] = alid[1];
390                                                 numaloptions++;
391                                         }
392                                 }
393                         } else EOUT << "dil2al: No AL references in " << listfile << " in select_TL_AL_refs(), continuing\n";
394                         alf.close();
395                 }
396                 // can enter AL ids directly, or quick-chooser choice from priority list
397                 String affiliation = "";
398                 while (affiliation=="") {
399                         if (useansi) cout << ANSI_UNDERLINE_ON; // underline on
400                         if (newchunk) cout << "\nChunk "; else cout << "\nEntry ";
401                         cout << "AL reference ID\n";
402                         if (useansi) cout << ANSI_UNDERLINE_OFF; // underline off
403                         for (int i=0; i<numaloptions; i++) cout << i << ". " << aloptions[i] << '\n';
404                         if (useansi) cout << ANSI_BOLD_ON; // bold on
405                         cout << "\"\"=" << curAL.after(basedir+RELLISTSDIR) << " DEFAULT,\n\"?\"=browse (e.g. use S to save file info to ~/tmp/dilref for dil2al),\n\"?&\"=fork browser: ";
406                         if (useansi) cout << ANSI_BOLD_OFF; // bold off
407                         cin.getline(lbuf,LLEN);
408                         if (lbuf[0]!='\0') {
409                                 affiliation = lbuf;
410                                 if (affiliation.matches(BRXint)) { // quick-select menu item
411                                         int q = atoi((const char *) affiliation);
412                                         if ((q>=0) && (q<numaloptions)) affiliation = aloptions[q].before(":");
413                                         else {
414                                                 EOUT << "dil2al: Selection " << q << " is not a predefined AL reference option\n";
415                                                 affiliation = "";
416                                         }
417                                 } else if (affiliation=="?") {
418                                         if (system(browser+" "+listfile)<0) EOUT << "dil2al: Unable to browse in select_TL_AL_refs(), continuing\n";
419                                         affiliation = "";
420                                         ifstream drf(dilref);
421                                         if (drf) {
422                                                 if (find_line(&drf,"Current URL",lbuf,LLEN)) {
423                                                         String urlline = lbuf;
424                                                         drf.getline(lbuf,LLEN);
425                                                         if (lbuf[0]==' ') urlline += lbuf;
426                                                         urlline.del("Current URL");
427                                                         urlline.del("file://");
428                                                         urlline.gsub(" ","");
429                                                         urlline.del(basedir+RELLISTSDIR);
430                                                         if (useansi) cout << ANSI_BOLD_ON; // bold on
431                                                         cout << "Take `" << urlline << "' as AL reference ID? (y/N)";
432                                                         if (useansi) cout << ANSI_BOLD_OFF; // bold off
433                                                         cin.getline(lbuf,LLEN);
434                                                         if ((lbuf[0]=='y') || (lbuf[0]=='Y')) affiliation = urlline;
435                                                 }
436                                                 drf.close();
437                                                 unlink(dilref);
438                                         }
439                                 } else if (affiliation=="?&") {
440                                         if (system("rxvt -e "+browser+" "+curAL+" &")<0) EOUT << "dil2al: Unable to spawn a browser in select_TL_AL_refs(), continuing\n";
441                                         affiliation = "";
442                                 } else { // verify that string is AL ID
443                                         alf.open(listfile);
444                                         if (!alf) {
445                                                 EOUT << "dil2al: Unable to read " << listfile << " in select_TL_AL_ref()\n";
446                                                 return String("");
447                                         }
448 #ifdef DEBUG
449                                         cout << "seeking " << affiliation << '\n';
450 #endif
451                                         if (find_line(&alf,"[<]A[       ][^>]*[Nn][Aa][Mm][Ee][         ]*=[    ]*\"AL\"",lbuf,LLEN)) {
452                                                 affiliation.prepend(RELLISTSDIR);
453                                                 affiliation.prepend("[<]LI[>][<]A[      ][^>]*[Hh][Rr][Ee][Ff][         ]*=[    ]*\"");
454                                                 if (find_line(&alf,affiliation,lbuf,LLEN)) {
455                                                         affiliation = lbuf;
456                                                         affiliation = affiliation.after(BigRegex("[Hh][Rr][Ee][Ff][     ]*=[    ]*\""));
457                                                         affiliation = affiliation.after(RELLISTSDIR);
458                                                         affiliation = affiliation.before("\">");
459 #ifdef DEBUG
460                                                         cout << "exists: " << affiliation << '\n';
461 #endif
462                                                 } else {
463                                                         EOUT << "dil2al: AL reference " << affiliation << " not found in " << listfile << '\n';
464                                                         affiliation = "";
465                                                 }
466                                         } else {
467                                                 EOUT << "dil2al: No AL references found in " << listfile << " in select_TL_AL_ref()\n";
468                                                 return String("");
469                                         }
470                                         alf.close();
471                                 }
472                         } else {
473                                 affiliation = curAL.after(basedir+RELLISTSDIR);
474                                 if (!newchunk) affiliation.prepend("*"); // same as chunk AL (no entry specific reference required)
475                         }
476                 }
477                 return affiliation;
478         } else {
479                 curAL = curAL.after(basedir+RELLISTSDIR);
480                 if (!newchunk) curAL.prepend("*");
481                 return curAL;
482         }
483 }
String select_TL_DIL_refs (String & tl, bool newchunk, String newalref)
Definition at line 161 of file tladmin.cc.
References AAU_ASK, AAU_NO, String::after(), ANSI_BOLD_OFF, ANSI_BOLD_ON, ANSI_UNDERLINE_OFF, ANSI_UNDERLINE_ON, String::at(), String::before(), confirmation(), String::contains(), StringList::contains(), String::del(), EOUT, find_line(), generate_AL(), get_most_recent_TC_AL(), get_most_recent_TC_DE(), String::gsub(), HTML_get_href(), HTML_get_table_cell(), HTML_remove_tags(), String::index(), String::length(), BigRegex::match_info(), String::matches(), String::prepend(), read_file_into_String(), RELLISTSDIR, remove_whitespace(), BigRegex::search(), Detailed_Items_List::Sort_by_Target_Date(), BigRegex::sublen(), BigRegex::subpos(), time_stamp_diff(), and VOUT.
Referenced by add_TL_chunk_or_entry().
161                                                                        {
162 // select DIL reference for new TL chunk or entry
163 // tl should provide a pointer to a String containing
164 // the most recent section of the Task Log
165 // newchunk indicates if a new chunk or a new entry is being prepared
166 // if newalref is not "" then use it as AL for default/quick choices
167 // return value "*<DIL-ref>"=same as chunk, "!<DIL-ref>"=non-DIL identifying
168 // comment, "*"=decision postponed (see variableAL), ""=error
169 // when newchunk=true the default is the highest priority item in the current AL
170 // when newchunk=true the default is the same as that of the current chunk
171         const int LLEN = 10240;
172         char lbuf[LLEN];
173         StringList diloptions;
174         int numdiloptions = 0;
175         String curAL;
176         if (newalref=="") curAL = get_most_recent_TC_AL(tl); // obtain current AL from TL
177         else {
178                 if (newalref[0]=='*') newalref.del("*");
179                 curAL = basedir+RELLISTSDIR+newalref;
180         }
181         // obtain default DIL ref for TL entry
182         if (!newchunk) { // chunk DIL ref (or identifying comment) is default
183                 diloptions[0] = get_most_recent_TC_DE(tl);
184                 if (diloptions[0]=="") {
185                         EOUT << "dil2al: Entry is not in a Task Log chunk in select_TL_DIL_refs()\n";
186                         return String("");
187                 }
188                 numdiloptions++;
189         }
190         // recompute the AL if the suggested start time for the next
191         // TC is significantly earlier than the current time
192         String curALstr;
193         if (read_file_into_String(curAL,curALstr)) {
194                 String tmpstr, cellcontent;
195                 HTML_get_table_cell(curALstr,0,tmpstr,cellcontent);
196                 HTML_remove_tags(cellcontent);
197                 BigRegex alr("Day[      ]+\\([0-9]+\\).*suggested[      ]+start[        ]+\\([0-9][0-9]\\):\\([0-9][0-9]\\)");
198                 if (cellcontent.index(alr)==0) {
199                         // get suggested start time for next TC
200                         tmpstr = cellcontent.at(alr.subpos(1),alr.sublen(1))+cellcontent.at(alr.subpos(2),alr.sublen(2))+cellcontent.at(alr.subpos(3),alr.sublen(3));
201                         time_t tdiff = time_stamp_diff(tmpstr,curtime); // positive if curtime is later than suggested time
202                         if (tdiff>alsyncslack) { // recompute the AL
203                                 // determine if AL updating should be automatic
204                                 // *** Note: A separate configuration variable should be used if alautoupdate
205                                 //     should apply only to the recomputation of the AL in stop_TL_chunk()
206                                 //     above.
207                                 switch (alautoupdate) {
208                                         case AAU_NO:
209                                                 if (verbose) VOUT << "Warning: AL desynchronized, no automatic recomputation (alautoupdate==AAU_NO)\n";
210                                                 break;
211                                         case AAU_ASK:
212                                                 if (confirmation("AL desynchronized, update now? (y/N) ",'y')) break;
213                                         default:
214                                                 VOUT << "Recomputing AL\n";
215                                                 Detailed_Items_List dilist;
216                                                 DIL_entry ** dep = dilist.Sort_by_Target_Date(true);
217                                                 // *** make this able to request generation of an AL
218                                                 //     corresponding to the superior that generated curAL
219                                                 if (!generate_AL(dep)) EOUT << "dil2al: Unable to generate AL in select_TL_DIL_refs(), continuing as is\n";
220                                                 else { // get new version of AL
221                                                         curALstr = "";
222                                                         read_file_into_String(curAL,curALstr);
223                                                 }
224                                                 delete[] dep;
225                                 }
226                         }
227                         // *** it is possible to add a message here if curtime is a lot
228                         //     smaller than the suggested start time of the AL, e.g.
229                         //     if all suggested TCs for this AL day have been completed
230                 } else EOUT << "Day row missing at top of AL " << curAL << " in select_TL_DIL_refs(), continuing as is\n";
231         }
232         // some options from high priority current AL items
233         if (curALstr.length()>0) {
234                 int cellindex = 0; String cellparameters, cellcontent;
235                 while ((numdiloptions<6) && ((cellindex=HTML_get_table_cell(curALstr,cellindex,cellparameters,cellcontent))>=0))
236                         if (!cellcontent.contains(BigRegex("[<]!--[     ]+@select_TL_DIL_refs:[         ]+SKIP ROW@[    ]+--[>]"))) { // skip marked rows
237                                 diloptions[numdiloptions]=cellcontent;
238                                 String idhreftext;
239                                 if (HTML_get_href(cellcontent,0,cellparameters,idhreftext)>=0) {
240                                         // only unique DIL options
241                                         for (int i=0; i<numdiloptions; i++) if (diloptions[i].contains(idhreftext)) { cellparameters=""; break; }
242                                         if (cellparameters.length()>0) {
243                                                 diloptions[numdiloptions]=cellparameters+':'+cellcontent.after(BigRegex("[]]\n?"));
244                                                 HTML_remove_tags(diloptions[numdiloptions]);
245                                                 remove_whitespace(diloptions[numdiloptions]);
246                                                 if (diloptions[numdiloptions]!="") numdiloptions++;
247                                         }
248                                 } else EOUT << "Missing DIL entry reference in AL " << curAL << " in select_TL_DIL_refs(), continuing\n";
249                         }
250         }
251         // some options from recent DIL refs in TL
252         BigRegex r("[<]!-- \\(chunk\\|entry\\) Context --[>]\\([^\n][^(]*\\)(");
253         int pos = tl.length(), matchlen;
254         while (((pos = r.search(tl,pos-1,matchlen,-1))>=0) && (numdiloptions<10)) {
255 #ifdef VERBOSEDEBUG
256                 cout << "Context...\n";
257 #endif
258                 int subpos;
259                 if (r.match_info(subpos,matchlen,2)) {
260                         diloptions[numdiloptions] = tl.at(subpos,matchlen);
261 #ifdef VERBOSEDEBUG
262                         cout << "Candidate Context from TL: " << diloptions[numdiloptions] << '\n';
263 #endif
264                         String idhrefname = diloptions[numdiloptions].at(BigRegex("#[0-9]+[.][0-9]+"));
265                         // only unique DIL options
266                         for (int i=0; i<numdiloptions; i++) if (diloptions[i].contains(idhrefname)) { idhrefname=""; break; }
267                         if (idhrefname!="") {
268                                 diloptions[numdiloptions].del(BigRegex("[<]A [^>]*[Hh][Rr][Ee][Ff][     ]*=[^\"]*\""));
269                                 diloptions[numdiloptions].gsub("\">",":");
270                                 diloptions[numdiloptions].del(BigRegex("\\([<][^>]*[>]\\)?[     ]*("));
271                                 if (diloptions[numdiloptions]!="") numdiloptions++;
272                         }
273                 }
274         }
275         // can enter DIL ids directly, or quick-chooser choice from priority list, or textual comment instead of DIL
276         if (askALDILref) {
277                 String affiliation = "";
278                 while (affiliation=="") {
279                         if (useansi) cout << ANSI_UNDERLINE_ON; // underline on
280                         if (newchunk) cout << "\nChunk "; else cout << "\nEntry ";
281                         cout << "DIL reference ID or identifying comment (DIL references generally\npreferred) can include HREFs\n";
282                         if (useansi) cout << ANSI_UNDERLINE_OFF; // underline off
283                         for (int i=1; i<numdiloptions; i++) cout << i << ". " << diloptions[i] << '\n';
284                         if (useansi) cout << ANSI_BOLD_ON; // bold on
285                         cout << "\"\"=" << diloptions[0] << " DEFAULT,\n\"?\"=browse (e.g. use S to save file info to ~/tmp/dilref for dil2al),\n\"?&\"=fork browser, \"*\"=postpone and get new Active List\n(current AL = "
286                                 << curAL.after(basedir+RELLISTSDIR) << "): ";
287                         if (useansi) cout << ANSI_BOLD_OFF; // bold off
288                         cin.getline(lbuf,LLEN);
289                         if (lbuf[0]!='\0') {
290                                 affiliation = lbuf;
291                                 if (affiliation.matches(BRXint)) { // quick-select menu item
292                                         int q = atoi((const char *) affiliation);
293                                         if ((q>0) && (q<numdiloptions)) affiliation = diloptions[q].before(":");
294                                         else {
295                                                 EOUT << "dil2al: Selection " << q << " is not a predefined DIL reference option\n";
296                                                 affiliation = "";
297                                         }
298                                 } else if (affiliation.matches(BRXdouble)) { // DIL ID
299                                         ifstream dbid(idfile);
300                                         if (!dbid) {
301                                                 EOUT << "dil2al: Unable to read " << idfile << " in select_TL_DIL_ref()\n";
302                                                 return String("");
303                                         }
304                                         affiliation.prepend("#");
305 #ifdef DEBUG
306                                         cout << "seeking " << affiliation << '\n';
307 #endif
308                                         if (find_line(&dbid,affiliation,lbuf,LLEN)) {
309                                                 affiliation = lbuf;
310                                                 affiliation.del(BigRegex("[^<]*[<]TD[^>]*[>][<]A[^>]*[Hh][Rr][Ee][Ff]=\""));
311                                                 affiliation = affiliation.before("\"");
312 #ifdef DEBUG
313                                         cout << "exists: " << affiliation << '\n';
314 #endif
315                                         } else {
316                                                 EOUT << "dil2al: DIL reference " << affiliation << " not found in " << idfile << '\n';
317                                                 affiliation = "";
318                                         }
319                                         dbid.close();
320                                 } else if (affiliation=="?") {
321                                         if (system(browser+" "+curAL)<0) EOUT << "dil2al: Unable to browse in select_TL_DIL_refs(), continuing\n";
322                                         affiliation = "";
323                                         ifstream drf(dilref);
324                                         if (drf) {
325                                                 if (find_line(&drf,"Current URL",lbuf,LLEN)) {
326                                                         String urlline = lbuf;
327                                                         drf.getline(lbuf,LLEN);
328                                                         if (lbuf[0]==' ') urlline += lbuf;
329                                                         urlline.del("Current URL");
330                                                         urlline.del("file://");
331                                                         urlline.gsub(" ","");
332                                                         urlline.del(basedir+RELLISTSDIR);
333                                                         if (useansi) cout << ANSI_BOLD_ON; // bold on
334                                                         cout << "Take `" << urlline << "' as DIL reference ID or identifying comment? (y/N)";
335                                                         if (useansi) cout << ANSI_BOLD_OFF; // bold off
336                                                         cin.getline(lbuf,LLEN);
337                                                         if ((lbuf[0]=='y') || (lbuf[0]=='Y')) affiliation=urlline;
338                                                 }
339                                                 drf.close();
340                                                 unlink(dilref);
341                                         }
342                                 } else if (affiliation=="?&") {
343                                         if (system("rxvt -e "+browser+" "+curAL+" &")<0) EOUT << "dil2al: Unable to spawn a browser in select_TL_DIL_refs(), continuing\n";
344                                         affiliation = "";
345                                 } else if (affiliation!="*") affiliation.prepend("!"); // else non-DIL identifying comment
346                         } else {
347                                 affiliation=diloptions[0].before(":");
348                                 if (!newchunk) affiliation.prepend("*"); // same as chunk DIL (no entry specific reference required)
349                         }
350                 }
351                 return affiliation;
352         } else {
353                 diloptions[0]=diloptions[0].before(":");
354                 if (!newchunk) diloptions[0].prepend("*");
355                 return diloptions[0];
356         }
357 }
bool send_dil_to_DIL (String dilfile)
Definition at line 477 of file diladmin.cc.
References add_new_to_DIL(), String::at(), backup_and_rename(), copy_until_line(), create_new_DIL(), String::del(), DIN, EOUT, generate_tag(), String::gsub(), String::index(), read_data_from_stream(), RELLISTSDIR, RX_Search_Safe(), BigRegex::sublen(), BigRegex::subpos(), substring_from_line(), and VOUT.
Referenced by dil2al_commands().
477                                      {
478         const int LLEN = 10240;
479         char lbuf[LLEN];
480         String dilid[2], dilfilename;
481         // read entry data into string buffer (to avoid confusion in case stdin and create file requests)
482         String dentrybuf;
483         if (verbose) VOUT << "Reading DIL entry content\n";
484         read_data_from_stream(DIN,dentrybuf,"@End of DIL entry@");
485         // get inline tag information and remove those inline tags
486         String supinfotag("DESUP"); supinfotag = RX_Search_Safe(generate_tag(supinfotag)); // get standardized tag
487         supinfotag.gsub(BigRegex(":[    ]*"),":[%_%]*\\(");
488         supinfotag.gsub(" ","[  ]+");
489         supinfotag.gsub("%_%","         ");
490         supinfotag.gsub("SUPid","[.0-9]+");
491         supinfotag.gsub(BigRegex("SI[^,)]*"),"[^,)]*");
492         supinfotag.gsub(BigRegex("\\(.\\)@"),"_1\\)@",'_');
493         BigRegex si(supinfotag); StringList supinfo; int supnum = 0;
494         while (dentrybuf.index(si)>=0) {
495                 supinfo[supnum] = dentrybuf.at(si.subpos(1),si.sublen(1)); // get superior id and information
496                 dentrybuf.del(si.subpos(0),si.sublen(0)); // remove tag
497                 supnum++;
498         }
499         // get name of DIL file regardless of whether it was a relative or absolute path
500         if (!substring_from_line("([^/]+)$",2,dilid,(const char *) dilfile)) {
501                 EOUT << "dil2al: Unable to parse name from DIL file path in send_dil_to_DIL()\n";
502                 return false;
503         } else dilfilename = dilid[1];
504         dilfile=basedir+RELLISTSDIR+dilfilename;
505         if (verbose) VOUT << "Sending DIL entry to " << dilfile << '\n';
506         ifstream df(dilfile);
507         if (!df) {
508                 // optionally create new DIL file
509                 cout << "DIL file " << dilfilename << " does not exist, create? (y/N) ";
510                 cin.getline(lbuf,LLEN);
511                 if ((lbuf[0]=='y') || (lbuf[0]=='Y')) {
512                         if (!create_new_DIL(dilfilename)) {
513                                 EOUT << "dil2al: Unable to create new DIL file " << dilfilename << " in send_dil_to_DIL()\n";
514                                 return false;
515                         }
516                         df.open(dilfile);
517                 } else return false;
518         }
519         if (df) {
520                 ofstream ndf(dilfile+".new");
521                 if (!ndf) {
522                         EOUT << "dil2al: Unable to create " << dilfile << ".new in send_dil_to_DIL()\n";
523                         return false;
524                 }
525                 if (verbose) VOUT << "Copying DIL to " << dilfile << ".new and adding new entry\n";
526                 // copy content up to bottom of DIL table
527                 if (copy_until_line(&df,&ndf,"[<]!-- *dil2al: *DIL *end *--[>]",lbuf,LLEN)<=0) {
528                         EOUT << "dil2al: End of DIL table ``<!-- dil2al: DIL end -->'' not found in send_dil_to_DIL()\n";
529                         return false;
530                 }
531                 // add new DIL content
532                 ndf << dentrybuf;
533                 // place end of DIL table marker
534                 ndf << lbuf << endl;
535                 // copy rest of DIL file
536                 ndf << df.rdbuf();
537                 df.close();
538                 ndf.close();
539         } else {
540                 EOUT << "dil2al: Unable to open new DIL file " << dilfilename << " in send_dil_to_DIL()\n";
541                 return false;
542         }
543         if (!backup_and_rename(dilfile,"DIL")) return false;
544         StringList * supinfoptr = NULL;
545         if (supinfo[0]!="") supinfoptr = &supinfo;
546         if (!add_new_to_DIL(dilfile,supinfoptr)) {
547                 EOUT << "dil2al: Unable to add new item from " << dilfile << " to DIL in send_dil_to_DIL()\n";
548                 return false;
549         }
550         return true;
551 }
void Set_Parameter (char * lbuf)
Definition at line 134 of file dil2al.cc.
References AAU_ASK, AAU_NO, AAU_YES, ACW_ASK, ACW_TIME, ACW_TL, alautoexpand, alautoupdate, alcumtimereqexcerptlength, alcurdayworkedstrategy, aldaydistfunc, ALDAYDISTFUNCLINEAR, ALDAYDISTFUNCSQUARED, aldaydistslope, alepshours, alfocused, algenall, algenregular, alshowcumulativereq, alsyncslack, alwide, alworkdaystart, askALDILref, askextractconcat, askprocesstype, followlinks, generatealtcs, hierarchyexcerptlength, hierarchymaxdepth, hierarchyplanparse, immediatesearchoutput, indexkeysnum, isdaemon, String::matches(), offercreate, pattern_in_line(), String::prepend(), quicknotedstnum, rapidscheduleupdating, remotesearch, reversehierarchy, searchprogressmeter, sectionsize, sectionstrategy, showflag, substring_from_line(), suggestnameref, targetdatepreferences, TCS_ASK, TCS_CURRENT, TCS_NEW, timechunkoverstrategy, timechunksize, timechunkslack, timechunkunderstrategy, TSS_ASK, TSS_CURRENT, TSS_NEW, UNIE_ASK, UNIE_NO, UNIE_YES, updatenoteineditor, useansi, usequickloadcache, wdworkendprefs, and work_end_preferences().
Referenced by dil2al_commands(), and initialize().
134                                 {
135         String confdefs[4];
136         // notetarget definitions
137         if (substring_from_line("^[     ]*notetarget[   ]*=[    ]*([^   ]+)[    ]*([^:]+)(.*)$",4,confdefs,lbuf)) {
138                 if (confdefs[1][0]!='/') confdefs[1].prepend(homedir);
139                 quicknotedst[quicknotedstnum]=confdefs[1];
140                 quicknotedsttitle[quicknotedstnum]=confdefs[2];
141                 quicknotedescr[quicknotedstnum]=confdefs[3];
142                 quicknotedstnum++;
143         }
144         // indexkey definitions
145         if (substring_from_line("^[     ]*indexkey[     ]*=[    ]*(.+)$",2,confdefs,lbuf)) {
146                 indexkeys[indexkeysnum]=confdefs[1];
147                 indexkeysnum++;
148         }
149         // preferred editor
150         if (substring_from_line("^[     ]*editor[       ]*=[    ]*(.+)$",2,confdefs,lbuf)) editor=confdefs[1];
151         // preferred browser
152         if (substring_from_line("^[     ]*browser[      ]*=[    ]*(.+)$",2,confdefs,lbuf)) browser=confdefs[1];
153         // default time chunk size
154         if (substring_from_line("^[     ]*timechunksize[        ]*=[    ]*(.+)$",2,confdefs,lbuf)) timechunksize=atoi((const char *) confdefs[1]);
155         // default time chunk slack
156         if (substring_from_line("^[     ]*timechunkslack[       ]*=[    ]*(.+)$",2,confdefs,lbuf)) timechunkslack=atoi((const char *) confdefs[1]);
157         // new decision strategy when time chunk is over timechunksize+timechunkslack
158         if (substring_from_line("^[     ]*timechunkoverstrategy[        ]*=[    ]*(.+)$",2,confdefs,lbuf)) {
159                 if (confdefs[1]=="TCS_CURRENT") timechunkoverstrategy=TCS_CURRENT;
160                 else if (confdefs[1]=="TCS_NEW") timechunkoverstrategy=TCS_NEW;
161                 else if (confdefs[1]=="TCS_ASK") timechunkoverstrategy=TCS_ASK;
162                 else if (confdefs[1].matches(BRXint)) {
163                         int q = atoi((const char *) confdefs[1]);
164                         if ((q==TCS_CURRENT) || (q==TCS_NEW) || (q==TCS_ASK)) timechunkoverstrategy=q;
165                 }
166         }
167         // new decision strategy when time chunk is under timechunksize
168         if (substring_from_line("^[     ]*timechunkunderstrategy[       ]*=[    ]*(.+)$",2,confdefs,lbuf)) {
169                 if (confdefs[1]=="TCS_CURRENT") timechunkunderstrategy=TCS_CURRENT;
170                 else if (confdefs[1]=="TCS_NEW") timechunkunderstrategy=TCS_NEW;
171                 else if (confdefs[1]=="TCS_ASK") timechunkunderstrategy=TCS_ASK;
172                 else if (confdefs[1].matches(BRXint)) {
173                         int q = atoi((const char *) confdefs[1]);
174                         if ((q==TCS_CURRENT) || (q==TCS_NEW) || (q==TCS_ASK)) timechunkunderstrategy=q;
175                 }
176         }
177         // new TL section decision strategy
178         if (substring_from_line("^[     ]*sectionstrategy[      ]*=[    ]*(.+)$",2,confdefs,lbuf)) {
179                 if (confdefs[1]=="TSS_CURRENT") sectionstrategy=TSS_CURRENT;
180                 else if (confdefs[1]=="TSS_NEW") sectionstrategy=TSS_NEW;
181                 else if (confdefs[1]=="TSS_ASK") sectionstrategy=TSS_ASK;
182                 else if (confdefs[1].matches(BRXint)) {
183                         int q = atoi((const char *) confdefs[1]);
184                         if ((q==TSS_CURRENT) || (q==TSS_NEW) || (q==TSS_ASK)) sectionstrategy=q;
185                 }
186         }
187         // update note in editor strategy
188         if (substring_from_line("^[     ]*updatenoteineditor[   ]*=[    ]*(.+)$",2,confdefs,lbuf)) {
189                 if (confdefs[1]=="UNIE_NO") updatenoteineditor=UNIE_NO;
190                 else if (confdefs[1]=="UNIE_YES") updatenoteineditor=UNIE_YES;
191                 else if (confdefs[1]=="UNIE_ASK") updatenoteineditor=UNIE_ASK;
192                 else if (confdefs[1].matches(BRXint)) {
193                         int q = atoi((const char *) confdefs[1]);
194                         if ((q==UNIE_NO) || (q==UNIE_YES) || (q==UNIE_ASK)) updatenoteineditor=q;
195                 }
196         }
197         // AL current work day time worked estimation strategy
198         if (substring_from_line("^[     ]*alcurdayworkedstrategy[       ]*=[    ]*(.+)$",2,confdefs,lbuf)) {
199                 if (confdefs[1]=="ACW_TIME") alcurdayworkedstrategy=ACW_TIME;
200                 else if (confdefs[1]=="ACW_TL") alcurdayworkedstrategy=ACW_TL;
201                 else if (confdefs[1]=="ACW_ASK") alcurdayworkedstrategy=ACW_ASK;
202                 else if (confdefs[1].matches(BRXint)) {
203                         int q = atoi((const char *) confdefs[1]);
204                         if ((q==ACW_TIME) || (q==ACW_TL) || (q==ACW_ASK)) alcurdayworkedstrategy=q;
205                 }
206         }
207         // automatically update AL and completion ratios strategy
208         if (substring_from_line("^[     ]*alautoupdate[         ]*=[    ]*(.+)$",2,confdefs,lbuf)) {
209                 if (confdefs[1]=="AAU_NO") alautoupdate=AAU_NO;
210                 else if (confdefs[1]=="AAU_YES") alautoupdate=AAU_YES;
211                 else if (confdefs[1]=="AAU_ASK") alautoupdate=AAU_ASK;
212                 else if (confdefs[1].matches(BRXint)) {
213                         int q = atoi((const char *) confdefs[1]);
214                         if ((q==AAU_NO) || (q==AAU_YES) || (q==AAU_ASK)) alautoupdate=q;
215                 }
216         }
217         // selected AL Day distribution function
218         if (substring_from_line("^[     ]*aldaydistfunc[        ]*=[    ]*(.+)$",2,confdefs,lbuf)) {
219                 if (confdefs[1]=="ALDAYDISTFUNCLINEAR") aldaydistfunc=ALDAYDISTFUNCLINEAR;
220                 else if (confdefs[1]=="ALDAYDISTFUNCSQUARED") aldaydistfunc=ALDAYDISTFUNCSQUARED;
221                 else if (confdefs[1].matches(BRXint)) {
222                         int q = atoi((const char *) confdefs[1]);
223                         if ((q==ALDAYDISTFUNCLINEAR) || (q==ALDAYDISTFUNCSQUARED)) aldaydistfunc=q;
224                 }
225         }
226         // update note in editor command line
227         if (substring_from_line("^[     ]*updatenoteineditorcmd[        ]*=[    ]*(.+)$",2,confdefs,lbuf)) updatenoteineditorcmd=confdefs[1];
228         // default TL section size
229         if (substring_from_line("^[     ]*sectionsize[  ]*=[    ]*(.+)$",2,confdefs,lbuf)) sectionsize=atoi((const char *) confdefs[1]);
230         // default number of AL TCs to generate
231         if (substring_from_line("^[     ]*generatealtcs[        ]*=[    ]*(.+)$",2,confdefs,lbuf)) generatealtcs=atol((const char *) confdefs[1]);
232         // default number of AL TCs to show in the shorter listing
233         if (substring_from_line("^[     ]*alfocused[    ]*=[    ]*(.+)$",2,confdefs,lbuf)) alfocused=atoi((const char *) confdefs[1]);
234         // default number of AL TCs to show in the longer listing
235         if (substring_from_line("^[     ]*alwide[       ]*=[    ]*(.+)$",2,confdefs,lbuf)) alwide=atoi((const char *) confdefs[1]);
236         // default number of hours in a regular AL-day
237         if (substring_from_line("^[     ]*algenregular[         ]*=[    ]*(.+)$",2,confdefs,lbuf)) algenregular=atoi((const char *) confdefs[1]);
238         // default number of hours in an AL-day for an AL with all DIL-entries
239         if (substring_from_line("^[     ]*algenall[     ]*=[    ]*(.+)$",2,confdefs,lbuf)) algenall=atoi((const char *) confdefs[1]);
240         // assumed available hours per day for EPS scheduling method
241         if (substring_from_line("^[     ]*alepshours[   ]*=[    ]*(.+)$",2,confdefs,lbuf)) alepshours=atof((const char *) confdefs[1]);
242         // default standard start time of work on a regular work day (seconds since midnight)
243         if (substring_from_line("^[     ]*alworkdaystart[       ]*=[    ]*(.+)$",2,confdefs,lbuf)) alworkdaystart=atol((const char *) confdefs[1]);
244         // default allowable desynchronization between AL suggested start and current time in seconds
245         if (substring_from_line("^[     ]*alsyncslack[  ]*=[    ]*(.+)$",2,confdefs,lbuf)) alsyncslack=atol((const char *) confdefs[1]);
246         // default slope of AL Day distribution
247         if (substring_from_line("^[     ]*aldaydistslope[       ]*=[    ]*(.+)$",2,confdefs,lbuf)) aldaydistslope=atof((const char *) confdefs[1]);
248         // command used to set up an at-job
249         if (substring_from_line("^[     ]*atcommand[    ]*=[    ]*(.+)$",2,confdefs,lbuf)) atcommand=confdefs[1];
250         // default depth to follow links in a search
251         if (substring_from_line("^[     ]*followlinks[  ]*=[    ]*(.+)$",2,confdefs,lbuf)) followlinks=atoi((const char *) confdefs[1]);
252         // HTML form interface
253         if (substring_from_line("^[     ]*htmlforminterface[    ]*=[    ]*(.+)$",2,confdefs,lbuf)) htmlforminterface=confdefs[1];
254         // HTML form method
255         if (substring_from_line("^[     ]*htmlformmethod[       ]*=[    ]*(.+)$",2,confdefs,lbuf)) htmlformmethod=confdefs[1];
256         // default length of text excerpt from DIL entry in row of Comulative Time Required form
257         if (substring_from_line("^[     ]*alcumtimereqexcerptlength[    ]*=[    ]*(.+)$",2,confdefs,lbuf)) alcumtimereqexcerptlength=atoi((const char *) confdefs[1]);
258         // default depth of DIL hierarchy
259         if (substring_from_line("^[     ]*hierarchymaxdepth[    ]*=[    ]*(.+)$",2,confdefs,lbuf)) hierarchymaxdepth=atoi((const char *) confdefs[1]);
260         // default length of text excerpt from DIL entry in row of DIL hierarchy
261         if (substring_from_line("^[     ]*hierarchyexcerptlength[       ]*=[    ]*(.+)$",2,confdefs,lbuf)) hierarchyexcerptlength=atoi((const char *) confdefs[1]);
262         // automatically expand number of hours per day as necessary
263         if (pattern_in_line("^[         ]*alautoexpand[         ]*",lbuf)) alautoexpand=true;
264         if (pattern_in_line("^[         ]*noalautoexpand[       ]*",lbuf)) alautoexpand=false;
265         // scheduled controller call at-job command line
266         if (substring_from_line("^[     ]*atcontroller[         ]*=[    ]*(.+)$",2,confdefs,lbuf)) atcontroller=confdefs[1];
267         if (pattern_in_line("^[         ]*suggestnameref[       ]*",lbuf)) suggestnameref=true;
268         if (pattern_in_line("^[         ]*askprocesstype[       ]*",lbuf)) askprocesstype=true;
269         if (pattern_in_line("^[         ]*offercreate[  ]*",lbuf)) offercreate=true;
270         if (pattern_in_line("^[         ]*askALDILref[  ]*",lbuf)) askALDILref=true;
271         if (pattern_in_line("^[         ]*showflag[     ]*",lbuf)) showflag=true;
272         if (substring_from_line("^[     ]*flagcmd[      ]*=[    ]*(.+)$",2,confdefs,lbuf)) flagcmd=confdefs[1];
273         if (pattern_in_line("^[         ]*noshowflag[   ]*",lbuf)) showflag=false;
274         if (pattern_in_line("^[         ]*isdaemon[     ]*",lbuf)) isdaemon=true;
275         if (pattern_in_line("^[         ]*useansi[      ]*",lbuf)) useansi=true;
276         if (pattern_in_line("^[         ]*nouseansi[    ]*",lbuf)) useansi=false;
277         if (pattern_in_line("^[         ]*askextractconcat[     ]*",lbuf)) askextractconcat=true;
278         if (pattern_in_line("^[         ]*noaskextractconcat[   ]*",lbuf)) askextractconcat=false;
279         if (pattern_in_line("^[         ]*searchprogressmeter[  ]*",lbuf)) searchprogressmeter=true;
280         if (pattern_in_line("^[         ]*nosearchprogressmeter[        ]*",lbuf)) searchprogressmeter=false;
281         if (pattern_in_line("^[         ]*immediatesearchoutput[        ]*",lbuf)) immediatesearchoutput=true;
282         if (pattern_in_line("^[         ]*noimmediatesearchoutput[      ]*",lbuf)) immediatesearchoutput=false;
283         if (pattern_in_line("^[         ]*remotesearch[         ]*",lbuf)) remotesearch=true;
284         if (pattern_in_line("^[         ]*noremotesearch[       ]*",lbuf)) remotesearch=false;
285         if (pattern_in_line("^[         ]*alshowcumulativereq[  ]*",lbuf)) alshowcumulativereq=true;
286         if (pattern_in_line("^[         ]*noalshowcumulativereq[        ]*",lbuf)) alshowcumulativereq=false;
287         if (pattern_in_line("^[         ]*rapidscheduleupdating[        ]*",lbuf)) rapidscheduleupdating=true;
288         if (pattern_in_line("^[         ]*norapidscheduleupdating[      ]*",lbuf)) rapidscheduleupdating=false;
289         if (pattern_in_line("^[         ]*targetdatepreferences[        ]*",lbuf)) targetdatepreferences=true;
290         if (pattern_in_line("^[         ]*notargetdatepreferences[      ]*",lbuf)) targetdatepreferences=false;
291         // the following seven parameters detected set preferred times for each day of the week at which the work day ends (used in the RSU method)
292         if (substring_from_line("^[     ]*sundayendwork[        ]*=[    ]*(.+)$",2,confdefs,lbuf)) wdworkendprefs[0] = work_end_preferences(confdefs[1]);
293         if (substring_from_line("^[     ]*mondayendwork[        ]*=[    ]*(.+)$",2,confdefs,lbuf)) wdworkendprefs[1] = work_end_preferences(confdefs[1]);
294         if (substring_from_line("^[     ]*tuesdayendwork[       ]*=[    ]*(.+)$",2,confdefs,lbuf)) wdworkendprefs[2] = work_end_preferences(confdefs[1]);
295         if (substring_from_line("^[     ]*wednesdayendwork[     ]*=[    ]*(.+)$",2,confdefs,lbuf)) wdworkendprefs[3] = work_end_preferences(confdefs[1]);
296         if (substring_from_line("^[     ]*thursdayendwork[      ]*=[    ]*(.+)$",2,confdefs,lbuf)) wdworkendprefs[4] = work_end_preferences(confdefs[1]);
297         if (substring_from_line("^[     ]*fridayendwork[        ]*=[    ]*(.+)$",2,confdefs,lbuf)) wdworkendprefs[5] = work_end_preferences(confdefs[1]);
298         if (substring_from_line("^[     ]*saturdayendwork[      ]*=[    ]*(.+)$",2,confdefs,lbuf)) wdworkendprefs[6] = work_end_preferences(confdefs[1]);
299         if (pattern_in_line("^[         ]*usequickloadcache[    ]*",lbuf)) usequickloadcache=true;
300         if (pattern_in_line("^[         ]*nousequickloadcache[  ]*",lbuf)) usequickloadcache=false;
301         if (pattern_in_line("^[         ]*reversehierarchy[     ]*",lbuf)) reversehierarchy=true;
302         if (pattern_in_line("^[         ]*noreversehierarchy[   ]*",lbuf)) reversehierarchy=false;
303         if (pattern_in_line("^[         ]*hierarchyplanparse[   ]*",lbuf)) hierarchyplanparse=true;
304         if (pattern_in_line("^[         ]*nohierarchyplanparse[         ]*",lbuf)) hierarchyplanparse=false;
305 }
void Show_DIL_Hierarchy (DIL_entry * topde, DIL_Visualize & dv, const int maxdepth, int depth = 0, double likelihood = DILSUPS_REL_UNSPECIFIED)
Definition at line 1388 of file diladmin.cc.
References DIL_Visualize::Attach_Level_Data(), DIL_ID::chars(), DIL_Visualize::Detach_Level_Data(), DILSUPS_REL_UNSPECIFIED, EOUT, DIL_Visualize::get_cumlikelihood(), PLLHandle< DIL_entry >::head(), DIL_Visualize::ldroot, PLLRoot< DIL_Hierarchy_Level_Data >::link_before(), PLL_LOOP_FORWARD, DIL_entry::Projects(), DIL_Visualize::set_cumlikelihood(), DIL_Visualize::Visualize_Element(), and DIL_Visualize::Visualize_NotShown().
Referenced by Tabbed_DIL_Hierarchy(), Tabbed_FORM_DIL_Hierarchy(), Tabbed_FORM_DIL_Hierarchy_full(), and Tabbed_HTML_DIL_Hierarchy().
1388                                                                                                                                                {
1389 // create a visual representation of a DIL hierarchy from a DIL entry
1390 // topde must be part of a valid Detailed_Items_List or at least part
1391 // of a valid PLLHandle<DIL_entry> list.
1392 #ifdef DEBUG_PLAN_ENTRY
1393   EOUT << "Show " << topde->chars() << '\n'; EOUT.flush();
1394 #endif
1395   DIL_Hierarchy_Level_Data ld(*topde,likelihood);
1396   dv.ldroot.link_before(&ld); // link into list of level data in this depth first process
1397   dv.Attach_Level_Data(ld);
1398   dv.Visualize_Element(topde,depth);
1399   dv.Detach_Level_Data();
1400   depth++;
1401   int numdependencies = 0; double thislevelcumlikelihood = dv.get_cumlikelihood();
1402   if (reversehierarchy) {
1403     DIL_AL_List * topdeproj = topde->Projects(0);
1404     if (topdeproj) PLL_LOOP_FORWARD(DIL_AL_List,topdeproj,1) if (!(e->Superiorbyid()==topde)) {
1405       if (maxdepth>=depth) {
1406         dv.set_cumlikelihood(thislevelcumlikelihood);
1407         Show_DIL_Hierarchy(e->Superiorbyid(),dv,maxdepth,depth,e->PLAN_OUTCOME_LIKELIHOOD);
1408       } else numdependencies++;
1409     }
1410   } else {
1411     PLL_LOOP_FORWARD(DIL_entry,topde->head(),1) if (e->Is_Direct_Dependency_Of(topde)) {
1412       if (maxdepth>=depth) Show_DIL_Hierarchy(e,dv,maxdepth,depth);
1413       else numdependencies++;
1414     }
1415   }
1416   // the following is used to convey benefit/risk information for PLAN
1417   // entries and if maxdepth was reached and there are further dependencies
1418   dv.Attach_Level_Data(ld);
1419   dv.Visualize_NotShown(numdependencies,depth);
1420   dv.Detach_Level_Data();
1421   // ld is automatically removed from list of level data in this depth first process
1422 }
void stop_TL_chunk (String & tl)
Definition at line 117 of file tladmin.cc.
References AAU_ASK, AAU_NO, String::after(), String::before(), confirmation(), EOUT, generate_AL(), get_most_recent_TC_AL(), get_most_recent_TC_DE(), String::gsub(), locate_most_recent_TL_chunk(), String::matches(), remove_AL_TC(), Detailed_Items_List::Sort_by_Target_Date(), time_stamp_diff(), update_DIL_entry_elements(), and VOUT.
Referenced by add_TL_chunk_or_entry(), add_TL_section(), and chunk_controller().
117                                 {
118 // Mark the completion time of a Task Log chunk if there is one open
119 // AL options determine if and how the current AL and closed chunk's
120 // DIL entry should be updated, and the corresponding update is done.
121         if (tl.gsub(BigRegex("[<]!--[   ]+chunk End[    ]+--[>][        ]*[<]/TD[>][    ]*[<]/TR[>]"),"<!-- chunk End --><I>"+curtime+"</I></TD></TR>")<=0) return;
122         // determine if AL anc completion ratios should be updated automatically
123         if (alautoupdate==AAU_NO) return;
124         if (alautoupdate==AAU_ASK) if (confirmation("Update AL and completion ratios? (y/N) ",'y')) return;
125         // obtain AL and DIL information from the most recent chunk
126         String chunkid; int lasttlchunk;
127         if ((lasttlchunk = locate_most_recent_TL_chunk(tl,-1,&chunkid))>=0) {
128                 bool recomputeAL = false;
129                 String curAL = get_most_recent_TC_AL(tl);
130                 String curDE = get_most_recent_TC_DE(tl);
131                 // a proper DIL entry ID is returned in the form:
132                 // some-DIL-file.html#XXXXXXXXXXXXXX.Y:DIL-title-and-entry-ID
133                 curDE = curDE.before(':'); curDE = curDE.after('#');
134                 if (curDE.matches(BRXdouble)) {
135                         time_t tdiff = time_stamp_diff(chunkid,curtime);
136 // *** suggest tdiff, but allow entry of other time, in which
137 //     case request if required time and completion status should
138 //     be modified directly
139 // *** if tdiff > taskchunksize*1.25 recompute AL... this test
140 //     may not be necessary, since any significant delay will
141 //     cause desynchronization between the updated suggested
142 //     start time in the AL and the current time, which causes
143 //     recomputation of the AL when a significant difference is
144 //     detected in select_TL_DIL_refs()
145                         if (!update_DIL_entry_elements(curDE,0.0,false,0.0,true,0.0,false,tdiff)) recomputeAL = true;
146                         if (!remove_AL_TC(curAL,curDE)) recomputeAL = true;
147                 } else {
148                         VOUT << "Completed task chunk was not a DIL entry\n";
149                         recomputeAL = true;
150                 }
151                 if (recomputeAL) { // recompute the AL
152                         VOUT << "Recomputing AL\n";
153                         Detailed_Items_List dilist;
154                         DIL_entry ** dep = dilist.Sort_by_Target_Date(true);
155                         if (!generate_AL(dep)) EOUT << "dil2al: Unable to generate AL in stop_TL_chunk(), continuing as is\n";
156                         delete[] dep;
157                 }
158         } else EOUT << "dil2al: Unable to update AL and DIL entry in stop_TL_chunk(), continuing\n";
159 }
bool substring_from_line (const char * pattern, int nsub, String * dilid, const char * lbuf)
Definition at line 2180 of file utilities.cc.
References EOUT.
Referenced by add_new_to_DIL(), create_new_DIL(), send_dil_to_DIL(), and Set_Parameter().
2180                                                                                             {
2181         const int SLEN = 1024;
2182         char sbuf[SLEN];
2183         regex_t re;
2184         regmatch_t * rm;
2185         int mres;
2186         if (nsub) {
2187                 if (regcomp(&re,pattern, REG_EXTENDED) != 0) {
2188                         EOUT << "dil2al: Unable to compile regular expression in substring_from_line()\n";
2189                         return false;
2190                 }
2191                 rm = new regmatch_t[nsub];
2192                 mres = regexec(&re,lbuf, (size_t) nsub, rm, 0);
2193                 if ((mres != 0) && (mres != REG_NOMATCH)) {
2194                         EOUT << "dil2al: Internal error while matching in substring_from_line()\n";
2195                 } else {
2196                         if (!mres) {
2197                                 if (rm[nsub-1].rm_so==-1) {
2198                                         EOUT << "dil2al: Wrong number of substring matches in substring_from_line()\n";
2199                                         mres = 3;
2200                                 } else {
2201                                         for (int i=0; i<nsub; i++) {
2202                                                 strncpy(sbuf,&lbuf[rm[i].rm_so],rm[i].rm_eo-rm[i].rm_so);
2203                                                 sbuf[rm[i].rm_eo-rm[i].rm_so]='\0';
2204                                                 dilid[i] = sbuf;
2205                                         }
2206                                 }
2207                         }
2208                 }
2209                 delete[] rm;
2210                 return (mres==0);
2211         } else {
2212                 EOUT << "dil2al: nsub==0 in substring_from_line()\n";
2213                 return false;
2214         }
2215 }
String Tabbed_DIL_Hierarchy (String dilidstr, int maxdepth = 50)
Definition at line 1424 of file diladmin.cc.
References String::after(), String::before(), DIL_entry::elbyid(), String::empty(), EOUT, Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), Detailed_Items_List::Get_All_Topical_DIL_Parameters(), PLLRoot< DIL_entry >::head(), Detailed_Items_List::list, DIL_Visualize_with_Tabs::Output(), DIL_Visualize_with_Tabs::Output_Content(), Show_DIL_Hierarchy(), DIL_ID::valid(), and write_file_from_String().
Referenced by DIL_Hierarchy_cmd().
1424                                                                 {
1425 // visualize a DIL hierarchy starting at dilid with tabs indicating depth
1426         DIL_Visualize_with_Tabs dv;
1427         // 3. Get optional expressions that must occur in DIL entry content text
1428         String expressions(dilidstr.after('#'));
1429         if (!expressions.empty()) dilidstr = dilidstr.before('#');
1430         // 4. Get optional ContentFile reference
1431         String contentfile(dilidstr.after('c'));
1432         if (!contentfile.empty()) dilidstr = dilidstr.before('c');
1433         DIL_ID dilid(dilidstr);
1434         if (!dilid.valid()) return String("");
1435         Detailed_Items_List dilist;
1436         dilist.Get_All_DIL_ID_File_Parameters();
1437         if (!contentfile.empty()) dilist.Get_All_Topical_DIL_Parameters(true);
1438         if (dilist.list.head()) Show_DIL_Hierarchy(dilist.list.head()->elbyid(dilid),dv,maxdepth);
1439         if (!contentfile.empty()) if (!write_file_from_String(contentfile,dv.Output_Content(),"DIL Hierarchy Content")) EOUT << "dil2al: Unable to write " << contentfile << "in Tabbed_DIL_Hierarchy(), continuing as is\n";
1440         return dv.Output();
1441 }
String Tabbed_FORM_DIL_Hierarchy (String dilidstr, int maxdepth = 50)
Definition at line 1488 of file diladmin.cc.
References String::after(), DIL_Visualize_with_FORM_Tabs::Append(), String::before(), DIL_entry::elbyid(), String::empty(), EOUT, Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), Detailed_Items_List::Get_All_Topical_DIL_Parameters(), PLLRoot< DIL_entry >::head(), StringList::length(), Detailed_Items_List::list, DIL_Visualize_with_FORM_Tabs::Output(), DIL_Visualize_with_FORM_Tabs::Output_Content(), Show_DIL_Hierarchy(), Tabbed_FORM_DIL_Hierarchy_full(), DIL_ID::valid(), VOUT, and write_file_from_String().
Referenced by DIL_Hierarchy_cmd().
1488                                                                      {
1489 // Visualize a DIL hierarchy starting at dilid with tabs indicating depth
1490 // including HREFs and other HTML code, while HTML head and tail code are
1491 // left to the content in which the extracted hierarchy is embedded.
1492 // A comment is included that enables commenting out of process output simply
1493 // by appending "<!-- " to the head code.
1494 // Note that since standard output does not know which file the text may
1495 // be embedded in, HREF file references are absolute. Post-processing may
1496 // convert those to relative references.
1497 // This output presents FORM check boxes and a "submit" button that extracts
1498 // checked DIL IDs with the aid of dil2al form processing.
1499 // There is also a "new hierarchy" button that uses the checked boxes as
1500 // the top items in new hierarchies to visualize.
1501 #ifdef DEBUG_HIERARCHY_EXPRESSIONS
1502   VOUT << "&&& Tabbed_FORM_DIL_Hierarchy: dilidstr = " << dilidstr << '\n';
1503 #endif
1504   DIL_Visualize_with_FORM_Tabs dv;
1505   // 3. Get optional expressions that must occur in DIL entry content text
1506   String expressions(dilidstr.after('#'));
1507   if (!expressions.empty()) dilidstr = dilidstr.before('#');
1508   // 4. Get optional ContentFile reference
1509   String contentfile(dilidstr.after('c'));
1510   if (!contentfile.empty()) dilidstr = dilidstr.before('c');
1511   // dilidstr may now contain no, one or several DIL IDs
1512   Detailed_Items_List dilist;
1513   dilist.Get_All_DIL_ID_File_Parameters();
1514   dilist.Get_All_Topical_DIL_Parameters(true); // always get for FORM hierarchy
1515   if (!dilist.list.head()) return String("");
1516   if (dilidstr.empty()) { // full hierarchy
1517     VOUT << "No specific DIL ID, creating full hierarchy\n";
1518     // *** Is implemented in ~/doc/html/lists.html: maxdepth = 5; // reduced depth for full hierarchy
1519     Tabbed_FORM_DIL_Hierarchy_full(dilist,dv,maxdepth,expressions);
1520   } else {
1521         StringList dilidlist(dilidstr,'+'); int dilidnum = dilidlist.length();
1522         DIL_ID dilid;
1523         for (int i = 0; i<dilidnum; i++) {
1524                 dilid = dilidlist[i];
1525                 if (dilid.valid()) {
1526                         Show_DIL_Hierarchy(dilist.list.head()->elbyid(dilid),dv,maxdepth);
1527                         dv.Append("<HR>\n");
1528                 }
1529         }
1530         if (!expressions.empty()) Tabbed_FORM_DIL_Hierarchy_full(dilist,dv,maxdepth,expressions);
1531   }
1532   if (!contentfile.empty()) if (!write_file_from_String(contentfile,dv.Output_Content(),"DIL Hierarchy Content")) EOUT << "dil2al: Unable to write " << contentfile << "in Tabbed_HTML_DIL_Hierarchy(), continuing as is\n";
1533   // prepare the FORM output
1534   String formoutputstr("<!-- comment out process output --><B>Maximum Depth = ");
1535   formoutputstr += String((long) maxdepth)+"</B>\n<FORM METHOD=\"GET\" ACTION=\"/cgi-bin/dil2al\"><INPUT type=\"hidden\" name=\"dil2al\" value=\"D\">\n<PRE>\n"+dv.Output()+"</PRE>\n<P>\n<INPUT type=\"radio\" name=\"processcmd\" value=\"extract\"> Extract\n<BR><INPUT type=\"radio\" name=\"processcmd\" value=\"newhierarchy\" checked> New Hierarchy with depth: <INPUT type=\"text\" name=\"maxdepth\" value=\"" + String((long) maxdepth) + "\" maxlength=5> and excerpt length: <INPUT type=\"text\" name=\"setpar__EQ__hierarchyexcerptlength\" value=\""+String((long) hierarchyexcerptlength)+"\" maxlength=5> <INPUT type=\"radio\" name=\"setpar\" value=\"noreversehierarchy\"";
1536   if (!reversehierarchy) formoutputstr += " checked";
1537   formoutputstr += "> top-down <INPUT type=\"radio\" name=\"setpar\" value=\"reversehierarchy hierarchyplanparse\"";
1538   if (reversehierarchy) formoutputstr += " checked";
1539   formoutputstr += "> bottom-up <INPUT type=\"checkbox\" name=\"expressions\" value=\"%40begin%3A%20PLAN%20DIL%20TEMPLATE\"";
1540   if (!expressions.empty()) formoutputstr += " checked";
1541   formoutputstr += "> PLAN entries only\n<BR><INPUT type=\"submit\" value=\"Process\"> <INPUT type=\"reset\"></FORM>\n";
1542   return formoutputstr;
1543 }
String Tabbed_HTML_DIL_Hierarchy (String dilidstr, int maxdepth = 50)
Definition at line 1443 of file diladmin.cc.
References String::after(), String::before(), DIL_entry::elbyid(), String::empty(), EOUT, Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), Detailed_Items_List::Get_All_Topical_DIL_Parameters(), PLLRoot< DIL_entry >::head(), Detailed_Items_List::list, DIL_Visualize_with_HTML_Tabs::Output(), DIL_Visualize_with_HTML_Tabs::Output_Content(), Show_DIL_Hierarchy(), DIL_ID::valid(), and write_file_from_String().
Referenced by DIL_Hierarchy_cmd().
1443                                                                      {
1444 // visualize a DIL hierarchy starting at dilid with tabs indicating depth
1445 // including HREFs and other HTML code, while HTML head and tail code are
1446 // left to the content in which the extracted hierarchy is embedded
1447 // Note that since standard output does not know which file the text may
1448 // be embedded in, HREF file references are absolute. Post-processing may
1449 // convert those to relative references.
1450         DIL_Visualize_with_HTML_Tabs dv;
1451         // 3. Get optional expressions that must occur in DIL entry content text
1452         String expressions(dilidstr.after('#'));
1453         if (!expressions.empty()) dilidstr = dilidstr.before('#');
1454         // 4. Get optional ContentFile reference
1455         String contentfile(dilidstr.after('c'));
1456         if (!contentfile.empty()) dilidstr = dilidstr.before('c');
1457         DIL_ID dilid(dilidstr);
1458         if (!dilid.valid()) return String("");
1459         Detailed_Items_List dilist;
1460         dilist.Get_All_DIL_ID_File_Parameters();
1461         if (!contentfile.empty()) dilist.Get_All_Topical_DIL_Parameters(true);
1462         if (dilist.list.head()) Show_DIL_Hierarchy(dilist.list.head()->elbyid(dilid),dv,maxdepth);
1463         if (!contentfile.empty()) if (!write_file_from_String(contentfile,dv.Output_Content(),"DIL Hierarchy Content")) EOUT << "dil2al: Unable to write " << contentfile << "in Tabbed_HTML_DIL_Hierarchy(), continuing as is\n";
1464         return "<PRE>\n"+dv.Output()+"</PRE>\n";
1465 }
void TeX_format_corrections (String & ostrtext, bool estimate = false)
Definition at line 307 of file ppfilter.cc.
References String::at(), String::before(), String::elem(), String::from(), String::gsub(), String::index(), String::length(), String::matches(), RX_Search_Safe(), String::SEARCH_END, String::sub(), BigRegex::sublen(), BigRegex::subpos(), TeX_get_argument(), TeX_get_command(), TeX_get_scope(), and VOUT.
Referenced by extract_paper_plan_to_paper().
307                                                                       {
308 // corrections applied to a generated TeX text
309 // rather than assuming a plain text source as above, this function assumes
310 // a TeX draft
311         const BigRegex TeXerr_refrx("\\\\\\\(ref\\|cite\\)\\([{]\\)[^}]*\\([{\\]\\)");
312         const BigRegex TeXnon_refrx("[^-0-9A-Za-z:._+]");
313         const BigRegex TeXnon_citerx("[^-0-9A-Za-z:._+,]");
314         const BigRegex TeXerr_reflblrx("\\\\ref[{]\\([^}]*[^-0-9A-Za-z:._+}][^}]*\\)[}]");
315         const BigRegex TeXerr_citelblrx("\\\\cite[{]\\([^}]*[^-0-9A-Za-z:._+,}][^}]*\\)[}]");
316         const BigRegex TeXfighererx("\\\\[A-za-z]*figurehere");
317         int i,j,k; String movestr, reststr;
318         // a) \ref{ \command[]{}{} } or \ref{ {  } } or \cite{ \command[]{}{} } or \cite{ {  } }
319         while ((i=ostrtext.index(TeXerr_refrx))>=0) { // iteratively applied to the whole text
320                 if ((k=TeX_get_command(ostrtext,i,reststr))>=0) {
321                         switch (ostrtext.elem(TeXerr_refrx.subpos(3))) {
322                                 case '\\': // move interfering command after \ref{} or \cite{}
323                                         if ((j=TeX_get_command(ostrtext,TeXerr_refrx.subpos(3),movestr))>=0) {
324                                                 reststr = ostrtext.at(j,k-j)+movestr+ostrtext.from(k);
325                                                 ostrtext = ostrtext.before(TeXerr_refrx.subpos(3));
326                                                 ostrtext += reststr;
327                                                 if (verbose) VOUT << "TeX Correction: Moved TeX command out of " << String(ostrtext.at(i,(k-movestr.length())-i)) << '\n';
328                                         } else { // loose `\'
329                                                 ostrtext[TeXerr_refrx.subpos(3)] = '-';
330                                                 if (verbose) VOUT << "TeX Correction: Changed `\\' to `-' in " << String(ostrtext.at(i,k-i)) << '\n';
331                                         }
332                                         break;
333                                 case '{': // move interfereing scope after \ref{} or \cite{}
334                                         if ((j=TeX_get_scope(ostrtext,TeXerr_refrx.subpos(3),movestr))>=0) {
335                                                 reststr = ostrtext.at(j,k-j)+'{'+movestr+'}'+ostrtext.from(k);
336                                                 ostrtext = ostrtext.before(TeXerr_refrx.subpos(3));
337                                                 ostrtext += reststr;
338                                                 if (verbose) VOUT << "TeX Correction: Moved TeX scope out of " << String(ostrtext.at(i,(k-(movestr.length()+2))-i)) << '\n';
339                                         } else { // loose `{'
340                                                 ostrtext[TeXerr_refrx.subpos(3)] = '+';
341                                                 if (verbose) VOUT << "TeX Correction: Changed `{' to `+' in " << String(ostrtext.at(i,k-i)) << '\n';
342                                         }
343                                         break;
344                         }
345                 } else { // missing `}'
346                         if ((j=ostrtext.index(TeXnon_refrx,TeXerr_refrx.subpos(2)+1))>=0) {
347                                 reststr = ostrtext.from(j);
348                                 ostrtext = ostrtext.before(j);
349                                 ostrtext += '}' + reststr;
350                         } else ostrtext += '}';
351                         if (verbose) VOUT << "TeX Correction: Added missing } for " << String(ostrtext.at(i,j-i)) << '\n';
352                 }
353         }
354         // b) \ref{ non-label-characters }
355         i = 0;
356         while ((i=ostrtext.index(TeXerr_reflblrx,i))>=0) { // single pass
357                 movestr = ostrtext.sub(TeXerr_reflblrx,1);
358                 movestr.gsub(TeXnon_refrx,"X");
359                 if (verbose) VOUT << "TeX Correction: Changed non-label characters to `X' in \\ref{" << movestr << "}\n";
360                 if (estimate) { // attempt to estimate the intended reference label
361                         j = 0; String argstr;
362                         while ((j=ostrtext.index(TeXfighererx,String::SEARCH_END,j))>=0) {
363                                 if ((k=TeX_get_argument(ostrtext,j,argstr,'{'))>=0) {
364                                         if ((k=TeX_get_argument(ostrtext,k,argstr,'{'))>=0) {
365                                                 if (movestr.matches(BigRegex("X*"+RX_Search_Safe(argstr)+"X*"))) {
366                                                         if (verbose) VOUT << "TeX Correction: Assuming that \\ref{" << movestr << "} actually refers to ``" << argstr << "''\n";
367                                                         movestr = argstr;
368                                                         break;
369                                                 }
370                                                 j = k;
371                                         }
372                                 }
373                         }
374                         
375                 }
376                 ostrtext.at(TeXerr_reflblrx.subpos(1),TeXerr_reflblrx.sublen(1)) = movestr;
377         }
378         // c) \cite{ non-label-characters }
379         // *** can compare with all known bibliography keys
380         i = 0;
381         while ((i=ostrtext.index(TeXerr_citelblrx,i))>=0) { // single pass
382                 movestr = ostrtext.sub(TeXerr_citelblrx,1);
383                 movestr.gsub(TeXnon_citerx,"X");
384                 if (verbose) VOUT << "TeX Correction: Changed non-label characters to `X' in \\cite{" << movestr << "}\n";
385                 ostrtext.at(TeXerr_citelblrx.subpos(1),TeXerr_citelblrx.sublen(1)) = movestr;
386         }
387 }
int TeX_get_argument (String & textstr, int start, String & argstr, char argtype, int * argstart = NULL)
Definition at line 218 of file ppfilter.cc.
References String::elem(), String::index(), and TeX_get_scope().
Referenced by TeX_format_corrections(), TeX_get_command(), and TeX_safe_text().
218                                                                                                         {
219 // get argument text between argtype brackets after start
220 // returns location after closing bracket or -1 if there is no such argument
221 // white space characters may precede the opening bracket
222         const BigRegex nonwsrx("[^ \n\t\r\v\f]");
223         if ((start=textstr.index(nonwsrx,start))<0) return -1;
224         if (textstr.elem(start)!=argtype) return -1;
225         if (argstart) *argstart = start;
226         return TeX_get_scope(textstr,start,argstr);
227 }
int TeX_get_command (String & textstr, int start, String & cmdstr)
Definition at line 229 of file ppfilter.cc.
References String::at(), String::matches(), BigRegex::sublen(), BigRegex::subpos(), and TeX_get_argument().
Referenced by extract_paper_plan_to_paper(), and TeX_format_corrections().
229                                                                   {
230 // get command and arguments text (\command[]{}{}{}{}{}{}{}{}) at start
231 // returns location
232 // *** if you need function that find commands or other chunks after rather than
233 //     at a certain location, in the same manner as the HTML utilities, then
234 //     either add a paramter that controls such an option, or create wrapper
235 //     functions that search for a chunk and then call these functions
236         const BigRegex TeXcmd("\\(\\\\[A-Za-z]+\\).*"); // TeX command identifier
237         if (!textstr.matches(TeXcmd,start)) return -1;
238         // get command
239         int cend = TeXcmd.subpos(1)+TeXcmd.sublen(1);
240         String argstr; int argstart, j, argsleft = 9;
241         // find possible optional argument
242         if ((j=TeX_get_argument(textstr,cend,argstr,'['))>=0) {
243                 cend = j; argsleft--;
244         }
245         // find and convert possible mandatory arguments
246         while ((argsleft>0) && ((j=TeX_get_argument(textstr,cend,argstr,'{'))>=0)) {
247                 cend = j; argsleft--;
248         }
249         cmdstr = textstr.at(start,cend-start);
250         return cend;
251 }
int TeX_get_scope (String & textstr, int start, String & scopecontent)
Definition at line 195 of file ppfilter.cc.
References String::at(), String::elem(), and String::index().
Referenced by TeX_format_corrections(), TeX_get_argument(), and TeX_safe_text().
195                                                                       {
196 // get the text between brackets starting at start
197 // returns location after closing bracket or -1 if there is no closing bracket
198         const BigRegex brck1rx("[\\{\\}]"); // \\{ rather than { because of regex-gnu.h/BigRegex.hh setting
199         const BigRegex brck2rx("[][]");
200         const BigRegex brck3rx("[()]");
201         const BigRegex * brckrx;
202         char bracket = textstr.elem(start);
203         switch (bracket) {
204                 case '{': brckrx = &brck1rx; break;
205                 case '[': brckrx = &brck2rx; break;
206                 case '(': brckrx = &brck3rx; break;
207         }
208         int depth = 1, i = start+1;
209         while ((depth>0) && ((i=textstr.index(*brckrx,i))>=0)) {
210                 if (i>0) if (textstr.elem(i-1)=='\\') { i++; continue; } // escaped bracket
211                 if (textstr.elem(i)==bracket) depth++; else depth--;
212                 i++;
213         }
214         if (i>=0) scopecontent = textstr.at(start+1,i-(start+2));
215         return i;
216 }
String TeX_safe_text (String & title)
Definition at line 253 of file ppfilter.cc.
References String::at(), String::elem(), String::from(), String::gsub(), String::index(), String::matches(), String::sub(), BigRegex::sublen(), TeX_get_argument(), and TeX_get_scope().
Referenced by extract_hierarchy_depth_increase_to_paper().
253                                      {
254 // produces a version of title in proper TeX format from plain text
255 // no attempt is made to convert '\', since it is assumed to precede
256 // TeX commands that are frequently embedded in notes
257 // there are two forms of recognized embedded TeX bracketing:
258 // (1) foo\somecommand [text0] {text1} {text2} {text3} bar (with optional space)
259 // (2) foo{\somecommand text}bar
260 // all other curly brackets and hanging curly brackets are converted
261         const BigRegex TeXchar("[#$%&_]"); // TeX special characters
262         const BigRegex TeXcmdctx("[\\{}]"); // TeX command context indicators
263         const BigRegex TeXcmd("\\(\\\\[A-Za-z]+\\).*"); // TeX command identifier
264         const BigRegex TeXscopecmd("{[ \n\t\r\v\f]*\\\\[A-Za-z]+.*"); // TeX scope limited command identification
265         int convertedto = 0, i = 0;
266         String convtitle;
267         while ((i=title.index(TeXcmdctx,convertedto))>=0) {
268                 convtitle += title.at(convertedto,i-convertedto);
269                 switch (title.elem(i)) {
270                         case '\\': if (title.matches(TeXcmd,i)) {
271                                         // find and convert command
272                                         convtitle += title.sub(TeXcmd,1);
273                                         convertedto = i + TeXcmd.sublen(1);
274                                         String argstr; int argstart, j, argsleft = 9;
275                                         // find and convert possible optional argument
276                                         if ((j=TeX_get_argument(title,convertedto,argstr,'[',&argstart))>=0) {
277                                                 convtitle += title.at(convertedto,argstart-convertedto) + '[' + TeX_safe_text(argstr) + ']';
278                                                 convertedto = j; argsleft--;
279                                         }
280                                         // find and convert possible mandatory arguments
281                                         while ((argsleft>0) && ((j=TeX_get_argument(title,convertedto,argstr,'{',&argstart))>=0)) {
282                                                 convtitle += title.at(convertedto,argstart-convertedto) + '{' + TeX_safe_text(argstr) + '}';
283                                                 convertedto = j; argsleft--;
284                                         }
285                                 } else {
286                                         convtitle += "$\\backslash$"; convertedto = i+1;
287                                 } break;
288                         case '{': if (title.matches(TeXscopecmd,i)) {
289                                         String scopecontent;
290                                         int j = TeX_get_scope(title,i,scopecontent);
291                                         if (j<0) {
292                                                 convtitle += "\\{"; convertedto = i+1;
293                                         } else {
294                                                 convtitle += '{' + TeX_safe_text(scopecontent) + '}'; convertedto = j;
295                                         }
296                                 } else {
297                                         convtitle += "\\{"; convertedto = i+1;
298                                 } break;
299                         case '}': convtitle += "\\}"; convertedto = i+1; break;
300                 }
301         }
302         convtitle += title.from(convertedto);
303         convtitle.gsub(TeXchar,"\\_0",'_');
304         return convtitle;
305 }
int Text_find_line_end (String & textstr, int start, char lend = '\n')
Definition at line 638 of file ppfilter.cc.
References String::index(), and String::length().
Referenced by Text_limit_line_length().
638                                                                       {
639 // returns next location of lend or string length
640         if (start>=textstr.length()) return -1;
641         int i = textstr.index(lend,start);
642         if (i>=0) return i;
643         return textstr.length();
644 }
void Text_limit_line_length (String & textstr, int optlinemax, int abslinemax, char lend = '\n')
Definition at line 646 of file ppfilter.cc.
References String::del(), EOUT, String::from(), String::index(), String::length(), Text_find_line_end(), and VOUT.
Referenced by convert_item_content_to_TeX().
646                                                                                                 {
647 // limits text lines in textstr using optlinemax as optimal line maximum and
648 // abslinemax as absolute line maximum
649         const BigRegex sptabrx("[       ]");
650         int i = 0, j, istart; String itembuf;
651         istart = optlinemax - 50; if (istart<0) istart = 0;
652         while ((j=Text_find_line_end(textstr,i,lend))>=0) {
653                 if ((j-i)>optlinemax) {
654                         if ((j=textstr.index(sptabrx,i+istart))<0) {
655                                 j = i+optlinemax;
656                                 itembuf = textstr.from(j); textstr.del(j,textstr.length()-j);
657                                 textstr += lend + itembuf;
658                                 EOUT << "dil2al: Unable to locate space for line-break, forcing break at column " << optlinemax << " in convert_item_content_to_TeX(), continuing as is\n";
659                         } else if (j>(i+abslinemax)) {
660                                 j = i+optlinemax;
661                                 itembuf = textstr.from(j); textstr.del(j,textstr.length()-j);
662                                 textstr += lend + itembuf;
663                                 EOUT << "dil2al: Space for line-break too distant, forcing break at column " << optlinemax << " in convert_item_content_to_TeX(), continuing as is\n";
664                         } else {
665                                 textstr[j] = lend; // replace rather than insert
666                                 if (verbose) VOUT << "TeX Correction: breaking long line at column " << (j-i) << '\n';
667                         }
668                 }
669                 i = j + 1;
670         }
671 }
time_t Time (time_t * tloc)
Definition at line 1824 of file utilities.cc.
Referenced by Active_List::Add_Day(), generate_AL(), read_financial_notes_file(), time_stamp(), and time_stamp_GM().
1824                           {
1825 // Local time() wrapper, allows emulation of different current time
1826 // returns time and sets (*tloc) to the same time if tloc!=NULL
1827         if (emulatedtime) {
1828                 if (tloc) *tloc = emulatedtime;
1829                 return emulatedtime;
1830         }
1831         return time(tloc);
1832 }
time_t time_chunk_remaining (String chunkid) [inline]
Definition at line 98 of file controller.cc.
References time_stamp(), time_stamp_diff(), and VOUT.
Referenced by schedule_controller().
98                                                    {
99         time_t tdiff = timechunksize*60;
100         tdiff -= time_stamp_diff(chunkid,time_stamp("%Y%m%d%H%M"));
101         if (verbose) VOUT << "\nTask schedule controller: " << tdiff << " seconds remaining in time chunk\n(Current chunk initiated at " << chunkid << ")\n";
102         return tdiff;
103 }
String time_stamp (const char * dateformat, time_t t = -1)
Definition at line 1834 of file utilities.cc.
References Time().
Referenced by Financial_Monthly_Root::add(), Active_List::Add_Day(), AL_Day_Marker(), AL_Passed_Target_Dates(), AL_Day::allocate(), AL_Day::allocate_with_value(), Time::caltime2local(), chunk_controller(), date_string(), dil2al_commands(), AL_Day::expand(), generate_AL(), generate_EPS_cells(), Active_List::generate_focused_AL(), generate_modify_element_FORM_interface_DIL_Superiors(), Active_List::generate_wide_AL(), get_new_DIL_ID(), include_article_tail_template(), Active_List::Initialize_AL_Length(), main(), make_note(), modify_DIL_entry_target_date(), modify_DIL_group_target_dates(), modify_DIL_group_target_dates_cmd(), modify_element_through_FORM_interface_DIL_Superiors(), Financial_Note::put(), AL_Day::set_TC_values(), time_chunk_remaining(), and Detailed_Items_List::Write_to_File().
1834                                                            {
1835 // time stamp in local time
1836         char dstr[80];
1837         if (t<0) t = Time(NULL);
1838         strftime(dstr,80,dateformat,localtime(&t));
1839         return String(dstr);
1840 }
time_t time_stamp_diff (String oldtime, String newtime)
Definition at line 1889 of file utilities.cc.
References time_stamp_time().
Referenced by decide_add_TL_chunk(), select_TL_DIL_refs(), stop_TL_chunk(), and time_chunk_remaining().
1889                                                       {
1890         return time_stamp_time(newtime) - time_stamp_time(oldtime);
1891 }
String time_stamp_GM (const char * dateformat, time_t t = -1)
Definition at line 1842 of file utilities.cc.
References Time().
Referenced by AL_Day_Marker(), Active_List::generate_focused_AL(), Active_List::Initialize_AL_Length(), and remove_AL_TC().
1842                                                              {
1843 // Greenwich Meantime time stamp
1844 // Note: Use this when expressing time differences
1845 //       such as hours and minutes since 0.
1846         char dstr[80];
1847         if (t<0) t = Time(NULL);
1848         strftime(dstr,80,dateformat,gmtime(&t));
1849         return String(dstr);
1850 }
time_t time_stamp_time (String timestr)
Definition at line 1856 of file utilities.cc.
References String::at(), and String::length().
Referenced by Active_List::Add_Day(), Detect_Form_Input(), dil2al_commands(), Detailed_Items_List::Get_Project_Data(), modify_DIL_group_target_dates_cmd(), Modify_Element(), modify_element_through_FORM_interface_DIL_Superiors(), time_stamp_diff(), and time_stamp_time_date().
1856                                        {
1857 // local time string to calendar time time_t
1858 // negative numbers are returned as they are so that
1859 // special codes can be detected
1860         struct tm ts;
1861         int tl = timestr.length();
1862         if (tl>0) if (timestr[0]=='-') return (time_t) atol((const char *) timestr);
1863         if (tl<9) return (time_t) -1;
1864         ts.tm_sec = 0;
1865         ts.tm_min = atoi((const char *) String(timestr.at(tl-2,2)));
1866         ts.tm_hour = atoi((const char *) String(timestr.at(tl-4,2)));
1867         ts.tm_mday = atoi((const char *) String(timestr.at(tl-6,2)));
1868         ts.tm_mon = atoi((const char *) String(timestr.at(tl-8,2)))-1;
1869         ts.tm_year = atoi((const char *) String(timestr.at(0,tl-8)))-1900;
1870         ts.tm_wday = 0;
1871         ts.tm_yday = 0;
1872         ts.tm_isdst = -1; // computed by mktime since indicated "unknown" here
1873         return mktime(&ts);
1874 }
time_t time_stamp_time_date (String timestr)
Definition at line 1882 of file utilities.cc.
References String::before(), String::length(), and time_stamp_time().
Referenced by Active_List::Add_Day(), financial_notes(), generate_EPS_cells(), Financial_Note::get(), and Active_List::Initialize_AL_Length().
1882                                             {
1883 // local time string %Y%m%d%H%M set to 00:00 time of
1884 // day to calendar time
1885         int tl = timestr.length() - 4;
1886         return time_stamp_time(String(timestr.before(tl))+"0000");
1887 }
time_t time_stamp_time_of_day (String timestr)
Definition at line 1876 of file utilities.cc.
References String::at(), String::chars(), and String::length().
Referenced by generate_EPS_cells(), Get_Worked_Estimate(), Active_List::Initialize_AL_Length(), and remove_AL_TC().
1876                                               {
1877         int tl = timestr.length();
1878         String h(timestr.at(tl-4,2)),m(timestr.at(tl-2,2));
1879         return ((((time_t) atoi(h.chars()))*60)+((time_t) atoi(m.chars())))*60;
1880 }
void unconvert_item_content_from_TeX (String & itemcontent)
Definition at line 711 of file ppfilter.cc.
References String::gsub().
Referenced by extract_recursively().
711                                                            {
712         // conversions from TeX
713         itemcontent.gsub(BigRegex("[\\]\\([#&_%]\\)"),"_1",'_');
714 }
bool Unlock_File (String lockfile)
Definition at line 1408 of file utilities.cc.
References EOUT.
Referenced by Detailed_Items_List::Read_from_Binary_Cache(), Detailed_Items_List::Read_Topical_from_Binary_Cache(), Detailed_Items_List::Write_to_Binary_Cache(), and Detailed_Items_List::Write_Topical_to_Binary_Cache().
1408                                   {
1409   if (unlink(lockfile)<0) {
1410     EOUT << "dil2al: Unable to remove lock file " << lockfile << " in Unlock_File(), continuing as is\n";
1411     return false;
1412   }
1413   return true;
1414 }
bool update_DIL_entry_elements (String dilid, double valuation, bool updateval, double completion, bool updatecomp, double required, bool updatereq, time_t tdiff = -1)
Definition at line 849 of file diladmin.cc.
References String::after(), String::before(), EOUT, String::from(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), get_file_in_list(), String::gsub(), PLLRoot< DIL_entry >::head(), HTML_get_table_cell(), HTML_put_table_cell(), HTML_remove_tags(), String::index(), Detailed_Items_List::list, PLL_LOOP_FORWARD, RX_Search_Safe(), String::SEARCH_END, Text_File_Buffers::tf, Text_File_Buffers::tfname, Text_File_Buffers::tfnum, DIL_entry::Topics(), VOUT, and write_file_from_String().
Referenced by Modify_Element(), modify_element_through_FORM_interface(), and stop_TL_chunk().
849                                                                                                                                                                        {
850   // update the elements of all instances of dilid, as
851   // referenced in the DIL-by-ID file
852   // When tdiff>=0, this is used to indicate new time spent on the DIL
853   // entry during a task chunk instead of the value in completion.
854   // The simplest update uses the difference between current time
855   // and the start time of the most recent task log chunk to compute
856   // the update. More sophisticated updates apply the rules
857   // specified in dil2al.html#20000815153735.1.
858   // get DIL references of DIL entry
859   Detailed_Items_List dilist; int entrynum;
860   if ((entrynum=dilist.Get_All_DIL_ID_File_Parameters(&dilid))<=0) {
861     EOUT << "DIL entry " << dilid << " not found in " << idfile << " in update_DIL_entry_completion_ratio(), continuing as is\n";
862     return false;
863   }
864   if (entrynum>1) VOUT << "Warning - DIL entry with ID " << dilid << " occurs " << entrynum << " times in " << idfile << '\n';
865   DIL_entry * de = dilist.list.head(); int dilidx;
866   PLL_LOOP_FORWARD(DIL_Topical_List,de->Topics(0),1) {
867     // get DIL file and update completion ratio of entry
868     if ((dilidx=get_file_in_list(e->dil.file,dilist.tf,dilist.tfname,dilist.tfnum))<0)
869       EOUT << "dil2al: DIL file " << e->dil.file << " not found in update_DIL_entry_elements(), continuing as is\n";
870     else {
871       // find DIL ID
872       String & dilstr = dilist.tf[dilidx];
873       int dilpos, dilentryend; String cellparams, cellcontent;
874       if ((dilpos=dilstr.index(BigRegex("[<]!--[        ]*dil2al:[      ]*DIL begin[    ]*--[>]"),String::SEARCH_END))<0) {
875         EOUT << "dil2al: Missing DIL begin marker in DIL file " << e->dil.file << " in update_DIL_entry_elements(), continuing as is\n";
876         continue;
877       }
878       if ((dilpos=dilstr.index(BigRegex(("[<][Aa][      ]+[Nn][Aa][Mm][Ee][     ]*=[    ]*\""+RX_Search_Safe(dilid))+'"'),dilpos))<0) {
879         EOUT << "dil2al: DIL entry with ID " << dilid << " not found in DIL file " << e->dil.file << " in update_DIL_entry_elements(), continuing as is\n";
880         continue;
881       }
882       if ((dilentryend=HTML_get_table_cell(dilstr,dilpos,cellparams,cellcontent,&dilpos))<0) {
883         EOUT << "dil2al: Missing data at DIL entry with ID " << dilid << " in DIL file " << e->dil.file << " in update_DIL_entry_elements(), continuing as is\n";
884         continue;
885       }
886       if (verbose) VOUT << "Setting:\n";
887       if (updateval) { // modify valuation
888         String vstr(valuation,"_1 %4.2f");
889         if (verbose) VOUT << "  valuation = " << vstr << '\n';
890         cellcontent.gsub(BigRegex("\\(valuation:[^-0-9  ]*\\)[  ]*\\([0-9]+[.][0-9]+\\|-\\)"),vstr,'_');
891       }
892       if (updatecomp) { // modify completion ratio
893         String crstr;
894         if (tdiff>=0) {
895           if (!updatereq) {
896             cellparams = cellcontent.after(BigRegex("time[      ]+required[^:   ]*[:    ]")); HTML_remove_tags(cellparams);
897             required = atof(cellparams);
898           }
899           crstr = cellparams.after(BigRegex("completion[        ]+ratio[^:      ]*[:    ]"));
900           completion = atof(crstr);
901           if (completion<0.0) EOUT << "dil2al: DIL entry with ID " << dilid << " in DIL file " << e->dil.file << " has a completion status with special meaning that cannot be updated in update_DIL_entry_elements(), continuing as is\n";
902           else {
903             if (required==0.0) EOUT << "dil2al: No time required indicated for DIL entry with ID " << dilid << " in DIL file " << e->dil.file << " in update_DIL_entry_elements(), continuing as is\n";
904             else completion += (((double) tdiff)/(ceil(required*60.0)*60.0));
905           }
906         }
907         crstr = String(completion,"_1 %4.2f");
908         if (verbose) VOUT << "  completion ratio = " << crstr << '\n';
909         cellcontent.gsub(BigRegex("\\(completion[       ]+ratio:[^-0-9  ]*\\)[  ]*\\([0-9]+[.][0-9]+\\|-\\)"),crstr,'_');
910       }
911       if (updatereq) { // modify required time
912         String rstr(required,"_1 %4.2f");
913         if (verbose) VOUT << "  required = " << rstr << '\n';
914         cellcontent.gsub(BigRegex("\\(time[     ]+required:[^-0-9       ]*\\)[  ]*\\([0-9]+[.][0-9]+\\|-\\)"),rstr,'_');
915       }
916       // paste modified DIL entry into topical DIL file
917       String newdilstr(dilstr.before(dilpos));
918       newdilstr += HTML_put_table_cell("",cellcontent,true) + dilstr.from(dilentryend);
919       // write modified DIL file
920       if (!write_file_from_String(e->dil.file,newdilstr,"DIL ``"+e->dil.title+"''")) return false;
921     }
922   }
923 #ifdef DEBUG
924   EOUT << "Completed DIL updates\n";
925 #endif
926   return true;
927 }
bool update_DIL_entry_parameter_elements (Detailed_Items_List & dilist, DIL_ID dilid, PLLRoot< DIL_Superiors > & addsups, StringList * removesups, int removesupsnum)
Definition at line 929 of file diladmin.cc.
References DIL_ID::chars(), DIL_Superiors, DIL_entry::elbyid(), EOUT, PLLRoot< DIL_entry >::head(), PLLRoot< PLLType >::head(), PLLRoot< DIL_entry >::length(), Detailed_Items_List::list, DIL_entry::parameters, PLL_LOOP_FORWARD, DIL_entry_parameters::project_append(), DIL_entry::Projects(), VOUT, and Detailed_Items_List::Write_to_File().
Referenced by modify_element_through_FORM_interface().
929                                                                                                                                                                    {
930   // update elements of the DIL-by-ID parameters file
931   // target date modification is currently a special case, as described in
932   // the modify_DIL_entry_target_date() and modify_DIL_group_target_dates()
933   // and is therefore not included in this function
934   int entrynum = dilist.list.length();
935   if (entrynum<1) return false;
936   DIL_entry * de = dilist.list.head()->elbyid(dilid);
937   if (!de) {
938     VOUT << "The DIL entry with ID " << dilid.chars() << "was not found in the Detailed_Items_List in update_DIL_entry_parameter_elements()\n";
939     return false;
940   }
941   // Add superiors referenced in dilref
942   if (addsups.head()) {
943     // modify project data to add the superiors
944     if (!de->parameters) {
945       EOUT << "DIL entry " << dilid << " parameters not found in " << idfile << " in update_DIL_entry_parameter_elements()\n";
946       return false;
947     }
948     if (verbose) VOUT << "Adding superior references from " << dilref << ":\n";
949     for (DIL_Superiors * dilsup = addsups.head(); dilsup; dilsup = dilsup->Next()) {
950       if (!de->parameters->project_append(dilsup->al.file,dilsup->al.title,dilsup->relevance,dilsup->unbounded,dilsup->bounded,dilsup->targetdate(),dilsup->tdproperty(),dilsup->urgency,dilsup->priority)) VOUT << "Unable to append a superior reference with ID " << dilsup->al.title << '\n';
951       else if (verbose) VOUT << "     " << dilsup->al.title << " added\n";
952     }
953   }
954   // Remove superiors indicated in removesups
955   if ((removesupsnum>0) && (removesups)) {
956     if (verbose) {
957       VOUT << "Removing superior references:\n";
958       for (int i = 0; i<removesupsnum; i++) VOUT << "     " << (*removesups)[i] << '\n';
959     }
960     // modify project data to remove the superiors
961     if (!de->Projects(0)) {
962       VOUT << "The DIL entry with ID " << dilid.chars() << " has no superiors, therefore none can be removed.\n";
963       return false;
964     }
965     for (int i = 0; i<removesupsnum; i++) {
966       PLL_LOOP_FORWARD(DIL_Superiors,de->Projects(0),1) if (e->al.title==(*removesups)[i]) {
967         e->remove();
968         if (verbose) VOUT << "     " << (*removesups)[i] << " removed\n";
969         break;
970       }
971     }
972   }
973   return dilist.Write_to_File();
974 }
bool update_DIL_to_AL ()
Definition at line 1334 of file alcomp.cc.
References DIL_ID::chars(), PLLHandle< DIL_entry >::fulllength(), generate_AL(), and Detailed_Items_List::Sort_by_Target_Date().
Referenced by Detect_Form_Input(), and dil2al_commands().
1334                         {
1335 // generate an updated AL from the DIL hierarchy
1336 // uses generatealmaxt and generatealtcs
1337         /*
1338         When computing priorities, also parse for ALs and refresh AL parameters
1339         for all detail items if prefixed with E (``automatic estimate'').
1340         */
1341         // *** can make this first part prepare in the background
1342         //     before a TC is completed
1343         Detailed_Items_List dilist;
1344         DIL_entry ** dep = dilist.Sort_by_Target_Date(true);
1345 #ifdef DEBUG
1346         if (dep) {
1347                 int entrynum = dep[0]->fulllength();
1348                 for (int i = 0; i<entrynum; i++) cerr << dep[i]->chars() << '\n';
1349         }
1350 #endif
1351         if (!generate_AL(dep)) {
1352                 delete[] dep;
1353                 return false;
1354         }
1355         delete[] dep; // may not be necessary here
1356         return true;
1357 }
bool update_main_ALs (DIL_entry * superior)
Definition at line 209 of file alcomp.cc.
References String::before(), capitalize(), DIL_ID::chars(), Elipsis_At(), DIL_entry::Entry_Text(), EOUT, String::from(), HTML_get_href(), HTML_get_list(), HTML_get_list_item(), HTML_get_name(), HTML_put_href(), HTML_put_list(), HTML_put_list_item(), read_file_into_String(), RELLISTSDIR, relurl(), VOUT, and write_file_from_String().
Referenced by generate_AL().
209                                            {
210 // add or modify a link to the AL referred to by superior on
211 // the main page (NULL = AL created with all DIL entries)
212         String mainstr, tag, text, supstr, supfilestr;
213         if (superior) supstr = superior->chars(); else supstr = "all";
214         supfilestr = relurl(listfile,basedir+RELLISTSDIR+("active-list."+supstr+".html"));
215         // get main lists file
216         if (!read_file_into_String(listfile,mainstr)) return false;
217         int mainloc = 0;
218         // locate list of ALs
219         do if ((mainloc=HTML_get_name(mainstr,mainloc,tag,text))<0) {
220                 EOUT << "dil2al: Unable to find HTML anchor ``AL'' in " << listfile << " in update_main_ALs()\n";
221                 return false;
222         } while (tag!="AL");
223         // get list of ALs
224         int liststart;
225         if ((mainloc=HTML_get_list(mainstr,mainloc,tag,text,&liststart))<0) {
226                 EOUT << "dil2al: Missing list of ALs in " << listfile << " in update_main_ALs()\n";
227                 return false;
228         }
229         // find list item with link to AL corresponding with superior
230         int listloc = 0; String itemtext,hreftext;
231         do if ((listloc=HTML_get_list_item(text,listloc,tag,itemtext))>=0) 
232                 if (HTML_get_href(itemtext,0,tag,hreftext)<0) EOUT << "dil2al: Missing HREF to AL in " << listfile << " in update_main_ALs(), continuing\n";
233         while ((listloc>=0) && (tag!=supfilestr));
234         if (listloc>=0) return true; // link already exists
235         // if new, add link to AL corresponding with superior
236         String newmainstr(mainstr.before(liststart));
237         if (superior) {
238                 if (superior->Entry_Text()) {
239                         tag = *(superior->Entry_Text());
240                         Elipsis_At(tag,100);
241                 } else {
242                         VOUT << "dil2al: Warning - No text content available for description of AL in update_main_ALs(), continuing as is\n";
243                         tag = "(No description available.)";
244                 }
245         } else tag = "A list of tasks created with all DIL entries.";
246         // *** perhaps don't use relaxedhtml, despite possible unexpected
247         //     behaviour by older function that read the main lists page
248         text += HTML_put_list_item(HTML_put_href(supfilestr,"Active List: "+capitalize(supstr))+"<BR>\n"+tag+'\n',true)+"<P>\n";
249         newmainstr += HTML_put_list('U',text) + mainstr.from(mainloc);
250         return write_file_from_String(listfile,newmainstr,"Main Lists");
251 }
String URI_unescape (String escapedURI)
Definition at line 2644 of file utilities.cc.
References String::length().
Referenced by extract_DIL_IDs_from_form(), search_FORM_cmd(), and Tabbed_FORM_DIL_Hierarchy_full().
2644                                        {
2645 // convert URI strings with escaped characters to regular character strings
2646         String s; char c; int d1,d2;
2647         for (int i = 0; i<escapedURI.length(); i++) {
2648                 c = escapedURI[i];
2649                 if (c=='%') {
2650                         i++; c = escapedURI[i];
2651                         if ((c>='0') && (c<='9')) d1 = (int) (c - '0');
2652                         else if ((c>='A') && (c<='F')) d1 = ((int) (c - 'A')) + 10;
2653                         else d1 = ((int) (c - 'a')) + 10;
2654                         i++; c = escapedURI[i];
2655                         if ((c>='0') && (c<='9')) d2 = (int) (c - '0');
2656                         else if ((c>='A') && (c<='F')) d2 = ((int) (c - 'A')) + 10;
2657                         else d2 = ((int) (c - 'a')) + 10;
2658                         d1 *=16; d1 += d2;
2659                         c = (char) d1;
2660                 }
2661                 s += c;
2662         }
2663         return s;
2664 }
bool write_file_from_String (String filename, const String & filestr, String message, bool isnew = false)
Definition at line 2116 of file utilities.cc.
References backup_and_rename(), String::empty(), EOUT, and VOUT.
Referenced by add_TL_chunk_or_entry(), add_TL_section(), chunk_controller(), DIL_Hierarchy_cmd(), extract_DIL_IDs_from_form(), generate_AL(), Active_List::generate_focused_AL(), Active_List::generate_wide_AL(), Target_Access::make_local_copy_of_directory(), post_process_note(), remove_AL_TC(), search(), Tabbed_DIL_Hierarchy(), Tabbed_FORM_DIL_Hierarchy(), Tabbed_HTML_DIL_Hierarchy(), update_DIL_entry_elements(), update_main_ALs(), write_financial_notes_file(), and Detailed_Items_List::Write_to_File().
2116                                                                                                          {
2117 // Write a file from string content, with automatic backup of
2118 // a previous version (if one exists).
2119 #ifdef DEBUG
2120         bool b = (filename==taskloghead);
2121         if (b) cout << '+';
2122 #endif
2123         String newfilename = filename;
2124         if (!isnew) newfilename += ".new";
2125         ofstream ntl(newfilename);
2126         if (!ntl) {
2127                 EOUT << "dil2al: Unable to create " << newfilename << " in write_file_from_String()\n";
2128                 return false;
2129         }
2130         ntl << filestr;
2131         ntl.close();
2132 #ifdef DEBUG
2133         if (b) cout << '+';
2134 #endif
2135         if (isnew) { if (verbose && (!message.empty())) VOUT << message << " initialized as " << filename << '\n'; }
2136         else if (!backup_and_rename(filename,message)) return false;
2137 #ifdef DEBUG
2138         if (b) cout << "+\n";
2139 #endif
2140         return true;
2141 }
bool write_financial_notes_file (PLLRoot< Financial_Note > & fnotes, String & finnotestop, String & finnotesend)
Definition at line 111 of file finances.cc.
References PLLRoot< PLLType >::head(), PLL_LOOP_FORWARD, and write_file_from_String().
Referenced by financial_notes().
111                                                                                                               {
112   PLL_LOOP_FORWARD(Financial_Note,fnotes.head(),1) finnotestop += e->put();
113   finnotestop += finnotesend;
114   return write_file_from_String(finnotesfile,finnotestop,"Financial notes");
115 }
Variable Documentation
bool alautoexpand
Definition at line 1356 of file dil2al.hh.
Referenced by Detect_Form_Input(), dil2al_commands(), and Set_Parameter().
int alautoupdate
Definition at line 1366 of file dil2al.hh.
Referenced by dil2al_commands(), and Set_Parameter().
int alcumtimereqexcerptlength
Definition at line 1358 of file dil2al.hh.
Referenced by Set_Parameter().
int alcurdayworkedstrategy
Definition at line 1364 of file dil2al.hh.
Referenced by Set_Parameter().
int aldaydistfunc
Definition at line 1368 of file dil2al.hh.
Referenced by Set_Parameter().
float aldaydistslope
Definition at line 1369 of file dil2al.hh.
Referenced by Set_Parameter().
float alepshours
Definition at line 1355 of file dil2al.hh.
Referenced by Set_Parameter().
int alfocused
Definition at line 1351 of file dil2al.hh.
Referenced by Set_Parameter().
int algenall
Definition at line 1354 of file dil2al.hh.
Referenced by Set_Parameter().
int algenregular
Definition at line 1353 of file dil2al.hh.
Referenced by Set_Parameter().
bool alshowcumulativereq
Definition at line 1357 of file dil2al.hh.
Referenced by Detect_Form_Input(), dil2al_commands(), and Set_Parameter().
time_t alsyncslack
Definition at line 1367 of file dil2al.hh.
Referenced by Set_Parameter().
int alwide
Definition at line 1352 of file dil2al.hh.
Referenced by Set_Parameter().
time_t alworkdaystart
Definition at line 1363 of file dil2al.hh.
Referenced by Set_Parameter().
time_t alworked
Definition at line 1365 of file dil2al.hh.
Referenced by Detect_Form_Input(), and dil2al_commands().
String articleheadtemplate
Definition at line 1326 of file dil2al.hh.
String articletailtemplate
Definition at line 1327 of file dil2al.hh.
bool askALDILref
Definition at line 1337 of file dil2al.hh.
Referenced by Set_Parameter().
bool askextractconcat
Definition at line 1337 of file dil2al.hh.
Referenced by Set_Parameter().
bool askprocesstype
Definition at line 1337 of file dil2al.hh.
Referenced by Set_Parameter().
String atcommand
Definition at line 1376 of file dil2al.hh.
String atcontroller
Definition at line 1377 of file dil2al.hh.
String basedir
Definition at line 1313 of file dil2al.hh.
String bibindexfile
Definition at line 1325 of file dil2al.hh.
String bibindexfilename
Definition at line 1324 of file dil2al.hh.
String browser
Definition at line 1381 of file dil2al.hh.
String cacheidfile
Definition at line 1318 of file dil2al.hh.
bool calledbyforminput
Definition at line 1388 of file dil2al.hh.
Referenced by Detect_Form_Input().
bool chunkcreated
Definition at line 1400 of file dil2al.hh.
String configfile
Definition at line 1385 of file dil2al.hh.
String crcidfile
Definition at line 1317 of file dil2al.hh.
String curdate
Definition at line 1341 of file dil2al.hh.
String curtime
Definition at line 1341 of file dil2al.hh.
Topical_DIL_Files_Root dil
Definition at line 1336 of file dil2al.hh.
String dilref
Definition at line 1323 of file dil2al.hh.
istream* din
Definition at line 1331 of file dil2al.hh.
Referenced by dil2al_commands(), and main().
ifstream dinfile
Definition at line 1330 of file dil2al.hh.
Referenced by dil2al_commands().
String editor
Definition at line 1380 of file dil2al.hh.
time_t emulatedtime
Definition at line 1340 of file dil2al.hh.
Referenced by dil2al_commands().
ostream* eout
Definition at line 1333 of file dil2al.hh.
Referenced by dil2al_commands(), Form_Reply_Open(), and main().
ofstream eoutfile
Definition at line 1332 of file dil2al.hh.
Referenced by dil2al_commands().
String figuresdirectory
Definition at line 1322 of file dil2al.hh.
String finnotesfile
Definition at line 1387 of file dil2al.hh.
String flagcmd
Definition at line 1382 of file dil2al.hh.
int followlinks
Definition at line 1389 of file dil2al.hh.
Referenced by Set_Parameter().
time_t generatealmaxt
Definition at line 1350 of file dil2al.hh.
Referenced by Detect_Form_Input(), and dil2al_commands().
long generatealtcs
Definition at line 1349 of file dil2al.hh.
Referenced by Detect_Form_Input(), dil2al_commands(), and Set_Parameter().
int hierarchyexcerptlength
Definition at line 1373 of file dil2al.hh.
Referenced by Set_Parameter().
int hierarchymaxdepth
Definition at line 1372 of file dil2al.hh.
Referenced by dil2al_commands(), and Set_Parameter().
bool hierarchyplanparse
Definition at line 1371 of file dil2al.hh.
Referenced by Set_Parameter().
String homedir
Definition at line 1312 of file dil2al.hh.
String htmlforminterface
Definition at line 1378 of file dil2al.hh.
String htmlformmethod
Definition at line 1379 of file dil2al.hh.
String idfile
Definition at line 1315 of file dil2al.hh.
bool immediatesearchoutput
Definition at line 1391 of file dil2al.hh.
Referenced by Set_Parameter().
StringList indexkeys
Definition at line 1397 of file dil2al.hh.
int indexkeysnum
Definition at line 1398 of file dil2al.hh.
Referenced by Set_Parameter().
bool isdaemon
Definition at line 1337 of file dil2al.hh.
Referenced by Set_Parameter().
String listfile
Definition at line 1314 of file dil2al.hh.
String lockidfile
Definition at line 1316 of file dil2al.hh.
Detailed_Items_List* looplist
Definition at line 1402 of file dil2al.hh.
String newTLID
Definition at line 1399 of file dil2al.hh.
String notetmpfile
Definition at line 1383 of file dil2al.hh.
int numDILs
Definition at line 1335 of file dil2al.hh.
Referenced by initialize().
bool offercreate
Definition at line 1337 of file dil2al.hh.
Referenced by Set_Parameter().
String owner
Definition at line 1342 of file dil2al.hh.
String paperplansfile
Definition at line 1321 of file dil2al.hh.
StringList quicknotedescr
Definition at line 1395 of file dil2al.hh.
StringList quicknotedst
Definition at line 1393 of file dil2al.hh.
int quicknotedstnum
Definition at line 1396 of file dil2al.hh.
Referenced by Set_Parameter().
StringList quicknotedsttitle
Definition at line 1394 of file dil2al.hh.
bool rapidscheduleupdating
Definition at line 1359 of file dil2al.hh.
Referenced by Set_Parameter().
bool remotesearch
Definition at line 1392 of file dil2al.hh.
Referenced by Set_Parameter().
bool reversehierarchy
Definition at line 1370 of file dil2al.hh.
Referenced by Set_Parameter().
bool searchprogressmeter
Definition at line 1390 of file dil2al.hh.
Referenced by Set_Parameter().
int sectionsize
Definition at line 1347 of file dil2al.hh.
Referenced by Set_Parameter().
int sectionstrategy
Definition at line 1348 of file dil2al.hh.
Referenced by Set_Parameter().
bool showflag
Definition at line 1337 of file dil2al.hh.
Referenced by dil2al_commands(), and Set_Parameter().
bool suggestnameref
Definition at line 1337 of file dil2al.hh.
Referenced by Set_Parameter().
String tareadfile
Definition at line 1386 of file dil2al.hh.
bool targetdatepreferences
Definition at line 1360 of file dil2al.hh.
Referenced by Set_Parameter().
String tasklog
Definition at line 1319 of file dil2al.hh.
String taskloghead
Definition at line 1320 of file dil2al.hh.
String templatearticlesubsection
Definition at line 1328 of file dil2al.hh.
String templatearticlesubsubsection
Definition at line 1329 of file dil2al.hh.
int timechunkoverstrategy
Definition at line 1345 of file dil2al.hh.
Referenced by Set_Parameter().
int timechunksize
Definition at line 1343 of file dil2al.hh.
Referenced by Set_Parameter().
int timechunkslack
Definition at line 1344 of file dil2al.hh.
Referenced by Set_Parameter().
int timechunkunderstrategy
Definition at line 1346 of file dil2al.hh.
Referenced by Set_Parameter().
String tlentrytmpfile
Definition at line 1384 of file dil2al.hh.
int updatenoteineditor
Definition at line 1375 of file dil2al.hh.
Referenced by Set_Parameter().
String updatenoteineditorcmd
Definition at line 1374 of file dil2al.hh.
bool useansi
Definition at line 1337 of file dil2al.hh.
Referenced by Set_Parameter().
bool usequickloadcache
Definition at line 1339 of file dil2al.hh.
Referenced by Set_Parameter().
bool verbose
Definition at line 1337 of file dil2al.hh.
Referenced by dil2al_commands().
ostream* vout
Definition at line 1334 of file dil2al.hh.
Referenced by dil2al_commands(), and main().
time_t wdworkendprefs[7]
Definition at line 1362 of file dil2al.hh.
Referenced by Set_Parameter().
bool weekdayworkendpreferences
Definition at line 1361 of file dil2al.hh.
Referenced by work_end_preferences().