finances.cc File Reference
#include `dil2al.hh`
Functions
bool read_financial_notes_file (PLLRoot< Financial_Note > &fnotes, String &finnotestop, String &finnotesend)
bool write_financial_notes_file (PLLRoot< Financial_Note > &fnotes, String &finnotestop, String &finnotesend)
bool financial_notes ()
bool financial_monthly ()
Function Documentation
bool financial_monthly ()
Definition at line 263 of file finances.cc.
References Financial_Monthly_Root::add(), PLLRoot< PLLType >::head(), PLL_LOOP_FORWARD, Financial_Monthly_Root::put_results(), read_financial_notes_file(), and VOUT.
Referenced by formalizer_commands().
263                          {
264   // Compute results from <A HREF="../../doc/html/financial-notes.html">financial-notes.html</A>.
265   PLLRoot<Financial_Note> fnotes; String finnotestop, finnotesend;
266   if (!read_financial_notes_file(fnotes,finnotestop,finnotesend)) return false;
267   // compute sums of categorized expenses that have not previously been handled
268   Financial_Monthly_Root fmonthly;
269   if (verbose) VOUT << "If you wish to rely on monthly results from the Financial Notes, please\nverify that all non-variable expenses listed in bank statements are\naccounted for in the Financial Notes.\n\n";
270   PLL_LOOP_FORWARD(Financial_Note,fnotes.head(),1) {
271     if (!e->Handled()) fmonthly.add(*e);
272   }
273   VOUT << fmonthly.put_results();
274 }
bool financial_notes ()
Definition at line 117 of file finances.cc.
References confirmation(), String::del(), String::empty(), String::length(), Financial_Note::link_sorted(), read_financial_notes_file(), time_stamp_time_date(), VOUT, and write_financial_notes_file().
Referenced by formalizer_commands().
117                        {
118   // Edit notes in <A HREF="../../doc/html/financial-notes.html">financial-notes.html</A>.
119   PLLRoot<Financial_Note> fnotes; String finnotestop, finnotesend;
120   if (!read_financial_notes_file(fnotes,finnotestop,finnotesend)) return false;
121   // add new notes (currently just by hand)
122   Financial_Note * f;
123   time_t d; double e; bool h; String dstr(curdate), t, n, c;
124   const int LLEN = 10240;
125   char lbuf[LLEN];
126   d = time_stamp_time_date(dstr+"0000");
127   while (1) {
128     VOUT << "date [" << dstr << "] (done=exit): ";
129     cin.getline(lbuf,LLEN); n = lbuf;
130     if (!n.empty()) {
131       if (n=="done") break;
132       dstr = n;
133       n += "0000"; n.del(12,n.length()-12);
134       d = time_stamp_time_date(n);
135     }
136     VOUT << "expense: ";
137     cin.getline(lbuf,LLEN);
138     e = atof(lbuf);
139     VOUT << "type [variable]: ";
140     cin.getline(lbuf,LLEN); t = lbuf;
141     if (t.empty()) t = "variable";
142     if (t==String("variable")) h = true;
143     else h = !confirmation("handled [n]: ",'y');
144     VOUT << "note: ";
145     cin.getline(lbuf,LLEN); n = lbuf;
146     VOUT << "comment: ";
147     cin.getline(lbuf,LLEN); c = lbuf;
148     f = new Financial_Note(d,e,t,h,n,c);
149     f->link_sorted(fnotes);
150   }
151   // write financial notes file
152   return write_financial_notes_file(fnotes,finnotestop,finnotesend);
153 }
bool read_financial_notes_file (PLLRoot< Financial_Note > & fnotes, String & finnotestop, String & finnotesend)
Definition at line 82 of file finances.cc.
References String::before(), String::del(), EOUT, String::from(), String::index(), String::length(), Financial_Note::link_sorted(), read_file_into_String(), String::SEARCH_END, Time(), and VOUT.
Referenced by financial_monthly(), and financial_notes().
82                                                                                                              {
83   String finnotesstr;
84   // read financial notes file
85   if (!read_file_into_String(finnotesfile,finnotesstr)) return false;
86   // extract financial notes table
87   if (verbose) VOUT << "Parsing Financial Notes file\n";
88   int i, j;
89   if ((i=finnotesstr.index("<!-- dil2al: start items -->",String::SEARCH_END,0))<0) {
90     EOUT << "formalizer: Missing start of financial notes items table\n";
91     return false;
92   }
93   if ((j=finnotesstr.index("<!-- dil2al: end items -->",0))<0) {
94     EOUT << "formalizer: Missing end of financial notes items table\n";
95     return false;
96   }
97   finnotestop = finnotesstr.before(i)+'\n';
98   finnotesend = finnotesstr.from(j);
99   finnotesstr.del(j,finnotesstr.length()-j);
100   finnotesstr.del(0,i); // finnotesstr contains table
101   // extract financial notes items while keeping track of dates and sorting by date
102   time_t notedate = Time(NULL);
103   for (i=0; i>=0; ) {
104     Financial_Note * fn = new Financial_Note(finnotesstr,notedate,i);
105     if (i<0) delete fn;
106     else fn->link_sorted(fnotes);
107   }
108   return true;
109 }
bool write_financial_notes_file (PLLRoot< Financial_Note > & fnotes, String & finnotestop, String & finnotesend)
Definition at line 111 of file finances.cc.
References PLLRoot< PLLType >::head(), PLL_LOOP_FORWARD, and write_file_from_String().
Referenced by financial_notes().
111                                                                                                               {
112   PLL_LOOP_FORWARD(Financial_Note,fnotes.head(),1) finnotestop += e->put();
113   finnotestop += finnotesend;
114   return write_file_from_String(finnotesfile,finnotestop,"Financial notes");
115 }