templates.defines.hh File Reference
Compounds
class PLLType
class PLLType
Defines
#define Protected_Linked_List_Class(PLLType)
#define Protected_Linked_List_functions(PLLType)
#define Protected_Linked_List_Indexed_Access(PLLType, Here, There)
#define PLL_LOOP_FORWARD(PLLType, Init_El, Extra_Test) for (PLLType * e = Init_El; ((e) && (Extra_Test)); e = e $\rightarrow$ Next())
Functions
if (pllprev) pllprev $\rightarrow$ pllnext=NULL
succ set_root (this)
bool PLL_ if (pred.head()) return false
pred set_root (pred $\rightarrow$ head())
PLLType *PLL_ if (!pllroot)
PLLRoot_ unlink_before (t)
unlink_after (r)
h link_before (t)
if (n >0)
if (pred $\rightarrow$ Root()!=this) return link_before(inshead)
PLLRoot_ pred unlink_after (h)
link_after (&h)
bool insert_after (int n, PLLType *inshead)
return insert_after (pred, inshead)
bool insert_before (PLLType *succ, PLLType *inshead)
if (succ $\rightarrow$ Root()!=this) return link_after(inshead)
link_before (&t)
bool insert_before (int n, PLLType *inshead)
return insert_before (succ, inshead)
Variables
PLLRoot_ PLLType
PLLRoot_ PLLType false
succ pllhead = this
else succ plltail = seek_tail()
pllprev = NULL
return true
pllnext = NULL
bool res = h.link_before(inshead)
PLLType * pred = el(n)
PLLType * succ = el(n)
Define Documentation
#define PLL_LOOP_FORWARD(PLLType, Init_El, Extra_Test) for (PLLType * e = Init_El; ((e) && (Extra_Test)); e = e $\rightarrow$ Next())
Definition at line 294 of file templates.defines.hh.
#define Protected_Linked_List_Class(PLLType)
#define Protected_Linked_List_functions(PLLType)
#define Protected_Linked_List_Indexed_Access(PLLType, Here, There)
Value:
if (!n) return Here; \
        if (PLLType * e = el(n)) return e->There; else return NULL \
Definition at line 288 of file templates.defines.hh.
Function Documentation
if (succ-, Root()! = this)
if (pred-, Root()! = this)
if (n, 0)
Definition at line 155 of file templates.defines.hh.
References pllnext.
155                          { 
156                         if (pllnext) return pllnext->el(n-1); 
157                         else return NULL; 
158                 } else { 
if (! succ) [inline]
Definition at line 140 of file templates.defines.hh.
References pllnext, and pllprev.
140                               { 
141                         pllprev->pllnext = pllnext; 
142                         pllnext->pllprev = pllprev; 
143                         PLLType * pn = pllnext; 
144                         delete this; 
145                         return pn; 
146                 } 
bool PLL_ if (pred.head()) [inline]
if (pllprev)
Definition at line 112 of file templates.defines.hh.
References PLLType< PLLType >::pllhead, PLLType< PLLType >::pllprev, PLLType< PLLType >::plltail, succ, and PLLType< PLLType >::tail().
112                              { 
113                         succ.plltail = pllroot->tail(); 
114                         pllroot->plltail = pllprev; 
115                         if (!pllprev) pllroot->pllhead = NULL; 
116                 } else succ.plltail = seek_tail(); 
return insert_after (pred, inshead)
bool insert_after (int n, PLLType * inshead) [inline]
return insert_before (succ, inshead)
bool insert_before (int n, PLLType * inshead) [inline]
bool insert_before (PLLType * succ, PLLType * inshead) [inline]
link_after (& h)
link_before (& t)
h link_before (t)
pred set_root (pred-, head())
succ set_root (this)
PLLRoot_ pred unlink_after (h)
unlink_after (r)
PLLRoot_ succ unlink_before (t)
Variable Documentation
class PLLRoot_ PLLType false
Referenced by AL_Day::AL_Day(), Financial_Note::Financial_Note(), Target_Access::Target_Access(), and Topical_DIL_Files::Topical_DIL_Files().
else pred pllhead = this
Definition at line 132 of file templates.defines.hh.
Referenced by update().
return pllnext = NULL
Definition at line 151 of file templates.defines.hh.
Referenced by if().
pllprev = NULL
Definition at line 117 of file templates.defines.hh.
Referenced by if().
pred plltail = seek_tail()
Definition at line 127 of file templates.defines.hh.
Referenced by if(), and update().
class PLLRoot_ PLLType
Definition at line 49 of file templates.defines.hh.
PLLType* pred = el(n)
Definition at line 265 of file templates.defines.hh.
Referenced by PLLRoot< PLLType >::insert_after(), PLLRoot< PLLType >::link_after(), and PLLHandle< PLLType >::unlink_after().
return res = h.link_before(inshead)
Definition at line 277 of file templates.defines.hh.
Referenced by add_new_to_DIL(), BigRegex::BigRegex(), cmdline_extract_paper_novelties(), generate_AL_full_entry(), generate_Figures_Directory_entry(), generate_tag(), get_active_DIL_IDs(), get_TL_head(), HTML_marker_arguments(), Search_Result::HTML_put_text(), HTML_remove_comments(), PLLRoot< PLLType >::insert_after(), PLLRoot< PLLType >::insert_before(), make_note(), BigRegex::match(), modify_DIL_entry_target_date(), modify_DIL_group_target_dates(), Quick_String_Hash::nodes(), process_note(), process_note_CC(), process_note_generic(), process_note_HTML(), process_note_TeX(), process_note_TL(), Financial_Monthly_Root::put_results(), Detailed_Items_List::Read_from_Binary_Cache(), Detailed_Items_List::Read_Topical_from_Binary_Cache(), search(), Search_Target::search(), BigRegex::search(), search_cmd(), search_output(), Quick_String_Hash::size(), superior_reference_info(), Detailed_Items_List::Write_to_Binary_Cache(), and Detailed_Items_List::Write_Topical_to_Binary_Cache().
PLLType* succ = el(n)
Definition at line 282 of file templates.defines.hh.
Referenced by if(), PLLRoot< PLLType >::insert_before(), PLLRoot< PLLType >::link_before(), and PLLHandle< PLLType >::unlink_before().
return true
Definition at line 135 of file templates.defines.hh.