tlfilter.cc File Reference
#include `dil2al.hh`
Functions
bool filter_TL_by_AL ()
bool generate_TL_keyword_index ()
bool search_TL (String searchstr)
bool extract_paper_novelties (String fname, String paperplanurl, ostream &ostr)
bool cmdline_extract_paper_novelties (String filepaper)
Function Documentation
bool cmdline_extract_paper_novelties (String filepaper)
Definition at line 65 of file tlfilter.cc.
References String::after(), backup_and_rename(), String::before(), EOUT, extract_paper_novelties(), String::prepend(), and res.
Referenced by dil2al_commands().
65                                                        {
66 // Commandline interface to the extraction of NOVELTY tagged items
67         bool res;
68         String fname, paperplanurl;
69         fname = filepaper.before("+");
70         if (fname == "") {
71                 fname = filepaper;
72                 paperplanurl = homedir+"doc/tex/somepaper/somepaper.html"; // dummy URL
73                 res = extract_paper_novelties(fname,paperplanurl,cout);
74         } else {
75                 paperplanurl = filepaper.after("+");
76                 if (paperplanurl == "") {
77                         paperplanurl = homedir+"doc/tex/somepaper/somepaper.html"; // dummy URL
78                         res = extract_paper_novelties(fname,paperplanurl,cout);
79                 } else {
80                         if (paperplanurl[0]!='/') paperplanurl.prepend(homedir);
81                         ofstream ostr(paperplanurl+".new");
82                         if (!ostr) {
83                                 EOUT << "dil2al: Unable to create " << paperplanurl << ".new in cmdline_extract_paper_novelties()\n";
84                                 return false;
85                         }
86                         ifstream istr(paperplanurl);
87                         bool isnew = (!istr);
88                         if (!isnew) ostr << istr.rdbuf(); // copy existing content (without regard to a possible </BODY> tag)
89                         istr.close();
90                         res = extract_paper_novelties(fname,paperplanurl,ostr);
91                         ostr.close();
92                         if (!backup_and_rename(paperplanurl,"Paper Plan",isnew)) return false;
93                 }
94         }
95         return true;
96 }
bool extract_paper_novelties (String fname, String paperplanurl, ostream & ostr)
Definition at line 19 of file tlfilter.cc.
References _BIGSTRING_ITERATOR, String::after(), String::at(), EOUT, String::gsub(), String::index(), read_file_into_String(), relurl(), RX_Search_Safe(), BigRegex::sublen(), and BigRegex::subpos().
Referenced by cmdline_extract_paper_novelties().
19                                                                                 {
20 // searches a document for <A NAME="NOVELTY-some-id">[<B>N</B>]</A>/<!-- @NOVELTY-some-id@ -->
21 // tags and returns the items between the tags
22         String fcont;
23         if (!read_file_into_String(fname,fcont)) {
24                 EOUT << "dil2al: Unable to read file " << fname << " in extract_paper_novelties()\n";
25                 return false;
26         }
27         _BIGSTRING_ITERATOR i=-1;
28         while ((i=fcont.index(BigRegex("[<]A[   ]+[Nn][Aa][Mm][Ee][     ]*=[    ]*\"NOVELTY-[^\"]*\"[>]"),i+1))>=0) {
29                 _BIGSTRING_ITERATOR ii = fcont.index("\">",i); // find end of ID
30                 if (ii>=0) {
31                         String nid;
32                         nid = fcont.at(i,ii-i);
33                         nid = nid.after("\"",-1);
34                         ii = fcont.index("</A>",ii); // find start of content
35                         if (ii>=0) {
36                                 BigRegex en("[<]!--[    ]+@"+RX_Search_Safe(nid)+"@[    ]+\\([^>]*\\)--[>]");
37                                 _BIGSTRING_ITERATOR iii = fcont.index(en,ii); // get end marker
38                                 if (iii>=0) {
39                                         String cstr, istr, lstr, sstr;
40                                         if (en.sublen(1)>0) { // extract possible qualifying and quantifying information
41                                                 String qqinfo = fcont.at(en.subpos(1),en.sublen(1));
42                                                 const BigRegex qqi("@CONTEXT:[  ]*\\([^@]*\\)@[         ]*@IMP:[        ]*\\([^@]*\\)@[         ]*@LEN:[        ]*\\([^@]*\\)@[         ]*@SECTION:[    ]*\\([^@]*\\)@");
43                                                 if (qqinfo.index(qqi)>=0) {
44                                                         cstr = qqinfo.at(qqi.subpos(1),qqi.sublen(1));
45                                                         istr = qqinfo.at(qqi.subpos(2),qqi.sublen(2));
46                                                         lstr = qqinfo.at(qqi.subpos(3),qqi.sublen(3));
47                                                         sstr = qqinfo.at(qqi.subpos(4),qqi.sublen(4));
48                                                 }
49                                         }
50                                         String ncont;
51                                         ncont = fcont.at(ii+4,iii-(ii+4)); // get content
52                                         ncont.gsub(BigRegex("[<][^>]*[>]"),""); // clean up content
53                                         String fshortname = fname.after("/",-1);
54                                         if (fshortname == "") fshortname = fname;
55                                         ostr << "<LI>" << ncont << " [<A HREF=\"" << relurl(paperplanurl,fname) << '#' << nid << "\">" << fshortname << '#' << nid << "</A>]<BR>\n"; // return content
56 //*** selection criteria suggestions can be automatically generated (see DIL#20000310091924.1)
57                                         ostr << "(<B>Context</B>: " << cstr << ", <B>Importance</B>: " << istr << ", <B>Length</B>: " << lstr << ", <B>Section</B>: " << sstr << ")\n"; // add selection criteria
58                                 }
59                         }
60                 }
61         } // else may already have HREF reference to paper in which it is included
62         return true;
63 }
bool filter_TL_by_AL ()
Definition at line 6 of file tlfilter.cc.
6                        {
7 }
bool generate_TL_keyword_index ()
Definition at line 9 of file tlfilter.cc.
9                                  {
10 // keywords can be created with a special tag that you insert anywhere
11 // in a task log entry, or anywhere in HTML or TeX documents or source code or
12 // plain text, plus in the dil2al configuration file
13 }
bool search_TL (String searchstr)
Definition at line 15 of file tlfilter.cc.
15                                  {
16 // searchstr is a regexp
17 }