utilities.cc File Reference
#include `dil2al.hh`
Defines
#define READSOMETYPE char*
#define TEST_LBUF_BOUNDS(slen, funcname) if (slen>=LLEN) { EOUT << `dil2al: Number of characters exceeds lbuf bounds in ` << funcname << '\n'; return false; }
#define PLAN_ENTRY_IDENTIFIER_TAG `<!-- @begin: PLAN DIL TEMPLATE: `
#define PLAN_ENTRY_IDENTIFIER_TAG_LENGTH 32
#define PLAN_ENTRY_DECISION_TAG `<BR><B>decision:`
#define PLAN_ENTRY_STRING_ACTION `action`
#define PLAN_ENTRY_STRING_GOAL `goal`
#define PLAN_ENTRY_STRING_OBJECTIVE `objective`
#define PLAN_ENTRY_STRING_OUTCOME `outcome`
#define PLAN_ENTRY_STRING_VARIABLE `variable`
#define NUM_PLAN_ENTRY_TYPES 5
Functions
bool Lock_File (String lockfile, String msgstr)
bool Unlock_File (String lockfile)
int DIL_entry_target_date_qsort_compare (const void *vde1, const void *vde2)
int BigRegex_freq (String &str, const BigRegex &rx)
int BigRegex_freq (String &str, String rxstr)
int BigRegex_freq (String &str, const char *rxstr)
String RX_Search_Safe (String s)
time_t Time (time_t *tloc)
String time_stamp (const char *dateformat, time_t t=-1)
String time_stamp_GM (const char *dateformat, time_t t=-1)
String date_string ()
time_t time_stamp_time (String timestr)
time_t time_stamp_time_of_day (String timestr)
time_t time_stamp_time_date (String timestr)
time_t time_stamp_diff (String oldtime, String newtime)
time_t double2time (double t)
bool confirmation (String message, char nondefault)
void auto_interactive (String &autostr, String message, char *lbuf, int llen)
String relurl (String srcurl, String dsturl)
String absurl (String srcurl, String relurl)
bool file_is_regular (String filepath)
bool file_is_regular_or_symlink (String filepath)
bool file_is_directory (String filepath)
bool prepare_temporary_file (String tmpfile, String initstr)
bool backup_and_rename (String filename, String message, bool isnew=false)
bool read_file_into_String (ifstream &sfl, String &filestr, bool warnnoopen=true)
bool read_file_into_String (String filename, String &filestr, bool warnnoopen=true)
bool read_file_into_String (bool &isnew, String filename, String &filestr)
int get_file_in_list (String &fname, StringList &srcf, StringList &srcfname, int &srcfnum)
bool write_file_from_String (String filename, const String &filestr, String message, bool isnew=false)
void read_data_from_stream (istream &ifs, String &dstr, const char *terminate)
int find_delimiter (String &str, int startpos, int lenlimit, char delimiter='\n')
bool pattern_in_line (const char *pattern, char *lbuf)
bool substring_from_line (const char *pattern, int nsub, String *dilid, const char *lbuf)
bool find_line (ifstream *lf, const char *pattern, char *lbuf, int llen)
int copy_until_line (ifstream *lf, ofstream *of, const char *pattern, char *lbuf, int llen)
int find_in_line (ifstream *lf, const char *pattern, int nsub, String *dilid, const char *before, char *lbuf, int llen)
bool initialize_new_DIL_TL (String initializecmd, bool includeinput)
int D2A_get_tag (String &d2astr, int strloc, String d2atag, String &tagtext)
int HTML_get_marker (String &htmlstr, int strloc, String &marker, bool locate=true)
String HTML_marker_arguments (String &marker)
int HTML_get_tagged_environment (const BigRegex &begintag, const BigRegex &endmatch, const BigRegex &endtag, String &htmlstr, int strloc, String &envparams, String &envcontent, int *envstart=NULL)
int HTML_get_table_cell (String &htmlstr, int strloc, String &cellparams, String &cellcontent, int *cellstart=NULL)
int HTML_get_table_row (String &htmlstr, int strloc, String &rowparams, String &rowcontent, int *rowstart=NULL)
int HTML_get_list (String &htmlstr, int strloc, String &listparams, String &listcontent, int *liststart=NULL)
int HTML_get_list_item (String &htmlstr, int strloc, String &itemparams, String &itemcontent, int *itemstart=NULL)
int HTML_get_href (String &htmlstr, int strloc, String &hrefurl, String &hreftext, int *hrefstart=NULL)
int HTML_get_name (String &htmlstr, int strloc, String &nametag, String &nametext)
String * HTML_safe (String &textstr)
String * HTML_remove_comments (String &htmlstr)
String * HTML_remove_tags (String &htmlstr)
String HTML_put_structure (String tag, String params, String content, bool relaxedhtml=false)
String HTML_put_table_row (String rowparams, String rowcontent, bool relaxedhtml=false)
String HTML_put_table_cell (String cellparams, String cellcontent, bool relaxedhtml=false)
String HTML_put_list (char listtype, String htmlstr)
String HTML_put_list_item (String htmlstr, bool relaxedhtml=false)
String HTML_put_href (String hrefurl, String hreftext)
String HTML_put_name (String nametag, String nametext)
String HTML_put_form (String formmethod, String formaction, String formcontent)
String HTML_put_form_input (String inputtype, String inputargs)
String HTML_put_form_submit (String submittext)
String HTML_put_form_reset ()
String HTML_put_form_radio (String radioname, String radiovalue, String radiotext, bool checked=false)
String HTML_put_form_checkbox (String checkboxname, String checkboxvalue, String checkboxtext, bool checked=false)
String HTML_put_form_text (String textname, String textvalue, long maxlen=-1)
String HTML_put_form_text (String textname, long maxlen=-1)
int Elipsis_At (String &s, int maxsize)
String URI_unescape (String escapedURI)
String Int2HexStr (unsigned int i)
String * remove_whitespace (String &str)
double get_double (String valstr, double defval=0.0, bool *gotdouble=NULL)
Variables
const char plan_entry_type_strings [NUM_PLAN_ENTRY_TYPES][10] = {PLAN_ENTRY_STRING_ACTION,PLAN_ENTRY_STRING_GOAL,PLAN_ENTRY_STRING_OBJECTIVE,PLAN_ENTRY_STRING_OUTCOME,PLAN_ENTRY_STRING_VARIABLE}
Define Documentation
#define NUM_PLAN_ENTRY_TYPES 5
Definition at line 21 of file utilities.cc.
Referenced by DIL_entry_content::Is_Plan_Entry().
#define PLAN_ENTRY_DECISION_TAG `<BR><B>decision:`
Definition at line 15 of file utilities.cc.
Referenced by Plan_entry_content::Parse_Entry_Content().
#define PLAN_ENTRY_IDENTIFIER_TAG `<!-- @begin: PLAN DIL TEMPLATE: `
Definition at line 13 of file utilities.cc.
Referenced by DIL_entry_content::Is_Plan_Entry().
#define PLAN_ENTRY_IDENTIFIER_TAG_LENGTH 32
Definition at line 14 of file utilities.cc.
Referenced by DIL_entry_content::Is_Plan_Entry().
#define PLAN_ENTRY_STRING_ACTION `action`
Definition at line 16 of file utilities.cc.
#define PLAN_ENTRY_STRING_GOAL `goal`
Definition at line 17 of file utilities.cc.
#define PLAN_ENTRY_STRING_OBJECTIVE `objective`
Definition at line 18 of file utilities.cc.
#define PLAN_ENTRY_STRING_OUTCOME `outcome`
Definition at line 19 of file utilities.cc.
#define PLAN_ENTRY_STRING_VARIABLE `variable`
Definition at line 20 of file utilities.cc.
#define READSOMETYPE char*
Definition at line 9 of file utilities.cc.
Referenced by DIL_ID::Read_DIL_ID_from_Binary_Cache(), Detailed_Items_List::Read_from_Binary_Cache(), DIL_entry::Read_from_Binary_Cache(), DIL_entry_parameters::Read_from_Binary_Cache(), DIL_AL_List::Read_from_Binary_Cache(), DIL_Topical_List::Read_from_Binary_Cache(), Detailed_Items_List::Read_Topical_from_Binary_Cache(), DIL_entry::Read_Topical_from_Binary_Cache(), and DIL_entry_content::Read_Topical_from_Binary_Cache().
#define TEST_LBUF_BOUNDS(slen, funcname) if (slen>=LLEN) { EOUT << `dil2al: Number of characters exceeds lbuf bounds in ` << funcname << '\n'; return false; }
Definition at line 11 of file utilities.cc.
Referenced by DIL_AL_List::Read_from_Binary_Cache(), DIL_Topical_List::Read_from_Binary_Cache(), and DIL_entry_content::Read_Topical_from_Binary_Cache().
Function Documentation
String absurl (String srcurl, String relurl)
Definition at line 1943 of file utilities.cc.
References String::after(), String::before(), String::contains(), String::freq(), and String::gsub().
Referenced by extract_paper_plan_to_paper(), extract_recursively(), generate_modify_element_FORM_interface_DIL_entry_content(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), get_Paper_Plans_Section_IDs(), modify_element_through_FORM_interface(), and Topical_DIL_Files::Refresh().
1943                                             {
1944 // srcurl is an absolute filename or a directory path
1945 // ending with "/"
1946 // relurl is a URL relative to srcurl or an absolute URL
1947 // Note: This function may be confused by directory names
1948 //       of the form BigRegex(".+[.][.]")
1949         if (relurl=="") return srcurl;
1950         if (relurl.contains("://")) relurl = relurl.after("://");
1951         if (relurl[0]=='/') return relurl;
1952         if (relurl[0]=='#') return srcurl+relurl;
1953         int upcnt = relurl.freq("../");
1954         relurl.gsub("../","");
1955         srcurl = srcurl.before('/',-1); // prune source filename
1956         for (int i = 0; i < upcnt; i++) srcurl = srcurl.before('/',-1);
1957         return srcurl+'/'+relurl;
1958 }
void auto_interactive (String & autostr, String message, char * lbuf, int llen)
Definition at line 1916 of file utilities.cc.
References String::del().
Referenced by chunk_controller().
1916                                                                                {
1917 // enables interactive responses or takes responses from autostr if available
1918         if (autostr=="") {
1919                 cout << message;
1920                 cin.getline(lbuf,llen);
1921         } else {
1922                 strcpy(lbuf,(const char *) autostr);
1923                 autostr.del(0,1);
1924         }
1925 }
bool backup_and_rename (String filename, String message, bool isnew = false)
Definition at line 2016 of file utilities.cc.
References EOUT, and VOUT.
Referenced by add_new_to_DIL(), cmdline_extract_paper_novelties(), create_new_DIL(), extract_paper_plan_to_paper(), send_dil_to_DIL(), and write_file_from_String().
2016                                                                             {
2017 // Backup previous version of file with date stamp and make
2018 // new version current.
2019         String backupname = filename+'.'+curdate+".bak";
2020         if (!isnew) if (rename(filename,backupname)<0) {
2021                 if (errno!=ENOENT) {
2022                         EOUT << "dil2al: Unable to rename " << filename << " to " << backupname << " in backup_and_rename()\n(New version remains in " << filename << ".new)\n";
2023                         return false;
2024                 } else EOUT << "dil2al: Warning - no old version of " << filename << " to backup in backup_and_rename()\n";
2025         }
2026         if (rename(filename+".new",filename)<0) {
2027                 EOUT << "dil2al: Unable to rename " << filename << ".new to " << filename << " in backup_and_rename()\n(New version remains in " << filename << ".new)\nRestoring previous " << filename << '\n';
2028                 if (!isnew) if (rename(backupname,filename)<0) EOUT << "dil2al: Unable to restore " << backupname << " to " << filename << '\n';
2029                 return false;
2030         }
2031         if (verbose) { // *** perhaps this should be suppressed if errno==ENOENT was caught above
2032                 if (isnew) VOUT << message << " initialized as " << filename << '\n';
2033                 else VOUT << "Old " << message << " file moved to " << backupname << '\n';
2034         }
2035         return true;
2036 }
int BigRegex_freq (String & str, const char * rxstr)
Definition at line 1809 of file utilities.cc.
Referenced by Assess_Paper_Correction_Time(), BigRegex_freq(), and decide_add_TL_chunk().
1809                                                     {
1810         BigRegex rx(rxstr);
1811         return BigRegex_freq(str,rx);
1812 }
int BigRegex_freq (String & str, String rxstr)
Definition at line 1804 of file utilities.cc.
References BigRegex_freq().
1804                                               {
1805         BigRegex rx(rxstr);
1806         return BigRegex_freq(str,rx);
1807 }
int BigRegex_freq (String & str, const BigRegex & rx)
Definition at line 1798 of file utilities.cc.
References String::index(), and String::SEARCH_END.
1798                                                      {
1799         int i = 0, cnt = 0;
1800         while ((i=str.index(rx,String::SEARCH_END,i))>=0) cnt++;
1801         return cnt;
1802 }
bool confirmation (String message, char nondefault)
Definition at line 1907 of file utilities.cc.
Referenced by extract_hierarchy_depth_decrease_to_paper(), extract_hierarchy_depth_increase_to_paper(), extract_recursively(), extract_required_item_to_paper(), financial_notes(), select_TL_DIL_refs(), and stop_TL_chunk().
1907                                                    {
1908 // requests confirmation, returns false if the response is nondefault
1909         const int LLEN = 16;
1910         char lbuf[LLEN];
1911         cout << message;
1912         cin.getline(lbuf,LLEN);
1913         return (lbuf[0]!=nondefault);
1914 }
int copy_until_line (ifstream * lf, ofstream * of, const char * pattern, char * lbuf, int llen)
Definition at line 2248 of file utilities.cc.
References EOUT.
Referenced by create_new_DIL(), make_note(), and send_dil_to_DIL().
2248                                                                                                {
2249 // returns 1 if line was encountered, 0 if not, and <0 for errors
2250 // the line containing pattern is not copied, but is returned in lbuf
2251         regex_t re;
2252         int mres;
2253         if (!lf) {
2254                 EOUT << "dil2al: input file not open in copy_until_line()\n";
2255                 return -1;
2256         }
2257         if (!of) {
2258                 EOUT << "dil2al: output file not open in copy_until_line()\n";
2259                 return -1;
2260         }
2261         if (regcomp(&re,pattern, REG_EXTENDED|REG_NOSUB) != 0) {
2262                 EOUT << "dil2al: Unable to compile regular expression in copy_until_line()\n";
2263                 return -2;
2264         }
2265         mres = 1;
2266         cout << "dil2al WARNING: copy_until_line(<from>,<to>," << pattern << ",<lbuf>,<llen>) may be broken as EOF is not detected when line length exceeds llen=" << llen << ", this code should use BigRegex functions instead!\n";
2267         while (mres!=0) {
2268                 if (lf->eof()) {
2269                         regfree(&re);
2270                         return 0;
2271                 }
2272                 lf->getline(lbuf,llen);
2273                 mres = regexec(&re,lbuf, (size_t) 0, NULL, 0);
2274                 if ((mres != 0) && (mres != REG_NOMATCH)) {
2275                         EOUT << "dil2al: Internal error while matching in copy_until_line()\n";
2276                         regfree(&re);
2277                         return -3;
2278                 }
2279                 if (mres!=0) (*of) << lbuf << endl;
2280         }
2281         regfree(&re);
2282         return 1;
2283 }
int D2A_get_tag (String & d2astr, int strloc, String d2atag, String & tagtext)
Definition at line 2396 of file utilities.cc.
References String::at(), EOUT, String::index(), BigRegex::match_info(), and String::SEARCH_END.
Referenced by Assess_Paper_Correction_Time().
2396                                                                               {
2397 // searches for a dil2al standardized tag with the specific regex
2398 // id d2atag and returns the corresponding specific information
2399 // in tagtext, as well as the position in d2astr immediately
2400 // following the tag
2401         BigRegex tm('@'+d2atag+":\\([^@]*\\)@");
2402         if ((strloc=d2astr.index(tm,String::SEARCH_END,strloc))>=0) {
2403                 int s,l;
2404                 if (!tm.match_info(s,l,1)) return -1;
2405                 if (l==0) EOUT << "dil2al: Warning - Non-specific tag at " << s << " in D2A_get_tag(), continuing\n";
2406                 tagtext = d2astr.at(s,l);
2407         }
2408         return strloc;
2409 }
String date_string ()
Definition at line 1852 of file utilities.cc.
References time_stamp().
Referenced by dil2al_commands(), and main().
1852                      {
1853         return time_stamp("%Y%m%d");
1854 }
int DIL_entry_target_date_qsort_compare (const void * vde1, const void * vde2)
Definition at line 1774 of file utilities.cc.
References MAXTIME_T.
Referenced by Detailed_Items_List::Sort_by_Target_Date().
1774                                                                               {
1775 // used with qsort() (<stdlib.h>)
1776 // Treats unspecified self-referential target dates as MAXTIME
1777 // for the ordering of the corresponding DIL entry  - and avoids
1778 // the accompanying warning messages.
1779 // (This is useful when groups of DIL entries with desired
1780 // target dates are sorted, in which some DIL entries are marked
1781 // with -2 codes).
1782 // Note: ISO C++ is strict about providing the correct function
1783 // declaration in cases such as the call to qsort(). This function
1784 // was therefore rewritten from the original declaration,
1785 // DIL_entry_target_date_qsort_compare(DIL_entry ** de1, DIL_entry ** de2)
1786 // - please keep in mind that the elements are of type DIL_entry **,
1787 // i.e. arrays/pointers of pointers to objects.
1788         DIL_entry ** de1 = (DIL_entry **) vde1;
1789         DIL_entry ** de2 = (DIL_entry **) vde2;
1790         time_t t1 = MAXTIME_T, t2 = MAXTIME_T;
1791         if (*de1) t1 = (*de1)->Propagated_Target_Date(false);
1792         if (*de2) t2 = (*de2)->Propagated_Target_Date(false);
1793         if (t1==t2) return 0;
1794         if (t1<t2) return -1;
1795         return 1;
1796 }
time_t double2time (double t)
Definition at line 1893 of file utilities.cc.
Referenced by DIL_entry::Get_Entry_Parameters().
1893                              {
1894         struct tm td;
1895         td.tm_sec = 0; // seconds not explicit
1896         td.tm_min = (int) fmod(t,100.0); t /= 100.0;
1897         td.tm_hour = (int) fmod(t,100.0); t /= 100.0;
1898         td.tm_mday = (int) fmod(t,100.0); t /= 100.0;
1899         td.tm_mon = ((int) fmod(t,100.0))-1; t /= 100.0;
1900         td.tm_year = ((int) t)-1900;
1901         td.tm_wday = 0;
1902         td.tm_yday = 0;
1903         td.tm_isdst = 0;
1904         return mktime(&td);
1905 }
int Elipsis_At (String & s, int maxsize)
Definition at line 2634 of file utilities.cc.
References String::before(), and String::length().
Referenced by AL_Passed_Target_Dates(), generate_AL(), Active_List::generate_focused_AL(), generate_modify_element_FORM_interface_DIL_Superiors(), Active_List::generate_wide_AL(), update_main_ALs(), DIL_Visualize_with_FORM_Tabs::Visualize_Element(), and DIL_Visualize_with_HTML_Tabs::Visualize_Element().
2634                                         {
2635 // returns the length of the resulting string
2636         if (s.length()>maxsize) {
2637                 s = s.before(maxsize);
2638                 s = s.before(BigRegex("[        \n.,;:]"),-1);
2639                 s += "...";
2640         }
2641         return s.length();
2642 }
bool file_is_directory (String filepath)
Definition at line 1988 of file utilities.cc.
References EOUT.
Referenced by Get_Target_Directory(), search_cmd(), and Target_Access::set_target().
1988                                         {
1989         struct stat fs;
1990         if (stat(filepath,&fs)!=0) {
1991                 if (verbose) EOUT << "dil2al: Error reading file attributes of " << filepath << "in file_is_directory()\n";
1992                 return false;
1993         }
1994         return S_ISDIR(fs.st_mode);
1995 }
bool file_is_regular (String filepath)
Definition at line 1970 of file utilities.cc.
References EOUT.
1970                                       {
1971         struct stat fs;
1972         if (stat(filepath,&fs)!=0) {
1973                 if (verbose) EOUT << "dil2al: Error reading file attributes of " << filepath << " in file_is_regular()\n";
1974                 return false;
1975         }
1976         return S_ISREG(fs.st_mode);
1977 }
bool file_is_regular_or_symlink (String filepath)
Definition at line 1979 of file utilities.cc.
References EOUT.
Referenced by Get_Target_Directory().
1979                                                  {
1980         struct stat fs;
1981         if (stat(filepath,&fs)!=0) {
1982                 if (verbose) EOUT << "dil2al: Error reading file attributes of " << filepath << "in file_is_regular_or_symlink()\n";
1983                 return false;
1984         }
1985         return (S_ISREG(fs.st_mode) || (S_ISLNK(fs.st_mode)));
1986 }
int find_delimiter (String & str, int startpos, int lenlimit, char delimiter = '\n') [inline]
Definition at line 2158 of file utilities.cc.
References String::index().
Referenced by Detailed_Items_List::Get_Project_Data().
2158                                                                                            {
2159         int delimpos = str.index(delimiter,startpos);
2160         if (delimpos>=lenlimit) return -1;
2161         return delimpos;
2162 }
int find_in_line (ifstream * lf, const char * pattern, int nsub, String * dilid, const char * before, char * lbuf, int llen)
Definition at line 2285 of file utilities.cc.
References EOUT.
Referenced by add_new_to_DIL(), get_active_DIL_IDs(), and select_TL_AL_refs().
2285                                                                                                                             {
2286 // takes an open ifstream and searches for the regex pattern with nsub subexpressions
2287 // before a line with the ``before'' pattern (NULL = EOF)
2288 // returns substrings in dilid and the return value
2289 // 1 (found ``pattern''), 0 (found ``before''), -1 (EOF),
2290 // -2 (wrong #substrings), -3 (regex error) -4 (file not open)
2291         const int SLEN = 1024;
2292         char sbuf[SLEN];
2293         regex_t re,be;
2294         regmatch_t * rm;
2295         int mres;
2296         bool done;
2297         if (*lf) {
2298                 if (nsub) rm = new regmatch_t[nsub];
2299                 else rm = NULL;
2300                 if (regcomp(&re,pattern, REG_EXTENDED) != 0) {
2301                         EOUT << "dil2al: Unable to compile ``pattern'' regular expression in find_in_line()\n";
2302                         return -3;
2303                 }
2304                 if (before) {
2305                         if (regcomp(&be,before, REG_EXTENDED|REG_NOSUB) != 0) {
2306                                 regfree(&re);
2307                                 EOUT << "dil2al: Unable to compile ``before'' regular expression in find_in_line()\n";
2308                                 return -3;
2309                         }
2310                 }
2311                 done = false;
2312                 while (!done) {
2313                         if (lf->eof()) { mres = 2; done=true; }
2314                         else {
2315                                 lf->getline(lbuf,llen);
2316                                 if (before) mres = regexec(&be,lbuf, (size_t) 0, NULL, 0);
2317                                 if ((before) && (mres != 0) && (mres != REG_NOMATCH)) {
2318                                         EOUT << "dil2al: Internal error while matching ``before'' in find_in_line()\n";
2319                                         mres = 4; done = true;
2320                                 } else {
2321                                         if ((before) && (mres==0)) { mres = 1; done = true; }
2322                                         else {
2323                                                 mres = regexec(&re,lbuf, (size_t) nsub, rm, 0);
2324                                                 if ((mres != 0) && (mres != REG_NOMATCH)) {
2325                                                         EOUT << "dil2al: Internal error while matching ``pattern'' in find_in_line()\n";
2326                                                         mres = 4; done = true;
2327                                                 } else {
2328                                                         if (!mres) {
2329                                                                 done = true;
2330                                                                 if (nsub) {
2331                                                                         if (rm[nsub-1].rm_so==-1) {
2332                                                                                 EOUT << "dil2al: Wrong number of substring matches in find_in_line()\n";
2333                                                                                 mres = 3;
2334                                                                         } else {
2335                                                                                 for (int i=0; i<nsub; i++) {
2336                                                                                         strncpy(sbuf,&lbuf[rm[i].rm_so],rm[i].rm_eo-rm[i].rm_so);
2337                                                                                         sbuf[rm[i].rm_eo-rm[i].rm_so]='\0';
2338                                                                                         dilid[i] = sbuf;
2339                                                                                 }
2340                                                                         }
2341                                                                 }
2342                                                         }
2343                                                 }
2344                                         }
2345                                 }
2346                         }
2347                 }
2348                 regfree(&re);
2349                 regfree(&be);
2350                 if (nsub) delete[] rm;
2351                 return (-mres) + 1;
2352         } else {
2353                 EOUT << "dil2al: file not open in find_in_line()\n";
2354                 return -4;
2355         }
2356 }
bool find_line (ifstream * lf, const char * pattern, char * lbuf, int llen)
Definition at line 2217 of file utilities.cc.
References EOUT.
Referenced by add_new_to_DIL(), get_active_DIL_IDs(), get_topic_keywords(), make_note(), Topical_DIL_Files::Refresh(), select_TL_AL_refs(), and select_TL_DIL_refs().
2217                                                                            {
2218 // takes an open ifstream and searches for the regex pattern
2219         regex_t re;
2220         int mres;
2221         if (*lf) {
2222                 if (regcomp(&re,pattern, REG_EXTENDED|REG_NOSUB) != 0) {
2223                         EOUT << "dil2al: Unable to compile regular expression in find_line()\n";
2224                         return false;
2225                 }
2226                 mres = 1;
2227                 while (mres!=0) {
2228                         if (lf->eof()) {
2229                                 regfree(&re);
2230                                 return false;
2231                         }
2232                         lf->getline(lbuf,llen);
2233                         mres = regexec(&re,lbuf, (size_t) 0, NULL, 0);
2234                         if ((mres != 0) && (mres != REG_NOMATCH)) {
2235                                 EOUT << "dil2al: Internal error while matching in find_line()\n";
2236                                 regfree(&re);
2237                                 return false;
2238                         }
2239                 }
2240                 regfree(&re);
2241                 return true;
2242         } else {
2243                 EOUT << "dil2al: file not open in find_line()\n";
2244                 return false;
2245         }
2246 }
double get_double (String valstr, double defval = 0.0, bool * gotdouble = NULL)
Definition at line 2685 of file utilities.cc.
References String::empty(), and String::matches().
Referenced by modify_element_through_FORM_interface(), and modify_element_through_FORM_interface_DIL_Superiors().
2685                                                                                {
2686   // attempts to extract a double variable value from a string
2687   // if no double variable value is found then the value defval is assigned
2688   bool gotdoubledummy;
2689   if (!gotdouble) gotdouble = &gotdoubledummy;
2690   if (valstr.empty()) { (*gotdouble) = false; return defval; }
2691   if (((*gotdouble)=valstr.matches(BRXdouble))==true) return atof((const char *) valstr);
2692   else return defval;
2693 }
int get_file_in_list (String & fname, StringList & srcf, StringList & srcfname, int & srcfnum)
Definition at line 2101 of file utilities.cc.
References EOUT, StringList::iselement(), and read_file_into_String().
Referenced by extract_hierarchy_depth_decrease_to_paper(), extract_hierarchy_depth_increase_to_paper(), extract_recursively(), Text_File_Buffers::FileIndex(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), Detailed_Items_List::Get_All_Topical_DIL_Parameters(), get_figure_data(), and update_DIL_entry_elements().
2101                                                                                              {
2102 // load a file if it is not already in a list of file-strings
2103         int srcidx;
2104         if ((srcidx = srcfname.iselement(fname))<0) {
2105                 if (!read_file_into_String(fname,srcf[srcfnum])) {
2106                         EOUT << "dil2al: Unable to load source document " << fname << " in get_file_in_list()\n";
2107                         return -1;
2108                 }
2109                 srcfname[srcfnum] = fname;
2110                 srcidx = srcfnum;
2111                 srcfnum++;
2112         }
2113         return srcidx;
2114 }
int HTML_get_href (String & htmlstr, int strloc, String & hrefurl, String & hreftext, int * hrefstart = NULL)
Definition at line 2483 of file utilities.cc.
References String::at(), EOUT, String::index(), BigRegex::match_info(), and String::SEARCH_END.
Referenced by generate_modify_element_FORM_interface_DIL_entry_content(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), Plan_entry_content::Parse_Entry_Content(), remove_AL_TC(), select_TL_DIL_refs(), and update_main_ALs().
2483                                                                                                              {
2484 // *** warning, this function can't deal properly yet with HREFs that contain
2485 //     HTML font formatting commands (e.g. <B>) in the reference text!
2486         const BigRegex h("[<][Aa][      ]+[^>]*[Hh][Rr][Ee][Ff][        ]*=[    ]*\"\\([^\"]*\\)\"[^>]*[>]\\([^<]*\\)[<]/[Aa][  ]?[^>]*[>]");
2487         if ((strloc=htmlstr.index(h,String::SEARCH_END,strloc))>=0) {
2488                 int s,l;
2489                 if (hrefstart) {
2490                   if (!h.match_info(s,l,0)) return -1;
2491                   else *hrefstart = s;
2492                 }
2493                 if (!h.match_info(s,l,1)) return -1;
2494                 if (l==0) {
2495                         EOUT << "dil2al: Missing HREF URL at " << s << " in HTML_get_href()\n";
2496                         return -1;
2497                 }
2498                 hrefurl = htmlstr.at(s,l);
2499                 if (!h.match_info(s,l,2)) return -1;
2500                 if (l==0) EOUT << "dil2al: Warning - Invisible HREF anchor at " << s << " in HTML_get_href(), continuing\n";
2501                 hreftext = htmlstr.at(s,l);
2502         }
2503         return strloc;
2504 }
int HTML_get_list (String & htmlstr, int strloc, String & listparams, String & listcontent, int * liststart = NULL)
Definition at line 2469 of file utilities.cc.
References HTML_get_tagged_environment().
Referenced by Plan_entry_content::Parse_Entry_Content(), and update_main_ALs().
2469                                                                                                                    {
2470         const BigRegex lm("[<][UuOo][Ll]");
2471         const BigRegex l("\\([<]/[UuOo][Ll]\\|[<]/[Tt][Aa][Bb][Ll][Ee]\\|[<]/[Bb][Oo][Dd][Yy]\\|[<]/[Hh][Tt][Mm][Ll]\\)");
2472         const BigRegex le("[<]/[UuOo][Ll][^>][>]"); 
2473         return HTML_get_tagged_environment(lm,l,le,htmlstr,strloc,listparams,listcontent,liststart);
2474 }
int HTML_get_list_item (String & htmlstr, int strloc, String & itemparams, String & itemcontent, int * itemstart = NULL)
Definition at line 2476 of file utilities.cc.
References HTML_get_tagged_environment().
Referenced by Plan_entry_content::Parse_Entry_Content(), and update_main_ALs().
2476                                                                                                                         {
2477         const BigRegex im("[<][Ll][Ii]");
2478         const BigRegex i("\\([<]/?[Ll][Ii]\\|[<]/[UuOo][Ll]\\|[<]/[Tt][Aa][Bb][Ll][Ee]\\|[<]/[Bb][Oo][Dd][Yy]\\|[<]/[Hh][Tt][Mm][Ll]\\)");
2479         const BigRegex ie("[<]/[Ll][Ii][^>][>]");
2480         return HTML_get_tagged_environment(im,i,ie,htmlstr,strloc,itemparams,itemcontent,itemstart);
2481 }
int HTML_get_marker (String & htmlstr, int strloc, String & marker, bool locate = true)
Definition at line 2411 of file utilities.cc.
References String::at(), String::index(), String::length(), and BigRegex::match_info().
Referenced by HTML_get_tagged_environment().
2411                                                                                       {
2412         const BigRegex m("[<][^>]+[>]");
2413         // find start of marker
2414         if (locate) {
2415                 if ((strloc=htmlstr.index(m,strloc))<0) return -1;
2416                 // get marker
2417                 int s,l;
2418                 m.match_info(s,l,0);
2419                 marker = htmlstr.at(s,l);
2420                 return strloc+l;
2421         }
2422         // get marker
2423         marker = htmlstr.at(m,strloc); // assumes marker starts at strloc
2424         return strloc+marker.length();
2425 }
int HTML_get_name (String & htmlstr, int strloc, String & nametag, String & nametext)
Definition at line 2506 of file utilities.cc.
References String::at(), EOUT, String::index(), BigRegex::match_info(), and String::SEARCH_END.
Referenced by Detailed_Items_List::Get_All_Topical_DIL_Parameters(), and update_main_ALs().
2506                                                                                      {
2507         const BigRegex n("[<][Aa][      ]+[^>]*[Nn][Aa][Mm][Ee][        ]*=[    ]*\"\\([^\"]*\\)\"[^>]*[>]\\([^<]*\\)[<]/[Aa][  ]?[^>]*[>]");
2508         if ((strloc=htmlstr.index(n,String::SEARCH_END,strloc))>=0) {
2509                 int s,l;
2510                 if (!n.match_info(s,l,1)) return -1;
2511                 if (l==0) {
2512                         EOUT << "dil2al: Missing NAME tag at " << s << " in HTML_get_name()\n";
2513                         return -1;
2514                 }
2515                 nametag = htmlstr.at(s,l);
2516                 if (!n.match_info(s,l,2)) return -1;
2517                 if (l==0) EOUT << "dil2al: Warning - Invisible NAME anchor at " << s << " in HTML_get_name(), continuing\n";
2518                 nametext = htmlstr.at(s,l);
2519         }
2520         return strloc;
2521 }
int HTML_get_table_cell (String & htmlstr, int strloc, String & cellparams, String & cellcontent, int * cellstart = NULL)
Definition at line 2455 of file utilities.cc.
References HTML_get_tagged_environment().
Referenced by Financial_Note::get(), get_AL_entry(), Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), Detailed_Items_List::Get_All_Topical_DIL_Parameters(), select_TL_DIL_refs(), and update_DIL_entry_elements().
2455                                                                                                                          {
2456         const BigRegex cm("[<][Tt][Dd]");
2457         const BigRegex c("\\([<]/?[Tt][DdRr]\\|[<]/[Tt][Aa][Bb][Ll][Ee]\\|[<]/[Bb][Oo][Dd][Yy]\\|[<]/[Hh][Tt][Mm][Ll]\\)");
2458         const BigRegex ce("[<]/[Tt][Dd][^>]*[>]");
2459         return HTML_get_tagged_environment(cm,c,ce,htmlstr,strloc,cellparams,cellcontent,cellstart);
2460 }
int HTML_get_table_row (String & htmlstr, int strloc, String & rowparams, String & rowcontent, int * rowstart = NULL)
Definition at line 2462 of file utilities.cc.
References HTML_get_tagged_environment().
Referenced by Financial_Note::get(), get_AL_entry(), Detailed_Items_List::Get_All_Topical_DIL_Parameters(), and Detailed_Items_List::Write_to_File().
2462                                                                                                                      {
2463         const BigRegex rm("[<][Tt][Rr]");
2464         const BigRegex r("\\([<]/?[Tt][Rr]\\|[<]/[Tt][Aa][Bb][Ll][Ee]\\|[<]/[Bb][Oo][Dd][Yy]\\|[<]/[Hh][Tt][Mm][Ll]\\)");
2465         const BigRegex re("[<]/[Tt][Rr][^>][>]");
2466         return HTML_get_tagged_environment(rm,r,re,htmlstr,strloc,rowparams,rowcontent,rowstart);
2467 }
int HTML_get_tagged_environment (const BigRegex & begintag, const BigRegex & endmatch, const BigRegex & endtag, String & htmlstr, int strloc, String & envparams, String & envcontent, int * envstart = NULL)
Definition at line 2433 of file utilities.cc.
References String::at(), HTML_get_marker(), String::index(), String::length(), and String::SEARCH_END.
Referenced by HTML_get_list(), HTML_get_list_item(), HTML_get_table_cell(), and HTML_get_table_row().
2433                                                                                                                                                                                                              {
2434 // searches for an environment beginning with a tag matching begintag,
2435 // determines the environment end according to possible matches in endmatch,
2436 // returns tag parameters in envparams, environment contents in envcontent,
2437 // optionally returns the start of the environment in envstart, and
2438 // returns the position directly after the environment and a potential
2439 // endtag
2440         // find start of environment
2441         if ((strloc=htmlstr.index(begintag,strloc))<0) return -1;
2442         if (envstart) (*envstart) = strloc;
2443         // get environment tag parameters
2444         if ((strloc=HTML_get_marker(htmlstr,strloc,envparams,false))<0) return -1;
2445         // get environment content
2446         int envend = htmlstr.index(endmatch,strloc);
2447         if (envend<0) envend = htmlstr.length();
2448         envcontent = htmlstr.at(strloc,envend-strloc);
2449         // skip possible end tag
2450         int envendtagend = htmlstr.index(endtag,String::SEARCH_END,envend);
2451         if (envendtagend>=0) envend = envendtagend;
2452         return envend;
2453 }
String HTML_marker_arguments (String & marker)
Definition at line 2427 of file utilities.cc.
References String::before(), String::from(), String::length(), and res.
Referenced by Detailed_Items_List::Write_to_File().
2427                                               {
2428         const BigRegex a("[     ]");
2429         String res = marker.from(a); if (res.length()>=1) res = res.before((int) res.length()-1);
2430         return res;
2431 }
String HTML_put_form (String formmethod, String formaction, String formcontent)
Definition at line 2593 of file utilities.cc.
Referenced by AL_Passed_Target_Dates().
2593                                                                                {
2594         return "<FORM METHOD="+formmethod+" ACTION=\""+formaction+"\">"+formcontent+"</FORM>";
2595 }
String HTML_put_form_checkbox (String checkboxname, String checkboxvalue, String checkboxtext, bool checked = false)
Definition at line 2617 of file utilities.cc.
References HTML_put_form_input().
Referenced by AL_Passed_Target_Dates(), generate_AL(), and generate_EPS_cells().
2617                                                                                                                     {
2618         String checkedstr;
2619         if (checked) checkedstr = "\" checked"; else checkedstr = "\"";
2620         return HTML_put_form_input("checkbox","name=\""+checkboxname+"\" value=\""+checkboxvalue+checkedstr)+' '+checkboxtext;
2621 }
String HTML_put_form_input (String inputtype, String inputargs)
Definition at line 2597 of file utilities.cc.
References String::length().
Referenced by AL_Passed_Target_Dates(), HTML_put_form_checkbox(), HTML_put_form_radio(), HTML_put_form_reset(), HTML_put_form_submit(), and HTML_put_form_text().
2597                                                                {
2598         String inputstr("<INPUT type=\""+inputtype+'"');
2599         if (inputargs.length()>0) return inputstr+' '+inputargs+'>';
2600         else return inputstr+'>';
2601 }
String HTML_put_form_radio (String radioname, String radiovalue, String radiotext, bool checked = false)
Definition at line 2611 of file utilities.cc.
References HTML_put_form_input().
Referenced by AL_Passed_Target_Dates(), and generate_modify_element_FORM_interface_DIL_Superiors().
2611                                                                                                         {
2612         String checkedstr;
2613         if (checked) checkedstr = "\" checked"; else checkedstr = "\"";
2614         return HTML_put_form_input("radio","name=\""+radioname+"\" value=\""+radiovalue+checkedstr)+' '+radiotext;
2615 }
String HTML_put_form_reset ()
Definition at line 2607 of file utilities.cc.
References HTML_put_form_input().
Referenced by AL_Passed_Target_Dates().
2607                              {
2608         return HTML_put_form_input("reset","");
2609 }
String HTML_put_form_submit (String submittext)
Definition at line 2603 of file utilities.cc.
References HTML_put_form_input().
Referenced by AL_Passed_Target_Dates().
2603                                                {
2604         return HTML_put_form_input("submit","value=\""+submittext+'"');
2605 }
String HTML_put_form_text (String textname, long maxlen = -1)
Definition at line 2630 of file utilities.cc.
Referenced by AL_Passed_Target_Dates(), generate_AL(), and generate_EPS_cells().
2630                                                              {
2631         return HTML_put_form_text(textname,"",maxlen);
2632 }
String HTML_put_form_text (String textname, String textvalue, long maxlen = -1)
Definition at line 2623 of file utilities.cc.
References HTML_put_form_input(), and String::length().
2623                                                                                {
2624         textname += '"';
2625         if (textvalue.length()>0) textname += " value=\"" + textvalue + '"';
2626         if (maxlen>0) textname += " maxlength=" + String(maxlen);
2627         return HTML_put_form_input("text","name=\""+textname);
2628 }
String HTML_put_href (String hrefurl, String hreftext)
Definition at line 2585 of file utilities.cc.
Referenced by AL_Day_Marker(), AL_Passed_Target_Dates(), generate_AL(), Active_List::generate_focused_AL(), generate_modify_element_FORM_interface_DIL_entry_content(), generate_modify_element_FORM_interface_DIL_entry_parameters(), Active_List::generate_wide_AL(), Target_Access::make_local_copy_of_directory(), update_main_ALs(), DIL_Visualize_with_FORM_Tabs::Visualize_Element(), DIL_Visualize_with_HTML_Tabs::Visualize_Element(), and Detailed_Items_List::Write_to_File().
2585                                                       {
2586         return "<A HREF=\""+hrefurl+"\">"+hreftext+"</A>";
2587 }
String HTML_put_list (char listtype, String htmlstr)
Definition at line 2577 of file utilities.cc.
References HTML_put_structure().
Referenced by update_main_ALs().
2577                                                    {
2578         return HTML_put_structure(listtype+String("L"),"",htmlstr);
2579 }
String HTML_put_list_item (String htmlstr, bool relaxedhtml = false)
Definition at line 2581 of file utilities.cc.
References HTML_put_structure().
Referenced by Active_List::generate_wide_AL(), and update_main_ALs().
2581                                                                     {
2582         return HTML_put_structure("LI","",htmlstr,relaxedhtml);
2583 }
String HTML_put_name (String nametag, String nametext)
Definition at line 2589 of file utilities.cc.
Referenced by Detailed_Items_List::Write_to_File().
2589                                                       {
2590         return "<A NAME=\""+nametag+"\">"+nametext+"</A>";
2591 }
String HTML_put_structure (String tag, String params, String content, bool relaxedhtml = false)
Definition at line 2561 of file utilities.cc.
References String::prepend().
Referenced by HTML_put_list(), HTML_put_list_item(), HTML_put_table_cell(), and HTML_put_table_row().
2561                                                                                                {
2562         params.prepend('<'+tag);
2563         params += '>'+content;
2564         if (relaxedhtml) return params;
2565         params += "</"+tag+">\n";
2566         return params;
2567 }
String HTML_put_table_cell (String cellparams, String cellcontent, bool relaxedhtml = false)
Definition at line 2573 of file utilities.cc.
References HTML_put_structure().
Referenced by AL_Day_Marker(), generate_AL(), generate_EPS_cells(), Active_List::generate_focused_AL(), Financial_Note::put(), update_DIL_entry_elements(), and Detailed_Items_List::Write_to_File().
2573                                                                                             {
2574         return HTML_put_structure("TD",cellparams,cellcontent,relaxedhtml);
2575 }
String HTML_put_table_row (String rowparams, String rowcontent, bool relaxedhtml = false)
Definition at line 2569 of file utilities.cc.
References HTML_put_structure().
Referenced by AL_Day_Marker(), generate_AL(), Active_List::generate_focused_AL(), Financial_Note::put(), remove_AL_TC(), and Detailed_Items_List::Write_to_File().
2569                                                                                          {
2570         return HTML_put_structure("TR",rowparams,rowcontent,relaxedhtml);
2571 }
String* HTML_remove_comments (String & htmlstr)
Definition at line 2530 of file utilities.cc.
References String::alloc(), String::at(), String::index(), String::length(), res, and String::SEARCH_END.
Referenced by Detailed_Items_List::Get_All_DIL_ID_File_Parameters(), and Plan_entry_content::Parse_Entry_Content().
2530                                                 {
2531   int cidx, cend = 0; String res;
2532   res.alloc(htmlstr.length());
2533   while ((cidx=htmlstr.index("<!--",cend))>=0) {
2534     if (cidx>cend) res += htmlstr.at(cend,cidx-cend);
2535     if ((cend=htmlstr.index(BigRegex("--[       ]*[>]"),String::SEARCH_END,cidx))<0) cend=htmlstr.length();
2536   }
2537   cidx=htmlstr.length();
2538   if (cidx>cend) res += htmlstr.at(cend,cidx-cend);
2539   htmlstr = res;
2540   return &htmlstr;
2541 }
String* HTML_remove_tags (String & htmlstr)
Definition at line 2555 of file utilities.cc.
References String::gsub().
Referenced by AL_Passed_Target_Dates(), generate_AL(), Active_List::generate_focused_AL(), generate_modify_element_FORM_interface_DIL_Superiors(), Active_List::generate_wide_AL(), Detailed_Items_List::Get_All_Topical_DIL_Parameters(), select_TL_DIL_refs(), update_DIL_entry_elements(), DIL_Visualize_with_FORM_Tabs::Visualize_Element(), DIL_Visualize_with_HTML_Tabs::Visualize_Element(), and DIL_Visualize_with_Tabs::Visualize_Element().
2555                                             {
2556         const BigRegex m("[<][^>]+[>]");
2557         htmlstr.gsub(m,"");
2558         return &htmlstr;
2559 }
String* HTML_safe (String & textstr)
Definition at line 2523 of file utilities.cc.
References String::gsub().
Referenced by Search_Result::HTML_put_text().
2523                                      {
2524         textstr.gsub("&","&amp;");
2525         textstr.gsub("<","&lt;");
2526         textstr.gsub(">","&gt;");
2527         return &textstr;
2528 }
bool initialize_new_DIL_TL (String initializecmd, bool includeinput)
Definition at line 2358 of file utilities.cc.
References DIN, EOUT, generate_TL_chunk_header(), generate_TL_entry_header(), get_new_DIL_ID(), and read_data_from_stream().
Referenced by dil2al_commands().
2358                                                                     {
2359 // sends a DIL template with a new DIL ID, or a Task Log chunk or entry template to stdout
2360         if (initializecmd=="tc") { // initialize Task Log chunk
2361                 cout << generate_TL_chunk_header("{"+curtime+"}","{relative-active-list-url}","{Active List Title}","{#tag-previous-AL-head}","relative-DIL-url","DIL Title/Non-DIL Identifying Comment","#tag-previous-DIL-head",-1) << "<!-- edit items in ``{}'' brackets";
2362                 if (!includeinput) cout << " and add entries here";
2363                 cout << " then close chunk -->\n";
2364         } else if (initializecmd=="te") { // initialize Task Log entry
2365                 cout << generate_TL_entry_header("{"+curtime+"}.{1}","{relative-active-list-url}","{Active List Title}","{#tag-previous-AL-head}","relative-DIL-url","DIL Title/Non-DIL Identifying Comment","#tag-previous-DIL-head") << "<!-- edit items in ``{}'' brackets";
2366                 if (!includeinput) cout << " and add content here";
2367                 cout << " -->\n";
2368         } else { // initialize DIL entry
2369                 String newdilid = get_new_DIL_ID();
2370                 if (newdilid=="") {
2371                         EOUT << "dil2al: Unable to generate new DIL ID in initialize_new_DIL_TL()\n";
2372                         return false;
2373                 }
2374                 cout << "<TR BGCOLOR=\"#00005F\">\n<TD WIDTH=\"15%\"><A NAME=\""
2375                         << newdilid << "\" HREF=\"detailed-items-by-ID.html#"
2376                         << newdilid << "\">" << newdilid
2377                         << "</A>\n<TD><B>time started:</B> - <B>time required:</B> ?.?hrs <B>completion ratio:</B> 0.0 <B>valuation:</B> ?.?\n<TR>\n<TD COLSPAN=2>";
2378         }
2379         if (includeinput) {
2380                 const int LLEN = 10240;
2381                 char lbuf[LLEN];
2382                 String dentrybuf;
2383                 read_data_from_stream(DIN,dentrybuf,"@End of DIL entry@");
2384                 cout << dentrybuf;
2385         }
2386         if (initializecmd=="tc") { // Task Log chunk
2387                 cout << generate_TL_chunk_header("","","","","","","",1);
2388         } else if (initializecmd=="te") { // Task Log entry
2389                 cout << "<P>\n\n";
2390         } else { // DIL entry
2391                 cout << "\n\n";
2392         }
2393         return true;
2394 }
String Int2HexStr (unsigned int i)
Definition at line 2666 of file utilities.cc.
References String::prepend().
2666                                   {
2667   // convert integer to hexadecimal string
2668   String s;
2669   if (i==0) s = "0";
2670   else {
2671     while (i>0) {
2672       int j = i % 16; i = i / 16;
2673       if (j<10) s.prepend(('0'+(char) j));
2674       else s.prepend(('A'+(char) (j-10)));
2675     }
2676   }
2677   return s;
2678 }
bool Lock_File (String lockfile, String msgstr)
Definition at line 1399 of file utilities.cc.
References EOUT, and prepare_temporary_file().
Referenced by Detailed_Items_List::Read_from_Binary_Cache(), Detailed_Items_List::Read_Topical_from_Binary_Cache(), Detailed_Items_List::Write_to_Binary_Cache(), and Detailed_Items_List::Write_Topical_to_Binary_Cache().
1399                                                {
1400   // check for lock file
1401   struct stat statbuf;
1402   if (stat(lockfile,&statbuf)!=-1) EOUT << "dil2al: Warning - lock file " << lockfile <<  " in use by other process, waiting for release of lock in Lock_File()\n";
1403   while (stat(lockfile,&statbuf)!=-1) sleep(5);
1404   // lock and write to binary cache file
1405   return prepare_temporary_file(lockfile,msgstr);
1406 }
bool pattern_in_line (const char * pattern, char * lbuf)
Definition at line 2164 of file utilities.cc.
References EOUT.
Referenced by add_new_to_DIL(), get_active_DIL_IDs(), Topical_DIL_Files::Refresh(), and Set_Parameter().
2164                                                         {
2165         regex_t re;
2166         int mres;
2167         if (regcomp(&re,pattern, REG_EXTENDED|REG_NOSUB) != 0) {
2168                 EOUT << "dil2al: Unable to compile regular expression in pattern_in_line()\n";
2169                 return false;
2170         }
2171         mres = regexec(&re,lbuf, (size_t) 0, NULL, 0);
2172         regfree(&re);
2173         if ((mres != 0) && (mres != REG_NOMATCH)) {
2174                 EOUT << "dil2al: Internal error while matching in pattern_in_line()\n";
2175                 return false;
2176         }
2177         return (mres==0);
2178 }
bool prepare_temporary_file (String tmpfile, String initstr)
Definition at line 1997 of file utilities.cc.
References EOUT.
Referenced by Lock_File(), and make_note().
1997                                                             {
1998 // Can be used to create temporary files (e.g. the dilref or,
1999 // note or DIL entry stubs), and automatically back up the
2000 // previous file if it exists. The stub is filled with the
2001 // content of initstr and closed.
2002         if (rename(tmpfile,tmpfile+".bak")<0) if (errno!=ENOENT) {
2003                 EOUT << "dil2al: Unable to rename " << tmpfile << " to " << tmpfile+".bak in prepare_temporary_file()\n";
2004                 return false;
2005         }
2006         ofstream ntf(tmpfile);
2007         if (!ntf) {
2008                 EOUT << "dil2al: Unable to create temporary file " << tmpfile << " in prepare_temporary_file()\n";
2009                 return false;
2010         }
2011         if (initstr!="") ntf << initstr;
2012         ntf.close();
2013         return true;
2014 }
void read_data_from_stream (istream & ifs, String & dstr, const char * terminate)
Definition at line 2143 of file utilities.cc.
Referenced by initialize_new_DIL_TL(), modify_DIL_group_target_dates_cmd(), and send_dil_to_DIL().
2143                                                                                  {
2144 // Reads data from a stream such as the data input stream
2145 // DIN line by line. Returns when end of file or a line
2146 // stating the terminate string is found.
2147 // *** This can be replaced by String::readtotag if LLEN=4096 is sufficient.
2148         const int LLEN = 10240;
2149         char lbuf[LLEN];
2150         while (ifs) {
2151                 ifs.getline(lbuf,LLEN);
2152                 if (ifs.eof()) break;
2153                 if (strcmp(lbuf,terminate)==0) break;
2154                 dstr = (dstr + lbuf) + '\n';
2155         }
2156 }
bool read_file_into_String (bool & isnew, String filename, String & filestr)
Definition at line 2074 of file utilities.cc.
References EOUT.
Referenced by add_TL_chunk_or_entry(), add_TL_section(), Assess_Paper_Correction_Time(), chunk_controller(), extract_paper_novelties(), extract_paper_plan_to_paper(), generate_AL_entry(), generate_modify_element_FORM_interface_DIL_entry_parameters(), get_file_in_list(), get_Paper_Plans_Section_IDs(), include_article_head_template(), include_article_section_head_template(), include_article_tail_template(), modify_element_through_FORM_interface(), pre_process_note(), Target_Access::read_cleartext_into_String(), read_file_into_String(), read_financial_notes_file(), Target_Access::read_raw_into_String(), Target_Access::read_uncompressed_into_String(), remove_AL_TC(), select_TL_DIL_refs(), and update_main_ALs().
2074                                                                             {
2075 // read the file called filename into filestr if it exists,
2076 // optionally offer to create the file if it does not exist,
2077 // or warn about the inability to open the file
2078 // returns true if file content was read into filestr
2079 // note that no file is created at this point, but the setting
2080 // of the isnew flag can be used later (e.g. by the function
2081 // write_string_to_file()) to anticipate new file creation
2082         if (read_file_into_String(filename,filestr,false)) {
2083                 isnew = false;
2084                 return true;
2085         } else {
2086                 if (offercreate) {
2087                         const int LLEN = 10;
2088                         char lbuf[LLEN];
2089                         cout << "File " << filename << "\ndoes not exist, create (y/N)? ";
2090                         cin.getline(lbuf,LLEN);
2091                         if ((lbuf[0]!='y') && (lbuf[0]!='Y')) return false;
2092                         isnew = true;
2093                         return true;
2094                 } else {
2095                         EOUT << "dil2al: Unable to open " << filename << " in read_file_into_String()\n";
2096                         return false;
2097                 }
2098         }
2099 }
bool read_file_into_String (String filename, String & filestr, bool warnnoopen = true)
Definition at line 2062 of file utilities.cc.
References EOUT, and read_file_into_String().
2062                                                                                       {
2063 // read the file called filename into the string filestr,
2064 // optionally warning about the inability to open the file
2065 // returns true if file content was read into filestr
2066         ifstream sfl(filename);
2067         if (read_file_into_String(sfl,filestr,false)) return true;
2068         else {
2069                 if (warnnoopen) EOUT << "dil2al: Unable to open " << filename << " in read_file_into_String()\n";
2070                 return false;
2071         }
2072 }
bool read_file_into_String (ifstream & sfl, String & filestr, bool warnnoopen = true)
Definition at line 2038 of file utilities.cc.
References EOUT.
2038                                                                                      {
2039 // read from an open file stream into the string filestr,
2040 // optionally warning about the inability to open the file
2041 // returns true if file content was read into filestr
2042         if (sfl) {
2043                 filestr = sfl;
2044 /*              sfl.seekg(0,ios::end); // seek to EOF
2045                 long int sflsize = sfl.tellg();
2046                 sfl.seekg(0);
2047                 char * s;
2048                 s = new char[sflsize+1];
2049                 sfl.read(s,sflsize);
2050                 s[sfl.gcount()]='\0';
2051                 filestr = s;
2052                 delete[] s;
2053                 if (sfl.gcount()!=sflsize) EOUT << "dil2al: Characters read (" << sfl.gcount() << ") does not equal expected file size (" << sflsize << ") in read_file_into_String(), continuing as is\n";
2054 */              sfl.close();
2055                 return true;
2056         } else {
2057                 if (warnnoopen) EOUT << "dil2al: Unable to open file in read_file_into_String()\n";
2058                 return false;
2059         }
2060 }
String relurl (String srcurl, String dsturl)
Definition at line 1927 of file utilities.cc.
References String::after(), String::before(), common_prefix(), String::empty(), String::from(), String::lastchar(), String::length(), String::prepend(), and String::through().
Referenced by AL_Day_Marker(), AL_Passed_Target_Dates(), extract_paper_novelties(), extract_paper_plan_to_paper(), extract_recursively(), extraction_put_figure(), generate_AL(), generate_Figures_Directory_entry(), Active_List::generate_focused_AL(), Active_List::generate_wide_AL(), get_figure_data(), make_note(), update_main_ALs(), and Detailed_Items_List::Write_to_File().
1927                                             {
1928         String tmp = common_prefix(srcurl.through('/',-1),dsturl.through('/',-1));
1929         if ((!tmp.empty()) && (tmp.lastchar()!='/')) tmp = tmp.through('/',-1);
1930         if (tmp!="") {
1931                 srcurl = srcurl.after(tmp);
1932                 dsturl = dsturl.after(tmp);
1933                 tmp = dsturl.from('#'); // for dsturl references in srcurl file
1934                 if (tmp.length()>0) {
1935                         String tmp2 = srcurl.before('#'); if (tmp2.length()==0) tmp2 = srcurl;
1936                         if (tmp2==dsturl.before('#')) return tmp;
1937                 }
1938                 while (srcurl.before('/')!="") { srcurl=srcurl.after('/'); dsturl.prepend("../"); }
1939         }
1940         return dsturl;
1941 }
String* remove_whitespace (String & str)
Definition at line 2680 of file utilities.cc.
References String::gsub().
Referenced by generate_modify_element_FORM_interface_DIL_Superiors(), and select_TL_DIL_refs().
2680                                          {
2681   str.gsub(BRXwhite," ");
2682   return &str;
2683 }
String RX_Search_Safe (String s)
Definition at line 1814 of file utilities.cc.
References String::after(), String::gsub(), and String::length().
Referenced by add_TL_chunk_or_entry(), Assess_Paper_Correction_Time(), convert_item_content_to_TeX(), extract_hierarchy_depth_decrease_to_paper(), extract_hierarchy_depth_increase_to_paper(), extract_paper_novelties(), extract_recursively(), extract_required_item_to_paper(), get_figure_data(), include_article_section_head_template(), include_article_section_tail_template(), include_protected_text(), item_content_between_range_tags(), modify_DIL_group_target_dates_cmd(), send_dil_to_DIL(), TeX_format_corrections(), and update_DIL_entry_elements().
1814                                 {
1815 // converts a regular string to that
1816 // string's match in a BigRegex search
1817         s.gsub("[","[[]");
1818         s.gsub("]","[]]");
1819         s.gsub(BigRegex("[\\.*+?$]"),"[_0]",'_');
1820         if ((s.length()>0) && (s[0]=='^')) s = "[^]" + s.after(0);
1821         return s;
1822 }
bool substring_from_line (const char * pattern, int nsub, String * dilid, const char * lbuf)
Definition at line 2180 of file utilities.cc.
References EOUT.
Referenced by add_new_to_DIL(), create_new_DIL(), send_dil_to_DIL(), and Set_Parameter().
2180                                                                                             {
2181         const int SLEN = 1024;
2182         char sbuf[SLEN];
2183         regex_t re;
2184         regmatch_t * rm;
2185         int mres;
2186         if (nsub) {
2187                 if (regcomp(&re,pattern, REG_EXTENDED) != 0) {
2188                         EOUT << "dil2al: Unable to compile regular expression in substring_from_line()\n";
2189                         return false;
2190                 }
2191                 rm = new regmatch_t[nsub];
2192                 mres = regexec(&re,lbuf, (size_t) nsub, rm, 0);
2193                 if ((mres != 0) && (mres != REG_NOMATCH)) {
2194                         EOUT << "dil2al: Internal error while matching in substring_from_line()\n";
2195                 } else {
2196                         if (!mres) {
2197                                 if (rm[nsub-1].rm_so==-1) {
2198                                         EOUT << "dil2al: Wrong number of substring matches in substring_from_line()\n";
2199                                         mres = 3;
2200                                 } else {
2201                                         for (int i=0; i<nsub; i++) {
2202                                                 strncpy(sbuf,&lbuf[rm[i].rm_so],rm[i].rm_eo-rm[i].rm_so);
2203                                                 sbuf[rm[i].rm_eo-rm[i].rm_so]='\0';
2204                                                 dilid[i] = sbuf;
2205                                         }
2206                                 }
2207                         }
2208                 }
2209                 delete[] rm;
2210                 return (mres==0);
2211         } else {
2212                 EOUT << "dil2al: nsub==0 in substring_from_line()\n";
2213                 return false;
2214         }
2215 }
time_t Time (time_t * tloc)
Definition at line 1824 of file utilities.cc.
Referenced by Active_List::Add_Day(), generate_AL(), read_financial_notes_file(), time_stamp(), and time_stamp_GM().
1824                           {
1825 // Local time() wrapper, allows emulation of different current time
1826 // returns time and sets (*tloc) to the same time if tloc!=NULL
1827         if (emulatedtime) {
1828                 if (tloc) *tloc = emulatedtime;
1829                 return emulatedtime;
1830         }
1831         return time(tloc);
1832 }
String time_stamp (const char * dateformat, time_t t = -1)
Definition at line 1834 of file utilities.cc.
References Time().
Referenced by Financial_Monthly_Root::add(), Active_List::Add_Day(), AL_Day_Marker(), AL_Passed_Target_Dates(), AL_Day::allocate(), AL_Day::allocate_with_value(), Time::caltime2local(), chunk_controller(), date_string(), dil2al_commands(), AL_Day::expand(), generate_AL(), generate_EPS_cells(), Active_List::generate_focused_AL(), generate_modify_element_FORM_interface_DIL_Superiors(), Active_List::generate_wide_AL(), get_new_DIL_ID(), include_article_tail_template(), Active_List::Initialize_AL_Length(), main(), make_note(), modify_DIL_entry_target_date(), modify_DIL_group_target_dates(), modify_DIL_group_target_dates_cmd(), modify_element_through_FORM_interface_DIL_Superiors(), Financial_Note::put(), AL_Day::set_TC_values(), time_chunk_remaining(), and Detailed_Items_List::Write_to_File().
1834                                                            {
1835 // time stamp in local time
1836         char dstr[80];
1837         if (t<0) t = Time(NULL);
1838         strftime(dstr,80,dateformat,localtime(&t));
1839         return String(dstr);
1840 }
time_t time_stamp_diff (String oldtime, String newtime)
Definition at line 1889 of file utilities.cc.
References time_stamp_time().
Referenced by decide_add_TL_chunk(), select_TL_DIL_refs(), stop_TL_chunk(), and time_chunk_remaining().
1889                                                       {
1890         return time_stamp_time(newtime) - time_stamp_time(oldtime);
1891 }
String time_stamp_GM (const char * dateformat, time_t t = -1)
Definition at line 1842 of file utilities.cc.
References Time().
Referenced by AL_Day_Marker(), Active_List::generate_focused_AL(), Active_List::Initialize_AL_Length(), and remove_AL_TC().
1842                                                              {
1843 // Greenwich Meantime time stamp
1844 // Note: Use this when expressing time differences
1845 //       such as hours and minutes since 0.
1846         char dstr[80];
1847         if (t<0) t = Time(NULL);
1848         strftime(dstr,80,dateformat,gmtime(&t));
1849         return String(dstr);
1850 }
time_t time_stamp_time (String timestr)
Definition at line 1856 of file utilities.cc.
References String::at(), and String::length().
Referenced by Active_List::Add_Day(), Detect_Form_Input(), dil2al_commands(), Detailed_Items_List::Get_Project_Data(), modify_DIL_group_target_dates_cmd(), Modify_Element(), modify_element_through_FORM_interface_DIL_Superiors(), time_stamp_diff(), and time_stamp_time_date().
1856                                        {
1857 // local time string to calendar time time_t
1858 // negative numbers are returned as they are so that
1859 // special codes can be detected
1860         struct tm ts;
1861         int tl = timestr.length();
1862         if (tl>0) if (timestr[0]=='-') return (time_t) atol((const char *) timestr);
1863         if (tl<9) return (time_t) -1;
1864         ts.tm_sec = 0;
1865         ts.tm_min = atoi((const char *) String(timestr.at(tl-2,2)));
1866         ts.tm_hour = atoi((const char *) String(timestr.at(tl-4,2)));
1867         ts.tm_mday = atoi((const char *) String(timestr.at(tl-6,2)));
1868         ts.tm_mon = atoi((const char *) String(timestr.at(tl-8,2)))-1;
1869         ts.tm_year = atoi((const char *) String(timestr.at(0,tl-8)))-1900;
1870         ts.tm_wday = 0;
1871         ts.tm_yday = 0;
1872         ts.tm_isdst = -1; // computed by mktime since indicated "unknown" here
1873         return mktime(&ts);
1874 }
time_t time_stamp_time_date (String timestr)
Definition at line 1882 of file utilities.cc.
References String::before(), String::length(), and time_stamp_time().
Referenced by Active_List::Add_Day(), financial_notes(), generate_EPS_cells(), Financial_Note::get(), and Active_List::Initialize_AL_Length().
1882                                             {
1883 // local time string %Y%m%d%H%M set to 00:00 time of
1884 // day to calendar time
1885         int tl = timestr.length() - 4;
1886         return time_stamp_time(String(timestr.before(tl))+"0000");
1887 }
time_t time_stamp_time_of_day (String timestr)
Definition at line 1876 of file utilities.cc.
References String::at(), String::chars(), and String::length().
Referenced by generate_EPS_cells(), Get_Worked_Estimate(), Active_List::Initialize_AL_Length(), and remove_AL_TC().
1876                                               {
1877         int tl = timestr.length();
1878         String h(timestr.at(tl-4,2)),m(timestr.at(tl-2,2));
1879         return ((((time_t) atoi(h.chars()))*60)+((time_t) atoi(m.chars())))*60;
1880 }
bool Unlock_File (String lockfile)
Definition at line 1408 of file utilities.cc.
References EOUT.
Referenced by Detailed_Items_List::Read_from_Binary_Cache(), Detailed_Items_List::Read_Topical_from_Binary_Cache(), Detailed_Items_List::Write_to_Binary_Cache(), and Detailed_Items_List::Write_Topical_to_Binary_Cache().
1408                                   {
1409   if (unlink(lockfile)<0) {
1410     EOUT << "dil2al: Unable to remove lock file " << lockfile << " in Unlock_File(), continuing as is\n";
1411     return false;
1412   }
1413   return true;
1414 }
String URI_unescape (String escapedURI)
Definition at line 2644 of file utilities.cc.
References String::length().
Referenced by extract_DIL_IDs_from_form(), search_FORM_cmd(), and Tabbed_FORM_DIL_Hierarchy_full().
2644                                        {
2645 // convert URI strings with escaped characters to regular character strings
2646         String s; char c; int d1,d2;
2647         for (int i = 0; i<escapedURI.length(); i++) {
2648                 c = escapedURI[i];
2649                 if (c=='%') {
2650                         i++; c = escapedURI[i];
2651                         if ((c>='0') && (c<='9')) d1 = (int) (c - '0');
2652                         else if ((c>='A') && (c<='F')) d1 = ((int) (c - 'A')) + 10;
2653                         else d1 = ((int) (c - 'a')) + 10;
2654                         i++; c = escapedURI[i];
2655                         if ((c>='0') && (c<='9')) d2 = (int) (c - '0');
2656                         else if ((c>='A') && (c<='F')) d2 = ((int) (c - 'A')) + 10;
2657                         else d2 = ((int) (c - 'a')) + 10;
2658                         d1 *=16; d1 += d2;
2659                         c = (char) d1;
2660                 }
2661                 s += c;
2662         }
2663         return s;
2664 }
bool write_file_from_String (String filename, const String & filestr, String message, bool isnew = false)
Definition at line 2116 of file utilities.cc.
References backup_and_rename(), String::empty(), EOUT, and VOUT.
Referenced by add_TL_chunk_or_entry(), add_TL_section(), chunk_controller(), DIL_Hierarchy_cmd(), extract_DIL_IDs_from_form(), generate_AL(), Active_List::generate_focused_AL(), Active_List::generate_wide_AL(), Target_Access::make_local_copy_of_directory(), post_process_note(), remove_AL_TC(), search(), Tabbed_DIL_Hierarchy(), Tabbed_FORM_DIL_Hierarchy(), Tabbed_HTML_DIL_Hierarchy(), update_DIL_entry_elements(), update_main_ALs(), write_financial_notes_file(), and Detailed_Items_List::Write_to_File().
2116                                                                                                          {
2117 // Write a file from string content, with automatic backup of
2118 // a previous version (if one exists).
2119 #ifdef DEBUG
2120         bool b = (filename==taskloghead);
2121         if (b) cout << '+';
2122 #endif
2123         String newfilename = filename;
2124         if (!isnew) newfilename += ".new";
2125         ofstream ntl(newfilename);
2126         if (!ntl) {
2127                 EOUT << "dil2al: Unable to create " << newfilename << " in write_file_from_String()\n";
2128                 return false;
2129         }
2130         ntl << filestr;
2131         ntl.close();
2132 #ifdef DEBUG
2133         if (b) cout << '+';
2134 #endif
2135         if (isnew) { if (verbose && (!message.empty())) VOUT << message << " initialized as " << filename << '\n'; }
2136         else if (!backup_and_rename(filename,message)) return false;
2137 #ifdef DEBUG
2138         if (b) cout << "+\n";
2139 #endif
2140         return true;
2141 }
Variable Documentation
const char plan_entry_type_strings[NUM_PLAN_ENTRY_TYPES][10] = {PLAN_ENTRY_STRING_ACTION,PLAN_ENTRY_STRING_GOAL,PLAN_ENTRY_STRING_OBJECTIVE,PLAN_ENTRY_STRING_OUTCOME,PLAN_ENTRY_STRING_VARIABLE}
Definition at line 23 of file utilities.cc.
Referenced by DIL_entry_content::Is_Plan_Entry().